### ISSUE TITLE
OutOfMemoryError thrown after loading tons of pictures in RecyclerView

### ISSUE THREAD

**Issue by imlunacat** [bumptech/glide#1002]
Hello,
  I tried use Glide to display internet picture inside RecyclerView. After lot of picture is loaded into RecyclerView. PriorityExecutor throws OutOfMemoryError and following picture cannot be loaded ;(

  Here is snippet of inside ViewHolder's bindView:
```java
 Glide.with(itemView.getContext())
    .load(url)
    .listener(sRequestListener) // sRequestListener is a simple logger
    .placeholder(placeHolder)
    .error(placeHolder)
    .into(new CustomViewTarget(itemView.imageview));
    // CustomViewTarget is an implementation of ImageViewTarget to help set/get Request
```

  ViewHolder:
```xml
<RelativeLayout
      ....>
      <SquareImageView
        android:id="@+id/imageview"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:scaleType="fitCenter"
        android:src="@drawable/bg_default" />
    <TextView ....
   ....
</RelativeLayout>
```
  Implementation of CustomViewTarget
```java
// extends com.bumptech.glide.request.target.ImageViewTarget
public class CustomViewTarget extends ImageViewTarget<GlideDrawable> {
    private static final int GLIDE_REQUEST_TAG_ID = -1;
    public NYImageViewTarget(ImageView view) {
        super(view);
    }

    @Override
    protected void setResource(GlideDrawable resource) {
        view.setImageDrawable(resource);
    }

    @Override
    public void setRequest(Request request) {
        view.setTag(GLIDE_REQUEST_TAG_ID, request);
    }

    @Override
    public Request getRequest(){
        Object tag = view.getTag(GLIDE_REQUEST_TAG_ID);
        if (tag != null) {
            if (tag instanceof Request) {
                return (Request) tag;
            } else {
                throw new IllegalArgumentException("tag is not instance of Request");
            }
        }

        return null;
    }
}
```
  SquareImageView is child of ImageView. It overrides onMeasure of ImageView
```java
    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        float padding = (float) (getPaddingLeft() + getPaddingRight());
        int widthSize = Math.round(MeasureSpec.getSize(widthMeasureSpec) - padding);
        setMeasuredDimension(widthSize, widthSize);
    }
```

sRequestListener is a simple logger, log would be remove in release.
```java
public class CustomRequestListener<T, R> implements RequestListener<T, R> {
    private static final String TAG = CustomRequestListener.class.getSimpleName();
    public CustomRequestListener(){
    }
    @Override
    public boolean onException(Exception e, T model, Target<R> target, boolean isFirstResource) {
        Log.d(TAG, String.format(Locale.ROOT, "onException(%s, %s, %s, %s)", e, model, target, isFirstResource), e);
        return false;
    }

    @Override
    public boolean onResourceReady(R resource, T model, Target<R> target, boolean isFromMemoryCache,
            boolean isFirstResource) {
        Log.d(TAG, String.format(Locale.ROOT,
                "onResourceReady(%s, %s, %s, %s, %s)", resource, model, target, isFromMemoryCache, isFirstResource));
        return false;
    }
}
```
  Glide version: 3.7.0 

  Sorry for the long text of code ;( 

  Is it possible to avoid this situation? Thank you.

**Comment by TWiStErRob** [comment]
The more (relevant!) code, the better, less questions to ask :) Sadly on first look this all seems ok.
Is `Glide.with` inside an `if` or `switch` in `bindView`? Do you have multiple view types?
Is there a particular reason why `CustomViewTarget` is implemented?
What does `sRequestListener` do? Does it capture the resource?

The request handling part looks correct (code copied from `ViewTarget` I guess), but you could just use the built-in `ViewTarget.setTagId(GLIDE_REQUEST_TAG_ID)` (preferably called in `Application.onCreate`) to achieve the same result. Can you share the rest of the class (if any)?
The problem might be that you don't handle the view sizing (not sure if you extended `ViewTarget` or `SimpleTarget`) and some of the images are too big to be loaded fully in memory.

**Comment by imlunacat** [comment]
Thank you @TWiStErRob ,

`Glide.with` is inside  `onBindViewHolder` of a `RecyclerView.Adapter` and this adapter do not have multiple view-type.

Missing code is in following:

Purpose of CustomViewTarget is handle get/set request
```java
// extends com.bumptech.glide.request.target.ImageViewTarget
public class CustomViewTarget extends ImageViewTarget<GlideDrawable> {
    private static final int GLIDE_REQUEST_TAG_ID = -1;
    public NYImageViewTarget(ImageView view) {
        super(view);
    }

    @Override
    protected void setResource(GlideDrawable resource) {
        view.setImageDrawable(resource);
    }

    @Override
    public void setRequest(Request request) {
        view.setTag(GLIDE_REQUEST_TAG_ID, request);
    }

    @Override
    public Request getRequest(){
        Object tag = view.getTag(NY_GLIDE_REQUEST_TAG_ID);
        if (tag != null) {
            if (tag instanceof Request) {
                return (Request) tag;
            } else {
                throw new IllegalArgumentException("tag is not instance of Request");
            }
        }

        return null;
    }
}
```

sRequestListener is just a simple logger. Logging would be removed in release.
```java
public class CustomRequestListener<T, R> implements RequestListener<T, R> {
    private static final String TAG = CustomRequestListener.class.getSimpleName();
    public CustomRequestListener(){
    }
    @Override
    public boolean onException(Exception e, T model, Target<R> target, boolean isFirstResource) {
        Log.d(TAG, String.format(Locale.ROOT, "onException(%s, %s, %s, %s)", e, model, target, isFirstResource), e);
        return false;
    }

    @Override
    public boolean onResourceReady(R resource, T model, Target<R> target, boolean isFromMemoryCache,
            boolean isFirstResource) {
        Log.d(TAG, String.format(Locale.ROOT,
                "onResourceReady(%s, %s, %s, %s, %s)", resource, model, target, isFromMemoryCache, isFirstResource));
        return false;
    }
}
```

I will follow your suggestion, use ```ViewTarget.setTagId``` and experiment it ;)

P.S. What should I know about Glide If multiple ViewType is supported in ```RecyclerView``` ?

**Comment by TWiStErRob** [comment]
I still don't see anything wrong, except a small thing: I don't know if this test would pass:
```java
view.setTag(-1, data);
Object retrieved = view.getTag(-1);
assertSame(data, retrieved);
```
Try it with a real ID as detailed in http://stackoverflow.com/a/35096552/253468

@sjudd do you see anything?

**Comment by imlunacat** [comment]
Hello @TWiStErRob ,
```java
view.setTag(-1, data);
Object retrieved = view.getTag(-1);
assertSame(data, retrieved);
```
will pass. 

Also, I tried ```ViewTarget.setTagId(R.id.glide_tag);``` in http://stackoverflow.com/a/35096552/253468,
but ```OutOfMemory```still occurs if ```RecyclerView``` load ton of pictures ;(

**Comment by TWiStErRob** [comment]
Hmm, when you said ton of pictures I assumed that you scroll a lot down and eventually it breaks, is this true? If not, do you display a grid of, say 10x10 images? Can you please clarify what you mean by "ton" and what the user is doing when this happens?

**Comment by peterbetos** [comment]
This is still happening when I download tons of images having 800 x 400 pixel dimensions

**Comment by TWiStErRob** [comment]
We can only progress once someone defines the problem, I asked several questions in my previous comment. Also, can either of you share a screenshot please?

**Comment by imlunacat** [comment]
Hello,
  Sorry my late reply ;(
  Basically, I implemented a `RecyclerView` with load more function.

  Here is procedure code:
 ```java
public void onCreate() {
    recyclerView.setLayoutManager(new GridLayoutManager(getActivity(), 2));
    recyclerView.addOnScrollLister( ...
        // inside of new OnScrollListener
        @Override
        public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
           ....
           if ( reachBottom ) {
               API.loadMore(); // call apiCallBack if API come back
           }
        }
    );
    mRecyclerAdapter = new RecyclerView.Adapter();
    recyclerView.setAdapter(mRecyclerAdapter);

}
void apiCallBack(ArrayList<Pic> pic){
    mRecyclerAdapter.addItems(pic);
    mRecyclerAdapter.notifyDataSetChanged();
}
```
  As you can see, it a simple 2-column `RecyclerView` with load more function :)
  `OutOfMemory` exception usually thrown after I load 500~600 pictures.

**Comment by TWiStErRob** [comment]
Ah, nothing stands out that can cause it...

Can you try scrolling until it breaks a few times and then take a heap dump and try to see what's keeping the images? See https://github.com/bumptech/glide/issues/679#issuecomment-148194654

Probably unrelated, but worth a try: RecyclerView has awesome facilities to notify that only part of the data is changed. You could remove `notifyDataSetChanged` and call something like [`notifyItemRangeInserted(oldSize, toAdd.size())`](http://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#notifyItemRangeInserted(int, int)) inside the `addItems` method.

**Comment by peterbetos** [comment]
@imlunacat Is your RecyclerView inside a ScrollView (i.e. maybe via modifying the class behavior)? It seems that AdapterViews inside a Scrollview is not performing a recycle and it attempts to render all list items in the scrollview container as heavy as possible. I checked if my Glide logs on the ViewHolder if it's rendering the list items one at a time and it doesn't; it shows the logs on all the list items. That happens on mine when I had the ListView inside ScrollView.

**Comment by imlunacat** [comment]
Hello @peterbetos, `ReyclerView` do not insides ```ScrollView``` :(, It insides a [SwipeRefreshLayout] (http://developer.android.com/intl/zh-tw/reference/android/support/v4/widget/SwipeRefreshLayout.html)


Here is memory dump:
```
03-07 18:10:50.985 24931-25332/com.demoshop E/dalvikvm-heap: Out of memory on a 2073616-byte allocation.
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm: "fifo-pool-thread-1" prio=5 tid=44 RUNNABLE
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0x41d43988 self=0x13c89f0
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:   | sysTid=25332 nice=10 sched=0/0 cgrp=bg_non_interactive handle=23245376
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:   | schedstat=( 0 0 0 ) utm=7262 stm=473 core=0
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:     at android.graphics.Bitmap.nativeCreate(Native Method)
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:     at android.graphics.Bitmap.createBitmap(Bitmap.java:605)
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:     at android.graphics.Bitmap.createBitmap(Bitmap.java:585)
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:     at com.bumptech.glide.load.resource.bitmap.TransformationUtils.fitCenter(TransformationUtils.java:112)
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:     at com.bumptech.glide.load.resource.bitmap.FitCenter.transform(FitCenter.java:24)
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:     at com.bumptech.glide.load.resource.bitmap.BitmapTransformation.transform(BitmapTransformation.java:54)
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperTransformation.transform(GifBitmapWrapperTransformation.java:34)
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:     at com.bumptech.glide.load.engine.DecodeJob.transform(DecodeJob.java:236)
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:     at com.bumptech.glide.load.engine.DecodeJob.transformEncodeAndTranscode(DecodeJob.java:139)
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:129)
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:     at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:     at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:     at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:     at java.lang.Thread.run(Thread.java:856)
03-07 18:10:50.985 24931-25332/com.demoshop I/dalvikvm:     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
03-07 18:10:51.015 24931-25332/com.demoshop E/PriorityExecutor: Request threw uncaught throwable
                                                                       java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
                                                                           at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:223)
                                                                           at java.util.concurrent.FutureTask.get(FutureTask.java:82)
                                                                           at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1084)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                                           at java.lang.Thread.run(Thread.java:856)
                                                                           at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
                                                                        Caused by: java.lang.OutOfMemoryError
                                                                           at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                           at android.graphics.Bitmap.createBitmap(Bitmap.java:605)
                                                                           at android.graphics.Bitmap.createBitmap(Bitmap.java:585)
                                                                           at com.bumptech.glide.load.resource.bitmap.TransformationUtils.fitCenter(TransformationUtils.java:112)
                                                                           at com.bumptech.glide.load.resource.bitmap.FitCenter.transform(FitCenter.java:24)
                                                                           at com.bumptech.glide.load.resource.bitmap.BitmapTransformation.transform(BitmapTransformation.java:54)
                                                                           at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperTransformation.transform(GifBitmapWrapperTransformation.java:34)
                                                                           at com.bumptech.glide.load.engine.DecodeJob.transform(DecodeJob.java:236)
                                                                           at com.bumptech.glide.load.engine.DecodeJob.transformEncodeAndTranscode(DecodeJob.java:139)
                                                                           at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:129)
                                                                           at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
                                                                           at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
                                                                           at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
                                                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
                                                                           at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
                                                                           at java.lang.Thread.run(Thread.java:856) 
                                                                           at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118) 
```

**Comment by TWiStErRob** [comment]
That's an OOM stack trace which bears no more information than to say "out of memory", read the articles I linked to see what heap dump is and how to handle them.

**Comment by imlunacat** [comment]
Hello @TWiStErRob ,
  I guess I missing understanding what you talk about ;( I will analysis heap dump and reply in this thread if I find something

**Comment by TWiStErRob** [comment]
Closing this now, feel free to reopen if you can provide more information and want to continue the investigation.

**Comment by AMK9978** [comment]
I'm searching about that and I think there is now way to get rid of this problem except clear the related array list and try to load time by time.
Because we have a full RAM and we must clear it out.we can do it on low memory.
Any way else?
