### ISSUE TITLE
IOException occured, showing 'Unable to put to disk cache'

### ISSUE THREAD

**Issue by licheedev** [bumptech/glide#1086]
**Glide Version**: 3.7.0
**Integration libraries**: okhttp 2.4.0
**Device/Android Version**: xiaomi 4 (Android 6.0.1)
**Issue details / Repro steps / Use case background**: 

This is the first time that I have encountered this problem.
All views using Glide fail to load images any more.
When the view trys to load a image, the logcat prints some wrong message as below.

Then I killed my application and ran it again, Glide worked well as usual.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
public class MyGlideModule implements GlideModule {
    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        ViewTarget.setTagId(R.id.glide_tag_id);
        builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_8888);
    }

    @Override
    public void registerComponents(Context context, Glide glide) {
        glide.register(ImageFid.class, InputStream.class, new FidLoader.Factory());
        glide.register(GlideUrl.class, InputStream.class, new OkHttpUrlLoader.Factory());
        glide.register(MsgFid.class,InputStream.class,new MsgFidLoader.Factory());
    }
}
```
using the default DiskLruCache

**Stack trace / LogCat**:
```ruby
22:38.366 21283-22334/com.company.appname W/DiskLruCacheWrapper: Unable to put to disk cache
 java.io.IOException: write failed: EBADF (Bad file number)
     at libcore.io.IoBridge.write(IoBridge.java:502)
     at java.io.FileOutputStream.write(FileOutputStream.java:186)
     at java.io.OutputStreamWriter.flushBytes(OutputStreamWriter.java:167)
     at java.io.OutputStreamWriter.convert(OutputStreamWriter.java:181)
     at java.io.OutputStreamWriter.write(OutputStreamWriter.java:266)
     at java.io.BufferedWriter.flushInternal(BufferedWriter.java:139)
     at java.io.BufferedWriter.flush(BufferedWriter.java:123)
     at com.bumptech.glide.disklrucache.DiskLruCache.edit(DiskLruCache.java:466)
     at com.bumptech.glide.disklrucache.DiskLruCache.edit(DiskLruCache.java:441)
     at com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper.put(DiskLruCacheWrapper.java:93)
     at com.bumptech.glide.load.engine.DecodeJob.cacheAndDecodeSourceData(DecodeJob.java:201)
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:187)
     at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
     at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
     at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
     at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)
     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
  Caused by: android.system.ErrnoException: write failed: EBADF (Bad file number)
     at libcore.io.Posix.writeBytes(Native Method)
     at libcore.io.Posix.write(Posix.java:258)
     at libcore.io.BlockGuardOs.write(BlockGuardOs.java:313)
     at libcore.io.IoBridge.write(IoBridge.java:497)
     at java.io.FileOutputStream.write(FileOutputStream.java:186) 
     at java.io.OutputStreamWriter.flushBytes(OutputStreamWriter.java:167) 
     at java.io.OutputStreamWriter.convert(OutputStreamWriter.java:181) 
     at java.io.OutputStreamWriter.write(OutputStreamWriter.java:266) 
     at java.io.BufferedWriter.flushInternal(BufferedWriter.java:139) 
     at java.io.BufferedWriter.flush(BufferedWriter.java:123) 
     at com.bumptech.glide.disklrucache.DiskLruCache.edit(DiskLruCache.java:466) 
     at com.bumptech.glide.disklrucache.DiskLruCache.edit(DiskLruCache.java:441) 
     at com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper.put(DiskLruCacheWrapper.java:93) 
     at com.bumptech.glide.load.engine.DecodeJob.cacheAndDecodeSourceData(DecodeJob.java:201) 
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:187) 
     at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177) 
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128) 
     at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122) 
     at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101) 
     at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58) 
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
     at java.lang.Thread.run(Thread.java:818) 
     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118) 
```

**Comment by TWiStErRob** [comment]
Hmm, never seen this before. Quick SO search points out permission problems, but I guess you must have those because you are using Glide for a long time.

The only thing I can think of is something like a synchronization issue, but all accesses to the disk cache journal is synchronized. Maybe there was an exception before this, that holds a clue, but it's likely gone from LogCat by this time. It could have been a disk full or similar error which left the diskcache in an inconsistent state.

@sjudd any ideas?

**Comment by TWiStErRob** [comment]
@licheedev try to get a full logcat dump from your device as soon as possible:
```shell
adb logcat -d -v long > github_1086.log
```

**Comment by sjudd** [comment]
This might be worth reporting at DiskLruCache, it doesn't look like an error in Glide: https://github.com/JakeWharton/DiskLruCache
