### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot draw recycled bitmaps

### ISSUE THREAD

**Issue by 1109993488** [bumptech/glide#1109]
```ruby
java.lang.IllegalArgumentException: Cannot draw recycled bitmaps
	at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:791)
	at android.view.GLES20RecordingCanvas.drawBitmap(GLES20RecordingCanvas.java:118)
	at com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable.draw(GlideBitmapDrawable.java:101)
	at com.bumptech.glide.request.target.SquaringDrawable.draw(SquaringDrawable.java:151)
	at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:216)
	at android.widget.ImageView.onDraw(ImageView.java:967)
	at android.view.View.draw(View.java:13803)
	at android.view.View.getDisplayList(View.java:12741)
	at android.view.View.getDisplayList(View.java:12785)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3001)
	at android.view.View.getDisplayList(View.java:12670)
	at android.view.View.getDisplayList(View.java:12785)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3001)
	at android.view.View.getDisplayList(View.java:12670)
	at android.view.View.getDisplayList(View.java:12785)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3001)
	at android.view.View.getDisplayList(View.java:12670)
	at android.view.View.getDisplayList(View.java:12785)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3001)
	at android.view.View.getDisplayList(View.java:12670)
	at android.view.View.getDisplayList(View.java:12785)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3001)
	at android.view.View.getDisplayList(View.java:12670)
	at android.view.View.getDisplayList(View.java:12785)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3001)
	at android.view.View.getDisplayList(View.java:12670)
	at android.view.View.getDisplayList(View.java:12785)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3001)
	at android.view.View.getDisplayList(View.java:12670)
	at android.view.View.getDisplayList(View.java:12785)
	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1249)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2480)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2340)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2142)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4879)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
	at android.view.Choreographer.doCallbacks(Choreographer.java:579)
	at android.view.Choreographer.doFrame(Choreographer.java:548)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5297)
	at java.lang.reflect.Method.invokeNative(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by TWiStErRob** [comment]
This is most likely a user error, check for custom transformations (especially ones that are designed for Picasso), decoders, transcoders, or `listener/target.onResourceReady(Bitmap, ...` where you save the Bitmap reference or pass it to an outside party. Doing a usage search on `Bitmap.recycle` and `ImageView.getDrawable` can also help.

Bitmap's shouldn't be recycled most of the time, Glide does do it internally, when it knows it's safe. Please share the results of these checks.

**Comment by 1109993488** [comment]
@Override
    protected Bitmap transform(BitmapPool pool, Bitmap source, int outWidth, int outHeight) {
        return ImageUtils.getCircularBitmapImage(source);
    }
    public static Bitmap getCircularBitmapImage(Bitmap source) {
        int size = Math.min(source.getWidth(), source.getHeight());
        int x = (source.getWidth() - size) / 2;
        int y = (source.getHeight() - size) / 2;
        Bitmap squaredBitmap = Bitmap.createBitmap(source, x, y, size, size);
        if (squaredBitmap != source && !source.isRecycled()) {
            source.recycle();
        }
        Paint paint = new Paint();
        paint.setAntiAlias(true);
        paint.setColor(Color.WHITE);
        Bitmap bitmap = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_4444);
        Canvas canvas = new Canvas(bitmap);
        BitmapShader shader = new BitmapShader(squaredBitmap, BitmapShader.TileMode.CLAMP, BitmapShader.TileMode.CLAMP);
        paint.setShader(shader);
        float r = size / 2f;
        canvas.drawCircle(r, r, r, paint);
        return bitmap;
    }

This is probably the wrong place to call source.recycle.

**Comment by TWiStErRob** [comment]
Yes it is, check out http://stackoverflow.com/a/25806229/253468 (most notably my edits and comments on this answer.)

**Comment by 1109993488** [comment]
Thank you

**Comment by TWiStErRob** [comment]
Did removal of that line help the exception?

**Comment by 1109993488** [comment]
Errors to the statistical background, change https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/resource/bitmap/TransformationUtils.java circleCrop () and error does not appear
