### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by BaeDongsun** [bumptech/glide#1110]
**Glide Version**: 3.7.0, 

**Integration libraries**: None

**Device/Android Version**: Galaxy S3 / Android 4.0.3

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(this).load(selectedItem.getImage()).into(ivImage);
```

**Layout XML**:
```xml
<ImageView
                    android:id="@+id/sd_image"
                    android:layout_width="140dp"
                    android:layout_height="fill_parent" />
```

**Stack trace / LogCat**:
```
[2016-04-06 16:43:35 - ILGOMobile] Warning: com.bumptech.glide.load.MultiTransformation: can't find referenced class java.lang.SafeVarargs
[2016-04-06 16:43:35 - ILGOMobile] Warning: com.bumptech.glide.load.engine.bitmap_recycle.SizeConfigStrategy: can't find referenced method 'void reconfigure(int,int,android.graphics.Bitmap$Config)' in class android.graphics.Bitmap
[2016-04-06 16:43:35 - ILGOMobile] Warning: com.bumptech.glide.load.engine.bitmap_recycle.SizeStrategy: can't find referenced method 'void reconfigure(int,int,android.graphics.Bitmap$Config)' in class android.graphics.Bitmap
[2016-04-06 16:43:35 - ILGOMobile] Warning: com.bumptech.glide.load.engine.cache.MemorySizeCalculator: can't find referenced method 'boolean isLowRamDevice()' in class android.app.ActivityManager
[2016-04-06 16:43:35 - ILGOMobile] Warning: com.bumptech.glide.manager.RequestManagerFragment: can't find referenced method 'android.app.Fragment getParentFragment()' in class com.bumptech.glide.manager.RequestManagerFragment
[2016-04-06 16:43:35 - ILGOMobile] Warning: com.bumptech.glide.manager.RequestManagerFragment: can't find referenced method 'android.app.Fragment getParentFragment()' in class android.app.Fragment
[2016-04-06 16:43:35 - ILGOMobile] Warning: com.bumptech.glide.manager.RequestManagerRetriever: can't find referenced method 'boolean isDestroyed()' in class android.app.Activity
[2016-04-06 16:43:35 - ILGOMobile] Warning: com.bumptech.glide.manager.RequestManagerRetriever: can't find referenced method 'android.app.FragmentManager getChildFragmentManager()' in class android.app.Fragment
[2016-04-06 16:43:35 - ILGOMobile] Warning: com.bumptech.glide.request.target.SquaringDrawable: can't find referenced method 'int getAlpha()' in class com.bumptech.glide.load.resource.drawable.GlideDrawable
[2016-04-06 16:43:35 - ILGOMobile] Warning: com.bumptech.glide.util.LogTime: can't find referenced method 'long elapsedRealtimeNanos()' in class android.os.SystemClock
[2016-04-06 16:43:35 - ILGOMobile] Warning: com.bumptech.glide.util.Util: can't find referenced method 'int getAllocationByteCount()' in class android.graphics.Bitmap
[2016-04-06 16:43:35 - ILGOMobile]       You should check if you need to specify additional program jars.
[2016-04-06 16:43:35 - ILGOMobile] Warning: there were 1 unresolved references to classes or interfaces.
[2016-04-06 16:43:35 - ILGOMobile]          You may need to specify additional library jars (using '-libraryjars').
[2016-04-06 16:43:35 - ILGOMobile] Warning: there were 10 unresolved references to program class members.
[2016-04-06 16:43:35 - ILGOMobile]          Your input classes appear to be inconsistent.
[2016-04-06 16:43:35 - ILGOMobile]          You may need to recompile them and try again.
[2016-04-06 16:43:35 - ILGOMobile]          Alternatively, you may have to specify the option 
[2016-04-06 16:43:35 - ILGOMobile]          '-dontskipnonpubliclibraryclassmembers'.
[2016-04-06 16:43:35 - ILGOMobile] java.io.IOException: Please correct the above warnings first.
[2016-04-06 16:43:35 - ILGOMobile] 	at proguard.Initializer.execute(Initializer.java:321)
[2016-04-06 16:43:35 - ILGOMobile] 	at proguard.ProGuard.initialize(ProGuard.java:211)
[2016-04-06 16:43:35 - ILGOMobile] 	at proguard.ProGuard.execute(ProGuard.java:86)
[2016-04-06 16:43:35 - ILGOMobile] 	at proguard.ProGuard.main(ProGuard.java:492)

```

In the USB debugging mode, there is no problem.
But when I run the Export to create the apk file, an error occurs.

java.lang.SafeVarargs class Added in API level 19(4.4.2)
According to your words, Glide requires a minimum API level of 10.

I chose to Glide because the minimum API level.

What is the problem?

**Comment by TWiStErRob** [comment]
It should be safe to use Glide on lower API, but your targetSdk must be 19+. This means that when you compile it uses the new classes for reference, but it'll be able to run on older devices as well, as down as you set your minSdk.

You can either increase your target level; or add `-dontwarn com.bumptech.glide.**` to your proguard file, because these method/class references should be protected by `SDK_INT` checks. They must be part of the class file in order to be able to use them on newer devices.

**Comment by BaeDongsun** [comment]
I use Eclipse.
And my AndroidManifest.xml in
<uses-sdk     android:minSdkVersion="16"
        android:targetSdkVersion="21" />

**Comment by TWiStErRob** [comment]
I think there's a properties file too, what's in that?

**Comment by BaeDongsun** [comment]
project.properties file??

**Comment by TWiStErRob** [comment]
Think so, t'was ye good ol' days I used Eclipse :)
There should be one line in it (and a lot of comment)

**Comment by BaeDongsun** [comment]
project.properties in

proguard.config=${sdk.dir}/tools/proguard/proguard-android.txt:proguard-project.txt
# Project target.
target=android-15
android.library.reference.1=..\\google-play-services_lib

Changing the target with 19+ also possible to use the device in the 4.0.3 version?

**Comment by TWiStErRob** [comment]
That's the the one, change it to:
```properties
target=android-21
```
And wait/refresh/restart (not sure what's needed).

In Gradle there are 3 values: target, min, compile.
Min is the easiest, it's the oldest device it can run on. Target in XML (=target in gradle) should be what you tested on, and it also triggers compatibilty emulation on newer devices in case people depend on behaviour/bugs only existed in the old platform. Target in properties (=compile in gradle) is the jar and resources used when compiling code, it comes out really prevalent when using the latest support v7 or design lib.

Increasing the target in properties should give you more classes and methods, but it'll also warn when you use them, because of your min level, ViewCompat, ContextCompat in support v4 help with this.
This will get rid of the warnings in proguard hopefully. Also if your using the latest and greatest (SDK, and device), your app will still run as low as your minSdk if you put the correct VERSION_CODES checks into your code.
So yes, it will be compatible. Notice that your compile level is lower than the minimum, it's weird it works that way too :)

The best is always to test this out, just change, compile, export, run on 4.0.3 and see what happens.

See also http://stackoverflow.com/q/26694108/253468 and similar questions.

**Comment by BaeDongsun** [comment]
Thank you very much!!!

**Comment by TWiStErRob** [comment]
You're welcome.
I'm assuming it worked, feel free to ask more if you still have troubles.

**Comment by sonaypsi** [comment]
How can I Use this library in Android Eclipse IDE

**Comment by TWiStErRob** [comment]
From project homepage (https://github.com/bumptech/glide/) go to Releases tab and download the `glide-<version>.jar` file. Put that file into your project's `libs` folder and let ADT do its magic: it should appear under "Private libraries". (For more see [SO](http://stackoverflow.com/a/3643015/253468)).
You can also download the sources jar and attach it the usual way, so you get variable names in methods and documentation.

Note: You must have support-v4 as dependency.

> Note: If you have been using Eclipse with ADT, be aware that Android Studio is now the official IDE for Android, so you should migrate to Android Studio to receive all the latest IDE updates. -- [android.com](http://developer.android.com/tools/sdk/eclipse-adt.html)
