### ISSUE TITLE
Full Size jpeg never finishes loading

### ISSUE THREAD

**Issue by frowing** [bumptech/glide#1128]
**Glide Version**:
Using Glide `3.7.0`

**Integration libraries**:

**Device/Android Version**:
Samsung Galaxy Note II (SGH-I317) / 4.1.2

**Issue details / Repro steps / Use case background**: 
Trying to download a jpeg image in full size.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```
    Bitmap map = Glide.
            with(appContext).
            load("https://media.lonelyplanet.com/mobile/flagship/transit-maps/357640.jpg").
            asBitmap().
            into(-1, -1).
            get();
```

**Stack trace / LogCat**:
No error at all, but it never finishes. Debugged it and found that `BitmapFactory.decodeStream()` on `Downsampler.java` returns `NULL`

**Comment by TWiStErRob** [comment]
Did you mean `.into(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)`?
Debug what options are passed into `BitmapFactory`, something is likely wrong there, e.g. `inSampleSize`.

**Comment by TWiStErRob** [comment]
> but it never finishes.

It finishes with `Target.onLoadFailed(null, null)`. First null: no exception, second null no `.error()` set.

See also https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener

**Comment by frowing** [comment]
@TWiStErRob It seems to be a OOM error. I'm trying with tweaking different settings like `format(DecodeFormat.PREFER_RGB_565)` Any other suggestions?

This is the stack trace: 
```
04-12 04:36:40.605 7308-7902/com.lonelyplanet.guides E/PriorityExecutor: Request threw uncaught throwable
                                                                         java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
                                                                             at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:223)
                                                                             at java.util.concurrent.FutureTask.get(FutureTask.java:82)
                                                                             at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1084)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                                             at java.lang.Thread.run(Thread.java:856)
                                                                             at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
                                                                          Caused by: java.lang.OutOfMemoryError
                                                                             at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
                                                                             at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:655)
                                                                             at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:329)
                                                                             at com.bumptech.glide.load.resource.bitmap.Downsampler.downsampleWithSize(Downsampler.java:220)
                                                                             at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:153)
                                                                             at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:50)
                                                                             at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
                                                                             at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:39)
                                                                             at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)
                                                                             at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:190)
                                                                             at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
                                                                             at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
                                                                             at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
                                                                             at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
                                                                             at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
                                                                             at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
                                                                             at java.lang.Thread.run(Thread.java:856) 
                                                                             at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118) 
```

**Comment by TWiStErRob** [comment]
If you want to display a pannable/zoomable map I would suggest looking into a library that specializes in that, e.g. using `BitmapRegionDecoder`. Glide is meant for displaying images in whole, fast, but the source you're trying is just too big. It's 90MB of raw ARGB pixels in memory, even if you were able to load it, the Android system would fail to display it in a regular ImageView, because of maximum OpenGL texture size is usually way below 4613x5000.

**Comment by frowing** [comment]
@TWiStErRob thank you sir! It seems like the images were unnecessarily large so reducing their size works fine. Your proposed solution is something that we will have to implement longer term, for sure.

**Comment by TWiStErRob** [comment]
Tip: if it's not pannable/zoomable then don't use `override` Glide knows the most effeftive size, regardless of input.
