### ISSUE TITLE
glide  on  android 6.0

### ISSUE THREAD

**Issue by smallobserver** [bumptech/glide#1138]
in my project, I use Glide for loading image. It's easy to use.
but when I run my project on SAMSUNG Note5 android system 6.0, the image was very small when the first time image loading.

I try to load again , it had been normal

**Comment by WaylanPunch** [comment]
@smallobserver You may want to try the `.override(width, height)` method, I think it might help to solve your problem.

**Comment by smallobserver** [comment]
@WaylanPunch but I run this proiect on other phone it normal ....   only run on  android 6.0 ...   and  only the first time load  the image was not right

**Comment by smallobserver** [comment]
@WaylanPunch  and the .override  not  solve my problem...

**Comment by jackL-e-e** [comment]
Meet this problem,too.
Tried [StackOverFlow:imageView is not shown in Nexus 5 (Android 6.0)](http://stackoverflow.com/questions/33204925/imageview-is-not-shown-in-nexus-5-android-6-0)not working
What's wired is another `Htc M8,android 6.0`works fine,and if request `http` instead of `https` works fine ,too.

Device: Nexus5,android 6.0
Log as below:

    Target for: android.widget.ImageView{cd1f5c8 V.ED..... ......ID 59400,0-60480,600}, true)
                                        javax.net.ssl.SSLHandshakeException: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate not valid until Sun Nov 01 08:00:00 GMT+08:00 2015 (compared to Sun Sep 06 15:56:26 GMT+08:00 2015)
                                            at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:328)
                                            at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103)
                                            at com.android.okhttp.Connection.connect(Connection.java:143)
                                            at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
                                            at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
                                            at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
                                            at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
                                            at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
                                            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
                                            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
                                            at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
                                            at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
                                            at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:64)
                                            at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:40)
                                            at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:17)
                                            at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:70)
                                            at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:53)
                                            at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
                                            at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
                                            at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
                                            at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
                                            at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
                                            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                            at java.lang.Thread.run(Thread.java:818)
                                            at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:52)
                                         Caused by: java.security.cert.CertificateException: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate not valid until Sun Nov 01 08:00:00 GMT+08:00 2015 (compared to Sun Sep 06 15:56:26 GMT+08:00 2015)

**Comment by TWiStErRob** [comment]
Can you create a small reproducing sample app? This sounds like an issue we can't resolve just by talking about it. It's enough if you can paste your Java and Layout files here, which don't depend on other code from your app.

**Comment by TWiStErRob** [comment]
You might also want to look at https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling if there's just a small issue (like the HTTPs) not related to layout and stuff.

**Comment by TWiStErRob** [comment]
@jackL-e-e see https://github.com/koush/ion/issues/559 and also do a Google search for the exception. If you need help integrating a solution into Glide feel free to create a separate issue for that.

**Comment by jackL-e-e** [comment]
Um...i fixed my problem with the Exception of `ExtCertPathValidatorException`,this `Nexus5` 's date was set a year ago(May be a QA stuff)...works fine when set the right date today.
Thx for your help.

**Comment by smallobserver** [comment]
@TWiStErRob   now I  know why this problem   I use the .placeholder()  method .   I  setting a  .9 image .     so  how can I  do...    only on android 6.0  it will show

**Comment by TWiStErRob** [comment]
I guess you-re using `wrap_content`, so the .9 image will be laid out as the smallest possible, because it has no intrinsic size. Change your layout XML to have at least one `match_parent`.

**Comment by TWiStErRob** [comment]
Also then it's not really a Glide issue, `imageView.setImageResource(R.drawable.ninepatch)` should fail just as badly.

**Comment by smallobserver** [comment]
@TWiStErRob   but the .9 image  will show normal   :(   and also  I  use  match_parent  not  warp_content

**Comment by TWiStErRob** [comment]
So what is the issue then? Please share some code and describe actual/expected behavior, that is fill in the issue template: https://raw.githubusercontent.com/bumptech/glide/master/ISSUE_TEMPLATE.md

**Comment by silentcmz** [comment]
@smallobserver Solve your problem? I encountered the same problem，Can you tell me why? 3Q

**Comment by smallobserver** [comment]
你是中国人吗 ？   are you chinese？   I  solve the problem

**Comment by smallobserver** [comment]
@silentcmz  你是中国人吗 ？ are you chinese？ I solve the problem
this problem   The cause of the problem is to use the default image problems in 6.0 so just remove the default diagram in 6.0

**Comment by silentcmz** [comment]
@smallobserver 谢谢，我试了不适用9-path的图片就没问题，还有加上asbitmap 方法也没问题，但是不知道会有什么影响

**Comment by liqing338** [comment]
@silentcmz  请问asbitmap 是什么的方法？

**Comment by liqing338** [comment]
@silentcmz i encountered the same question:
(1) don't use "src" or "backgroud" attribute when use 9.path 
(2) use asbitmap()
(3) use placeholder(9.path) to set the default picture
