### ISSUE TITLE
Logcat shows OOM, but APP works, just the gif stops playing in ViewPager

### ISSUE THREAD

**Issue by SwayChen** [bumptech/glide#1162]
**Glide 3.7.0**

**Nexus 5**

Firstly, show Exception:
```java
Request threw uncaught throwable
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Failed to allocate a 2842572 byte allocation with 1886384 free bytes and 1842KB until OOM
    at java.util.concurrent.FutureTask.report(FutureTask.java:94)
    at java.util.concurrent.FutureTask.get(FutureTask.java:164)
    at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1121)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
    at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
 Caused by: java.lang.OutOfMemoryError: Failed to allocate a 2842572 byte allocation with 1886384 free bytes and 1842KB until OOM
    at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
    at android.graphics.Bitmap.nativeCreate(Native Method)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
    at com.bumptech.glide.load.resource.bitmap.TransformationUtils.fitCenter(TransformationUtils.java:112)
    at com.bumptech.glide.load.resource.bitmap.FitCenter.transform(FitCenter.java:24)
    at com.bumptech.glide.load.resource.bitmap.BitmapTransformation.transform(BitmapTransformation.java:54)
    at com.bumptech.glide.load.engine.DecodeJob.transform(DecodeJob.java:236)
    at com.bumptech.glide.load.engine.DecodeJob.transformEncodeAndTranscode(DecodeJob.java:139)
    at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:129)
    at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
    at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
    at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
    at java.lang.Thread.run(Thread.java:818) 
    at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118) 
```

---
Here are Codes & xml:
```java
public class GifPagerAdapter extends FragmentPagerAdapter {

        List<String> mUrlLists = new ArrayList<>();

        public GifPagerAdapter(FragmentManager fm) {
            super(fm);
            mUrlLists = urlList;
        }

        @Override
        public Fragment getItem(int position) {
            GifFragment gifFragment = new GifFragment();
            Bundle bundle = new Bundle();
            bundle.putString("gif_url", mUrlLists.get(position));
            bundle.putInt("current_pos", currentPos);
            gifFragment.setArguments(bundle);
            return gifFragment;
        }

        @Override
        public int getCount() {
            return mUrlLists.size();
        }
    }
```
```java
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        mView = inflater.inflate(R.layout.fragment_gif, container, false);
        mGifImageView = (ImageView) mView.findViewById(R.id.iv_gif);
        mProgressBar = (ContentLoadingProgressBar) mView.findViewById(R.id.progress_bar);
        mProgressBar.setVisibility(View.VISIBLE);

        Glide.with(mFragment).load(mImgUrl).asGif().diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .listener(mRequestListener).into(mGifImageView);
        return mView;
    }
```
```xml
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             xmlns:tools="http://schemas.android.com/tools"
             android:layout_width="match_parent"
             android:layout_height="match_parent"
             tools:context="me.sway.giphydemo.example.GifFragment">

    <ImageView
        android:id="@+id/iv_gif"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

    <android.support.v4.widget.ContentLoadingProgressBar
        android:id="@+id/progress_bar"
        style="?android:attr/progressBarStyleLarge"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"/>

</FrameLayout>
```

Actually, when I load gif in RecyclerView as bitmap, It also happens. If you are free enough, I think you can see my demo codes in Github: [https://github.com/SwayChen/GiphyDemo](https://github.com/SwayChen/GiphyDemo) and you maybe make some revises. Don't laugh at my codes :(

Thank you very much!

**Comment by TWiStErRob** [comment]
At first glance ViewPager holds multiple pages in memory, which means left and right pages are still loading and playing GIFs, even when not visible. Try to reduce off-screen count or clear the imageview when the page is not visible.
