### ISSUE TITLE
Gson serialize/deserialize causes exception in GlideUrl because of Headers interface

### ISSUE THREAD

**Issue by khandelwaludit** [bumptech/glide#1172]
I have a separate wrapper module for glide and my main project uses that wrapper module. Now, in my main project, I am serializing and deserializing using Gson. Gson uses reflection ( and access all private, public and protected member variables ) to serialize the object. The reason I mentioned the first line was to give you the idea that I do not have access to GsonBuilder to have instance creator. 
**What is it that I can do now to make it work ?**

```
java.lang.RuntimeException: Unable to invoke no-args constructor for interface com.bumptech.glide.load.model.Headers. Register an InstanceCreator with Gson for this type may fix this problem.
     at com.google.gson.internal.ConstructorConstructor$12.construct(ConstructorConstructor.java:210)
     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:207)
     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
     at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:285)
     at com.flipkart.chat.toolbox.RuntimeTypeAdapterFactory$1.read(RuntimeTypeAdapterFactory.java:214)
     at com.google.gson.Gson.fromJson(Gson.java:814)
     at com.google.gson.Gson.fromJson(Gson.java:779)
     at com.google.gson.Gson.fromJson(Gson.java:728)
     at com.google.gson.Gson.fromJson(Gson.java:700)
     at com.flipkart.chat.manager.GsonSerializer.deserialize(GsonSerializer.java:113)
     at com.flipkart.chat.components.Message.<init>(Message.java:30)
     at com.flipkart.chat.ui.builder.adapters.DBAdapter$10.run(DBAdapter.java:490)
     at com.flipkart.chat.db.NotifyingAsyncQueryHandler.handleMessage(NotifyingAsyncQueryHandler.java:31)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:136)
     at android.os.HandlerThread.run(HandlerThread.java:61)
  Caused by: java.lang.reflect.InvocationTargetException
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:515)
     at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:48)
     at com.google.gson.internal.ConstructorConstructor$12.construct(ConstructorConstructor.java:207)
     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:207) 
     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117) 
     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217) 
     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117) 
     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217) 
     at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:285) 
     at com.flipkart.chat.toolbox.RuntimeTypeAdapterFactory$1.read(RuntimeTypeAdapterFactory.java:214) 
     at com.google.gson.Gson.fromJson(Gson.java:814) 
     at com.google.gson.Gson.fromJson(Gson.java:779) 
     at com.google.gson.Gson.fromJson(Gson.java:728) 
     at com.google.gson.Gson.fromJson(Gson.java:700) 
     at com.flipkart.chat.manager.GsonSerializer.deserialize(GsonSerializer.java:113) 
     at com.flipkart.chat.components.Message.<init>(Message.java:30) 
     at com.flipkart.chat.ui.builder.adapters.DBAdapter$10.run(DBAdapter.java:490) 
     at com.flipkart.chat.db.NotifyingAsyncQueryHandler.handleMessage(NotifyingAsyncQueryHandler.java:31) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:136) 
     at android.os.HandlerThread.run(HandlerThread.java:61) 
  Caused by: java.lang.InstantiationException: can't instantiate class com.bumptech.glide.load.model.Headers; abstract class or interface
     at sun.misc.Unsafe.allocateInstance(Native Method)
     at java.lang.reflect.Method.invokeNative(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:515) 
     at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:48) 
     at com.google.gson.internal.ConstructorConstructor$12.construct(ConstructorConstructor.java:207) 
     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:207) 
     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117) 
     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217) 
     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117) 
     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217) 
     at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:285) 
     at com.flipkart.chat.manager.GsonSerializer.deserialize(GsonSerializer.java:113) 
     at com.flipkart.chat.components.Message.<init>(Message.java:30) 
     at com.flipkart.chat.ui.builder.adapters.DBAdapter$10.run(DBAdapter.java:490) 
     at com.flipkart.chat.db.NotifyingAsyncQueryHandler.handleMessage(NotifyingAsyncQueryHandler.java:31) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:136) 
     at android.os.HandlerThread.run(HandlerThread.java:61) 
```

**Comment by TWiStErRob** [comment]
Does it matter what's in the headers for you? If not, serialize `glideUrl.toStringUrl()` only.
Can you please explain a little more, I don't get why you would need to serialize a GlideUrl.
LazyHeaders (the implementation of Headers) can have anonymous inner classes passed in from outside stored inside which would likely also cause problems.

**Comment by TWiStErRob** [comment]
You could also try creating GlideUrl manually with an explicit implementation of Headers that don't contain any fields and return empty collections.

**Comment by khandelwaludit** [comment]
Gson serializes the entire class based on members and not fields. This is making headers a bottleneck as it is trying to instantiate headers as well. By the way, how would I create glideurl with explicit implementation on headers ?

**Comment by TWiStErRob** [comment]
>  access all private, public and protected member variables  
> based on members and not fields

What is a member variable if not a field? Because in my head a class has members: [static] fields, [static] methods, inner classes. Constrcutor/getter/setter are just specially treated methods.

After writing this I think you mean properties of a class (get/set pairs that may or may not be backed by fields). In which case there isn't anything we can do without specifying to Gson to ignore the headers or tell it how to deal with. Even if you get through this error, GlideUrl is not mutable, so Gson couldn't set the url via a setter, it needs to be provided in the ctor.

> How would I create glideurl with explicit implementation on headers?

I was thinking:
```java
new GlideUrl("", new Headers() { ... });
```
of course extract that anon class as top-level so it has a name. After writing the above about propertirs I'm not sure it'll help, because it sounds like Gson doesn't care about runtime type if the property/getter's type is an interface.

---

Please explain more why are you trying to serialize a GlideUrl and why cannot you set up Gson to handle these classes specially?

**Comment by TWiStErRob** [comment]
Another possibility is that you extend GlideUrl and override methods to annotate them to help Gson? I'm not sure if that way of configuring works in your case.

**Comment by khandelwaludit** [comment]
My bad. What I meant was that it uses fields/ members and not the getters and setters to serialize. This causes it to initialize all of the variables. 

I have already overrriden the GlideUrl but then since it uses reflection and initializes private fields as well, all members are initialized. 


Currently, I have created a superclass exclusion strategy and declared the same field in my overriden class and added superclass exclusion strategy to gson builder. 
The stackoverflow post to do the same, in case somebody else has the same issue.
[](http://stackoverflow.com/questions/16476513/class-a-declares-multiple-json-fields)

**Comment by TWiStErRob** [comment]
You said you don't have access to GsonBuilder to have an instance creator, but you can add an exclusion strategy on the builder? Did you mean that you can't control how stuff is serialized, only how it is deserialized? If so, I see why the exclusion strategy works.
*Sorry to nitpick so much, but you didn't give much context so I can only go on what's written down here.*
