### ISSUE TITLE
java.lang.IllegalStateException: Activity has been destroyed

### ISSUE THREAD

**Issue by shewenbiao** [bumptech/glide#1175]
**Glide Version**: [3.8.0-SNAPSHOT](https://github.com/bumptech/glide/wiki/Snapshots)

**Issue details / Repro steps / Use case background**: 
Use glide to load image on activity `onPrepareOptionsMenu(Menu menu)` method, but here I got a IllegalStateException: Activity has been destroyed. Is there anyway to avoid this exception?

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java
Glide.with(this)
         .load(shuffleIcon)
         .listener(new RequestListener<String, GlideDrawable>() {
                        @Override
                        public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                            notifyToUserWithAnimation();
                            return false;
                        }

                        @Override
                        public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                            return false;
                        }
                    })
          .placeholder(R.drawable.emoji_gift)
          .error(R.drawable.ic_shuffle)
          .into(mShuffleImg);
```

**Stack trace / LogCat**:

``` ruby
java.lang.IllegalStateException: Activity has been destroyed
    at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1460)
    at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
    at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:617)
    at com.bumptech.glide.manager.RequestManagerRetriever.getSupportRequestManagerFragment(RequestManagerRetriever.java:187)
    at com.bumptech.glide.manager.SupportRequestManagerFragment.onAttach(SupportRequestManagerFragment.java:116)
    at android.support.v4.app.Fragment.onAttach(Fragment.java:1152)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:968)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1197)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1562)
    at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2027)
    at android.support.v4.app.Fragment.performDestroy(Fragment.java:2179)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1147)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1197)
    at android.support.v4.app.FragmentManagerImpl.moveToState$2563266(FragmentManagerImpl.java:1179)
    at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2028)
    at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:235)
    at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:290)
    at android.support.v7.app.ActionBarActivity.onDestroy(ActionBarActivity.java:169)
    at com.android.inputmethod.latin.kkuirearch.KKEmojiSetupActivity.onDestroy(KKEmojiSetupActivity.java:1413)
    at android.app.Activity.performDestroy(Activity.java:5447)
    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1117)
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3503)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3534)
    at android.app.ActivityThread.access$1400(ActivityThread.java:139)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1253)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5103)
    at java.lang.reflect.Method.invokeNative(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
    at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by TWiStErRob** [comment]
The first thing I would try is `Glide.clear(mShuffleImg)` in, say onStop or in onDestroy before calling super.

How do you reproduce this? Does this happen every time or just when rotating or backing out, etc?

**Comment by shewenbiao** [comment]
Thanks for your suggestion, I will try it. This problem not happen every time and just happen in backing out.

**Comment by ZhaoKaiQiang** [comment]
I also have this issue：

Devices:Android 4.1.2,level 16 GT-I8190L(samsung)

StackTrace:

java.lang.IllegalStateException
Activity has been destroyed
java.lang.RuntimeException:Unable to destroy activity {kjv.bible.app/com.seal.activity.MainActivity}: java.lang.IllegalStateException: Activity has been destroyed
android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3319)
......
Caused by:
java.lang.IllegalStateException:Activity has been destroyed
android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1511)
android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:617)
com.bumptech.glide.manager.RequestManagerRetriever.getSupportRequestManagerFragment(RequestManagerRetriever.java:187)
com.bumptech.glide.manager.SupportRequestManagerFragment.onAttach(SupportRequestManagerFragment.java:116)
android.support.v4.app.Fragment.onAttach(Fragment.java:1152)
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1019)
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2078)
android.support.v4.app.Fragment.performDestroy(Fragment.java:2179)
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1198)
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2079)
android.support.v4.app.Fragment.performDestroy(Fragment.java:2179)
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1198)
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2079)
android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:235)
android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:326)
android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:161)
com.seal.activity.MainActivity.onDestroy(MainActivity.java:200)
android.app.Activity.performDestroy(Activity.java:5211)
android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1124)
android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3306)
android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3337)
android.app.ActivityThread.access$1300(ActivityThread.java:134)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1271)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loop(Looper.java:137)
android.app.ActivityThread.main(ActivityThread.java:4867)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:511)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
dalvik.system.NativeStart.main(Native Method)

**Comment by TWiStErRob** [comment]
@shewenbiao I think it may be that some async thing finishes after you pressed the back button, and starts the Glide load which queues the fragment addition, but since you're destroying already it fails.

@shewenbiao @ZhaoKaiQiang can either of you create a small app to reproduce this almost consistently?

**Comment by shewenbiao** [comment]
@TWiStErRob I used glide on ui thread, not on work thread, so I think it may be that the `RequestListener` still work in work thread after pressed the back button.

**Comment by TWiStErRob** [comment]
Async things usually finish on the UI thread, e.g. `AsyncTask.onPostExecute` or `runOnUiThread`, and that is queued together with UI events like back button. When you start a Glide load with a fragment host Glide adds a fragment to track the lifecycle, but this addition is async (on the UI thread). So the ordering is important here. I'm not sure exactly what happens, but I'm fairly confident that it's the Glide load being started late. I don't have enough context to debug, that's why I'm asking for a full repro.

**Comment by shewenbiao** [comment]
Thank you for your quick reply. but I start Glide load on  `onPrepareOptionsMenu(Menu menu)` method with activity not fragment, however this error is related to fragment.

**Comment by TWiStErRob** [comment]
Ah, sorry, I got confused with other issues probably or that line was meant for @ZhaoKaiQiang... in any case a repro from either of you would be welcome.
