### ISSUE TITLE
Cant find a way around "Canvas: trying to use a recycled bitmap"

### ISSUE THREAD

**Issue by chainani** [bumptech/glide#1179]
**Glide Version**: 3.7.0

**Issue details / Repro steps / Use case background**: 

I get an error about trying to use a recycled bitmap. Upon reviewing #857 I realised that this is because I call getDrawable() in a custom image view. I use this to make it so that the image is top crop and  not center crop. Is there any way to work around this?

Here's my code for the ImageView :
```java
public class TopCropImageView extends ImageView {

    public TopCropImageView(Context context) {
        super(context);
        setup();
    }

    public TopCropImageView(Context context, AttributeSet attrs) {
        super(context, attrs);
        setup();
    }

    public TopCropImageView(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        setup();
    }

    private void setup() {
        setScaleType(ScaleType.MATRIX);
    }

    @Override
    protected boolean setFrame(int frameLeft, int frameTop, int frameRight, int frameBottom) {
        recomputeImgMatrix(frameLeft, frameTop, frameRight, frameBottom);
        return super.setFrame(frameLeft, frameTop, frameRight, frameBottom);
    }


    private void recomputeImgMatrix(int frameLeft, int frameTop, int frameRight, int frameBottom) {
        if (getDrawable() != null && getScaleType() == ScaleType.MATRIX) {
            float frameWidth = frameRight - frameLeft;
            float frameHeight = frameBottom - frameTop;

            float originalImageWidth = (float) getDrawable().getIntrinsicWidth();
            float originalImageHeight = (float) getDrawable().getIntrinsicHeight();

            float usedScaleFactor;


                float fitHorizontallyScaleFactor = frameWidth / originalImageWidth;
                float fitVerticallyScaleFactor = frameHeight / originalImageHeight;

                usedScaleFactor = Math.max(fitHorizontallyScaleFactor, fitVerticallyScaleFactor);

            Matrix matrix = getImageMatrix();
            matrix.setScale(usedScaleFactor, usedScaleFactor, 0, 0); 
            if(fitVerticallyScaleFactor>fitHorizontallyScaleFactor){
                matrix.postTranslate(-((originalImageWidth*usedScaleFactor)-frameWidth)/2,0);
            }
            setImageMatrix(matrix);
        }
    }
}
```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(fragment)
.load(imgUrl)
.dontAnimate()
.placeholder(new ColorDrawable(placeholderColor))
.diskCacheStrategy(DiskCacheStrategy.SOURCE)
.into(dest);
```

**Stack trace / LogCat**:
```ruby
Fatal Exception: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@d13d5c7
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
       at android.graphics.Canvas.drawBitmap(Canvas.java:1404)
       at com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable.draw(GlideBitmapDrawable.java:101)
       at android.widget.ImageView.onDraw(ImageView.java:1257)
       at android.view.View.draw(View.java:16194)
       at android.view.View.updateDisplayListIfDirty(View.java:15190)
       at android.view.View.draw(View.java:15964)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
       at android.view.View.updateDisplayListIfDirty(View.java:15185)
       at android.view.View.draw(View.java:15964)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
       at android.view.View.draw(View.java:16197)
       at android.view.View.updateDisplayListIfDirty(View.java:15190)
       at android.view.View.draw(View.java:15964)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
       at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:3588)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
       at android.view.View.updateDisplayListIfDirty(View.java:15185)
       at android.view.View.draw(View.java:15964)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
       at android.view.View.draw(View.java:16197)
       at android.view.View.updateDisplayListIfDirty(View.java:15190)
       at android.view.View.draw(View.java:15964)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
       at android.view.View.updateDisplayListIfDirty(View.java:15185)
       at android.view.View.draw(View.java:15964)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
       at android.view.View.draw(View.java:16197)
       at android.view.View.updateDisplayListIfDirty(View.java:15190)
       at android.view.View.draw(View.java:15964)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1229)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
       at android.view.View.updateDisplayListIfDirty(View.java:15185)
       at android.view.View.draw(View.java:15964)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
       at android.view.View.updateDisplayListIfDirty(View.java:15185)
       at android.view.View.draw(View.java:15964)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
       at android.view.View.updateDisplayListIfDirty(View.java:15185)
       at android.view.View.draw(View.java:15964)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
       at android.view.View.updateDisplayListIfDirty(View.java:15185)
       at android.view.View.draw(View.java:15964)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
       at android.view.View.draw(View.java:16197)
       at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
       at android.view.View.updateDisplayListIfDirty(View.java:15190)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2627)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2446)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2079)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
       at android.view.Choreographer.doFrame(Choreographer.java:606)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by TWiStErRob** [comment]
I think this may not be related to the code in `TopCropImageView`. That kind of `getDrawable()` access is safe, because the `ImageView` still owns the Drawable, you're just querying the size of it on the UI thread. Any lifecycle will also happen on the UI thread so there's no threading issue either.
You can easily confirm that the exception is coming from `TopCropImageView`: override `onDraw()` and just call super; this will make `TopCropImageView` appear in the stack trace.

What is `dest` in your Glide load line?

---
Other notes, unrelated to the issue: I think you're working around Glide a lot here. I think the optimal way for this would be to create a custom transformation that does something similar to `CenterCrop`, but the alignment is to the top (probably `dy = 0` in `TransformationUtils.centerCrop`). To use this you would do: `.transform(new TopCrop(context)).into(dest)` and `scaleType` could be anything and there's no need to have a custom ImageView. This transformation could be cached as well in RESULT cache.

**Comment by chainani** [comment]
dest is just a TopCropImageView object.
If this sort of getDraweable() is not an issue, then, looking at the stacktrace, can you identify something else that could cause this. I can't pinpoint the issue since I only see it in Crashlytics for live users and can't figure out how to replicate it.

**Comment by TWiStErRob** [comment]
The stack trace in this case is not helpful, you have to look for clues as I described in https://github.com/bumptech/glide/issues/857#issuecomment-168630569.
(Check again, I added one more item to the list.)

This exception usually means that Glide cleared an ImageView's Target, but the ImageView still held on to the Bitmap and tried to draw it (this is where stealing the Drawable/Bitmap from the ImageView via `getDrawable()` and holding onto it can be unsafe). When `Target.onLoadCleared` is called the Bitmap (or Drawable) that was given to the same Target in `onResourceReady` is invalid. It may be re-used, recycled, resized, re-drawn, ... anything can happen to it.

Are you sure you're looking at the right RecyclerView in your code? There's a DrawerLayout in the stack so this RecyclerView can be the main content OR the drawer's item list.

**Comment by chainani** [comment]
@TWiStErRob still looking into this. can it also be called if i call `onResourceReady(resource, null);` on the target I receive in in the request listener?

**Comment by TWiStErRob** [comment]
You'll still get a target.onLoadCleared even if you "override" the target behaviour with a listener (= return true in callback). If you need a notification *after* the image has been set I would suggest using a custom target, see #275.
