### ISSUE TITLE
Fails on Redirects - Request Failed 302

### ISSUE THREAD

**Issue by alenz316** [bumptech/glide#119]
Glide does not follow redirects (302).

Sample:
Glide fails when trying to get Facebook profile pics through the Graph endpoint.

``` ruby
http://graph.facebook.com/zuck/picture?width=144&height=144
    java.io.IOException: Request failed 302: forced.302
            at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:50)
            at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:14)
            at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:69)
            at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:52)
            at com.bumptech.glide.load.engine.SourceResourceRunner.decodeFromSource(SourceResourceRunner.java:175)
            at com.bumptech.glide.load.engine.SourceResourceRunner.runWrapped(SourceResourceRunner.java:141)
            at com.bumptech.glide.load.engine.SourceResourceRunner.run(SourceResourceRunner.java:123)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
            at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:52)
```

**Comment by DeanSingh** [comment]
I was still getting this crash or perhaps similiar when DLing a Facebook Image URL https://graph.facebook.com/10155197719330646/picture?width=200&height=200.  Using any other ImageURL works.

I tried upgrading and OKHTTP, Glide, and Glide OKHTTP Integration to latest and it still crashes on the Facebook URL.

Any ideas?

**Comment by sjudd** [comment]
Can you file a new issue and fill out the template (you can find a link to the template in CONTRIBUTORS.md)?
