### ISSUE TITLE
IllegalStateException when loading image from url. 

### ISSUE THREAD

**Issue by blaksos** [bumptech/glide#1194]
I've recently experienced a crash with the below stack trace: 
Device : Samsung Galaxy S4 (GT-I9505)  
Android version: 5.0.1

**Glide Version**:
3.6.1

**Stack trace**
```
Can't call reconfigure() on a recycled bitmap
      at android.graphics.Bitmap.checkRecycled(Bitmap.java:393)
      at android.graphics.Bitmap.reconfigure(Bitmap.java:265)
      at com.bumptech.glide.load.engine.bitmap_recycle.SizeConfigStrategy.get(SizeConfigStrategy.java:72)
      at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.getDirty(LruBitmapPool.java:130)
      at com.bumptech.glide.load.resource.bitmap.Downsampler.downsampleWithSize(Downsampler.java:218)
      at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:153)
      at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:50)
      at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
      at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:39)
      at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)
      at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeBitmapWrapper(GifBitmapWrapperResourceDecoder.java:121)
      at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeStream(GifBitmapWrapperResourceDecoder.java:94)
      at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:71)
      at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:61)
      at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:22)
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:190)
      at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
      at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
      at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
      at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
      at java.lang.Thread.run(Thread.java:818)
      at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(MyActivity.this)
    .load(thumbnailUrl)
    .bitmapTransform(new CropCircleTransformation(MyActivity.this))
    .listener(new RequestListener<String, GlideDrawable>() {
        @Override
        public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
            return false;
        }

        @Override
        public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
           
//Some code here that change some view visibility.
            return false;
        }
    })
    .dontAnimate()
    .into(mOtherImageView);
```

**Comment by TWiStErRob** [comment]
See #1109, different exception message, but same reason.
