### ISSUE TITLE
RequestManagerRetriever - Illegal Argument Exception

### ISSUE THREAD

**Issue by rahulr4** [bumptech/glide#1204]
Hi,
This is just one of the random issues i have faced with glide

```
java.lang.IllegalArgumentException: You cannot start a load on a fragment before it is attached
       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:109)
       at com.bumptech.glide.Glide.with(Glide.java:658)
       at com.app.gymapp.fragments.NavigationDrawerCategoryFragment$3.run(NavigationDrawerCategoryFragment.java:128)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5279)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Maybe The fragment on which i am using glide ias not loaded yet but the library should not crash like this

**Comment by TWiStErRob** [comment]
I'm pretty sure if Glide doesn't crash, the support lib would crash later, making it harder to diagnose.

You should start that Runnable only after `onAttach` is called, I usually do Glide loads in `onViewCreated` because an ImageView is needed anyway. What is the relevant lifecycle of the fragment in question?

**Comment by rahulr4** [comment]
I do the image loading part in onViewCreated() only or on onResume.
I would suggest handling the crash on that particular line

**Comment by TWiStErRob** [comment]
You're clearly not starting the Glide load in those methods (at least not the one that causes the exception), because they don't show up in the stack trace you quoted above. Posting a `Runnable` to a `Handler`/`Looper`/`View.post`/`Activity.runOnUiThread` is not "starting a load", it's "deferring a load to start later" and by that time (when the action is queued up and executed) the fragment can be removed. You should check the same condition as Glide does in `RequestManagerRetriever`:
```java
if (fragment.getActivity() == null) {
    throw new IllegalArgumentException("You cannot start a load on a fragment before it is attached");
}
```
and return early from your Runnable. There's usually no point in doing any work if the Fragment is not shown.
