### ISSUE TITLE
show svg and add header error

### ISSUE THREAD

**Issue by gushoubang** [bumptech/glide#1228]
version 3.7.0
```java
  public static void loadSvg(Context context,ImageView imageView) {
        String url = "http://oss-dev.dituwuyou.com/uploads/icons/svg/000000-s-embassy.svg";
        GenericRequestBuilder requestBuilder = Glide.with(context)
                .using(Glide.buildStreamModelLoader(Uri.class, context), InputStream.class)
                .from(Uri.class)
                .as(SVG.class)
                .transcode(new SvgDrawableTranscoder(), PictureDrawable.class)
                .sourceEncoder(new StreamEncoder())
                .cacheDecoder(new FileToStreamDecoder<SVG>(new SvgDecoder()))
                .decoder(new SvgDecoder())
                .placeholder(R.drawable.ic_empty)
                .error(R.drawable.ic_empty)
                .animate(android.R.anim.fade_in)
                .listener(new SvgSoftwareLayerSetter<Uri>());
        GlideUrl glideUrl = new GlideUrl(url, new LazyHeaders.Builder().addHeader("Referer", "http://app.dituwuyou.com").build());
        requestBuilder.diskCacheStrategy(DiskCacheStrategy.SOURCE)
                // SVG cannot be serialized so it's not worth to cache it
                .load(glideUrl).into(imageView);
    }
```
but
```java
java.lang.RuntimeException: Unable to resume activity {com.dituwuyou/com.dituwuyou.ui.StyleMarkerActivity}: java.lang.ClassCastException: com.bumptech.glide.load.model.GlideUrl cannot be cast to android.net.Uri
                                                                 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
                                                                 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1388)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                              Caused by: java.lang.ClassCastException: com.bumptech.glide.load.model.GlideUrl cannot be cast to android.net.Uri
                                                                 at com.bumptech.glide.load.model.UriLoader.getResourceFetcher(UriLoader.java:16)
                                                                 at com.bumptech.glide.request.GenericRequest.onSizeReady(GenericRequest.java:438)
                                                                 at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.getSize(ViewTarget.java:211)
                                                                 at com.bumptech.glide.request.target.ViewTarget.getSize(ViewTarget.java:100)
                                                                 at com.bumptech.glide.request.GenericRequest.begin(GenericRequest.java:272)
                                                                 at com.bumptech.glide.manager.RequestTracker.resumeRequests(RequestTracker.java:83)
                                                                 at com.bumptech.glide.RequestManager.resumeRequests(RequestManager.java:180)
                                                                 at com.bumptech.glide.RequestManager.onStart(RequestManager.java:203)
                                                                 at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStart(ActivityFragmentLifecycle.java:50)
                                                                 at com.bumptech.glide.manager.SupportRequestManagerFragment.onStart(SupportRequestManagerFragment.java:135)
                                                                 at android.support.v4.app.Fragment.performStart(Fragment.java:1813)
                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:989)
                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1120)
                                                                 at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:1934)
                                                                 at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:568)
                                                                 at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
                                                                 at android.app.Activity.performStart(Activity.java:6268)
                                                                 at android.app.Activity.performRestart(Activity.java:6314)
                                                                 at android.app.Activity.performResume(Activity.java:6319)
                                                                 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
                                                                 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1388) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:148) 
```

**Comment by TWiStErRob** [comment]
You should get a compile error for this at `load()`, but you removed the generic arguments from requestBuilder. So you have an unchecked warning. You're explicitly saying that you will be loading an Uri.class, just change that.

**Comment by gushoubang** [comment]
but I changge like that
```java
GenericRequestBuilder requestBuilder = Glide.with(context)
                .using(Glide.buildStreamModelLoader(GlideUrl.class, context), InputStream.class)
                .from(GlideUrl.class)
                .as(SVG.class)
                .transcode(new SvgDrawableTranscoder(), PictureDrawable.class)
                .sourceEncoder(new StreamEncoder())
                .cacheDecoder(new FileToStreamDecoder<SVG>(new SvgDecoder()))
                .decoder(new SvgDecoder())
                .placeholder(R.drawable.ic_index_empty)
                .error(R.drawable.ic_empty)
                .animate(android.R.anim.fade_in)
                .listener(new SvgSoftwareLayerSetter<GlideUrl>());

   requestBuilder.diskCacheStrategy(DiskCacheStrategy.SOURCE)
                // SVG cannot be serialized so it's not worth to cache it
                .load(getGlideUrl(url)).into(imageView);
```
the image can't show

**Comment by TWiStErRob** [comment]
If it doesn't load there must be a reason: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

**Comment by gushoubang** [comment]
It‘s good,thanks.

**Comment by TWiStErRob** [comment]
What was it?

**Comment by gushoubang** [comment]
the url is error
