### ISSUE TITLE
Getting a Bitmap from a SVG Url resource

### ISSUE THREAD

**Issue by gushoubang** [bumptech/glide#1239]
I want it like this,becaus I need return the bitmap
```java
Bitmap theBitmap = Glide.
        with(this).
        load("http://....").
        asBitmap().
        into(100, 100). // Width and height
        get();
```

**Comment by TWiStErRob** [comment]
You can do the same as presented here: https://github.com/bumptech/glide/tree/3.0/samples/svg/src/main/java/com/bumptech/glide/samples/svg but don't finish with `.into(iv)`.

**Comment by TWiStErRob** [comment]
Sorry the above was a rushed answer. I realize what's your problem now. That example only shows how to get a Drawable from SVG, but you need to render that to Bitmap, preferably with Glide, on a background thread. I use this class to rasterize my SVGs:
```java
public class SvgBitmapDecoder implements ResourceDecoder<InputStream, Bitmap> {
	private final BitmapPool bitmapPool;
	public SvgBitmapDecoder(Context context) { this(Glide.get(context).getBitmapPool()); }
	public SvgBitmapDecoder(BitmapPool bitmapPool) { this.bitmapPool = bitmapPool; }

	public Resource<Bitmap> decode(InputStream source, int width, int height) throws IOException {
		try {
			SVG svg = SVG.getFromInputStream(source);
			if (width == Target.SIZE_ORIGINAL && height == Target.SIZE_ORIGINAL) {
				width = (int)svg.getDocumentWidth();
				height = (int)svg.getDocumentHeight();
				if (width <= 0 || height <= 0) {
					RectF viewBox = svg.getDocumentViewBox();
					width = (int)viewBox.width();
					height = (int)viewBox.height();
				}
			} else {
				if (width == Target.SIZE_ORIGINAL) {
					width = (int)(height * svg.getDocumentAspectRatio());
				}
				if (height == Target.SIZE_ORIGINAL) {
					height = (int)(width / svg.getDocumentAspectRatio());
				}
			}
			if (width <= 0 || height <= 0) {
				throw new IllegalArgumentException("Either the Target or the SVG document must declare a size.");
			}

			Bitmap bitmap = findBitmap(width, height);
			Canvas canvas = new Canvas(bitmap);
			svg.renderToCanvas(canvas);
			return BitmapResource.obtain(bitmap, bitmapPool);
		} catch (SVGParseException ex) {
			throw new IOException("Cannot load SVG from stream", ex);
		}
	}

	private Bitmap findBitmap(int width, int height) {
		Bitmap bitmap = bitmapPool.get(width, height, Config.ARGB_8888);
		if (bitmap == null) {
			bitmap = Bitmap.createBitmap(width, height, Config.ARGB_8888);
		}
		return bitmap;
	}

	@Override public String getId() {
		return getClass().getSimpleName();
	}
}
```
and all my SVGs look like this:
```xml
<?xml version="1.0"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"> 
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0,0 1000 1000">...</svg>
```
I'm using Option 2 from #362 to end up with a GlideDrawable-compatible resource, even though I'm using a Bitmap a decoder, if you really just need a bitmap try something like this:
```java
Glide.with(context)
     .load(source)
     .asBitmap()
     .imageDecoder(new SvgBitmapDecoder(context))
     ....
;
```

I would also suggest considering `.diskCacheStrategy(SOURCE)` or `.diskCacheStrategy(ALL)` due to small SVG source size.

**Comment by gushoubang** [comment]
but I use it by "ExecutorService" it post ExecutionException

**Comment by TWiStErRob** [comment]
What's the cause of that exception? Always check the bottom-most message in a stack trace!

**Comment by gushoubang** [comment]
OK，I think Ifind the question，because I use "diskCacheStrategy"
now it's OK
```
  executorService.execute(new Runnable() {
            @Override
            public void run() {
                try {
                    theBitmap = Glide
                            .with(MainActivity.this)
                            .load(url)
                            .asBitmap()
                            .imageDecoder(new SvgBitmapDecoder(MainActivity.this))
                            //.diskCacheStrategy(DiskCacheStrategy.ALL)
                            .into(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                            .get();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                } catch (ExecutionException e) {
                    e.printStackTrace();
                }
                Log.e("aa", "aa");
            }
        });
```

**Comment by TWiStErRob** [comment]
You should use SOURCE or  ALL, what's the problem with it?

**Comment by gushoubang** [comment]
If I use ".diskCacheStrategy(DiskCacheStrategy.ALL)" like this 
```
public class MainActivity extends FragmentActivity {
    TextView tv_name;
    Bitmap theBitmap;
    ExecutorService executorService;
    //    String url = "http://pic36.nipic.com/20131217/6704106_233034463381_2.jpg";
    String url = "http://www.clker.com/cliparts/u/Z/2/b/a/6/android-toy-h.svg";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        tv_name = (TextView) findViewById(R.id.tv_name);
        executorService = Executors.newFixedThreadPool(1);

        executorService.execute(new Runnable() {
            @Override
            public void run() {
                try {
                    theBitmap = Glide
                            .with(MainActivity.this)
                            .load(url)
                            .asBitmap()
                            .imageDecoder(new SvgBitmapDecoder(MainActivity.this))
                            .diskCacheStrategy(DiskCacheStrategy.ALL)
                            .into(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                            .get();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                } catch (ExecutionException e) {
                    e.printStackTrace();
                }
                Log.e("aa", "aa");
            }
        });
    }
}
```
it post ExecutionException

**Comment by TWiStErRob** [comment]
Yes, but what is the cause of that exception? Scroll down more in logs and read "caused by".

**Comment by gushoubang** [comment]
```
06-02 16:48:05.563 15305-15305/com.xiaogu W/ActivityThread: Application com.xiaogu is waiting for the debugger on port 8100...
06-02 16:48:07.388 15305-15305/com.xiaogu W/System: ClassLoader referenced unknown path: /data/app/com.xiaogu-1/lib/arm
06-02 16:48:08.674 15305-15434/com.xiaogu W/System.err: java.util.concurrent.ExecutionException
06-02 16:48:08.674 15305-15434/com.xiaogu W/System.err:     at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:189)
06-02 16:48:08.674 15305-15434/com.xiaogu W/System.err:     at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:100)
06-02 16:48:08.674 15305-15434/com.xiaogu W/System.err:     at com.xiaogu.ui.MainActivity$1.run(MainActivity.java:45)
06-02 16:48:08.674 15305-15434/com.xiaogu W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-02 16:48:08.674 15305-15434/com.xiaogu W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-02 16:48:08.674 15305-15434/com.xiaogu W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

**Comment by TWiStErRob** [comment]
Oh, so that looks like you got a null exception cause (unless you missed a few lines below, which is unlikely). In your decoder make sure to always throw an exception whey you have a problem. Returning null will fail the load, but you won't know why, like now.

**Comment by gushoubang** [comment]
Oh,Yes

**Comment by catkbm** [comment]
imageDecoder() unresolved refence showing in my case. Please clear the answer as soon as possible. Thanks in advance

**Comment by Nivedh28** [comment]
I am also facing the same issue of imageDecoder() unresolved

**Comment by TWiStErRob** [comment]
The discussion here was 5 years ago for version 3 of Glide. See https://github.com/bumptech/glide/issues/3522 for how to migrate.

**Comment by TWiStErRob** [comment]
See also the updated SVG sample:
https://github.com/bumptech/glide/tree/master/samples/svg/src/main/java/com/bumptech/glide/samples/svg
