### ISSUE TITLE
Don't load SVG (Have a Error java.lang.NoClassDefFoundError)

### ISSUE THREAD

**Issue by AlexZolq** [bumptech/glide#1278]
Hi
i try use code from sample SvgDecoder but i have a strange error 
I newbee in android, please help with this error

**Error**
```
PriorityExecutor: Request threw uncaught throwable
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Failed resolution of: Lokio/Okio;
   at java.util.concurrent.FutureTask.report(FutureTask.java:93)
   at java.util.concurrent.FutureTask.get(FutureTask.java:163)
   at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1120)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
   at java.lang.Thread.run(Thread.java:818)
   at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lokio/Okio;
   at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:189)
   at okhttp3.internal.io.RealConnection.buildConnection(RealConnection.java:170)

```

**MainActivity**
```java
private GenericRequestBuilder<Uri, InputStream, SVG, PictureDrawable> requestBuilder;

// from https://github.com/bumptech/glide/tree/3.0/samples/svg/src/main/java/com/bumptech/glide/samples/svg
requestBuilder = Glide.with(this)
                .using(Glide.buildStreamModelLoader(Uri.class, this), InputStream.class)
                .from(Uri.class)
                .as(SVG.class)
                .transcode(new SvgDrawableTranscoder(), PictureDrawable.class)
                .sourceEncoder(new StreamEncoder())
                .cacheDecoder(new FileToStreamDecoder<SVG>(new SvgDecoder()))
                .decoder(new SvgDecoder())
                .placeholder(R.drawable.ic_menu_camera)
                .error(R.drawable.ic_menu_slideshow)
                // .animate(android.)
                .listener(new SvgSoftwareLayerSetter<Uri>());

                               Uri uri = Uri.parse(strUrl);
                                requestBuilder
                                        .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                                        // SVG cannot be serialized so it's not worth to cache it
                                        .load(uri)
                                        .into(imageView);

```

**MyGlideModule.class**
```java
public class MyGlideModule  implements GlideModule {
    @Override
    public void applyOptions(Context context, GlideBuilder builder) {

    }

    @Override
    public void registerComponents(Context context, Glide glide) {

        OkHttpClient client = new OkHttpClient.Builder()
                .connectTimeout(90, TimeUnit.SECONDS)
                .writeTimeout(90, TimeUnit.SECONDS)
                .readTimeout(90, TimeUnit.SECONDS)
                .build();
      

        glide.register(GlideUrl.class, InputStream.class,
                new com.bumptech.glide.integration.okhttp3.OkHttpUrlLoader.Factory(client));
        
    }
}
```

**Manifest**
```xml
<application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

        <meta-data
            android:name="com.alexerp.MyGlideModule"
            android:value="GlideModule" />
```

**Build.gradle**
```gradle
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.android.support:support-v4:23.1.1'

    compile 'com.github.bumptech.glide:okhttp3-integration:1.4.0@jar'
    // compile 'com.squareup.okhttp3:okhttp:3.2.0'

    compile files('libs/org.apache.http.legacy.jar')
    // compile files('libs/glide-3.7.0.jar')
    // compile files('libs/svg-android-1.1.jar')
    // compile files('libs/okhttp-3.3.1.jar')
}
```

**Comment by TWiStErRob** [comment]
You can try `transitive`: http://stackoverflow.com/q/31731014/253468
Or better: explicitly list Glide and OkHttp3 dependencies with the version you want.

I suggest that you try to avoid putting any jars to the `libs` directory. Everything you need should be available in a Maven repo that you can reference in Gradle. I used `com.caverock:androidsvg:1.2.1`.
