### ISSUE TITLE
Canvas: trying to use a recycled bitmap

### ISSUE THREAD

**Issue by MFlisar** [bumptech/glide#1284]
**Glide Version**: 3.7.0

**Issue details / Repro steps / Use case background**: 

I'm trying to use an image from a list as the placeholder image for the big image view (clicking an image in the list will open the big image view). I want to reuse the drawable from the `ImageView` in the list.

I've read similar issues, but I'm not sure how to solve that. I assume, the problem is in reusing the bitmap from `ImageView` in the list as placeholder (`placeholder(image.getDrawable())`), is this correct? How would I make that correctly?

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
public static void loadFull(@NonNull IMedia photo, @NonNull final ImageView image)
{
	DrawableRequestBuilder requestBase = photo.getRequestBase(image.getContext(), true)
			.diskCacheStrategy(getStrategy(photo))
			.dontAnimate()
			.priority(Priority.HIGH)
			.dontTransform()
			;

	requestBase
			.placeholder(image.getDrawable())
			.thumbnail(loadThumbRequest(photo, image.getContext(), ImagePreviewType.None))
			.override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
			.into(new GlideDrawableTarget(image));
}
```

**Stack trace / LogCat**:
```ruby
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@8de2c9c
        at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
        at android.graphics.Canvas.drawBitmap(Canvas.java:1404)
        at com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable.draw(GlideBitmapDrawable.java:101)
        at android.widget.ImageView.onDraw(ImageView.java:1246)
        at android.view.View.draw(View.java:16187)
        at com.alexvasilkov.gestures.views.GestureImageView.draw(GestureImageView.java:79)
        at android.view.View.updateDisplayListIfDirty(View.java:15184)
        at android.view.View.draw(View.java:15957)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.updateDisplayListIfDirty(View.java:15179)
        at android.view.View.draw(View.java:15957)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.draw(View.java:16190)
        at android.support.v4.view.ViewPager.draw(ViewPager.java:2341)
        at android.view.View.updateDisplayListIfDirty(View.java:15184)
        at android.view.View.draw(View.java:15957)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1131)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.draw(View.java:16190)
        at android.view.View.updateDisplayListIfDirty(View.java:15184)
        at android.view.View.draw(View.java:15957)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1373)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.updateDisplayListIfDirty(View.java:15179)
        at android.view.View.draw(View.java:15957)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1373)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.draw(View.java:16190)
        at android.view.View.updateDisplayListIfDirty(View.java:15184)
        at android.view.View.draw(View.java:15957)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.updateDisplayListIfDirty(View.java:15179)
        at android.view.View.draw(View.java:15957)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.updateDisplayListIfDirty(View.java:15179)
        at android.view.View.draw(View.java:15957)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.updateDisplayListIfDirty(View.java:15179)
        at android.view.View.draw(View.java:15957)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.updateDisplayListIfDirty(View.java:15179)
        at android.view.View.draw(View.java:15957)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.draw(View.java:16190)
        at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2946)
        at android.view.View.updateDisplayListIfDirty(View.java:15184)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:282)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:288)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
        at android.view.Choreographer.doFrame(Choreographer.java:606)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5466)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
```

**Comment by TWiStErRob** [comment]
Remove placeholder, `getDrawable()` is unsafe. You need to add another layer of thumbnail that is the same load that loaded `getDrawable` and that will hit the memory cache and do the reusing for you:
```java
Glide
    .with()
    .load(full)
    .thumbnail(Glide
        .with()
        .load(thumb)
        .thumbnail(Glide
            .with()
            .load(smallThumb)))
    .into()
```

The related issue is #527, and see #861 where we used this trick extensively.

**Comment by MFlisar** [comment]
Thanks for clarifying that, I just was not sure if this is the same...

**Comment by MFlisar** [comment]
I still can't get this working correctly.

In my adapter, I use following function to load the small images:

    loadThumbRequest(photo, image.getContext());

In my big view, I now tried following:

     request
        .thumbnail(loadThumbRequest(photo, image.getContext())))
     ...

**PROBLEM**

I'm animating an image (a new `ImageView`, not the one from the list directly) from the list to the big image view, so I really need to make sure, that the thumbnail (or the placeholder I used before) is immediately available. Using the above method results in not showing the image immediately... I'm using the exact same request for the thumbnail as I use for the image in the list...

**Comment by TWiStErRob** [comment]
Take a look at what I did in #1279

Also because you need to animate to, you need to not croasFade, I'm pretty sure that will mess up display. To prevent that: in onCreate load the memory cached image. After the transition is complete load the full quality image. If you want this to happen really fast after the transition you can do a low priority preload in onCreate.

Add a listener to each load to see if you're hitting the right cache. See the debugging wiki for deeper tips.

Let me know if this is not enough. It's tricky and there should be a guide to do this on the wiki or on someone's blog because it keeps coming up.

**Comment by MFlisar** [comment]
I think, my problem was, that I oversaw, that my new preview image loading via exif thumbnail, did skip the cache (because I used the glide `byte[]` loader). Now I wrote a custom data fetcher that loads the thumb from the exif thumbnail and now it's working fine.

**Comment by mushtaq99** [comment]
@TWiStErRob  i had the same problem did you resolved it
Fatal Exception: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@1eb3bdb
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
       at android.graphics.Canvas.drawBitmap(Canvas.java:1404)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:544)
       at android.widget.ImageView.onDraw(ImageView.java:1226)
       at android.view.View.draw(View.java:16507)
       at android.view.View.updateDisplayListIfDirty(View.java:15460)
       at android.view.View.draw(View.java:16261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
       at android.view.View.updateDisplayListIfDirty(View.java:15452)
       at android.view.View.draw(View.java:16261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
       at android.view.View.draw(View.java:16519)
       at android.view.View.updateDisplayListIfDirty(View.java:15460)
       at android.view.View.draw(View.java:16261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
       at android.view.View.updateDisplayListIfDirty(View.java:15452)
       at android.view.View.draw(View.java:16261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
       at android.view.View.updateDisplayListIfDirty(View.java:15452)
       at android.view.View.draw(View.java:16261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
       at android.view.View.draw(View.java:16519)
       at android.view.View.updateDisplayListIfDirty(View.java:15460)
       at android.view.View.draw(View.java:16261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
       at android.view.View.updateDisplayListIfDirty(View.java:15452)
       at android.view.View.draw(View.java:16261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
       at android.view.View.updateDisplayListIfDirty(View.java:15452)
       at android.view.View.draw(View.java:16261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
       at android.view.View.updateDisplayListIfDirty(View.java:15452)
       at android.view.View.draw(View.java:16261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
       at android.view.View.updateDisplayListIfDirty(View.java:15452)
       at android.view.View.draw(View.java:16261)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2758)
       at android.view.View.draw(View.java:16519)
       at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2744)
       at android.view.View.updateDisplayListIfDirty(View.java:15460)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:286)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:292)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:327)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3015)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2819)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2431)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1321)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6703)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
       at android.view.Choreographer.doCallbacks(Choreographer.java:696)
       at android.view.Choreographer.doFrame(Choreographer.java:631)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5763)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
