### ISSUE TITLE
Leak RecyclerView Adapter 

### ISSUE THREAD

**Issue by petrovichtim** [bumptech/glide#1287]
Good day.
Please help me to find memory leak in my adapter. [source](https://gist.github.com/petrovichtim/ecddfd87aeb3aa21cbb682b43e79eed6)
Glide load **gif** images 0.1 to 5 Mb.

It give OOM exeption:
```
06-24 20:34:05.031 5244-5468/com.rusdelphi.catlist E/PriorityExecutor: Request threw uncaught throwable
 java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Failed to allocate a 163852 byte allocation with 80968 free bytes and 79KB until OOM
     at java.util.concurrent.FutureTask.report(FutureTask.java:94)
     at java.util.concurrent.FutureTask.get(FutureTask.java:164)
     at com.bumptech.glide.load.b.c.a.afterExecute(Unknown Source)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1121)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
     at java.lang.Thread.run(Thread.java:818)
     at com.bumptech.glide.load.b.c.b$1.run(Unknown Source)
  Caused by: java.lang.OutOfMemoryError: Failed to allocate a 163852 byte allocation with 80968 free bytes and 79KB until OOM
     at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:91)
     at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:201)
     at com.bumptech.glide.load.resource.c.o.a(Unknown Source)
     at com.bumptech.glide.load.resource.c.o.a(Unknown Source)
     at com.bumptech.glide.load.resource.c.o.a(Unknown Source)
     at com.bumptech.glide.load.resource.d.c.a(Unknown Source)
     at com.bumptech.glide.load.resource.d.c.b(Unknown Source)
     at com.bumptech.glide.load.resource.d.c.a(Unknown Source)
     at com.bumptech.glide.load.resource.d.c.a(Unknown Source)
     at com.bumptech.glide.load.resource.d.c.a(Unknown Source)
     at com.bumptech.glide.load.resource.d.g.a(Unknown Source)
     at com.bumptech.glide.load.resource.d.g.a(Unknown Source)
     at com.bumptech.glide.load.resource.b.c.a(Unknown Source)
     at com.bumptech.glide.load.resource.b.c.a(Unknown Source)
     at com.bumptech.glide.load.b.a.a(Unknown Source)
     at com.bumptech.glide.load.b.a.b(Unknown Source)
     at com.bumptech.glide.load.b.a.a(Unknown Source)
     at com.bumptech.glide.load.b.a.e(Unknown Source)
     at com.bumptech.glide.load.b.a.c(Unknown Source)
     at com.bumptech.glide.load.b.t.f(Unknown Source)
     at com.bumptech.glide.load.b.t.d(Unknown Source)
     at com.bumptech.glide.load.b.t.run(Unknown Source)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
     at java.lang.Thread.run(Thread.java:818) 
     at com.bumptech.glide.load.b.c.b$1.run(Unknown Source) 
```

**Comment by TWiStErRob** [comment]
The gist is 404

**Comment by petrovichtim** [comment]
Please, try this
https://gist.github.com/petrovichtim/ecddfd87aeb3aa21cbb682b43e79eed6
Here is a error : 06-24 20:34:05.031 5244-5468/com.rusdelphi.catlist E/PriorityExecutor: Request threw uncaught throwable
                                                                       java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Failed to allocate a 163852 byte allocation with 80968 free bytes and 79KB until OOM
                                                                           at java.util.concurrent.FutureTask.report(FutureTask.java:94)
                                                                           at java.util.concurrent.FutureTask.get(FutureTask.java:164)
                                                                           at com.bumptech.glide.load.b.c.a.afterExecute(Unknown Source)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1121)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                           at java.lang.Thread.run(Thread.java:818)
                                                                           at com.bumptech.glide.load.b.c.b$1.run(Unknown Source)
                                                                        Caused by: java.lang.OutOfMemoryError: Failed to allocate a 163852 byte allocation with 80968 free bytes and 79KB until OOM
                                                                           at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:91)
                                                                           at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:201)
                                                                           at com.bumptech.glide.load.resource.c.o.a(Unknown Source)
                                                                           at com.bumptech.glide.load.resource.c.o.a(Unknown Source)
                                                                           at com.bumptech.glide.load.resource.c.o.a(Unknown Source)
                                                                           at com.bumptech.glide.load.resource.d.c.a(Unknown Source)
                                                                           at com.bumptech.glide.load.resource.d.c.b(Unknown Source)
                                                                           at com.bumptech.glide.load.resource.d.c.a(Unknown Source)
                                                                           at com.bumptech.glide.load.resource.d.c.a(Unknown Source)
                                                                           at com.bumptech.glide.load.resource.d.c.a(Unknown Source)
                                                                           at com.bumptech.glide.load.resource.d.g.a(Unknown Source)
                                                                           at com.bumptech.glide.load.resource.d.g.a(Unknown Source)
                                                                           at com.bumptech.glide.load.resource.b.c.a(Unknown Source)
                                                                           at com.bumptech.glide.load.resource.b.c.a(Unknown Source)
                                                                           at com.bumptech.glide.load.b.a.a(Unknown Source)
                                                                           at com.bumptech.glide.load.b.a.b(Unknown Source)
                                                                           at com.bumptech.glide.load.b.a.a(Unknown Source)
                                                                           at com.bumptech.glide.load.b.a.e(Unknown Source)
                                                                           at com.bumptech.glide.load.b.a.c(Unknown Source)
                                                                           at com.bumptech.glide.load.b.t.f(Unknown Source)
                                                                           at com.bumptech.glide.load.b.t.d(Unknown Source)
                                                                           at com.bumptech.glide.load.b.t.run(Unknown Source)
                                                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                           at java.lang.Thread.run(Thread.java:818) 
                                                                           at com.bumptech.glide.load.b.c.b$1.run(Unknown Source)

**Comment by TWiStErRob** [comment]
Nothing obvious stands out, try to use Monitors in Android Studio to watch the memory grow, and when it's near OOM take a heap dump and check what's dominating the heap. You may need `hprof-conv` and MAT to do that though if AS's tools are not enough. This approach is better than trying to find the culprit via static analysis, because it'll tell you exactly what is leaking.

I guess you tried `trimMemory` to prevent OOM, don't forget to remove that, it shouldn't be needed in production. I made few other comments on the gist which are unrelated to Glide.

**Comment by petrovichtim** [comment]
I try to find leak two days.
Here  is my  [https://yadi.sk/d/nEBX4UC3smV8U](com.rusdelphi.catlist.hprof)

**Comment by TWiStErRob** [comment]
*Either don't insert a link, just the plain url, or use it correctly: `[label](url)`.* I realized that was the problem with the gist too.

**Comment by petrovichtim** [comment]
I corrected the review

**Comment by TWiStErRob** [comment]
Hmm looking at the dump it looks like what you want is just not possible. Based on the small size of the dump I guess your device has very little memory. Glide needs to keep the GIF bytes in memory + 2 frames. This means that for a 5MB 500x500 GIF it takes 5MB + 2*1MB = 7MB memory. And this is for only one animated GIF, you're saying you have a list of these.
Next time you have a memory issue, try to disable proguard so you can see which classes are holding memory; `g.b.d` and `b.a.i` tell me the same amount as to you.

**Comment by petrovichtim** [comment]
Thank you. Make a [new file](https://yadi.sk/d/bOkRwhVSsmYUG). On nexus 5x got the same error. Allocated memory grown on images loaded. And OOM happens when it more than 250 Mb.

**Comment by TWiStErRob** [comment]
Take the heap dump when the memory is near 250 or even after OOM happened. a 20-something MB sized heap dump doesn't tell which objects are repeated too many times.

**Comment by petrovichtim** [comment]
Please look at this [one ](https://yadi.sk/d/tG0g6n-8smagY)

**Comment by petrovichtim** [comment]
I think error is here 
![here ](https://cloud.githubusercontent.com/assets/7734561/16355385/8c5d787a-3ae7-11e6-8b91-afc6ad8fd6a9.PNG)

**Comment by petrovichtim** [comment]
Adapter leak on this place 
` private void setupRecyclerView(final RecyclerView recyclerView) {
        mStaggeredGridLayoutManager = new StaggeredGridLayoutManager(mOneColumn ?
                1 : getResources().getInteger(R.integer.gallery_columns), LinearLayoutManager.VERTICAL);
        recyclerView.setLayoutManager(mStaggeredGridLayoutManager);
        RecyclerView.ItemAnimator itemAnimator = new DefaultItemAnimator();
        itemAnimator.setAddDuration(1000);
        itemAnimator.setRemoveDuration(1000);
        recyclerView.setItemAnimator(itemAnimator);

        adapterWrapper = new MyAdmobAdapterWrapper(this);
        adapterWrapper.setAdapter(mCatsAdapter);
        //adapterWrapper.setTestDeviceId("74F6DC1DAF8CF87A11720BCC0BBFA91B");//"EA497D32970347B3AF961BC22B54F0A1");

        recyclerView.swapAdapter(mCatsAdapter, true);
    }`
Fixed by added 
` @Override
    public void onViewDetachedFromWindow(CatsAdapter.CatsViewHolder holder) {
        Glide.clear(holder.imageView);
    }`

**Comment by AjayNiu** [comment]
Maybe you can help me. :)
