### ISSUE TITLE
ArrayIndexOutOfBoundsException in Fragment

### ISSUE THREAD

**Issue by joydeepsaha05** [bumptech/glide#1296]
**Glide Version**: 3.7.0

**Integration libraries**: None

**Device/Android Version**: Fails on Android Lollipop, works on other versions

**Issue details / Repro steps / Use case background**: I am loading images into recyclerView items which are present in a fragment. The images are loaded in the onResume() method.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**: Loading the images in the recyclerView's adapter.
```java
@Override
public void onBindViewHolder(final ViewHolder viewHolder, int position) {
        Glide.with(App.getAppContext())
                .load(itemsData.get(0).getImage())
                .skipMemoryCache(true)
                .diskCacheStrategy(DiskCacheStrategy.RESULT)
                .into(viewHolder.imageView);
}
```

**Layout XML**:
```xml
<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    android:id="@+id/cv"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    card_view:cardBackgroundColor="#00FFFFFF"
    card_view:cardCornerRadius="4dp"
    card_view:cardElevation="0dp"
    card_view:cardMaxElevation="0dp"
    card_view:cardPreventCornerOverlap="false"
    card_view:cardUseCompatPadding="true">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
            android:id="@+id/overlay"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <TextView
                android:id="@+id/title"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                android:textSize="22sp"
                android:textStyle="bold" />

            <ImageView
                android:id="@+id/tab2_image"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:adjustViewBounds="true"
                android:contentDescription="@string/NULL" />

            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="@drawable/overlay" />

        </FrameLayout>

        <RelativeLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentBottom="true"
            android:layout_alignParentEnd="true"
            android:layout_alignParentRight="true"
            android:padding="4dp">

            <TextView
                android:id="@+id/details"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentEnd="true"
                android:layout_alignParentRight="true"
                android:layout_marginBottom="1dp"
                android:textColor="#FFFFFF"
                android:textSize="14sp" />

            <TextView
                android:id="@+id/airDate"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentEnd="true"
                android:layout_alignParentRight="true"
                android:layout_below="@+id/details"
                android:textColor="#FFFFFF"
                android:textSize="14sp" />

        </RelativeLayout>

    </RelativeLayout>

</android.support.v7.widget.CardView>
```

**Stack trace / LogCat**:
```ruby
java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
                                                                              at android.util.PathParser$PathDataNode.addCommand(PathParser.java:380)
                                                                              at android.util.PathParser$PathDataNode.nodesToPath(PathParser.java:260)
                                                                              at android.graphics.drawable.VectorDrawable$VPath.toPath(VectorDrawable.java:1265)
                                                                              at android.graphics.drawable.VectorDrawable$VPathRenderer.drawPath(VectorDrawable.java:950)
                                                                              at android.graphics.drawable.VectorDrawable$VPathRenderer.drawGroupTree(VectorDrawable.java:931)
                                                                              at android.graphics.drawable.VectorDrawable$VPathRenderer.draw(VectorDrawable.java:938)
                                                                              at android.graphics.drawable.VectorDrawable$VectorDrawableState.updateCachedBitmap(VectorDrawable.java:705)
                                                                              at android.graphics.drawable.VectorDrawable.draw(VectorDrawable.java:280)
                                                                              at android.widget.ImageView.onDraw(ImageView.java:1148)
                                                                              at android.view.View.draw(View.java:15114)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:14048)
                                                                              at android.view.View.getDisplayList(View.java:14071)
                                                                              at android.view.View.draw(View.java:14838)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:14043)
                                                                              at android.view.View.getDisplayList(View.java:14071)
                                                                              at android.view.View.draw(View.java:14838)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                                              at android.view.View.draw(View.java:15117)
                                                                              at android.widget.FrameLayout.draw(FrameLayout.java:592)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:14048)
                                                                              at android.view.View.getDisplayList(View.java:14071)
                                                                              at android.view.View.draw(View.java:14838)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
                                                                              at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4134)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                                              at android.view.View.draw(View.java:15117)
                                                                              at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3543)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:14048)
                                                                              at android.view.View.getDisplayList(View.java:14071)
                                                                              at android.view.View.draw(View.java:14838)
                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:14043)
                                                                              at android.view.View.getDisplayList(View.java:14071)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:14008)
                                                                              at android.view.View.getDisplayList(View.java:14071)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:14008)
                                                                              at android.view.View.getDisplayList(View.java:14071)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:14008)
                                                                              at android.view.View.getDisplayList(View.java:14071)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:14008)
                                                                              at android.view.View.getDisplayList(View.java:14071)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:14008)
                                                                              at android.view.View.getDisplayList(View.java:14071)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3388)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3367)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:14008)
                                                                              at android.view.View.getDisplayList(View.java:14071)
                                                                          	at android.view.ViewGrou
```

**Comment by TWiStErRob** [comment]
It looks like your bind doesn't depend on position, but that is not he problem here because the index is 2 and not 0. One of your VectorDrawable is causing the problem, maybe `overlay`? If you check the source code of the exception origin you'll see that it's trying to access the path segment's values. Check you paths for missing parameters (e.g. h,v has 1, m,l has 2, a has 7) or just dangling letters.

**Comment by joydeepsaha05** [comment]
@TWiStErRob This is the code for the overlay.
 
```xml
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <gradient
        android:centerColor="#40000000"
        android:endColor="#99000000"
        android:startColor="#00000000" />
</shape>
```

I am not using vectorDrawables anywhere. Also, the issue presents itself only in Android L and not in any previous or later versions.

**Comment by TWiStErRob** [comment]
Huh, interesting. But you still have a VectorDrawable in an ImageView somewhere:
```
at android.graphics.drawable.VectorDrawable.draw(VectorDrawable.java:280)
at android.widget.ImageView.onDraw(ImageView.java:1148)
```

Put a method breakpoint on `VectorDrawable.draw` and see which ImageView contains it by changing the stack frame in the debug view after the breakpoint stops the app.
