### ISSUE TITLE
OutOfMemoryError for gif big 

### ISSUE THREAD

**Issue by fanweiguo** [bumptech/glide#1300]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
    at java.util.concurrent.FutureTask.report(FutureTask.java:94)
    at java.util.concurrent.FutureTask.get(FutureTask.java:160)
    at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
    at java.lang.Thread.run(Thread.java:841)
    at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
 Caused by: java.lang.OutOfMemoryError
    at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:91)
    at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:201)
    at com.bumptech.glide.load.resource.gif.GifResourceDecoder.inputStreamToBytes(GifResourceDecoder.java:106)
    at com.bumptech.glide.load.resource.gif.GifResourceDecoder.decode(GifResourceDecoder.java:57)
    at com.bumptech.glide.load.resource.gif.GifResourceDecoder.decode(GifResourceDecoder.java:26)
    at com.bumptech.glide.load.resource.file.FileToStreamDecoder.decode(FileToStreamDecoder.java:39)
    at com.bumptech.glide.load.resource.file.FileToStreamDecoder.decode(FileToStreamDecoder.java:17)
    at com.bumptech.glide.load.engine.DecodeJob.loadFromCache(DecodeJob.java:222)
    at com.bumptech.glide.load.engine.DecodeJob.decodeSourceFromCache(DecodeJob.java:109)
    at com.bumptech.glide.load.engine.EngineRunnable.decodeFromCache(EngineRunnable.java:116)
    at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:99)
    at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
    at java.util.concurrent.FutureTask.run(FutureTask.java:234)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
    at java.lang.Thread.run(Thread.java:841) 
    at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118) 
```

**Comment by fanweiguo** [comment]
已经设置了diskCacheStrategy(DiskCacheStrategy.SOURCE), but  not useful,please help look

**Comment by TWiStErRob** [comment]
The full GIF file will be loaded into memory + 2 frames will be needed to show the animation (1 displayed, 1 loading, then swap). If your source GIF is huge, it'll take up memory. If your GIF's resolution is huge it'll take up memory. There's no way around this. You can try `.override()` to load a smaller image, but it looks like it's failing before even having a chance to decode Bitmaps.

Try to do some normal OOM troubleshooting, it's possible you have a leak somewhere else, but it comes up here, because GIFs need a lot of memory.

**Comment by TWiStErRob** [comment]
Please add more details by editing your first comment, the device/android version may give a clue about how big your available memory is for example.
