### ISSUE TITLE
Out of memory on a 65536016-byte allocation using glide library android

### ISSUE THREAD

**Issue by youcaf** [bumptech/glide#1309]
have tried many things to handle this error. I was facing the same issue when i was using picasso before glide. When ever i click on "change photo" and select a photo from gallery or camera etc and want to set that selected image in the "Update Activity" in the image view. It throws out of memory exception. I am resizing the image size to 500x500 and compress it then trying to set it in the image view but it stills goes out of memory.I guess the problem is that i am not freeing this memory allocated but i searched but did not get any idea. Thanks in advance.

Here is my code of activities. 

```java
public class UpdateActivity  extends AppCompatActivity {
    @InjectView(R.id.image)
    ImageView _USERImage;
    @InjectView(R.id.input_name)
    EditText _nameText;
    @InjectView(R.id.btnchangephoto)
    Button changePhoto;
    @InjectView(R.id.input_password)
    EditText _passwordText;
    @InjectView(R.id.input_number)
    TextView _numText;
    public static boolean UpdatingPhoto = false;
    public String encodedPhotoString = null;
    public String ChangedName = null;
    public String ChangedPassword = null;
    public String ChangedContactNo = null;
    HashMap<String, String> ThingsTobeUpdated = null;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        try{
            setContentView(R.layout.updateactivity);
            ButterKnife.inject(this);
        }catch (OutOfMemoryError e){
            Toast.makeText(getBaseContext(), "Sorry,Something went wrong, try again", Toast.LENGTH_SHORT).show();
        }

        ThingsTobeUpdated  = new HashMap<>();
        CheckImage();

        changePhoto.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                UpdatingPhoto = true;
                Intent intent = new Intent(getApplicationContext(), CroppingActivity.class);
                startActivity(intent);
                UpdateActivity.this.finish();
            }
        });

    }

    public void CheckImage() {
        if (CroppingActivity.newImage != null) {

            Drawable drawable = _USERImage.getDrawable();
            BitmapDrawable bitmapDrawable = (BitmapDrawable) drawable;
            Bitmap bitmap = bitmapDrawable.getBitmap();
            bitmap.recycle();
            CroppingActivity.newImage =  getResizedBitmap(CroppingActivity.newImage,500,500);
            ByteArrayOutputStream stream = new ByteArrayOutputStream();
            CroppingActivity.newImage.compress(Bitmap.CompressFormat.JPEG, 100, stream);
            Uri uri = getImageUri(CroppingActivity.newImage);
            String url = getRealPathFromURI(uri);
            File file = new File(url);
            Glide.with(UpdateActivity.this).load(file).override(400,400).placeholder(R.drawable.user).error(R.drawable.error)
                    .centerCrop().crossFade().bitmapTransform(new CropCircleTransformation(UpdateActivity.this)).into(_USERImage);
           
            byte[] byte_arr = stream.toByteArray();
            encodedPhotoString = Base64.encodeToString(byte_arr, 0);

        } else {
            Glide.with(UpdateActivity.this).load(getImageURL()).override(400,400).placeholder(R.drawable.user).error(R.drawable.error)
                    .centerCrop().crossFade().bitmapTransform(new CropCircleTransformation(UpdateActivity.this)).into(_USERImage);
           
        }
    }
    // Resize the image ====================================
    public Bitmap getResizedBitmap(Bitmap bm, int newHeight, int newWidth)
    {
        int width = bm.getWidth();
        int height = bm.getHeight();
        float scaleWidth = ((float) newWidth) / width;
        float scaleHeight = ((float) newHeight) / height;
        // create a matrix for the manipulation
        Matrix matrix = new Matrix();
        // resize the bit map
        matrix.postScale(scaleWidth, scaleHeight);
        // recreate the new Bitmap
        Bitmap resizedBitmap = Bitmap.createBitmap(bm, 0, 0, width, height, matrix, false);
        return resizedBitmap;
    }

    public String getRealPathFromURI(Uri contentUri) {
        Cursor cursor = null;
        try {
            String[] proj = { MediaStore.Images.Media.DATA };
            cursor = UpdateActivity.this.getContentResolver().query(contentUri,  proj, null, null, null);
            int column_index = cursor.getColumnIndexOrThrow(MediaStore.Images.Media.DATA);
            cursor.moveToFirst();
            return cursor.getString(column_index);
        } finally {
            if (cursor != null) {
                cursor.close();
            }
        }
    }

    public Uri getImageUri( Bitmap inImage) {
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        inImage.compress(Bitmap.CompressFormat.JPEG, 100, bytes);
        String path = MediaStore.Images.Media.insertImage(UpdateActivity.this.getContentResolver(), inImage, "Title", null);
        return Uri.parse(path);
    }

    public String getImageURL(){
        return "http://abdulbasit.website/blood_app/images/"+LoginActivity.ImageofLoggedINUser;
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.menu_update, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        String ChangesHappened = "no";
        if (item.getItemId() == R.id.done_update) {
                // start updating process
            if(_nameText.getText().toString().equals("")){
                ChangedName = null;
            }else {
                ChangedName = _nameText.getText().toString();
                ChangesHappened = "yes";
            }
            if(_passwordText.getText().toString().equals("")){
                ChangedPassword = null;
            }else {
                ChangedPassword = _passwordText.getText().toString();
                ChangesHappened = "yes";
            }
            if(_numText.getText().toString().equals("")){
                ChangedContactNo = null;
            }else {
                ChangedContactNo = _numText.getText().toString();
                ChangesHappened = "yes";
            }
            if(encodedPhotoString!=null){
                ChangesHappened = "yes";
            }
            if(ChangesHappened=="yes"){
                 StartUpdate();
                 return true;
            }else {
                Toast.makeText(getBaseContext(), "Nothing to update", Toast.LENGTH_SHORT).show();
            }
        }
        return super.onOptionsItemSelected(item);
    }

    private void StartUpdate() {
        ThingsTobeUpdated.put("email", LoginActivity.EmailofLoggedInUser);
        if (encodedPhotoString != null) {
            ThingsTobeUpdated.put("image", encodedPhotoString);
        }
        if (ChangedName != null) {
            ThingsTobeUpdated.put("name", ChangedName);
        }
        if (ChangedPassword != null) {
            ThingsTobeUpdated.put("password", ChangedPassword);
        }
        if (ChangedContactNo != null) {
            ThingsTobeUpdated.put("contact", ChangedContactNo);
        }
        UpdateAsync updatestart = new UpdateAsync();
        updatestart.execute();

    }


    public class UpdateAsync extends AsyncTask<Void, Void, Void> {

        private ProgressDialog pDialog;
        JSONObject json = null;
        @Override
        protected Void doInBackground(Void... voids) {
            json = new HttpCall().postForJSON("http://abdulbasit.website/blood_app/UpdateProfile.php", ThingsTobeUpdated);
            return null;
        }
        @Override
        protected void onPreExecute() {
            super.onPreExecute();
            pDialog = new ProgressDialog(UpdateActivity.this);
            pDialog.setMessage("Updating profile...");
            pDialog.setIndeterminate(false);
            pDialog.setCancelable(false);
            pDialog.show();
        }
        @Override
        protected void onPostExecute(Void aVoid) {
            super.onPostExecute(aVoid);
            pDialog.dismiss();
            if (json != null) {
                Toast.makeText(getBaseContext(), "Profile updated, Login Again to see changes", Toast.LENGTH_SHORT).show();
                finish();
            } else {
                Toast.makeText(getBaseContext(), "Error updating profile. Try Again", Toast.LENGTH_LONG).show();
            }
        }

    }
}


   private CropImageView mCropImageView;

    public static Bitmap finalImage = null;
    public static Bitmap newImage = null;
    private Uri mCropImageUri;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_crop);
        mCropImageView = (CropImageView) findViewById(R.id.CropImageView);

    }

    /**
     * On load image button click, start pick image chooser activity.
     */
    public void onLoadImageClick(View view) {
        startActivityForResult(getPickImageChooserIntent(), 400);
    }

    public void  onSetImageClick(View view) {

        if(UpdateActivity.UpdatingPhoto){
            newImage = mCropImageView.getCroppedImage(400, 400);
            try {
                Intent intent = new Intent(getApplicationContext(), UpdateActivity.class);
                startActivity(intent);
                finish();
            } catch (Exception e) {
                Toast.makeText(CroppingActivity.this, "Oppss..Error occured.", Toast.LENGTH_SHORT).show();
                e.printStackTrace();
            }

        }else {
            finalImage = mCropImageView.getCroppedImage(400, 400);
            try {
                Intent intent = new Intent(getApplicationContext(), UploadImage.class);
                startActivity(intent);
                finish();
            } catch (Exception e) {
                Toast.makeText(CroppingActivity.this, "Oppss..Error occured.", Toast.LENGTH_SHORT).show();
                e.printStackTrace();
            }
        }
    }
    /**
     * Crop the image and set it back to the cropping view.
     */
    public void onCropImageClick(View view) {
        Bitmap cropped = mCropImageView.getCroppedImage(400, 400);
        if (cropped != null)
            mCropImageView.setImageBitmap(cropped);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (resultCode == Activity.RESULT_OK) {
            Uri imageUri = getPickImageResultUri(data);

            // For API >= 23 we need to check specifically that we have permissions to read external storage,
            // but we don't know if we need to for the URI so the simplest is to try open the stream and see if we get error.
            boolean requirePermissions = false;
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M &&
                    checkSelfPermission(Manifest.permission.READ_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED &&
                    isUriRequiresPermissions(imageUri)) {

                // request permissions and handle the result in onRequestPermissionsResult()
                requirePermissions = true;
                mCropImageUri = imageUri;
                requestPermissions(new String[]{Manifest.permission.READ_EXTERNAL_STORAGE}, 0);
            }
            if (!requirePermissions) {
                mCropImageView.setImageUriAsync(imageUri);
            }
        }
    }

    @Override
    public void onBackPressed() {
        UpdateActivity.UpdatingPhoto = false;
        super.onBackPressed();
        finish();
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, String permissions[], int[] grantResults) {
        if (mCropImageUri != null && grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
            mCropImageView.setImageUriAsync(mCropImageUri);
        } else {
            Toast.makeText(this, "Required permissions are not granted", Toast.LENGTH_LONG).show();
        }
    }

    /**
     * Create a chooser intent to select the source to get image from.<br/>
     * The source can be camera's (ACTION_IMAGE_CAPTURE) or gallery's (ACTION_GET_CONTENT).<br/>
     * All possible sources are added to the intent chooser.
     */
    public Intent getPickImageChooserIntent() {

        // Determine Uri of camera image to save.
        Uri outputFileUri = getCaptureImageOutputUri();

        List<Intent> allIntents = new ArrayList<>();
        PackageManager packageManager = getPackageManager();

        // collect all camera intents
        Intent captureIntent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
        List<ResolveInfo> listCam = packageManager.queryIntentActivities(captureIntent, 0);
        for (ResolveInfo res : listCam) {
            Intent intent = new Intent(captureIntent);
            intent.setComponent(new ComponentName(res.activityInfo.packageName, res.activityInfo.name));
            intent.setPackage(res.activityInfo.packageName);
            if (outputFileUri != null) {
                intent.putExtra(MediaStore.EXTRA_OUTPUT, outputFileUri);
            }
            allIntents.add(intent);
        }

        // collect all gallery intents
        Intent galleryIntent = new Intent(Intent.ACTION_GET_CONTENT);
        galleryIntent.setType("image/*");
        List<ResolveInfo> listGallery = packageManager.queryIntentActivities(galleryIntent, 0);
        for (ResolveInfo res : listGallery) {
            Intent intent = new Intent(galleryIntent);
            intent.setComponent(new ComponentName(res.activityInfo.packageName, res.activityInfo.name));
            intent.setPackage(res.activityInfo.packageName);
            allIntents.add(intent);
        }

        // the main intent is the last in the list (fucking android) so pickup the useless one
        Intent mainIntent = allIntents.get(allIntents.size() - 1);
        for (Intent intent : allIntents) {
            if (intent.getComponent().getClassName().equals("com.android.documentsui.DocumentsActivity")) {
                mainIntent = intent;
                break;
            }
        }
        allIntents.remove(mainIntent);

        // Create a chooser from the main intent
        Intent chooserIntent = Intent.createChooser(mainIntent, "Select source");

        // Add all other intents
        chooserIntent.putExtra(Intent.EXTRA_INITIAL_INTENTS, allIntents.toArray(new Parcelable[allIntents.size()]));

        return chooserIntent;
    }

    /**
     * Get URI to image received from capture by camera.
     */
    private Uri getCaptureImageOutputUri() {
        Uri outputFileUri = null;
        File getImage = getExternalCacheDir();
        if (getImage != null) {
            outputFileUri = Uri.fromFile(new File(getImage.getPath(), "pickImageResult.jpeg"));
        }
        return outputFileUri;
    }

    /**
     * Get the URI of the selected image from {@link #getPickImageChooserIntent()}.<br/>
     * Will return the correct URI for camera and gallery image.
     *
     * @param data the returned data of the activity result
     */
    public Uri getPickImageResultUri(Intent data) {
        boolean isCamera = true;
        if (data != null && data.getData() != null) {
            String action = data.getAction();
            isCamera = action != null && action.equals(MediaStore.ACTION_IMAGE_CAPTURE);
        }
        return isCamera ? getCaptureImageOutputUri() : data.getData();
    }

    /**
     * Test if we can open the given Android URI to test if permission required error is thrown.<br>
     */
    public boolean isUriRequiresPermissions(Uri uri) {
        try {
            ContentResolver resolver = getContentResolver();
            InputStream stream = resolver.openInputStream(uri);
            stream.close();
            return false;
        } catch (FileNotFoundException e) {
            if (e.getCause() instanceof ErrnoException) {
                return true;
            }
        } catch (Exception e) {
        }
        return false;
    }
}
```

```
can't open /data/misc/app_oom.hprof: Permission denied
07-04 16:25:41.416 23278-23278/com.donateblood.blooddonation E/dalvikvm-heap:  hprofDumpHeap failed with result: -1 
07-04 16:25:41.416 23278-23278/com.donateblood.blooddonation E/dalvikvm-heap: After hprofDumpHeap for process
07-04 16:25:41.416 23278-23278/com.donateblood.blooddonation E/dalvikvm: Out of memory: Heap Size=76760KB, Allocated=13818KB, Limit=98304KB, Proc Limit=98304KB
07-04 16:25:41.416 23278-23278/com.donateblood.blooddonation E/dalvikvm: Extra info: Footprint=76760KB, Allowed Footprint=76760KB, Trimmed=16KB
07-04 16:25:41.436 23278-23278/com.donateblood.blooddonation E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.donateblood.blooddonation, PID: 23278
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.donateblood.blooddonation/com.donateblood.blooddonation.UpdateActivity}: java.lang.NullPointerException
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2596)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2653)
 at android.app.ActivityThread.access$800(ActivityThread.java:156)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:157)
 at android.app.ActivityThread.main(ActivityThread.java:5872)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:515)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
 at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
 at com.donateblood.blooddonation.UpdateActivity.CheckImage(UpdateActivity.java:93)
```

**Comment by youcaf** [comment]
@TWiStErRob  Can you please help me

**Comment by TWiStErRob** [comment]
*(This question was really for SO, since you've had this problem before even with Picasso.)*
It's curious that you attached an NPE stack trace for an OOM problem... here's what I think anyway:

I think you're just holding too many Bitmaps in memory at once. If you just do a quick bookkeeping how many things are actually in memory at the end of `CheckImage` you're already accumulating a lot:
 * `CroppingActivity.newImage` is a non-null Bitmap, of potentially big size
 * `_USERImage.getDrawable().getBitmap()` is a non-null bitmap, 500x500
 * `CroppingActivity.newImage` is overwritten by a 500x500 version
 * this image is then compressed into memory (likely insignificant because it's JPEG)
 (are there any other references? probably so, because it's not recycled here)
 * The Glide load will require a 500x500 Bitmap, and two 400x400 Bitmaps, most likely only 2 out of 3 at once.
 * `toByteArray` creates a copy of the stream's buffer
 * Base64 makes another copy of the same JPEG file

You can do better than this by dropping temporary object as soon as you're done with them. For example after you've compressed the bitmap you can say: `newImage.recycle(); newImage = null;` to help the GC do it's job.

This is just one piece of OOM, you should also look for other objects, there are a lot of Bitmap fields and manipulations going on. You should really look into how to diagnose OOMs, just create a heap dump and look at what's taking up the memory. You'll see the full object graph and you can search for Bitmap objects (a hunch that it's the problem), or leaked Activities. The app to use is MAT to analyze the dump.

Other notes:
 * in onCreate's `catch(OOM)` you still let the activity start up, I think you would want `Toast; finish(); return;` there..
 * You're encoding the JPEG file twice. JPEG compression is not for free, especially since you're doing it on the UI thread... at least you should be re-using `byte_arr` if you already have it, just reorder the lines. You can just dump those bytes into a File, there's no need to re-compress the same Bitmap.
