### ISSUE TITLE
Glide doesn't load image

### ISSUE THREAD

**Issue by meet2011** [bumptech/glide#1311]
Trying to load image in fragment but it doesn't work.

It says "Failed to load model" under **onException**

````Javascript
                Glide.with(PImageFragment.this).load(Utility.productBaseURL + image_url)
                .placeholder(R.drawable.ic_placeholder)
                .error(R.drawable.ic_placeholder)
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .crossFade()
                .listener(new RequestListener<String, GlideDrawable>() {
                    @Override
                    public boolean onException(Exception e, String model, Target<GlideDrawable> target,       boolean isFirstResource) {

                        Utility.showLog(TAG,"onFailed");
                        Utility.showLog(TAG, e.getLocalizedMessage());

                        return false;
                    }

                    @Override
                    public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {

                        Utility.showLog(TAG, "onResource Ready");
                        return false;
                    }
                })
                .into(ivProductImage);

**Comment by TWiStErRob** [comment]
The failure reason is hidden within the exception.
Please check https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

The key is to log more than the exception message, which `Log.d(TAG, "message", e)` does, you can also simply just `e.printStackTrace()` temporarily to see the reason.

Please reply with the full stack trace of the `e` argument.

**Comment by meet2011** [comment]
Full stack trace 

Unable to give image url due to restriction but can provide original image.
```Javascript
 java.lang.Exception: Failed to load model: ' '
                                                                                at com.bumptech.glide.request.GenericRequest.onSizeReady(GenericRequest.java:441)
                                                                                at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.notifyCbs(ViewTarget.java:177)
                                                                                at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.checkCurrentDimens(ViewTarget.java:193)
                                                                                at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.access$000(ViewTarget.java:161)
                                                                                at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer$SizeDeterminerLayoutListener.onPreDraw(ViewTarget.java:292)
                                                                                at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2000)
                                                                                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1073)
                                                                                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5988)
                                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                                at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:135)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5930)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
```

**Comment by TWiStErRob** [comment]
Is the url valid? Did you register a custom loader for `String.class` in a `GlideModule`?
Based on static code analysis, you will get this exception if the model is an empty string.

You could check why you get a null fetcher if you put a breakpoint
```
 at GenericRequest.onSizeReady(GenericRequest.java:438)
```
and step into the `getResourceFetcher` method.

**Comment by meet2011** [comment]
Yes URL is valid but i haven't registered anything in ` GlideModule`

**Comment by meet2011** [comment]
I have removed the URL from the line "Failed to load model" but i do get the URL over there. What can be done to fix the issue?

**Comment by TWiStErRob** [comment]
Debug, as I said above.

**Comment by meet2011** [comment]
Where i will get those methods?

**Comment by TWiStErRob** [comment]
In your IDE: open type `GenericRequest` then scroll down to `onSizeReady` and put a breakpoint on the line.

**Comment by meet2011** [comment]
is it compulsory to define height and width of image view?

**Comment by TWiStErRob** [comment]
In Android, yes. Glide should handle match and wrap as well. What did you find?

**Comment by meet2011** [comment]
I got the following details after putting breakpoint on the line `onSizeReady`

````
this = {GenericRequest@20137} 
width = 800
height = 500
startTime = 36766241607374
status = {GenericRequest$Status@19743} "WAITING_FOR_SIZE"



this = {GenericRequest@20137} 
width = 800
height = 500
resource = null
loadedFromMemoryCache = false
startTime = 36766241607374

**Comment by TWiStErRob** [comment]
So the size is correct, and it's ready to be queued up, try to stop on the lines:
```java
        ModelLoader<A, T> modelLoader = loadProvider.getModelLoader();
        final DataFetcher<T> dataFetcher = modelLoader.getResourceFetcher(model, width, height);
```
Note down what the concrete type of `modelLoader` is.
Then step *into* `getResourceFetcher` to find out why it is returning a `null`.
See the Run menu for different Step commands.

Something else to check: do you have any special characters in your url? (other than `a-zA-Z0-9/_.-`)

**Comment by meet2011** [comment]
Another details after putting breakpoint on `ModelLoader` line

```
this = {GenericRequest@20005} 
width = 680
height = 500
startTime = 39500473481226
status = {GenericRequest$Status@19741} "WAITING_FOR_SIZE"

this = {GenericRequest@20005} 
width = 680
height = 500
sizeMultiplier = 1.0
model = " https://api1.kicksexchangeapp.com/kicksexchange/assets/products/055b2bf189.jpg"
loadProvider = {ChildLoadProvider@20018} 

this = {GenericRequest@20005} 
width = 680
height = 500
modelLoader = {ImageVideoModelLoader@20031} 
model = " https://api1.kicksexchangeapp.com/kicksexchange/assets/products/055b2bf189.jpg"
loadProvider = {ChildLoadProvider@20018} 


this = {GenericRequest@20005} 
width = 680
height = 500
resource = null
loadedFromMemoryCache = false
startTime = 39500473481226

**Comment by TWiStErRob** [comment]
There's a space at the beginning of your model...

**Comment by meet2011** [comment]
Working Perfectly 👍  Thanks for helping.

**Comment by TWiStErRob** [comment]
You still have your urls visible, didn't you want to hide them?

**Comment by meet2011** [comment]
Urls are removed now. I do have another question regarding circleImageView with Glide, can i ask here?

**Comment by TWiStErRob** [comment]
Read https://github.com/bumptech/glide#compatibility first, if that doesn't help please open a new issue.

*It's easier to duplicate issues if they're distinct problems. It also helps if you don't hijack a totally different issue. Just remember what your original comment was on ([#662](https://github.com/bumptech/glide/%69ssues/662)) and what your problem turned out to be. "It doesn't work" can have unlimited root causes.*

**Comment by safeer-ahmed** [comment]
I experienced the same issue while loading images in recyclerview. But in my case issue is gone when i removed RecyclerView.SmoothScroller for navigating recyclerview to top upon loading a new list. So, it seems its somewhere tied with Scrolling.
