### ISSUE TITLE
SkImageDecoder::Factory returned null, When loading file from disk

### ISSUE THREAD

**Issue by spidergears** [bumptech/glide#1330]
**Glide Version**:  'com.github.bumptech.glide:glide:3.7.0'

**Integration libraries**: No

**Device/Android Version**: Moto G2, Android 6.0 Lollipop

**Issue details / Repro steps / Use case background**: 
Image does not show up in the image_preview view, instead it thows a RuntimeException
java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
See logs attached. 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
ImageView previewView = (ImageView) this.findViewById(R.id.image_preview);
File file = new File(capturedPhotoPath);
Glide
                .with(this)
                .load(file)
                .listener(new RequestListener<File, GlideDrawable>() {
                    @Override
                    public boolean onException(Exception e, File model, Target<GlideDrawable> target, boolean isFirstResource) {
                        Log.e(getString(R.string.app_name), "Exception occurred while loading image", e);
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(GlideDrawable resource, File model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                        return false;
                    }
                })
                .error(R.drawable.kid)
                .into(previewView);
```

**Layout XML**:
```xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context="com.me.myapplication.PreviewActivity">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <TextView
            android:id="@+id/textView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="Preview"
            android:gravity="center"
            android:textAppearance="?android:attr/textAppearanceLarge" />

        <ImageView
            android:id="@+id/image_preview"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:adjustViewBounds="true"
            android:scaleType="center"
            android:visibility="visible" />

    </LinearLayout>
</RelativeLayout>

```

**Stack trace / LogCat**:
```ruby
03:33:39.044 30084-30084/? D/MyApplication: Photo is successfully saved to [/storage/emulated/0/Pictures/MyApplication/IMG-20160712-033331-187428771.jpg]
07-12 03:33:39.047 1782-3820/? I/ActivityManager: START u0 {<ActivityName> (has extras)} from uid 10219 on display 0
07-12 03:33:39.049 23826-23826/? D/MediaScannerReceiver: action: android.intent.action.MEDIA_SCANNER_SCAN_FILE path: /storage/emulated/0/Pictures/MyApplication/IMG-20160712-033331-187428771.jpg
07-12 03:33:39.060 407-30353/? E/mm-camera-sensor: Got some events
07-12 03:33:39.060 407-30353/? E/mm-camera-sensor: sensor_thread_func:152 sensor_thread_func:Sensor thread is exiting
07-12 03:33:39.081 30084-30112/? I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/09/15, 6cbbf7d, I3193f6e94a
07-12 03:33:39.081 30084-30112/? I/OpenGLRenderer: Initialized EGL, version 1.4
07-12 03:33:39.185 30084-30458/? D/skia: --- SkImageDecoder::Factory returned null
07-12 03:33:39.186 30084-30458/? D/skia: --- SkImageDecoder::Factory returned null
07-12 03:33:39.191 377-377/? E/MetadataRetrieverClient: offset (0) bigger than file size (0)
07-12 03:33:39.193 23826-30455/? D/skia: --- SkImageDecoder::Factory returned null
07-12 03:33:39.222 30084-30084/? E/MyApplication: Exception occurred while loading image
                                                      java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
                                                          at android.media.MediaMetadataRetriever.setDataSource(Native Method)
                                                          at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:144)
                                                          at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:46)
                                                          at com.bumptech.glide.load.resource.bitmap.FileDescriptorBitmapDecoder.decode(FileDescriptorBitmapDecoder.java:45)
                                                          at com.bumptech.glide.load.resource.bitmap.FileDescriptorBitmapDecoder.decode(FileDescriptorBitmapDecoder.java:19)
                                                          at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:50)
                                                          at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)
                                                          at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeBitmapWrapper(GifBitmapWrapperResourceDecoder.java:121)
                                                          at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeStream(GifBitmapWrapperResourceDecoder.java:94)
                                                          at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:71)
                                                          at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:61)
                                                          at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:22)
                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:190)
                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
                                                          at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
                                                          at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
                                                          at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                          at java.lang.Thread.run(Thread.java:818)
                                                          at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
```

```

```

**Comment by TWiStErRob** [comment]
Did you into "file size (0)". It looks like Glide is trying a possible ways to get an image for you, but you're trying an empty file.

**Comment by spidergears** [comment]
Yes, you are right. I overlooked it. My bad.
Looks like something is wrong with `ACTION_MEDIA_SCANNER_SCAN_FILE` intent.
Its proper file to gallery for the first capture after app starts up.
On subsequent captures, an empty is saved to Gallery.

This not Glide's fault.
I will close the issue. I am still unable to figure out `ACTION_MEDIA_SCANNER_SCAN_FILE` intent.

**Comment by TWiStErRob** [comment]
That intent should only read the file, not modify it. Check if the file is written correctly, and if not, why?
Note: You don't need to add an image to media store to show it with Glide, but it must be non-0 length.
