### ISSUE TITLE
Sharing Image With Glide

### ISSUE THREAD

**Issue by venkymsnv** [bumptech/glide#1355]
I want to share the images using glide,which are available in the cache,
`      return Glide
                        .with(context)
                        .load(url)
                        .downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                        .get();`
I have gone through the issues #459, #[411](https://github.com/bumptech/glide/issues/411) but could not get a solution for this.Please let me know any changes required
I am  getting error in below line
` Uri uri = FileProvider.getUriForFile(getApplicationContext(),"com.abc.photos", result);`
error as

>   java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
            at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:560)
            at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:534)
            at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:376)
            at shopi.online.ng6.flicker.FullscreenActivity$ShareTask.onPostExecute(FullscreenActivity.java:248)
            at shopi.online.ng6.flicker.FullscreenActivity$ShareTask.onPostExecute(FullscreenActivity.java:221)
            at android.os.AsyncTask.finish(AsyncTask.java:636)
            at android.os.AsyncTask.access$500(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5343)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by TWiStErRob** [comment]
Did you try http://stackoverflow.com/q/30896130/253468?
