### ISSUE TITLE
[AppWidget/RemoteViews] IllegalArgumentException: You must call this method on the main thread

### ISSUE THREAD

**Issue by MGaetan89** [bumptech/glide#1363]
**Glide Version**: 3.7.0
**Integration libraries**:
- okhttp-integration 1.4.0
- [glide-transformations](https://github.com/wasabeef/glide-transformations) 2.0.1

**Device/Android Version**: Nexus 5 Emulator, Android 6.0 (with Google APIs)
**Issue details / Repro steps / Use case background**:
I am trying to use Glide to load an image from the network and display it inside an app widget.
To do so, I use an `AppWidgetTarget` as a parameter of the `into` method, but it ends up in a crash because the call is made on the wrong `Thread`.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
BitmapRequestBuilder<ModelType, TranscodeType> glide = Glide.with(context)
    .load(url)
    .asBitmap()
    .diskCacheStrategy(DiskCacheStrategy.ALL)

    if (circleTransform) {
        glide.transform(new CropCircleTransformation(context))
    }

    glide.into(new AppWidgetTarget(context, remoteViews, viewId, appWidgetId))
```

This code runs inside a `RemoteViewsFactory`, in the `getViewAt(int)` method.
- `context` is the instance of the `RemoteViewsService`, which created this `RemoteViewsFactory`
- `remoteViews` is an instance of the `RemoteViews` class, created in the `getViewAt(int)` method
- `viewId` is the id of the remote `ImageView` that should display the loaded image.

**Stack trace / LogCat**:
```ruby
E/AndroidRuntime: FATAL EXCEPTION: Binder_1
        Process: com.mgaetan89.showsrage.dev, PID: 14272
        java.lang.IllegalArgumentException: You must call this method on the main thread
        at com.bumptech.glide.util.Util.assertMainThread(Util.java:135)
        at com.bumptech.glide.GenericRequestBuilder.into(GenericRequestBuilder.java:642)
        at com.mgaetan89.showsrage.helper.ImageLoader.load(ImageLoader.kt:39)
        at com.mgaetan89.showsrage.widget.HistoryWidgetFactory.getViewAt(HistoryWidgetFactory.kt:43)
        at android.widget.RemoteViewsService$RemoteViewsFactoryAdapter.getViewAt(RemoteViewsService.java:164)
        at com.android.internal.widget.IRemoteViewsFactory$Stub.onTransact(IRemoteViewsFactory.java:85)
        at android.os.Binder.execTransact(Binder.java:453)
```

I found [this issue](https://github.com/bumptech/glide/issues/310), which looks similar to mine, but it's for an older version of `Glide` and I didn't find anything to help me there.

**Comment by TWiStErRob** [comment]
The last https://github.com/bumptech/glide/issues/310#issuecomment-71136379 is still valid. You simply need to be on the main thread which has `Looper.getMainLooper()`. Glide is async anyway, so even if you were able to call `into`, the image wouldn't be ready immediately. I think what you need is something like:
```java
// prepare `glide` request builder
runOnUiThread({
    glide.into(new AppWidgetTarget(context, remoteViews, viewId, appWidgetId));
});
return remoteViews;
```
Look into the `into(int,int)` exception Sam mentioned, you'll see that it does the same.

If you know a better way, feel free to open a PR. `AppWidgetTarget` was contributed by someone too, it may only cover a very specific use case.

**Comment by MGaetan89** [comment]
Oh, you're right. I miss-interpreted that comment.
I updated my code as follow:

```java
BitmapRequestBuilder<ModelType, TranscodeType> glide = Glide.with(context)
    .load(url)
    .asBitmap()
    .diskCacheStrategy(DiskCacheStrategy.ALL)

    if (circleTransform) {
        glide.transform(new CropCircleTransformation(context))
    }

FutureTarget<TranscodeType> bitmap = it.into(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
remoteViews.setImageViewBitmap(viewId, bitmap.get())
Glide.clear(bitmap)
```

But I have the following exception now:

```
java.util.concurrent.ExecutionException: java.io.FileNotFoundException: No such file or directory
   at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:189)
   at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:100)
   at com.mgaetan89.showsrage.helper.ImageLoader.load(ImageLoader.kt:41)
   at com.mgaetan89.showsrage.widget.HistoryWidgetFactory.getViewAt(HistoryWidgetFactory.kt:40)
   at android.widget.RemoteViewsService$RemoteViewsFactoryAdapter.getViewAt(RemoteViewsService.java:164)
   at com.android.internal.widget.IRemoteViewsFactory$Stub.onTransact(IRemoteViewsFactory.java:85)
   at android.os.Binder.execTransact(Binder.java:453)
Caused by: java.io.FileNotFoundException: No such file or directory
   at android.os.Parcel.openFileDescriptor(Native Method)
   at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:270)
   at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:200)
   at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:937)
   at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:865)
   at com.bumptech.glide.load.data.FileDescriptorLocalUriFetcher.loadResource(FileDescriptorLocalUriFetcher.java:21)
   at com.bumptech.glide.load.data.FileDescriptorLocalUriFetcher.loadResource(FileDescriptorLocalUriFetcher.java:14)
   at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
   at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:83)
   at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:53)
   at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
   at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
   at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
   at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
   at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
   at java.lang.Thread.run(Thread.java:818)
   at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
```

**Comment by TWiStErRob** [comment]
Did you double-check that the Uri is correct and it exists? Glide can't do anything if you pass in invalid models, it only reads what you tell it. You probably had the same exception, but `.get()` throws it out, while in an async load you only get notified in a `.listener`. See https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

**Comment by MGaetan89** [comment]
The URL is correct, because it works fine in the application itself.
But I guess there is an issue when I run my application in the emulator. Because if I remove the widget and add it again, it works fine.
Thanks for your help and information!

**Comment by ygl750994280** [comment]
How to resole this problem?
