### ISSUE TITLE
Canvas: trying to use a recycled bitmap

### ISSUE THREAD

**Issue by pauliktamas** [bumptech/glide#1368]
**Glide Version**: 3.7.0
Glide README.md says I should use 
```
'com.android.support:support-v4:19.1.0'
```
but I'm using 
```
'com.android.support:support-v4:24.1.1'
```
Don't know if it can cause the problem

**Device/Android Version**: Nexus 5X - Android 6.0.1

**Issue details / Repro steps / Use case background**: 
I have a RecyclerView with CardViews inside. I'm loading images into the ViewHolder with placeholder and error images. I just keep scrolling up and down in the RecyclerView (~500 items) and the app sometimes crashes with the Stacktrace below. 

I need to show a ProgressBar with a different background when loading, and then display the image with a gradient overlay on it, when the image is ready.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
private SimpleTarget target = new SimpleTarget<Bitmap>() {
        @Override
        public void onLoadStarted(Drawable placeholder) {
                mFlBackground.setBackground(placeholder);
        }

        @Override
        public void onResourceReady(Bitmap bitmap, GlideAnimation<? super Bitmap> glideAnimation) {
                mFlBackground.setBackground(null);
                mIvPreviewImage.setImageBitmap(bitmap);
                changeVisibilitiesAfterLoading(true);
        }

        @Override
        public void onLoadFailed(Exception e, Drawable errorDrawable) {
                mFlBackground.setBackground(null);
                mIvPreviewImage.setImageDrawable(errorDrawable);
                changeVisibilitiesAfterLoading(false);
        }
};

public void bindSector(...) {
        ...
        Glide.with(context)
                .load(BuildConfig.SERVER_URL + sector.getImageUrl())
                .asBitmap()
                .placeholder(R.drawable.image_placeholder)
                .error(R.drawable.image_placeholder)
                .dontAnimate()
                .into(target);
       ...
}

private void changeVisibilitiesAfterLoading(boolean isSuccess) {
        if (isSuccess) {
                mIvPreviewImage.setVisibility(View.VISIBLE);
                mLlGradientOverlay.setVisibility(View.VISIBLE);
        }

        mPbLoader.setVisibility(View.GONE);
}
```

**Layout XML**:
```xml
<FrameLayout
        android:id="@+id/fl_background"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <ImageView
                android:id="@+id/iv_preview"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:scaleType="centerCrop"
                tools:ignore="ContentDescription" />

            <LinearLayout
                android:id="@+id/gradient_overlay"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="@drawable/sector_card_overlay_vertical_gradient"
                android:orientation="vertical"
                android:visibility="gone" />

            <include
                layout="@layout/loader"
                android:layout_width="@dimen/default_spinner_size"
                android:layout_height="@dimen/default_spinner_size"
                android:layout_alignParentEnd="true"
                android:layout_marginEnd="@dimen/sector_card_padding"
                android:layout_marginTop="@dimen/sector_card_padding" />
        </RelativeLayout>
</FrameLayout>
```

**Stack trace / LogCat**:
```ruby
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@342ab43
        at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
        at android.graphics.Canvas.drawBitmap(Canvas.java:1404)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:544)
        at android.widget.ImageView.onDraw(ImageView.java:1246)
        at android.view.View.draw(View.java:16184)
        at android.view.View.updateDisplayListIfDirty(View.java:15180)
        at android.view.View.draw(View.java:15954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.updateDisplayListIfDirty(View.java:15175)
        at android.view.View.draw(View.java:15954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.draw(View.java:16187)
        at android.view.View.updateDisplayListIfDirty(View.java:15180)
        at android.view.View.draw(View.java:15954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.draw(View.java:16187)
        at android.view.View.updateDisplayListIfDirty(View.java:15180)
        at android.view.View.draw(View.java:15954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
        at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4134)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
        at android.view.View.draw(View.java:16187)
        at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3543)
        at android.view.View.updateDisplayListIfDirty(View.java:15180)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15140)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15140)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15140)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15140)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15140)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15140)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15140)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15140)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15140)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15140)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
        at android.view.ViewRootImpl.d
```

**Comment by TWiStErRob** [comment]
Custom targets are not easy to get right. I'm assuming all this code is in a ViewHolder. I think you should consider using a view target like below:
```java
private final LoaderListener listener = new LoaderListener();
private class LoaderListener implements RequestListener<String, GlideDrawable> {
	public void onLoadStarted() { // not an override, just to encapsulate behavior
		mPbLoader.setVisibility(View.VISIBLE);
		mLlGradientOverlay.setVisibility(View.INVISIBLE);
		// or mIvPreviewImage.setForeground(null);
	}
	@Override public boolean onException(Exception e,
			String model, Target<GlideDrawable> target, boolean isFirstResource) {
		mPbLoader.setVisibility(View.INVISIBLE);
		mLlGradientOverlay.setVisibility(???);
		// or mIvPreviewImage.setForeground(???);
		return false;
	}
	@Override public boolean onResourceReady(GlideDrawable resource,
			String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
		mPbLoader.setVisibility(View.INVISIBLE);
		mLlGradientOverlay.setVisibility(View.VISIBLE);
		// or mIvPreviewImage.setForeground(R.drawable.sector_card_overlay_vertical_gradient);
		return false;
	}
}

public void bindSector(...) {
	String url = BuildConfig.SERVER_URL + sector.getImageUrl();
	//mIvPreviewImage.setVisibility(View.VISIBLE); // no need, always visible
	listener.onLoadStarted();
	Glide.with(context)
	     .load(url)
	     .placeholder(R.drawable.glide_placeholder)
	     .error(R.drawable.glide_placeholder) // consider changing it to something else to signify a failed load
	     .listener(listener)
	     .dontAnimate()
	     .centerCrop()
	     .into(mIvPreviewImage);
```

```xml
<FrameLayout
	android:layout_width="match_parent"
	android:layout_height="match_parent">
	<ImageView
		android:id="@+id/iv_preview"
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		android:scaleType="fitCenter"
		tools:ignore="ContentDescription" />

	<View
		android:id="@+id/gradient_overlay"
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		android:background="@drawable/sector_card_overlay_vertical_gradient"
		android:visibility="invisible"
		tools:visibility="visible" />

	<include
		layout="@layout/loader"
		android:layout_width="@dimen/default_spinner_size"
		android:layout_height="@dimen/default_spinner_size"
		android:layout_gravity="top|end"
		android:layout_marginStart="@dimen/sector_card_padding"
		android:layout_marginEnd="@dimen/sector_card_padding"
		android:layout_marginTop="@dimen/sector_card_padding" />
</FrameLayout>
```

Here are the changes I made and the reasons:
 * Separate progress display and image loading so Glide can work it's magic better when loading the image, and it gets rid of the custom target.
 * Use INVISIBLE instead of GONE because it helps preventing layout, the scrolling should be smoother as a result. Visibilty of the loader changes quite a lot because of recycling.
 * No need to put the placeholder in the background, I just set up Glide and the ImageView to hopefully achive the same effect. I'm guessing cropping is why you had it in the background.
 * Changed gradient overlay to View, because you don't need a layout there. Note that there's also a View.setForeground method where you could set your overlay.
 * Removed redundant layout, a FrameLayout should cover all you need (notice the gravity).

I hope you can reproduce it quite consistently and test if these fix the problem.

**Comment by pauliktamas** [comment]
Thank you for the help!

I managed to change my code as you suggested and i've been scrolling for quite a while without any app crashes, so I guess it worked. :)
