### ISSUE TITLE
Socket Timeout Exception

### ISSUE THREAD

**Issue by Sutirth** [bumptech/glide#1375]
Glide version: compile 'com.github.bumptech.glide:glide:3.7.0'

Scenario: Glide image fails to load with socket timeout Exception

```
D: onException(null,myURL
D: LazyHeaders{headers={access_token=[StringHeaderFactory{value='20f0c022-e1da-4cf0-9c09-b0675435b647'}], User-Agent=[StringHeaderFactory{value='Dalvik/2.1.0 (Linux; U; Android 6.0.1; Nexus 6P Build/MTC19X)'}], Accept-Encoding=[StringHeaderFactory{value='identity'}]}}, Target for: de.hdodenhof.circleimageview.CircleImageView{f15d013 V.ED..... ........ 35,70-371,406 #7f1001ad app:id/profilePicUser}, true)
D: java.net.SocketTimeoutException: timeout
D:     at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:207)
D:     at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
D:     at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
D:     at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
D:     at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
D:     at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
D:     at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
D:     at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
D:     at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904)
D:     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
D:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
D:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
D:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501)
D:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
D:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
D:     at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:76)
D:     at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:44)
D:     at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:20)
D:     at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:70)
D:     at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:53)
D:     at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
D:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
D:     at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
D:     at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
D:     at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
D:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
D:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
D:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
D:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
D:     at java.lang.Thread.run(Thread.java:818)
D:     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
```

Glide module load code:

```
  GlideUrl glideUrl = new GlideUrl(URL, new LazyHeaders.Builder()
                .addHeader("access_token", ACCESS_TOKEN)
                .build());


        Glide.with(getApplicationContext()).load(glideUrl)
                .signature(new StringSignature(profileImageUpdateAt))
                .dontAnimate()
                .listener(new RequestListener<GlideUrl, GlideDrawable>() {
                              @Override
                              public boolean onException(Exception e, GlideUrl model, Target<GlideDrawable> target, boolean isFirstResource) {
                                  android.util.Log.d("GLIDE", String.format(Locale.ROOT,
                                          "onException(%s, %s, %s, %s)", e.getCause(), model, target, isFirstResource), e);

                                  return false;

                              }

                              @Override
                              public boolean onResourceReady(GlideDrawable resource, GlideUrl model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                                  txtProfileInitials.setVisibility(View.GONE);
                                  profilePicUser.setVisibility(View.VISIBLE);
                                  android.util.Log.d("GLIDE", String.format(Locale.ROOT,
                                          "onResourceReady(%s, %s, %s, %s, %s)", resource, model, target, isFromMemoryCache, isFirstResource));

                                  return false;
                              }
                          }

                )
                .into(profilePicUser);
```

Basically I always get ending up with Socket timeout exception.

**Comment by 80998062** [comment]
Maybe #432 can help you...

**Comment by TWiStErRob** [comment]
Yep, the defaults may be too low for your server/connection.

**Comment by Sutirth** [comment]
@TWiStErRob  Could you please explain a bit more "the defaults may be too low for your server/connection."

**Comment by TWiStErRob** [comment]
[HttpUrlFetcher timeout](https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/data/HttpUrlFetcher.java#L66-L67) is used when no integration library present: 2.5 seconds currently. Don't be confused about `okhttp` in the stack trace, Android internally uses a version of that, but it's all hidden behind standard Java APIs.

#432 suggests to add the okhttp integration library, which would allow you to set the timeouts relatively easily, because it would stop using the default `HttpUrlFetcher`.
