### ISSUE TITLE
Getting a crash in Glide 3.3 library

### ISSUE THREAD

**Issue by GargManish** [bumptech/glide#138]
Hi All,

I have seen one random crash in my application which was due to Glide image loading. Please find below the logs.

There is one more issue which I am facing. Sometime Glide is displaying random images. It is displaying those images which had been downloaded in other activity.

``` ruby
14-Sep-2014 08:41:31 PM java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
    at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:63)
    at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:29)
    at com.bumptech.glide.Glide.with(Glide.java:537)
    at com.miamiheat.common.MHImageDownloadWrapper.loadImage(MHImageDownloadWrapper.java:12)
    at com.miamiheat.ui.module.MHWallpaperModule.setWallpaperViewData(MHWallpaperModule.java:234)
    at com.miamiheat.ui.module.MHWallpaperModule.taskManagerResponseCallback(MHWallpaperModule.java:257)
    at com.miamiheat.service.taskmanager.MHWallpaperTaskManager.asyncResultCallback(MHWallpaperTaskManager.java:133)
    at com.miamiheat.service.framework.MHAsyncServiceTask.onPostExecute(MHAsyncServiceTask.java:191)
    at android.os.AsyncTask.finish(AsyncTask.java:631)
    at android.os.AsyncTask.access$600(AsyncTask.java:177)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:176)
    at android.app.ActivityThread.main(ActivityThread.java:5419)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:525)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Cliffus** [comment]
is there a reason why Glide doesn't always use the Application Context? The reason why people use libraries such as Glide is that they don't have to worry about the little details which can cause your application to crash.

Thanks for your feedback!

**Comment by TWiStErRob** [comment]
Please open a new issue, this is rather old, the current version is 3.6.1.

**Comment by Cliffus** [comment]
correct, but I'm having the exact same issue (which is apparently not an issue, but a feature ;-), should I really open a new ticket? I'm only suggesting an improvement.

**Comment by TWiStErRob** [comment]
It won't be an improvement because it would be against the resource sensitive nature of Android/Glide. Glide uses the object given in `Glide.with` to attach a fragment to, which obviously cannot be done for an app context. This fragment cancels/pauses any load to prevent unnecessary background work if the result would not be used anyway. See for example http://stackoverflow.com/a/32887693/253468.

That little detail you mentioned can mean battery drain or memory leak in your app, which, thanks to Glide, is now surfaced. Why do you think that starting a load after the activity (where the image would be potentially displayed) has been destroyed is good idea?

**Comment by Cliffus** [comment]
ok, that totally makes sense, but do you also get that crashing the app isn't a good solution too? I currently worked around this issue, but it isn't pretty.

What's the 'official' way of handling these situations, because our app sometimes crashes because of the IllegalArgumentException, even when we think we handled all the edge cases.

**Comment by Cliffus** [comment]
(the workaround I mentioned: check if the Activity is finishing, if so, stop loading the image)

**Comment by TWiStErRob** [comment]
Is `isFinishing` true when the activity is fully destroyed? (I.e.`isDestroyed` is true)
Can you share some code? It would be nice to fully see the case when this happens.

**Comment by Cliffus** [comment]
well, we are currently in our last sprint to release the application. When I've collected some more crash data, I'll try to share it with you.

**Comment by cristiano939** [comment]
I'm having the exact same issue, right now,
but the app isn't destroying the activity, all of a sudden it happens.
It could be caused by a recycleview or something like that?

**Comment by TWiStErRob** [comment]
Please open a new issue with more information on **your** case, just write #138 to reference this issue. For example what are you doing as user just before that "all of a sudden" and what are you doing as a dev (code) just before that "all of a sudden".

**Comment by shivangbtech** [comment]
Getting Same Problem.

**Comment by Mr-Wu** [comment]
good
