### ISSUE TITLE
NullPointerException ManifestParser.parse(ManifestParser.java:27)

### ISSUE THREAD

**Issue by jemshit** [bumptech/glide#1386]
I'm using Glide in my CustomView, i give Glide a context which i get from Constructor of CustomView. CustomView is initiated from XML layout, not from java code. I get below code on AS LayoutEditor preview screen. 
```
Glide.with(context.getApplicationContext())
```

Error:
```
java.lang.NullPointerException
	at com.bumptech.glide.module.ManifestParser.parse(ManifestParser.java:27)
	at com.bumptech.glide.Glide.get(Glide.java:149)
	at com.bumptech.glide.RequestManager.<init>(RequestManager.java:62)
	at com.bumptech.glide.RequestManager.<init>(RequestManager.java:53)
	at com.bumptech.glide.manager.RequestManagerRetriever.getApplicationManager(RequestManagerRetriever.java:73)
	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:95)
	at com.bumptech.glide.Glide.with(Glide.java:629)
	at com.pordiva.skylife.controller.ImageLoadController.load(ImageLoadController.java:647)
	at com.pordiva.skylife.component.custom_views.KesfetCategoryView.applyAttributes(KesfetCategoryView.java:101)
	at com.pordiva.skylife.component.custom_views.KesfetCategoryView.initializeAndApply(KesfetCategoryView.java:82)
	at com.pordiva.skylife.component.custom_views.KesfetCategoryView.<init>(KesfetCategoryView.java:76)
	at sun.reflect.GeneratedConstructorAccessor437.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:465)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:172)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:105)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:176)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:247)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:171)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:835)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:838)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:838)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:838)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:229)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:426)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:520)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:508)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:967)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:508)
	at com.android.tools.idea.rendering.RenderTask.access$600(RenderTask.java:75)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:620)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:617)
	at com.android.tools.idea.rendering.RenderService.runRenderAction(RenderService.java:371)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:617)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:639)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.doRender(AndroidLayoutPreviewToolWindowManager.java:654)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.access$1700(AndroidLayoutPreviewToolWindowManager.java:82)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7$1.run(AndroidLayoutPreviewToolWindowManager.java:596)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7.run(AndroidLayoutPreviewToolWindowManager.java:591)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:271)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:286)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:244)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by TWiStErRob** [comment]
Hmm, it looks like `appInfo` is null @ https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/module/ManifestParser.java#L27

Can you please debug what package name is there?

**Comment by jemshit** [comment]
i can't debug, it doesnt stop there

**Comment by TWiStErRob** [comment]
Try putting the breakpoint on the method entry and step lines. That usually works even of the code is out of sync to the byte code.

**Comment by jemshit** [comment]
i stops one when i use Glide in Activity, where appInfo is not null but appInfo.metaData is null. But still it doesn't stop when i use Glide inside CustomView

**Comment by TWiStErRob** [comment]
Aaah, I just understood that you're trying to initialize Glide in the layout editor. Of course the debugger won't stop there. There's no development-time support for Glide, you have to make sure you use Glide only in the real environment. Wrap any Glide calls in [`!isInEditMode()`](https://developer.android.com/reference/android/view/View.html#isInEditMode()).
