### ISSUE TITLE
Fatal Exception with Proguard enabled

### ISSUE THREAD

**Issue by JeffreyCA** [bumptech/glide#1392]
**Glide Version**: 3.7.0

**Integration libraries**: Volley

**Device/Android Version**: LG G3 6.0.1

**Issue details / Repro steps / Use case background**: 
I get a `FATAL EXCEPTION` when Proguard is enabled in my release build of my app and the error points to the Volley Integration library. The app does not crash, but I still get this error shown below.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```
**build.gradle (relevant parts)**:
```java
compile 'com.github.bumptech.glide:glide:3.7.0'
compile 'com.github.bumptech.glide:volley-integration:1.4.0@aar'
```

**proguard-rules.pro**:
```java
-keep class android.support.v4.app.** { *; }
-keep interface android.support.v4.app.** { *; }
-keep class android.support.v7.app.** { *; }
-keep interface android.support.v7.app.** { *; }
-keep class com.bumptech.glide.integration.volley.VolleyGlideModule
```

**Stack trace / LogCat**:
```ruby
08-05 15:01:13.901 21922-21922/ca.jeffrey.myapp E/AndroidRuntime: FATAL EXCEPTION: main
Process: ca.jeffrey.myapp, PID: 21922
java.lang.IllegalArgumentException: Unable to find GlideModule implementation
	at com.b.a.f.b.a(Unknown Source)
	at com.b.a.f.b.a(Unknown Source)
	at com.b.a.h.a(Unknown Source)
	at com.b.a.l.<init>(Unknown Source)
	at com.b.a.l.<init>(Unknown Source)
	at com.b.a.e.o.a(Unknown Source)
	at com.b.a.e.o.a(Unknown Source)
	at com.b.a.h.a(Unknown Source)
	at ca.jeffrey.myapp.MainActivity.a(Unknown Source)
	at ca.jeffrey.myapp.MainActivity.a(Unknown Source)
	at ca.jeffrey.myapp.h.a(Unknown Source)
	at ca.jeffrey.myapp.h.a(Unknown Source)
	at com.a.a.a.m.a(Unknown Source)
	at ca.jeffrey.myapp.j.a(Unknown Source)
	at ca.jeffrey.myapp.j.a(Unknown Source)
	at com.a.a.i.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5421)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
 Caused by: java.lang.ClassNotFoundException: com.bumptech.glide.integration.volley.VolleyGlideModule
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:324)
	at java.lang.Class.forName(Class.java:285)
	at com.b.a.f.b.a(Unknown Source) 
	at com.b.a.f.b.a(Unknown Source) 
	at com.b.a.h.a(Unknown Source) 
	at com.b.a.l.<init>(Unknown Source) 
	at com.b.a.l.<init>(Unknown Source) 
	at com.b.a.e.o.a(Unknown Source) 
	at com.b.a.e.o.a(Unknown Source) 
	at com.b.a.h.a(Unknown Source) 
	at ca.jeffrey.myapp.MainActivity.a(Unknown Source) 
	at ca.jeffrey.myapp.MainActivity.a(Unknown Source) 
	at ca.jeffrey.myapp.h.a(Unknown Source) 
	at ca.jeffrey.myapp.h.a(Unknown Source) 
	at com.a.a.a.m.a(Unknown Source) 
	at ca.jeffrey.myapp.j.a(Unknown Source) 
	at ca.jeffrey.myapp.j.a(Unknown Source) 
	at com.a.a.i.run(Unknown Source) 
	at android.os.Handler.handleCallback(Handler.java:739) 
	at android.os.Handler.dispatchMessage(Handler.java:95) 
	at android.os.Looper.loop(Looper.java:148) 
	at android.app.ActivityThread.main(ActivityThread.java:5421) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102) 
 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bumptech.glide.integration.volley.VolleyGlideModule" on path: DexPathList[[zip file "/data/app/ca.jeffrey.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/ca.jeffrey.myapp-1/lib/arm, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at java.lang.Class.classForName(Native Method) 
	at java.lang.Class.forName(Class.java:324) 
	at java.lang.Class.forName(Class.java:285) 
	at com.b.a.f.b.a(Unknown Source) 
	at com.b.a.f.b.a(Unknown Source) 
	at com.b.a.h.a(Unknown Source) 
	at com.b.a.l.<init>(Unknown Source) 
	at com.b.a.l.<init>(Unknown Source) 
	at com.b.a.e.o.a(Unknown Source) 
	at com.b.a.e.o.a(Unknown Source) 
	at com.b.a.h.a(Unknown Source) 
	at ca.jeffrey.myapp.MainActivity.a(Unknown Source) 
	at ca.jeffrey.myapp.MainActivity.a(Unknown Source) 
	at ca.jeffrey.myapp.h.a(Unknown Source) 
	at ca.jeffrey.apodgallery.h.a(Unknown Source) 
	at com.a.a.a.m.a(Unknown Source) 
	at ca.jeffrey.apodgallery.j.a(Unknown Source) 
	at ca.jeffrey.apodgallery.j.a(Unknown Source) 
	at com.a.a.i.run(Unknown Source) 
	at android.os.Handler.handleCallback(Handler.java:739) 
	at android.os.Handler.dispatchMessage(Handler.java:95) 
	at android.os.Looper.loop(Looper.java:148) 
	at android.app.ActivityThread.main(ActivityThread.java:5421) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102) 
	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.bumptech.glide.integration.volley.VolleyGlideModule" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
			... 28 more
		Suppressed: java.lang.ClassNotFoundException: com.bumptech.glide.integration.volley.VolleyGlideModule
	at java.lang.Class.classForName(Native Method)
	at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
	at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
				... 29 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by TWiStErRob** [comment]
Are you sure your configuration is being picked up?
Add `-dontobfuscate` to your pro file and see if the problem goes away. This should confirm that (1) the  obfuscation (class rename) is the issue and (2) the configuration is correctly used.

If the above confirmations are positive, it's still weird why it's not being kept. Try [this rule](https://github.com/bumptech/glide/wiki/Integration-Libraries#generic-proguard) instead.

**Comment by JeffreyCA** [comment]
Thanks, your advice worked! I added `-dontobfuscate`, then the error disappeared. I then removed that, and it still doesn't appear anymore. Strange, but I'm glad it worked.

**Comment by TWiStErRob** [comment]
Heh, so you just needed a clean build? :confused:

**Comment by JeffreyCA** [comment]
Yeah I guess so, likely not related to Glide at all then.
