### ISSUE TITLE
 Compute cache files size，has TransactionTooLargeException

### ISSUE THREAD

**Issue by hqw5566** [bumptech/glide#1445]
**Glide Version**:3.7.0

**Integration libraries**:no

**Device/Android Version**:HUAWEI G750-T20

**Issue details / Repro steps / Use case background**: 
I want to  compute cache files size.I user this function ,filePath is glide's cache path: 
```java
public static String getAutoFileOrFilesSize(String filePath) {
        File file = new File(filePath);
        long blockSize = 0;
        try {
            if (file.isDirectory()) {
                blockSize = getFileSizes(file);
            } else {
                blockSize = getFileSize(file);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return FormetFileSize(blockSize);
}
private static long getFileSizes(File f) throws Exception {
        long size = 0;
        File flist[] = f.listFiles();
        for (int i = 0; i < flist.length; i++) {
            if (flist[i].isDirectory()) {
                size = size + getFileSizes(flist[i]);
            } else {
                size = size + getFileSize(flist[i]);
            }
        }
        return size;
    }

private static long getFileSize(File file) throws Exception {
        long size = 0;
        if (file.exists()) {
            FileInputStream fis = null;
            fis = new FileInputStream(file);
            size = fis.available();
        } else {
            file.createNewFile();
        }
        return size;
    }
```
It  used to work,but today throw  a problem "TransactionTooLargeException".
I dont use bundle,finally find if i use getAutoFileOrFilesSize(glideCachePat) cause this exception,app to normal after delete this,or change an other path.
DiskCache all is default. I dont custom.

I guess that the problem cache file? Is glide bug?

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:no custom GlideModule
```java
 String size = FileUtils.getAutoFileOrFilesSize(Glide.getPhotoCacheDir(context).getPath());
        UIUtils.setText(tv_cache_size, size);
```

**Stack trace / LogCat**:
```ruby
java.lang.RuntimeException: Adding window failed
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:666)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3035)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2434)
	at android.app.ActivityThread.access$600(ActivityThread.java:171)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5468)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:936)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.os.TransactionTooLargeException
	at android.os.BinderProxy.transact(Native Method)
	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:682)
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:655)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248) 
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69) 
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3035) 
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2434) 
	at android.app.ActivityThread.access$600(ActivityThread.java:171) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393) 
	at android.os.Handler.dispatchMessage(Handler.java:107) 
	at android.os.Looper.loop(Looper.java:194) 
	at android.app.ActivityThread.main(ActivityThread.java:5468) 
	at java.lang.reflect.Method.invokeNative(Native Method) 
	at java.lang.reflect.Method.invoke(Method.java:525) 
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:936) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703) 
	at dalvik.system.NativeStart.main(Native Method) 
```

[cachefiles part image](https://github.com/hqw5566/my/blob/master/images/111.png)
all size:52M

**Comment by TWiStErRob** [comment]
I don't think it's related to Glide, it's not in the stack trace, check out http://stackoverflow.com/q/11451393/253468

Tip: `getFileSize(x)` can be replaced with `x.length()`, it's much better, you don't need to open a stream that's a lot of work. You also forgot to close `fis`.

**Comment by hqw5566** [comment]
thanks,it‘s my problem,use file.length() to normal.
Thank you for your guidance!
