### ISSUE TITLE
Out of memory exception

### ISSUE THREAD

**Issue by SachinRana028** [bumptech/glide#1446]
Hi 

I am facing out memory issue. I also go through the existing issues related to out of memory exception and on the basis of that I also increase the heap by adding line "android:largeHeap="true" " in the manifest file but still I getting same exception.

```
E/PriorityExecutor: Request threw uncaught throwable
 java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
     at java.util.concurrent.FutureTask.report(FutureTask.java:93)
     at java.util.concurrent.FutureTask.get(FutureTask.java:163)
     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1120)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:841)
     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
  Caused by: java.lang.OutOfMemoryError
     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
     at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:719)
     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:695)
     at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:329)
     at com.bumptech.glide.load.resource.bitmap.Downsampler.downsampleWithSize(Downsampler.java:220)
     at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:153)
     at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:50)
     at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
     at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:39)
     at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)
     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeBitmapWrapper(GifBitmapWrapperResourceDecoder.java:121)
     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeStream(GifBitmapWrapperResourceDecoder.java:94)
     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:71)
     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:61)
     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:22)
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:190)
     at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
     at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
     at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
     at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
     at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
     at java.lang.Thread.run(Thread.java:841) 
     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118) 
```

**Comment by TWiStErRob** [comment]
As far as I remember OOM was always a usage error, `largeHeap` will just delay it; or if it's a large load then maybe it's not possible. Check https://github.com/bumptech/glide/issues/679#issuecomment-148194654 how to diagnose for leaks.

If you want more help, please fill in the [template](https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md).
