### ISSUE TITLE
Unable to load bitmap into Viewtarget

### ISSUE THREAD

**Issue by sant527** [bumptech/glide#1447]
**Glide Version**: compile 'jp.wasabeef:glide-transformations:2.0.0'

**Integration libraries**: No

As per the tutorial on https://futurestud.io/blog/glide-callbacks-simpletarget-and-viewtarget-for-custom-view-classes

I am trying the following with a viewtarget.

```java
VrPanoramaView panoWidgetView = (VrPanoramaView) v.findViewById(R.id.pano_view);
final VrPanoramaView.Options viewOptions = new VrPanoramaView.Options();
viewOptions.inputType = VrPanoramaView.Options.TYPE_MONO;

        ViewTarget viewTarget = new ViewTarget<VrPanoramaView, GlideDrawable>( panoWidgetView ) {
            @Override
            public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> glideAnimation) {
                this.view.loadImageFromBitmap(((GlideBitmapDrawable) resource).getBitmap(),viewOptions);
            }
        };

        Glide
                .with(this) // safer!
                .load("http://sacredindiaapp.com/media/img/plc31-08-16-15-06-2736421_1080.jpg")
                .asBitmap()
                .into(viewTarget );
```

the error its giving is:

```
FATAL EXCEPTION: main
Process: com.google.devrel.vrviewapp, PID: 14225
java.lang.ClassCastException: android.graphics.Bitmap cannot be cast to com.bumptech.glide.load.resource.drawable.GlideDrawable
    at com.google.devrel.vrviewapp.WelcomeFragment$1.onResourceReady(WelcomeFragment.java:75)
    at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:525)
    at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:507)
    at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:158)
    at com.bumptech.glide.load.engine.EngineJob.access$100(EngineJob.java:22)
    at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:202)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:189)
    at android.app.ActivityThread.main(ActivityThread.java:5529)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
```

**Comment by sant527** [comment]
I have solved it using the below method

```
        Glide
                .with(this) // safer!
                .load("http://sacredindiaapp.com/media/img/plc31-08-16-15-06-2736421_1080.jpg")
                .asBitmap()
                .into(new SimpleTarget<Bitmap>() {
                    @Override
                    public void onResourceReady(Bitmap resource, GlideAnimation glideAnimation) {
                        panoWidgetView.loadImageFromBitmap(resource, viewOptions);
                    }
                });

```

**Comment by TWiStErRob** [comment]
If your pano view only visible on the activity/fragment I suggest using `ViewTarget`. The benefit of `ViewTarget` is that it manages some lifecycle for you better and it's possible to call `Glide.clear(view)` to magically clean up the view, of course for it to work you need to implement `onLoadCleared` whatever target you use. Take a look at `ImageViewTarget` to see how to correctly implement a target.

The original problem was that you ignored the unchecked warning at `.into` because `viewTarget` had a raw type. If you check the return value of `.asBitmap()` or the IDE suggested types for `.into()` you'll see the difference between the default and bitmap loads.
