### ISSUE TITLE
Some users can't instantiate a Glide Module

### ISSUE THREAD

**Issue by FrancoisBlavoet** [bumptech/glide#1467]
**Glide Version**: 3.7.0

**Integration libraries**:
okhttp

**Device/Android Version**:
a large range of devices and Android version from 4.4 to 6.0

**Issue details / Repro steps / Use case background**: 
The app starts and tries to init Glide for the first image load
However the class referenced in the manifest can't be found be the class loader : 

It only happens for a small fraction of our users and it does not seem to be linked with any specific scenario.  

MultiDex sounds like a good culprit but the issue also happens for API 5.0 >= where we should not have any multidexing issue.

**Stack trace / LogCat**:

``` ruby
Fatal Exception: java.lang.RuntimeException: Unable to create service com.deezer.jukebox.JukeboxService: java.lang.IllegalArgumentException: Unable to find GlideModule implementation
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2785)
       at android.app.ActivityThread.access$1800(ActivityThread.java:145)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1406)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5319)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
Caused by java.lang.IllegalArgumentException: Unable to find GlideModule implementation
       at com.bumptech.glide.module.ManifestParser.parseModule(Unknown Source:46)
       at com.bumptech.glide.module.ManifestParser.parse(Unknown Source:30)
       at com.bumptech.glide.Glide.get(Unknown Source:149)
       at com.bumptech.glide.RequestManager.(Unknown Source:62)
       at com.bumptech.glide.RequestManager.(Unknown Source:53)
       at com.bumptech.glide.manager.RequestManagerRetriever.getApplicationManager(Unknown Source:73)
       at com.bumptech.glide.manager.RequestManagerRetriever.get(Unknown Source:95)
       at com.bumptech.glide.Glide.with(Unknown Source:629)
```

**Comment by TWiStErRob** [comment]
It's says `JukeboxService` on the top, can it be that the low number is because it's rare that the first load after app startup is in a service?

I didn't use multidex yet, but doesn't the "should not have any multidexing issue" only applies for `targetApi >= 21` or even `minSdk >= 21`? I would assume that for older apps the same multidex problem would show up on newer devices if they were compiled far in the past.

**Comment by Teovald** [comment]
hmm
I am not an expert in multidexing, so I just had a look at the multiDex.install() method called when you initialize an app using the multidex support lib : 

 ```public static void install(Context context) {
        Log.i("MultiDex", "install");
        if(IS_VM_MULTIDEX_CAPABLE) {
            Log.i("MultiDex", "VM has multidex support, MultiDex support library is disabled.");
        }```   

So it looks like that new android versions just rely on the native multidexing, even when you are using the support lib.

**Comment by TWiStErRob** [comment]
Actually, shouldn't multidex prevent exactly this kind of exceptions? Can you please put the rest of the stack trace above? It looks like a `ClassNotFoundException` cause is missing.

**Comment by Teovald** [comment]
sure, here it is   


```  
Fatal Exception: java.lang.IllegalArgumentException: Unable to find GlideModule implementation
       at com.bumptech.glide.module.ManifestParser.parseModule(Unknown Source:46)
       at com.bumptech.glide.module.ManifestParser.parse(Unknown Source:30)
       at com.bumptech.glide.Glide.get(Unknown Source:149)
       at deezer.android.app.DZMidlet.onTrimMemory(Unknown Source:461)
       at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:4383)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1569)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5434)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:834)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.ClassNotFoundException: com.deezer.android.ui.medialoader.DeezerGlideModule
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:217)
       at java.lang.Class.forName(Class.java:172)
       at com.bumptech.glide.module.ManifestParser.parseModule(Unknown Source:44)
       at com.bumptech.glide.module.ManifestParser.parse(Unknown Source:30)
       at com.bumptech.glide.Glide.get(Unknown Source:149)
       at deezer.android.app.DZMidlet.onTrimMemory(Unknown Source:461)
       at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:4383)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1569)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5434)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:834)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NoClassDefFoundError: com/deezer/android/ui/medialoader/DeezerGlideModule
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:217)
       at java.lang.Class.forName(Class.java:172)
       at com.bumptech.glide.module.ManifestParser.parseModule(Unknown Source:44)
       at com.bumptech.glide.module.ManifestParser.parse(Unknown Source:30)
       at com.bumptech.glide.Glide.get(Unknown Source:149)
       at deezer.android.app.DZMidlet.onTrimMemory(Unknown Source:461)
       at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:4383)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1569)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5434)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:834)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.IllegalAccessError: interface not accessible
       at dalvik.system.DexFile.defineClass(DexFile.java)
       at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:211)
       at dalvik.system.DexPathList.findClass(DexPathList.java:313)
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:51)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:217)
       at java.lang.Class.forName(Class.java:172)
       at com.bumptech.glide.module.ManifestParser.parseModule(Unknown Source:44)
       at com.bumptech.glide.module.ManifestParser.parse(Unknown Source:30)
       at com.bumptech.glide.Glide.get(Unknown Source:149)
       at deezer.android.app.DZMidlet.onTrimMemory(Unknown Source:461)
       at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:4383)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1569)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5434)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:834)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)```

**Comment by Teovald** [comment]
and the corresponding crashlytics report : http://crashes.to/s/ecbc21a2848

**Comment by TWiStErRob** [comment]
Does `DeezerGlideModule` only implement `GlideModule`?

Fabric shows `.JukeboxService.setUpNotificationImageLoader` is directly called from `ActiviyThread.handleCreateService`. For me this either means that `setUpNotificationImageLoader` is called in a static initializer, a field initializer or in the constructor, or possibly an agressively inlined `onCreate` call, not sure what proguard can mess up in stacks. Anyway, before `onCreate` `service.getApplicationContext()` is not valid, see `handleCreateService` source code.

Similarly the method you pasted shows `onTrimMemory`. Glide is being set up in `onTrimMemory`, not sure if, again, the context is ready or is being called in a weird state. Is it possible that at that point in the lifecycle of `DZMidlet` the multidex is not installed yet?

**Comment by Teovald** [comment]
>Does DeezerGlideModule only implement GlideModule?
yes

>JukeboxService.setUpNotificationImageLoader   
it is called from the onCreate method of the service


>Similarly the stack you pasted shows onTrimMemory

Actually, this might be the issue.  
I manually call 
        `Glide.get(this).trimMemory(level);`

in DZMidlet.onTrimMemory
so maybe that onTrimMemory can be called before MultiDex is initialized, triggering a glide initialization and failure ?  

I have removed this call.  Glide already does this automatically anyway.

**Comment by suhadzain** [comment]
One Scenario u should check if GlideModule added in manifest with full package name..
