### ISSUE TITLE
(Huge)Lag in response of Multiple requests from same fragment from two different adapters

### ISSUE THREAD

**Issue by vkramsingh** [bumptech/glide#1474]
**Glide Version**:
I am running Glide 3.6.1

**Integration libraries**:
I use Volley integration

**Device/Android Version**:
All phones will fairly less memory

**Issue details / Repro steps / Use case background**: 
I am creating a image selector gallery. After allowing the user to select the photos, I open a fragment which has two components :
1) A recycler view with horizontal layout which shows the images chosen by the user.
2) A view pager which shows a large size preview of the image selected from the recycler view.

While the recycler view loads the images quite promptly, the view pager shows a lot of lag in a lot of the images. The expected behavior is that since the image is already loaded in the recycler view, loading it in a view pager should be almost immediate since DiskCacheStrategy.SOURCE option has been selected.

**Pager adapter :**

``` java
    @Override
    public Object instantiateItem(ViewGroup container, int position) {
        View imageAndTag = View.inflate(mContext, R.layout.review_selection_pager_view, null);
        container.addView(imageAndTag);
        ImageView mImageBig = (ImageView) imageAndTag.findViewById(R.id.imageBig);

        ImageModel currentImageModel = mSelectedImages.get(position);
        View progressView = imageAndTag.findViewById(R.id.progressPhotoImage);
        if (currentImageModel != null) {
            setImageOnView(mImageBig, progressView, currentImageModel.getPath());
            CheckBox markAsCoverCb = (CheckBox) imageAndTag.findViewById(R.id.mark_as_cover_checkbox);
            if (markAsCoverCb != null) {
                markAsCoverCb.setTag(position);
                markAsCoverCb.setOnCheckedChangeListener(this);
                markAsCoverCb.setChecked(currentImageModel.isCoverPhoto());
            }
        }

        return imageAndTag;
    }

    private void setImageOnView(final ImageView bigImageView, final View progressView, String path) {
        if (bigImageView != null && path != null) {
            if (progressView != null) {
                progressView.setVisibility(View.VISIBLE);
            }
            Glide.with(mContext).load(path).diskCacheStrategy(DiskCacheStrategy.SOURCE).listener(new RequestListener<String, GlideDrawable>() {
                @Override
                public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                    if (progressView != null) {
                        progressView.setVisibility(View.GONE);
                    }
                    return false;
                }

                @Override
                public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                    if (progressView != null) {
                        progressView.setVisibility(View.GONE);
                    }
                    return false;
                }
            }).into(bigImageView);
        }
    }
```

**Recycler view adapter :**

``` java
 private void bindBottomPreviewImageViewHolder(BottomPreviewViewHolder holder, int position) {
        if (mImageList != null && mImageList.size() > position) {
            ImageModel currentImage = mImageList.get(position);
            if (currentImage != null) {
                setPreviewImage(currentImage.getPath(), holder, position);
            }
            addRemoveSelectionBorderOnLayout(holder.mImageView, mSelectedIndex == position);
        }
    }
 private void setPreviewImage(String path, BottomPreviewViewHolder holder, final int position) {
        if (path != null && holder != null) {
            final View progressView = holder.mProgressView;
            if (progressView != null) {
                progressView.setVisibility(View.VISIBLE);
            }
            Glide.with(mContext).load(path).diskCacheStrategy(DiskCacheStrategy.SOURCE).dontAnimate().listener(new RequestListener<String, GlideDrawable>() {
                @Override
                public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                    if (progressView != null) {
                        progressView.setVisibility(View.GONE);
                    }
                    return false;
                }

                @Override
                public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                    if (progressView != null) {
                        progressView.setVisibility(View.GONE);
                    }
                    if (mClickListener != null) {
                        mClickListener.imageLoaded(position);
                    }
                    return false;
                }
            }).into(holder.mImageView);
        }
    }
```

**Layout XML**:
**Recycler item layout:**

``` xml
<?xml version="1.0" encoding="utf-8"?>
<ImageView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/preview_image_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

</ImageView>
```

**Pager adapter**

``` xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center_horizontal"
    android:orientation="vertical">

    <RelativeLayout
        android:layout_width="300dp"
        android:layout_height="match_parent"
        android:layout_marginTop="30dp">

        <com.multipleselect.app.ui.NNAcresProgressWheel xmlns:wheel="http://schemas.android.com/apk/res-auto"
            android:id="@+id/progressPhotoImage"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:visibility="gone"
            wheel:matProg_barColor="@color/material_blue_500"
            wheel:matProg_progressIndeterminate="true" />

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <ImageView
                android:id="@+id/imageBig"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:scaleType="centerCrop" />
            <CheckBox
                android:id="@+id/mark_as_cover_checkbox"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:minHeight="16dp"
                android:textSize="12sp"
                android:paddingTop="5dp"
                android:paddingBottom="5dp"
                android:paddingLeft="10dp"
                android:paddingRight="10dp"
                android:textColor="@drawable/cover_photo_text_color_selector"
                android:gravity="center"
                android:button="@null"
                android:text="@string/cover_photo_unarked_label"
                android:background="@drawable/mark_cover_photo_background_selector"
                android:layout_alignParentBottom="true"/>
        </RelativeLayout>
    </RelativeLayout>

</LinearLayout> 
```

![screenshot_2016-09-19-22-09-31-048_com nnacres app](https://cloud.githubusercontent.com/assets/12782190/18640595/70964b04-7eb6-11e6-8cf5-7323c7b72216.png)
![screenshot_2016-09-19-22-09-42-757_com nnacres app](https://cloud.githubusercontent.com/assets/12782190/18640597/709b6864-7eb6-11e6-976a-6540b12bcc74.png)
![screenshot_2016-09-19-22-09-52-911_com nnacres app](https://cloud.githubusercontent.com/assets/12782190/18640596/709ab900-7eb6-11e6-89ba-727ba972bfec.png)
![screenshot_2016-09-19-22-09-56-246_com nnacres app](https://cloud.githubusercontent.com/assets/12782190/18640598/709bdc54-7eb6-11e6-8966-1c301229f03f.png)

**Comment by vkramsingh** [comment]
Interestingly, when i take logs for t he request, I get a OOM exception but my app DOES NOT crash : 
E/art: Throwing OutOfMemoryError "Failed to allocate a 15116556 byte allocation with 5346608 free bytes and 5MB until OOM"
09-19 15:13:54.354 8758-9371/com.multipleselect.app D/skia: --- decoder->decode returned false
09-19 15:13:54.354 8758-9371/com.multipleselect.app E/PriorityExecutor: Request threw uncaught throwable
                                                                 java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Failed to allocate a 15116556 byte allocation with 5346608 free bytes and 5MB until OOM
                                                                     at java.util.concurrent.FutureTask.report(FutureTask.java:93)
                                                                     at java.util.concurrent.FutureTask.get(FutureTask.java:163)
                                                                     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1120)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
                                                                  Caused by: java.lang.OutOfMemoryError: Failed to allocate a 15116556 byte allocation with 5346608 free bytes and 5MB until OOM
                                                                     at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
                                                                     at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:639)
                                                                     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:615)
                                                                     at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:329)
                                                                     at com.bumptech.glide.load.resource.bitmap.Downsampler.downsampleWithSize(Downsampler.java:220)
                                                                     at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:153)
                                                                     at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:50)
                                                                     at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
                                                                     at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:39)
                                                                     at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)
                                                                     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeBitmapWrapper(GifBitmapWrapperResourceDecoder.java:121)
                                                                     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeStream(GifBitmapWrapperResourceDecoder.java:94)
                                                                     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:71)
                                                                     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:61)
                                                                     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:22)
                                                                     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperStreamResourceDecoder.decode(GifBitmapWrapperStreamResourceDecoder.java:24)
                                                                     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperStreamResourceDecoder.decode(GifBitmapWrapperStreamResourceDecoder.java:14)
                                                                     at com.bumptech.glide.load.resource.file.FileToStreamDecoder.decode(FileToStreamDecoder.java:39)
                                                                     at com.bumptech.glide.load.resource.file.FileToStreamDecoder.decode(FileToStreamDecoder.java:17)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.loadFromCache(DecodeJob.java:222)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.decodeSourceFromCache(DecodeJob.java:109)
                                                                     at com.bumptech.glide.load.engine.EngineRunnable.decodeFromCache(EngineRunnable.java:116)
                                                                     at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:99)
                                                                     at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                     at java.lang.Thread.run(Thread.java:818) 
                                                                     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)

**Comment by TWiStErRob** [comment]
If you want to catch OOMs upgrade to 3.8.0 (currently [SNAPSHOT](https://github.com/bumptech/glide/wiki/Snapshots)), see #1057 for more details.

I think you're getting OOMs, because the viewpager doesn't clear up memory. When you load `.into(holder.iv)` in a RecyclerView you're essentially cancelling a previous load, because it's recycled. With ViewPager you don't have that luxury, but you have to manually call `Glide.clear(imageView)` for non-visible pages.

**Comment by vkramsingh** [comment]
Using 3.8.0 snapshot helped me catch the OOM exceptions.
I used Glide.clear in the destroyItem method of PagerAdapter, but the OOM is still there. Any suggestions? Really caught up in a tizzy here.
**PagerAdapter**

@Override
    public void destroyItem(ViewGroup container, int position, Object object) {
        if(object instanceof View){
            ImageView bigImageView = (ImageView) ((View) object).findViewById(R.id.imageBig);
            if(bigImageView !=null){
                Glide.clear(bigImageView);
            }
        }
        ((ViewPager) container).removeView((View) object);
    }

**Comment by TWiStErRob** [comment]
Destroy helps, but that's not what is using the memory: it's the off-screen pages that still exist to left-right of current.

**Comment by anmolarora** [comment]
I'm facing the same issue with ViewPager.
@TWiStErRob Will **FragmentStatePagerAdapter** help if I use it in place of **PagerAdapter** ?
As stated by developer.android.com 

[FragmentStatePagerAdapter](https://developer.android.com/reference/android/support/v4/app/FragmentStatePagerAdapter.html)
> This version of the pager is more useful when there are a large number of pages, working more like a list view. When pages are not visible to the user, their entire fragment may be destroyed, only keeping the saved state of that fragment. **This allows the pager to hold on to much less memory associated with each visited page** as compared to FragmentPagerAdapter at the cost of potentially more overhead when switching between pages.

**Comment by TWiStErRob** [comment]
@anmolarora that sounds like a potential solution. I suggest you give it a try! Note that I may potentially not solve the issue fully, because you'll still have 3 pages in memory at a time if your pager is configured like that.
