### ISSUE TITLE
NPE in Transformation

### ISSUE THREAD

**Issue by huzhenjie** [bumptech/glide#1478]
## glide version

```
compile 'com.github.bumptech.glide:glide:3.7.0'
```
## Exception

```
09-21 14:35:00.483 29752-29752/com.test.organization E/AndroidRuntime: FATAL EXCEPTION: main
   Process: com.test.organization, PID: 29752
   java.lang.RuntimeException: Unable to resume activity {com.test.organization/com.test.organization.module.user.UserEditActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.bumptech.glide.load.Transformation.getId()' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2956)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2987)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5238)
       at java.lang.reflect.Method.invoke(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
    Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.bumptech.glide.load.Transformation.getId()' on a null object reference
       at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperTransformation.getId(GifBitmapWrapperTransformation.java:51)
       at com.bumptech.glide.load.MultiTransformation.getId(MultiTransformation.java:51)
       at com.bumptech.glide.load.engine.EngineKey.hashCode(EngineKey.java:109)
       at java.util.Collections.secondaryHash(Collections.java:3405)
       at java.util.HashMap.remove(HashMap.java:616)
       at com.bumptech.glide.util.LruCache.remove(LruCache.java:135)
       at com.bumptech.glide.load.engine.cache.LruResourceCache.remove(LruResourceCache.java:12)
       at com.bumptech.glide.load.engine.Engine.getEngineResourceFromCache(Engine.java:232)
       at com.bumptech.glide.load.engine.Engine.loadFromCache(Engine.java:222)
       at com.bumptech.glide.load.engine.Engine.load(Engine.java:153)
       at com.bumptech.glide.request.GenericRequest.onSizeReady(GenericRequest.java:449)
       at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.getSize(ViewTarget.java:211)
       at com.bumptech.glide.request.target.ViewTarget.getSize(ViewTarget.java:100)
       at com.bumptech.glide.request.GenericRequest.begin(GenericRequest.java:272)
       at com.bumptech.glide.request.ThumbnailRequestCoordinator.begin(ThumbnailRequestCoordinator.java:87)
       at com.bumptech.glide.manager.RequestTracker.resumeRequests(RequestTracker.java:83)
       at com.bumptech.glide.RequestManager.resumeRequests(RequestManager.java:180)
       at com.bumptech.glide.RequestManager.onStart(RequestManager.java:203)
       at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStart(ActivityFragmentLifecycle.java:50)
       at com.bumptech.glide.manager.SupportRequestManagerFragment.onStart(SupportRequestManagerFragment.java:135)
       at android.support.v4.app.Fragment.performStart(Fragment.java:2000)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
       at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2051)
       at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:185)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
       at android.app.Activity.performStart(Activity.java:5955)
       at android.app.Activity.performRestart(Activity.java:6012)
       at android.app.Activity.performResume(Activity.java:6017)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2945)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2987) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:135) 
       at android.app.ActivityThread.main(ActivityThread.java:5238) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704) 

```

**Comment by TWiStErRob** [comment]
And how did you achieve this? What's your code?
