### ISSUE TITLE
Network issue: Request failed 403: Forbidden

### ISSUE THREAD

**Issue by ductranit** [bumptech/glide#1479]
**Glide Version**: 3.7.0

**Integration libraries**: stock networking & OkHttp3

**Device/Android Version**: samsung galaxy s3

**Issue details / Repro steps / Use case background**: 
This is my image url: https://i.ytimg.com/vi/bNEtWBhkOVA/mqdefault.jpg
The image can't be loaded from Youtube server. The logcat says 403 error. But I can view this image on laptop or phone browser (and it does work if I use [UIL](https://github.com/nostra13/Android-Universal-Image-Loader) library)
It looks like issue #841 , but I tried OkHttp3 and still not work

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java
// My Adapter
Glide.with(context).load(item.getThumbnailUrl()).fitCenter().error(R.drawable.tw_image_holder).crossFade().into(holder.imgTextThumb);
```

**Layout XML**:

``` xml
<FrameLayout
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">

    <ImageView
        android:id="@+id/imgTextThumb"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:adjustViewBounds="true"/>

    <ImageView
        android:id="@+id/imgPlay"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:src="@drawable/tw_btn_play_in_message" />
</FrameLayout>
```

**Stack trace / LogCat**:

``` ruby
GenericRequest: load failed    java.io.IOException: Request failed 403: Forbidden
    at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:90)
    at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:44)
    at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:20)
    at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:70)
    at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:53)
    at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
    at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
    at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
    at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
    at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
    at java.util.concurrent.FutureTask.run(FutureTask.java:234)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
    at java.lang.Thread.run(Thread.java:841)
    at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
```

**Comment by TWiStErRob** [comment]
I just put this in an app and it works fine:
```java
Glide
				.with(context)
				.load("https://i.ytimg.com/vi/bNEtWBhkOVA/mqdefault.jpg")
				.fitCenter()
				.error(R.drawable.glide_error)
				.crossFade()
				.into(imageView);
```

Are you sure that's the actual url? Try adding a listener and log every argument.
It could be also a temporary network issue with your device, router, ISP.

**Comment by ductranit** [comment]
@TWiStErRob I check again. Your code is worked for single image in activity. So I can confirm this isn't network issue. But it still doesn't display in my adapter. 
So I tried another way with simple target bitmap

 ```
Glide.with(holder.imgTextThumb.getContext()).load("https://i.ytimg.com/vi/d5ZOpQ5o2Ns/mqdefault.jpg").asBitmap().into(new SimpleTarget<Bitmap>() {
                    @Override
                    public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                        holder.imgTextThumb.setImageBitmap(resource);
                    }
                });
```
and it can display correctly. Do you have any idea?

**Comment by TWiStErRob** [comment]
Can you try to put a breakpoint in HttpUrlFetcher into the branch that detects non-2xx and grab the response headers from the connection? I saw somewhere that servers may respond with `X-Reject-Reason`, let's hope YT does something similar too.

**Comment by mfsi-trayambakm** [comment]
I faced the same issue with image url
https://github.com/bumptech/glide/issues/1479
