### ISSUE TITLE
Not able to load received/sent images 10 minutes later in the UI

### ISSUE THREAD

**Issue by jcelaviie** [bumptech/glide#1488]
Hi, I came across issue with loading received or sent images after more than 10 minutes. This issue only happens in JB. 

**Glide Version**:

**Device/Android Version**:
OS info: device: "C2305"
JB : Sony C2305/JB-4.2.2

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java
requestManager
        .asDrawable()
        .apply(requestOptions)
        .load(new FifeModel(url, fifeUrlOptions, accountId));
```

**Stack trace / LogCat**:

``` ruby
Babel_db: getTempStoreFd: error creating pfd for /data/data/<packagename>/cache/scratch/2047465361613405861.temp.jpg
java.io.FileNotFoundException: No such file or directory
at android.os.Parcel.openFileDescriptor(Parcel.java)
at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:124)
at android.content.ContentProvider.openAssetFile(ContentProvider.java:829)
at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:268)
at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:741)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:638)
at com.bumptech.glide.load.data.FileDescriptorLocalUriFetcher.loadResource(FileDescriptorLocalUriFetcher.java:21)
at com.bumptech.glide.load.data.FileDescriptorLocalUriFetcher.loadResource(FileDescriptorLocalUriFetcher.java:13)
at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:40)
at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:93)
at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:274)
at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherFailed(DecodeJob.java:363)
at com.bumptech.glide.load.engine.SourceGenerator.onLoadFailed(SourceGenerator.java:118)
at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:142)
at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:134)
at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:45)
at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:93)
at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:274)
at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:244)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:838)
at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:346)
Glide   : class art: Failed to load resource
```

It looks like file expires in the cache after some time and glide still try to load the image from the cache.

**Comment by TWiStErRob** [comment]
That file path doesn't look like a Glide cached image, double-check however you convert `FifeModel` to an `Uri`.
