### ISSUE TITLE
{java.lang.RuntimeException}error:24064064:random number generator:SSLEAY_RAND_BYTES:PRNG not seeded

### ISSUE THREAD

**Issue by Chunyulo** [bumptech/glide#1510]
Recently this issue occurs when use glide, detail info as follows:

**Glide Version**:glide:3.7.0

**Integration libraries**:NO

**Device/Android Version**:SM-G355M 4.4.2 /itel it1701 4.4.2

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

``` java
Glide.with...
```

**Layout XML**:

``` xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:

``` ruby
at com.android.org.conscrypt.NativeCrypto.RAND_bytes(Native Method)
at com.android.org.conscrypt.OpenSSLRandom.engineNextBytes(OpenSSLRandom.java:32)
at java.security.SecureRandom.nextBytes(SecureRandom.java:270)
at java.util.UUID.randomUUID(UUID.java:130)
at com.bumptech.glide.load.resource.d.f$d.(GifFrameLoader.java:192)
at com.bumptech.glide.load.resource.d.f.e(GifFrameLoader.java:103)
at com.bumptech.glide.load.resource.d.f.a(GifFrameLoader.java:124)
at com.bumptech.glide.load.resource.d.f$c.handleMessage(GifFrameLoader.java:135)
```

some ref in
1. https://www.openssl.org/docs/faq.html#USER1
2. http://android-developers.blogspot.com/2013/08/some-securerandom-thoughts.html
but cannot solve it

**Comment by TWiStErRob** [comment]
Glide is using the standard Java API. Does this only happen on those devices?
What about ProGuard? Maybe it messed with something.

**Comment by Chunyulo** [comment]
Yes，this happened on some Samsung devices of OS version 4.4.2 & 4.4.4, and one itel it phone. ref glide through gradle and ProGuard keeps glide.

**Comment by TWiStErRob** [comment]
Can you reproduce this issue?

**Comment by TWiStErRob** [comment]
I've look into this a little and looks like self-seeding was added in https://android.googlesource.com/platform/external/conscrypt/+/49336618a762eff280621cf7474021e06e8521fa%5E%21/#F0. I'm not sure what version of android is this because there are no tags pre-Lollipop in this repo. Not sure though that this is the problem.

**Comment by paour** [comment]
I'm getting about 10 crashes per week with this issues, on the following devices, all on 4.4.4:

- GT-I9060M
- SM-G360H
- GT-I9060I

**Comment by TasneemBohra** [comment]
I am also getting this exception on device 	
GT-I9060I - 4.4.4

`Fatal Exception: java.lang.RuntimeException: error:24064064:random number generator:SSLEAY_RAND_BYTES:PRNG not seeded
       at com.android.org.conscrypt.NativeCrypto.RAND_bytes(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLRandom.engineNextBytes(OpenSSLRandom.java:32)
       at java.security.SecureRandom.nextBytes(SecureRandom.java:270)
       at java.util.UUID.randomUUID(UUID.java:130)
       at com.bumptech.glide.load.resource.gif.GifFrameLoader$FrameSignature.(GifFrameLoader.java)
       at com.bumptech.glide.load.resource.gif.GifFrameLoader.loadNextFrame(GifFrameLoader.java:103)
       at com.bumptech.glide.load.resource.gif.GifFrameLoader.onFrameReady(GifFrameLoader.java:124)
       at com.bumptech.glide.load.resource.gif.GifFrameLoader$FrameLoaderCallback.handleMessage(GifFrameLoader.java:135)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5584)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)`
