### ISSUE TITLE
ANR with Glide, please have a look.

### ISSUE THREAD

**Issue by johnsonyuw** [bumptech/glide#1517]
# **_"fifo-pool-thread-0" prio=5 tid=48 WAIT_**

| group="main" sCount=1 dsCount=0 obj=0x423b0ff8 self=0x6c8f7978

| sysTid=13050 nice=10 sched=0/0 cgrp=apps/bg_non_interactive handle=1764435968

| state=S schedstat=( 213565993 70961352 195 ) utm=17 stm=4 core=1

at java.lang.Object.wait(Native Method)

# **_- waiting on <0x423b1188> (a java.lang.VMThread) held by tid=48 (fifo-pool-thread-0)_**

at java.lang.Thread.parkFor(Thread.java:1231)

at sun.misc.Unsafe.park(Unsafe.java:323)

at java.util.concurrent.locks.LockSupport.park(LockSupport.java:159)

at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2019)

at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:505)

at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1013)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1073)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)

at java.lang.Thread.run(Thread.java:856)

at com.bumptech.glide.load.engine.executor.a.run(SourceFile:118)

```

**Comment by johnsonyuw** [comment]
Just  part of ANR log.

**Comment by TWiStErRob** [comment]
This is normal, the worker threads are waiting for work: notice `PBQ.take` in the stack.

ANR happens when you block the UI thread: https://developer.android.com/training/articles/perf-anr.html#anr
Find your main thread, search for `"main" prio=` or `ActivityThread` in the stack
