### ISSUE TITLE
GenericRequest: load failed

### ISSUE THREAD

**Issue by liubo123** [bumptech/glide#1552]
```
10-26 15:45:20.433 15105-15105/com.example.liubo.myapplication V/Engine: Started new load in 0.160886ms, key: EngineKey{http://packages.asiatravel.com/packageImage/Tour/AddtlImages/137/Night%20Safari.jpg+com.bumptech.glide.signature.EmptySignature@25c6886+[984x600]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'FitCenter.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
10-26 15:45:20.433 15105-15279/com.example.liubo.myapplication V/DecodeJob: Decoded transformed from cache in 0.062188, key: EngineKey{http://packages.asiatravel.com/packageImage/Tour/AddtlImages/137/Night%20Safari.jpg+com.bumptech.glide.signature.EmptySignature@25c6886+[984x600]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'FitCenter.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
10-26 15:45:20.433 15105-15105/com.example.liubo.myapplication V/GenericRequest: finished onSizeReady in 32.363594 this: 858630209
10-26 15:45:20.433 15105-15279/com.example.liubo.myapplication V/DecodeJob: Transcoded transformed from cache in 0.013802, key: EngineKey{http://packages.asiatravel.com/packageImage/Tour/AddtlImages/137/Night%20Safari.jpg+com.bumptech.glide.signature.EmptySignature@25c6886+[984x600]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'FitCenter.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
10-26 15:45:20.443 15105-16270/com.example.liubo.myapplication I/System.out: [CDS]rx timeout:2500
10-26 15:45:20.523 15105-15105/com.example.liubo.myapplication I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@33a7e66a time:19005625
10-26 15:45:20.753 15105-16270/com.example.liubo.myapplication V/DecodeJob: Fetched data in 313.942187, key: EngineKey{http://packages.asiatravel.com/packageImage/Tour/AddtlImages/137/Night%20Safari.jpg+com.bumptech.glide.signature.EmptySignature@25c6886+[984x600]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'FitCenter.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
10-26 15:45:20.953 15105-15317/com.example.liubo.myapplication D/skia: --- decoder->decode returned false
10-26 15:45:21.463 15105-15330/com.example.liubo.myapplication D/skia: --- decoder->decode returned false
10-26 15:45:21.563 15105-16270/com.example.liubo.myapplication D/LruBitmapPool: Missing bitmap=[331820](RGB_565)
10-26 15:45:21.563 15105-16270/com.example.liubo.myapplication V/LruBitmapPool: Get bitmap=[331820](RGB_565)
10-26 15:45:21.563 15105-16270/com.example.liubo.myapplication V/LruBitmapPool: Hits=0, misses=2, puts=0, evictions=0, currentSize=0, maxSize=30689280
                                                                                Strategy=SizeConfigStrategy{groupedMap=GroupedLinkedMap( {[331820](RGB_565):0} ), sortedSizes=(RGB_565[{}])}
10-26 15:45:21.573 15105-16270/com.example.liubo.myapplication D/skia: --- decoder->decode returned false
10-26 15:45:21.573 15105-16270/com.example.liubo.myapplication V/DecodeJob: Decoded from source in 822.0108329999999, key: EngineKey{http://packages.asiatravel.com/packageImage/Tour/AddtlImages/137/Night%20Safari.jpg+com.bumptech.glide.signature.EmptySignature@25c6886+[984x600]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'FitCenter.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
10-26 15:45:21.573 15105-16270/com.example.liubo.myapplication V/DecodeJob: Transformed resource from source in 0.12906199999999998, key: EngineKey{http://packages.asiatravel.com/packageImage/Tour/AddtlImages/137/Night%20Safari.jpg+com.bumptech.glide.signature.EmptySignature@25c6886+[984x600]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'FitCenter.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
10-26 15:45:21.573 15105-16270/com.example.liubo.myapplication V/DecodeJob: Transcoded transformed from source in 0.014426999999999999, key: EngineKey{http://packages.asiatravel.com/packageImage/Tour/AddtlImages/137/Night%20Safari.jpg+com.bumptech.glide.signature.EmptySignature@25c6886+[984x600]+''+'ImageVideoBitmapDecoder.com.bumptech.glide.load.resource.bitmap'+'FitCenter.com.bumptech.glide.load.resource.bitmap'+'BitmapEncoder.com.bumptech.glide.load.resource.bitmap'+'GifBitmapWrapperDrawableTranscoder.com.bumptech.glide.load.resource.transcode'+''}
10-26 15:45:21.573 15105-15105/com.example.liubo.myapplication D/GenericRequest: load failed
10-26 15:45:21.573 15105-15105/com.example.liubo.myapplication D/GLIDE: onException(null, http://packages.asiatravel.com/packageImage/Tour/AddtlImages/137/Night%20Safari.jpg, Target for: android.support.v7.widget.AppCompatImageView{3c93bf40 V.ED.... ........ 48,48-1032,648 #7f0c0050 app:id/iv_imageview}, true)
```

the url is http://packages.asiatravel.com/packageImage/Tour/AddtlImages/137/Night%20Safari.jpg

**Comment by liubo123** [comment]
Glide: Root cause (1 of 12)
                                                                        java.io.IOException: Exception decoding bitmap, outWidth: 470, outHeight: 353, outMimeType: image/jpeg, inBitmap: [1065x800] ARGB_8888 (3408000)
                                                                            at com.bumptech.glide.load.resource.bitmap.Downsampler.newIoExceptionForInBitmapAssertion(Downsampler.java:486)
                                                                            at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:426)
                                                                            at com.bumptech.glide.load.resource.bitmap.Downsampler.downsampleWithSize(Downsampler.java:339)
                                                                            at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:185)
                                                                            at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:156)
                                                                            at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:115)
                                                                            at com.bumptech.glide.load.resource.bitmap.ByteBufferBitmapDecoder.decode(ByteBufferBitmapDecoder.java:31)
                                                                            at com.bumptech.glide.load.resource.bitmap.ByteBufferBitmapDecoder.decode(ByteBufferBitmapDecoder.java:15)
                                                                            at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67)
                                                                            at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52)
                                                                            at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43)
                                                                            at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
                                                                            at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
                                                                            at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:435)
                                                                            at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:428)
                                                                            at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:414)
                                                                            at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:372)
                                                                            at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:345)
                                                                            at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91)
                                                                            at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:68)
                                                                            at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71)
                                                                            at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:271)
                                                                            at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:238)
                                                                            at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:216)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                            at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:346)
                                                                         Caused by: java.lang.IllegalArgumentException: Problem decoding into existing bitmap
                                                                            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:862)
                                                                            at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:424)
                                                                            at com.bumptech.glide.load.resource.bitmap.Downsampler.downsampleWithSize(Downsampler.java:339) 
                                                                            at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:185) 
                                                                            at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:156) 
                                                                            at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:115) 
                                                                            at com.bumptech.glide.load.resource.bitmap.ByteBufferBitmapDecoder.decode(ByteBufferBitmapDecoder.java:31) 
                                                                            at com.bumptech.glide.load.resource.bitmap.ByteBufferBitmapDecoder.decode(ByteBufferBitmapDecoder.java:15) 
                                                                            at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67) 
                                                                            at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52) 
                                                                            at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43) 
                                                                            at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56) 
                                                                            at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42) 
                                                                            at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:435) 
                                                                            at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:428) 
                                                                            at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:414) 
                                                                            at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:372) 
                                                                            at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:345) 
                                                                            at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91) 
                                                                            at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:68) 
                                                                            at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71) 
                                                                            at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:271) 
                                                                            at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:238) 
                                                                            at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:216) 
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                            at java.lang.Thread.run(Thread.java:818) 
                                                                            at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:346)

**Comment by liubo123** [comment]
I'm using 3.7 version

**Comment by TWiStErRob** [comment]
Can you please fill in the [issue template](https://raw.githubusercontent.com/bumptech/glide/master/ISSUE_TEMPLATE.md) and give more info on your usage?

**Comment by liubo123** [comment]
Glide.with(this).load(Uri.parse("http://packages.asiatravel.com/packageImage/Tour/AddtlImages/2542/S.E.A%20Aquarium%206.jpg"))
                .listener(new RequestListener<Drawable>() {
                    @Override
                    public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
                        Log.d("onLoadFailed = %s", e.getMessage());
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
                        return false;
                    }
                })
                .into(iv_imageview);




This is the source I used github reported the following error. And other url can be displayed properly.





java.io.IOException: Exception decoding bitmap, outWidth: 470, outHeight: 353, outMimeType: image/jpeg, inBitmap: [1065x800] ARGB_8888 (3408000)
                                                                            at com.bumptech.glide.load.resource.bitmap.Downsampler.newIoExceptionForInBitmapAssertion(Downsampler.java:486)
                                                                            at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:426)
                                                                            at com.bumptech.glide.load.resource.bitmap.Downsampler.downsampleWithSize(Downsampler.java:339)
                                                                            at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:185)
                                                                            at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:156)
                                                                            at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:60)
                                                                            at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:17)
                                                                            at com.bumptech.glide.load.resource.bitmap.BitmapDrawableDecoder.decode(BitmapDrawableDecoder.java:45)
                                                                            at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67)
                                                                            at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52)
                                                                            at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43)
                                                                            at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
                                                                            at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
                                                                            at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:435)
                                                                            at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:428)
                                                                            at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:414)
                                                                            at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:372)
                                                                            at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:345)
                                                                            at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:134)
                                                                            at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91)
                                                                            at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:73)
                                                                            at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71)
                                                                            at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:48)
                                                                            at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:271)
                                                                            at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:380)
                                                                            at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:345)
                                                                            at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:134)
                                                                            at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91)
                                                                            at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:68)
                                                                            at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71)
                                                                            at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:48)
                                                                            at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:271)
                                                                            at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:241)
                                                                            at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:216)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                            at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:346)
                                                                         Caused by: java.lang.IllegalArgumentException: Problem decoding into existing bitmap
                                                                            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:862)
                                                                            at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:424)
                                                                            at com.bumptech.glide.load.resource.bitmap.Downsampler.downsampleWithSize(Downsampler.java:339) 
                                                                            at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:185) 
                                                                            at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:156) 
                                                                            at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:60) 
                                                                            at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:17) 
                                                                            at com.bumptech.glide.load.resource.bitmap.BitmapDrawableDecoder.decode(BitmapDrawableDecoder.java:45) 
                                                                            at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67) 
                                                                            at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52) 
                                                                            at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43) 
                                                                            at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56) 
                                                                            at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42) 
                                                                            at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:435) 
                                                                            at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:428) 
                                                                            at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:414) 
                                                                            at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:372) 
                                                                            at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:345) 
                                                                            at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:134) 
                                                                            at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91) 
                                                                            at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:73) 
                                                                            at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71) 
                                                                            at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:48) 
                                                                            at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:271) 
                                                                            at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:380) 
                                                                            at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:345) 
                                                                            at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:134) 
                                                                            at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91) 
                                                                            at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:68) 
                                                                            at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71) 
                                                                            at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:48) 
                                                                            at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:271) 
                                                                            at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:241) 
                                                                            at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:216) 
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                            at java.lang.Thread.run(Thread.java:818) 
                                                                            at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:346)

**Comment by TWiStErRob** [comment]
3.7.0 doesn't have `newIoExceptionForInBitmapAssertion` neither `SourceGenerator`: https://github.com/bumptech/glide/blob/v3.7.0/library/src/main/java/com/bumptech/glide/load/resource/bitmap/Downsampler.java

You must be using the v4 snapshot.

**Comment by TWiStErRob** [comment]
I tried to reproduce it, but couldn't get the strategy to reuse the bitmap as yours did.

Can you please get a full log (Glide tags only), from app startup to this exception above from the same run? Bitmap reuse issues are usually more complex and stuff that's in the bitmap pool affect it very much. Best would be if you can present with a simple repro app in a github repo and repro steps, please.

**Comment by liubo123** [comment]
I have sent my project to your mailbox. 
Please try to use Huawei mobile phones, most of Huawei's mobile phone can not be displayed, thank you.

**Comment by liubo123** [comment]
I think it should be decoding compatibility issues
