### ISSUE TITLE
java.lang.IllegalStateException: Activity has been destroyed on Nested Fragment (Demo Project Inside)

### ISSUE THREAD

**Issue by jt-gilkeson** [bumptech/glide#1592]
**Glide Version**: 3.7.0

**Issue details / Repro steps / Use case background**: 
Use Case: Master/Detail view with choices on the left, and nested detail fragments on the right (many different kinds).  All of our detail fragments work fine, except the one that uses Glide to load images.

Details of Simple Demo: Master/Detail view with Master fragment being retained, and nested Detail fragment being replaced anytime after a rotation.  Calling Glide.with(this).load in the new replacement fragment will crash.

I've created a project to demonstrate: https://github.com/jt-gilkeson/GlideCrash

Note: this project uses a technique to retain the child fragment manager to get around a bug in the Support Lib.

Steps to reproduce:

- Launch App, Press Show Details Fragment.  Notice nested fragment displays.
- Rotate, Notice Details Fragment is still there.  
- Click Show Details Fragment (creates a new fragment to replace the existing one) crash:

```
FATAL EXCEPTION: main
    Process: com.jt.glidecrash, PID: 11153
    java.lang.IllegalStateException: Activity has been destroyed
        at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1515)
        at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:638)
        at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:621)
        at com.bumptech.glide.manager.RequestManagerRetriever.getSupportRequestManagerFragment(RequestManagerRetriever.java:187)
        at com.bumptech.glide.manager.SupportRequestManagerFragment.onAttach(SupportRequestManagerFragment.java:116)
        at android.support.v4.app.Fragment.onAttach(Fragment.java:1165)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1019)
        at android.support.v4.app.BackStackRecord.setLastIn(BackStackRecord.java:779)
        at android.support.v4.app.BackStackRecord.calculateFragments(BackStackRecord.java:802)
        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:660)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
        at android.support.v4.app.Fragment.performStart(Fragment.java:1996)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Using other image libraries this way does not crash - it's glide-specific.  

Note: 

- Glide.with(this) (fragment) crashes when you create a new Details fragment and replace.
- Glide.with(iv.getContext()) crashes on rotation. 
- Glide.with(getActivity()) crashes on rotation.
- Glide.with(getContext().getApplicationContext()) works (and appears to be the only way to get this to work)

Disclaimer: I know that people don't like using Retained Instance for UI, and that using the workaround for the support lib problem seems like a hack, but hopefully this example will help debug what's going on in Glide under the covers that may be causing this issue for more conventional uses.

This may be a related to or a dupe of issues:

- https://github.com/bumptech/glide/issues/795
- https://github.com/bumptech/glide/issues/850

**Comment by weitzj** [comment]
Maybe this might be related to the `childFragmentManager` (https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/manager/RequestManagerRetriever.java#L163) and Glide should use the same workaround as you did https://github.com/jt-gilkeson/GlideCrash/blob/master/app/src/main/java/com/jt/glidecrash/MasterFragment.java#L76

https://code.google.com/p/android/issues/detail?id=42601
http://stackoverflow.com/questions/15207305/getting-the-error-java-lang-illegalstateexception-activity-has-been-destroyed/15656428#15656428

**Comment by sjudd** [comment]
Argh well I'm a day (year) late and a dollar short, but I did try out these steps and the sample app after updating to Glide v4 and I'm no longer able to reproduce this. I'd guess an issue was fixed in the support library?

**Comment by jt-gilkeson** [comment]
Wow they finally fixed the childfragmentmanager bug!   Thanks for the followup.
