### ISSUE TITLE
Problem with glide in conjunction with robolectric

### ISSUE THREAD

**Issue by bartoszwilk** [bumptech/glide#1606]
**Glide Version**: 3.7.0
**Robolectric Version**: 3.1.4

Related issue on Robolectric github: [#2726](https://github.com/robolectric/robolectric/issues/2726)

We encountered a problem with Glide when writing tests in Robolectric. 
We are creating a shadowActivity with RecyclerView and injected presenter.

When we call setUserList() on that activity, the activity sets those items on the adapter and ViewHolder's bind() method is called.
In this method we use Glide to load image from the url and put it into imageView.

Here is our test's class code: 

```java
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 21)
public class ListingActivityTest {

    @Mock
    private ListingPresenter mListingPresenter;

    @InjectMocks
    private ListingActivity mListingActivity = Robolectric.setupActivity(ListingActivity.class);

    @Before
    public void setUp() throws Exception {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetContent() throws Exception {
        User user1 = new User();
        User user2 = new User();
        User user3 = new User();
        user1.setLogin("first");
        user2.setLogin("second");
        user3.setLogin("third"); 
        user1.setAvatarUrl("http://www.thewrap.com/wp-content/uploads/2016/09/1200.jpg");
        user2.setAvatarUrl("http://www.thewrap.com/wp-content/uploads/2016/09/1200.jpg");
        user3.setAvatarUrl("http://www.thewrap.com/wp-content/uploads/2016/09/1200.jpg");
        mListingActivity.setUserList(Arrays.asList(user1, user2, user3));
        ...
    }
}
```

Here is the ViewHolder:
```java
public class UserViewHolder extends RecyclerView.ViewHolder {

    @BindView(R.id.avatar)
    ImageView mAvatarImageView;
    @BindView(R.id.login)
    TextView mLoginTextView;
    @BindView(R.id.url)
    TextView mUrlTextView;
    private View mRowView;

    public UserViewHolder(View itemView) {
        super(itemView);
        this.mRowView = itemView;
        ButterKnife.bind(this, itemView);
    }

    public void bind(User user, UserAdapter.UserClickListener userClickListener) {
        mLoginTextView.setText(user.getLogin());
        mUrlTextView.setText(user.getUrl());

        Glide.with(mRowView.getContext())
                .load(user.getAvatarUrl())
                .into(mAvatarImageView);

        mRowView.setOnClickListener(v -> userClickListener.onUserClick(user));
    }
}
```

When the setUserList() method is called, the test fails and we are getting the following cast exception:
```ruby
java.lang.ClassCastException: Cannot cast com.mateuszkoslacz.moviper.rxsample.viper.presenter.ListingPresenter$$EnhancerByMockitoWithCGLIB$$5fd48d18 to org.robolectric.shadows.ShadowActivity

	at java.lang.invoke.MethodHandleImpl.newClassCastException(MethodHandleImpl.java:361)
	at java.lang.invoke.MethodHandleImpl.castReference(MethodHandleImpl.java:356)
	at android.app.Activity.getWindow(Activity.java)
	at android.support.v4.app.FragmentActivity$HostCallbacks.onHasView(FragmentActivity.java:1094)
	at android.support.v4.app.BackStackRecord.calculateFragments(BackStackRecord.java:854)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:719)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:541)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:144)
	at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:30)
	at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:105)
	at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:354)
	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:256)
	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:237)
	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:220)
	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:210)
	at org.robolectric.util.Scheduler.setIdleState(Scheduler.java:79)
	at org.robolectric.util.Scheduler.unPause(Scheduler.java:113)
	at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:307)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:358)
	at org.robolectric.shadows.ShadowViewGroup.addView(ShadowViewGroup.java:34)
	at android.view.ViewGroup.addView(ViewGroup.java)
	at android.view.ViewGroup.addView(ViewGroup.java:3678)
	at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:676)
	at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
	at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:7399)
	at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7357)
	at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7345)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1459)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1408)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:580)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3374)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3183)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3627)
	at android.view.View.layout(View.java:15596)
	at android.view.ViewGroup.layout(ViewGroup.java:4966)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
	at android.view.View.layout(View.java:15596)
	at android.view.ViewGroup.layout(ViewGroup.java:4966)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15596)
	at android.view.ViewGroup.layout(ViewGroup.java:4966)
	at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
	at android.view.View.layout(View.java:15596)
	at android.view.ViewGroup.layout(ViewGroup.java:4966)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15596)
	at android.view.ViewGroup.layout(ViewGroup.java:4966)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15596)
	at android.view.ViewGroup.layout(ViewGroup.java:4966)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15596)
	at android.view.ViewGroup.layout(ViewGroup.java:4966)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2072)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1829)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:144)
	at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:30)
	at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:105)
	at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:312)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:152)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:141)
	at org.robolectric.shadows.ShadowMessageQueue.enqueueMessage(ShadowMessageQueue.java:126)
	at android.os.MessageQueue.enqueueMessage(MessageQueue.java)
	at android.os.Handler.enqueueMessage(Handler.java:631)
	at android.os.Handler.sendMessageAtTime(Handler.java:600)
	at android.os.Handler.sendMessageDelayed(Handler.java:570)
	at android.os.Handler.postDelayed(Handler.java:398)
	at org.robolectric.shadows.ShadowChoreographer.postCallbackDelayed(ShadowChoreographer.java:49)
	at android.view.Choreographer.postCallbackDelayed(Choreographer.java)
	at android.view.Choreographer.postCallback(Choreographer.java:291)
	at android.view.ViewRootImpl.scheduleTraversals(ViewRootImpl.java:1025)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:869)
	at android.view.View.requestLayout(View.java:17364)
	at org.robolectric.internal.ProxyMaker$GeneratedProxy/1008188683.requestLayout(Unknown Source)
	at org.robolectric.shadows.ShadowView.requestLayout(ShadowView.java:218)
	at android.view.View.requestLayout(View.java)
	at android.view.View.requestLayout(View.java:17364)
	at org.robolectric.internal.ProxyMaker$GeneratedProxy/1008188683.requestLayout(Unknown Source)
	at org.robolectric.shadows.ShadowView.requestLayout(ShadowView.java:218)
	at android.view.View.requestLayout(View.java)
	at android.view.View.requestLayout(View.java:17364)
	at org.robolectric.internal.ProxyMaker$GeneratedProxy/1008188683.requestLayout(Unknown Source)
	at org.robolectric.shadows.ShadowView.requestLayout(ShadowView.java:218)
	at android.view.View.requestLayout(View.java)
	at android.view.View.requestLayout(View.java:17364)
	at org.robolectric.internal.ProxyMaker$GeneratedProxy/1008188683.requestLayout(Unknown Source)
	at org.robolectric.shadows.ShadowView.requestLayout(ShadowView.java:218)
	at android.view.View.requestLayout(View.java)
	at android.view.View.requestLayout(View.java:17364)
	at org.robolectric.internal.ProxyMaker$GeneratedProxy/1008188683.requestLayout(Unknown Source)
	at org.robolectric.shadows.ShadowView.requestLayout(ShadowView.java:218)
	at android.view.View.requestLayout(View.java)
	at android.view.View.requestLayout(View.java:17364)
	at org.robolectric.internal.ProxyMaker$GeneratedProxy/1008188683.requestLayout(Unknown Source)
	at org.robolectric.shadows.ShadowView.requestLayout(ShadowView.java:218)
	at android.view.View.requestLayout(View.java)
	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:360)
	at android.view.View.requestLayout(View.java:17364)
	at org.robolectric.internal.ProxyMaker$GeneratedProxy/1008188683.requestLayout(Unknown Source)
	at org.robolectric.shadows.ShadowView.requestLayout(ShadowView.java:218)
	at android.view.View.requestLayout(View.java)
	at android.support.v7.widget.RecyclerView.requestLayout(RecyclerView.java:3635)
	at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onChanged(RecyclerView.java:4792)
	at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:10764)
	at android.support.v7.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:6342)
	at com.mateuszkoslacz.moviper.rxsample.viper.view.adapter.UserAdapter.setUserList(UserAdapter.java:46)
	at com.mateuszkoslacz.moviper.rxsample.viper.view.activity.ListingActivity.setUserList(ListingActivity.java:67)
	at com.mateuszkoslacz.moviper.rxsample.viper.view.activity.ListingActivityTest.testSetContent(ListingActivityTest.java:130)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:498)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:245)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:171)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:137)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

It's kinda weird that ListingPresenter is trying to be casted to ShadowActivity when we are using Glide in ViewHolder.
However, this cast exception disappears and test succeeds when we use Picasso instead.

Have you guys ever met with similar problem?

**Comment by mkoslacz** [comment]
> in fact it looks like it's a problem with Robolectric and Mockito, it has nothing to do with Glide. 

This problem can be tracked in the mentioned issue on Robolectric github: [#2726](https://github.com/robolectric/robolectric/issues/2726).

Close this issue please.
