### ISSUE TITLE
java.lang.InternalError: Thread starting during runtime shutdown

### ISSUE THREAD

**Issue by chendiyou** [bumptech/glide#1629]
java.lang.InternalError: Thread starting during runtime shutdown
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:1063)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
	at com.bumptech.glide.load.engine.executor.a.run(SourceFile:118)

**Comment by sjudd** [comment]
Can you fill out the issue template? And provide reproducible steps?

**Comment by mhdtouban** [comment]
@sjudd  This also been reported by our crashlytics tool. 
Android version: 6.0.1
Brand: HTC
Model: HTC M10
Glide Version: 3.8.0
RAM free: 846.36 MB
Disk free: 3.45 GB
Stacktrace:
java.lang.Thread.nativeCreate (Thread.java)
java.lang.Thread.start (Thread.java:1063)
java.util.concurrent.ThreadPoolExecutor.addWorker (ThreadPoolExecutor.java:921)
java.util.concurrent.ThreadPoolExecutor.processWorkerExit (ThreadPoolExecutor.java:989)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1131)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)
com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run (SourceFile:118)

**Comment by sjudd** [comment]
I'd assume this happens when you start a new request while your application is crashing, being updated, or otherwise killed. I don't think there's anything we can do about it, but if you're able to reproduce it or have an idea of how we can fix it, let me know.

**Comment by amalnafia** [comment]
any updates in crash?
