### ISSUE TITLE
Picture skewing again in android-sdk-17 use glide 3.7.0

### ISSUE THREAD

**Issue by SimplySu** [bumptech/glide#1667]
**Glide Version**: 3.7.0

**Integration libraries**: none

**Device/Android Version**: Android SDK:17

**Issue details / Repro steps / Use case background**: 

I got a picture skewing showing on device about android sdk-17 version.
I note that 
#128(RequestTracker should not restart cleared requests in onResume)
#129(Image skewing)
and also #611(OOM in Android 4.1 caused by ARGB_8888 even if PREFER_RGB_565)

like the code description:
``` 
place:glide/library/src/main/java/com/bumptech/glide/load/resource/bitmap/Downsampler.java
private Bitmap.Config getConfig(InputStream is, DecodeFormat format) throws IOException {
    // Changing configs can cause skewing on 4.1, see issue #128.
    if (format == DecodeFormat.PREFER_ARGB_8888
        || Build.VERSION.SDK_INT == Build.VERSION_CODES.JELLY_BEAN) {
      return Bitmap.Config.ARGB_8888;
    }
```

I try setBitmapPool:
```builder.setBitmapPool(new BitmapPoolAdapter());```
but it didn't fix it,skewing always, how would I fix it use glide3.7.0,any tips?
@TWiStErRob @sjudd  thx so much. 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
// GlideModule
builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_8888);

// ImageView load
Glide.with(getContext()).load(PictureUtils.getUriFromUrl(picShow.getUrl())) // url
          .priority(isPointToShow == true ? Priority.HIGH : Priority.LOW) // priority
          .dontAnimate().thumbnail(0.1f) 
          .listener(getNormalRequestListener(imageView)) //listener
          .into(imageView.getSimpleDraweeView()); //just the ImageView

```

**Comment by SimplySu** [comment]
I notice that when image skewing ,some exception log below will happened. would it avoid?
@TWiStErRob @sjudd thx so much
**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
EXCEPTION: Mark has been invalidated

12-29 15:31:24.780 W/System.err(14806): com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException: Mark has been invalidated
12-29 15:31:24.784 W/System.err(14806):         at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.reset(RecyclableBufferedInputStream.java:350)
12-29 15:31:24.784 W/System.err(14806):         at com.bumptech.glide.util.ExceptionCatchingInputStream.reset(ExceptionCatchingInputStream.java:94)
12-29 15:31:24.784 W/System.err(14806):         at java.io.FilterInputStream.reset(FilterInputStream.java:154)
12-29 15:31:24.784 W/System.err(14806):         at com.bumptech.glide.util.MarkEnforcingInputStream.reset(MarkEnforcingInputStream.java:51)
12-29 15:31:24.784 W/System.err(14806):         at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
12-29 15:31:24.784 W/System.err(14806):         at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:534)
12-29 15:31:24.784 W/System.err(14806):         at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:329)
12-29 15:31:24.784 W/System.err(14806):         at com.bumptech.glide.load.resource.bitmap.Downsampler.downsampleWithSize(Downsampler.java:220)
12-29 15:31:24.784 W/System.err(14806):         at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:153)
12-29 15:31:24.784 W/System.err(14806):         at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:50)
12-29 15:31:24.784 W/System.err(14806):         at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
12-29 15:31:24.788 W/System.err(14806):         at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:39)
12-29 15:31:24.788 W/System.err(14806):         at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)
12-29 15:31:24.788 W/System.err(14806):         at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:190)
12-29 15:31:24.788 W/System.err(14806):         at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
12-29 15:31:24.788 W/System.err(14806):         at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
12-29 15:31:24.788 W/System.err(14806):         at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
12-29 15:31:24.788 W/System.err(14806):         at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
12-29 15:31:24.788 W/System.err(14806):         at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
12-29 15:31:24.788 W/System.err(14806):         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
12-29 15:31:24.788 W/System.err(14806):         at java.util.concurrent.FutureTask.run(FutureTask.java:234)
12-29 15:31:24.788 W/System.err(14806):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
12-29 15:31:24.788 W/System.err(14806):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
12-29 15:31:24.788 W/System.err(14806):         at java.lang.Thread.run(Thread.java:856)
12-29 15:31:24.788 W/System.err(14806):         at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
12-29 15:31:24.788 D/skia    (14806): ------- reset threw an exception
```

**Comment by SimplySu** [comment]
Close for that it was ok showing on some android emulators , only happened in some special machines with sdk-17(perhaps some bugs with these machines framework).

So I change the glide imageDecoder(**use Android default Bitmap Decoder**) to avoid it only in some special machine with sdk-17.
