### ISSUE TITLE
Issues running Glide with Robolectic inside a custom view

### ISSUE THREAD

**Issue by 4gus71n** [bumptech/glide#1696]
**Glide Version**: com.github.bumptech.glide:glide:3.5.2

**Integration libraries**: org.robolectric:robolectric:3.1.2, org.mockito:mockito-core:1.+

**Device/Android Version**: None

I have several Unit Tests in my App code, most of them uses Glide one way or another, I have no problem with any of these. However I was writting a new Unit Test for a Fragment, this Fragment is held by a common AppCompatActivity and contains a custom view called CardBackView. In CardBackView I'm loading some images using Glide, but I'm getting this error when I try to run the test:

```ruby
java.lang.IllegalStateException: FragmentManager is already executing transactions

	at android.support.v4.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:1946)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1992)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:709)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:144)
	at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:30)
	at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:105)
	at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:293)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:143)
	at org.robolectric.shadows.ShadowMessageQueue.enqueueMessage(ShadowMessageQueue.java:126)
	at android.os.MessageQueue.enqueueMessage(MessageQueue.java)
	at android.os.Handler.enqueueMessage(Handler.java:631)
	at android.os.Handler.sendMessageAtTime(Handler.java:600)
	at android.os.Handler.sendMessageDelayed(Handler.java:570)
	at android.os.Handler.post(Handler.java:326)
	at android.support.v4.app.FragmentManagerImpl.scheduleCommit(FragmentManager.java:1877)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1860)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:643)
	at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:608)
	at com.bumptech.glide.manager.RequestManagerRetriever.supportFragmentGet(RequestManagerRetriever.java:178)
	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:103)
	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:86)
	at com.bumptech.glide.Glide.with(Glide.java:609)
	at com.siplay.android_siplay.ui.customView.CardBackView.updatePlayerImages(CardBackView.java:249)
	at com.siplay.android_siplay.ui.customView.CardBackView.setmImages(CardBackView.java:478)
	at com.siplay.android_siplay.ui.fragment.CardFlipFragment.showPlayerImages(CardFlipFragment.java:607)
	at com.siplay.android_siplay.ui.presenter.player.PlayerCardPresenterImp.onImagesFetched(PlayerCardPresenterImp.java:159)
	at com.siplay.android_siplay.domain.interactor.player.GetPlayerImagesInteractor$1.onResponse(GetPlayerImagesInteractor.java:41)
	at com.siplay.android_siplay.domain.interactor.player.GetPlayerImagesInteractor$1.onResponse(GetPlayerImagesInteractor.java:25)
	at com.si.play.di.MockRepositoryModule$MockPlayerRepository.getPlayerImages(MockRepositoryModule.java:220)
	at com.siplay.android_siplay.domain.interactor.player.GetPlayerImagesInteractor.execute(GetPlayerImagesInteractor.java:25)
	at com.siplay.android_siplay.ui.presenter.player.PlayerCardPresenterImp.getPlayerImages(PlayerCardPresenterImp.java:111)
	at com.siplay.android_siplay.ui.fragment.CardFlipFragment.onCreateView(CardFlipFragment.java:272)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2184)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1298)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(FragmentManager.java:2323)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2136)
	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1998)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:709)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:144)
	at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:30)
	at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:105)
	at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:293)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:143)
	at org.robolectric.shadows.ShadowMessageQueue.enqueueMessage(ShadowMessageQueue.java:126)
	at android.os.MessageQueue.enqueueMessage(MessageQueue.java)
	at android.os.Handler.enqueueMessage(Handler.java:631)
	at android.os.Handler.sendMessageAtTime(Handler.java:600)
	at android.os.Handler.sendMessageDelayed(Handler.java:570)
	at android.os.Handler.post(Handler.java:326)
	at android.support.v4.app.FragmentManagerImpl.scheduleCommit(FragmentManager.java:1877)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1860)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:643)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:603)
	at com.si.play.fragment.CardFlipFragmentTest.setUp(CardFlipFragmentTest.java:107)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:250)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:176)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:142)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

This is my Unit Test:

```java
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 23, application = SipTestApplication.class)
public class CardFlipFragmentTest extends SipBaseTest {

   private static class PlayerCardsInteractorModule extends MockInteractorModule {
        @Override
        public CheckFeatureFlag provideCheckFeatureFlagInteractor() {
            //Mock this so we have enable the FA list
            CheckFeatureFlag mockedFeatureFlag = mock(CheckFeatureFlag.class);
            when(mockedFeatureFlag.check(any(Context.class), eq(FeatureFlags.FAMILY_ACCOUNTS))).
                    thenReturn(true);
            return mockedFeatureFlag;
        }
    }

    CardFlipFragment mCard;

    @Before
    public void setUp() throws Exception {
        setCustomMockInteractorModule(new PlayerCardsInteractorModule());

        mCard = new CardFlipFragment();

        Player player = MockitoUtils.buildMockedPlayer(this);
        Team team = MockitoUtils.buildMockedTeam(this);
        PlayerHistory playerHistory = MockitoUtils.buildMockedPlayerHistory(this);

        mCard.setmHistory(playerHistory);
        mCard.setmPlayer(player);
        mCard.setmTeam(team);

        AppCompatActivity activity = Robolectric.buildActivity(AppCompatActivity.class)
                .create()
                .start()
                .get();

        activity.getSupportFragmentManager()
                .beginTransaction()
                .add(mCard, TeamDetailActivity.FRAGMENT_CARD)
                .commit();

        setUpFragment(mCard);
    }

    /**
     * Check that we load all the contact data as we should
     * @throws Exception
     */
    @Test
    public void testLoading() throws Exception {
        CardBackView backCardView = mCard.getBackCardView();
        LinearLayout contactsContainer = backCardView.getContactsContainer();

        LinearLayout familyContainer = backCardView.getFamilyContainer();

        Log.d("asdasdad", "asdadas");
    }

}
```

I'm executing the testLoading method. And this is the code that triggers the error in the custom view:

```java
if (mImages.size() > 0) {

    mRecentImage1.setVisibility(View.VISIBLE);

    Glide.with(getContext())
            .load(mImages.get(0).getMediumPhotoUrl())
            .asBitmap()
            .into(new SimpleTarget<Bitmap>() {
                @Override
                public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                    mRecentImage1.setImageBitmap(resource);
                }
            });
}
```

I checked that the URL is not null, I tried setting the image using into(ImageView) and removing the asBitmap() but It always triggers the same error.

Any clue about what I'm doing wrong? Thanks in advance.

**Comment by TWiStErRob** [comment]
From the stack trace it looks like the async behavior of the main thread is not happening and the fragment manager gets confused. Sounds like you ran into https://github.com/robolectric/robolectric/issues/1306.

You need to make sure `Scheduler`:
```java
  public synchronized void postDelayed(Runnable runnable, long delayMillis) {
    if ((idleState != CONSTANT_IDLE && (isPaused() || delayMillis > 0)) || Thread.currentThread() != associatedThread) {
      queueRunnableAndSort(runnable, currentTime + delayMillis);
    } else {
      runOrQueueRunnable(runnable, currentTime + delayMillis);
    }
  }
```
doesn't call `runOrQueueRunnable`.

**Comment by kingargyle** [comment]
Ran into this today.  Simplest work arounds was to pause the foreground and background schedulers in the test.
