### ISSUE TITLE
GC occurred frequently and any new images can not be loaded

### ISSUE THREAD

**Issue by vincgao** [bumptech/glide#1701]
**Glide Version**: Glide 3.7

**Integration libraries**: OkHttp3

**Device/Android Version**: Samsung SM-C7000, Android 6.0.1

**Issue details / Repro steps / Use case background**: 
This problem has been bothering me for days. Sometimes, I found  **All of** ImageViews in my app can not load new images with Glide. If a image is cached before this, it can be loaded normally in  ImageView, but a new file can not be loaded with Glide.

My MainActivity has a ViewPager with 4 pages(Fragments). Three of them have a RecyclerView, the Rv mainly consists of ImageViews.I try some optimization mentioned in other issues, like:
1. I don't use `ViewPager.setOffscreenPageLimit();` specially
2. Use `Glide.with(fragment)` in fragments
3. Call `Glide.clear(imageView)` in `onViewRecycled()`
But this problem still exists in my app !

The phenomenon is not occur every time in my application.But if it occurred, you can only kill the app and restart it to bring the app back to normal. I'm using [LeakCanary](https://github.com/square/leakcanary) in my project, and LeakCanary didn't report any memory leaks event. I can guarantee the network is stable.(The same app in another Android phone works well in the same time)

I don't know how to recurrence this problem , and have no idea how to debug it, so I want to some help. 

Thanks everyone.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
public class MainNewestAdapter extends RecyclerAdapter<RecyclerView.ViewHolder> {

    private List<Show> mDataList;
    private int mCoverWidth;
    private Fragment mHost;

    public MainNewestAdapter(Fragment fragment, List<Show> list) {
        mHost = fragment;
        mDataList = list;
        mCoverWidth = (CommonUtils.getScreenWidth() - CommonUtils.dp2px(4) * 4) / 3;
    }

    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        if (viewType == R.layout.item_main_newest_header) {
            View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_main_newest_header, parent, false);
            return new HeaderViewHolder(view);
        } else {
            View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_main_newest, parent, false);
            return new ItemViewHolder(view);
        }
    }

    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
        if (holder instanceof ItemViewHolder) {
            int realPosition = position - 1;
            ItemViewHolder itemHolder = (ItemViewHolder) holder;
            Show show = mDataList.get(realPosition);
            itemHolder.tvCity.setText(show.city);
            itemHolder.tvName.setText(show.creator.name);
            FrameLayout.LayoutParams params = (FrameLayout.LayoutParams) itemHolder.ivCover.getLayoutParams();
            params.width = mCoverWidth;
            params.height = mCoverWidth;
            if (mHost != null && mHost.getActivity() != null) {
                Glide.with(mHost)
                        .load(show.creator.photoUrl)
                        .centerCrop()
                        .placeholder(R.drawable.live_holder)
                        .into(itemHolder.ivCover);
            }
        }
    }

    @Override
    public int getItemCount() {
        if (mDataList.isEmpty()) {
            return 0;
        }
        return mDataList.size() + 1;
    }

    @Override
    public int getItemViewType(int position) {
        if (position == 0) {
            return R.layout.item_main_newest_header;
        } else {
            return R.layout.item_main_newest;
        }
    }

    @Override
    public void onViewRecycled(RecyclerView.ViewHolder holder) {
        super.onViewRecycled(holder);
        if (holder instanceof ItemViewHolder) {
            ItemViewHolder itemHolder = (ItemViewHolder) holder;
            Glide.clear(itemHolder.ivCover);
        }
    }

    public static class ItemViewHolder extends RecyclerView.ViewHolder {
        @BindView(R.id.iv_cover) ImageView ivCover;
        @BindView(R.id.tv_city) TextView tvCity;
        @BindView(R.id.tv_name) TextView tvName;
        @BindView(R.id.ll_parent) LinearLayout llParent;

        public ItemViewHolder(View itemView) {
            super(itemView);
            ButterKnife.bind(this, itemView);
        }
    }

    public static class HeaderViewHolder extends RecyclerView.ViewHolder {
        public HeaderViewHolder(View itemView) {
            super(itemView);
        }
    }
}
```

**Layout XML**:
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/ll_parent"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:paddingLeft="2dp"
    android:paddingRight="2dp"
    android:paddingBottom="10dp"
    android:orientation="vertical">

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
        <ImageView
            android:id="@+id/iv_cover"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:scaleType="centerCrop"/>

        <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginLeft="5dp"
            android:layout_marginBottom="4dp"
            android:layout_gravity="bottom"
            android:orientation="horizontal">
            <ImageView
                android:layout_width="8dp"
                android:layout_height="wrap_content"
                android:adjustViewBounds="true"
                android:layout_gravity="center_vertical"
                android:src="@drawable/location_shadow"/>

            <TextView
                android:id="@+id/tv_city"
                style="@style/font_shadow"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="3dp"
                android:maxLines="1"
                android:ellipsize="end"
                android:textSize="12sp"/>
        </LinearLayout>
    </FrameLayout>

    <TextView
        android:id="@+id/tv_name"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textColor="@color/color66"
        android:maxLines="1"
        android:ellipsize="end"
        android:textSize="14sp"
        android:layout_marginTop="2dp"
        android:layout_marginLeft="5dp"
        android:layout_marginRight="10dp"/>
</LinearLayout>
```

 **All** ImageViews in my app can not load images. Like this,
![wechatimg538](https://cloud.githubusercontent.com/assets/3355843/22204330/61b3781a-e1ac-11e6-97a8-31ec9ce16363.png)

In Android Studio Android Monitor, We can see GC is looping frequently, and cpu is busying. The memory usage is not large enough. 
<img width="593" alt="screen shot 2017-01-23 at 20 26 03" src="https://cloud.githubusercontent.com/assets/3355843/22204324/58c623b0-e1ac-11e6-9aca-ef528d5a5ce8.png">

**Comment by TWiStErRob** [comment]
Try to call `setLayoutParams` and add an `.override(mCoverWidth, mCoverWidth)` as that's what you want to happen, judging from your code.

You should also consider a 3-column `GridLayoutManager` with a `4dp` left-right padding + a layout that allows for square views (PercentLayout with aspect ratio of 1, or [SquareFrameLayout](https://github.com/bumptech/glide/issues/439#issuecomment-95748769). This should remove all trickery from your adapter and let the Android View hierarchy do its job.

---

To figure out what's going on you should check what Glide is doing: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

I suspect OOMs. The usual reason it happens is because you have 3 lists, all bound at the same time. If you don't clean them they stay alive and all their images are hogging the memory. This results in the foreground list not being able to load the bitmaps, while the 2 background lists happily keep their images in memory.

**Comment by vincgao** [comment]
Thanks, I will try adjusting my hierarchy. 
But why did the app not crash in this phenomenon if the OOM occurred? And from the Android Monitor, I can see the memory usage is not large enough. That bothers me a lot.

**Comment by TWiStErRob** [comment]
I suspect OOMs because you said frequent GC, only you see what is actually thrown (if you did what's on the wiki). It's possible you don't receive an OOM, but even if you do, I think in Android an app only crashes when the Main/UI thread receives an uncaught exception. Background threads (especially self-managed ones like Glide's pooled ones) will not cause a full-crash, only that Thread dies and the stack trace is printed. Take a look at `java.lang.ThreadGroup#uncaughtException` to see what I mean.

**Comment by vincgao** [comment]
After reading [Debugging-and-Error-Handling](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling), I found these error log when I reproduced the issue.
```java
02-06 16:28:07.213 V/IVML: Exception fetching input stream, trying ParcelFileDescriptorjava.io.IOException: Canceled
           at okhttp3.RealCall.getResponse(RealCall.java:238)
           at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
           at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
           at okhttp3.RealCall.execute(RealCall.java:57)
           at com.bumptech.glide.integration.okhttp3.OkHttpStreamFetcher.loadData(OkHttpStreamFetcher.java:43)
           at com.bumptech.glide.integration.okhttp3.OkHttpStreamFetcher.loadData(OkHttpStreamFetcher.java:19)
           at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:70)
           at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:53)
           at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
           at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
           at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
           at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
           at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
           at java.lang.Thread.run(Thread.java:818)
           at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
02-06 16:28:07.213 V/EngineRunnable: Exception decodingjava.io.IOException: Canceled
           at okhttp3.RealCall.getResponse(RealCall.java:238)
           at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
           at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
           at okhttp3.RealCall.execute(RealCall.java:57)
           at com.bumptech.glide.integration.okhttp3.OkHttpStreamFetcher.loadData(OkHttpStreamFetcher.java:43)
           at com.bumptech.glide.integration.okhttp3.OkHttpStreamFetcher.loadData(OkHttpStreamFetcher.java:19)
           at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:70)
           at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:53)
           at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
           at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
           at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
           at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
           at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
           at java.lang.Thread.run(Thread.java:818)
           at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
```

**Comment by TWiStErRob** [comment]
That exception looks like another bind to the same imageView is cancelling the previous load, but that should be normal when scrolling.

> recycle images inside RecycleView when the ImageView is not visible
You already have `Glide.clear` in `onViewRecycled`, nothing better than that. I suggest `if (hasImage()) load(image).into(iv); else Glide.clear(iv);` in bind, but I didn't see conditional logic above.

**Comment by zhaiyuzhai** [comment]
@vincgao hello，请问这个问题后来有什么解决方案吗，我们遇到了和您一样类似的问题，一旦出现这种情况，就必须要杀掉进程重新打开。版本是Glide@3.8.0
