### ISSUE TITLE
FragmentActivity.onDestroy() causes java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by Will5** [bumptech/glide#1722]
If a FragmentActivity is destroyed, then it will throw an Exception due to RequestManager.pauseRequests() calling Util.assertMainThread(). (This stack trace is from 3.8.0-SNAPSHOT, but reproducible on 3.7.0 as well)

```
Fatal Exception: java.lang.IllegalArgumentException: You must call this method on the main thread
       at com.bumptech.glide.util.Util.assertMainThread(Util.java:135)
       at com.bumptech.glide.RequestManager.pauseRequests(RequestManager.java:147)
       at com.bumptech.glide.RequestManager.onStop(RequestManager.java:212)
       at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStop(ActivityFragmentLifecycle.java:57)
       at com.bumptech.glide.manager.SupportRequestManagerFragment.safedk_SupportRequestManagerFragment_onStop_1e0524360de126072eb3da6c812a77d8(SupportRequestManagerFragment.java:153)
       at com.bumptech.glide.manager.SupportRequestManagerFragment.onStop(SupportRequestManagerFragment.java)
       at android.support.v4.app.Fragment.performStop(Fragment.java:2376)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1360)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1523)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1585)
       at android.support.v4.app.FragmentManagerImpl.dispatchReallyStop(FragmentManager.java:2859)
       at android.support.v4.app.FragmentController.dispatchReallyStop(FragmentController.java:249)
       at android.support.v4.app.FragmentActivity.onReallyStop(FragmentActivity.java:816)
       at android.support.v4.app.FragmentActivity.doReallyStop(FragmentActivity.java:795)
       at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:388)
```

**Comment by Will5** [comment]
I stand corrected: The stack trace above was another crash, which I fixed. The stack trace below is the crash I described. If a FragmentActivity is destroyed, then it will throw an Exception due to the Activity being destroyed. I'm checking if (activity != null) && if (!activity.isFinishing()) && if (!(Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1 && activity.isDestroyed())) before calling Glide, but I get the following:

```
java.lang.IllegalStateException: Activity has been destroyed
    at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1854)
    at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:643)
    at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:608)
    at com.bumptech.glide.manager.RequestManagerRetriever.getSupportRequestManagerFragment(RequestManagerRetriever.java:187)
    at com.bumptech.glide.manager.RequestManagerRetriever.supportFragmentGet(RequestManagerRetriever.java:195)
    at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:104)
    at com.bumptech.glide.Glide.with(Glide.java:653)
```

**Comment by Will5** [comment]
This is actually similar to assertNotDestroyed(activity);, which returned true in RequestManagerRetriever.get(FragmentActivity activity)

**Comment by Emeritus-DarranKelinske** [comment]
Did you find a fix for this?

**Comment by Will5** [comment]
I actually forgot about this crash. I don't see any new crash reports, but I also see that I'm ignoring it, so I may only be masking it. The method is wrapped in a runOnUiThread() and a try/catch block. The first catch block catches InterruptedException and ExecutionException and handles it gracefully, and the second catch block catches Exception and sets a result code. Let me know if this works for you.
