### ISSUE TITLE
 Loading too many images to cause OOM

### ISSUE THREAD

**Issue by zhanfangzxc** [bumptech/glide#1736]
I have a ViewPager,and Viewpager include RecyclerView, each item of recyclerview is a Imageview，i use Glide to load Images,so:

```
 Caused by: java.lang.OutOfMemoryError: Failed to allocate a 2073612 byte allocation with 763344 free bytes and 745KB until OOM
                                                                     at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
                                                                     at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:639)
                                                                     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:615)
                                                                     at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:329)
                                                                     at com.bumptech.glide.load.resource.bitmap.Downsampler.downsampleWithSize(Downsampler.java:220)
                                                                     at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:153)
                                                                     at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:50)
                                                                     at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
                                                                     at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:39)
                                                                     at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)
                                                                     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeBitmapWrapper(GifBitmapWrapperResourceDecoder.java:121)
                                                                     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeStream(GifBitmapWrapperResourceDecoder.java:94)
                                                                     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:71)
                                                                     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:61)
                                                                     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:22)
                                                                     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperStreamResourceDecoder.decode(GifBitmapWrapperStreamResourceDecoder.java:24)
                                                                     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperStreamResourceDecoder.decode(GifBitmapWrapperStreamResourceDecoder.java:14)
                                                                     at com.bumptech.glide.load.resource.file.FileToStreamDecoder.decode(FileToStreamDecoder.java:39)
                                                                     at com.bumptech.glide.load.resource.file.FileToStreamDecoder.decode(FileToStreamDecoder.java:17)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.loadFromCache(DecodeJob.java:222)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.decodeResultFromCache(DecodeJob.java:85)
                                                                     at com.bumptech.glide.load.engine.EngineRunnable.decodeFromCache(EngineRunnable.java:108)
                                                                     at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:99)
                                                                     at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                     at java.lang.Thread.run(Thread.java:818) 
                                                                     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118) 
```

**Comment by gaara87** [comment]
👍

**Comment by hargoyal** [comment]
Same here...Is there any way to resolve it?

**Comment by JimVanG** [comment]
Lower your `ViewPagers` offscreenPageLimit: `viewPager.setOffscreenPageLimit(1);`. This will help reduce your applications memory footprint since you have multiple pages loading and potentially holding onto tons of images.

Make sure you override `onDestroyView()` to clear out your `adapter`, `RecyclerView`, and any other views you may be holding onto that you won't need since you *should* be recreating them when the `Fragment` page's view is recreated.

Example of `onDestroyView()`:
```Java
    @Override
    public void onDestroyView()
    {
        super.onDestroyView();
        if (recyclerView != null)
        {
            recyclerView.setAdapter(null);
            recyclerView.setLayoutManager(null);
            recyclerView.clearOnScrollListeners();
            recyclerView.addItemDecoration(null);
            recyclerView = null;
        }
        adapter = null;
        layoutManager = null;
        someView = null;
        anotherView = null;
    }
```

Also in your `RecyclerView` adapter be sure to override `onViewRecycled()`, there you can clear out any `Glide` requests like so:

```Java
    @Override
    public void onViewRecycled(MyViewHolder holder)
    {
        if (holder != null)
        {
            ImageView icon = holder.iconImageView;
            if (icon != null)
            {
                Glide.clear(icon);
                icon.setImageDrawable(null);
                icon.setImageBitmap(null);
            }
        }
        super.onViewRecycled(holder);
    }
```

Also, probably the most important thing to do is to use the right lifecycle with your `Glide.with()` statement. Always tie it to the closest lifecycle. So if you were loading an image in an `AppCompatActivity` you'd use: `Glide.with(this)...` (`this` being your `AppCompatActivity`).

Since you're using `Fragments` with `RecyclerViews` in a `ViewPager` you'll want to tie your `Glide` image loads to the **hosting** `Fragment`. So you'd want to pass in the `Glide` `RequestManager` to your `RecyclerViews` adapter, do that like so:

```Java
//
// A sample adapter.
//
public class MyAdapter extends RecyclerView.Adapter<ItemViewHolder>
{
// This is your glide request manager that you will use to load images, it'll be tied to your Fragments lifecycle.
private final RequestManager glide;

    public MyAdapter(
            /*Other Stuff maybe */
            RequestManager glide)
    {
       // Other stuff
        this.glide = glide;
    }
    @Override
    public void onBindViewHolder(ItemViewHolder holder, int position)
    {
             // Other stuff
             //....

                glide.load(iconUri)
                    .dontAnimate()
                    .dontTransform()
                    .into(holder.iconImageView);
    }
}

//
// A sample Fragment that creates the above Adapter.
//
public class MyFragment extents Fragment {

// do your regular set up stuff...

    @Override
    public void onActivityCreated(Bundle savedInstanceState)
    {
        super.onActivityCreated(savedInstanceState);
        
        // Passing in the Glide RequestManager that is tied to your fragment will allow it to follow the lifecycle events of Fragment
        adapter = new MyAdapter(Glide.with(this));
        recyclerView.setAdapter(adapter);
    }
}
```

More on this can be found here: https://stackoverflow.com/a/32887693/2371425

**Comment by gaara87** [comment]
I wonder if Glide will ever become lifecycle aware with the new architecture components coming into play

**Comment by JimVanG** [comment]
@gaara87, Glide _is_ "lifecycle aware," if you read my detailed comment above, or the [link I included to a SO answer](https://stackoverflow.com/a/32887693/2371425) from @TWiStErRob, you'll see that Glide _is_ lifecycle aware, you just need to make sure you're using Glide correctly (which is simple).

Follow the steps in my [comment above](https://github.com/bumptech/glide/issues/1736#issuecomment-307709314), or read the [SO answer](https://stackoverflow.com/a/32887693/2371425) from @TWiStErRob. These will show you how to utilize Glide's awesome `Activity`/`Fragment`/`Application` lifecycle awareness capabilities (it's highly recommended you follow those conventions).

Good luck. Let me know if if you have any other questions about this.

**Comment by gaara87** [comment]
I had read the post, but the lifecycle awareness seems to be strongly associated to the request only. Not the memory/bitmap usage. 

Imagine if the imageview can be cleared of the bitmap memory in onStop. That would save up a bunch of space by itself.

**Comment by TWiStErRob** [comment]
@gaara87 Yes, but the request is strongly associated to the view, so if either is cleared the other one is notified and freed. You can use `Glide.clear(*)` to manually free resources when you know you won't be needing them any more, or use `Glide.with()`/`Glide.get()` to call other lifecycle methods, but make sure you test all possibilities.
