### ISSUE TITLE
Canvas: trying to use a recycled bitmap android.graphics.Bitmap

### ISSUE THREAD

**Issue by sandip31** [bumptech/glide#1761]
App crashes while app goes to back ground(on backpressed or when remove app from background)
```java
glide.load(Utility.getImageUrl(context))
                    .asBitmap()
                    .transform(new RoundImageTransform(context))
                    .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                    .into(new SimpleTarget<Bitmap>() {
                @Override
                public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                    profileImage.setImageBitmap(resource);
                }
            });
```

and stacktrace is

```
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@e33d442
                                         at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
                                         at android.graphics.Canvas.drawBitmap(Canvas.java:1357)
                                         at android.graphics.Bitmap.createBitmap(Bitmap.java:759)
                                         at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:615)
                                         at com.pkmmte.view.CircularImageView.refreshBitmapShader(CircularImageView.java:341)
                                         at com.pkmmte.view.CircularImageView.invalidate(CircularImageView.java:262)
                                         at android.widget.ImageView.invalidateDrawable(ImageView.java:246)
                                         at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:390)
                                         at android.graphics.drawable.Drawable.setVisible(Drawable.java:769)
                                         at android.widget.ImageView.onDetachedFromWindow(ImageView.java:1485)
                                         at android.view.View.dispatchDetachedFromWindow(View.java:14766)
                                         at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3200)
                                         at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3200)
                                         at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3200)
                                         at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3200)
                                         at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3200)
                                         at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3200)
                                         at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3200)
                                         at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3200)
                                         at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3200)
                                         at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3200)
                                         at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3200)
                                         at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3200)
                                         at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3506)
                                         at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6204)
                                         at android.view.ViewRootImpl.die(ViewRootImpl.java:6176)
                                         at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:447)
                                         at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:402)
                                         at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
                                         at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4120)
                                         at android.app.ActivityThread.-wrap5(ActivityThread.java)
                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1547)
                                         at android.os.Handler.dispatchMessage(Handler.java:111)
                                         at android.os.Looper.loop(Looper.java:207)
                                         at android.app.ActivityThread.main(ActivityThread.java:5769)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by sandip31** [comment]
host image view is under navigation drawer

**Comment by TWiStErRob** [comment]
You should use `into(profileImage)` to get proper lifecycle handling. Glide notifies the target when the Bitmap is no longer valid, but `SimpleTarget` ignores that.

Note: why are you using both `CircularImageView` and `RoundImageTransform`?

**Comment by sandip31** [comment]
`CircularImageView` have native method to provide image border.

![screenshot_2017-03-02-09-22-13-371](https://cloud.githubusercontent.com/assets/12872544/23492335/cf278874-ff29-11e6-8c20-660ab48ecfec.jpeg)

can we achieve same thing with `RoundImageTransform`.

**Comment by zhaochuanxing** [comment]
You should use into(profileImage) to get proper lifecycle handling. Glide notifies the target when the Bitmap is no longer valid, but SimpleTarget ignores that.

hello,which is the proper lifecycle please ? @TWiStErRob
