### ISSUE TITLE
glide已经做了在主线程加载的判断了，为什么还有这个问题

### ISSUE THREAD

**Issue by dazhiyu** [bumptech/glide#1771]
java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
	at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134)
	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:102)
	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:87)
	at com.bumptech.glide.Glide.with(Glide.java:629)
	at com.bhtc.huajuan.manager.GlideManager.loadImage(GlideManager.java:86)
	at com.bhtc.huajuan.ui.activity.HotPersonActivity$AdvertPager.init(HotPersonActivity.java:624)
	at com.bhtc.huajuan.ui.activity.HotPersonActivity$AdvertPager.<init>(HotPersonActivity.java:618)
	at com.bhtc.huajuan.ui.activity.HotPersonActivity.setViewPager(HotPersonActivity.java:402)
	at com.bhtc.huajuan.ui.fragment.HotGoodsFragment$5.onResponse(HotGoodsFragment.java:153)
	at com.bhtc.huajuan.ui.fragment.HotGoodsFragment$5.onResponse(HotGoodsFragment.java:142)
	at com.zhy.http.okhttp.OkHttpUtils$4.run(OkHttpUtils.java:259)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5849)
	at java.lang.reflect.Method.invoke(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1109)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:875)

**Comment by dazhiyu** [comment]
if (Util.isOnMainThread()) {
            Glide
                    .with(context)
                    .load(url)
                    .diskCacheStrategy(DiskCacheStrategy.ALL)
                    .placeholder(R.drawable.icon_loading)
                    .error(R.drawable.icon_loading)
                    .fitCenter()
                    .animate(R.anim.fade_in)
                    .into(imageView);
        }

**Comment by xesam** [comment]
这个与是否在主线程无关，是因为 activity 被销毁而产生的错误，如果不担心内存泄露，就用 ApplicationContext

**Comment by dazhiyu** [comment]
。。。就是因为有内存泄露才改的这个（以前也用的是ApplicationContext而且在baseactivity中）：

@Override
    protected void onDestroy() {
        if (Util.isOnMainThread()) {
            Glide.get(this).clearMemory();
        }
        super.onDestroy();
    }

，还有什么好主意吗？

**Comment by simophin** [comment]
从你给的栈上来看，你的OkHttp的主线程回调发生在Activity被销毁之后，也就是说你的回调已经是在泄露内存了，这里跟主线程没关系。一般Activity销毁，你的请求也要跟着销毁才对

**Comment by qianshui423** [comment]
即使在调用点处判断了activity是否销毁，仍会在Glide.with时发生该崩溃，为什么不考虑到崩溃降级问题，而是直接崩溃呢
