### ISSUE TITLE
NullPointerException: Attempt to invoke interface method 'void java.util.List.clear()' on a null object reference

### ISSUE THREAD

**Issue by drmms** [bumptech/glide#1775]
I'm using the following configuration: 

```
compile 'com.squareup.okhttp3:okhttp:3.6.0' 
compile 'com.github.bumptech.glide:glide:4.0.0-SNAPSHOT'
compile 'com.github.bumptech.glide:okhttp3-integration:2.0.0-SNAPSHOT'
```

I added a mudule to set a custom timeout: 

```
public class CustomGlideModule implements GlideModule {
    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        /* Do nothing. */
    }
    @Override
    public void registerComponents(Context context, Registry registry) { 
        OkHttpClient okHttpClient = new OkHttpClient.Builder()
                .connectTimeout(Network.DEFAULT_REQUEST_TIMEOUT_SECONDS, TimeUnit.SECONDS)
                .writeTimeout(Network.DEFAULT_REQUEST_TIMEOUT_SECONDS, TimeUnit.SECONDS)
                .readTimeout(Network.DEFAULT_REQUEST_TIMEOUT_SECONDS + 1, TimeUnit.SECONDS)
                .build();
        registry.append(GlideUrl.class, InputStream.class, new OkHttpUrlLoader.Factory(okHttpClient)); 
    }
}

```
```
        <meta-data
            android:name="com.myapp.android.common.image.CustomGlideModule"
            android:value="GlideModule" />
```

And I'm keep getting the following exception when loading an image from network: 

```
03-09 13:18:07.868 W/Glide: Load failed for http://uploads01.myappdomain.com/bcce7a87.thumbnail.png with size [120x120]
                            class com.bumptech.glide.load.engine.GlideException: Failed to load resource
03-09 13:18:07.868 E/Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
03-09 13:18:07.870 E/GlideExecutor: Request threw uncaught throwable
                                    java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.List.clear()' on a null object reference
                                        at com.bumptech.glide.util.pool.FactoryPools$3.reset(FactoryPools.java:86)
                                        at com.bumptech.glide.util.pool.FactoryPools$3.reset(FactoryPools.java:83)
                                        at com.bumptech.glide.util.pool.FactoryPools$FactoryPool.release(FactoryPools.java:162)
                                        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.cleanup(MultiModelLoader.java:98)
                                        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.cleanup(MultiModelLoader.java:101)
                                        at com.bumptech.glide.load.engine.SourceGenerator.cacheData(SourceGenerator.java:87)
                                        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:45)
                                        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:275)
                                        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:245)
                                        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:220)
                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                        at java.lang.Thread.run(Thread.java:818)
                                        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)

```

**Comment by TWiStErRob** [comment]
`MultiModelLoader$MultiFetcher` code suggests that `cleanup` was called without prior `loadData`.
Further `SourceGenerator` shows that `startNext` had a `dataToCache`.
The load was also rescheduled based on line 245 of `runWrapped`.

Can you know which Glide load and what user behavior triggers this? It looks like an edge case.

**Comment by drmms** [comment]
The app is using this load: 
Glide.with(context).asBitmap().load(Uri uri).

The Context is a simple Activity.

**Comment by sjudd** [comment]
I think this is obsolete, here's now a null check on the exceptions list.
