### ISSUE TITLE
Gif not loading from url

### ISSUE THREAD

**Issue by Mahe1235** [bumptech/glide#1778]
I'm trying to a load Gif from url. But .error() is been shown. On adding a listener, I'm getting a null exception.

**Glide Version**: glide:3.7.0

**Integration libraries**: okhttp-integration:1.3.0

**Device/Android Version**: 

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```
public static void loadImage(final Activity context, ImageView imageView, String url) {
        if (context == null ) return;

        Glide.with(context)
                .load(url)
                .asGif()
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .error(R.drawable.jpeg_ft)
                .fitCenter()
                .listener(new RequestListener<String, GifDrawable>() {
                    @Override
                    public boolean onException(Exception e, String model, Target<GifDrawable> target, boolean isFirstResource) {
                        e.printStackTrace();
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(GifDrawable resource, String model, Target<GifDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                        return false;
                    }
                })
                .into(imageView);
    }
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.NullPointerException
                      at com.prosoftnet.android.idriveonline.util.Utility$3.onException(Utility.java:9844)
                      at com.prosoftnet.android.idriveonline.util.Utility$3.onException(Utility.java:9841)
                      at com.bumptech.glide.request.GenericRequest.onException(GenericRequest.java:547)
                      at com.bumptech.glide.load.engine.EngineJob.handleExceptionOnMainThread(EngineJob.java:183)
                      at com.bumptech.glide.load.engine.EngineJob.access$200(EngineJob.java:22)
                      at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:204)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:137)
                      at android.app.ActivityThread.main(ActivityThread.java:5103)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:525)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                      at dalvik.system.NativeStart.main(Native Method)
```

**Comment by TWiStErRob** [comment]
Yes that `e` param is `@Nullable`, for example if you try to load a HTML page as an image, BitmapFactory will freak out and return a `null` to Glide, in that case there's no exception.

**Comment by Mahe1235** [comment]
So how do I show a gif from an url ? Say using the following url. https://media.giphy.com/media/9fbYYzdf6BbQA/giphy.gif

**Comment by TWiStErRob** [comment]
Check out https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling for figuring out why you get null. You can also debug `DecodeJob` to see what's  wrong.

Based on your code: change cache from ALL to SOURCE, and printStackTrace to `Log.e("Glide", "failed " + model, e);`
I just remembered that if you pass a null model you may also get a null exception, the above log line will cover that case.

**Comment by Mahe1235** [comment]
Also, I forgot to add. If I don't integrate the okhttp module, only the first frame of the gif is shown

**Comment by Mahe1235** [comment]
**Stack trace / LogCat**:
```
javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x612adb58: Failure in SSL library, usually a protocol error
                                                                          error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x596676a2:0x00000000)
                                                                              at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:440)
                                                                              at com.squareup.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103)
                                                                              at com.squareup.okhttp.Connection.connect(Connection.java:143)
                                                                              at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:185)
                                                                              at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
                                                                              at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
                                                                              at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
                                                                              at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
                                                                              at com.squareup.okhttp.Call.getResponse(Call.java:273)
                                                                              at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
                                                                              at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
                                                                              at com.squareup.okhttp.Call.execute(Call.java:81)
                                                                              at com.bumptech.glide.integration.okhttp.OkHttpStreamFetcher.loadData(OkHttpStreamFetcher.java:48)
                                                                              at com.bumptech.glide.integration.okhttp.OkHttpStreamFetcher.loadData(OkHttpStreamFetcher.java:19)
                                                                              at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
                                                                              at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
                                                                              at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
                                                                              at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
                                                                              at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
                                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                              at java.lang.Thread.run(Thread.java:841)
                                                                              at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
                                                                          	Suppressed: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x6009f278: Failure in SSL library, usually a protocol error
                                                                          error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x596676a2:0x00000000)
                                                                          		... 25 more
                                                                          	Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x6009f278: Failure in SSL library, usually a protocol error
                                                                          error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x596676a2:0x00000000)
                                                                              at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
                                                                              at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:398)
                                                                              		... 24 more
                                                                           Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x612adb58: Failure in SSL library, usually a protocol error
                                                                          error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x596676a2:0x00000000)
                                                                              at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
                                                                              at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:398)
                                                                              	... 24 more
```

**Comment by TWiStErRob** [comment]
So, are you getting `onException(null, ...` or an actual image? That doesn't make sense. Are you talking about another issue now?
