### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by tuesda** [bumptech/glide#1790]
**Glide Version**: 3.7.0

**Integration libraries**: okhttp3 - 1.4.0

**Device/Android Version**: android 4.+ - 7.+

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```java
java.lang.NullPointerException: Attempt to invoke interface method 'void com.bumptech.glide.g.b.g.c(android.graphics.drawable.Drawable)' on a null object reference
       at com.bumptech.glide.request.GenericRequest.begin(GenericRequest.java:276)
       at com.bumptech.glide.manager.RequestTracker.resumeRequests(RequestTracker.java:83)
       at com.bumptech.glide.RequestManager.resumeRequests(RequestManager.java:180)
       at com.bumptech.glide.RequestManager.onStart(RequestManager.java:203)
       at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStart(ActivityFragmentLifecycle.java:50)
       at com.bumptech.glide.manager.SupportRequestManagerFragment.onStart(SupportRequestManagerFragment.java:135)
       at android.support.v4.app.Fragment.performStart(Fragment.java:2215)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:199)
       at android.app.ActivityThread.main(ActivityThread.java:5783)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:982)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:777)
```

```java
/**
     * Starts any not yet completed or failed requests.
     */
    public void resumeRequests() {
        isPaused = false;
        for (Request request : Util.getSnapshot(requests)) {
            if (!request.isComplete() && !request.isCancelled() && !request.isRunning()) {
                request.begin();
            }
        }
        pendingRequests.clear();
    }
```

I think the crash cause is use `Util.getSnapshot(requests)` in above code. Request in requests may be cleared and recycled someWhere. Because use `Util.getSnapshot(requests)`, request recycled is still in that copy ArrayList. And this cause this crash, Request#recycle() can set target in Request with null.

**Comment by TWiStErRob** [comment]
We need to be able to repro this to fix. Do you have more info?

**Comment by TWiStErRob** [comment]
For example your load and other interactions with glide (e.g. Glide.get)

**Comment by tuesda** [comment]
We find this crash occurred in devices of our customer with fabric.io. And we can not repro this issue. So we can only analyze this issue with stack trace. Please check if usage of `Util.getSnapshot(requests)` can cause this issue. tks!
