### ISSUE TITLE
NoClassDefFoundError thrown

### ISSUE THREAD

**Issue by csaba-csete-87** [bumptech/glide#1801]
**Glide Version**: 3.7.0

**Integration libraries**: none

**Device/Android Version**: Nexus 5 / 6.0

What I did observe was that simply reverting back to version 3.6.1, the error does not get thrown
        

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(this) // this is an activity
                .load("http://i.imgur.com/2Dc19mw.jpg")
                .into(imageView); // ImageView
```

**Layout XML**:
```ruby
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="@dimen/nav_header_height"
    android:background="@drawable/side_nav_bar"
    android:gravity="bottom"
    android:orientation="vertical"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin">

    <ImageView
        android:id="@+id/user_account_image"
        android:layout_width="48dp"
        android:layout_height="48dp"
        android:src="@drawable/ic_account_circle"
        android:tint="@android:color/white"/>

    <TextView
        android:id="@+id/user_account_name"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:paddingTop="@dimen/nav_header_vertical_spacing"
        android:textColor="@android:color/white"/>

    <TextView
        android:id="@+id/user_account_email"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textColor="@android:color/white"/>

</LinearLayout>
```

**Stack trace / LogCat**:
```ruby
java.lang.NoClassDefFoundError: com.bumptech.glide.manager.SupportRequestManagerFragment
at com.bumptech.glide.manager.RequestManagerRetriever.getSupportRequestManagerFragment(RequestManagerRetriever.java:178)
at com.bumptech.glide.manager.RequestManagerRetriever.supportFragmentGet(RequestManagerRetriever.java:195)
at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:104)
at com.bumptech.glide.Glide.with(Glide.java:653)
```

You can checkout the project here
**Repo**: https://github.com/csaba-csete-87/shared-shopping-list/tree/develop

**Comment by yangxiaoweihn** [comment]
I met the same problem.

**Comment by TWiStErRob** [comment]
@csaba-csete-87 tried building (`shared-shopping-list>gradlew installDebug`) but got:
> File google-services.json is missing. The Google Services Plugin cannot function without it.

Try a clean build and look around dex limit, with all these libs you may need multidex.
