### ISSUE TITLE
Glide does not showing images from backendless URL

### ISSUE THREAD

**Issue by mubtadasyed** [bumptech/glide#1804]
**Glide Version**:3.7.0

**Integration libraries**:

**Device/Android Version**:4.4.2

**Issue details / Repro steps / Use case background**: Hi, I'm working on android and using 'backendless' as mbass. I have uploaded a picture in their file storage and I'm given a public URL for image retrieving. I'm retrieving image successfully by simple 'HttpURLConnection' but when I use glide, it always stuck in 'error' instead of retrieving the image. 

here it is my URL: https://api.backendless.com/CF512434-CCA8-067C-FF92-D76481A44000/v1/files/profilePhotos/mubtada.syedprofileImage.png 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(getContext())
                        .load("https://api.backendless.com/CF512434-CCA8-067C-FF92-D76481A44000/v1/files/profilePhotos/mubtada.syedprofileImage")
                        .placeholder(R.drawable.ic_video_call_white_36dp)
                        .error(R.drawable.loginbackground)
                        .into(ImageView);
```

**Layout XML**:
```xml
<RelativeLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content">

            <ImageView
                android:id="@+id/profile_dp"
                android:layout_width="135dp"
                android:layout_height="145dp"
                android:layout_gravity="center_horizontal"
                android:contentDescription="@string/profile_image"
                android:longClickable="true"
                android:padding="@dimen/dp2"/>
                <!--android:src="@drawable/ic_add_a_photo_black_48dp" />-->

            <ProgressBar
                android:id="@+id/imageProgressBar"
                style="@android:style/Widget.ProgressBar.Small"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:visibility="invisible"
                android:layout_centerInParent="true" />
        </RelativeLayout>
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by TWiStErRob** [comment]
Check the error: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

**Comment by TWiStErRob** [comment]
You're probably using the wrong url, the String in your code doesn't have `.png` at the end, even in the browser it returns `{"code":6007,"message":"The specified resource was not found"}`.

**Comment by godfrednanaowusu** [comment]
Well, i had issues with loading images via Glide for days with no success, the app was previously working so i didnt know what had happened, it appeared that Glide wasnt loading the images because i had turned the cellular settings on my emulator to poor states, to test for a different app.
but when i turned it back to normal, Glide loaded all images efficiently.

**Comment by Dipongkar12** [comment]
W/Glide: Load failed for https://firebasestorage.googleapis.com/v0/b/mfree-9290a.appspot.com/o/placeholder.jpg?alt=media&token=45452c04-e97f-430c-9be2-2b1f31446a50 with size [80x80]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.net.SocketTimeoutException(failed to connect to firebasestorage.googleapis.com/2404:6800:4007:80a::200a (port 443) from /fec0::68bb:adbd:5e34:9bd3 (port 36718) after 2500ms)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    java.net.SocketTimeoutException(failed to connect to firebasestorage.googleapis.com/2404:6800:4007:80a::200a (port 443) from /fec0::68bb:adbd:5e34:9bd3 (port 36718) after 2500ms)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.net.SocketTimeoutException(failed to connect to firebasestorage.googleapis.com/2404:6800:4007:80a::200a (port 443) from /fec0::68bb:adbd:5e34:9bd3 (port 36718) after 2500ms)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.net.SocketTimeoutException: failed to connect to firebasestorage.googleapis.com/2404:6800:4007:80a::200a (port 443) from /fec0::68bb:adbd:5e34:9bd3 (port 36718) after 2500ms
2020-04-08 12:54:03.098 12299-12299/com.example.mfree I/Glide: Root cause (1 of 1)
    java.net.SocketTimeoutException: failed to connect to firebasestorage.googleapis.com/2404:6800:4007:80a::200a (port 443) from /fec0::68bb:adbd:5e34:9bd3 (port 36718) after 2500ms
        at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
        at libcore.io.IoBridge.connect(IoBridge.java:129)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
        at java.net.Socket.connect(Socket.java:621)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:145)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:26)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:100)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:56)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:62)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
        at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)



any solution??
