### ISSUE TITLE
set a timeout for a single request

### ISSUE THREAD

**Issue by ysemylord** [bumptech/glide#1829]
how can I set a timeout for a single request 。
version com.github.bumptech.glide:glide:3.8.0-SNAPSHOT

**Comment by TWiStErRob** [comment]
It should be as easy as changing:
```java
Glide
	.with(this)
	.load(url)
```
to
```java
Glide
	.with(this)
	.using(new StreamModelLoaderWrapper<>(new OkHttpUrlLoader(longTimeoutClient)))
	.load(new GlideUrl(url))
```
See above linked commit for more info details
 (e.g. impl of [`StreamModelLoaderWrapper](https://github.com/TWiStErRob/glide-support/blob/master/src/glide3/java/com/bumptech/glide/supportapp/github/_1829_timeout_for_one_load/StreamModelLoaderWrapper.java) which is only needed because of #1832.

The difference in LogCat between the two loads:
```
V/GLIDE: load1.onException(java.net.SocketTimeoutException: timeout, https://httpbin.org/delay/15, Target for: v7.widget.AppCompatImageView{bcf6361 V.ED..C.. ........ 0,57-1080,868 #1020007 android:id/icon1}, first)
java.net.SocketTimeoutException: timeout
     ...
     at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:76)
     at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:44)
     at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:20)

D/skia: --- SkImageDecoder::Factory returned null
V/GLIDE: load2.onException(null, https://httpbin.org/delay/15
LazyHeaders{headers={User-Agent=[StringHeaderFactory{value='Dalvik/2.1.0 (Linux; U; Android 6.0.1; SM-G900FD Build/MMB29M)'}], Accept-Encoding=[StringHeaderFactory{value='identity'}]}}, Target for: v7.widget.AppCompatImageView{3163347 V.ED..C.. ........ 0,868-1080,1680 #1020008 android:id/icon2}, first)
```
The second one fails, but that's because I'm using `httpbin`, if that was a real image on a slow server, it would've loaded.
