### ISSUE TITLE
Problem decoding into existing bitmap,useing V4

### ISSUE THREAD

**Issue by 835127729** [bumptech/glide#1843]
I use V4 to load my pic,but i found my url is unable to decode sucessfully.
And get "Problem decoding into existing bitmap" Exception.

I copy V4 code into my own project but change noting.Maybe this is something wrong with my url or the size of pic.

my code is simple:

> url = "http://interface.im.taobao.com/mobileimweb/fileupload/downloadPriFile.do?type=1&fileId=740b1b57cc3fa369227a7fe4ff362f05.jpg&suffix=jpg&width=384&height=512&mediaSize=64305&YWOriginalImage=0&YWShowOriginal=0&wangxintype=1_64305&client=ww";
Glide.with(MainActivity.this).load(url).into(imageView);

And then,I get the exception like this:
```
I/Glide: Root cause (8 of 8)
java.io.IOException: Exception decoding bitmap, outWidth: 384, outHeight: 512, outMimeType: image/jpeg, inBitmap: [197x263] ARGB_8888 (207244)
at com.example.a835127729qqcom.glidedemo.glide.load.resource.bitmap.Downsampler.newIoExceptionForInBitmapAssertion(Downsampler.java:487)
at com.example.a835127729qqcom.glidedemo.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:427)
at com.example.a835127729qqcom.glidedemo.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:244)
at com.example.a835127729qqcom.glidedemo.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:177)
at com.example.a835127729qqcom.glidedemo.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:62)
at com.example.a835127729qqcom.glidedemo.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
at com.example.a835127729qqcom.glidedemo.glide.load.resource.bitmap.BitmapDrawableDecoder.decode(BitmapDrawableDecoder.java:47)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:69)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.DecodePath.decodeResource(DecodePath.java:54)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.DecodePath.decode(DecodePath.java:45)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:58)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.LoadPath.load(LoadPath.java:44)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:447)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:440)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:426)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:380)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:352)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:136)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:92)
at com.example.a835127729qqcom.glidedemo.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:75)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:72)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:50)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:277)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:388)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:352)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:136)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:92)
at com.example.a835127729qqcom.glidedemo.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:70)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:72)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:50)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:277)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:247)
at com.example.a835127729qqcom.glidedemo.glide.load.engine.DecodeJob.run(DecodeJob.java:222)
```

**Comment by storix** [comment]
I had a similar problem. In my case Glide v4 could not load an image because of the spaces in the path.

**Comment by 835127729** [comment]
@storix I hope so,but I can not find a space in my path.  why dont you try it？[http://interface.im.taobao.com/mobileimweb/fileupload/downloadPriFile.do?type=1&fileId=740b1b57cc3fa369227a7fe4ff362f05.jpg&suffix=jpg&width=384&height=512&mediaSize=64305&YWOriginalImage=0&YWShowOriginal=0&wangxintype=1_64305&client=ww](url)

**Comment by storix** [comment]
I checked your url with Glide 3.8.0-SNAPSHOT and it has been successfully loaded. I cannot check this with Glide v4 because I deintegrated it from all my projects.

**Comment by TWiStErRob** [comment]
I tried with latest Glide v4 and it showed me the picture:
![image](https://cloud.githubusercontent.com/assets/2906988/25043605/019b4b40-2119-11e7-920b-7cef75e148d5.png)

```
04-14 12:45:24.931 6932-7739/com.bumptech.glide.supportapp.v4 D/skia: libjpeg error 105 <  Ss=0, Se=63, Ah=0, Al=0> from Incomplete image data
04-14 12:45:24.941 6932-6932/com.bumptech.glide.supportapp.v4 V/GLIDE: .onResourceReady(BitmapDrawable@8787f6e(480x640@ARGB_8888), http://interface.im.taobao.com/mobileimweb/fileupload/downloadPriFile.do?type=1&fileId=740b1b57cc3fa369227a7fe4ff362f05.jpg&suffix=jpg&width=384&height=512&mediaSize=64305&YWOriginalImage=0&YWShowOriginal=0&wangxintype=1_64305&client=ww, Target for: v7.widget.AppCompatImageView{f35f60f V.ED..... ........ 0,0-480,680 #1020006 android:id/icon}(params=-1x-1->size=480x680), REMOTE, first)
```

Note this is on API 25, on API 19 it crashes similar to yours, but you forgot to include the root cause in your stack trace:
```
          Caused by: java.lang.IllegalArgumentException: Problem decoding into existing bitmap
             at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:593)
             at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:424)
             at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:243) 
             at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:176) 
             at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:60) 
             at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:17) 
             at com.bumptech.glide.load.resource.bitmap.BitmapDrawableDecoder.decode(BitmapDrawableDecoder.java:45) 
             at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67) 
             at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52) 
             at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43) 
             at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56) 
             at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42) 
             at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:445) 
             at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:438) 
             at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:424) 
             at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:378) 
             at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:350) 
             at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:134) 
             at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91) 
             at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:73) 
             at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71) 
             at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:48) 
             at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:275) 
             at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:386) 
             at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:350) 
             at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:134) 
             at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91) 
             at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:68) 
             at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71) 
             at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:48) 
             at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:275) 
             at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:245) 
             at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:220) 
             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
             at java.lang.Thread.run(Thread.java:841) 
             at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347) 
```
Notice that the exception is coming from the Android System. The problem is made obvious by the warning on API 25. Checking with JPEGSnoop also confirms that the file ends prematurely, it's missing some bytes.

If you wrote/have control over `downloadPriFile.do` check if you flush the stream correctly or if it has a stream copy operation check if it's correct, the last bit may be missing, here's a **buggy** pseudo code for both of these:
```
OutputStream networkStream = ...;
BufferedOutputStream out = new BufferedOutputStream(networkStream);
for (some data) out.write(some data);
networkStream.close(); // this is wrong
// the end of some data may be still in memory of the buffered stream
// you need to close the outer stream (out) first, so it flushes to the underlying stream.
```
```
byte[] buffer = new byte[2048];
while(in.read(buffer) == 2048) { // == 2048 should be > 0
     out.write(buffer); // and write should be `out.write(buffer, 0, length of last batch of bytes)`
} // the last batch of bytes read to the buffer will be less than 2048
```
