### ISSUE TITLE
NotificationTarget.update fc

### ISSUE THREAD

**Issue by ucxl** [bumptech/glide#1893]
java.lang.IllegalStateException: Can't parcel a recycled bitmap
	at android.graphics.Bitmap.checkRecycled(Bitmap.java:400)
	at android.graphics.Bitmap.writeToParcel(Bitmap.java:1867)
	at android.widget.RemoteViews$BitmapCache.writeBitmapsToParcel(RemoteViews.java:1143)
	at android.widget.RemoteViews.writeToParcel(RemoteViews.java:3489)
	at android.widget.RemoteViews.clone(RemoteViews.java:2408)
	at android.app.Notification.cloneInto(Notification.java:1592)
	at android.app.Notification.clone(Notification.java:1566)
	at android.app.NotificationManager.notify(NotificationManager.java:274)
	at android.app.NotificationManager.notify(NotificationManager.java:211)
	at com.bumptech.glide.request.target.NotificationTarget.update(NotificationTarget.java:82)
	at com.bumptech.glide.request.target.NotificationTarget.onResourceReady(NotificationTarget.java:88)
	at com.bumptech.glide.request.target.NotificationTarget.onResourceReady(NotificationTarget.java:20)
	at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:525)
	at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:507)
	at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:158)
	at com.bumptech.glide.load.engine.EngineJob.access$100(EngineJob.java:22)
	at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:202)

**Comment by sjudd** [comment]
Pull requests welcome :)

**Comment by MurtadhaS** [comment]
This is not invalid
