### ISSUE TITLE
AppModuleProcessor failed

### ISSUE THREAD

**Issue by csshuai** [bumptech/glide#1906]
AppModuleProcessor failed

**Glide Version**:
4.0.0-SNAPSHOT

**Stack trace / LogCat**:
```ruby
Caused by: java.lang.IllegalArgumentException: expected type but was null
	at com.squareup.javapoet.CodeBlock$Builder.argToType(CodeBlock.java:225)
	at com.squareup.javapoet.CodeBlock$Builder.add(CodeBlock.java:176)
	at com.squareup.javapoet.TypeSpec$Builder.addJavadoc(TypeSpec.java:390)
	at com.bumptech.glide.annotation.compiler.RequestBuilderGenerator.generate(RequestBuilderGenerator.java:153)
	at com.bumptech.glide.annotation.compiler.AppModuleProcessor.maybeWriteAppModule(AppModuleProcessor.java:94)
	at com.bumptech.glide.annotation.compiler.GlideAnnotationProcessor.process(GlideAnnotationProcessor.java:125)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 40 more

```

**Comment by TWiStErRob** [comment]
Do you have any `GlideModule`s? Annotated or otherwise?

**Comment by csshuai** [comment]
I use `@GlideModule`
`@GlideModule public class Module extends AppGlideModule`

compiler with `  annotationProcessor "com.github.bumptech.glide:compiler:1.0.0-SNAPSHOT"
`

**Comment by TWiStErRob** [comment]
Something really funky must be going on, [that line on HEAD](https://github.com/bumptech/glide/blob/3761a432c0f58fd77cd9d06314a1c6c17bca35f0/annotation/compiler/src/main/java/com/bumptech/glide/annotation/compiler/RequestBuilderGenerator.java#L153) doesn't really contain anything that can be null, maybe there are some unexpected behaviors in APT I don't know yet.

**Comment by sjudd** [comment]
Try `"com.github.bumptech.glide:compiler:4.0.0-SNAPSHOT"`

**Comment by bitsydarel** [comment]
Hi, i can't find 
com.github.bumptech.glide:annotation:1.0.0-SNAPSHOT
com.github.bumptech.glide:compiler:1.0.0-SNAPSHOT

From jcenter and maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
where can i get it ?

**Comment by TWiStErRob** [comment]
That should be it, though note that Sam just said `4.0.0`, not `1.0.0` for the compiler.
https://oss.sonatype.org/content/repositories/snapshots/com/github/bumptech/glide/compiler/4.0.0-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/com/github/bumptech/glide/annotations/1.0.0-SNAPSHOT/

**Comment by TWiStErRob** [comment]
@csshuai was your problem solved by upgrading to latest?

**Comment by sjudd** [comment]
Actually it should be 4.0.0 all around. There was a bug in the way I was specifying the group id which buried the 4.0.0 version of the annotations snapshot. 

Wait for this travis build to finish and then use 4.0.0 for all the versions: https://travis-ci.org/bumptech/glide/builds/229975733

**Comment by bejibx** [comment]
For me upgrading from compiler version ```1.0.0-SNAPSHOT``` to ```4.0.0-SNAPSHOT``` fixes this issue.
