### ISSUE TITLE
How to: get original bitmap/jpg?, combine multiple bitmap/jpg?, store bitmap as jpg in SDcard?

### ISSUE THREAD

**Issue by JaydevM** [bumptech/glide#1917]
**Glide Version**: 3.7.0

**Device/Android Version**: Asus Zenfone 2, Android 5.0,  x86 processor, 4GB RAM

**Issue details / Repro steps / Use case background**: 
I hope this is right place for this.
Currently i'm using Glide just to display images because of lack of knowledge,
but i want to do more things like:
- saving large bitmaps to files,
- scaling bitmaps,
- combining multiple bitmaps in canvas to ultimately saving combined bitmap as file,
- etc.

Because of my lack of knowledge of Glide's capabilities, i'm handling large bitmaps inefficiently and getting "java.lang.OutOfMemoryError".
Currently i solved this issue by adding this `android:largeHeap="true"` in my manifest, but i know this is not right way to solve this problem.

**Activity Overview**:
User has an original jpg image.
User can select any frame from bottom bar.
Frame will be applied to original jpg image.
User can change frame anytime.
Only one frame will be applied to original jpg image.
When user clicks on "Done", original jpg image with selected frame will be stored as single output jpg on SD card.
**NOTES**
There is no fix dimension and aspect ration of original jpg image. (3072\*4096) OR (320\*320).
There is no fix dimension and aspect ration of frame. (640\*640)
Frame must be scaled to match dimension and aspect ration of original jpg image. (Aspect Ration of frame is not important.)

**Layout XML**:
It is a big ImageView and a RecyclerView at the bottom of screen. RecyclerView which will display all available frames.
See screenshot below.
I'm using two ImageView; one for original jpg image and other for frame.
User can change frame by selecting it from bottom bar, and i do not want to alter/modify original jpg image in `editedImageView` unless user clicks on "Done". That's why I've used two separate Image Views.
```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/bottom_bar"
        android:layout_width="match_parent"
        android:layout_height="100dp"
        android:layout_alignParentBottom="true"
        android:orientation="horizontal"
        app:layoutManager="android.support.v7.widget.LinearLayoutManager" />

    <ImageView
        android:id="@+id/editedImageView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@+id/bottom_bar" />
    <!--These both ImageView are overlaping eachother. editedImageView will be below frameImageView because of it's elevation-->
    <ImageView
        android:id="@+id/frameImageView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@+id/bottom_bar"
        android:elevation="2dp" />

</RelativeLayout>
```
![screenshot_2017-05-09-18-53-28](https://cloud.githubusercontent.com/assets/22527365/25853138/56f9f86e-34e9-11e7-8f05-adf25346281e.jpg)

**FrameActivity.java**:
This is working with large heap, but as mentioned earlier, gives "java.lang.OutOfMemoryError" without large heap.
I have commented what i'm doing and why.
Also I've identified places with `[OPTIMIZE THIS]` where optimization is possible.
**_Please give suggestions so that i can use this activity without large heap._**
```java
public class FrameActivity extends AppCompatActivity {

    private ImageView mFrameImageView;//At start, there is no frame selected.
    private ImageView mSelectedImageView;//Shows original jpg
    private int frameResourceID;//At start it is 0.
    private Uri mSelectedImageUri;//URI for original large jpg (3072*4096)
    private Uri outputUri;//An URI pointing to output file where edited image will be stored when "Done" is pressed.
    private Bitmap img;//[OPTIMIZE THIS] A hack created for getting actual width and height of original image file (3072*4096).

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_frame);

        mSelectedImageUri = getIntent().getData();
        outputUri = getIntent().getParcelableExtra("opUri");

        ((RecyclerView) findViewById(R.id.bottom_bar)).setAdapter(new FrameAdapter(this));
        //Nothing fancy in adapter. Just calls applyFrame(frameResourceID) when user clicks on an frame from bottom bar.

        mSelectedImageView = (ImageView) findViewById(R.id.editedImageView);
        mFrameImageView = (ImageView) findViewById(R.id.frameImageView);

        try {//[OPTIMIZE THIS] As mentioned earlier, this is done just to get original image width and height
            //Please tell if it is possible to get original dimension (not display dimension) of image from glide.
            InputStream image_stream = getContentResolver().openInputStream(mSelectedImageUri);
            img = BitmapFactory.decodeStream(image_stream);
            if (image_stream != null) {
                image_stream.close();
                //image_stream=null;
            }
        } catch (IOException e) {
            e.printStackTrace();
            finish();
        }

        Glide
                .with(this)
                .load(mSelectedImageUri)
                .diskCacheStrategy(DiskCacheStrategy.NONE)//I've used this two line with every Glide call.
                .skipMemoryCache(true)//Please tell me if removing this two line will be useful.
                .into(mSelectedImageView);
    }
    
    /* This method will be called from adapter,when user clicks on a frame from bottom bar.*/
    protected void applyFrame(int frameResourceID) {
        this.frameResourceID = frameResourceID;

        Glide
                .with(this)
                .load(frameResourceID)
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .skipMemoryCache(true)
                .bitmapTransform(new Transformation<Bitmap>() {
                    /*This is required because dimension of original jpg and dimension of frame resource do not match every-time.
                    * Hence i'm scaling frame to match with dimension of original jpg.
                    */
                    @Override
                    public Resource<Bitmap> transform(Resource<Bitmap> resource, int outWidth, int outHeight) {
                        return BitmapResource.obtain(Bitmap.createScaledBitmap(resource.get(),
                                img.getWidth(), img.getHeight(), false),
                                Glide.get(getApplicationContext()).getBitmapPool());
                    }

                    @Override
                    public String getId() {
                        return "ScaleAsMainImage";
                    }
                })
                .into(mFrameImageView);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.frame_activity_menu, menu);
        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case R.id.done_adding_frame:
                if (frameResourceID == 0) {
                    finish();
                    return super.onOptionsItemSelected(item);
                }

                //TODO:[OPTIMIZE THIS] Everything below requires optimization.
                //There will be 3 bitmaps. Original jpg(img), selected frame(frm), output(op) 
                //We already have "img" from "onCreate()"
                //We create "frm" from selected frame resource ID "frameResourceID"
                //Also note that "frm" is scaled to match dimension of "img"
                //We create blank "op" with dimension of "img"
                //We create a canvas for combining "img" and "frm"
                //We create jpg file from "op" bitmap, which is combination of "img" and "frm"
                //
                //Here we are creating 3 bitmap which are giving "java.lang.OutOfMemoryError"
                //Note we already have original jpg and scaled frame in two ImageViews: "editedImageView" and "frameImageView"
                //I want to optimize this process. Please suggest any improvement which can be done.
                Bitmap frm, op;

                frm = Bitmap.createScaledBitmap(BitmapFactory.decodeResource(getResources(), frameResourceID, null), img.getWidth(), img.getHeight(), false);

                op = Bitmap.createBitmap(img.getWidth(), img.getHeight(),
                        Bitmap.Config.RGB_565);

                Canvas comboImage = new Canvas(op);
                comboImage.drawBitmap(img, 0, 0, null);
                comboImage.drawBitmap(frm, 0, 0, null);

                try {
                    OutputStream stream = new FileOutputStream(outputUri.getPath());
                    /* Write bitmap to file using JPEG or PNG and 90% quality hint for JPEG. */
                    op.compress(Bitmap.CompressFormat.JPEG, 90, stream);
                    stream.close();
                } catch (IOException e) {
                    e.printStackTrace();
                    finish();
                    return super.onOptionsItemSelected(item);
                }

                setResult(RESULT_OK);
                finish();
                return super.onOptionsItemSelected(item);
            default:
                return super.onOptionsItemSelected(item);
        }
    }
}
```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
//In FrameActivity.java. Already shown above
Glide
        .with(this)
        .load(mSelectedImageUri)
        .diskCacheStrategy(DiskCacheStrategy.NONE)
        .skipMemoryCache(true)
        .into(mSelectedImageView);
```
```java
//In FrameActivity.java. Already shown above
Glide
        .with(this)
        .load(frameResourceID)
        .diskCacheStrategy(DiskCacheStrategy.NONE)
        .skipMemoryCache(true)
        .bitmapTransform(new Transformation<Bitmap>() {
            @Override
            public Resource<Bitmap> transform(Resource<Bitmap> resource, int outWidth, int outHeight) {
                return BitmapResource.obtain(Bitmap.createScaledBitmap(resource.get(),
                        img.getWidth(), img.getHeight(), false),
                        Glide.get(getApplicationContext()).getBitmapPool());
            }

            @Override
            public String getId() {
                return "ScaleAsMainImage";
            }
        })
        .into(mFrameImageView);
```
```java
//In FrameAdapter.java.
//(RecyclerView)bottom_bar's FrameAadapter's onBindViewHolder()
//FrameAdapter extends RecyclerView.Adapter
Glide
        .with(frameActivity)//frameActivity is instance of FrameActivity class. (FrameActivity is shown in FrameActivity.java)
        .load(frames.getResourceId(position, -1))
        .into(((CategoryViewHolder) holder).frameImage);//frameImage is ImageView
```

**Stack trace / LogCat**:
Use this for line number reference:
FrameActivity.java:111: frm = Bitmap.createScaledBitmap(BitmapFactory.decodeRe...
```ruby
E/AndroidRuntime: FATAL EXCEPTION: main
        Process: com.divine.photoeditor, PID: 1237
        java.lang.OutOfMemoryError: Failed to allocate a 50331660 byte allocation with 16777216 free bytes and 40MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:817)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:794)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:725)
        at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:601)
        at com.divine.photoeditor.FrameActivity.onOptionsItemSelected(FrameActivity.java:111)
        at android.app.Activity.onMenuItemSelected(Activity.java:2924)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:408)
        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
        at android.support.v7.app.AppCompatDelegateImplV9.onMenuItemSelected(AppCompatDelegateImplV9.java:679)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:959)
        at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
        at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:154)
        at android.view.View.performClick(View.java:4756)
        at android.view.View$PerformClick.run(View.java:19761)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5264)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
```

**Comment by JaydevM** [comment]
@TWiStErRob Hi, can you look into this issue OR tell me if i need to rephrase it OR this is not right place for this type of question?

**Comment by AndroidDeveloperLB** [comment]
Is there a way to get just the size of the original image on the way by Glide, and letting it do all the things normally?
