### ISSUE TITLE
Custom model loader - handling of null stream

### ISSUE THREAD

**Issue by MFlisar** [bumptech/glide#1934]
**Glide Version**:

    compile 'com.github.bumptech.glide:glide:3.7.0'

**Integration libraries**:

    compile 'com.github.bumptech.glide:okhttp3-integration:1.4.0@aar'

**Issue details / Repro steps / Use case background**: 

Here's my custom contact image loader I use:

	public class GlideContactsImageLoader implements StreamModelLoader<Integer> {
		private static volatile boolean photoSizeInitialized = false;
		private static int photoSize = 96;
		private static int thumbnailSize = 96;
		private static boolean full;

		private Context context;
		private ModelLoader<Integer,InputStream> modelLoader;
		public GlideContactsImageLoader(Context context, boolean full) {
			this.context = context;
			this.full = full;
			if(!photoSizeInitialized)
				initContactsPhotoSize(context);
		}

		@Override
		public ContactDataFetcher getResourceFetcher(Integer contactId, int width, int height) {
			Uri contactUri = Uri.withAppendedPath(ContactsContract.Contacts.CONTENT_URI, "" + contactId);
			boolean thumbnail = !full && width <= thumbnailSize;
			if (full)
				photoSizeInitialized = true;
			return new ContactDataFetcher(contactUri,thumbnail,context);
		}

		public synchronized static void initContactsPhotoSize(final Context context) {
			if(photoSizeInitialized)
				return;

			int phothoSize = 96; //Default;
			final Uri uri = ContactsContract.DisplayPhoto.CONTENT_MAX_DIMENSIONS_URI;
			final String[] projection = new String[] { ContactsContract.DisplayPhoto.DISPLAY_MAX_DIM, ContactsContract.DisplayPhoto.THUMBNAIL_MAX_DIM };
			final Cursor c = context.getContentResolver().query(uri, projection, null, null, null);
			try {
				c.moveToFirst();
				photoSize = c.getInt(0);
				thumbnailSize = c.getInt(1);
				photoSizeInitialized = true;
				L.d("Contacts photo size initialized. Photo = %d Thumbnails = %d", phothoSize, thumbnailSize);
			} finally {
				c.close();
			}
		}

		static class ContactDataFetcher implements DataFetcher<InputStream> {
			private boolean cancelled;
			private Uri contactUri;
			private Context context;
			private boolean thumbnail;

			public ContactDataFetcher(Uri contactUri, boolean thumbnail, Context context) {
				this.contactUri = contactUri;
				this.thumbnail = thumbnail;
				this.context = context;
			}

			@Override
			public InputStream loadData(Priority priority) throws Exception {
				L.v("load contact photo for %s. Thumbnail = %b", contactUri, thumbnail);

				InputStream stream = null;
				if(contactUri!=null && !cancelled) {
					if(thumbnail)
						stream = ContactsContract.Contacts.openContactPhotoInputStream(context.getContentResolver(), contactUri);
					else
						stream = ContactsContract.Contacts.openContactPhotoInputStream(context.getContentResolver(), contactUri,true);
				}
				return stream;
			}

			@Override
			public void cleanup() {

			}

			@Override
			public String getId() {
				return contactUri.toString()+"_thumbnail"+thumbnail;
			}

			@Override
			public void cancel() {
				cancelled = true;
			}
		}
	}

And this is what I do:

    	BitmapTypeRequest<Integer> builder = Glide.with(MainApp.get())
			.using(new GlideContactsImageLoader(MainApp.get(), true))
			.load(contact.getPhoneId())
			.asBitmap();

	return builder
			.diskCacheStrategy(DiskCacheStrategy.NONE)
			.skipMemoryCache(true)
			.into(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
			.get();

And this is the result on one of my users devices (a few hundred devices work already without problems so it's working in general):

	load contact photo for content://com.android.contacts/contacts/365. Thumbnail = false
	[a:82 a]: java.util.concurrent.ExecutionException
		at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:189)
		at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:100)
		at com.my.app.glide.GlideUtil.getBitmap(GlideUtil.java:137)

=> GlideUtil.java:137 is the `return builder` line from above...

Any ideas what the root cause is? The log shows that the contact uri is NOT null, what else could cause such an exception?

**Comment by MFlisar** [comment]
I now know the root cause, the cause is that the contact does not have an image. So the stream is null.

What is the correct way to handle this? Let my `GlideContactsImageLoader`  throw a custom exception, catch it like follwoing:

    Bitmap bitmap = null;
            try
            {
                bitmap = GlideUtil.getBitmap(contact, false);
            }
            catch (ExecutionException e)
            {
                if (e.getCause() instanceof NoImageException)
                    return false;
                throw e;
            }

Or can I somehow change my class to return null instead of throwing an exception?
