### ISSUE TITLE
Canvas: trying to use a recycled bitmap android.graphics.Bitmap

### ISSUE THREAD

**Issue by ProsperousBloom** [bumptech/glide#1968]
I am using Glide 3.7.0 and getting this error at very random times:

`E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.embargoapp.app, PID: 1569
                                                 java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@e2351f2
                                                     at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1271)
                                                     at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:257)
                                                     at android.graphics.Canvas.drawBitmap(Canvas.java:1415)
                                                     at com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable.draw(GlideBitmapDrawable.java:101)
                                                     at android.widget.ImageView.onDraw(ImageView.java:1298)
                                                     at android.view.View.draw(View.java:17185)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                     at android.view.View.draw(View.java:16951)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                     at android.view.View.draw(View.java:16951)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                     at android.view.View.draw(View.java:17188)
                                                     at android.widget.ScrollView.draw(ScrollView.java:1737)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                     at android.view.View.draw(View.java:16951)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                     at android.view.View.draw(View.java:17188)
                                                     at android.support.v4.view.ViewPager.draw(ViewPager.java:2447)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                     at android.view.View.draw(View.java:16951)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                     at android.view.View.draw(View.java:16951)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                     at android.view.View.draw(View.java:17188)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                     at android.view.View.draw(View.java:16951)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                     at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1195)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                     at android.view.View.draw(View.java:16951)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                     at android.view.View.draw(View.java:16951)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                     at android.view.View.draw(View.java:16951)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                     at android.view.View.draw(View.java:17188)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                     at android.view.View.draw(View.java:16951)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                     at android.view.View.draw(View.java:16951)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                     at android.view.View.draw(View.java:17188)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                     at android.view.View.draw(View.java:16951)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                     at android.view.View.draw(View.java:17188)
                                                     at com.android.internal.policy.DecorView.draw(DecorView.java:754)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)`

I am using Glide at multiple locations in my code, but I believe this error is connected to a transitioning routine that I have. Basically there are several images, with one being shown at a time, which fades into the next one every 5 secs. The following code is called every 5 secs (and could be called at random points as well):

        final ImageView imageViewFadeIn = (ImageView) viewItem.findViewById(R.id.viewpager_image_fadein);
        final ImageView imageViewFadeOut = (ImageView) viewItem.findViewById(R.id.viewpager_image_fadeout);

        if (imageViewFadeOut.getAnimation() != null) {
            return;
        }

        Glide.with(fragment.getContext())
            .load(link)
            .centerCrop()
            .placeholder(R.drawable.venue_placeholder)
            .dontAnimate()
            .listener(new RequestListener<String, GlideDrawable>() {
                @Override
                public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                    return false;
                }

                @Override
                public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                    try {
                        int transitionTime = 1000;
                        if (imageViewFadeOut.getDrawable().getConstantState().equals(App.getContext().getResources().getDrawable(R.drawable.venue_placeholder).getConstantState())) {
                            transitionTime = 200;
                        }

                        imageViewFadeIn.setImageDrawable(resource);
                        float sat = active ? 1.0f : 0.0f;
                        ColorMatrix matrix = new ColorMatrix();
                        matrix.setSaturation(sat);
                        ColorMatrixColorFilter filter = new ColorMatrixColorFilter(matrix);
                        imageViewFadeIn.setColorFilter(filter);

                        Animation animation = new AlphaAnimation(1.00f, 0.00f);
                        animation.setAnimationListener(new Animation.AnimationListener() {
                            @Override
                            public void onAnimationStart(Animation arg0) {
                            }

                            @Override
                            public void onAnimationRepeat(Animation arg0) {
                            }

                            @Override
                            public void onAnimationEnd(Animation arg0) {
                                imageViewFadeOut.setImageDrawable(imageViewFadeIn.getDrawable());
                            }
                        });
                        animation.setDuration(transitionTime);
                        imageViewFadeOut.startAnimation(animation);
                    }
                    catch (Exception e) {
                        return true;
                    }
                    return true;
                }
            })
            .into(imageViewFadeIn);`

Any idea what causes the crash? And if not there, where else would I need to look to find out exactly what's causing the crash?

Thank you!

**Comment by sjudd** [comment]
If you start a new load into imageViewFadeIn, or call ``clear()`` on it, you need to stop the animation. If you try to draw the Bitmap after the corresponding View or Target is cleared, you will (randomly) see this kind of exception.

**Comment by ProsperousBloom** [comment]
Hi Sam, thanks for the quick answer. 

However, isn't that taken care of with the following being called right at the beginning of the function?
```
if (imageViewFadeOut.getAnimation() != null) {
        return;
    }
```

So it should never even get to the Glide part if an animation is attached to the image, no? An animation is only added to imageViewFadeOut. Basically imageFadeIn is just displayed behind the imageFadeOut with the latter having an animation fading the alpha to zero. 

Maybe the issue is in the following?

```
  @Override
  public void onAnimationEnd(Animation arg0) {
      imageViewFadeOut.setImageDrawable(imageViewFadeIn.getDrawable());
  }
```

This method is using imageViewFadeIn, which was declared final before. So could it be that it doesn't exist anymore by the time the function stops?  Maybe it gets recycled somehow? (not that I'm doing anything like this intentionally). Would this result in such an error message? If that's the case I would have probably expected another error

**Comment by sjudd** [comment]
Do you cancel this animation when your activity is destroyed? It looks like you're passing the Activity Context into Glide, so Glide will clear out your request at the appropriate point in the lifecycle. Once the request is cleared, the Bitmap may be recycled (often it's just returned to the BitmapPool, but sometimes the BitmapPool is full, so the Bitmap is recycled instead).

If the animation is still running, it may then try to draw your recycled Bitmap.

If this is possible the safest thing to do is to make sure that you cancel your animation whenever your load is cleared. The [``onLoadCleared()``][2] method is available in [``Target``][1] so that you can handle this kind of event.

You can subclass [``DrawableImageViewTarget``][3] directly if you'd like:

```java
Glide.with(fragment)
   ... // your options here
  .into(new DrawableImageViewTarget(imageViewFadeOut) {
    @Override
    public void onLoadCleared(Drawable placeholder) {
      imageViewFadeOut.clearAnimation();
    }
  });
```

[1]: http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/request/target/Target.html
[2]: http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/request/target/Target.html#onLoadCleared-android.graphics.drawable.Drawable-
[3]: http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/request/target/DrawableImageViewTarget.html
