### ISSUE TITLE
Can't load svg from res , just work with Link ?

### ISSUE THREAD

**Issue by chihung93** [bumptech/glide#1980]
```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.github.bumptech.glide:glide:4.0.0-RC0'
    compile 'com.caverock:androidsvg:1.2.1'
    testCompile 'junit:junit:4.12'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0-RC0'
}


import android.content.ContentResolver;
import android.graphics.drawable.PictureDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.ImageView;

import com.bumptech.glide.RequestBuilder;

import static com.bumptech.glide.load.resource.drawable.DrawableTransitionOptions.withCrossFade;

public class Main2Activity extends AppCompatActivity {
    private ImageView imageViewRes;
    private ImageView imageViewNet;
    private RequestBuilder<PictureDrawable> requestBuilder;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);
        imageViewRes = (ImageView) findViewById(R.id.svg_image_view1);
        imageViewNet = (ImageView) findViewById(R.id.svg_image_view2);
        requestBuilder = GlideApp.with(this)
                .as(PictureDrawable.class)
                .placeholder(R.drawable.ic_img_default)
                .error(R.drawable.ic_img_default)
                .transition(withCrossFade())
                .listener(new SvgSoftwareLayerSetter());
        loadRes();
        loadNet();
    }
    private void loadRes() {
        Uri uri = Uri.parse(ContentResolver.SCHEME_ANDROID_RESOURCE + "://" + getPackageName() + "/"
                + R.raw.ic_alert_gray);
        requestBuilder.load(uri).into(imageViewRes);
    }

    private void loadNet() {
    }
}



05-31 15:21:45.682 20693-21326/cn.hung.com.testsvg E/GlideExecutor: Request threw uncaught throwable
                                                                    java.lang.NullPointerException: Attempt to read from field 'com.caverock.androidsvg.SVG$Length com.caverock.androidsvg.SVG$Svg.width' on a null object reference
                                                                        at com.caverock.androidsvg.SVG.renderToPicture(SVG.java:265)
                                                                        at cn.hung.com.testsvg.SvgDrawableTranscoder.transcode(SvgDrawableTranscoder.java:19)
                                                                        at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:45)
                                                                        at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
                                                                        at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
                                                                        at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:445)
                                                                        at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:438)
                                                                        at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:424)
                                                                        at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:378)
                                                                        at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:350)
                                                                        at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
                                                                        at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:48)
                                                                        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
                                                                        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:275)
                                                                        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:245)
                                                                        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:220)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                        at java.lang.Thread.run(Thread.java:818)
                                                                        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)
05-31 15:21:49.700 20693-20693/cn.hung.com.testsvg W/Glide: Load failed for android.resource://cn.hung.com.testsvg/2131099648 with size [1080x1680]
                                                            class com.bumptech.glide.load.engine.GlideException: Failed to load resource
05-31 15:21:49.700 20693-20693/cn.hung.com.testsvg E/Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
05-31 15:21:49.701 20693-20693/cn.hung.com.testsvg I/Choreographer: Skipped 240 frames!  The application may be doing too much work on its main thread.
05-31 15:21:54.756 20693-20693/cn.hung.com.testsvg I/Choreographer: Skipped 303 frames!  The application may be doing too much work on its main thread.

```
My phone: ASUS Zenfone 3 - OS 6.0.1
Here my images: 
I can't load SVG from Resources but use this link "http://www.clker.com/cliparts/u/Z/2/b/a/6/android-toy-h.svg" its work.

```
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="24dp"
        android:height="24dp"
        android:viewportWidth="24.0"
        android:viewportHeight="24.0">
    <path
        android:pathData="M12.498,0h-1.002C10.947,0 10.5,0.449 10.5,1.004v0.641c-3.977,0.715 -6.99,4.182 -6.99,8.359v6.043L0,18.887V20.5h24v-1.613l-3.49,-2.84v-6.043c0,-4.188 -3.027,-7.656 -7.01,-8.363V1.004C13.5,0.449 13.053,0 12.498,0L12.498,0z"
        android:fillColor="#989898"/>
    <path
        android:pathData="M12,24c1.381,0 2.498,-1.119 2.498,-2.5H9.496C9.498,22.881 10.619,24 12,24z"
        android:fillColor="#989898"/>
</vector>
```
<img width="271" alt="screen shot 2017-05-31 at 15 26 05" src="https://cloud.githubusercontent.com/assets/5199109/26622742/8c32959e-4615-11e7-8f02-353bc9632c63.png">

**Comment by TWiStErRob** [comment]
Look up the difference between SVG and Android vector drawables.

**Comment by chihung93** [comment]
Sorry about stupid question , 
Glide 3.8 can support vector drawable or not ?
