### ISSUE TITLE
In Android 7.1.1,7.1.2, glide 4.0.0-RC0 load a local video as a bitmap failed

### ISSUE THREAD

**Issue by Haoxiqiang** [bumptech/glide#1992]
**Glide Version**:com.github.bumptech.glide:glide:4.0.0-RC0

**Integration libraries**:none

**Device/Android Version**:fails on  Nexus 5x 7.1.1,Nexus 5x 7.1.2, and some others 7.1.x rom.works fine on others 6.x and 5.x rom

**Issue details / Repro steps / Use case background**: load a local video as bitmap

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
        //glide 3.7.0 will works well
        Glide.with(getApplicationContext())
                .load(uri)
                .asBitmap()
                .diskCacheStrategy(DiskCacheStrategy.RESULT)
                .thumbnail(1.0f)
                .sizeMultiplier(0.8f)
                .dontAnimate()
                .into(iv);
        //Glide 4.0.0 will not
        Glide.with(getApplicationContext())
                .asBitmap()
                .load(uri)
       .apply(RequestOptions.diskCacheStrategyOf(DiskCacheStrategy.RESOURCE).downsample(DownsampleStrategy.NONE))
                .into(iv);
```

**Stack trace / LogCat**:
```ruby
I/art: Late-enabling -Xcheck:jni
I/art: Debugger is no longer active
I/art: Starting a blocking GC Instrumentation
W/System: ClassLoader referenced unknown path: /data/app/com.vesta.glidetest-1/lib/arm64
I/InstantRun: starting instant run server: is main process
V/InstantRun: Starting server socket listening for package com.vesta.glidetest on android.net.LocalSocketAddress@5536217
V/InstantRun: Started server for package com.vesta.glidetest
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList,  would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
I/Adreno: QUALCOMM build                   : 6818200, Idb2b4cb785
          Build Date                       : 11/18/16
          OpenGL ES Shader Compiler Version: XE031.09.00.04
          Local Branch                     : N25
          Remote Branch                    : 
          Remote Branch                    : 
          Reconstruct Branch               : 
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
W/Glide: Load failed for file:/storage/emulated/0/Pictures/snow_20175220019.mp4 with size [-2147483648x-2147483648]
         class com.bumptech.glide.load.engine.GlideException: Failed to load resource
           Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, LOCAL
             Cause (1 of 1): class java.io.FileNotFoundException: /storage/emulated/0/Pictures/snow_20175220019.mp4 (No such file or directory)
           Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.os.ParcelFileDescriptor, LOCAL
             Cause (1 of 1): class java.io.FileNotFoundException: No such file or directory
E/Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
I/Glide: Root cause (1 of 2)
         java.io.FileNotFoundException: /storage/emulated/0/Pictures/snow_20175220019.mp4 (No such file or directory)
             at java.io.FileInputStream.open(Native Method)
             at java.io.FileInputStream.<init>(FileInputStream.java:146)
             at java.io.FileInputStream.<init>(FileInputStream.java:99)
             at android.content.ContentResolver.openInputStream(ContentResolver.java:702)
             at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResourceFromUri(StreamLocalUriFetcher.java:79)
             at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResource(StreamLocalUriFetcher.java:55)
             at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResource(StreamLocalUriFetcher.java:16)
             at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:40)
             at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
             at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:275)
             at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:245)
             at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:220)
             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
             at java.lang.Thread.run(Thread.java:761)
             at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)
I/Glide: Root cause (2 of 2)
         java.io.FileNotFoundException: No such file or directory
             at android.os.Parcel.openFileDescriptor(Native Method)
             at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:283)
             at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:200)
             at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:979)
             at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:907)
             at com.bumptech.glide.load.data.FileDescriptorLocalUriFetcher.loadResource(FileDescriptorLocalUriFetcher.java:21)
             at com.bumptech.glide.load.data.FileDescriptorLocalUriFetcher.loadResource(FileDescriptorLocalUriFetcher.java:13)
             at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:40)
             at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
             at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:275)
             at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherFailed(DecodeJob.java:365)
             at com.bumptech.glide.load.engine.SourceGenerator.onLoadFailed(SourceGenerator.java:118)
             at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:45)
             at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
             at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:275)
             at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:245)
             at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:220)
             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
             at java.lang.Thread.run(Thread.java:761)
             at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)
```

**Comment by sjudd** [comment]
``java.io.FileNotFoundException`` means that ``/storage/emulated/0/Pictures/snow_20175220019.mp4`` doesn't exist. It's not possible to load a thumbnail for a non-existent video.

Double check that your video exists, the path is correct and that the video has a non-zero size.

**Comment by TWiStErRob** [comment]
Is it possible this is related to https://developer.android.com/about/versions/nougat/android-7.0-changes.html#sharing-files ? (look at the failing/passing device list in OP)

**Comment by Haoxiqiang** [comment]
I see.But Glide 3.7.0 works well under the same conditions.This is where I am confused.

**Comment by Haoxiqiang** [comment]
@TWiStErRob Do you have received some similar issues?

**Comment by TWiStErRob** [comment]
I don't remember getting any, but looking at this again, I may see a potential problem.
You're loading the Uri as
`file:/storage/emulated/0/Pictures/snow_20175220019.mp4`,
while it should be
`file:///storage/emulated/0/Pictures/snow_20175220019.mp4`
(see [Uri.fromFile](https://developer.android.com/reference/android/net/Uri.html#fromFile(java.io.File)))

Didn't double-check now, but as far as I remember Glide v3 had some exceptional path if the `Uri` had the file scheme. Looking at your exception trace, now `StreamLocalUriFetcher` goes through a content resolver, which may behave differently (i.e. not tolerate `file:/`).

**Comment by Haoxiqiang** [comment]
@TWiStErRob 
I've been debugging for a long time.It's maybe a system problem.I found a big difference between the `Uri.fromFile` and `Uri.Builder`.
I will be debugging on more equipment, thank you for your help.
