### ISSUE TITLE
Redirect url java.io.IOException: Request failed with code: 406

### ISSUE THREAD

**Issue by Leonid-Kiev** [bumptech/glide#1999]
I am trying to load an image through the resolver (redirect to dynamic url).
Started from using Gide out-of-the box.
Ended up creating custom module in order to increase timeout:

public class CustomGlideModule extends OkHttpGlideModule {
    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        // stub
    }

    @Override
    public void registerComponents(Context context, Glide glide) {
        final OkHttpClient.Builder builder = new OkHttpClient.Builder();
        builder.readTimeout(30, TimeUnit.SECONDS);
        builder.writeTimeout(30, TimeUnit.SECONDS);
        builder.connectTimeout(30, TimeUnit.SECONDS);
        glide.register(GlideUrl.class, InputStream.class, new OkHttpUrlLoader.Factory(builder.build()));
    }
}

meta-data is added to the manifest.

Loading into an image view target

```
 Glide.with(imageView.getContext())
                .load(url)
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .dontAnimate()
                .into(new GlideDrawableImageViewTarget(imageView) {
                    @Override
                    public void onResourceReady(GlideDrawable resource, GlideAnimation<? super GlideDrawable> animation) {
                        super.onResourceReady(resource, animation);
                        Log.d(TAG, "onResourceReady: ");
                    }
                    @Override
                    public void onLoadFailed(Exception e, Drawable errorDrawable) {
                        super.onLoadFailed(e, errorDrawable);
                        Log.d(TAG, "onLoadFailed: ");
                    }
                });

```
Image which I am trying to load:
 https://spalneo.mlox.eu/media/cache/resolve/profile_1440/media/users/58/58ff069ad5d28.png 
And here loading fails with the java.io.IOException: Request failed with code: 406.

Using 3.7.0 version

Also adding the logs:
D/GLIDE: onException(java.io.IOException: Request failed with code: 406, https://spalneo.mlox.eu/media/cache/resolve/profile_1440/media/users/58/58ff069ad5d28.png, Target for: android.support.v7.widget.AppCompatImageView{a963fe3 V.ED..... ........ 0,0-1440,875 #7f0d0108 app:id/iv_avatar_background}, true)
         java.io.IOException: Request failed with code: 406
             at com.bumptech.glide.integration.okhttp3.OkHttpStreamFetcher.loadData(OkHttpStreamFetcher.java:46)
             at com.bumptech.glide.integration.okhttp3.OkHttpStreamFetcher.loadData(OkHttpStreamFetcher.java:19)
             at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:70)
             at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:53)
             at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
             at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
             at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
             at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
             at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
             at java.lang.Thread.run(Thread.java:761)
             at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)

**Comment by sjudd** [comment]
A 406 error is a server error, from google: http://www.hostingflow.com/http-error-406-not-acceptable/. 

Unfortunately I don't think there's anything we can do to help with that. If you do re-open, please make sure you fill out the rest of the issue template.
