### ISSUE TITLE
AppWidgetTarget.update causes crash: Can't parcel a recycled bitmap

### ISSUE THREAD

**Issue by EsteveAguilera** [bumptech/glide#2004]
**Glide Version**:

    Glide version: 3.8.0
    Glide-transformations version: 2.0.2

**Integration libraries**:

    Glide okhttp-integration version: 1.4.0@aar

**Device/Android Version**:

    Devices: Samsung, Condor, HTC...
    Android version: 4.1.2 to 4.3

**Issue details / Repro steps / Use case background**: 

We've recently migrated our project from Picasso to Glide. Everything is working perfect except a widget.

We have not been able to reproduce the issue, but fabric is telling us we're getting some crashes updating the widget:

AppWidgetTarget.java line 128
com.bumptech.glide.request.target.AppWidgetTarget.update

Fatal Exception: java.lang.IllegalStateException: Can't parcel a recycled bitmap

I've searched and found nothing...

Any advice?

Thanks in advance

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

Our GlideModule:

```java
public class GlideModule implements GlideModule {
    @Override public void applyOptions(Context context, GlideBuilder builder) {
        builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_8888);
    }

    @Override public void registerComponents(Context context, Glide glide) {
        OkHttpClient client = HttpUtils.getOkHttpClient();
        client.setConnectTimeout(15, TimeUnit.SECONDS);
        client.setReadTimeout(15, TimeUnit.SECONDS);
        OkHttpUrlLoader.Factory factory = new OkHttpUrlLoader.Factory(client);
        glide.register(GlideUrl.class, InputStream.class, factory);
    }
}
```

The Glide load lines

```java
    private void updateAvatarWithLocalPicture(Context context, RemoteViews remoteViews, int viewId, int widgetId) {
        File file = OpenPictureMethodDialogListener.getAvatarFile();
        if (file.exists()) {
            updateAvatar(context, remoteViews, viewId, widgetId, OpenPictureMethodDialogListener.getAvatarUriForPicasso());
        } else {
            updateAvatarWithEmptyAvatar(context, remoteViews, viewId, widgetId);
        }
    }

    private void updateAvatar(Context context, RemoteViews remoteViews, int viewId, int widgetId, String pictureUrl) {
        AppWidgetTarget appWidgetTarget = new AppWidgetTarget(context, remoteViews, viewId, widgetId);
        Glide.with(context)
                .load(pictureUrl)
                .asBitmap()
                .centerCrop()
                .override(pictureSize, pictureSize)
                .transform(new AvatarTransformation(context, strokeWidth))
                .into(appWidgetTarget);
    }

    private void updateAvatarWithEmptyAvatar(Context context, RemoteViews remoteViews, int viewId, int widgetId) {
        AppWidgetTarget appWidgetTarget = new AppWidgetTarget(context, remoteViews, viewId, widgetId);
        Glide.with(context)
                .load(R.drawable.emptyavatar)
                .asBitmap()
                .centerCrop()
                .override(pictureSize, pictureSize)
                .transform(new AvatarTransformation(context, strokeWidth))
                .into(appWidgetTarget);
    }
```

**Layout XML**:
```xml
    <LinearLayout
        android:layout_width="@dimen/main_title_row_width"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <FrameLayout
            android:id="@+id/fl_avatar"
            android:layout_width="@dimen/main_title_row_width"
            android:layout_height="@dimen/main_title_row_width"
            android:layout_gravity="center"
            android:background="@color/main_avatar_background"
            android:padding="@dimen/padding_medium">

            <ImageView
                android:id="@+id/iv_avatar"
                style="@style/avatar_circular" />
        </FrameLayout>
...
```

**Stack trace / LogCat**:
```ruby
Fatal Exception: java.lang.IllegalStateException: Can't parcel a recycled bitmap
       at android.graphics.Bitmap.checkRecycled(Bitmap.java:272)
       at android.graphics.Bitmap.writeToParcel(Bitmap.java:1324)
       at android.widget.RemoteViews$BitmapCache.writeBitmapsToParcel(RemoteViews.java:905)
       at android.widget.RemoteViews.writeToParcel(RemoteViews.java:2457)
       at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.updateAppWidgetIds(IAppWidgetService.java:649)
       at android.appwidget.AppWidgetManager.updateAppWidget(AppWidgetManager.java:393)
       at com.bumptech.glide.request.target.AppWidgetTarget.update(AppWidgetTarget.java:128)
       at com.bumptech.glide.request.target.AppWidgetTarget.onResourceReady(AppWidgetTarget.java:135)
       at com.bumptech.glide.request.target.AppWidgetTarget.onResourceReady(AppWidgetTarget.java:21)
       at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:525)
       at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:507)
       at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:158)
       at com.bumptech.glide.load.engine.EngineJob.access$100(EngineJob.java:22)
       at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:202)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5317)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by sjudd** [comment]
That means that the Target was cleared without removing the Bitmap from the remote view. Either you're recycling the Target manually, or you're loading the Bitmap using a RequestManager from an Activity or Fragment, which is automatically clearing the Target when the corresponding Activity or Fragment is destroyed.

Make sure you're not clearing the Target manually and use the application context when loading into a remote view:

```java
Glide.with(context.getApplicationContext())
  .load(url)
  .into(appWidgetTarget);
```
