### ISSUE TITLE
Failed to load frame, as bitmap, from video at particular time in Glide v4

### ISSUE THREAD

**Issue by vaibhavvishal** [bumptech/glide#2007]
App crashed while trying to load a frame at particular time in the video as bitmap

Android version : 24
Glide version : 4.0.0-RC0

Code : 

`  String url = <path of video present in app internal storage>

RequestOptions options = new RequestOptions();
options.decode(VideoBitmapDecoder.class);
options.frame(6000);

File f = new File(file);
ParcelFileDescriptor pfd = null;
try {
	pfd = ParcelFileDescriptor.open(f, ParcelFileDescriptor.MODE_READ_ONLY);
} catch (FileNotFoundException e) {
	e.printStackTrace();
}

Glide.with(MainActivity.this).asBitmap().load(pfd).apply(options)
		.listener(new RequestListener<Bitmap>() {
			@Override
			public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Bitmap> target,
										boolean isFirstResource) {
				Log.d(TAG, "onLoadFailed");
				return false;
			}

			@Override
			public boolean onResourceReady(Bitmap resource, Object model, Target<Bitmap> target,
										   DataSource dataSource, boolean isFirstResource) {
				Log.d(TAG, "onResourceReady");
				return false;
			}
		}).into(mImageView);`

Error : 

Request threw uncaught throwable
com.bumptech.glide.Registry$NoModelLoaderAvailableException: Failed to find any ModelLoaders for model: {ParcelFileDescriptor: java.io.FileDescriptor@6834d86}
    at com.bumptech.glide.Registry.getModelLoaders(Registry.java:227)
    at com.bumptech.glide.load.engine.DecodeHelper.getLoadData(DecodeHelper.java:179)
    at com.bumptech.glide.load.engine.DecodeHelper.getCacheKeys(DecodeHelper.java:197)
    at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:41)
    at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:275)
    at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:242)
    at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:220)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:762)
    at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)

**Comment by sjudd** [comment]
Just pass the File object in to the ``load()`` don't open the file descriptor first. Opening the file descriptor isn't necessary and it looks like you're doing it on the main thread, which will cause jank.

**Comment by vaibhavvishal** [comment]
I had passed the time in Millis instead of Micros.
Thanks. It's working after changing time in microseconds
