### ISSUE TITLE
java.lang.IllegalStateException: Cannot pool recycled bitmap

### ISSUE THREAD

**Issue by tarasokunev** [bumptech/glide#2012]
Heelo, I use ver: 4.0.0-RC0

And have some problems...when Activity calls onDestroy I have the problem:

`java.lang.IllegalStateException: Cannot pool recycled bitmap
                                                                                           at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4247)
                                                                                           at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4265)
                                                                                           at android.app.ActivityThread.-wrap6(ActivityThread.java)
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1565)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6247)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                                                                                        Caused by: java.lang.IllegalStateException: Cannot pool recycled bitmap
                                                                                           at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.put(LruBitmapPool.java:86)
                                                                                           at com.bumptech.glide.load.resource.bitmap.LazyBitmapDrawableResource.recycle(LazyBitmapDrawableResource.java:57)
                                                                                           at com.bumptech.glide.load.engine.EngineResource.recycle(EngineResource.java:63)
                                                                                           at com.bumptech.glide.load.engine.ResourceRecycler.recycle(ResourceRecycler.java:28)
                                                                                           at com.bumptech.glide.load.engine.Engine.onResourceReleased(Engine.java:319)
                                                                                           at com.bumptech.glide.load.engine.EngineResource.release(EngineResource.java:101)
                                                                                           at com.bumptech.glide.load.engine.Engine.release(Engine.java:275)
                                                                                           at com.bumptech.glide.request.SingleRequest.releaseResource(SingleRequest.java:287)
                                                                                           at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:266)
                                                                                           at com.bumptech.glide.manager.RequestTracker.clearRemoveAndRecycle(RequestTracker.java:59)
                                                                                           at com.bumptech.glide.RequestManager.untrack(RequestManager.java:437)
                                                                                           at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:424)
                                                                                           at com.bumptech.glide.RequestManager.clear(RequestManager.java:412)
                                                                                           at com.bumptech.glide.RequestManager.onDestroy(RequestManager.java:272)
                                                                                           at com.bumptech.glide.manager.ActivityFragmentLifecycle.onDestroy(ActivityFragmentLifecycle.java:64)
                                                                                           at com.bumptech.glide.manager.SupportRequestManagerFragment.onDestroy(SupportRequestManagerFragment.java:187)
                                                                                           at android.support.v4.app.Fragment.performDestroy(Fragment.java:2434)
                                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1442)
                                                                                           at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                                           at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2951)
                                                                                           at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:271)
                                                                                           at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:390)
                                                                                           at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)
                                                                                           at com.tarasproduction.currencyconverter.MainActivity.onDestroy(MainActivity.java:1211)
                                                                                           at android.app.Activity.performDestroy(Activity.java:6959)
                                                                                           at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
                                                                                           at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4234)
                                                                                           at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4265) 
                                                                                           at android.app.ActivityThread.-wrap6(ActivityThread.java) 
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1565) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                           at android.os.Looper.loop(Looper.java:154) 
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6247) 
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872) 
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) `

And it is my code(same error with Bitmap):
`Glide.with(getContext())
 .asDrawable()
                .load(requestGraph)
                .apply(new RequestOptions().diskCacheStrategy(DiskCacheStrategy.DATA).skipMemoryCache(true))
                .into(new SimpleTarget<Drawable>() {
                    @Override
                    public void onResourceReady(final Drawable graph, Transition<? super Drawable> transition) {
showGraph(((BitmapDrawable)graph).getBitmap());
                        }              
                });
        }`

**Comment by anthony3444** [comment]
Hi,

(Android 8.0 ; Glide 4.3.1)

I have the same problem when onDestroy() is called:

```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {com.xxx/com.xxx.ui.photo.PhotoActivity}: java.lang.IllegalStateException: Cannot pool recycled bitmap
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4993)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5012)
       at android.app.ActivityThread.-wrap6(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1944)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7358)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)
Caused by java.lang.IllegalStateException: Cannot pool recycled bitmap
       at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.put(LruBitmapPool.java:86)
       at com.bumptech.glide.load.resource.bitmap.BitmapResource.recycle(BitmapResource.java:57)
       at com.bumptech.glide.load.engine.EngineResource.recycle(EngineResource.java:63)
       at com.bumptech.glide.load.engine.ResourceRecycler.recycle(ResourceRecycler.java:28)
       at com.bumptech.glide.load.engine.Engine.onResourceReleased(Engine.java:336)
       at com.bumptech.glide.load.engine.EngineResource.release(EngineResource.java:101)
       at com.bumptech.glide.load.engine.Engine.release(Engine.java:292)
       at com.bumptech.glide.request.SingleRequest.releaseResource(SingleRequest.java:337)
       at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:316)
       at com.bumptech.glide.manager.RequestTracker.clearRemoveAndRecycle(RequestTracker.java:62)
       at com.bumptech.glide.RequestManager.untrack(RequestManager.java:462)
       at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:449)
       at com.bumptech.glide.RequestManager.clear(RequestManager.java:437)
       at com.bumptech.glide.RequestManager.onDestroy(RequestManager.java:290)
       at com.bumptech.glide.manager.ActivityFragmentLifecycle.onDestroy(ActivityFragmentLifecycle.java:64)
       at com.bumptech.glide.manager.SupportRequestManagerFragment.onDestroy(SupportRequestManagerFragment.java:187)
       at android.support.v4.app.Fragment.performDestroy(Fragment.java:2516)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1557)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
       at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3218)
       at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:262)
       at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:362)
       at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)
       at com.xxx.ui.BaseActivity.onDestroy(BaseActivity.java:307)
       at com.xxx.ui.photo.PhotoActivity.onDestroy(PhotoActivity.java:164)
       at android.app.Activity.performDestroy(Activity.java:7572)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1253)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4980)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5012)
       at android.app.ActivityThread.-wrap6(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1944)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7358)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)
```

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/resourcereuse.html#common-errors

**Comment by anthony3444** [comment]
@tarasokunev : did you resolve your problem? I have the same error like you.
Thank you very much!

**Comment by supperyan** [comment]
@anthony3444 did you resolve your problem? I have the same error like you.
Thank you very much!

**Comment by ravikant-dexati** [comment]
This issue was due to loading very large image in glide in my case.
Using override(int w,int h) to restrict it to device width and height fixed the issue.
`DisplayMetrics metrics=getResources().getDisplayMetrics();

                                Bitmap bitmap = GlideApp.
                                        with(CategoryImageViewerScreen.this).
                                        asBitmap().
                                        override(metrics.widthPixels,metrics.heightPixels).
                                        load(downloadUrl).
                                        submit().
                                        get();`
Hope it helps

**Comment by muslimmuda15** [comment]
I got same issue, but I put 
`Glide.get(this).clearMemory()`
Before `onDestroy()`
So, I just remove it.
