### ISSUE TITLE
Glide4.0 load image error,help,help

### ISSUE THREAD

**Issue by cuihp** [bumptech/glide#2043]
Picture of the URL can be used in the browser can be displayed properly, but can not be displayed in the application, in urgent need of help, picture address: `http://bucketcuihp.oss-cn-hongkong.aliyuncs.com/wKgBDVlDPIuAPflbAAo_XkWE53U004.jpg`

### use

```
 RequestOptions options = new RequestOptions()
                .format(DecodeFormat.PREFER_RGB_565)
                .placeholder(android.R.color.black)
                .error(R.mipmap.img_error)
                .override(1280, 800);
        Glide.with(this)
                .load(proxyUrl)
                .apply(options)
                .into(imageView);
```

### error log
```
Glide: Load failed for file:///mnt/sdcard/Android/data/com.xxx.xxx/cache/img-cache/b3942aaf03c05b3b4608ee879b7987aa.jpg with size [1280x800]
                                                       class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                         Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, LOCAL
                                                           Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
                                                           Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
                                                             Cause (1 of 1): class java.io.IOException: Exception decoding bitmap, outWidth: 1728, outHeight: 1080, outMimeType: image/jpeg, inBitmap: [1728x1080] RGB_565
                                                           Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
                                                             Cause (1 of 1): class java.io.IOException: Exception decoding bitmap, outWidth: 1728, outHeight: 1080, outMimeType: image/jpeg, inBitmap: [1728x1080] RGB_565
                                                         Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, LOCAL
                                                           Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
                                                           Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
06-16 10:34:39.546 9802-9802/com.vistyle.adha I/Glide: Root cause (1 of 2)
                                                       java.io.IOException: Exception decoding bitmap, outWidth: 1728, outHeight: 1080, outMimeType: image/jpeg, inBitmap: [1728x1080] RGB_565
                                                           at com.bumptech.glide.load.resource.bitmap.Downsampler.newIoExceptionForInBitmapAssertion(Downsampler.java:482)
                                                           at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:426)
                                                           at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:243)
                                                           at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:176)
                                                           at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:60)
                                                           at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:17)
                                                           at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67)
                                                           at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52)
                                                           at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43)
                                                           at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
                                                           at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
                                                           at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:445)
                                                           at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:438)
                                                           at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:424)
                                                           at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:378)
                                                           at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:350)
                                                           at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
                                                           at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:125)
                                                           at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:48)
                                                           at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:93)
                                                           at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
                                                           at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:275)
                                                           at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:245)
                                                           at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:220)
                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                           at java.lang.Thread.run(Thread.java:856)
                                                           at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)
                                                        Caused by: java.lang.IllegalArgumentException: Problem decoding into existing bitmap
                                                           at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:539)
                                                           at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:424)
                                                           at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:243)?
                                                           at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:176)?
                                                           at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:60)?
                                                           at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:17)?
                                                           at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67)?
                                                           at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52)?
                                                           at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43)?
                                                           at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)?
                                                           at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)?
                                                           at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:445)?
                                                           at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:438)?
                                                           at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:424)?
                                                           at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:378)?
                                                           at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:350)?
                                                           at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)?
                                                           at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:125)?
                                                           at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:48)?
                                                           at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:93)?
                                                           at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)?
                                                           at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:275)?
                                                           at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:245)?
                                                           at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:220)?
                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)?
                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)?
                                                           at java.lang.Thread.run(Thread.java:856)?
                                                           at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)?
```

**Comment by RainliFu** [comment]
I have the same error
