### ISSUE TITLE
loading InputStream resource throws error

### ISSUE THREAD

**Issue by igorperciuleac** [bumptech/glide#2060]
**Glide Version**: 4.0.0-RC1

**Integration libraries**: No

**Device/Android Version**: Android 7.0

**Issue details / Repro steps / Use case background**: 

GlideApp.with(context).load(contentStream).into(imageView)

**Stack trace / LogCat**:
```ruby
06-21 23:32:21.243 10351-10351/com.pinbox.android.dev E/Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
06-21 23:32:21.243 10351-10634/com.pinbox.android.dev E/GlideExecutor: Request threw uncaught throwable
                                                                       com.bumptech.glide.Registry$NoModelLoaderAvailableException: Failed to find any ModelLoaders for model: com.amazonaws.services.s3.model.S3ObjectInputStream@62905e5
                                                                           at com.bumptech.glide.Registry.getModelLoaders(Registry.java:227)
                                                                           at com.bumptech.glide.load.engine.DecodeHelper.getLoadData(DecodeHelper.java:179)
                                                                           at com.bumptech.glide.load.engine.DecodeHelper.getCacheKeys(DecodeHelper.java:197)
                                                                           at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:41)
                                                                           at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:282)
                                                                           at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:249)
                                                                           at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:222)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                           at java.lang.Thread.run(Thread.java:761)
                                                                           at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)

```
I use AmazonS3Client for get content as input stream of my image.
Finally i have S3ObjectInputStream which extends InputStream
When i try to load my ImputStream to Glide I get error "Failed to find any ModelLoaders"

I guess that i need to implement ModelLoader with S3ObjectInputStream, but this is a bit strange.
Glide doesn't have default InputStream Model Loader ?

**Comment by sjudd** [comment]
For posterity, no Glide does not have a ModelLoader that handles InputStreams as models. 

It's inefficient (and potentially dangerous in terms of leaks) to pass InputStreams around. Instead you should write a ModelLoader that takes whatever data you need to pass to AmazonS3Client and that returns a S3ObjectInputStream. Then Glide's built in InputStream ResourceDecoders will work as expected.

**Comment by nvmnghia** [comment]
@igorperciuleac Did you find any solution to this? I also want to load content from `InputStream`.
