### ISSUE TITLE
Canvas: trying to use a recycled bitmap android.graphics.Bitmap

### ISSUE THREAD

**Issue by baole** [bumptech/glide#2066]
**Glide Version**: 3.7.0

**Integration libraries**: default

**Device/Android Version**: Android 4.x-7.x

**Issue details / Repro steps / Use case background**: Glide does not raise exception to caller

**Stack trace / LogCat**:

This is crashes from Fabric on a production app: http://crashes.to/s/8b223050d7c

It's probably app-level issue. However Glide does not raise exception to the app and I couldn't figure out which part of my app causes this issue. I expect Glide raise an exception so that the app can handle the crash.

Sample stack trace:

```
Fatal Exception: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@473e24d8
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1084)
       at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:844)
       at com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable.draw(Unknown Source:101)
       at android.widget.ImageView.onDraw(ImageView.java:1037)
       at android.view.View.draw(View.java:14490)
       at android.view.View.getDisplayList(View.java:13387)
       at android.view.View.getDisplayList(View.java:13429)
       at android.view.View.draw(View.java:14207)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14493)
       at android.support.v4.view.ViewPager.draw(Unknown Source:2443)
       at android.view.View.getDisplayList(View.java:13387)
       at android.view.View.getDisplayList(View.java:13429)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13325)
       at android.view.View.getDisplayList(View.java:13429)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13325)
       at android.view.View.getDisplayList(View.java:13429)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13325)
       at android.view.View.getDisplayList(View.java:13429)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13325)
       at android.view.View.getDisplayList(View.java:13429)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13325)
       at android.view.View.getDisplayList(View.java:13429)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13325)
       at android.view.View.getDisplayList(View.java:13429)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13325)
       at android.view.View.getDisplayList(View.java:13429)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13325)
       at android.view.View.getDisplayList(View.java:13429)
       at android.view.View.draw(View.java:14207)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14493)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.widget.ScrollView.draw(ScrollView.java:1603)
       at android.view.View.getDisplayList(View.java:13387)
       at android.view.View.getDisplayList(View.java:13429)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13325)
       at android.view.View.getDisplayList(View.java:13429)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13325)
       at android.view.View.getDisplayList(View.java:13429)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13325)
       at android.view.View.getDisplayList(View.java:13429)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13325)
       at android.view.View.getDisplayList(View.java:13429)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13325)
       at android.view.View.getDisplayList(View.java:13429)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13325)
       at android.view.View.getDisplayList(View.java:13429)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13325)
       at android.view.View.getDisplayList(View.java:13429)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13325)
       at android.view.View.getDisplayList(View.java:13429)
       at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1577)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1451)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2377)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2249)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1879)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5603)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5095)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by P-Zenker** [comment]
I've got the same issue inside a BaseAdapter for a ListView

**Comment by Jeyhey** [comment]
I have the same issue with `CursorAdapter `and `com.github.bumptech.glide:glide:4.1.1` in my Android app.

**Comment by MasterScrat** [comment]
Same problem, happens sometimes (rarely) in a simple Activity loading an image into an ImageView.

`compile 'com.github.bumptech.glide:glide:4.0.0'`

**Comment by JeetSingh4** [comment]
I am also facing the same crash on BaseAdapter. I am using glide 4.3.1.

```java
GlideApp.with(mActivity)
                        .asBitmap()
                        .placeholder(R.drawable.ic_loading)
                        .listener(new RequestListener<Bitmap>() {
                            @Override
                            public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Bitmap> target, boolean isFirstResource) {
                                return false;
                            }

                            @Override
                            public boolean onResourceReady(Bitmap resource, Object model, Target<Bitmap> target, DataSource dataSource, boolean isFirstResource) {
                                if (resource != null) {
                                    retailer.adapterData.bitmap = resource;
                                    notifyDataSetChanged();
                                }
                                return false;
                            }
                        })
                        .dontAnimate()
                        .priority(Priority.HIGH)
                        .load(retailer.getFSCategoryIcon()).into(viewHolder.imageView);
```

**Comment by sjudd** [comment]
@P-Zenker and @JeetSingh4 you both need to remove your references to the Bitmap when onLoadCleared is called. Typically that means implementing ``onLoadCleared`` in ``Target`` so that you can  null out any references to the ``Bitmap``.

**Comment by JeetSingh4** [comment]
Can you provide a snippet implementing onLoadCleared in Target for better understanding?

**Comment by sjudd** [comment]
See one of Glide's targets, ImageViewTarget might be a reasonable example:

https://github.com/bumptech/glide/blob/589597481028abf68a90526316dbdb846c1465f4/library/src/main/java/com/bumptech/glide/request/target/ImageViewTarget.java#L83-L88

**Comment by trr-amsiq** [comment]
Seeing the same issue. Looks like it happens after activity has been paused

**Comment by zhengzun** [comment]
when leave the activity, then back to activity. sometimes app is crashed. the stack trace just the same
