### ISSUE TITLE
Failed to remove target from managers error when scrolling after configuration change

### ISSUE THREAD

**Issue by foxware00** [bumptech/glide#2092]
**Glide Version**: 4.0.0-RC1

**Integration libraries**: okhttp3, recyclerview

**Device/Android Version**: Fails on One plus 3t, and Nexus 6p

**Issue details / Repro steps / Use case background**: Have a long list of items, scroll fast, when you rotate the screen (setRetainInstance(true)) the fragment stays in position. as soon as you then start to scroll this crash happens

**Stack trace / LogCat**:
```ruby 
java.lang.IllegalStateException: Failed to remove target from managers
       at com.bumptech.glide.Glide.removeFromManagers(Glide.java:625)
       at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:426)
       at com.bumptech.glide.RequestManager.clear(RequestManager.java:412)
       at com.bumptech.glide.RequestManager.clear(RequestManager.java:397)
       at xxx.loadImage(ChatAdapter.java:162)
       at xxx.onBindViewHolder(ChatAdapter.java:156)
       at xxx.onBindViewHolder(ChatAdapter.java:111)
       at xxx.onBindViewHolder(ChatAdapter.java:49)
       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6507)
       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5450)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5716)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5555)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5551)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2211)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1538)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1498)
       at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1312)
       at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1057)
       at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4836)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:886)
       at android.view.Choreographer.doCallbacks(Choreographer.java:698)
       at android.view.Choreographer.doFrame(Choreographer.java:630)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:872)
       at android.os.Handler.handleCallback(Handler.java:769)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by sjudd** [comment]
What Activity or Fragment are you passing in to ``Glide.with()``?

**Comment by foxware00** [comment]
`android.support.v4.app.Fragment`

**Comment by sjudd** [comment]
Duplicate of #2262
