### ISSUE TITLE
build apk in less than android 4.4(19) sysetem, happened java.lang.VerifyError: com/bumptech/glide/manager/RequestManagerRetriever carsh when run

### ISSUE THREAD

**Issue by SimplySu** [bumptech/glide#2101]
**Glide Version**: 3.8.0

**Integration libraries**: okhttp3.6.0

**Device/Android Version**: android sdk 18 (less than 19)

**Issue details / Repro steps / Use case background**: 

it was little crazy about this problem :
1.  it will crash when I build my app with **sdk-18** level system build : **it carsh device 18, but 19 or high level devices shows ok**
2. good run when I build my app with **sdk-19 or high level**：**shows ok in device 18 ,19 and high level**
above the two system build method can build the apk sucess, only happend when run the apk

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with... // normal use
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="... // normal use
```

**Stack trace / LogCat**:
```java
crash when app start and also other place use glide to load pictures , the logs are the same

01-02 08:00:32.716 E/AndroidRuntime( 3052): FATAL EXCEPTION: main
01-02 08:00:32.716 E/AndroidRuntime( 3052): java.lang.VerifyError: com/bumptech/glide/manager/RequestManagerRetriever
01-02 08:00:32.716 E/AndroidRuntime( 3052):     at com.bumptech.glide.Glide.with(Glide.java:656)
01-02 08:00:32.716 E/AndroidRuntime( 3052):     at com.xxx.xxx.MainApplication.onTrimMemory(MainApplication.java:176)
01-02 08:00:32.716 E/AndroidRuntime( 3052):     at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:4157)
01-02 08:00:32.716 E/AndroidRuntime( 3052):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
01-02 08:00:32.716 E/AndroidRuntime( 3052):     at android.os.Handler.dispatchMessage(Handler.java:99)
01-02 08:00:32.716 E/AndroidRuntime( 3052):     at android.os.Looper.loop(Looper.java:137)
01-02 08:00:32.716 E/AndroidRuntime( 3052):     at android.app.ActivityThread.main(ActivityThread.java:5103)
01-02 08:00:32.716 E/AndroidRuntime( 3052):     at java.lang.reflect.Method.invokeNative(Native Method)
01-02 08:00:32.716 E/AndroidRuntime( 3052):     at java.lang.reflect.Method.invoke(Method.java:525)
01-02 08:00:32.716 E/AndroidRuntime( 3052):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:773)
01-02 08:00:32.716 E/AndroidRuntime( 3052):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:589)
01-02 08:00:32.716 E/AndroidRuntime( 3052):     at dalvik.system.NativeStart.main(Native Method)

```

@sjudd @TWiStErRob , has any tips for this problem , thx so much !

**Comment by SimplySu** [comment]
check problem is the 4.3 system build apk not compatible with glide ,close it!
@sjudd  @TWiStErRob ，thx so much.
