### ISSUE TITLE
Sharing image from Glide Cache to Social Media

### ISSUE THREAD

**Issue by giftonian** [bumptech/glide#2116]
**Glide Version 3.5.2**
@TWiStErRob 
Is there a simple way to share currently loaded image (in ImageView) using share intent? I am using `ShareTask` described in #459 , but failed to get desired results. My latest error (a part of error message) is following: 
```
java.lang.RuntimeException: Unable to get provider android.support.v4.content.FileProvider:
java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
 at android.app.ActivityThread.installProvider(ActivityThread.java:5383)
 at android.app.ActivityThread.installContentProviders(ActivityThread.java:4975)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4915)
```

It's already discussed in #459 , but I couldn't get it.

**Comment by adisiji** [comment]
Don't forget to add meta-data in your provider tag in manifest
```xml
<provider
    android:name="android.support.v4.content.FileProvider"
    android:authorities="com.mydomain.fileprovider"
    android:exported="false"
    android:grantUriPermissions="true">
    **<meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/file_paths" />**
</provider>
```
More: [Read here](https://developer.android.com/reference/android/support/v4/content/FileProvider.html)

**Comment by TWiStErRob** [comment]
Thanks @adisiji, sorry @giftonian there are times when I can't catch up with Glide issues.

**Comment by idedalusse** [comment]
Hi, i need help please 
I am under Android and I try to integrate the function of capturing a photo for a profile,it works when I choose a photo from the gallery but when I try to take a picture from the camera it does not run the application,go back to the previous menu here is the error message.
there is my error message/
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.company_name.nidhal, PID: 14052
    java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.bumptech.glide.provider
        at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:606)
        at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
        at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
        at com.company_name.nidhal.activity.inscriptionActivity.dispatchTakePictureIntent(inscriptionActivity.java:233)
        at com.company_name.nidhal.activity.inscriptionActivity.access$000(inscriptionActivity.java:55)
        at com.company_name.nidhal.activity.inscriptionActivity$2.onPermissionsChecked(inscriptionActivity.java:297)
        at com.karumi.dexter.DexterInstance$1.run(Unknown Source)
        at com.karumi.dexter.MainThread.execute(Unknown Source)
        at com.karumi.dexter.DexterInstance.checkMultiplePermissions(Unknown Source)
        at com.karumi.dexter.DexterInstance.checkPermissions(Unknown Source)
        at com.karumi.dexter.Dexter.check(Unknown Source)
        at com.company_name.nidhal.activity.inscriptionActivity.requestStoragePermission(inscriptionActivity.java:314)
        at com.company_name.nidhal.activity.inscriptionActivity.lambda$selectImage$2$inscriptionActivity(inscriptionActivity.java:208)
        at com.company_name.nidhal.activity.-$$Lambda$inscriptionActivity$HdbkXPKYHZW7s-cLAiVtg3_g0t8.onClick(lambda)
        at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1068)
        at android.widget.AdapterView.performItemClick(AdapterView.java:310)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1233)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3279)
        at android.widget.AbsListView$3.run(AbsListView.java:4235)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:210)
        at android.app.ActivityThread.main(ActivityThread.java:5839)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
