### ISSUE TITLE
downloadOnly in backgroud thread ExecutionException 

### ISSUE THREAD

**Issue by yangjiantao** [bumptech/glide#2117]
**Glide Version**: 3.7.0

**Device/Android Version**: android 7.0

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
// this code is execute on new Thread (Thread[RxNewThreadScheduler-1,5,main])
FutureTarget<File> future = Glide.with(appContext)
                                .load(ImageUtil.getInstance(context).checkUrl(splashEntity.imageUrl, DeviceUtil.getScreenWidth(appContext), DeviceUtil.getScreenHeight(appContext)))
                                .downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL);
                        File cacheFile = future.get(); //throw exception on this line

```
**Stack trace / LogCat**:
```ruby

07-06 16:52:50.405 9931-10008/com.medlinker.sdk.usermodule W/System.err: java.util.concurrent.ExecutionException
07-06 16:52:50.405 9931-10008/com.medlinker.sdk.usermodule W/System.err:     at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:189)
07-06 16:52:50.405 9931-10008/com.medlinker.sdk.usermodule W/System.err:     at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:100)
07-06 16:52:50.405 9931-10008/com.medlinker.sdk.usermodule W/System.err:     at com.medlinker.sdk.usermodule.data.sync.CommonDataUtil$6.accept(CommonDataUtil.java:249)
```

**Comment by swabbass** [comment]
for me i see this trace and im facing the same issue with your condition (loading in bg) ->

`Request threw uncaught throwable
                                                              com.bumptech.glide.Registry$NoResultEncoderAvailableException: Failed to find result encoder for resource class: class java.io.File
                                                                  at com.bumptech.glide.load.engine.DecodeJob$DecodeCallback.onResourceDecoded(DecodeJob.java:549)
                                                                  at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:44)
                                                                  at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
                                                                  at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:489)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:461)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:447)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:401)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:370)
                                                                  at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91)
                                                                  at com.bumptech.glide.load.model.UnitModelLoader$UnitFetcher.loadData(UnitModelLoader.java:39)
                                                                  at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:293)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:260)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                  at java.lang.Thread.run(Thread.java:764)
                                                                  at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(Glid`
