### ISSUE TITLE
Crash when app widget loading images

### ISSUE THREAD

**Issue by dxinl** [bumptech/glide#2121]
**Glide Version**:
glide-full-4.0.0-RC1

**Integration libraries**:

**Device/Android Version**:
Nexus 6/Android 7.1.1

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
RequestOptions options = new RequestOptions()
                .centerCrop()
                .override(thumbnailWidth, thumbnailHeight);
return Glide.with(context).asBitmap().load(realUri).apply(options).submit().get();

/** then in RemoteViewsFactory */
views.setImageViewBitmap(R.id.iv_item_widget_image, bitmap);
```

**Stack trace / LogCat**:
```ruby
java.lang.SecurityException: ConnectivityService: Neither user 10126 nor current process has android.permission.ACCESS_NETWORK_STATE.
                                                                        at android.os.Parcel.readException(Parcel.java:1684)
                                                                        at android.os.Parcel.readException(Parcel.java:1637)
                                                                        at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:1170)
                                                                        at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:745)
                                                                        at com.bumptech.glide.manager.DefaultConnectivityMonitor.isConnected(DefaultConnectivityMonitor.java:61)
                                                                        at com.bumptech.glide.manager.DefaultConnectivityMonitor.register(DefaultConnectivityMonitor.java:42)
                                                                        at com.bumptech.glide.manager.DefaultConnectivityMonitor.onStart(DefaultConnectivityMonitor.java:67)
                                                                        at com.bumptech.glide.manager.ApplicationLifecycle.addListener(ApplicationLifecycle.java:13)
                                                                        at com.bumptech.glide.RequestManager.<init>(RequestManager.java:101)
                                                                        at com.bumptech.glide.RequestManager.<init>(RequestManager.java:71)
                                                                        at com.bumptech.glide.manager.RequestManagerRetriever$1.build(RequestManagerRetriever.java:402)
                                                                        at com.bumptech.glide.manager.RequestManagerRetriever.getApplicationManager(RequestManagerRetriever.java:96)
                                                                        at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:117)
                                                                        at com.bumptech.glide.Glide.with(Glide.java:540)
                                                                        at com.dxinl.utils.BitmapUtils.loadThumbnailForWidget(BitmapUtils.java:55)
                                                                        at com.dxinl.widget.NoteViewsFactory.getImageViews(NoteViewsFactory.java:127)
                                                                        at com.dxinl.widget.NoteViewsFactory.getViewAt(NoteViewsFactory.java:68)
                                                                        at android.widget.RemoteViewsService$RemoteViewsFactoryAdapter.getViewAt(RemoteViewsService.java:164)
                                                                        at com.android.internal.widget.IRemoteViewsFactory$Stub.onTransact(IRemoteViewsFactory.java:85)
                                                                        at android.os.Binder.execTransact(Binder.java:565)
```

By the way, **I do not request ACCESS_NETWORK_STATE permission in my Manifest.** If I request that permission, the crashing will not happen. But I use Glide to load just local images, so I don't want to request that permission.

**Comment by sjudd** [comment]
If you don't want to monitor connectivity status (totally fine), you can use [``setConnectivityMonitorFactory()``][1] in a ``GlideModule`` and set a factory that just returns an empty listener. 

For more information on configuring Glide, see [Glide's docs][2].

[1]: http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/GlideBuilder.html#setConnectivityMonitorFactory-com.bumptech.glide.manager.ConnectivityMonitorFactory-
[2]: http://bumptech.github.io/glide/doc/configuration.html#application-options

**Comment by dxinl** [comment]
@sjudd Thanks very much for your reply. 

But I am still confused. There is code which call ```Context#checkCallingOrSelfPermission(String)``` to check permission ```ACCESS_NETWORK_STATE``` in ```DefaultConnectivityMonitorFactory#build(Context, ConnectivityListener)```.

The method ```Context#checkCallingOrSelfPermission(String)``` 
> Determine whether the calling process of an IPC or you have been granted a particular permission.

In my case, calling process of an IPC has ```ACCESS_NETWORK_STATE``` permission but not my app. So, crash happen when getting network state later.

I guess calling ```Context#context.checkCallingOrSelfPermission(String)``` is incorrect. Is it?
