### ISSUE TITLE
Issue implementing a custom decoder in 4.0.0-RC1

### ISSUE THREAD

**Issue by jpmcosta** [bumptech/glide#2128]
**Glide Version**: 4.0.0-RC1

**Integration libraries**: -

**Device/Android Version**: 5.1.1 (22)

**Issue details / Repro steps / Use case background**: 

I'm trying to implement a custom `ResourceDecoder` but in my use case, I sometimes get the exception below.

I'm not sure how should I implement the decoder to make sure recycled bitmaps are not reused.

**Stack trace / LogCat**:
```
E/GlideExecutor: Request threw uncaught throwable
    java.lang.IllegalStateException: Cannot pool recycled bitmap
    at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.put(LruBitmapPool.java:86)
    at com.bumptech.glide.load.resource.bitmap.BitmapResource.recycle(BitmapResource.java:57)
    at com.bumptech.glide.load.engine.DecodeJob$DecodeCallback.onResourceDecoded(DecodeJob.java:499)
    at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:44)
    at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
    at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
    at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:457)
    at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:450)
    at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:436)
    at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:390)
    at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:359)
    at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
    at com.jpmcosta.test.glidetestproject.glide.ApplicationIconDataFetcher.loadData(ApplicationIconDataFetcher.kt:10)
    at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
    at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:282)
    at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:252)
    at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:222)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
    at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)
```

**Sample app repository**:

I created a simple test project to replicate the issue: https://github.com/jpmcosta/GlideTestProject/tree/76d9485fd5b00f9320b400aa0ca0285864be7917

The test code is located in `MainActivity`, in the method `testGlide()`.
The decoder code is in package `com.jpmcosta.test.glidetestproject.glide`.

**Comment by jpmcosta** [comment]
When decoding, I needed to provide a mutable copy of the icon's bitmap. That was **not** being ensured by using `Bitmap.createBitmap(bitmap)`.

**Fix**:
Now uses `Bitmap.copy()`, instead. See: https://github.com/jpmcosta/GlideTestProject/commit/b242d09967ff48f57cd81a7e97e13710a33a7197

**Conclusion**:
This was not an issue with Glide, my decoder implementation was not correct.
