### ISSUE TITLE
glide dowload image sometimes faild.  Request failed 503, glide:3.7.0

### ISSUE THREAD

**Issue by lhjandroid** [bumptech/glide#2136]
glide:3.7.0
in my activity it have a Edittext when i input some words and close softinput then use glide dowload an image.and use okhttp libs with it.
`ImageLoader.display(this, poster_img_url, -1, -1, new ImageLoader.OnLoadImageListener<Bitmap>() {
                    @Override
                    public void onStart() {
                        LogUtil.i(TAG,"downloadImage onStart");
                    }

                    @Override
                    public void onLoadCompleted(final Bitmap resource, GlideAnimation glideAnimation) {
                        LogUtil.i(TAG,"downloadImage onLoadCompleted");
                        if (resource != null) {
                            LogUtil.i(TAG,"downloadImage onLoadCompleted resource != null");
                            new Thread() {
                                @Override
                                public void run() {
                                    BitmapUtil util = new BitmapUtil();
                                    final byte[] thubmData = util.bitmap2Bytes(resource, WXMediaMessage.THUMB_LENGTH_LIMIT - 100);
                                    final Bitmap thumb = BitmapFactory.decodeByteArray(thubmData,0,thubmData.length);
                                    runOnUiThread(new Runnable() {
                                        @Override
                                        public void run() {
                                            hideProgressDialog(true);
                                            ThirdPartShareManager.getInstance(GiveRedpacktActivity.this).doShare(shareType,ThirdPartShareManager.IMediaType.t_image_image,thumb,resource,shareInfo);
                                        }
                                    });
                                }
                            }.start();
                        } else {
                            LogUtil.i(TAG,"downloadImage onLoadCompleted resource == null");
                            hideProgressDialog(true);
                            UIUtil.toast(getResources().getString(R.string.net_work_error));
                        }
                    }

                    @Override
                    public void onLoadFailed(Exception e, Drawable errorDrawable) {
                        LogUtil.i(TAG,"downloadImage onLoadFailed");
                        LogUtil.e(TAG,e);
                        hideProgressDialog(true);
                        UIUtil.toast(getResources().getString(R.string.net_work_error));
                    }
                });
            } catch (Exception e) {
                e.printStackTrace();
                LogUtil.i(TAG,"downloadImage catch");
                LogUtil.e(TAG,e);
                hideProgressDialog(true);
                UIUtil.toast(getResources().getString(R.string.net_work_error));
            }`

sometimes it dowload fail in onLoadFailed(Exception e, Drawable errorDrawable) .and the exception is
`java.io.IOException: Request failed 503: 
                                                           at com.bumptech.glide.load.a.f.a(SourceFile`:90)
                                                           at com.bumptech.glide.load.a.f.b(SourceFile`:44)
                                                           at com.bumptech.glide.load.a.f.a(SourceFile`:20)
                                                           at com.bumptech.glide.load.model.e$a.b(SourceFile`:70)
                                                           at com.bumptech.glide.load.model.e$a.a(SourceFile`:53)
                                                           at com.bumptech.glide.load.engine.a.e(SourceFile`:170)
                                                           at com.bumptech.glide.load.engine.a.c(SourceFile`:128)
                                                           at com.bumptech.glide.load.engine.EngineRunnable.f(SourceFile`:122)
                                                           at com.bumptech.glide.load.engine.EngineRunnable.d(SourceFile`:101)
                                                           at com.bumptech.glide.load.engine.EngineRunnable.run(SourceFile`:58)
                                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                           at java.lang.Thread.run(Thread.java:818)
                                                           at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$a$1.run(SourceFile`:118)`
 it show in less phones like opp.
first i guess when show softinputpan let the activity on pause and glide stop to dowload the image.but from lagcat it not. in this cause when dowload fail and i change my app to background then let it to foreground the glide will dowload the image again and can be dowload success.what is wrong?how can i resovle it?thanks

**Comment by sjudd** [comment]
It looks like an error with your backend: https://httpstatuses.com/503. 

Glide will attempt to retry failed requests at certain points (connectivity changes, lifecycle events). If the retry succeeds, it may mean the error is flaky. 

Unfortunately there's nothing we can do if we're given a 503.
