### ISSUE TITLE
Glide fails to load multiple images with same cache key

### ISSUE THREAD

**Issue by NirpE** [bumptech/glide#2176]
When trying to load same images at the same time I am receiving following exception. Use case is to display list results and those can contain same images. The cache key is image url bytes:

`@Override
    public void updateDiskCacheKey(MessageDigest messageDigest) {
        messageDigest.update(getImageUrl().getBytes());
}`

` java.lang.IllegalStateException: Had two simultaneous puts for: b4967e4deebfb22bfasdfasdfasdfsadf087ac49849898498f664e8d6
                                                                                    at com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper.put(DiskLruCacheWrapper.java:108)
                                                                                    at com.bumptech.glide.load.engine.SourceGenerator.cacheData(SourceGenerator.java:78)
                                                                                    at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:45)
                                                                                    at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:282)
                                                                                    at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:252)
                                                                                    at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:222)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                    at java.lang.Thread.run(Thread.java:761)
                                                                                    at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)`

**Glide Version**: 4.0.0-RC1

**Comment by tmm1** [comment]
I am experiencing this same issue. I guess two parts of my UI are trying to display the same image?

```
11-04 10:13:09.261  7509  7509 W Glide   : class com.bumptech.glide.load.engine.GlideException: Failed to load resource
11-04 10:13:09.261  7509  7509 W Glide   : There was 1 root cause:
11-04 10:13:09.261  7509  7509 W Glide   : java.lang.IllegalStateException(Had two simultaneous puts for: 3171d8cb16238dfa8783c15e06a329f857214733a083e9dce31d48608386ee30)
11-04 10:13:09.261  7509  7509 W Glide   :  call GlideException#logRootCauses(String) for more detail
11-04 10:13:09.261  7509  7509 W Glide   :   Cause (1 of 1): class java.lang.IllegalStateException: Had two simultaneous puts for: 3171d8cb16238dfa8783c15e06a329f857214733a083e9dce31d48608386ee30
11-04 10:13:09.262  7509  7509 I Glide   : Root cause (1 of 1)
11-04 10:13:09.262  7509  7509 I Glide   : java.lang.IllegalStateException: Had two simultaneous puts for: 3171d8cb16238dfa8783c15e06a329f857214733a083e9dce31d48608386ee30
11-04 10:13:09.262  7509  7509 I Glide   : 	at z0.e.a(DiskLruCacheWrapper.java:113)
11-04 10:13:09.262  7509  7509 I Glide   : 	at com.bumptech.glide.load.engine.v.b(SourceGenerator.java:49)
11-04 10:13:09.262  7509  7509 I Glide   : 	at com.bumptech.glide.load.engine.v.a(SourceGenerator.java:8)
11-04 10:13:09.262  7509  7509 I Glide   : 	at com.bumptech.glide.load.engine.h.E(DecodeJob.java:24)
11-04 10:13:09.262  7509  7509 I Glide   : 	at com.bumptech.glide.load.engine.h.G(DecodeJob.java:49)
11-04 10:13:09.262  7509  7509 I Glide   : 	at com.bumptech.glide.load.engine.h.run(DecodeJob.java:28)
11-04 10:13:09.262  7509  7509 I Glide   : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-04 10:13:09.262  7509  7509 I Glide   : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-04 10:13:09.262  7509  7509 I Glide   : 	at java.lang.Thread.run(Thread.java:923)
11-04 10:13:09.262  7509  7509 I Glide   : 	at a1.a$b$a.run(GlideExecutor.java:32)
```
