### ISSUE TITLE
MultiTransformation Request threw uncaught throwable AbstractMethodError

### ISSUE THREAD

**Issue by Alexandre-Nut** [bumptech/glide#2177]
**Glide Version**:

```
compile "com.github.bumptech.glide:glide:4.0.0-RC1'"
annotationProcessor "com.github.bumptech.glide:compiler4.0.0-RC1'"
```

**Integration libraries**:3
```
compile 'jp.wasabeef:glide-transformations:2.0.2'
```

**Device/Android Version**:
```
minSdkVersion 21
targetSdkVersion 26
```

**Issue details / Repro steps / Use case background**: 
Every MultiTransformation

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
List<Transformation<Bitmap>> transformationList = new LinkedList<>();
        transformationList.add(new BlurTransformation(context, 15));
        transformationList.add(new ColorFilterTransformation(mActivity, colorForFilter));

        MultiTransformation<Bitmap> multiTransformation = new MultiTransformation<>(transformationList);

        Glide.with(mActivity)
                .load(Utility.bitmapToByte(newBitmap))
                .apply(new RequestOptions()
                        .transform(multiTransformation))
                .into(blurImage);
```

**Stack trace / LogCat**:
```ruby
E/GlideExecutor: Request threw uncaught throwable
 java.lang.AbstractMethodError: abstract method "com.bumptech.glide.load.engine.Resource com.bumptech.glide.load.Transformation.transform(android.content.Context, com.bumptech.glide.load.engine.Resource, int, int)"
  at com.bumptech.glide.load.MultiTransformation.transform(MultiTransformation.java:40)
  at com.bumptech.glide.load.engine.DecodeJob$DecodeCallback.onResourceDecoded(DecodeJob.java:495)
  at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:44)
  at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
  at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
  at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:457)
  at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:450)
  at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:436)
  at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:390)
  at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:359)
  at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
  at com.bumptech.glide.load.model.ByteArrayLoader$Fetcher.loadData(ByteArrayLoader.java:59)
  at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
  at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:282)
  at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:249)
  at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:222)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
  at java.lang.Thread.run(Thread.java:761)
  at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)
E/GlideExecutor: Request threw uncaught throwable
java.lang.AbstractMethodError: abstract method "com.bumptech.glide.load.engine.Resource com.bumptech.glide.load.Transformation.transform(android.content.Context, com.bumptech.glide.load.engine.Resource, int, int)"
  at com.bumptech.glide.load.MultiTransformation.transform(MultiTransformation.java:40)
  at com.bumptech.glide.load.engine.DecodeJob$DecodeCallback.onResourceDecoded(DecodeJob.java:495)
  at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:44)
  at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
  at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
  at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:457)
  at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:450)
  at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:436)
  at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:390)
  at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:359)
  at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
  at com.bumptech.glide.load.model.ByteArrayLoader$Fetcher.loadData(ByteArrayLoader.java:59)
  at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
  at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:282)
  at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:249)
  at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:222)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
  at java.lang.Thread.run(Thread.java:761)
  at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)
```

**Comment by TWiStErRob** [comment]
The API changed between v3 and v4, urge @wasabeef to release a new version/fork the library to support Glide 4+

**Comment by Saketme** [comment]
@TWiStErRob wasabeef seems to be busy so I think I'll have to fix this myself. Can you point us to what is incorrectly being done in the older transformations?

**Comment by TWiStErRob** [comment]
Nothing is incorrect, just different. Copy over one of the transformations from the library and make it compile in your project with Glide v4.

Note: not strictly speaking part for v3-v4 differences, but I urge you to `extends BitmapTransformation` instead of `implements Transformation`. It takes a lot of complexity off your hands.
