### ISSUE TITLE
How do I use glide to load images from FTP server?

### ISSUE THREAD

**Issue by VictoryWangV** [bumptech/glide#2196]
```
String url = "ftp://ftpuser:av9bcxm1ae9r9wjfeka2@10.10.20.122:21/2017/03f03ae0e2dbd0e264157b4dc194d04f.jpeg";
Uri uri = Uri.parse(url);
Glide.with(context).load(uri).into(mImageView);
```
It doesn't work, but I can load this url on the chrome browser;

This is the exception message:
```
D/GenericRequest: load failed
                  java.lang.Exception: Failed to load model: 'ftp://ftpuser:av9bcxm1ae9r9wjfeka2@10.10.20.122:21/2017/03f03ae0e2dbd0e264157b4dc194d04f.jpeg'
                      at com.bumptech.glide.request.GenericRequest.onSizeReady(GenericRequest.java:441)
                      at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.getSize(ViewTarget.java:211)
                      at com.bumptech.glide.request.target.ViewTarget.getSize(ViewTarget.java:100)
                      at com.bumptech.glide.request.GenericRequest.begin(GenericRequest.java:272)
                      at com.bumptech.glide.manager.RequestTracker.resumeRequests(RequestTracker.java:83)
                      at com.bumptech.glide.RequestManager.resumeRequests(RequestManager.java:180)
                      at com.bumptech.glide.RequestManager.onStart(RequestManager.java:203)
                      at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStart(ActivityFragmentLifecycle.java:50)
                      at com.bumptech.glide.manager.RequestManagerFragment.onStart(RequestManagerFragment.java:136)
                      at android.app.Fragment.performStart(Fragment.java:2379)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1027)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
                      at android.app.BackStackRecord.run(BackStackRecord.java:816)
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
                      at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6290)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by sjudd** [comment]
Is this Glide v3? Can you fill out the rest of the issue template?

**Comment by VictoryWangV** [comment]
First of all, thank you for answering my question.
this is Glide v3.7.0
` "com.github.bumptech.glide:glide:3.7.0"`
i don't know what  the rest of the issue template means,
if you're referring to exception message,That's all I can get,
if you're referring to my code,When I switch to a url like this,it works,
```
        //String url = "ftp://ftpuser:av9bcxm1ae9r9wjfeka2@10.10.20.122:21/2017/03f03ae0e2dbd0e264157b4dc194d04f.jpeg";
        String url = "http://imgsrc.baidu.com/imgad/pic/item/267f9e2f07082838b5168c32b299a9014c08f1f9.jpg";
        Uri uri = Uri.parse(url);
        Glide.with(context).load(uri).into(mImageView);
```

**Comment by sjudd** [comment]
Thanks. Glide doesn't directly support ftp urls out of the box (as you've discovered). They have to be treated somewhat differently from http urls so we'd need an additional ModelLoader to retrieve ftp streams.

**Comment by VictoryWangV** [comment]
thanks again!
I seem to need A custom ModelLoader...

**Comment by yanbin92** [comment]
i solve this in Glidev3.7 link this https://github.com/bumptech/glide/issues/2991#issuecomment-497220796
