### ISSUE TITLE
 Expected instanceof GlideModule, but found XXX.

### ISSUE THREAD

**Issue by sundxing** [bumptech/glide#2211]
**Glide Version**: 3.8.0

**Integration libraries**: NO

**Device/Android Version**: Galaxy S5 5.0

**Issue details / Repro steps / Use case background**:  Crash report in `farbic`.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
proguard.pro :
```
 -keep public class * implements com.bumptech.glide.module.GlideModule
 -keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
    **[] $VALUES;
    public *;
}
```
``` java
public class MyGlideModule implements GlideModule {
...
}
```
And meta info is right in `AndroidManifest.xml`

**Stack trace / LogCat**:
```ruby
Fatal Exception: java.lang.RuntimeException: Expected instanceof GlideModule, but found: com.XXX.MyGlideModule@10e4109a
       at com.bumptech.glide.module.ManifestParser.parseModule(ManifestParser.java:59)
       at com.bumptech.glide.module.ManifestParser.parse(ManifestParser.java:30)
       at com.bumptech.glide.Glide.parseGlideModules(Glide.java:1187)
       at com.bumptech.glide.RequestManager.(RequestManager.java)
       at com.bumptech.glide.RequestManager.(RequestManager.java)
       at com.bumptech.glide.manager.RequestManagerRetriever.fragmentGet(RequestManagerRetriever.java:4171)
       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:89)
       at com.bumptech.glide.Glide.with(Glide.java:657)
```

**Comment by TWiStErRob** [comment]
- Double check package name
- multidex?
- how many occurrences?
- reproducible?
- only S5? (I have one, if you want me to, I could download your app and see if it crashes, feel free to send link in private mail)

**Comment by meidikawardana** [comment]
I got this error too. I posted it on stackoverflow: https://stackoverflow.com/questions/46638056/how-to-use-glidemodule-on-glide-4

**Comment by TWiStErRob** [comment]
Kevin is right on SO.

**Comment by meidikawardana** [comment]
so I need to open new issue and remove my comments here, @TWiStErRob ?

**Comment by TWiStErRob** [comment]
No worries, just follow what Kevin said, that should resolve your problem.

**Comment by kannuverma12** [comment]
I am also getting the same error.
any resolution?

**Comment by TWiStErRob** [comment]
@kannuverma12 not enough info in OP, if you can repro and provide details

**Comment by Dvik** [comment]
This issue recently started happening for me when i updated to Google Maps Beta SDK (https://developers.google.com/maps/documentation/android-sdk/v3-client-migration). Not sure how that's related. I'm on Glide version 3.8.0. 

```
java.lang.RuntimeException: Expected instanceof GlideModule, but found: MyGlideModule@9ee46bc
        at com.google.android.libraries.maps.w.zzd.zza(ManifestParser.java:39)
        at com.google.android.libraries.maps.w.zzd.zza(ManifestParser.java:18)
        at com.google.android.libraries.maps.c.zzb.zza(Glide.java:14)
        at com.google.android.libraries.maps.c.zzb.zzb(Glide.java:240)
        at com.google.android.libraries.maps.cq.zzh.zza(ResourceManagerImpl.java:7)
        at com.google.android.libraries.maps.ij.zzaw.zza(Suppliers.java:7)
        at com.google.android.libraries.maps.cq.zzi.run(Unknown Source:8)
        at com.google.android.libraries.maps.fv.zzc.run(CancelableRunnable.java:7)
        at com.google.android.libraries.maps.fv.zzae.run(Task.java:9)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.libraries.maps.fv.zzv.run(GmmThread.java:10)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by Maulik0412** [comment]
> This issue recently started happening for me when i updated to Google Maps Beta SDK (https://developers.google.com/maps/documentation/android-sdk/v3-client-migration). Not sure how that's related. I'm on Glide version 3.8.0.
> 
> ```
> java.lang.RuntimeException: Expected instanceof GlideModule, but found: MyGlideModule@9ee46bc
>         at com.google.android.libraries.maps.w.zzd.zza(ManifestParser.java:39)
>         at com.google.android.libraries.maps.w.zzd.zza(ManifestParser.java:18)
>         at com.google.android.libraries.maps.c.zzb.zza(Glide.java:14)
>         at com.google.android.libraries.maps.c.zzb.zzb(Glide.java:240)
>         at com.google.android.libraries.maps.cq.zzh.zza(ResourceManagerImpl.java:7)
>         at com.google.android.libraries.maps.ij.zzaw.zza(Suppliers.java:7)
>         at com.google.android.libraries.maps.cq.zzi.run(Unknown Source:8)
>         at com.google.android.libraries.maps.fv.zzc.run(CancelableRunnable.java:7)
>         at com.google.android.libraries.maps.fv.zzae.run(Task.java:9)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at com.google.android.libraries.maps.fv.zzv.run(GmmThread.java:10)
>         at java.lang.Thread.run(Thread.java:919)
> ```

I am also getting the same issue 
any solution for that.?

**Comment by TWiStErRob** [comment]
@Dvik @Maulik0412 please report this to Google Maps SDK, they need to find a way to use Glide internally that doesn't conflict with normal Glide usage. `maps.c` and `maps.w` are repackaged and obfuscated versions of Glide.

They might be missing a flag to turn off manifest parsing, if they use v4. Or need to start using v4 with annotation processing to discover GlideModules their side of the compilation, not at runtime.

You can work around by migrating to Glide v4 and/or using annotation processing to discover GlideModules. See the current Glide docs how.
