### ISSUE TITLE
missing IConnectivityManager

### ISSUE THREAD

**Issue by lotuslovenature** [bumptech/glide#2224]
**Glide Version**:3.7.0

**Integration libraries**:

**Device/Android Version**:4.0.3 BesTV_R1229 STB

**Issue details / Repro steps / Use case background**: 
crashReport show this error many times.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
DefaultConnectivityMonitorFactory
```

**Stack trace / LogCat**:
```ruby
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bestv.ott.baseservices/com.bestv.ott.launcher.LauncherActivity}: java.lang.NullPointerException: missing IConnectivityManager
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1956)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
at android.app.ActivityThread.access$600(ActivityThread.java:123)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4429)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException: missing IConnectivityManager
at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:52)
at android.net.ConnectivityManager.<init>(ConnectivityManager.java:601)
at android.app.ContextImpl$8.createStaticService(ContextImpl.java:295)
at android.app.ContextImpl$StaticServiceFetcher.getService(ContextImpl.java:229)
at android.app.ContextImpl.getSystemService(ContextImpl.java:1208)
at android.content.ContextWrapper.getSystemService(ContextWrapper.java:386)
at com.bumptech.glide.manager.DefaultConnectivityMonitor.isConnected(DefaultConnectivityMonitor.java:53)
at com.bumptech.glide.manager.DefaultConnectivityMonitor.register(DefaultConnectivityMonitor.java:38)
at com.bumptech.glide.manager.DefaultConnectivityMonitor.onStart(DefaultConnectivityMonitor.java:61)
at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStart(ActivityFragmentLifecycle.java:50)
at com.bumptech.glide.manager.RequestManagerFragment.onStart(RequestManagerFragment.java:136)
at android.app.Fragment.performStart(Fragment.java:1532)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:862)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1032)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1014)
at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:1771)
at android.app.Activity.performStart(Activity.java:4481)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1929)
... 11 more
java.lang.NullPointerException: missing IConnectivityManager
at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:52)
at android.net.ConnectivityManager.<init>(ConnectivityManager.java:601)
at android.app.ContextImpl$8.createStaticService(ContextImpl.java:295)
at android.app.ContextImpl$StaticServiceFetcher.getService(ContextImpl.java:229)
at android.app.ContextImpl.getSystemService(ContextImpl.java:1208)
at android.content.ContextWrapper.getSystemService(ContextWrapper.java:386)
at com.bumptech.glide.manager.DefaultConnectivityMonitor.isConnected(DefaultConnectivityMonitor.java:53)
at com.bumptech.glide.manager.DefaultConnectivityMonitor.register(DefaultConnectivityMonitor.java:38)
at com.bumptech.glide.manager.DefaultConnectivityMonitor.onStart(DefaultConnectivityMonitor.java:61)
at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStart(ActivityFragmentLifecycle.java:50)
at com.bumptech.glide.manager.RequestManagerFragment.onStart(RequestManagerFragment.java:136)
at android.app.Fragment.performStart(Fragment.java:1532)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:862)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1032)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1014)
at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:1771)
at android.app.Activity.performStart(Activity.java:4481)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1929)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
at android.app.ActivityThread.access$600(ActivityThread.java:123)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4429)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
at dalvik.system.NativeStart.main(Native Method)
```

This crash appear some special device model, Once it appears, it occurs again and again. Guess The system service is not ready when the device is started. Can you add an NPE judge, please help!

**Comment by sjudd** [comment]
In Glide you can modify the connectivity monitor factory to handle this device: http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/GlideBuilder.html#setConnectivityMonitorFactory-com.bumptech.glide.manager.ConnectivityMonitorFactory-

To change options in GlideBuilder, see:
http://bumptech.github.io/glide/doc/configuration.html#application-options

If it only occurs on once device and it's a bug in the platform, it's probably not something we'll handle in the library.
