### ISSUE TITLE
Request threw uncaught throwable  java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by sinhpn92** [bumptech/glide#2229]
I have got error `OutOfMemoryError` when use `Glide 4`.
My logcat:

```
dalvikvm-heap: Clamp target GC heap from 131.904MB to 128.000MB
dalvikvm: GC_BEFORE_OOM freed 1K, 10% free 116658K/129380K, paused 76ms, total 76ms
dalvikvm-heap: Out of memory on a 2457616-byte allocation.
dalvikvm: "glide-disk-cache-thread-1" prio=5 tid=45 RUNNABLE
dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0x48f5bd80 self=0x7b500dc0
dalvikvm:   | sysTid=25510 nice=9 sched=0/0 cgrp=apps handle=2106302120
dalvikvm:   | state=R schedstat=( 142347293 12250103 38 ) utm=14 stm=0 core=1
dalvikvm:     at android.graphics.Bitmap.nativeCreate(Native Method)
dalvikvm:     at android.graphics.Bitmap.createBitmap(Bitmap.java:903)
dalvikvm:     at android.graphics.Bitmap.createBitmap(Bitmap.java:880)
dalvikvm:     at android.graphics.Bitmap.createBitmap(Bitmap.java:847)
dalvikvm:     at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.getDirty(LruBitmapPool.java:140)
dalvikvm:     at com.bumptech.glide.load.resource.bitmap.Downsampler.setInBitmap(Downsampler.java:504)
dalvikvm:     at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:240)
dalvikvm:     at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:176)
dalvikvm:     at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:134)
dalvikvm:     at com.bumptech.glide.load.resource.bitmap.ByteBufferBitmapDecoder.decode(ByteBufferBitmapDecoder.java:31)
dalvikvm:     at com.bumptech.glide.load.resource.bitmap.ByteBufferBitmapDecoder.decode(ByteBufferBitmapDecoder.java:15)
dalvikvm:     at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67)
dalvikvm:     at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52)
dalvikvm:     at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43)
dalvikvm:     at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
dalvikvm:     at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
dalvikvm:     at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:457)
dalvikvm:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:450)
dalvikvm:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:436)
dalvikvm:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:390)
dalvikvm:     at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:359)
dalvikvm:     at com.bumptech.glide.load.engine.ResourceCacheGenerator.onDataReady(ResourceCacheGenerator.java:100)
dalvikvm:     at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:68)
dalvikvm:     at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:79)
dalvikvm:     at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:282)
dalvikvm:     at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:249)
dalvikvm:     at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:222)
dalvikvm:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
dalvikvm:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
dalvikvm:     at java.lang.Thread.run(Thread.java:841)
dalvikvm:     at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)
GlideExecutor: Request threw uncaught throwable
         java.lang.OutOfMemoryError
             at android.graphics.Bitmap.nativeCreate(Native Method)
             at android.graphics.Bitmap.createBitmap(Bitmap.java:903)
             at android.graphics.Bitmap.createBitmap(Bitmap.java:880)
             at android.graphics.Bitmap.createBitmap(Bitmap.java:847)
             at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.getDirty(LruBitmapPool.java:140)
             at com.bumptech.glide.load.resource.bitmap.Downsampler.setInBitmap(Downsampler.java:504)
             at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:240)
             at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:176)
             at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:134)
             at com.bumptech.glide.load.resource.bitmap.ByteBufferBitmapDecoder.decode(ByteBufferBitmapDecoder.java:31)
             at com.bumptech.glide.load.resource.bitmap.ByteBufferBitmapDecoder.decode(ByteBufferBitmapDecoder.java:15)
             at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67)
             at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52)
             at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43)
             at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
             at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
             at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:457)
             at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:450)
             at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:436)
             at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:390)
             at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:359)
             at com.bumptech.glide.load.engine.ResourceCacheGenerator.onDataReady(ResourceCacheGenerator.java:100)
             at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:68)
             at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:79)
             at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:282)
             at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:249)
             at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:222)
             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
             at java.lang.Thread.run(Thread.java:841)
             at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)

```

I was trying to `clearMemory` in `onLowMemory` method, but it not call this.

     @Override
    public void onLowMemory() {
        super.onLowMemory();
        GlideApp.get(this).clearMemory();
        GlideApp.with(this).onLowMemory();
    }

    @Override
    public void onTrimMemory(int level) {
        super.onTrimMemory(level);
        GlideApp.get(this).onTrimMemory(level);
        GlideApp.with(this).onTrimMemory(level);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        GlideApp.get(this).clearMemory();
    }

How can i handle this error and fix it? Thanks so much.

**Comment by TWiStErRob** [comment]
Are you aware of this: https://stackoverflow.com/a/32887693/253468

Maybe something is holding on, or you just have a non-Glide related memory leak.

**Comment by sinhpn92** [comment]
@TWiStErRob yeap. I did. I didn't use `applicationContext`. 
I use `GlideApp.with(this)` in `Activity` or `Fragment`. Sometime i use `GlideApp.with(context)`  in customview.

**Comment by sinhpn92** [comment]
@TWiStErRob 
Have any problem if i use `GlideApp` like this? 
```
public class CustomView extends LinearLayout {
      
    ....
    private GlideRequests glideRequests;
    private ImageView imv;

    public CustomView(Context context) {
        super(context);
        init();
    }

    public CustomView(Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
        init();
    }

    public CustomView(Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        init();
    }

    @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
    public CustomView(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        super(context, attrs, defStyleAttr, defStyleRes);
        init();
    }

    private void init() {
      inflate(getContext(), R.layout.layout_custom_view, this);
      glideRequests = GlideApp.with(getContext());
      ...
    }

    public void bindView(Entity entity) {
       glideRequests.load(entity.getUrl())
                .skipMemoryCache(false)
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .transition(DrawableTransitionOptions.withCrossFade())
                .into(imv);
    }
}
```

**Comment by TWiStErRob** [comment]
There's a new `with(View)` overload.

It shouldn't be a problem though to use it like this. Try to take a heap dump and check what's using the memory.

**Comment by sinhpn92** [comment]
@TWiStErRob 
When i add this code into my `View`, My app is not `OutOfMemoryError`.
```
@Override
    protected void onDetachedFromWindow() {
        super.onDetachedFromWindow();
        Log.e("Sinhpn", "DealViewV2: onDetachedFromWindow");
        GlideApp.get(getContext()).clearMemory();
    }
```

**Comment by sjudd** [comment]
See https://developer.android.com/studio/profile/investigate-ram.html. You're going to need a heap dump to investigate memory issues.

**Comment by hansonchris** [comment]
I see the same issue. Here are the results of tracking memory allocations when this issue occurs:

![image](https://user-images.githubusercontent.com/2294270/31628854-bf87e5e4-b266-11e7-8bb0-60e0c45977e3.png)

![image](https://user-images.githubusercontent.com/2294270/31628942-fb8d310c-b266-11e7-88e2-4f65b698488d.png)

Those two threads were using far more memory than any other. I see this consistently on an old Galaxy S3 that I unfortunately must continue to support, but I have not seen it on any other device or emulator.

I am doing two Glide operations at the same time. One is loading the `Uri` into an `ImageView`, and the other is loading the `Uri` into a `SimpleTarget<Drawable>` so that I can scale the bytes and upload to a service.

I'm sure that the advice here is "don't do two Glide operations simultaneously", and I definitely will work towards that. But I thought that at least providing memory details might help, assuming that what I'm seeing has the same root cause as what others have reported.
