### ISSUE TITLE
Failed to load resource  HttpException okhttp3

### ISSUE THREAD

**Issue by rundong-wang** [bumptech/glide#2230]
i got  issues  
class com.bumptech.glide.load.engine.GlideException: Failed to load resource
I/Glide: Root cause (1 of 1)
                                                         com.bumptech.glide.load.HttpException: 
                                                             at com.bumptech.glide.integration.okhttp3.OkHttpStreamFetcher$1.onResponse(OkHttpStreamFetcher.java:62)
                                                             at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
                                                             at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                             at java.lang.Thread.run(Thread.java:762)

**Comment by victorfan336** [comment]
hello, I have the same problem, can you share the answer with me ? thanks

**Comment by john990** [comment]
same problem
````
W/Glide: Load failed for https://lastfm.freetls.fastly.net/i/u/174s/560c0e05df0298da38428c38877f1ccd.png with size [86x86]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 root cause:
    com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 root cause:
    com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.HttpException: Failed to connect or obtain data, status code: -1
````

**Comment by chnouman** [comment]
same
