### ISSUE TITLE
ConcurrentModificationException with RequestBuilder as a thumbnail

### ISSUE THREAD

**Issue by blink7** [bumptech/glide#2237]
**Glide Version**: 4.0.0

**Integration libraries**: okhttp3-integration

**Device/Android Version**: Galaxy Note 5 7.0/Nexus 6P 8.0

In my app there is a list (RecyclerView) of images, which load through Glide. Some images are GIF, so for them I use static thumbnails. When I quickly scroll down and up the app crashes with following exception:
```
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.blinkseven.jrviewer, PID: 18619
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.next(ArrayList.java:831)
    at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.notifyCbs(ViewTarget.java:180)
    at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.checkCurrentDimens(ViewTarget.java:197)
    at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer$SizeDeterminerLayoutListener.onPreDraw(ViewTarget.java:310)
    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1013)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2513)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1522)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7098)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
    at android.view.Choreographer.doCallbacks(Choreographer.java:702)
    at android.view.Choreographer.doFrame(Choreographer.java:638)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6682)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```
I noticed that the app crashes only on items with GIFs and its thumbnails, namely when I include thumbnails loading.

Here is an example of loading GIFs with Glide:
```
RequestBuilder<Drawable> thumbnailRequest = GlideApp
                .with(this)
                .load(imageModel.getUri())
                .thumbnail(0.5f)
                .fallback(android.R.color.holo_orange_light)
                .placeholder(android.R.color.holo_green_light)
                .error(android.R.color.holo_red_light)
                .dontAnimate();

        GlideApp
                .with(this)
                .load(imageModel.getFullUri())
                .listener(listener)
                // Load gif's thumbnail through RequestBuilder
                .thumbnail(thumbnailRequest)
                .fallback(android.R.color.holo_orange_light)
                .placeholder(android.R.color.holo_green_light)
                .error(android.R.color.holo_red_light)
                .into((ImageView) findViewById(R.id.image));
```

If exclude 'thumbnail' option there is no exception.

**Comment by sjudd** [comment]
Can you share your Listener code?

**Comment by blink7** [comment]
Yes, here it is:
```
RequestListener<Drawable> listener = new RequestListener<Drawable>() {
            @Override
            public boolean onLoadFailed(@Nullable GlideException e, Object model,
                                        Target<Drawable> target, boolean isFirstResource) {
                return false;
            }

            @Override
            public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target,
                                           DataSource dataSource, boolean isFirstResource) {
                textView.setVisibility(View.GONE);
                return false;
            }
        };
```
