### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by devtechvalens** [bumptech/glide#2300]
**Glide Version**:
4.0.0

**Integration libraries**:
Retrofit, OkHttp3

**Device/Android Version**:
Samsung Galaxy J7, 6.0

**Issue details / Repro steps / Use case background**: 
I am getting **Unauthorized** Error.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
      LazyHeaders auth = new LazyHeaders.Builder() // can be cached in a field and reused
                        .addHeader("auth-token", MyPreference.getUserAuthToken())
                        .build();
                Glide
                        .with(mActivity)
                        .load(new GlideUrl
                                (ApiEndPoint.IMG_BASE_URL + "/tickets/" + mTicketsDatumModal.getSequence()
                                        + "/qrcode", auth))
                        .into(qr_code_iv);
```

**Stack trace / LogCat**:
```ruby
com.bumptech.glide.load.HttpException: Unauthorized
                                                    at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:118)
                                                    at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:53)
                                                    at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
                                                    at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:282)
                                                    at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:252)
                                                    at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:222)
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                    at java.lang.Thread.run(Thread.java:818)
                                                    at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)
```

**Comment by sjudd** [comment]
Have you checked to ensure that your auth header is being sent? Or that you've included all required headers?

**Comment by TWiStErRob** [comment]
Could be as simple as `getUserAuthToken` returning an invalid token.
