### ISSUE TITLE
Preloading Images returning 500 Server Error

### ISSUE THREAD

**Issue by bailsp** [bumptech/glide#2308]
**Glide Version**: 4.0

**Integration libraries**: None.

**Device/Android Version**: Droid/Android 6.0.1 API 23

**Issue details / Repro steps / Use case background**: Working on an offline application that requires to preload 1000+ images onto the disk cache. When attempting to hit the server, some of the image cache requests are returning a 500 code (Server Error). 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GlideUrl glideUrl = new GlideUrl(url, new LazyHeaders.Builder().addHeader("Authorization", "Bearer " + token).build());
GlideApp.with(context).load(glideUrl).diskCacheStrategy(DiskCacheStrategy.ALL).preload();
```

**Stack trace / LogCat**:
```ruby
08-30 09:11:21.220 16097-16097/net.com.app W/Glide: Load failed for {link removed} with size [-2147483648x-2147483648]
                                                       class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                         Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
                                                           Cause (1 of 1): class com.bumptech.glide.load.HttpException: Server Error
08-30 09:11:21.220 16097-16097/net.com.app E/Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
08-30 09:11:21.220 16097-16097/net.com.app I/Glide: Root cause (1 of 1)
                                                       com.bumptech.glide.load.HttpException: Server Error
                                                           at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:118)
                                                           at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:53)
                                                           at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
                                                           at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:282)
                                                           at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:252)
                                                           at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:222)
                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                           at java.lang.Thread.run(Thread.java:818)
                                                           at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)```

**Comment by sjudd** [comment]
You'll need to investigate whatever backend you're using to determine why it's experiencing errors.
