### ISSUE TITLE
No virtual method load

### ISSUE THREAD

**Issue by Ajit121** [bumptech/glide#2311]
Updated version from 3.7.0 to 4.0.0 and now facing issues with this version. Lot of .class file is missing from previous version and i'm also not able to use the version 3.7.0 for which i have already raised an issue (#2310). These files are very necessary.

**Glide Version**:
Version 4.0.0

**Stack trace / LogCat**:

      java.lang.NoSuchMethodError: No virtual method load(Ljava/io/File;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/cipl.hello-1/base.apk)
                                                                 at vc908.stickerfactory.StickerLoader.load(StickerLoader.java:77)
                                                                 at vc908.stickerfactory.StickerLoader.into(StickerLoader.java:70)
                                                                 at cipl.adapter.ChatListAdapter.onBindViewHolder(ChatListAdapter.java:114)
                                                                 at cipl.adapter.ChatListAdapter.onBindViewHolder(ChatListAdapter.java:43)
                                                                 at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                                 at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                 at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                 at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                 at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                 at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                 at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                 at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                 at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                 at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                 at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                 at android.view.View.layout(View.java:17689)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5582)
                                                                 at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                 at android.view.View.layout(View.java:17689)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5582)
                                                                 at com.sothree.slidinguppanel.SlidingUpPanelLayout.onLayout(SlidingUpPanelLayout.java:864)
                                                                 at android.view.View.layout(View.java:17689)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5582)
                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                 at android.view.View.layout(View.java:17689)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5582)
                                                                 at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
                                                                 at android.view.View.layout(View.java:17689)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5582)
                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                 at android.view.View.layout(View.java:17689)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5582)
                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                 at android.view.View.layout(View.java:17689)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5582)
                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                 at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
                                                                 at android.view.View.layout(View.java:17689)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5582)
                                                                 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                 at android.view.Choreographer.doFrame(Choreographer.java:621)
08-30 23:52:43.755 7609-7609/cipl.hello E/UncaughtException:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                 at android.os.Handler.handleCallback(Handler.java:751)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by TWiStErRob** [comment]
Solved and explained in #2310
