### ISSUE TITLE
App compat errors

### ISSUE THREAD

**Issue by Tolriq** [bumptech/glide#2321]
**Glide Version**:
4.x

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

Sometimes at random Support libraries for vector drawable have bugs or race condition and will crash.
I know this is probably out of Glide scope to catch those errors. But this is not something that can be fixed by applications. And currently there's no way to catch those.
I'd rather prefer a missing image when the lib have a problem than an app crash.
Maybe you can add an option to catch and ignore those OS / support lib errors?

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=13; index=13
       at android.support.v4.util.SparseArrayCompat.append(SparseArrayCompat.java:325)
       at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:383)
       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
       at android.support.v7.content.res.AppCompatResources.android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatResources.java:1188)
       at com.bumptech.glide.request.SingleRequest.loadDrawableV7(SingleRequest.java:383)
       at com.bumptech.glide.request.SingleRequest.loadDrawable(SingleRequest.java:371)
       at com.bumptech.glide.request.SingleRequest.getErrorDrawable(SingleRequest.java:23343)
       at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:216)
       at com.bumptech.glide.RequestBuilder.com.bumptech.glide.manager.RequestTracker.runRequest(RequestBuilder.java:9039)
       at com.bumptech.glide.RequestBuilder$1.run(RequestBuilder.java:485)
       at android.os.Handler.handleCallback(Handler.java)
       at android.os.Handler.dispatchMessage(Handler.java)
       at android.os.Looper.loop(Looper.java)
       at android.app.ActivityThread.main(ActivityThread.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

**Comment by sjudd** [comment]
Do you have a sample vector drawable that can cause this?

**Comment by sjudd** [comment]
Internal bug is b/65349424

**Comment by TWiStErRob** [comment]
I agree here, the problem is that `getErrorDrawable`/`getPlaceholderDrawable` are running on the main thread without a `catch`, these errors should be delegated to `listener/target.onLoadFailed`, not let roam free, right?

**Comment by sjudd** [comment]
I wouldn't want to call onLoadFailed, the load may succeed even if we can't display the placeholder. We could silently ignore these I guess, but it's pretty weird to just have an image not display too. 

It's really a bug in the support library, hopefully they can fix it relatively quickly. If they can't I'll add try/catch ignore in 4.2. 

Also how frequently does this occur? If you can't reproduce but you see it logged infrequently, it's probably fine to wait. If it's easy to reproduce or happens all the time then maybe I can sneak it in to 4.1.1 (which I'll hopefully get out tomorrow).

**Comment by TWiStErRob** [comment]
Hmm, good point about placeholder(), but error()/fallback() should fail? because at that point there's nothing to display and no further action will be taken. Kind of like terminal event. OP's stack is error().

**Comment by Tolriq** [comment]
This is a very rare crash and actually not always tied to vector drawable.
(And was here since 21 or 20 app compat so I doubt about a quick fix ;) )

Typically with Glide I only use png as error images and from the crash dump it seems it's tied to one error image.

I have crash report from Android 4 to 6 lot's of different models.

**Comment by sjudd** [comment]
Have you (or anyone else) seen this crash in an app not using XposedBridge?

**Comment by Tolriq** [comment]
@sjudd yes

On non rooted device the error can be for example: 
(This one is about vector drawable as menu icons)
But really very very rare crash. 

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=61; index=61
       at android.support.v4.util.SparseArrayCompat.append(SparseArrayCompat.java:325)
       at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:383)
       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
       at android.support.v7.content.res.AppCompatResources.android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatResources.java:1188)
       at android.support.v7.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:491)
       at android.support.v7.view.menu.ActionMenuItemView.initialize$667f453d(ActionMenuItemView.java:125)
       at android.support.v7.widget.ActionMenuPresenter.bindItemView(ActionMenuPresenter.java:210)
       at android.support.v7.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:187)
       at android.support.v7.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:196)
       at android.support.v7.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:476)
       at android.support.v7.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1164)
       at android.support.v7.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:95)
       at android.support.v7.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:229)
       at android.support.v7.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:8291)
       at android.support.v7.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:1078)
       at android.support.v7.app.ToolbarActionBar$1.android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:1461)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5525)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

**Comment by sjudd** [comment]
@Tolriq great thanks!

@TWiStErRob If error/fallback fail our default would be to show error or fallback :). We could work around that but then callers either get no notification, or they get two error callbacks for the same load. 

I think we either:
1. Assume this happens infrequently enough that we can wait for a fix in the support library (it looks like it might be a threading issue).
2. try/catch/ignore the exception.

**Comment by Tolriq** [comment]
Earlier for Glide 3 we had a discussion about how to handle OOM for those error images too.
https://github.com/bumptech/glide/issues/491

Don't know if this is still handled in Glide 4. But this kind of issue may not always be caused by support libs.

Having crash by default is good as can help find issues. (Like I used to have an error image wrongly put in mdpi folder and not nodpi that took 36Mb of ram once on xxxhdpi devices :))
But having an option to ignore then when we know that we can't fix the root cause might be cool.

**Comment by sjudd** [comment]
Given how incoherent the failures are going to be here, I'm inclined to not try to try/catch in the library. Hopefully this will be fixed soon in the support library.
