### ISSUE TITLE
okhttp3 User-Agent Unexpected char exception

### ISSUE THREAD

**Issue by skauss** [bumptech/glide#2331]
Hi 
we use Glide version 4.0.0 with okhttp3-integration.
build.gradle :
```ruby
    compile 'com.github.bumptech.glide:glide:4.0.0'
    compile 'com.github.bumptech.glide:annotations:4.0.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0'
    compile 'com.github.bumptech.glide:okhttp3-integration:4.0.0@aar'
```

The device I use is from china. 
The Glide okhttp3-intergration try to set the User-Agent into the Http header. 
I guess 
```ruby
String userAgent = System.getProperty( "http.agent" );
```

java.lang.IllegalArgumentException: Unexpected char 0x516b at 43 in User-Agent value: 
**Dalvik/2.1.0 (Linux; U; Android 5.0; P98 4G八核版(A8H8) Build/LRX21M)**

Here is the compleat exception

```ruby
09-05 13:15:03.670 4285-4594/de.package.xx E/RenderScript: Couldn't load libRSSupportIO.so
09-05 13:15:03.715 4285-4509/de.package.xx E/GlideExecutor: Request threw uncaught throwable
                                                                                    java.lang.IllegalArgumentException: Unexpected char 0x516b at 43 in User-Agent value: Dalvik/2.1.0 (Linux; U; Android 5.0; P98 4G八核版(A8H8) Build/LRX21M)
                                                                                        at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:321)
                                                                                        at okhttp3.Headers$Builder.add(Headers.java:271)
                                                                                        at okhttp3.Request$Builder.addHeader(Request.java:177)
                                                                                        at com.bumptech.glide.integration.okhttp3.OkHttpStreamFetcher.loadData(OkHttpStreamFetcher.java:40)
                                                                                        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:95)
                                                                                        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
                                                                                        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:282)
                                                                                        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:252)
                                                                                        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:222)
```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
@GlideModule
public final class MyAppGlideModule extends AppGlideModule {}
```

**Comment by skauss** [comment]
The http header User-Agent is set in LazyHeaders line 102

**Comment by sjudd** [comment]
Sounds right. You can work around this by manually setting your user agent to something else in each request. It's tedious though.

**Comment by skauss** [comment]
Thanks for the fast response and correction.
