### ISSUE TITLE
The ImageView.setColorFitler method crashes(NP exception)on Android 6.0 

### ISSUE THREAD

**Issue by yuejinzhao** [bumptech/glide#2344]
**Glide Version**: 3.8.0

**Integration libraries**: 

**Device/Android Version**: sony z3, 6.0

**Issue details / Repro steps / Use case background**: 

ImageView.setColorFilter crashes (called while onTouch)

```java
public boolean onTouch(View v, MotionEvent event) {
              themeHolder.themeThumbnail.setColorFilter;
        
        return true;
 
}
```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with((themeHolder.itemView.getContext())).load(theme.thumbnailUrl).asBitmap().fitCenter()
                .placeholder(R.drawable.locker_theme_thumbnail_loading).error(R.drawable.locker_theme_thumbnail_failed)
                .crossFade(550).format(DecodeFormat.PREFER_RGB_565).diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .into(themeHolder.themeThumbnail);
```

**Layout XML**:
```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:launcher="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/grid_root"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:elevation="@dimen/card_elevation"
    tools:ignore="UnusedAttribute"
    tools:layout_width="200dp">

    <com.ihs.inputmethod.uimodules.ui.customize.view.HorizontalBannerImageView
        android:id="@+id/theme_thumbnail"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        launcher:aspectRatioOverride="0.5625"
        launcher:round_left_bottom_corner_radius="@dimen/card_round_corner_radius"
        launcher:round_left_top_corner_radius="@dimen/card_round_corner_radius"
        launcher:round_right_bottom_corner_radius="@dimen/card_round_corner_radius"
        launcher:round_right_top_corner_radius="@dimen/card_round_corner_radius"
        tools:src="@drawable/wallpaper_thumbnail"/>

</FrameLayout>

```

**Stack trace / LogCat**:
```ruby
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable()' on a null object reference
                                                                                at android.graphics.drawable.LayerDrawable$ChildDrawable.<init>(LayerDrawable.java:1723)
                                                                                at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:1792)
                                                                                at android.graphics.drawable.TransitionDrawable$TransitionState.<init>(TransitionDrawable.java:248)
                                                                                at android.graphics.drawable.TransitionDrawable.createConstantState(TransitionDrawable.java:101)
                                                                                at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:1652)
                                                                                at android.widget.ImageView.applyColorMod(ImageView.java:1426)
                                                                                at android.widget.ImageView.setColorFilter(ImageView.java:1374)
                                                                                at android.widget.ImageView.setColorFilter(ImageView.java:1320)
                                                                                at android.widget.ImageView.setColorFilter(ImageView.java:1332)
                                                                                at com.ihs.inputmethod.uimodules.ui.customize.view.ImagePressedTouchListener.setPressedState(ImagePressedTouchListener.java:69)
                                                                                at com.ihs.inputmethod.uimodules.ui.customize.view.ImagePressedTouchListener.onTouch(ImagePressedTouchListener.java:55)
                                                                                at android.view.View.dispatchTouchEvent(View.java:9371)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2548)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2241)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
                                                                                at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2410)
                                                                                at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1744)
                                                                                at android.app.Activity.dispatchTouchEvent(Activity.java:2805)
                                                                                at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                                at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2371)
                                                                                at android.view.View.dispatchPointerEvent(View.java:9597)
                                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4234)
                                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4100)
                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
                                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
                                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
                                                                                at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3791)
                                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
                                                                                at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3848)
                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
                                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
                                                                            	at android.view.ViewRootImpl$

```

I have tried to switch to **ImageLoader** and the setColorFiler works well.

**Comment by sjudd** [comment]
Usually full stack traces are helpful.

At the moment I'm not planning on further bug fix releases for Glide v3. Did you consider using the latest version of Glide (4.1.1)?

**Comment by yuejinzhao** [comment]
Hi @sjudd I have tried updating to glide 4.1.1, but seems some 3.8 method cannot resolve?
Does Glide(4.1.1) ever change **BitmapTypeRequest**, **asBitmap**, **DiskCacheStrategy** ?
Gradle throws the compile error.

**Comment by sjudd** [comment]
There's a pretty substantial set of API changes between 3.x and 4.x: http://bumptech.github.io/glide/doc/migrating.html.

It's usually straight forward to migrate, but things have definitely changed.

For what it's worth, the exception here looks like it's in TransitionDrawable more so than any of Glide's content. You may be able to fix it by removing the cross fade?

**Comment by yuejinzhao** [comment]
Thank you @sjudd 
Removing cross fade helps
