### ISSUE TITLE
Customize Loader for 4.0 But could not decode correctly

### ISSUE THREAD

**Issue by fishwjy** [bumptech/glide#2361]
Customize the data fetcher, Modeloader and AppGlideModule in GLide 4.0. But I get the failure below:
( Similar code in Glide 3.0 works very well) Attachment is my custom Loader for glide 4.0.
[CustomLoader.zip](https://github.com/bumptech/glide/files/1288477/CustomLoader.zip)

```
09-09 00:08:07.967 3983-6577/gov.police.deyang.oplatform D/skia: --- SkImageDecoder::Factory returned null
09-09 00:08:07.967 3983-6577/gov.police.deyang.oplatform D/skia: --- SkImageDecoder::Factory returned null
09-09 00:08:07.968 3983-6577/gov.police.deyang.oplatform D/skia: --- SkImageDecoder::Factory returned null
09-09 00:08:07.968 3983-6577/gov.police.deyang.oplatform D/skia: --- SkImageDecoder::Factory returned null
09-09 00:08:07.970 3983-6577/gov.police.deyang.oplatform D/skia: --- SkImageDecoder::Factory returned null
09-09 00:08:07.970 3983-6577/gov.police.deyang.oplatform D/skia: --- SkImageDecoder::Factory returned null
09-09 00:08:07.970 3983-6577/gov.police.deyang.oplatform D/skia: --- SkImageDecoder::Factory returned null
09-09 00:08:07.971 3983-6577/gov.police.deyang.oplatform D/skia: --- SkImageDecoder::Factory returned null
09-09 00:08:08.008 3983-3983/gov.police.deyang.oplatform W/Glide: Load failed for http://7.124.70.7:8080/file/download?filekey=4028d8815e337ca4015e4bf6a0120671 with size [275x275]
                                                                  class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                                    Cause (1 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, REMOTE, http://7.124.70.7:8080/file/download?filekey=4028d8815e337ca4015e4bf6a0120671
                                                                      Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
                                                                      Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
                                                                      Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
                                                                    Cause (2 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, REMOTE, http://7.124.70.7:8080/file/download?filekey=4028d8815e337ca4015e4bf6a0120671
                                                                      Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
                                                                      Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
                                                                      Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
                                                                    Cause (3 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, REMOTE, http://7.124.70.7:8080/file/download?filekey=4028d8815e337ca4015e4bf6a0120671
                                                                      Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
                                                                      Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
                                                                    Cause (4 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, REMOTE, http://7.124.70.7:8080/file/download?filekey=4028d8815e337ca4015e4bf6a0120671
                                                                      Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
                                                                      Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
                                                                      Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
                                                                    Cause (5 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, REMOTE, http://7.124.70.7:8080/file/download?filekey=4028d8815e337ca4015e4bf6a0120671
                                                                      Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
                                                                      Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
                                                                      Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
                                                                    Cause (6 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, REMOTE, http://7.124.70.7:8080/file/download?filekey=4028d8815e337ca4015e4bf6a0120671
                                                                      Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
                                                                      Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
09-09 00:08:08.008 3983-3983/gov.police.deyang.oplatform E/Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
```

**Glide Version**:
```groovy
    compile 'com.github.bumptech.glide:glide:4.0.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0'**
```

**Integration libraries**:
OkHttp

**Device/Android Version**:
XiaomiNote Android 6.0

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
 RequestOptions options = new RequestOptions();
        options.centerCrop()
                .placeholder(R.drawable.bg_load)
                .error(R.drawable.bg_load_fail);

        Glide.with(holder.itemView.getContext())
//                .using(new OPLoader(holder.itemView.getContext()))
                .load(new GlideUrl(String.format(URL_DOWNLOAD, chatImg.getFile().getId())))
//                .centerCrop()
//                .placeholder(R.drawable.bg_load)
//                .error(R.drawable.bg_load_fail)
                .apply(options)
                .into(holder.iv_img);
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
09-09 00:08:07.967 3983-6577/gov.police.deyang.oplatform D/skia: --- SkImageDecoder::Factory returned null
09-09 00:08:07.967 3983-6577/gov.police.deyang.oplatform D/skia: --- SkImageDecoder::Factory returned null
09-09 00:08:07.968 3983-6577/gov.police.deyang.oplatform D/skia: --- SkImageDecoder::Factory returned null
09-09 00:08:07.968 3983-6577/gov.police.deyang.oplatform D/skia: --- SkImageDecoder::Factory returned null
09-09 00:08:07.970 3983-6577/gov.police.deyang.oplatform D/skia: --- SkImageDecoder::Factory returned null
09-09 00:08:07.970 3983-6577/gov.police.deyang.oplatform D/skia: --- SkImageDecoder::Factory returned null
09-09 00:08:07.970 3983-6577/gov.police.deyang.oplatform D/skia: --- SkImageDecoder::Factory returned null
09-09 00:08:07.971 3983-6577/gov.police.deyang.oplatform D/skia: --- SkImageDecoder::Factory returned null
09-09 00:08:08.008 3983-3983/gov.police.deyang.oplatform W/Glide: Load failed for http://7.124.70.7:8080/file/download?filekey=4028d8815e337ca4015e4bf6a0120671 with size [275x275]
                                                                  class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                                    Cause (1 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, REMOTE, http://7.124.70.7:8080/file/download?filekey=4028d8815e337ca4015e4bf6a0120671
                                                                      Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
                                                                      Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
                                                                      Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
                                                                    Cause (2 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, REMOTE, http://7.124.70.7:8080/file/download?filekey=4028d8815e337ca4015e4bf6a0120671
                                                                      Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
                                                                      Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
                                                                      Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
                                                                    Cause (3 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, REMOTE, http://7.124.70.7:8080/file/download?filekey=4028d8815e337ca4015e4bf6a0120671
                                                                      Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
                                                                      Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
                                                                    Cause (4 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, REMOTE, http://7.124.70.7:8080/file/download?filekey=4028d8815e337ca4015e4bf6a0120671
                                                                      Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
                                                                      Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
                                                                      Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
                                                                    Cause (5 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, REMOTE, http://7.124.70.7:8080/file/download?filekey=4028d8815e337ca4015e4bf6a0120671
                                                                      Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
                                                                      Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
                                                                      Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
                                                                    Cause (6 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, REMOTE, http://7.124.70.7:8080/file/download?filekey=4028d8815e337ca4015e4bf6a0120671
                                                                      Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
                                                                      Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
09-09 00:08:08.008 3983-3983/gov.police.deyang.oplatform E/Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
```

**Comment by sjudd** [comment]
It looks like the image that's saved to Glide's disk cache is invalid in some way. 

Does it work if you use ``DiskCacheStrategy.RESOURCE``? That shouldn't be necessary but Glide v4 did change the default disk cache strategy so remote images are written to the disk cache and then decoded from the disk cache, rather than being decoded from the source stream directly.

Have you verified that the images you're downloading are otherwise valid? If you pull one from Glide's cache directory, are you able to load it with BitmapFactory if you pass it in as a File path or stream?

**Comment by fishwjy** [comment]
Yes, It works after I use **DiskCacheStrategy.RESOURCE**. And I tried other strategies. All that caching first strategy will be failed. Only decoding first then caching local disk will be successful. That's strange. Would you tell me why? Thanks a lot.

**Comment by sjudd** [comment]
``RESOURCE`` uses a slightly different code path, so it's a way of narrowing down what might be broken.

Does it work if you try Glide ``v4.1.1`` with [``DiskCacheStrategy.AUTOMATIC``][1] (or none set)? If so, it might have been fixed here: 1594655d9c256e52f7ac829bba5fafb926d001c0 

[1]: https://github.com/bumptech/glide/blob/a4af922db56c928a56bcb8bfc7651e32fe10fd10/library/src/main/java/com/bumptech/glide/load/engine/DiskCacheStrategy.java#L123

**Comment by fishwjy** [comment]
There are some IDE error when I try to compile the 4.1.1, but I think it's not the error of glide.
It seems it's necessary of android annotation 26.0.2, but in my IDE, the latest version is 26.0.1. Any opinions for that?
[Some_IDE_ERR_not_related_with_glide.zip](https://github.com/bumptech/glide/files/1291173/Some_IDE_ERR_not_related_with_glide.zip)

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/download-setup.html#gradle, in particular:

```
repositories {
  mavenCentral()
  maven { url 'https://maven.google.com' }
}
```

**Comment by fishwjy** [comment]
This is test result in 4.1.1:

DiskCacheStrategy.AUTOMATIC: Failed
DiskCacheStrategy.ALL: Failed
DiskCacheStrategy.DATA: Failed

DiskCacheStrategy.RESOURCE: Successful
DiskCacheStrategy.NONE: Successful

**Comment by sjudd** [comment]
Is the content length header you receive greater than the number of bytes you receive when you download one of these images?

**Comment by sjudd** [comment]
One way to test what I asked is to remove the ContentLengthInputStream wrapper in your DataFetcher and see if that works.

**Comment by fishwjy** [comment]
Still failed.

I remove wrapper in my DataFetcher like below: 
`@Override
            public void onResponse(Call call, Response response) throws IOException {
                responseBody = response.body();
                if (response.isSuccessful()) {
//                    long contentLength = responseBody.contentLength();
//                    stream = ContentLengthInputStream.obtain(responseBody.byteStream(), contentLength);
                    stream = responseBody.byteStream();
                    callback.onDataReady(stream);
                } else {
                    callback.onLoadFailed(new HttpException(response.message(), response.code()));
                }
            }`

and load like this below:
`RequestOptions options = new RequestOptions();
        options.centerCrop()
//                .diskCacheStrategy(DiskCacheStrategy.RESOURCE)
                .placeholder(R.drawable.bg_load)
                .error(R.drawable.bg_load_fail);

        Glide.with(holder.itemView.getContext())
                .load(new GlideUrl(String.format(URL_DOWNLOAD, chatImg.getFile().getId())))
                .apply(options)
                .into(holder.iv_img);`

**Comment by liufsd** [comment]
+1
```
  09-14 15:57:27.645 25121-26693/com.hujiang.cctalk E/GlideExecutor: Request threw uncaught throwable
                                                                   java.lang.IllegalArgumentException: Fetchers don't match!, old: com.bumptech.glide.load.model.FileLoader$FileFetcher@269c249b new: com.bumptech.glide.load.model.FileLoader$FileFetcher@5d24812
                                                                       at com.bumptech.glide.util.Preconditions.checkArgument(Preconditions.java:17)
                                                                       at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:245)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:831)
                                                                       at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)
09-14 15:57:27.650 25121-25121/com.hujiang.cctalk W/Glide: Load failed for https://f1gr.hjfile.cn/pic/20170907/201709070541281607.gif with size [-2147483648x-2147483648]
                                                           class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                             Cause (1 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, DATA_DISK_CACHE, https://f1gr.hjfile.cn/pic/20170907/201709070541281607.gif
                                                               Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
                                                               Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
                                                               Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
                                                             Cause (2 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, DATA_DISK_CACHE, https://f1gr.hjfile.cn/pic/20170907/201709070541281607.gif
                                                               Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
                                                               Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
                                                               Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
                                                             Cause (3 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, DATA_DISK_CACHE, https://f1gr.hjfile.cn/pic/20170907/201709070541281607.gif
                                                               Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
                                                               Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
                                                             Cause (4 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, REMOTE, https://f1gr.hjfile.cn/pic/20170907/201709070541281607.gif
                                                               Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
                                                               Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
                                                               Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
                                                             Cause (5 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, REMOTE, https://f1gr.hjfile.cn/pic/20170907/201709070541281607.gif
                                                               Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
                                                               Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
                                                               Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
                                                             Cause (6 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, REMOTE, https://f1gr.hjfile.cn/pic/20170907/201709070541281607.gif
                                                               Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
                                                               Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
09-14 15:57:28.935 4242-4483/? W/WifiProJNI: poll before: pipefd=201
09-14 15:57:28.935 4242-4483/? W/WifiProJNI: poll before: pipefd=201
09-14 15:57:28.935 4242-4484/? W/HuaweiWifiWatchdogStateMachine: OTA TCP Rssi bad, current: false, false, false; rsth:-75
09-14 15:57:29.935 4858-4858/? E/MY_TAG: plugged changed1505375849939

```

**Comment by liufsd** [comment]
but, i have test demo project. it will show success .
why ?

**Comment by sjudd** [comment]
Oh, if you're using a disk cache strategy other than NONE, make sure you clear the cache in your application before trying agin (or uninstall and re-install). You should do this when you're experimenting with a new fetcher.

It's possible that an earlier version of your fetcher wrote broken data to Glide's disk cache, which you're then decoding each time you request the same image. Clearing the application cache each time you change your fetcher ensures that you're only using new data from your updated implementation.

**Comment by liufsd** [comment]
thanks.
