### ISSUE TITLE
No virtual method isManifestParsingEnabled()Z

### ISSUE THREAD

**Issue by zhangkehu** [bumptech/glide#2378]
```
09-12 15:19:14.659 31756-31756/com.view.asim.enterprise E/CrashReport: #++++++++++Record By Bugly++++++++++#
09-12 15:19:14.659 31756-31756/com.view.asim.enterprise E/CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
09-12 15:19:14.659 31756-31756/com.view.asim.enterprise E/CrashReport: # PKG NAME: com.view.asim.enterprise
09-12 15:19:14.659 31756-31756/com.view.asim.enterprise E/CrashReport: # APP VER: 1.9.14.170901
09-12 15:19:14.660 31756-31756/com.view.asim.enterprise E/CrashReport: # LAUNCH TIME: 2017-09-12 15:18:48
09-12 15:19:14.660 31756-31756/com.view.asim.enterprise E/CrashReport: # CRASH TYPE: JAVA_CRASH
09-12 15:19:14.660 31756-31756/com.view.asim.enterprise E/CrashReport: # CRASH TIME: 2017-09-12 15:19:14
09-12 15:19:14.660 31756-31756/com.view.asim.enterprise E/CrashReport: # CRASH PROCESS: com.view.asim.enterprise
09-12 15:19:14.660 31756-31756/com.view.asim.enterprise E/CrashReport: # CRASH THREAD: main
09-12 15:19:14.660 31756-31756/com.view.asim.enterprise E/CrashReport: # REPORT ID: 9b58dfa7-b666-4966-b4df-b0b9dd462cad
09-12 15:19:14.660 31756-31756/com.view.asim.enterprise E/CrashReport: # CRASH DEVICE: EVA-AL00 UNROOT
09-12 15:19:14.660 31756-31756/com.view.asim.enterprise E/CrashReport: # RUNTIME AVAIL RAM:1422450688 ROM:19491528704 SD:19470557184
09-12 15:19:14.661 31756-31756/com.view.asim.enterprise E/CrashReport: # RUNTIME TOTAL RAM:2915516416 ROM:26933706752 SD:26912735232
09-12 15:19:14.661 31756-31756/com.view.asim.enterprise E/CrashReport: # CRASH STACK: 
09-12 15:19:14.661 31756-31756/com.view.asim.enterprise E/CrashReport: java.lang.NoSuchMethodError: No virtual method isManifestParsingEnabled()Z in class Lcom/view/asim/model/AKGlideModule; or its super classes (declaration of 'com.view.asim.model.AKGlideModule' appears in /data/app/com.view.asim.enterprise-2/base.apk:classes38.dex)
                                                                           at com.bumptech.glide.GeneratedAppGlideModuleImpl.isManifestParsingEnabled(GeneratedAppGlideModuleImpl.java:38)
                                                                           at com.bumptech.glide.Glide.initializeGlide(Glide.java:192)
                                                                           at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:172)
                                                                           at com.bumptech.glide.Glide.get(Glide.java:156)
                                                                           at com.bumptech.glide.Glide.getRetriever(Glide.java:535)
                                                                           at com.bumptech.glide.Glide.with(Glide.java:561)
                                                                           at com.view.asim.manager.AvatarManager.displayUserAvatar(AvatarManager.java:138)
                                                                           at com.view.asim.activity.MainActivity.refreshMyInfoView(MainActivity.java:1567)
                                                                           at com.view.asim.activity.MainActivity.inflateSlidingMenu(MainActivity.java:639)
                                                                           at com.view.asim.activity.MainActivity.onResume(MainActivity.java:362)
                                                                           at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1279)
                                                                           at android.app.Activity.performResume(Activity.java:7017)
                                                                           at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3561)
                                                                           at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3626)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2876)
                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:156)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
09-12 15:19:14.661 31756-31756/com.view.asim.enterprise E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#
09-12 15:19:17.185 31756-31756/com.view.asim.enterprise E/CrashReport: sys default last handle start!
                                                                       
                                                                       --------- beginning of crash
09-12 15:19:17.185 31756-31756/com.view.asim.enterprise E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.view.asim.enterprise, PID: 31756
                                                                          java.lang.NoSuchMethodError: No virtual method isManifestParsingEnabled()Z in class Lcom/view/asim/model/AKGlideModule; or its super classes (declaration of 'com.view.asim.model.AKGlideModule' appears in /data/app/com.view.asim.enterprise-2/base.apk:classes38.dex)
                                                                              at com.bumptech.glide.GeneratedAppGlideModuleImpl.isManifestParsingEnabled(GeneratedAppGlideModuleImpl.java:38)
                                                                              at com.bumptech.glide.Glide.initializeGlide(Glide.java:192)
                                                                              at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:172)
                                                                              at com.bumptech.glide.Glide.get(Glide.java:156)
                                                                              at com.bumptech.glide.Glide.getRetriever(Glide.java:535)
                                                                              at com.bumptech.glide.Glide.with(Glide.java:561)
                                                                              at com.view.asim.manager.AvatarManager.displayUserAvatar(AvatarManager.java:138)
                                                                              at com.view.asim.activity.MainActivity.refreshMyInfoView(MainActivity.java:1567)
                                                                              at com.view.asim.activity.MainActivity.inflateSlidingMenu(MainActivity.java:639)
                                                                              at com.view.asim.activity.MainActivity.onResume(MainActivity.java:362)
                                                                              at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1279)
                                                                              at android.app.Activity.performResume(Activity.java:7017)
                                                                              at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3561)
                                                                              at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3626)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2876)
                                                                              at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:156)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
09-12 15:19:18.629 32442-32470/com.view.asim.enterprise E/CrashReport: --------------------------------------------------------------------------------------------
09-12 15:19:18.629 32442-32470/com.view.asim.enterprise E/CrashReport: --------------------------------------------------------------------------------------------
```

**Comment by TWiStErRob** [comment]
Also include relevant Gradle depedencies (there may be something that is transitively pulling in an old Glide version).
