### ISSUE TITLE
Bug: SVG sample crashes

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [bumptech/glide#2434]
Tested on Nexus 5x with Android O.

This is what I get in logs:
```
09-26 16:12:46.111 3298-5922/? E/NetworkScheduler.ATC: Unable to resolve correct action against com.google.android.apps.walletnfcrel/com.google.commerce.tapandpay.android.clientconfig.sync.ClientConfigSyncService for user #0 to instantiate callback. Not executing task.
09-26 16:12:48.469 14340-14347/? E/zygote64: Failed sending reply to debugger: Broken pipe
09-26 16:12:48.870 14340-14340/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.bumptech.glide.samples.svg, PID: 14340
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bumptech.glide.samples.svg/com.bumptech.glide.samples.svg.MainActivity}: android.content.res.Resources$NotFoundException: Drawable com.bumptech.glide.samples.svg:drawable/image_loading with resource ID #0x7f020002
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                       at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                    Caused by: android.content.res.Resources$NotFoundException: Drawable com.bumptech.glide.samples.svg:drawable/image_loading with resource ID #0x7f020002
                                                    Caused by: android.content.res.Resources$NotFoundException: File res/drawable/image_loading.xml from drawable resource ID #0x7f020002
                                                       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:768)
                                                       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:600)
                                                       at android.content.res.Resources.getDrawableForDensity(Resources.java:876)
                                                       at android.content.res.Resources.getDrawable(Resources.java:818)
                                                       at android.support.v4.content.res.ResourcesCompat.getDrawable(ResourcesCompat.java:76)
                                                       at com.bumptech.glide.request.SingleRequest.loadDrawableBase(SingleRequest.java:406)
                                                       at com.bumptech.glide.request.SingleRequest.loadDrawableV7(SingleRequest.java:400)
                                                       at com.bumptech.glide.request.SingleRequest.loadDrawable(SingleRequest.java:385)
                                                       at com.bumptech.glide.request.SingleRequest.getPlaceholderDrawable(SingleRequest.java:367)
                                                       at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:250)
                                                       at com.bumptech.glide.manager.RequestTracker.resumeRequests(RequestTracker.java:95)
                                                       at com.bumptech.glide.RequestManager.resumeRequests(RequestManager.java:234)
                                                       at com.bumptech.glide.RequestManager.onStart(RequestManager.java:257)
                                                       at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStart(ActivityFragmentLifecycle.java:50)
                                                       at com.bumptech.glide.manager.RequestManagerFragment.onStart(RequestManagerFragment.java:185)
                                                       at android.app.Fragment.performStart(Fragment.java:2637)
                                                       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1312)
                                                       at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1549)
                                                       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1611)
                                                       at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3039)
                                                       at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2996)
                                                       at android.app.FragmentController.dispatchStart(FragmentController.java:189)
                                                       at android.app.Activity.performStart(Activity.java:6998)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2780)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                       at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                    Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #4: <bitmap> requires a valid 'src' attribute
                                                       at android.graphics.drawable.BitmapDrawable.updateStateFromTypedArray(BitmapDrawable.java:823)
09-26 16:12:48.871 14340-14340/? E/AndroidRuntime:     at android.graphics.drawable.BitmapDrawable.inflate(BitmapDrawable.java:754)
                                                       at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)
                                                       at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1295)
                                                       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1284)
                                                       at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:279)
                                                       at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:194)
                                                       at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)
                                                       at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1295)
                                                       at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1254)
                                                       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:758)
                                                       	... 32 more
```

**Comment by AndroidDeveloperLB** [comment]
Thanks. Seems to work well now.
Where may I ask questions about this library?

**Comment by AndroidDeveloperLB** [comment]
Also, when running the SVG sample, I noticed this issue:

![image](https://user-images.githubusercontent.com/5357526/30900316-498485fe-a36c-11e7-9646-450f807019e7.png)

It stays on this state. How come?
