### ISSUE TITLE
Crash in RequestManager

### ISSUE THREAD

**Issue by Tolriq** [bumptech/glide#2436]
**Glide Version**: 4.1.1

**Integration libraries**:

**Device/Android Version**: Android 4

**Issue details / Repro steps / Use case background**: 

**Stack trace / LogCat**:
```ruby
Fatal Exception: java.lang.RuntimeException: Unable to stop activity {xxxxActivity}: java.lang.ArithmeticException: divide by zero
       at android.app.ActivityThread.handleSleeping(ActivityThread.java:3640)
       at android.app.ActivityThread.access$3100(ActivityThread.java:172)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1501)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5653)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.ArithmeticException: divide by zero
       at com.bumptech.glide.RequestManager.onStop(RequestManager.java:269)
       at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStop(ActivityFragmentLifecycle.java:57)
       at com.bumptech.glide.manager.SupportRequestManagerFragment.onStop(SupportRequestManagerFragment.java:181)
       at android.support.v4.app.FragmentManagerImpl.android.support.v4.app.Fragment.performStop(FragmentManager.java:16541)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3217)
       at android.support.v4.app.FragmentManagerImpl.dispatchStop(FragmentManager.java:3194)
       at android.support.v4.app.FragmentManagerImpl.android.support.v4.app.Fragment.performStop(FragmentManager.java:16537)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3217)
       at android.support.v4.app.FragmentManagerImpl.dispatchStop(FragmentManager.java:3194)
       at android.support.v4.app.FragmentActivity.android.support.v4.app.FragmentController.dispatchStop(FragmentActivity.java:20236)
       at android.support.v7.app.AppCompatActivity.onStop(AppCompatActivity.java:183)
       at xxxActivity.onStop(BaseActivity.java:161)
       at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1218)
       at android.app.Activity.performStop(Activity.java:5686)
       at android.app.ActivityThread.handleSleeping(ActivityThread.java:3637)
       at android.app.ActivityThread.access$3100(ActivityThread.java:172)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1501)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5653)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by sjudd** [comment]
It looks like some of the stack trace is missing? I'd expect there to be a call into ``RequestTracker``.

**Comment by Tolriq** [comment]
Proguard inlining :( Only got 1 report on Crashlytics.

**Comment by sjudd** [comment]
I'm going to close this for now. I can't even find anywhere that seems like we'd be dividing by 0 in onStop. Let me know if you keep seeing this or get a better stack trace :/

**Comment by TWiStErRob** [comment]
I checked as well, there are no easily relateable [divisions (in the whole library)](https://github.com/bumptech/glide/files/1364634/divisions.txt) to `onStop` (removed any divisions by constants from that list).

@Tolriq, can you privately send me the APK that caused this + the original non-retraced stack trace between `AppCompatActivity.onStop(AppCompatActivity.java:183)` and `RequestManager.onStop(RequestManager.java:269)`) I would be curious to decompile and see what ProGuard has done to Glide internals?
