### ISSUE TITLE
bug: clearDiskCache()在缓存文件不存在下调用会导致无法加载图片

### ISSUE THREAD

**Issue by yxcSini** [bumptech/glide#2464]
手动将diskcache缓存文件夹删除后，再调用clearDiskCahce()方法会导致设置DiskCacheStrategy.ALL的Glide无法加载图片

步骤：
1.进入系统设置-应用，删除该应用的缓存数据
2.调用GlideApp.get(this).clearDiskCache();
报错日志：
`W/DiskLruCacheWrapper: Unable to clear disk cache
                                                                                java.io.IOException: not a readable directory: /data/data/com.paisheng.example.pslib/cache/image_manager_disk_cache
                                                                                    at com.bumptech.glide.disklrucache.Util.deleteContents(Util.java:55)
                                                                                    at com.bumptech.glide.disklrucache.DiskLruCache.delete(DiskLruCache.java:660)
                                                                                    at com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper.clear(DiskLruCacheWrapper.java:143)
                                                                                    at com.bumptech.glide.load.engine.Engine.clearDiskCache(Engine.java:326)
                                                                                    at com.bumptech.glide.Glide.clearDiskCache(Glide.java:498)`
3.使用GlideApp加载图片
报错日志：
`E/GlideExecutor: Request threw uncaught throwable
                                                                          java.lang.IllegalStateException: cache is closed
                                                                              at com.bumptech.glide.disklrucache.DiskLruCache.checkNotClosed(DiskLruCache.java:620)
                                                                              at com.bumptech.glide.disklrucache.DiskLruCache.get(DiskLruCache.java:409)
                                                                              at com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper.get(DiskLruCacheWrapper.java:75)
                                                                              at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:62)
                                                                              at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:293)
                                                                              at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:260)
                                                                              at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                              at java.lang.Thread.run(Thread.java:841)
                                                                              at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:386)`

**Comment by SelenaWong** [comment]
I meet the same error.

**Comment by yxcSini** [comment]
@SelenaWong Update your Glide's version
