### ISSUE TITLE
Unable to manage OutOfMemoryError exception

### ISSUE THREAD

**Issue by perracolabs** [bumptech/glide#2470]
I’m performing a memory stress test where our software is executed in a very low memory scenario.

An OutOfMemoryError exception is expected to happen under such stress test so we can identify such exception occurrences, and manage the scenario accordingly.
  
Under such stress test Glide is throwing an uncaught exception which I don’t know how and where to catch to manage it, which makes it impossible to do some cleanup or at least to close the app gracefully.

**Glide Version**: 4.2.0

**Stack trace / LogCat**:
```
 GlideExecutor: Request threw uncaught throwable
	   java.lang.NullPointerException: Tried to decrement empty size, size: 1048576, this: com.bumptech.glide.load.engine.bitmap_recycle.LruArrayPool@6024dd8
		   at com.bumptech.glide.load.engine.bitmap_recycle.LruArrayPool.decrementArrayOfSize(LruArrayPool.java:151)
		   at com.bumptech.glide.load.engine.bitmap_recycle.LruArrayPool.evictToSize(LruArrayPool.java:140)
		   at com.bumptech.glide.load.engine.bitmap_recycle.LruArrayPool.evict(LruArrayPool.java:131)
		   at com.bumptech.glide.load.engine.bitmap_recycle.LruArrayPool.put(LruArrayPool.java:65)
		   at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.release(RecyclableBufferedInputStream.java:113)
		   at com.bumptech.glide.load.data.InputStreamRewinder.cleanup(InputStreamRewinder.java:31)
		   at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:492)
		   at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:461)
		   at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:447)
		   at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:401)
		   at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:370)
		   at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
		   at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:49)
		   at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
		   at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:293)
		   at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:260)
		   at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
		   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
		   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
		   at java.lang.Thread.run(Thread.java:761)
		   at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:386)
```

-----------------
```
E/GlideExecutor: Request threw uncaught throwable
 java.lang.OutOfMemoryError: Failed to allocate a 5242892 byte allocation with 605912 free bytes and 591KB until OOM
	 at com.bumptech.glide.load.engine.bitmap_recycle.ByteArrayAdapter.newArray(ByteArrayAdapter.java:22)
	 at com.bumptech.glide.load.engine.bitmap_recycle.ByteArrayAdapter.newArray(ByteArrayAdapter.java:6)
	 at com.bumptech.glide.load.engine.bitmap_recycle.LruArrayPool.get(LruArrayPool.java:92)
	 at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:163)
	 at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:309)
	 at java.io.FilterInputStream.read(FilterInputStream.java:107)
	 at com.bumptech.glide.load.resource.gif.StreamGifDecoder.inputStreamToBytes(StreamGifDecoder.java:67)
	 at com.bumptech.glide.load.resource.gif.StreamGifDecoder.decode(StreamGifDecoder.java:53)
	 at com.bumptech.glide.load.resource.gif.StreamGifDecoder.decode(StreamGifDecoder.java:23)
	 at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67)
	 at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52)
	 at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43)
	 at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
	 at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
	 at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:489)
	 at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:461)
	 at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:447)
	 at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:401)
	 at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:370)
	 at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
	 at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:49)
	 at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
	 at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:293)
	 at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:409)
	 at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:370)
	 at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
	 at com.bumptech.glide.load.data.mediastore.ThumbFetcher.loadData(ThumbFetcher.java:67)
	 at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
	 at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:293)
	 at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:260)
	 at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	 at java.lang.Thread.run(Thread.java:761)
	 at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:386)
```

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/doc/configuration.html#uncaughtthrowablestrategy

**Comment by sjudd** [comment]
I actually also added more robust support for this here: 74fcad1340da13ac302994873e076731ab96b8e6. So starting in Glide 4.3, OOMs should get passed through normal RequestListener/Target onError methods. 

The major problem with my pervious suggestion was actually Futures. Glide's Futures were not previously notified of failures caused by uncaught exceptions, which would cause them to block forever. That's been fixed and as part of that fix, OOMs are now passed along as Throwables.
