### ISSUE TITLE
Error from glide4.0 to 4.2.0

### ISSUE THREAD

**Issue by xiongke15117937934** [bumptech/glide#2473]
```
FATAL EXCEPTION: main
                                                                 Process: com.apkpure.aegon, PID: 9557
                                                                 java.lang.IllegalStateException: You can't start or clear loads in RequestListener or Target callbacks. If you must do so, consider posting your into() or clear() calls to the main thread using a Handler instead.
                                                                     at com.bumptech.glide.request.SingleRequest.assertNotCallingCallbacks(SingleRequest.java:279)
                                                                     at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:296)
                                                                     at com.bumptech.glide.manager.RequestTracker.clearRemoveAndRecycle(RequestTracker.java:62)
                                                                     at com.bumptech.glide.RequestManager.untrack(RequestManager.java:443)
                                                                     at com.bumptech.glide.Glide.removeFromManagers(Glide.java:651)
                                                                     at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:432)
                                                                     at com.bumptech.glide.RequestManager.clear(RequestManager.java:418)
                                                                     at com.bumptech.glide.RequestManager.clear(RequestManager.java:403)
                                                                     at com.apkpure.aegon.widgets.dialog.GalleryDialogFragment$ImagePageFragment$3.onResourceReady(GalleryDialogFragment.java:265)
                                                                     at com.apkpure.aegon.glide.GlideUtils$1.onResourceReady(GlideUtils.java:179)
                                                                     at com.apkpure.aegon.glide.GlideUtils$1.onResourceReady(GlideUtils.java:166)
                                                                     at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:555)
                                                                     at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:530)
                                                                     at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:184)
                                                                     at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:288)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
```
 compile 'com.github.bumptech.glide:glide:4.2.0'
    compile 'com.github.bumptech.glide:okhttp3-integration:4.2.0@aar'
```

**Comment by sjudd** [comment]
Yes this is intended. Please see the exception information for suggestions on how to fix this, or the behavior changes of the release notes: https://github.com/bumptech/glide/releases/tag/v4.2.0.
