### ISSUE TITLE
Glide bugs or error ?

### ISSUE THREAD

**Issue by bentahyar** [bumptech/glide#2477]
Hello, I want to ask something about an error or bug that I'm currently facing. 

I have to integrate a payment gateway from Midtrans (An Indonesian Payment Gateway), when I use the Midtrans SDK for Android, Glide ran to an error eventhough I'm not using Glide in that activity or the next one. My assumption is that Midtrans uses a lower version of Glide (I think version 4 below) and I'm using Glide v4.2.0

**Stack trace / LogCat**:
```ruby
10-12 14:31:41.596 5513-5513/com.tingtong.android E/FancyButton: Unable to find fontawesome.ttf font. Using Typeface.DEFAULT instead.
10-12 14:31:41.598 5513-5513/com.tingtong.android E/FancyButton: Unable to find robotoregular.ttf font. Using Typeface.DEFAULT instead.
10-12 14:31:41.623 5513-5513/com.tingtong.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.tingtong.android, PID: 5513
                                                                    java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/Integer;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.tingtong.android-1/base.apk)
                                                                        at com.midtrans.sdk.uikit.activities.PaymentMethodsActivity.j(Unknown Source)
                                                                        at com.midtrans.sdk.uikit.activities.PaymentMethodsActivity.f(Unknown Source)
                                                                        at com.midtrans.sdk.uikit.activities.PaymentMethodsActivity.onCreate(Unknown Source)
                                                                        at android.app.Activity.performCreate(Activity.java:6684)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6236)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```

**Comment by sjudd** [comment]
Yup, it looks like they're using v3 and you're using v4. There isn't a way to fix this aside from both of you using the same version.

**Comment by radityagumay** [comment]
@bentahyar you can exclude group glide from midtrans in gradle
