### ISSUE TITLE
Mark has been invalidated, pos: 2904 markLimit: 65536

### ISSUE THREAD

**Issue by miguoer** [bumptech/glide#2478]
Hello Sam, I got a wierd problem when I scrolled the ListView.  Wish you could help me figure this out.

Glide version: 4.0.0
Glide RequestOptions: `        options = new RequestOptions()
                .priority(Priority.HIGH)
                .centerCrop()
                .skipMemoryCache(false)
                .diskCacheStrategy(DiskCacheStrategy.NONE);`

 And My adapter has implemented ListPreloader.PreloadModelProvider<T> . The network state is well.
Error log :
```
10-12 16:58:50.693 E/Glide   (12874): class com.bumptech.glide.load.engine.GlideException: Failed to load resource
10-12 16:58:50.726 I/Glide   (12874): Root cause (1 of 2)
10-12 16:58:50.726 I/Glide   (12874): java.net.SocketTimeoutException
10-12 16:58:50.726 I/Glide   (12874): 	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:491)
10-12 16:58:50.726 I/Glide   (12874): 	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
10-12 16:58:50.726 I/Glide   (12874): 	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
10-12 16:58:50.726 I/Glide   (12874): 	at java.io.BufferedInputStream.read(BufferedInputStream.java:283)
10-12 16:58:50.726 I/Glide   (12874): 	at com.android.okhttp.internal.http.HttpTransport$FixedLengthInputStream.read(HttpTransport.java:386)
10-12 16:58:50.726 I/Glide   (12874): 	at java.io.FilterInputStream.read(FilterInputStream.java:118)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.util.ContentLengthInputStream.read(ContentLengthInputStream.java:67)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.util.ContentLengthInputStream.read(ContentLengthInputStream.java:62)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:141)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:310)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.util.ExceptionCatchingInputStream.read(ExceptionCatchingInputStream.java:85)
10-12 16:58:50.726 I/Glide   (12874): 	at java.io.FilterInputStream.read(FilterInputStream.java:118)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.util.MarkEnforcingInputStream.read(MarkEnforcingInputStream.java:45)
10-12 16:58:50.726 I/Glide   (12874): 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
10-12 16:58:50.726 I/Glide   (12874): 	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:627)
10-12 16:58:50.726 I/Glide   (12874): 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:603)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:426)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:245)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:178)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:62)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:69)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:54)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:45)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:58)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:44)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:459)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:452)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:438)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:392)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:361)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:113)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:131)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:69)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:97)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:284)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:251)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:224)
10-12 16:58:50.726 I/Glide   (12874): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-12 16:58:50.726 I/Glide   (12874): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-12 16:58:50.726 I/Glide   (12874): 	at java.lang.Thread.run(Thread.java:841)
10-12 16:58:50.726 I/Glide   (12874): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:349)
10-12 16:58:50.728 I/Glide   (12874): Root cause (2 of 2)
10-12 16:58:50.728 I/Glide   (12874): com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException: Mark has been invalidated, pos: 2904 markLimit: 65536
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.reset(RecyclableBufferedInputStream.java:350)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.data.InputStreamRewinder.rewindAndGet(InputStreamRewinder.java:26)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.data.InputStreamRewinder.rewindAndGet(InputStreamRewinder.java:13)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:66)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:54)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:45)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:58)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:44)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:459)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:452)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:438)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:392)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:361)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:113)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:131)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:69)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:97)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:284)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:251)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:224)
10-12 16:58:50.728 I/Glide   (12874): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-12 16:58:50.728 I/Glide   (12874): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-12 16:58:50.728 I/Glide   (12874): 	at java.lang.Thread.run(Thread.java:841)
10-12 16:58:50.728 I/Glide   (12874): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:349)
```

**Comment by sjudd** [comment]
It looks like network issues: ``java.net.SocketTimeoutException``. The rewind error could happen in a similar circumstance.

**Comment by miguoer** [comment]
Thanks, it seems my network circumstance is not stable.
