### ISSUE TITLE
IllegalArgumentException when using fallback with FutureTarget

### ISSUE THREAD

**Issue by moxie0** [bumptech/glide#2487]
It looks like `fallback()` and `error()` don't work with `submit()` to `FutureTarget`.

Code such as:

`````
            Uri uri = null;
            Bitmap bitmap = Glide.with(MainActivity.this)
                                 .asBitmap()
                                 .load(uri)
                                 .apply(new RequestOptions().fallback(android.R.drawable.ic_delete))
                                 .submit(500, 500)
                                 .get();
`````

Will always throw:

`````
10-15 16:39:43.627 25771 25826 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
10-15 16:39:43.627 25771 25826 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
10-15 16:39:43.627 25771 25826 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
10-15 16:39:43.627 25771 25826 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
10-15 16:39:43.627 25771 25826 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
10-15 16:39:43.627 25771 25826 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
10-15 16:39:43.627 25771 25826 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-15 16:39:43.627 25771 25826 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-15 16:39:43.627 25771 25826 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
10-15 16:39:43.627 25771 25826 E AndroidRuntime: Caused by: java.lang.AssertionError: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Load failed
10-15 16:39:43.627 25771 25826 E AndroidRuntime: 	at org.moxie.glitchycorners.MainActivity$1.doInBackground(MainActivity.java:45)
10-15 16:39:43.627 25771 25826 E AndroidRuntime: 	at org.moxie.glitchycorners.MainActivity$1.doInBackground(MainActivity.java:28)
10-15 16:39:43.627 25771 25826 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-15 16:39:43.627 25771 25826 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-15 16:39:43.627 25771 25826 E AndroidRuntime: 	... 4 more
10-15 16:39:43.627 25771 25826 E AndroidRuntime: Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Load failed
10-15 16:39:43.627 25771 25826 E AndroidRuntime: 	at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:206)
10-15 16:39:43.627 25771 25826 E AndroidRuntime: 	at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:108)
10-15 16:39:43.627 25771 25826 E AndroidRuntime: 	at org.moxie.glitchycorners.MainActivity$1.doInBackground(MainActivity.java:39)
10-15 16:39:43.627 25771 25826 E AndroidRuntime: 	... 7 more
10-15 16:39:43.627 25771 25826 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Load failed
10-15 16:39:43.627 25771 25826 E AndroidRuntime: 	... 10 more
`````

Same code works fine with `into()` an `ImageView` instead.

I'm not sure whether this is *supposed* to work or not, but I think it'd be nice if it did, since then it'd be possible to reuse the same Glide fallback logic for situations where a controller needs to load a Bitmap (like for notifications) rather than having Glide talk to a view directly.

**Glide Version**: 4.2.0

**Comment by sjudd** [comment]
It has to fail, otherwise you'd never be able to tell the difference between a successful load and a failed load on a background thread. We could special case null models again I guess, but it's pretty easy to just call ``context.getDrawable()`` (or ``context.getResources().getDrawable``) in the required catch block right? Just less elegant?

**Comment by moxie0** [comment]
It feels a little inconsistent to me. If I'm specifying a "fallback," I don't feel like I'm asking to know when a load fails, just the same as if I were making the same call with a View as a target.

Catching the exception would feel pretty iffy to me, since a runtime exception like `IllegalStateException` doesn't seem like something I should be handling.

In my case I could use an `if` condition to explicitly check for null and load the fallback instead, but it's just slightly less convenient and inconsistent with everywhere else I use the API.

Feel free to close this if it's the intended behavior, thanks for the response.

**Comment by sjudd** [comment]
Future requires you to catch any ExecutionException when you call get(): https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Future.html#get(). 

Otherwise I see your point I'll think about it, thanks for brining this up.
