### ISSUE TITLE
ContextCompat.checkSelfPermission(context, NETWORK_PERMISSION) has crash 

### ISSUE THREAD

**Issue by pizi6** [bumptech/glide#2528]
**Glide Version**:4.2.0

**Integration libraries**:

**Device/Android Version**: api 22

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
java.lang.NoSuchMethodError: No static method checkSelfPermission(Landroid/content/Context;Ljava/lang/String;)I in class Landroid/support/v4/content/ContextCompat; or its super classes (declaration of 'android.support.v4.content.ContextCompat' appears in /data/app/com.dev.hangoutist-1/split_lib_dependencies_apk.apk)
                                                                        at com.bumptech.glide.manager.DefaultConnectivityMonitorFactory.build(DefaultConnectivityMonitorFactory.java:21)
                                                                        at com.bumptech.glide.RequestManager.<init>(RequestManager.java:89)
                                                                        at com.bumptech.glide.RequestManager.<init>(RequestManager.java:70)
                                                                        at com.bumptech.glide.manager.RequestManagerRetriever$1.build(RequestManagerRetriever.java:416)
                                                                        at com.bumptech.glide.manager.RequestManagerRetriever.supportFragmentGet(RequestManagerRetriever.java:372)
                                                                        at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:125)
                                                                        at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:108)
                                                                        at com.bumptech.glide.Glide.with(Glide.java:566)
```

**Comment by sjudd** [comment]
Does including the following in your build.gradle file solve the issue?

compile "com.android.support:support-v4:26.0.2"

**Comment by sjudd** [comment]
I'm not able to reproduce this locally. If you can attach a sample app or try my suggestion above, I'd appreciate it.
