### ISSUE TITLE
The picture cannot be loaded

### ISSUE THREAD

**Issue by MuFe** [bumptech/glide#2538]
**Glide Version**:4.2.0

**Integration libraries**:com.github.bumptech.glide:okhttp3-integration:4.2.0'

**Device/Android Version**:6.0.1

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
 String url = data.getUrl();
        String[] urls = url.split("\\?");
        if (urls.length > 1) {
            url = urls[0];
        }
        GlideRequest request=GlideApp.with(imageView).asDrawable();
        if (isloadOrginal) {
            request.error(R.drawable.img_load_error);
        }
        request.transforms(new RotateTransformation(data.getRoate()), new FitCenter())
                .placeholder(R.drawable.img_loading);
        request.listener(new OrginalListener(face, data));
        if (!isloadOrginal) {
            request.thumbnail(GlideApp.with(imageView)
                    .load(data.getUrl())
                    .transforms(new RotateTransformation(data.getRoate()), new FitCenter())
                    .placeholder(R.drawable.img_loading)
                    .error(R.drawable.img_load_error)
                    .centerCrop()
            );
            request.onlyRetrieveFromCache(true);
        }
        request.load(url).into(imageView);
```
The code above is used to load pictures，First load thumbnail, and then download the original if there is a download。
It's normal to load pictures at the beginning，
When I click repeatedly to view the larger picture, the picture cannot be loaded。
Some problems have been discovered through debug。
Thumbnails will be loaded using SingleRequest，and in the onSizeReady method, I found that loadStatus was always null。
Because in the Engine class, the 184th row EngineJob<? > current = jobs.get (key); current is not null。
Finally, I found that there was a problem with the onDataFetcherReady method in the DecodeJob class。
The decodeFromRetrievedData method calls the decodeFromData method, but the decodeFromData method does not return a value, so the decodeFromRetrievedData method will not continue, leading to the DecodeJob has been in a state of decoding。
![image](https://user-images.githubusercontent.com/8475257/32225227-650815be-be12-11e7-9109-db3fd61eeb21.png)
![image](https://user-images.githubusercontent.com/8475257/32225259-8359e61e-be12-11e7-9c82-cbd141302b87.png)
![image](https://user-images.githubusercontent.com/8475257/32225289-a0236f0e-be12-11e7-94f0-e526e2e43f70.png)

so the decodeFromFetcher method has no return value。

But I don't know if I have a problem with the loading settings, or is this a Glide logical bug, hoping to get your answer?

**Comment by sjudd** [comment]
> Thumbnails will be loaded using SingleRequest，and in the onSizeReady method, I found that loadStatus was always null。

This is expected. The load isn't started until we get a size from the ``Target``.

> Because in the Engine class, the 184th row EngineJob<? > current = jobs.get (key); current is not null。

This means that Glide has found an equivalent load and will wait for that one to finish rather than starting a second identical request.

> Finally, I found that there was a problem with the onDataFetcherReady method in the DecodeJob class。

This just mean that your request has failed. See http://bumptech.github.io/glide/doc/debugging.html#local-logs. The exception will typically have more data, though in some cases when decoders return null Glide isn't very specific about why the load failed.

**Comment by MuFe** [comment]
I found this through debug

1-01 10:32:39.026 14101-15194/com.eeark.memory E/GlideExecutor: Request threw uncaught throwable
                                                                 java.lang.OutOfMemoryError: Failed to allocate a 18391740 byte allocation with 11596344 free bytes and 11MB until OOM
                                                                     at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                     at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                     at android.graphics.Bitmap.createBitmap(Bitmap.java:975)
                                                                     at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
                                                                     at android.graphics.Bitmap.createBitmap(Bitmap.java:913)
                                                                     at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.getDirty(LruBitmapPool.java:140)
                                                                     at com.bumptech.glide.load.resource.bitmap.Downsampler.setInBitmap(Downsampler.java:669)
                                                                     at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:298)
                                                                     at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:209)
                                                                     at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:162)
                                                                     at com.bumptech.glide.load.resource.bitmap.ByteBufferBitmapDecoder.decode(ByteBufferBitmapDecoder.java:31)
                                                                     at com.bumptech.glide.load.resource.bitmap.ByteBufferBitmapDecoder.decode(ByteBufferBitmapDecoder.java:15)
                                                                     at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67)
                                                                     at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52)
                                                                     at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43)
                                                                     at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
                                                                     at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:489)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:461)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:447)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:401)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:370)
                                                                     at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:91)
                                                                     at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:69)
                                                                     at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:71)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:293)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:260)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                     at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:386)

**Comment by MuFe** [comment]
After I updated 4.3.0, I got this

 class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                           Cause (1 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, DATA_DISK_CACHE, http://www.shiji.dsjapp.cn/uploads/item/2017/09/30/59cf4aae31ce3e7c5d27419f9b90c22d16316431d4850.jpg?imageMogr2/auto-orient/thumbnail/1280x1280>/quality/50
                                                             Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
                                                             Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
                                                               Cause (1 of 1): class java.lang.OutOfMemoryError: Failed to allocate a 18391740 byte allocation with 16777216 free bytes and 16MB until OOM
                                                             Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
                                                               Cause (1 of 1): class java.lang.OutOfMemoryError: Failed to allocate a 18391740 byte allocation with 16777216 free bytes and 16MB until OOM
                                                           Cause (2 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, DATA_DISK_CACHE, http://www.shiji.dsjapp.cn/uploads/item/2017/09/30/59cf4aae31ce3e7c5d27419f9b90c22d16316431d4850.jpg?imageMogr2/auto-orient/thumbnail/1280x1280>/quality/50
                                                             Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
                                                             Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
                                                               Cause (1 of 1): class java.lang.OutOfMemoryError: Failed to allocate a 18391740 byte allocation with 16777216 free bytes and 16MB until OOM
                                                             Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
                                                               Cause (1 of 1): class java.lang.OutOfMemoryError: Failed to allocate a 18391740 byte allocation with 16777216 free bytes and 16MB until OOM
                                                           Cause (3 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, DATA_DISK_CACHE, http://www.shiji.dsjapp.cn/uploads/item/2017/09/30/59cf4aae31ce3e7c5d27419f9b90c22d16316431d4850.jpg?imageMogr2/auto-orient/thumbnail/1280x1280>/quality/50
                                                             Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
                                                             Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
                                                               Cause (1 of 1): class java.io.IOException: java.lang.IllegalArgumentException
                                                           Cause (4 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Object->Drawable}, REMOTE, http://www.shiji.dsjapp.cn/uploads/item/2017/09/30/59cf4aae31ce3e7c5d27419f9b90c22d16316431d4850.jpg?imageMogr2/auto-orient/thumbnail/1280x1280>/quality/50
                                                             Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->GifDrawable->Drawable}
                                                             Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Drawable}
                                                               Cause (1 of 1): class java.lang.OutOfMemoryError: Failed to allocate a 18391740 byte allocation with 16777216 free bytes and 16MB until OOM
                                                             Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->BitmapDrawable->Drawable}
                                                               Cause (1 of 1): class java.lang.OutOfMemoryError: Failed to allocate a 18391740 byte allocation with 16777216 free bytes and 16MB until OOM
                                                           Cause (5 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, REMOTE, http://www.shiji.dsjapp.cn/uploads/item/2017/09/30/59cf4aae31ce3e7c5d27419f

**Comment by MuFe** [comment]
I found it easy to appear OutOfMemoryError after upgrading V4. Maybe I didn't pay attention to this problem before. Is there any way to avoid this situation?

**Comment by sjudd** [comment]
18391740 is ~18mb, so these are some pretty large images. If you can narrow down exactly what is causing the memory usage we might be able to provide more help. See http://bumptech.github.io/glide/doc/debugging.html#out-of-memory-errors for ideas on where to start.
