### ISSUE TITLE
Compiling project with glide dependencies giving "Unable to merge dex" error.

### ISSUE THREAD

**Issue by damianialex** [bumptech/glide#2565]
I am using Android Studio 3.0, gradle version 4.3, and glide version 4.3.0. I am having the same issue with Glide version 4.2.0. I am getting an error whenever trying to run the project saying 

    Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
    > com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex.

The device version I am try to run the project on is a Nexus 5x, but I believe that is regardless of the issue since I can't even get the project to compile.

Here is my build.gradle file.

    apply plugin: 'com.android.application'

	android {
	    compileSdkVersion 26
	    buildToolsVersion "26.0.2"
	    defaultConfig {
	        applicationId "com.damianialex.chanreader"
	        minSdkVersion 15
	        targetSdkVersion 26
	        versionCode 1
	        versionName "1.0"
	        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
	        multiDexEnabled true //Add this
	    }
	    buildTypes {
	        release {
	            minifyEnabled false
	            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
	        }
	    }
	}

	repositories {
	    mavenCentral()
	    maven { url 'https://maven.google.com' }
	}

	dependencies {
	    compile fileTree(include: ['*.jar'], dir: 'libs')
	    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
	        exclude group: 'com.android.support', module: 'support-annotations'
	    })
	    compile 'com.android.support:appcompat-v7:26.1.0'
	    compile 'com.android.support:design:26.1.0'
	    compile 'com.android.support.constraint:constraint-layout:1.0.2'
	    testCompile 'junit:junit:4.12'
	    compile files('libs/picasso-2.5.2.jar')

	    compile 'com.github.bumptech.glide:glide:4.3.0'
	    annotationProcessor 'com.github.bumptech.glide:compiler:4.3.0'
	}

Here's the full stack trace as well.

	* Exception is:
	org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
	    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
	    at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	    at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	    at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	    at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	    at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	    at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
	    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
	    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
	    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
	    at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
	    at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
	    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
	    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	    at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	    at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	Caused by: java.lang.RuntimeException: java.io.IOException: Can't write [C:\Users\Alex\AndroidStudioProjects\ChanReader\app\build\intermediates\multi-dex\debug\componentClasses.jar] (Can't read [C:\Users\Alex\.gradle\caches\modules-2\files-2.1\com.github.bumptech.glide\glide\4.3.0\5ef2a3700ab3320576eab21ff504189e5a92a350\glide-4.3.0.jar(;;;;;;**.class)] (Duplicate zip entry [glide-4.3.0.jar:com/bumptech/glide/util/Synthetic.class]))
	    at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
	    at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
	    at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:213)
	    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	    at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
	    at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	    at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
	    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
	    at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	    at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	    at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
	    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	    ... 27 more
	Caused by: java.io.IOException: Can't write [C:\Users\Alex\AndroidStudioProjects\ChanReader\app\build\intermediates\multi-dex\debug\componentClasses.jar] (Can't read [C:\Users\Alex\.gradle\caches\modules-2\files-2.1\com.github.bumptech.glide\glide\4.3.0\5ef2a3700ab3320576eab21ff504189e5a92a350\glide-4.3.0.jar(;;;;;;**.class)] (Duplicate zip entry [glide-4.3.0.jar:com/bumptech/glide/util/Synthetic.class]))
	    at proguard.OutputWriter.writeOutput(OutputWriter.java:187)
	    at proguard.OutputWriter.execute(OutputWriter.java:79)
	    at proguard.ProGuard.writeOutput(ProGuard.java:427)
	    at proguard.ProGuard.execute(ProGuard.java:175)
	    at com.android.build.gradle.internal.transforms.BaseProguardAction.runProguard(BaseProguardAction.java:61)
	    at com.android.build.gradle.internal.transforms.MainDexListTransform.shrinkWithProguard(MainDexListTransform.java:232)
	    at com.android.build.gradle.internal.transforms.MainDexListTransform.transform(MainDexListTransform.java:184)
	    at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:222)
	    at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:218)
	    at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	    ... 39 more
	Caused by: java.io.IOException: Can't read [C:\Users\Alex\.gradle\caches\modules-2\files-2.1\com.github.bumptech.glide\glide\4.3.0\5ef2a3700ab3320576eab21ff504189e5a92a350\glide-4.3.0.jar(;;;;;;**.class)] (Duplicate zip entry [glide-4.3.0.jar:com/bumptech/glide/util/Synthetic.class])
	    at proguard.InputReader.readInput(InputReader.java:188)
	    at proguard.InputReader.readInput(InputReader.java:158)
	    at proguard.OutputWriter.writeOutput(OutputWriter.java:176)
	    ... 48 more
	Caused by: java.io.IOException: Duplicate zip entry [glide-4.3.0.jar:com/bumptech/glide/util/Synthetic.class]
	    at proguard.io.JarWriter.getOutputStream(JarWriter.java:138)
	    at proguard.io.FilteredDataEntryWriter.getOutputStream(FilteredDataEntryWriter.java:106)
	    at proguard.io.FilteredDataEntryWriter.getOutputStream(FilteredDataEntryWriter.java:106)
	    at proguard.io.FilteredDataEntryWriter.getOutputStream(FilteredDataEntryWriter.java:92)
	    at proguard.io.ClassRewriter.read(ClassRewriter.java:68)
	    at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
	    at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
	    at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
	    at proguard.io.JarReader.read(JarReader.java:65)
	    at proguard.io.DirectoryPump.readFiles(DirectoryPump.java:65)
	    at proguard.io.DirectoryPump.pumpDataEntries(DirectoryPump.java:53)
	    at proguard.InputReader.readInput(InputReader.java:184)
	    ... 50 more

I have already made a stackoverflow post of the problem here as well for reference https://stackoverflow.com/questions/47086275/trying-to-build-android-project-with-glide-package-throws-unable-to-merge-dex.

**Comment by sjudd** [comment]
Do you see the same error if you use 4.2.0? Do you have any jars in your libs folder?

**Comment by damianialex** [comment]
@sjudd That was it. I had the jar in my libs folder. After removing it no more issues.

**Comment by sjudd** [comment]
Thanks for following up and providing lots of detail in your issue, very helpful! Glad it's fixed.

**Comment by SmileHub** [comment]
Had similar issue while importing another dependency.
launched a small shell script to see the dependency tree:
```
#/usr/bin/sh
export JAVA_HOME=<path to your jre directory, like: /home/myhome/android-studio/jre>
./gradlew -q :app:dependencies > dependencies.txt
```

saw, that although i've been on many dependencies with v.26, component was using v.27 and somehow it all was messing up. So upgraded main dependencies in gradle to v.27 and it worked out eventually:
```
    implementation 'com.android.support:appcompat-v7:27.1.0'
    implementation 'com.android.support:design:27.1.0'
    implementation 'com.android.support:support-v4:27.1.0'
```
