### ISSUE TITLE
Memory use is much more than expected?

### ISSUE THREAD

**Issue by miguoer** [bumptech/glide#2570]
**Glide Version**: 4.0.0

**Device/Android Version**: WEBOX/Android4.4

**Issue details / Repro steps / Use case background**: 
My app totally jumps 4 Activities started from MainActivity. Each Acitivty will not execute onDestroy. And at each Activity, it will load about 10 images. And then, in some low memory devices,  some images will load failed. 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
My adapter implements ListPreloader.PreloadModelProvider.
```java
        mRequestManager.load(p.mPoster)
                .apply(options)
                .listener(new RequestListener<Drawable>() {
                    @Override
                    public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
                        LogUtil.d(TAG, "load " + p.mPoster + "failed");
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
                        LogUtil.d(TAG, "load " + p.mPoster + "success");
                        return false;
                    }
                })
                .into(holder.mImage);
```

**Stack trace / LogCat**:
```ruby
11-06 17:26:41.042 13600-21661/com.togic.livevideo E/GlideExecutor: Request threw uncaught throwable
                                                                    java.lang.OutOfMemoryError
                                                                        at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:813)
                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:790)
                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:757)
                                                                        at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.getDirty(LruBitmapPool.java:142)
                                                                        at com.bumptech.glide.load.resource.bitmap.Downsampler.setInBitmap(Downsampler.java:506)
                                                                        at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:242)
                                                                        at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:178)
                                                                        at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:62)
                                                                        at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
                                                                        at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:69)
                                                                        at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:54)
                                                                        at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:45)
                                                                        at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:58)
                                                                        at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:44)
                                                                        at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:459)
                                                                        at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:452)
                                                                        at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:438)
                                                                        at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:392)
                                                                        at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:361)
                                                                        at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:113)
                                                                        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:131)
                                                                        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:69)
                                                                        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:97)
                                                                        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
                                                                        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:284)
                                                                        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:251)
                                                                        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:224)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                        at java.lang.Thread.run(Thread.java:841)
                                                                        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:349)
```
I trace the total memory size that allocates for Glide. The max size is 25.6MB.
```ruby
Calculation complete, Calculated memory cache size: 7.20 MB, pool size: 14.40 MB, byte array size: 4.00 MB, memory class limited? true, max size: 25.60 MB, memoryClass: 64, isLowMemoryDevice: false
```
But I dump the memory info as you can see in the enclosure, and find that the memory use for Glide is much more than 25.6MB. Is there any chance which will make the LRU don't work?  Why is the memory use larger than expected? 
[com.togic.livevideo_2017.11.06_14.56.hprof.zip](https://github.com/bumptech/glide/files/1445671/com.togic.livevideo_2017.11.06_14.56.hprof.zip)

**Comment by sjudd** [comment]
Can you explain why you think Glide is holding on to more than 25.6MB of memory? What objects are you looking at in the heap dump that you're attributing to Glide?

In Glide's memory cache I see 17 242x360 Bitmaps, totaling about 6.8mb, less than the 7.2mb limit.
Glide's BitmapPool appears totally empty.

I do see what appear to be a few Activity leaks (Histogram -> Search for Activity -> Right click ``com.togic.common.activity.TogicActivity$1`` -> merge shortest paths to gc roots excluding weak references. 

It looks like most (37) of the Bitmaps are held by ``ProgramListActivity`` which is held by the ``FilterLabelItemView`` class? Via the mChecked and mContext variables?

Another 19 are held by ``com.togic.common.XGPush.XGMsgDispatcher$XGMsgDispatcherInstanceHolder`` in the listeners array, which may also be a memory leak.
