### ISSUE TITLE
Glide suddenly does not work,and throws exceptions

### ISSUE THREAD

**Issue by a583114867** [bumptech/glide#2577]
Dependencies:
compile 'com.github.bumptech.glide:glide:4.0.0'
compile 'jp.wasabeef:glide-transformations:2.0.1'
compile 'com.squareup.okhttp:okhttp:2.4.0'
    compile 'com.squareup.okio:okio:1.5.0'

Device:
VivoX7

User like this:
```java
GlideApp.with(context).load(url).placeholder(placeholderResId).error(errorResId)
                    .listener(new RequestListener<Drawable>() {
                        @Override
                        public boolean onLoadFailed(@Nullable GlideException e, Object model,
                                                    Target<Drawable> target, boolean isFirstResource) {
                            if (listener != null) {
                                listener.onError();
                            }
                            return false;
                        }

                        @Override
                        public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target,
                                                       DataSource dataSource, boolean isFirstResource) {
                            if (listener != null) {
                                listener.onComplete();
                            }
                            return false;
                        }
                    }).into(imageView);
```

```
Log:
 java.lang.IllegalStateException: cache is closed
                                                                      at com.bumptech.glide.disklrucache.DiskLruCache.checkNotClosed(DiskLruCache.java:620)
                                                                      at com.bumptech.glide.disklrucache.DiskLruCache.get(DiskLruCache.java:409)
                                                                      at com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper.get(DiskLruCacheWrapper.java:75)
                                                                      at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:62)
                                                                      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:282)
                                                                      at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:249)
                                                                      at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:222)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:818)
                                                                      at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)
```

**Comment by sjudd** [comment]
Are you out of space on your sd card? Did you clear the disk cache or close it? Can you reproduce it on 4.3.1?
