### ISSUE TITLE
java.lang.IllegalArgumentException: Unexpected char 0x672a at 0 in x-oss-meta-filename value: 未标题-2.jpg

### ISSUE THREAD

**Issue by 736791050** [bumptech/glide#2582]
**Glide Version**:4.0.0-RTC

**Integration libraries**:

**Device/Android Version**:HUAWEI RIO-AL00 6.0.1_23

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
String url = "https://img.ilovelook.cn/eb/26/2e/eb262e670a71eba7b9a27b18eb2f91fd-smallWebp";
GlideApp.with(context).downloadOnly().skipMemoryCache(true).load(url).submit().get();
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
2017-11-09 15:03:05
App Version: 1.0.1_101
OS Version: 6.0.1_23
Vendor: HUAWEI
Model: HUAWEI RIO-AL00
CPU ABI: arm64-v8a

java.lang.IllegalArgumentException: Unexpected char 0x672a at 0 in x-oss-meta-filename value: 未标题-2.jpg
	at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:320)
	at okhttp3.Headers$Builder.add(Headers.java:270)
	at okhttp3.internal.http.Http2xStream.readHttp2HeadersList(Http2xStream.java:263)
	at okhttp3.internal.http.Http2xStream.readResponseHeaders(Http2xStream.java:149)
	at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775)
	at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86)
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760)
	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613)
	at okhttp3.RealCall.getResponse(RealCall.java:244)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
	at okhttp3.RealCall.access$100(RealCall.java:30)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:833)
```

**Comment by 736791050** [comment]
if use huawei cellphone,and download or load webp image(if response headers contain Chinese, I will get the error)。
response header：
`

X-Firefox-Spdy | h2
-- | --
age | 705
content-length | 20224
content-type | image/webp
date | Thu, 09 Nov 2017 07:24:51 GMT
eagleid | 71cf2d4615102129969053482e
etag | "EB262E670A71EBA7B9A27B18EB2F91FD"
last-modified | Thu, 09 Nov 2017 06:24:09 GMT
server | Tengine
timing-allow-origin | *
via | cache17.l2et2-2[0,304-0,H], cache25.l2et2-2[0,0], cache4.cn245[0,200-0,H], cache6.cn245[0,0]
x-cache | HIT TCP_MEM_HIT dirn:4:284436588 mlen:-1
x-oss-hash-crc64ecma | 10002117397484771228
x-oss-meta-data-md5 | eb262e670a71eba7b9a27b18eb2f91fd
x-oss-meta-filename | æªæ é¢-2.jpg
x-oss-object-type | Normal
x-oss-request-id | 5A0402C3CB3DB120D2932872
x-oss-storage-class | Standard
x-swift-cachetime | 3600
x-swift-savetime | Thu, 09 Nov 2017 07:36:25 GMT
`
I find the error code, but I do not how to fix it。
`    private void checkNameAndValue(String name, String value) {
      if (name == null) throw new NullPointerException("name == null");
      if (name.isEmpty()) throw new IllegalArgumentException("name is empty");
      for (int i = 0, length = name.length(); i < length; i++) {
        char c = name.charAt(i);
        if (c <= '\u001f' || c >= '\u007f') {
          throw new IllegalArgumentException(Util.format(
              "Unexpected char %#04x at %d in header name: %s", (int) c, i, name));
        }
      }
      if (value == null) throw new NullPointerException("value == null");
      for (int i = 0, length = value.length(); i < length; i++) {
        char c = value.charAt(i);
        if (c <= '\u001f' || c >= '\u007f') {
          throw new IllegalArgumentException(Util.format(
              "Unexpected char %#04x at %d in %s value: %s", (int) c, i, name, value));
        }
      }
    }`

**Comment by Tolriq** [comment]
Http is very strict :) 
https://tools.ietf.org/html/rfc7230#section-3.2.6

Headers are not allowed to have Chinese characters you need to have the server side fixed.
