### ISSUE TITLE
Conflict between Glide and OkHttp cache

### ISSUE THREAD

**Issue by ajmirB** [bumptech/glide#2584]
Hi,

I'm currently using 
- OkHttp 2.7.5 
- Retrofit 1.9.0
- Glide 4.2.0

In my application, i enabled _Last-Modified_ (or _Etags_) : 
```
OkHttpClient client = new OkHttpClient();
...
client.setCache(new Cache(context.getCacheDir(), CACHE_SIZE));

RestAdapter.Builder builder = new RestAdapter.Builder()
                .setClient(client);
```

But now, my images aren't display when my device hasn't network.

In my logcat, i got this : 
```
Glide: Load failed for https://d1uu45z6xo0diz.cloudfront.net/public/offers/list_background/3383-1474547358.jpeg with size [-2147483648x-2147483648]
     class com.bumptech.glide.load.engine.GlideException: Failed to load resource
          Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
               Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
                    Cause (1 of 1): class java.net.ConnectException: failed to connect to /192.168.1.141 (port 8888) after 2500ms: connect failed: ENETUNREACH (Network is unreachable)

I/Glide: Root cause (1 of 1)
java.net.ConnectException: failed to connect to /192.168.1.141 (port 8888) after 2500ms: connect failed: ENETUNREACH (Network is unreachable)
     at libcore.io.IoBridge.connect(IoBridge.java:114)
     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
     at java.net.Socket.connect(Socket.java:843)
     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:131)
     at com.android.okhttp.Connection.connect(Connection.java:101)
     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
     at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
     at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
     at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:161)
     at com.newrelic.agent.android.instrumentation.HttpsURLConnectionExtension.connect(HttpsURLConnectionExtension.java:103)
     at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:102)
     at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:54)
     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96)
     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:147)
     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:141)
     at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:60)
     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96)
     at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
     at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:293)
     at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:263)
     at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:841)
     at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:386)
Caused by: libcore.io.ErrnoException: connect failed: ENETUNREACH (Network is unreachable)
     at libcore.io.Posix.connect(Native Method)
     at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:85)
     at libcore.io.IoBridge.connectErrno(IoBridge.java:144)
     at libcore.io.IoBridge.connect(IoBridge.java:112)
```

I try to use Okhttp 3 because i found a GlideModule on it (with proguard) : 
[OkHttpLibraryGlideModule](https://github.com/bumptech/glide/blob/master/integration/okhttp3/src/main/java/com/bumptech/glide/integration/okhttp3/OkHttpLibraryGlideModule.java)
But i don't really know how to verify if the module is enabled.

**Comment by sjudd** [comment]
If you haven't previously loaded the images, then they won't be cached when you're offline. Have you previously loaded the images? If so, have you verified that the images you're attempting to load are in OkHttp's cache when you go offline and then try to load the image with Glide? What ``DiskCacheStrategy`` are you using with Glide? 

Can you provide your ``build.gradle`` file where you're specifying your dependencies? You won't be able to use both okhttp and okhttp3, you'll need to specify one or the other (though I assume you already are).

**Comment by ajmirB** [comment]
Yes, i already have loaded the images before being in offline. In fact, when my connection is enabled again, the image pop out very fast (like they are fetched from the cache).

I think i got this problem (image loading from OkHttp Cache instead of Glide). My DiskCacheStrategy is "DiskCacheStrategy.DATA"

A sample of my build.gradle : 
```
    compile "com.squareup.okhttp:okhttp:2.7.5"
    compile "com.squareup.retrofit:retrofit:1.9.0"
    compile "com.github.bumptech.glide:glide:4.2.0"
    annotationProcessor "com.github.bumptech.glide:glide:4.2.0"
```
When i tried okhttp3, i : 
- change the first line
- update glide to 4.3.1 
- compile the Glide’s annotations `compile 'com.github.bumptech.glide:annotations:4.3.1'`

**Comment by sjudd** [comment]
Are you downloading the images with OkHttp directly, then trying to load the same URL with Glide after you go offline? So the images have been loaded with OkHttp, but not with Glide?

If so that's not working because you're not using Glide's OkHttp integration library. In the stack trace above, Glide is using the platform default HttpUrlConnection and you haven't added a dependency on the OkHttp integration library in your build.gradle file.

If you want to use http caching, I'd recommended using Glide's OkHttp library and ``DiskCacheStrategy.NONE`` to allow all disk caching to happen in OkHttp.

**Comment by ajmirB** [comment]
I am downloading the images with Glide (Okhttp is used with Retrofit only).

It seems Okhttp blocked Glide to get the image from the cache  when i go offline.

I will try to add Glide's Okhttp dependency and set `DiskCacheStrategy.NONE`. If it works, i'll close this issue.

Thanks.

**Comment by sjudd** [comment]
So to be clear, the failure above is just that the image was not in the disk cache. 

If you want to use http caching, my comment still stands.
