### ISSUE TITLE
Resource Leak detected by StrictMode 

### ISSUE THREAD

**Issue by wilburt** [bumptech/glide#2594]
**Glide Version**:4.3.1

**Integration libraries**: OkHttp3

**Device/Android Version**: Techno Camon CX

**Issue details / Repro steps / Use case background**: 
I am using a custom model loader. Strictmode is reporting that the inpustream is not closed. This doesn't always happen but it does happens.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

**Glide ModelLoader**
```
public class ArtistArtModel implements ModelLoader<Artist, InputStream> {
    @Nullable
    @Override
    public LoadData<InputStream> buildLoadData(Artist artist, int width, int height, Options options) {
        return new LoadData<>(new ObjectKey(artist.getName()), new ArtistArtLoader(artist, width));
    }

    @Override
    public boolean handles(Artist artist) {
        return true;
    }

    public static class Factory implements ModelLoaderFactory<Artist, InputStream> {

        @Override
        public ModelLoader<Artist, InputStream> build(MultiModelLoaderFactory multiFactory) {
            return new ArtistArtModel();
        }

        @Override
        public void teardown() {
        }
    }

    static class ArtistArtLoader implements DataFetcher<InputStream> {
        private Artist artist;
        private boolean isCancelled = false;
        private int size;

        ArtistArtLoader(Artist artist, int size) {
            this.artist = artist;
            this.size = size;
        }

        @Override
        public void loadData(Priority priority, DataCallback<? super InputStream> callback) {
            //First check if request is not cancelled before starting request
            if (!isCancelled) {
                InputStream inputStream = getArtistArtInputStream();
                if (inputStream != null) {
                    callback.onDataReady(inputStream);
                } else {
                    callback.onLoadFailed(new IOException("Forced Glide network failure. Can't load Album image"));
                }


            }

        }

        private InputStream getArtistArtInputStream() {
            if (!Connectivity.isConnected(App.getAppContext())) {
                return null;
            }

            Response response = null;
            InputStream inputStream = null;

            try {
                String imageUrl = getAlbumArtUrl();
                if (!TextUtils.isEmpty(imageUrl)) {
                    Request request = new Request.Builder()
                            .url(imageUrl)
                            .cacheControl(App.cacheControl)
                            .build();

                    response = App.getOkHttpClient().newCall(request).execute();
                    if (response.isSuccessful()) {
                        inputStream =  response.body().byteStream();

                    }
                }
            } catch (IOException e) {
                e.printStackTrace();
            }

            if (inputStream == null && response != null) {
                Timber.w("getArtistArtInputStream: Closing");
                response.body().close();
            }

            return inputStream;
        }

        private String getAlbumArtUrl() {
            String urlFrmLastFm = getUrlFrmAPI1();
            return TextUtils.isEmpty(urlFrmLastFm)? getUrlFrmAPI2() : urlFrmLastFm;
        }



        private String getUrlFrmAPI1() {
            // Do some stuffs and return the appropriate url
        }

        private String getUrlFrmAPI2() {
            // Do some stuffs and return the appropriate url
        }

        @Override
        public void cleanup() {
            // Do nothing
        }

        @Override
        public void cancel() {
            isCancelled = true;
        }

        @Override
        public Class<InputStream> getDataClass() {
            return InputStream.class;
        }

        @Override
        public DataSource getDataSource() {
            return DataSource.REMOTE;
        }
    }
}
```
**In onBindViewHolder of RecyclerView**
```
GlideApp.with(context)
                .load(artist)
                .apply(options)
                .placeholder(placeHolder)
                .diskCacheStrategy(DiskCacheStrategy.RESOURCE)
                .into(imageView);
```

```


<!--
What is the error message that you got in the log?
You can find some help on diagnosing issues here: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling
-->
**Stack trace / LogCat**:
```ruby
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                     java.lang.Throwable: Explicit termination method 'response.body().close()' not called
                                                                         at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at okhttp3.internal.platform.AndroidPlatform$CloseGuard.createAndOpen(AndroidPlatform.java:329)
                                                                         at okhttp3.internal.platform.AndroidPlatform.getStackTraceForCloseable(AndroidPlatform.java:144)
                                                                         at okhttp3.RealCall.captureCallStackTrace(RealCall.java:89)
                                                                         at okhttp3.RealCall.execute(RealCall.java:73)
                                                                         at com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute(Unknown Source)
                                                                         at com.wilburt.xplayer.glide.ArtistArtModel$ArtistArtLoader.getArtistArtInputStream(ArtistArtModel.java:105)
                                                                         at com.wilburt.xplayer.glide.ArtistArtModel$ArtistArtLoader.loadData(ArtistArtModel.java:73)
                                                                         at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
                                                                         at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298)
                                                                         at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:268)
                                                                         at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:229)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                         at java.lang.Thread.run(Thread.java:761)
                                                                         at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)
```

From the stacktrace line 105 = `response = App.getOkHttpClient().newCall(request).execute();`

**Comment by sjudd** [comment]
Implement ``cleanup()`` in ``DataFetcher`` and close the stream and response body. For an example see: https://github.com/bumptech/glide/blob/c1c9be203e6dd031c970f49abf1de60cd043c096/integration/okhttp3/src/main/java/com/bumptech/glide/integration/okhttp3/OkHttpStreamFetcher.java#L89

**Comment by wilburt** [comment]
@sjudd Thanks a million. This fixed the issue.

**Comment by someonelikeypp** [comment]
@sjudd 
hey, My Glide Version:4.4.0. But I have the same issue about this.
I find that "Implement cleanup() in DataFetcher and close the stream and response body." But my the StrictMode also can detect the Resource Leak.
what should I do? to update the version or ...
Thanks for the help.
![image](https://user-images.githubusercontent.com/15836287/46242160-aeb16580-c3f7-11e8-88e9-10479cb39624.png)

![image](https://user-images.githubusercontent.com/15836287/46242009-4c576580-c3f5-11e8-858f-05ec8dcbab89.png)

**Comment by arstao** [comment]
i have the sampe problem like @someonelikeypp  as my glide version is 4.7.1
and my okhttp version is 3.10.0
