### ISSUE TITLE
Custom ModelLoader/ResourceDecoder question

### ISSUE THREAD

**Issue by frel** [bumptech/glide#2607]
Hi, I'm trying to create a custom ModelLoader and ResourceDecoder in order to load a POJO. I've made a test repo just to figure out how I can approach this. It builds, runs and crashes :) https://github.com/frel/GlideCustomLoader

The issue I'm having is that when the resource is loading it crashes with `IllegalStateException: Can't compress a recycled bitmap`

The bitmap is created in PaletteDecoder. Please see https://github.com/frel/GlideCustomLoader/blob/master/app/src/main/java/com/subgarden/glidecustomloader/PaletteDecoder.kt

Do you have any ideas of what I'm doing wrong? Also, is this approach feasible?
Thank you

**Comment by sjudd** [comment]
Please fill out the issue template when filing new issues.

Can you include the full stack trace?

**Comment by sjudd** [comment]
Ah I see, there's more history here: #2569.

Sorry I missed your update. If you can provide the full exception stack trace that would be helpful.

**Comment by sjudd** [comment]
And you did! If I'd scrolled down more in the sample repo:

```
java.lang.IllegalStateException: Can't compress a recycled bitmap
at android.graphics.Bitmap.checkRecycled(Bitmap.java:374)
at android.graphics.Bitmap.compress(Bitmap.java:1225)
at com.bumptech.glide.load.resource.bitmap.BitmapEncoder.encode(BitmapEncoder.java:66)
at com.bumptech.glide.load.resource.bitmap.BitmapEncoder.encode(BitmapEncoder.java:31)
at com.bumptech.glide.load.resource.bitmap.BitmapDrawableEncoder.encode(BitmapDrawableEncoder.java:27)
at com.bumptech.glide.load.resource.bitmap.BitmapDrawableEncoder.encode(BitmapDrawableEncoder.java:15)
at com.bumptech.glide.load.engine.DataCacheWriter.write(DataCacheWriter.java:30)
at com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper.put(DiskLruCacheWrapper.java:112)
at com.bumptech.glide.load.engine.DecodeJob$DeferredEncodeManager.encode(DecodeJob.java:639)
at com.bumptech.glide.load.engine.DecodeJob.notifyEncodeAndRelease(DecodeJob.java:435)
at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:412)
at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:375)
at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
at com.subgarden.glidecustomloader.PaletteDataFetcher.loadData(PaletteDataFetcher.kt:13)
at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298)
at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:268)
at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:229)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)
```

**Comment by sjudd** [comment]
Ok I figured it out, the exception is caused by the second bug mentioned in https://github.com/bumptech/glide/releases/tag/v4.3.1 and was fixed here: 2371aa66594b160a74e1ddfbffc3e335152e3c55.

All you need to do is update to ``4.3.1`` from ``4.3.0`` and it works

**Comment by frel** [comment]
Thank you @sjudd that worked perfectly. Is there a version of Glide before 4.3.1 where this is not an issue? For my own use I'll use 4.3.1, but not everyone can refactor from e.g. Glide 3. Thank you.

**Comment by sjudd** [comment]
This issue never affected 3.0 and lots of other things are different about 3.0 and 4.0 that would prevent them from using your code directly, even though the same general concept works in both cases.

**Comment by frel** [comment]
Ok, thank you for all the help! Much appreciated.

**Comment by sjudd** [comment]
Sure, glad it's working!
