### ISSUE TITLE
GlideException: Fetching data failed, class java.io.InputStream, REMOTE

### ISSUE THREAD

**Issue by fuyifang** [bumptech/glide#2620]
**Glide Version**:V4.3

**Integration libraries**:default 

**Device/Android Version**:TVBOX android 4.4

**Issue details / Repro steps / Use case background**: use glide in recyclerview, the images Url is correct but not display and got this error

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(mContext).load(img).apply(new RequestOptions().timeout(15)).into(mImg);
```

**Layout XML**:
```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="30pt"
    android:layout_height="260pt"
    android:background="@color/item_default_color"
    android:clickable="true"
    android:focusable="true">

    <ImageView
        android:id="@+id/image"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="centerCrop" />

    <View
        android:layout_width="match_parent"
        android:layout_height="30dp"
        android:layout_gravity="bottom"
        android:background="#80000000" />

    <TextView
        android:id="@+id/title"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginLeft="10pt"
        android:layout_marginRight="10pt"
        android:ellipsize="end"
        android:gravity="bottom|center_horizontal"
        android:maxEms="7"
        android:maxLines="1"
        android:textColor="#fff"
        android:textSize="20pt"
        android:textStyle="bold" />

    <TextView
        android:id="@+id/tv_changed"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="bottom|right"
        android:padding="10pt"
        android:textColor="@color/light_slate_gray"
        android:textSize="20sp" />

</FrameLayout>

```

**Stack trace / LogCat**:
```ruby
 Load failed for http://cj.tv6.com/upload/vod/2017-10-25/15089225359.jpg with size [178x260]
                                                       class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                         Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
                                                           Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
                                                             Cause (1 of 1): class java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
/Glide: Root cause (1 of 1)
                                                       java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                           at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:545)
                                                           at libcore.io.IoBridge.recvfrom(IoBridge.java:509)
                                                           at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
                                                           at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
                                                           at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
                                                           at java.io.InputStream.read(InputStream.java:162)
                                                           at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
                                                           at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
                                                           at com.android.okhttp.internal.Util.readAsciiLine(Util.java:316)
                                                           at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
                                                           at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
                                                           at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
                                                           at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
                                                           at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
                                                           at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:179)
                                                           at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:104)
                                                           at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:54)
                                                           at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96)
                                                           at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:147)
                                                           at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:141)
                                                           at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:60)
                                                           at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96)
                                                           at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
                                                           at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298)
                                                           at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:268)
                                                           at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:229)
                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                           at java.lang.Thread.run(Thread.java:841)
                                                           at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)
                                                        Caused by: libcore.io.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                           at libcore.io.Posix.recvfromBytes(Native Method)
                                                           at libcore.io.Posix.recvfrom(Posix.java:141)
                                                           at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
                                                           at libcore.io.IoBridge.recvfrom(IoBridge.java:506)
                                                           at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488) 
                                                           at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46) 
                                                           at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240) 
                                                           at java.io.InputStream.read(InputStream.java:162) 
                                                           at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142) 
                                                           at java.io.BufferedInputStream.read(BufferedInputStream.java:227) 
                                                           at com.android.okhttp.internal.Util.readAsciiLine(Util.java:316) 
                                                           at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308) 
                                                           at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135) 
                                                           at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644) 
                                                           at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347) 
                                                           at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296) 
                                                           at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:179) 
                                                           at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:104) 
                                                           at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:54) 
                                                           at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96) 
                                                           at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:147) 
                                                           at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:141) 
                                                           at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:60) 
                                                           at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96) 
                                                           at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61) 
                                                           at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298) 
                                                           at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:268) 
                                                           at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:229) 
                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                           at java.lang.Thread.run(Thread.java:841) 
```

**Comment by sjudd** [comment]
``java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)`` is a network error, probably nothing related to Glide. Is your network quality poor?

**Comment by fuyifang** [comment]
my network is work well,just not display in this device,set timeout long time also not display

**Comment by sjudd** [comment]
Maybe an error in your backend?

Only other idea I have is that you could try the OkHttp or Volley integration libraries.

**Comment by fuyifang** [comment]
in another device work well,i try to change integration libraries,thanks

**Comment by rene-dohan** [comment]
The sam problem here

**Comment by Alpha-chen** [comment]
> The sam problem here

Encountered the same problem, still good three hours ago

**Comment by Dipongkar12** [comment]
```
at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
W/Glide: Load failed for https://firebasestorage.googleapis.com/v0/b/mfree-9290a.appspot.com/o/uploads%2F1585237282229.null?alt=media&token=fbf576df-2c63-44bf-886d-58b32d5f49e5 with size [150x150]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.net.SocketTimeoutException(SSL handshake timed out)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    java.net.SocketTimeoutException(SSL handshake timed out)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.net.SocketTimeoutException(SSL handshake timed out)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.net.SocketTimeoutException: SSL handshake timed out
I/Glide: Root cause (1 of 1)
```

**Comment by Dipongkar12** [comment]
/Glide: Load failed for https://firebasestorage.googleapis.com/v0/b/mfree-9290a.appspot.com/o/uploads%2F1585237282229.null?alt=media&token=fbf576df-2c63-44bf-886d-58b32d5f49e5 with size [150x150]

**Comment by Tanhab** [comment]
same problem till now, any solution?

**Comment by MahmoudMabrok** [comment]
same problem till now, any solution?

**Comment by MrRoot313** [comment]
yeah same issue,,, please don't refer it to my network as its fast :P :D

**Comment by moshlp** [comment]
same issue:
```
Load failed for http://img.mlstatic.com/org-img/MP3/API/logos/testJuan.gif with size [300x300]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.io.FileNotFoundException(http://img.mlstatic.com/org-img/MP3/API/logos/testJuan.gif)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    java.io.FileNotFoundException(http://img.mlstatic.com/org-img/MP3/API/logos/testJuan.gif)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
```

**Comment by sruthimangala** [comment]
same issue

**Comment by chnouman** [comment]
same shit

**Comment by ridhofh** [comment]
anyone has solved this problem?

**Comment by jaswanthreddy-007** [comment]
same problem for me

**Comment by narcismorar** [comment]
does anyone have any information on this issue?

**Comment by HarinG10** [comment]
try to load image as bitmap. like below
`Glide.with(context).asBitmap().load(url).into(imageview)`

this happen because because of big resolution image

**Comment by jaswanthreddy-007** [comment]
Thank you now its working.

**Comment by 89hnim** [comment]
Same issue. Just worked 1 hour ago and then BOOM, can't load images anymore. 
Note: Happens with WIFI when load google drive link. (still can load others image). If use mobile data it's working again
