### ISSUE TITLE
It's oom  when I load a gif list 

### ISSUE THREAD

**Issue by LinHuanTanLy** [bumptech/glide#2626]
Request threw uncaught throwable
                                                                      java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
                                                                          at java.util.concurrent.FutureTask.report(FutureTask.java:93)
                                                                          at java.util.concurrent.FutureTask.get(FutureTask.java:163)
                                                                          at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1120)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                          at java.lang.Thread.run(Thread.java:841)
                                                                          at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
                                                                       Caused by: java.lang.OutOfMemoryError
                                                                          at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                          at android.graphics.Bitmap.createBitmap(Bitmap.java:809)
                                                                          at android.graphics.Bitmap.createBitmap(Bitmap.java:786)
                                                                          at android.graphics.Bitmap.createBitmap(Bitmap.java:753)
                                                                          at com.bumptech.glide.gifdecoder.GifDecoder.getNextBitmap(GifDecoder.java:692)
                                                                          at com.bumptech.glide.gifdecoder.GifDecoder.setPixels(GifDecoder.java:516)
                                                                          at com.bumptech.glide.gifdecoder.GifDecoder.getNextFrame(GifDecoder.java:299)
                                                                          at com.bumptech.glide.load.resource.gif.GifFrameResourceDecoder.decode(GifFrameResourceDecoder.java:20)
                                                                          at com.bumptech.glide.load.resource.gif.GifFrameResourceDecoder.decode(GifFrameResourceDecoder.java:11)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:190)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
                                                                          at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
                                                                          at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
                                                                          at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
                                                                          at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                          at java.lang.Thread.run(Thread.java:841) 
                                                                          at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)

**Comment by sjudd** [comment]
Please fill out the issue template when filing new issues.

http://bumptech.github.io/glide/doc/debugging.html#out-of-memory-errors
