### ISSUE TITLE
How to use the http get method?

### ISSUE THREAD

**Issue by fiepi** [bumptech/glide#2636]
Server only supports get method. Glide seems to use the post method.

glide:4.3.1
okhttp3-integration:4.3.1

```
curl -X POST https://xxx.xxx/8b01015525e93e76fe5ea798573d6e32.jpg
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.12.1</center>
</body>
</html>

curl -X GET https://xxx.xxx/8b01015525e93e76fe5ea798573d6e32.jpg -o img.jpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  294k  100  294k    0     0    98k      0  0:00:03  0:00:03 --:--:-- 95422
```

```
W/Glide: Load failed for https://xxx.xxx/8b01015525e93e76fe5ea798573d6e32.jpg with size [1080x1584]
                                                            class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                              Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
                                                                Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
                                                                  Cause (1 of 1): class java.io.FileNotFoundException: https://xxx.xxx/8b01015525e93e76fe5ea798573d6e32.jpg


I/Glide: Root cause (1 of 1)
                                                            java.io.FileNotFoundException: https://xxx.xxx/8b01015525e93e76fe5ea798573d6e32.jpg
                                                                at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
                                                                at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                                                                at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)
                                                                at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:104)
                                                                at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:54)
                                                                at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96)
                                                                at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:147)
                                                                at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:141)
                                                                at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:60)
                                                                at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96)
                                                                at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
                                                                at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298)
                                                                at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:268)
                                                                at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:229)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                at java.lang.Thread.run(Thread.java:764)
                                                                at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)

```

**Comment by sjudd** [comment]
In https://github.com/sjudd/glide/commit/c1172428c2689841084fbea2e98b818365f51292 I've added assertions that confirm that Glide's default http library uses ``GET``, not ``POST``.

If you still think Glide is using ``POST``, can you add a failing test case to that file?

**Comment by fiepi** [comment]
@sjudd

I'm sure a very small picture using get.  big picture using post.

This small pic can load.
https://assets.yande.re/data/preview/8b/01/8b01015525e93e76fe5ea798573d6e32.jpg

This big one cant.
https://files.yande.re/sample/8b01015525e93e76fe5ea798573d6e32/yande.re%20420567%20sample%20animal_ears%20guitar%20neko%20pandea_work.jpg

**Comment by sjudd** [comment]
No problem, thanks for letting me know what the issue was.
