### ISSUE TITLE
Using Glide as PictureDrawable.class causes GlideException: Failed to load resource

### ISSUE THREAD

**Issue by zlluvhaj** [bumptech/glide#2643]
**Glide Version**: 4.3.1

**Issue details / Repro steps / Use case background**: Basically, I am trying to load SVG files using Glide author's provided sample. I am using this code below, but using Glide as PictureDrawable class to listen to the SVGSoftwareLayerSetter class, it starts refusing loading resources:

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
public RequestBuilder<PictureDrawable> requestBuilder;

@Override
protected void onCreate(Bundle savedInstanceState) {
    ...
    requestBuilder = Glide.with(this).as(PictureDrawable.class).listener(new SVGSoftwareLayerSetter());
    ...
}
```

**Layout**:
```java
ImageView imageView1 = new ImageView(mainActivity);
imageView1.setLayoutParams(new LinearLayout.LayoutParams(200, 100));
mainActivity.requestBuilder.load(Uri.parse("http://www.clker.com/cliparts/u/Z/2/b/a/6/android-toy-h.svg")).into(imageView1);
linearLayout2.addView(imageView1);
```

**Stack trace / LogCat**:
```ruby
Load failed for http://www.clker.com/cliparts/u/Z/2/b/a/6/android-toy-h.svg with size [200x100] class com.bumptech.glide.load.engine.
GlideException: Failed to load resource
Cause (1 of 1): class java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
```

**Comment by sjudd** [comment]
Can you provide the full stack trace? You may need to enable verbose logging, see http://bumptech.github.io/glide/doc/debugging.html#requestlistener-and-custom-logs for an example of how to do this as a one off.

**Comment by zlluvhaj** [comment]
Thank you for the reply, this is the full stack trace:
```ruby
Root cause (1 of 1)
                                                            java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                                                                at java.util.ArrayList.get(ArrayList.java:437)
                                                                at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:57)
                                                                at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298)
                                                                at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:265)
                                                                at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:229)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                at java.lang.Thread.run(Thread.java:764)
                                                                at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)
```

**Comment by zlluvhaj** [comment]
Problem solved, I forgot to add other class files to the project too (besides SVGSoftwareLayerSetter).

**Comment by slavaantonenko** [comment]
Hello,
I have added all classes and set everything in place but still getting the error.

**Comment by bernatik** [comment]
I have the same issue. My stack trace:
09-22 14:01:46.087 21013-21013/<i removed my app package here> W/Glide: Load failed for http://upload.wikimedia.org/wikipedia/de/f/f9/Everton_FC.svg with size [131x131]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.lang.IndexOutOfBoundsException(Index: 0, Size: 0)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
09-22 14:01:46.087 21013-21013/<i removed my app package here> I/Glide: Root cause (1 of 1)
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:411)
        at java.util.Collections$UnmodifiableList.get(Collections.java:1295)
        at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:71)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)

**Comment by protoss5482** [comment]
implementation 'com.github.bumptech.glide:glide:4.8.0'
    implementation 'com.caverock:androidsvg-aar:1.3' or implementation 'com.caverock:androidsvg:1.2.1'

`10-03 15:07:50.195 19175-19175/<i removed my app package here> W/Glide: Load failed for https://<url hide>.svg with size [756x336]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.lang.IndexOutOfBoundsException(Index: 0, Size: 0)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
10-03 15:07:50.196 19175-19175/<i removed my app package here> I/Glide: Root cause (1 of 1)
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at java.util.Collections$UnmodifiableList.get(Collections.java:1351)
        at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:71)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)`
