### ISSUE TITLE
How to load or resize a Bitmap from a Bitmap using Glide ?

### ISSUE THREAD

**Issue by michaelDnguyen** [bumptech/glide#2651]
Glide Version: 4.3.1

Integration libraries: No

Device/Android Version: Android API > 16

Issue details / Repro steps / Use case background:

Glide load line / GlideModule (if any) / list Adapter code (if any):

How to load resize a bitmap from a bitmap using Glide ? Example code:
`Bitmap bitOrigin = Glide.with(getActivity()).asBitmap().load(url).submit().get();
//process a bitmap...
Bitmap bitResult  = Glide.with(getActivity()).asBitmap().load(bitOrigin).submit(1000,1000).get();`

Layout XML: No

Stack trace / LogCat: 
`11-30 09:05:42.352: W/System.err(12765): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
11-30 09:05:42.355: W/System.err(12765): 	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:750)
11-30 09:05:42.355: W/System.err(12765): 	at com.scanlibrary.ResultFragment$SaveAndAddPageClickListener$1.run(ResultFragment.java:291)
11-30 09:05:42.355: W/System.err(12765): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
11-30 09:05:42.355: W/System.err(12765): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-30 09:05:42.355: W/System.err(12765): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-30 09:05:42.355: W/System.err(12765): 	at java.lang.Thread.run(Thread.java:762)
`

thanks & best regards,

**Comment by sjudd** [comment]
Hi @michaelDnguyen,

It looks like you might not have included some important information when you filed this issue.  To make sure we have all the information we need to help with your issue. Please take a look at the [Issue Template](https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md) and make sure you've filled out as many sections as possible.
In particular you **must** include:
* Glide Version * Glide load line * Issue details.
I'm marking this issue as requiring more information. Please understand that if you do not provide that information or update the issue within the next 7 days this issue will be automatically closed so that it doesn't clutter the bug tracker.
Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by michaelDnguyen** [comment]
I just update issue, Thanks

**Comment by sjudd** [comment]
Thanks, but I'm still not totally clear what you're asking.

You can use ``.submit()`` on a background thread to retrieve a ``Bitmap``. You cannot use ``.submit()`` on the main thread. You can use [``into(Target)``][1] to load a ``Bitmap`` asynchronously.

If you just want to transform the ``Bitmap``, you can write a custom [``Transformation``][2]. See also http://bumptech.github.io/glide/doc/transformations.html

[1]: http://bumptech.github.io/glide/javadocs/431/com/bumptech/glide/RequestBuilder.html#into-Y-
[2]: http://bumptech.github.io/glide/javadocs/431/com/bumptech/glide/load/resource/bitmap/BitmapTransformation.html

**Comment by michaelDnguyen** [comment]
I have some process in a Bitmap: crop, rotate, draw in bitmap... and end of process, i want resize this bitmap by Glide, how to do it ?

**Comment by sjudd** [comment]
You could write a [``BitmapTransformation``][1] that does your crop/rotate/draw/resize?

[1]: http://bumptech.github.io/glide/javadocs/431/com/bumptech/glide/load/resource/bitmap/BitmapTransformation.html
