### ISSUE TITLE
How to load Audio Cover Art using Glide

### ISSUE THREAD

**Issue by rk8339811** [bumptech/glide#2652]
I want to load Audio file cover art to an ImageView. I am already aware of this [answer ](https://github.com/bumptech/glide/issues/699#issuecomment-149598922) and also tried using it but I am getting the below error.
```

java.lang.IllegalArgumentException: Unknown type class com.package.app.Classes.AudioCover. 
You must provide a Model of a type for which there is a registered ModelLoader, 
if you are using a custom model, you must first call Glide#register with a ModelLoaderFactory for your custom model class
at com.bumptech.glide.RequestManager.loadGeneric(RequestManager.java:629)
at com.bumptech.glide.RequestManager.load(RequestManager.java:598) 
```
**Can Anyone please help me! I am not very much familiar with Android Development hence any help would be really grateful.**
**Also I only have the path to the Audio File**

This is my Glide Loading line
```
Glide
    .with(context)
    .load(new AudioCover(filePath))
    .placeholder(R.drawable.loading_cover)
    .error(R.drawable.missing_cover)
    .into(imageView)
```

I am using this line to import the library `compile 'com.github.bumptech.glide:glide:3.7.0'`

**Comment by sjudd** [comment]
Hi @rk8339811,

It looks like you might not have included some important information when you filed this issue.  To make sure we have all the information we need to help with your issue. Please take a look at the [Issue Template](https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md) and make sure you've filled out as many sections as possible.
In particular you **must** include:
* Glide Version * Glide load line * Issue details.
I'm marking this issue as requiring more information. Please understand that if you do not provide that information or update the issue within the next 7 days this issue will be automatically closed so that it doesn't clutter the bug tracker.
Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by TWiStErRob** [comment]
here's how to interpret the error message:

> You must provide a Model of a type for which there is a registered ModelLoader, 

`AudioCover` is the one, but there's no model loader for it

> if you are using a custom model, you must first call Glide#register with a ModelLoaderFactory for your custom model class

This line is not executed before you start the load:
```java
glide.register(AudioCover.class, InputStream.class, new AudioCoverLoader.Factory());
```

Reason: the module created is probably not registered. Take a look at https://github.com/bumptech/glide/wiki/Configuration#lazy-configuration how to register your module.

**Comment by rk8339811** [comment]
@TWiStErRob  Thank You very much. Do I have to call `glide.register(AudioCover.class, InputStream.class, new AudioCoverLoader.Factory());` every time I execute 
```
Glide
    .with(context)
    .load(new AudioCover(filePath))
    .placeholder(R.drawable.loading_cover)
    .error(R.drawable.missing_cover)
    .into(imageView)
```
Also can you please tell me that do I have to unregister the module before I try to use the Glide library without any custom module as my app has to load Images and Video images also.

**Comment by rk8339811** [comment]
Hey,

Thank You very much. I Tried following the steps but it give me this error

java.lang.RuntimeException: Unable to instantiate GlideModule
implementation for class com.package.name.Glide_Modules.AudioCoverModule

This error occurs when I try to load a Images thumbnail using the default
Glide library and without any custom module.

Can you pls help with this also.

Thanks
Rajesh.

**Comment by rk8339811** [comment]
@TWiStErRob  Hey,
I Tried following the steps but it give me this error
`java.lang.RuntimeException: Unable to instantiate GlideModule implementation for class com.package.name.Glide_Modules.AudioCoverModule`

This error occurs when I try to load a Images thumbnail using the default Glide library and without any custom module.

Can you pls help with this also.
