### ISSUE TITLE
Can't load existing local file

### ISSUE THREAD

**Issue by clement-petitcunot** [bumptech/glide#2664]
**Glide Version**:
4.3.1

**Integration libraries**:
4.3.1

**Device/Android Version**:
Pixel C Android 8.0.0

**Issue details / Repro steps / Use case background**:
Glide doesn't load an existing local file.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(imageView.getContext())
                    .load(url)
                    .apply(new RequestOptions().diskCacheStrategy(DiskCacheStrategy.RESOURCE).centerCrop())
                    .into(imageView);
```

**Stack trace / LogCat**:
```ruby
11-30 18:00:41.822 19592-19592/com.allianzes W/Glide: Load failed for file:///storage/emulated/0/Android/data/com.allianzes/cache/288162/xm6gjgmy_48e-59dcd8453c585.jpg with size [409x230]
                                                              class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                                Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, LOCAL
                                                                  Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
                                                                    Cause (1 of 1): class java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
                                                                  Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
                                                                    Cause (1 of 1): class java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
                                                                Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{StringUri->Object->Drawable}, LOCAL
                                                                  Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{StringUri->Drawable->Drawable}
                                                                  Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{StringUri->Bitmap->Drawable}
11-30 18:00:41.823 19592-19592/com.allianzes I/Glide: Root cause (1 of 2)
                                                              java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
                                                                  at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:133)
                                                                  at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:24)
                                                                  at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67)
                                                                  at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52)
                                                                  at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43)
                                                                  at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
                                                                  at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:494)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:466)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:452)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:406)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:375)
                                                                  at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
                                                                  at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:49)
                                                                  at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:268)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:229)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                  at java.lang.Thread.run(Thread.java:764)
                                                                  at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)
                                                               Caused by: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
                                                                  at android.media.MediaMetadataRetriever.setDataSource(Native Method)
                                                                  at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:136)
                                                                  at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:123)
                                                                  at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:24) 
                                                                  at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67) 
                                                                  at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52) 
                                                                  at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43) 
                                                                  at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56) 
                                                                  at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42) 
                                                                  at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:494) 
                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:466) 
                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:452) 
                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:406) 
                                                                  at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:375) 
                                                                  at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111) 
                                                                  at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:49) 
                                                                  at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61) 
                                                                  at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298) 
                                                                  at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:268) 
                                                                  at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:229) 
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                  at java.lang.Thread.run(Thread.java:764) 
                                                                  at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413) 
11-30 18:00:41.824 19592-19592/com.allianzes I/Glide: Root cause (2 of 2)
                                                              java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
                                                                  at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:133)
                                                                  at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:24)
                                                                  at com.bumptech.glide.load.resource.bitmap.BitmapDrawableDecoder.decode(BitmapDrawableDecoder.java:45)
                                                                  at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67)
                                                                  at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52)
                                                                  at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43)
                                                                  at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
                                                                  at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:494)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:466)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:452)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:406)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:375)
                                                                  at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
                                                                  at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:49)
                                                                  at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:268)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:229)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                  at java.lang.Thread.run(Thread.java:764)
                                                                  at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)
                                                               Caused by: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
                                                                  at android.media.MediaMetadataRetriever.setDataSource(Native Method)
                                                                  at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:136)
                                                                  at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:123)
                                                                  at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:24) 
                                                                  at com.bumptech.glide.load.resource.bitmap.BitmapDrawableDecoder.decode(BitmapDrawableDecoder.java:45) 
                                                                  at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67) 
                                                                  at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52) 
                                                                  at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43) 
                                                                  at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56) 
                                                                  at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42) 
                                                                  at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:494) 
                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:466) 
                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:452) 
                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:406) 
                                                                  at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:375) 
                                                                  at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111) 
                                                                  at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:49) 
                                                                  at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61) 
                                                                  at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298) 
                                                                  at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:268) 
                                                                  at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:229) 
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                  at java.lang.Thread.run(Thread.java:764) 
                                                                  at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413) 
```

**Comment by sjudd** [comment]
What is url? Can you attach the file? Is it an image or video?

Usually this kind of exception means the filepath is invalid or the file at the filepath is invalid.

**Comment by clement-petitcunot** [comment]
Url is a Uri that contain : 
`file:///storage/emulated/0/Android/data/com.allianzes/cache/288162/xm6gjgmy_48e-59dcd8453c585.jpg`
It's an image, the filepath is correct and the file is correct too ( i can display it in Google Photos for example).

One thing i didn't say before, i use a LibraryGlideModule for add custom cookies when i call online url.

```java
@GlideModule
public class CustomGlideModule extends LibraryGlideModule {
    @Override
    public void registerComponents(Context context, Glide glide, Registry registry) {
        registry.replace(Uri.class, InputStream.class, new HeaderedLoader.Factory());
    }

    private static class HeaderedLoader extends BaseGlideUrlLoader<Uri> {

        HeaderedLoader(ModelLoader<GlideUrl, InputStream> concreteLoader) {
            super(concreteLoader);
        }

        @Override
        protected String getUrl(Uri uri, int width, int height, Options options) {
            return uri.toString();
        }

        @Nullable
        @Override
        protected Headers getHeaders(Uri uri, int width, int height, Options options) {
            return new LazyHeaders.Builder()
                        .addHeader("cookie", "my_custom_cookie")
                        .build();
           
        }

        @Override
        public boolean handles(Uri uri) {
            if(uri != null && uri.toString() != null && uri.toString().length() > 4 && uri.toString().substring(0,4).equals("file")){
                return false;
            }
            return true;
        }

        public static class Factory implements ModelLoaderFactory<Uri, InputStream> {

            @Override
            public ModelLoader<Uri, InputStream> build(MultiModelLoaderFactory multiFactory) {
                ModelLoader<GlideUrl, InputStream> loader = multiFactory.build(GlideUrl.class, InputStream.class);
                return new HeaderedLoader(loader);
            }

            @Override
            public void teardown() { /* nothing to free */ }
        }
    }
}
```

When i comment the line in "registerComponents" function, every thing works but if i let this line, the local files that i never displayed don't display and i get the error in my first post. I guess i don't use the LibraryGlideModule the right way..

Thank you for your assistance

**Comment by sjudd** [comment]
Ugh sorry I missed this.

This occurs because you're using ``replace()``, which removes all existing loaders for ``Uri`` to ``InputStream``, which will include Glide's default File, resource, and asset ``Uri`` loaders, among others.

You want ``prepend()`` instead, see http://bumptech.github.io/glide/doc/configuration.html#ordering-components.

There's also some more information on ``BaseGlideUrlLoader`` here: http://bumptech.github.io/glide/tut/custom-modelloader.html#baseglideurlloader
