### ISSUE TITLE
java.lang.IllegalStateException: Cannot pool recycled bitmap (Android 8)

### ISSUE THREAD

**Issue by anthony3444** [bumptech/glide#2665]
Hi,

(Android 8.0 ; Glide 4.3.1)

I have this crash when onDestroy() is called:

```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {com.xxx/com.xxx.ui.photo.PhotoActivity}: java.lang.IllegalStateException: Cannot pool recycled bitmap
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4993)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5012)
       at android.app.ActivityThread.-wrap6(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1944)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7358)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)
Caused by java.lang.IllegalStateException: Cannot pool recycled bitmap
       at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.put(LruBitmapPool.java:86)
       at com.bumptech.glide.load.resource.bitmap.BitmapResource.recycle(BitmapResource.java:57)
       at com.bumptech.glide.load.engine.EngineResource.recycle(EngineResource.java:63)
       at com.bumptech.glide.load.engine.ResourceRecycler.recycle(ResourceRecycler.java:28)
       at com.bumptech.glide.load.engine.Engine.onResourceReleased(Engine.java:336)
       at com.bumptech.glide.load.engine.EngineResource.release(EngineResource.java:101)
       at com.bumptech.glide.load.engine.Engine.release(Engine.java:292)
       at com.bumptech.glide.request.SingleRequest.releaseResource(SingleRequest.java:337)
       at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:316)
       at com.bumptech.glide.manager.RequestTracker.clearRemoveAndRecycle(RequestTracker.java:62)
       at com.bumptech.glide.RequestManager.untrack(RequestManager.java:462)
       at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:449)
       at com.bumptech.glide.RequestManager.clear(RequestManager.java:437)
       at com.bumptech.glide.RequestManager.onDestroy(RequestManager.java:290)
       at com.bumptech.glide.manager.ActivityFragmentLifecycle.onDestroy(ActivityFragmentLifecycle.java:64)
       at com.bumptech.glide.manager.SupportRequestManagerFragment.onDestroy(SupportRequestManagerFragment.java:187)
       at android.support.v4.app.Fragment.performDestroy(Fragment.java:2516)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1557)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
       at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3218)
       at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:262)
       at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:362)
       at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)
       at com.xxx.ui.BaseActivity.onDestroy(BaseActivity.java:307)
       at com.xxx.ui.photo.PhotoActivity.onDestroy(PhotoActivity.java:164)
       at android.app.Activity.performDestroy(Activity.java:7572)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1253)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4980)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5012)
       at android.app.ActivityThread.-wrap6(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1944)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7358)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)
```
It's the first time I have this crash. How can I catch this exception?

Thank you very much,

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/resourcereuse.html#common-errors

**Comment by anthony3444** [comment]
@sjudd : ok but I didn't see some interesting elements to understand this specific error...

**Comment by PrinceDholakiya** [comment]
you can not use bitmap after recycle() it.
So make sure that you have done it anywhere before you use it.
