### ISSUE TITLE
Compiler crash when compiling with kapt and in-process execution strategy

### ISSUE THREAD

**Issue by rubengees** [bumptech/glide#2673]
**Glide Version**: `4.3.1`

**Integration libraries**: `OkHttp3`

**Device/Android Version**: Not relevant

**Issue details / Repro steps / Use case background**:

I have a project that uses `Kotlin` and thus `kapt`. I want to compile the project with the compiler flag `-Dkotlin.compiler.execution.strategy="in-process"` due to [this issue](https://youtrack.jetbrains.com/issue/KT-15562) which fails my CI builds.

Glide's annotation processor sadly fails with the attached stacktrace when trying that. It seems that the `@Excludes` annotation is triggering the issue.

**Minimal `GlideModule` to trigger the issue**:
```kt
@GlideModule
@Excludes(OkHttpLibraryGlideModule::class)
class ExampleGlideModule : AppGlideModule() {}
```

**Layout XML**: Not relevant

**Stack trace / LogCat**:
```ruby
java.lang.ClassCastException: com.sun.tools.javac.code.Attribute$Class cannot be cast to com.sun.tools.javac.code.Attribute$Class
        at com.bumptech.glide.annotation.compiler.ProcessorUtil.findClassValuesFromAnnotationOnClassAsNames(ProcessorUtil.java:383)
        at com.bumptech.glide.annotation.compiler.AppModuleGenerator.getExcludedGlideModuleClassNames(AppModuleGenerator.java:228)
        at com.bumptech.glide.annotation.compiler.AppModuleGenerator.generate(AppModuleGenerator.java:86)
        at com.bumptech.glide.annotation.compiler.AppModuleProcessor.maybeWriteAppModule(AppModuleProcessor.java:109)
        at com.bumptech.glide.annotation.compiler.GlideAnnotationProcessor.process(GlideAnnotationProcessor.java:127)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
        at org.jetbrains.kotlin.kapt3.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:73)
        at org.jetbrains.kotlin.kapt3.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:42)
        at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:205)
        at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:166)
        at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:82)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:96)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:106)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:83)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:376)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:67)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:96)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:367)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules(KotlinToJVMBytecodeCompiler.kt:132)
```

I have created a demo project [here](https://github.com/rubengees/GlideKaptIssue) that fails when building with the compiler flag.

If you need any more info I am more than happy to provide what you need.
Thanks in advance!

**Comment by sjudd** [comment]
Thanks for the sample app and detailed report, very helpful!

**Comment by rubengees** [comment]
Thanks for fixing this issue so fast!
