### ISSUE TITLE
com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)

### ISSUE THREAD

**Issue by yanchengdeng** [bumptech/glide#2680]
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366] 
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366] "glide-source-thread-2" prio=5 tid=64 Waiting
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   | group="" sCount=1 dsCount=0 obj=0x135531c0 self=0x7f7d330000
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   | sysTid=25886 nice=9 cgrp=default sched=0/0 handle=0x7f78ffa440
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   | state=S schedstat=( 21043538 8803801 75 ) utm=2 stm=0 core=5 HZ=100
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   | stack=0x7f78ef8000-0x7f78efa000 stackSize=1037KB
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   | held mutexes=
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   kernel: __switch_to+0x70/0x7c
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   kernel: futex_wait_queue_me+0xd4/0x12c
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   kernel: futex_wait+0xdc/0x1e4
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   kernel: do_futex+0xc8/0x8d0
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   kernel: SyS_futex+0xf8/0x174
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   kernel: cpu_switch_to+0x48/0x5a0
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   native: #00 pc 000000000001bf9c  /system/lib64/libc.so (syscall+28)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   native: #01 pc 000000000013bc14  /system/lib64/libart.so (_ZN3art17ConditionVariable4WaitEPNS_6ThreadE+136)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   native: #02 pc 00000000003994ec  /system/lib64/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadElibNS_11ThreadStateE+1440)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   native: #03 pc 00000000003996e0  /system/lib64/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadEPNS_6mirror6ObjectElibNS_11ThreadStateE+244)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   native: #04 pc 000000000000087c  /system/framework/arm64/boot.oat (Java_java_lang_Object_wait__JI+144)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at java.lang.Object.wait!(Native method)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   - waiting on <0x08dfad29> (a java.lang.Object)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at java.lang.Thread.parkFor$(Thread.java:1220)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   - locked <0x08dfad29> (a java.lang.Object)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at sun.misc.Unsafe.park(Unsafe.java:299)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1036)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at java.lang.Thread.run(Thread.java:818)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366] 
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366] "glide-source-thread-3" prio=5 tid=65 Waiting
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   | group="" sCount=1 dsCount=0 obj=0x1356ae20 self=0x7f773ec600
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   | sysTid=25889 nice=9 cgrp=default sched=0/0 handle=0x7f78ef5440
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   | state=S schedstat=( 59968899 5987710 104 ) utm=4 stm=1 core=6 HZ=100
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   | stack=0x7f78df3000-0x7f78df5000 stackSize=1037KB
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   | held mutexes=
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   kernel: __switch_to+0x70/0x7c
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   kernel: futex_wait_queue_me+0xd4/0x12c
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   kernel: futex_wait+0xdc/0x1e4
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   kernel: do_futex+0xc8/0x8d0
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   kernel: SyS_futex+0xf8/0x174
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   kernel: cpu_switch_to+0x48/0x5a0
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   native: #00 pc 000000000001bf9c  /system/lib64/libc.so (syscall+28)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   native: #01 pc 000000000013bc14  /system/lib64/libart.so (_ZN3art17ConditionVariable4WaitEPNS_6ThreadE+136)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   native: #02 pc 00000000003994ec  /system/lib64/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadElibNS_11ThreadStateE+1440)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   native: #03 pc 00000000003996e0  /system/lib64/libart.so (_ZN3art7Monitor4WaitEPNS_6ThreadEPNS_6mirror6ObjectElibNS_11ThreadStateE+244)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   native: #04 pc 000000000000087c  /system/framework/arm64/boot.oat (Java_java_lang_Object_wait__JI+144)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at java.lang.Object.wait!(Native method)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   - waiting on <0x04b568ae> (a java.lang.Object)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at java.lang.Thread.parkFor$(Thread.java:1220)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   - locked <0x04b568ae> (a java.lang.Object)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at sun.misc.Unsafe.park(Unsafe.java:299)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1036)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at java.lang.Thread.run(Thread.java:818)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]   at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)
12-05 09:51:00.080 25709-25709/? A/art: art/runtime/runtime.cc:366]

**Comment by sjudd** [comment]
Hi @yanchengdeng,

It looks like you might not have included some important information when you filed this issue. To make sure we have all the information we need to help with your issue. Please take a look at the [Issue Template](https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md) and make sure you've filled out as many sections as possible.

In particular you **must** include:

* Glide Version
* Glide load line
* Issue details.

I'm marking this issue as requiring more information. Please understand that if you do not provide that information or update the issue within the next 7 days this issue will be automatically closed so that it doesn''t clutter the bug tracker.

Best regards,

~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.
