### ISSUE TITLE
I used glide_4.4  had  the error, but there is no such error glide_4.3.1

### ISSUE THREAD

**Issue by shenyunhuan** [bumptech/glide#2682]
Called getHeight() on a recycle()'d bitmap! This is undefined behavior!
12-05 10:18:40.505 14835-14835/com.guyu.android W/Bitmap: Called getConfig() on a recycle()'d bitmap! This is undefined behavior!
12-05 10:18:40.505 14835-14835/com.guyu.android D/AndroidRuntime: Shutting down VM
12-05 10:18:40.505 14835-14835/com.guyu.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.guyu.android, PID: 14835
                                                                  java.lang.IllegalStateException: Cannot obtain size for recycled Bitmap: android.graphics.Bitmap@ef16c94[1024x600] ARGB_8888
                                                                      at com.bumptech.glide.util.Util.getBitmapByteSize(Util.java:74)
                                                                      at com.bumptech.glide.load.resource.bitmap.BitmapResource.getSize(BitmapResource.java:52)
                                                                      at com.bumptech.glide.load.engine.EngineResource.getSize(EngineResource.java:57)
                                                                      at com.bumptech.glide.load.engine.cache.LruResourceCache.getSize(LruResourceCache.java:39)
                                                                      at com.bumptech.glide.load.engine.cache.LruResourceCache.getSize(LruResourceCache.java:13)
                                                                      at com.bumptech.glide.util.LruCache.put(LruCache.java:123)
                                                                      at com.bumptech.glide.load.engine.cache.LruResourceCache.put(LruResourceCache.java:13)
                                                                      at com.bumptech.glide.load.engine.Engine.onResourceReleased(Engine.java:327)
                                                                      at com.bumptech.glide.load.engine.ActiveResources.cleanupActiveReference(ActiveResources.java:104)
                                                                      at com.bumptech.glide.load.engine.ActiveResources.access$000(ActiveResources.java:22)
                                                                      at com.bumptech.glide.load.engine.ActiveResources$1.handleMessage(ActiveResources.java:30)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                      at android.os.Looper.loop(Looper.java:158)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:7231)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by sjudd** [comment]
Are you able to reproduce it? If so, how?

Are you calling Bitmap.recycle() anywhere in your code?

**Comment by shenyunhuan** [comment]
yes, I  calling Bitmap.recycle(), But when I use glide4.3.1 everything works fine，No code change

**Comment by shenyunhuan** [comment]
when I use glide4.4,I commented on the Bitmap.recycle()，This error is still

**Comment by shenyunhuan** [comment]
I able to reproduce it,But I'm not sure when it happened.
12-05 15:48:17.752 21156-21156/com.guyu.android W/Bitmap: Called getWidth() on a recycle()'d bitmap! This is undefined behavior!
12-05 15:48:17.752 21156-21156/com.guyu.android W/Bitmap: Called getHeight() on a recycle()'d bitmap! This is undefined behavior!
12-05 15:48:17.752 21156-21156/com.guyu.android W/Bitmap: Called getConfig() on a recycle()'d bitmap! This is undefined behavior!
12-05 15:48:17.752 21156-21156/com.guyu.android D/AndroidRuntime: Shutting down VM
12-05 15:48:17.752 21156-21156/com.guyu.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.guyu.android, PID: 21156
                                                                  java.lang.IllegalStateException: Cannot obtain size for recycled Bitmap: android.graphics.Bitmap@cd91271[1024x600] ARGB_8888
                                                                      at com.bumptech.glide.util.Util.getBitmapByteSize(Util.java:74)
                                                                      at com.bumptech.glide.load.resource.bitmap.BitmapResource.getSize(BitmapResource.java:52)
                                                                      at com.bumptech.glide.load.engine.EngineResource.getSize(EngineResource.java:57)
                                                                      at com.bumptech.glide.load.engine.cache.LruResourceCache.getSize(LruResourceCache.java:39)
                                                                      at com.bumptech.glide.load.engine.cache.LruResourceCache.getSize(LruResourceCache.java:13)
                                                                      at com.bumptech.glide.util.LruCache.trimToSize(LruCache.java:179)
                                                                      at com.bumptech.glide.load.engine.cache.LruResourceCache.trimMemory(LruResourceCache.java:52)
                                                                      at com.bumptech.glide.Glide.trimMemory(Glide.java:555)
                                                                      at com.bumptech.glide.Glide.onTrimMemory(Glide.java:752)
                                                                      at android.app.Application.onTrimMemory(Application.java:158)
                                                                      at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:5979)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:158)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:7231)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
12-05 15:48:51.042 21156-21156/com.guyu.android I/Process: Sending signal. PID: 21156 SIG: 9

**Comment by shenyunhuan** [comment]
Forget it, I still use glide4.3.1

**Comment by sjudd** [comment]
Don't call bitmap.recycle() on Bitmaps loaded from Glide. Instead clear the corresponding ``Target``. All ``into()`` methods return a ``Target`` that you can clear when you're done, so it's usually fairly straightforward to replace ``recycle()`` with ``clear()``.

**Comment by sjudd** [comment]
Also see the behavior changes section in the release notes for context: https://github.com/bumptech/glide/releases/tag/v4.4.0
