### ISSUE TITLE
Canvas: trying to use a recycled bitmap Glide 4.4.0

### ISSUE THREAD

**Issue by lam-amsiq** [bumptech/glide#2693]
Stack:
```
Fatal Exception: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@2941016
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
       at android.graphics.Canvas.drawBitmap(Canvas.java:1404)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:544)
       at android.widget.ImageView.onDraw(ImageView.java:1244)
       at android.view.View.draw(View.java:16435)
       at android.view.View.updateDisplayListIfDirty(View.java:15388)
       at android.view.View.draw(View.java:16189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3738)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3528)
       at android.view.View.draw(View.java:16447)
       at android.view.View.updateDisplayListIfDirty(View.java:15388)
       at android.view.View.draw(View.java:16189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3738)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3528)
       at android.view.View.draw(View.java:16447)
       at android.view.View.updateDisplayListIfDirty(View.java:15388)
       at android.view.View.draw(View.java:16189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3738)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3528)
       at android.view.View.draw(View.java:16447)
       at android.view.View.updateDisplayListIfDirty(View.java:15388)
       at android.view.View.draw(View.java:16189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3738)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3528)
       at android.view.View.draw(View.java:16447)
       at android.view.View.updateDisplayListIfDirty(View.java:15388)
       at android.view.View.draw(View.java:16189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3738)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3528)
       at android.view.View.draw(View.java:16447)
       at android.view.View.updateDisplayListIfDirty(View.java:15388)
       at android.view.View.draw(View.java:16189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3738)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3528)
       at android.view.View.draw(View.java:16447)
       at android.view.View.updateDisplayListIfDirty(View.java:15388)
       at android.view.View.draw(View.java:16189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3738)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3528)
       at android.view.View.draw(View.java:16447)
       at android.view.View.updateDisplayListIfDirty(View.java:15388)
       at android.view.View.draw(View.java:16189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3738)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3528)
       at android.view.View.draw(View.java:16447)
       at android.view.View.updateDisplayListIfDirty(View.java:15388)
       at android.view.View.draw(View.java:16189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3738)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3528)
       at android.view.View.draw(View.java:16447)
       at android.view.View.updateDisplayListIfDirty(View.java:15388)
       at android.view.View.draw(View.java:16189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3738)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3528)
       at android.view.View.draw(View.java:16447)
       at android.view.View.updateDisplayListIfDirty(View.java:15388)
       at android.view.View.draw(View.java:16189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3738)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3528)
       at android.view.View.draw(View.java:16447)
       at android.view.View.updateDisplayListIfDirty(View.java:15388)
       at android.view.View.draw(View.java:16189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3738)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3528)
       at android.view.View.draw(View.java:16447)
       at android.view.View.updateDisplayListIfDirty(View.java:15388)
       at android.view.View.draw(View.java:16189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3738)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3528)
       at android.view.View.draw(View.java:16447)
       at android.view.View.updateDisplayListIfDirty(View.java:15388)
       at android.view.View.draw(View.java:16189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3738)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3528)
       at android.view.View.draw(View.java:16447)
       at android.view.View.updateDisplayListIfDirty(View.java:15388)
       at android.view.View.draw(View.java:16189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3738)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3528)
       at android.view.View.draw(View.java:16447)
       at android.view.View.updateDisplayListIfDirty(View.java:15388)
       at android.view.View.draw(View.java:16189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3738)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3528)
       at android.view.View.draw(View.java:16447)
       at android.view.View.updateDisplayListIfDirty(View.java:15388)
       at android.view.View.draw(View.java:16189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3738)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3528)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2757)
       at android.view.View.draw(View.java:16447)
       at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2743)
       at android.view.View.updateDisplayListIfDirty(View.java:15388)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:286)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:292)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:327)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3020)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2824)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2436)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1321)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6708)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
       at android.view.Choreographer.doCallbacks(Choreographer.java:696)
       at android.view.Choreographer.doFrame(Choreographer.java:631)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5765)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```
[Fabric](http://crashes.to/s/9f69dd0100f)

**Comment by sjudd** [comment]
Please fill out the issue template when filing new issues.

What load line are you using? Are you calling ``Bitmap.recycle()`` anywhere in your app? Can you reproduce this?

Probably the next step is for you to attach a sample app that reproduces the issue (or a [failing test case][1]).

There's some generic advice on how to fix this kind of issue here: http://bumptech.github.io/glide/doc/resourcereuse.html#common-errors. One other thing to consider is disabling active resources, but if you try that, let me know whether or not it works: 

```java
@Override
public void applyOptions(Context context, GlideBuilder builder) {
  builder.setIsActiveResourceRetentionAllowed(false);
}
```

See the first bullet point in the latest release notes under Behavior Changes: https://github.com/bumptech/glide/releases/tag/v4.4.0

[1]: http://bumptech.github.io/glide/tut/failing-test-cases.html

**Comment by trr-amsiq** [comment]
SimpleTarget is not the issue. We have removed all SimpleTargets from the code and it is still occurring.

**Comment by AnandKhinvasara** [comment]
I am also facing similar issue.

**Comment by trr-amsiq** [comment]
Seems to be fixed in 4.5.0

**Comment by sjudd** [comment]
@trr-amsiq thanks for letting me know, were you using ``RequestBuilder#error(RequestBuilder)`` in your application?

**Comment by trr-amsiq** [comment]
@sjudd  the code looked like this
```
RequestOptions requestOptions = new RequestOptions()
                .fitCenter();

RequestBuilder<Drawable> imageBuilder = Glide.with(context)
                .load(image)
                .apply(requestOptions);

        if (thumb != null) {
            imageBuilder = imageBuilder.thumbnail(
                    Glide.with(context)
                            .load(thumb)
                            .apply(requestOptions));
        }
```
