### ISSUE TITLE
 Request failed 404: OK

### ISSUE THREAD

**Issue by jianglijs** [bumptech/glide#2702]
my url：http://172.16.3.3/images/preset/FarPicNo5.jpg?0.3594843255168094
the problem appear when i click a button to load,but at first i load a dozen pictures is ok. i don,t why.
using okhttp3-integration  also has the same problem.  

1.glide version 'com.github.bumptech.glide:glide:3.8.0'

2. stack
` java.io.IOException: Request failed 404: OK
                                                                        at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:90)
                                                                        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:44)
                                                                        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:20)
                                                                        at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:70)
                                                                        at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:53)
                                                                        at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
                                                                        at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
                                                                        at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:127)
                                                                        at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:106)
                                                                        at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                        at java.lang.Thread.run(Thread.java:761)
                                                                        at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)`

3.my usage
 public static void loadImage(final ImageView imageView, String uri, @DrawableRes int
            placeholderImageRes, int width, int height, boolean centerCrop, boolean noneCache,
                                 final Action onSuccessCommand, final Action
                                         onFailureCommand) {
        DrawableRequestBuilder<String> requestBuilder = Glide.with(imageView.getContext())
                .load(uri)
                .crossFade();
        if (!noneCache) {
            requestBuilder.diskCacheStrategy(DiskCacheStrategy.RESULT);
        } else {
            requestBuilder.diskCacheStrategy(DiskCacheStrategy.NONE);
        }
        if (!centerCrop) {
            requestBuilder.centerCrop();
        }
        if (placeholderImageRes > 0) {
            requestBuilder.placeholder(placeholderImageRes);
            requestBuilder.error(placeholderImageRes);
        }
        if (width > 0 && height > 0) {
            requestBuilder.override(width, height);
        }
        requestBuilder.into(imageView);
    }

**Comment by sjudd** [comment]
``404`` is an HTTP error code that means "Not Found". Either your server has an error, or you're trying to load an image that no longer exists.

**Comment by jianglijs** [comment]
but i use picasso is OK

**Comment by jianglijs** [comment]
thank you for reply so fast.thanks you.
I think it is a problem,but i don,t find the reason. and i use chrome to browse it, also ok.

**Comment by sjudd** [comment]
I don't seem to be able to load it from the US, but maybe that's unrelated.

The other option is that the whitelisting in GlideUrl isn't correct, there was recently a fix here: 014bf4482637f7fb7abe1febb0e6796d3e04a2dc.

You probably won't be able to easily cherry pick that into the v3 branch, but you could manually apply the same fix and build Glide yourself.

Unfortunately we're only working on Glide v4 now, so the only other advice I can offer if it is an issue with Glide is for you to consider [migrating][1] to Glide v4.

[1]: http://bumptech.github.io/glide/doc/migrating.html

**Comment by Muyangmin** [comment]
@sjudd 172.16.3.3 seems to be a *LAN address*, so we might never load that image outside.

@jianglijs I also suggest you to try Glide v4 for the same image in another sample project. If problem still exists, maybe you can just debug glide source to see what's wrong. If possible, you can write a [failing-test-case](https://muyangmin.github.io/glide-docs-cn/tut/failing-test-cases.html) to help us, and remember to use a public image address.
