### ISSUE TITLE
StrictMode warning about an unclosed resourse in okhttp3

### ISSUE THREAD

**Issue by dodatw** [bumptech/glide#2714]
Getting a StrictMode warning on the latest Glide 4.3.1

Some time StrickMode report this issue.
```
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                               java.lang.Throwable: Explicit termination method 'response.body().close()' not called
                                                                   at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at okhttp3.internal.platform.AndroidPlatform$CloseGuard.createAndOpen(AndroidPlatform.java:329)
                                                                   at okhttp3.internal.platform.AndroidPlatform.getStackTraceForCloseable(AndroidPlatform.java:144)
                                                                   at okhttp3.RealCall.captureCallStackTrace(RealCall.java:89)
                                                                   at okhttp3.RealCall.enqueue(RealCall.java:98)
                                                                   at com.bumptech.glide.integration.okhttp3.OkHttpStreamFetcher.loadData(OkHttpStreamFetcher.java:51)
                                                                   at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96)
                                                                   at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:147)
                                                                   at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:141)
                                                                   at com.bumptech.glide.integration.okhttp3.OkHttpStreamFetcher.onFailure(OkHttpStreamFetcher.java:73)
                                                                   at okhttp3.RealCall$AsyncCall.execute(RealCall.java:161)
                                                                   at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                   at java.lang.Thread.run(Thread.java:818)
```

**Comment by sjudd** [comment]
What version of Android/OkHttp are you using? Please always fill out [the issue template][1] when filing new issues.

[1]: https://github.com/bumptech/glide/blob/0cffd1da977e9ca334032ebc1d798213a177aab7/ISSUE_TEMPLATE.md
