### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/load/engine+DecodeJob

### ISSUE THREAD

**Issue by michael-snow** [bumptech/glide#2727]
**Glide Version**: 4.3.0

**Integration libraries**: NO

**Device/Android Version**: Galaxy J3(2016) 5.1.1

**Issue details / Repro steps / Use case background**: 

**Stack trace / LogCat**:
```ruby
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/load/engine+DecodeJob;
       at com.bumptech.glide.load.engine.Engine$DecodeJobFactory$1.create(Engine.java:418)
       at com.bumptech.glide.load.engine.Engine$DecodeJobFactory$1.create(Engine.java:415)
       at com.bumptech.glide.util.pool.FactoryPools$FactoryPool.acquire(FactoryPools.java:146)
       at com.bumptech.glide.load.engine.Engine$DecodeJobFactory.build(Engine.java:444)
       at com.bumptech.glide.load.engine.Engine.load(Engine.java:210)
       at com.bumptech.glide.request.SingleRequest.onSizeReady(SingleRequest.java:443)
       at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.getSize(ViewTarget.java:250)
       at com.bumptech.glide.request.target.ViewTarget.getSize(ViewTarget.java:89)
       at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:257)
       at com.bumptech.glide.manager.RequestTracker.resumeRequests(RequestTracker.java:95)
       at com.bumptech.glide.RequestManager.resumeRequests(RequestManager.java:245)
       at com.bumptech.glide.RequestManager.onStart(RequestManager.java:268)
       at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStart(ActivityFragmentLifecycle.java:50)
       at com.bumptech.glide.manager.SupportRequestManagerFragment.onStart(SupportRequestManagerFragment.java:175)
       at android.support.v4.app.Fragment.performStart(Fragment.java:2287)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1458)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
       at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:7007)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by java.lang.ClassNotFoundException: Didn't find class "com.bumptech.glide.load.engine+DecodeJob" on path: DexPathList[[zip file "/data/app/com.package.appname-1/base.apk"],nativeLibraryDirectories=[/data/app/com.package.appname-1/lib/arm, /vendor/lib, /system/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
       at com.bumptech.glide.load.engine.Engine$DecodeJobFactory$1.create(Engine.java:418)
       at com.bumptech.glide.load.engine.Engine$DecodeJobFactory$1.create(Engine.java:415)
       at com.bumptech.glide.util.pool.FactoryPools$FactoryPool.acquire(FactoryPools.java:146)
       at com.bumptech.glide.load.engine.Engine$DecodeJobFactory.build(Engine.java:444)
       at com.bumptech.glide.load.engine.Engine.load(Engine.java:210)
       at com.bumptech.glide.request.SingleRequest.onSizeReady(SingleRequest.java:443)
       at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.getSize(ViewTarget.java:250)
       at com.bumptech.glide.request.target.ViewTarget.getSize(ViewTarget.java:89)
       at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:257)
       at com.bumptech.glide.manager.RequestTracker.resumeRequests(RequestTracker.java:95)
       at com.bumptech.glide.RequestManager.resumeRequests(RequestManager.java:245)
       at com.bumptech.glide.RequestManager.onStart(RequestManager.java:268)
       at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStart(ActivityFragmentLifecycle.java:50)
       at com.bumptech.glide.manager.SupportRequestManagerFragment.onStart(SupportRequestManagerFragment.java:175)
       at android.support.v4.app.Fragment.performStart(Fragment.java:2287)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1458)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
       at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:7007)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by sjudd** [comment]
Probably an issue with your build, either you're including multiple version of Glide, are running in to a multi dex issue, or have some unusual proguard config.

**Comment by michael-snow** [comment]
gradle

`implementation 'com.github.bumptech.glide:glide:4.3.1'
 annotationProcessor 'com.github.bumptech.glide:compiler:4.3.1'
 implementation('com.github.bumptech.glide:recyclerview-integration:4.3.1') { transitive = false }
`


proguard

`
-optimizationpasses 5
-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-dontskipnonpubliclibraryclassmembers
-dontpreverify
-repackageclasses ''
-allowaccessmodification
-verbose
-keepclassmembers class fqcn.of.javascript.interface.for.webview {
   public *;
}
-keep public class * extends android.view.View {
 public <init>(android.content.Context);
 public <init>(android.content.Context, android.util.AttributeSet);
 public <init>(android.content.Context, android.util.AttributeSet, int);
 public void set*(...);
}
-keepclasseswithmembers class * {
 public <init>(android.content.Context, android.util.AttributeSet);
}
-keepclasseswithmembers class * {
 public <init>(android.content.Context, android.util.AttributeSet, int);
}
-dontwarn okio.**
-dontwarn javax.annotation.**
-dontnote retrofit2.Platform
-dontwarn retrofit2.Platform$Java8
-keepattributes Signature
-keepattributes Exceptions
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**

-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.AppGlideModule
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
    **[] $VALUES;
    public *;
}

-dontwarn android.support.**
-dontwarn android.support.v4.**
-keep class android.support.v4.** { *; }
-keep interface android.support.v4.** { *; }
-dontwarn android.support.v7.**
-keep class android.support.v7.** { *; }
-keep interface android.support.v7.** { *; }

-dontwarn android.support.design.**
-keep class android.support.design.** { *; }
-keep interface android.support.design.** { *; }
-keep public class android.support.design.R$* { *; }

-keep class com.crashlytics.** { *; }
-keep class com.crashlytics.android.**
-keepattributes SourceFile, LineNumberTable, *Annotation*
-dontwarn com.crashlytics.**
-keepnames class * implements android.os.Parcelable {public static final ** CREATOR;}
-keep class * implements java.io.Serializable { *; }
-keep class com.google.** { *; }
-keep interface com.google.** { *; }
-keep class org.appspot.apprtc.**  { *; }
-keep class de.tavendo.autobahn.**  { *; }
-keepclasseswithmembernames class * {native <methods>;}
-dontwarn org.chromium.**
-dontwarn com.google.devtools.build.android.desugar.runtime.ThrowableExtension
-dontwarn com.googlecode.mp4parser.**
-keepattributes EnclosingMethod
-keepattributes InnerClasses
 `
