### ISSUE TITLE
Canvas: trying to use a recycled bitmap

### ISSUE THREAD

**Issue by SpiritMan** [bumptech/glide#2731]
Glide v3.8.0

`Glide
                    .load(item.gifurl)
                    .asGif()
                    .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                    .into(mPreviewImg);`

`java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@c98b8fb
	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1404)
	at com.bumptech.glide.load.resource.gif.GifDrawable.draw(GifDrawable.java)
	at android.widget.ImageView.onDraw(ImageView.java:1228)
	at android.view.View.draw(View.java:16201)
	at android.view.View.updateDisplayListIfDirty(View.java:15198)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.draw(View.java:16204)
	at android.view.View.updateDisplayListIfDirty(View.java:15198)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.draw(View.java:16204)
	at android.support.v7.widget.RecyclerView.draw(RecyclerView.java)
	at android.view.View.updateDisplayListIfDirty(View.java:15198)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.draw(View.java:16204)
	at android.support.v4.view.ViewPager.draw(ViewPager.java)
	at android.view.View.updateDisplayListIfDirty(View.java:15198)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.draw(View.java:16204)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
	at android.view.View.updateDisplayListIfDirty(View.java:15198)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:282)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:288)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2642)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2461)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2094)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
	at android.view.Choreographer.doCallbacks(Choreographer.java:672)
	at android.view.Choreographer.doFrame(Choreographer.java:608)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
	at android.os.Handler.handleCallback(Handler.java:742)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:5524)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)`

i use glide show gif in recycleview

**Comment by sjudd** [comment]
https://github.com/bumptech/glide/wiki/Resource-re-use-in-Glide#common-mistakes
