### ISSUE TITLE
com.bumptech.glide.request.GenericRequest.getErrorDrawable throws exception on vector drawable

### ISSUE THREAD

**Issue by KMKnation** [bumptech/glide#2742]
**Glide Version**:
3.7.0

**Device/Android Version**:
Error throws on Galaxy S4 4.4.4 SGH-M919 and works other devices

**Issue details / Repro steps / Use case background**: 
should display error vector drawable

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(context)
                        .load(path)
                        .fitCenter()
                        .override(72, 72)
                        .centerCrop()
                        .error(R.drawable.ic_white_circular_profile_pic)
                        .into(imageView);
```

**Stack trace / LogCat**:
```java
UnknownException
at drawable.graphics.android.Drawable.createFromXmlInner(Drawable.java:986)
at drawable.graphics.android.Drawable.createFromXml(Drawable.java:930)
at res.content.android.Resources.loadDrawable(Resources.java:3435)
at res.content.android.Resources.getDrawable(Resources.java:1893)
at request.glide.bumptech.com.GenericRequest.getErrorDrawable(GenericRequest.java:409)
at request.glide.bumptech.com.GenericRequest.setErrorPlaceholder(GenericRequest.java:399)
at request.glide.bumptech.com.GenericRequest.onException(GenericRequest.java:548)
at engine.load.glide.bumptech.com.EngineJob.handleExceptionOnMainThread(EngineJob.java:183)
at engine.load.glide.bumptech.com.EngineJob.access$200(EngineJob.java:22)
at engine.load.glide.bumptech.com.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:204)
at os.android.Handler.dispatchMessage(Handler.java:98)
at os.android.Looper.loop(Looper.java:146)
at app.android.ActivityThread.main(ActivityThread.java:5635)
at reflect.lang.java.Method.invokeNative(Native Method)
at reflect.lang.java.Method.invoke(Method.java:515)
at os.internal.android.com.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at os.internal.android.com.ZygoteInit.main(ZygoteInit.java:1107)
at system.dalvik.NativeStart.main(Native Method)
res.content.android.Resources$NotFoundException: (File res/drawable/ic_white_circular_profile_pic.xml from drawable resource ID #0x7f0200b2. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEna
at res.content.android.Resources.loadDrawable(Resources.java:3439)
at res.content.android.Resources.getDrawable(Resources.java:1893)
at request.glide.bumptech.com.GenericRequest.getErrorDrawable(GenericRequest.java:409)
at request.glide.bumptech.com.GenericRequest.setErrorPlaceholder(GenericRequest.java:399)
at request.glide.bumptech.com.GenericRequest.onException(GenericRequest.java:548)
at engine.load.glide.bumptech.com.EngineJob.handleExceptionOnMainThread(EngineJob.java:183)
at engine.load.glide.bumptech.com.EngineJob.access$200(EngineJob.java:22)
at engine.load.glide.bumptech.com.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:204)
at os.android.Handler.dispatchMessage(Handler.java:98)
at os.android.Looper.loop(Looper.java:146)
at app.android.ActivityThread.main(ActivityThread.java:5635)
at reflect.lang.java.Method.invokeNative(Native Method)
at reflect.lang.java.Method.invoke(Method.java:515)
at os.internal.android.com.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at os.internal.android.com.ZygoteInit.main(ZygoteInit.java:1107)
at system.dalvik.NativeStart.main(Native Method)

```

**Comment by sjudd** [comment]
Probably because older versions of Android don't support vector Drawables out of the box. I'd guess the other devices you mentioned are on newer versions of Android?

If so, this is fixed in Glide v4 where we use the support library (if it's included in your project). Unfortunately no further updates are planned for v3, so if you want vector drawables to work across all versions of Android as placeholders in Glide, you'll need to upgrade.
