### ISSUE TITLE
Unable to load svg with the provided sample code

### ISSUE THREAD

**Issue by Devenias** [bumptech/glide#2753]
I've upgraded today from **Glide v3.7.0 to v4.4.0** and was making adjustments following the migration guide.
Previously I used the sample code for v3 to load SVG images and it worked like a charm. After the upgrade with the updated sample code SVG aren't loaded anymore.

I updated following dependencies:
```
dependencies {
    implementation 'com.github.bumptech.glide:glide:4.4.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.4.0'
    implementation 'com.caverock:androidsvg:1.2.1'
}
```
also **Volley** is used for network requests but not as a GlideModule. (so glide uses its own?)

The sample code contains a SvgModule, which registers the component for decoding and transcoding:
```
registry.register(SVG.class, PictureDrawable.class, new SvgDrawableTranscoder())
                .append(InputStream.class, SVG.class, new SvgDecoder());
```

For loading the SVG images I use:
```
RequestBuilder<PictureDrawable> mSvgRequestBuilder = Glide.with(context)
                .as(PictureDrawable.class)
                .listener(new SvgSoftwareLayerSetter());

RequestOptions options = new RequestOptions()
                .diskCacheStrategy(DiskCacheStrategy.RESOURCE);

        mSvgRequestBuilder
                .load(uri)
                .apply(options)
                .into(imageView);
```

I get following error message:
```
Request threw uncaught throwable
	com.bumptech.glide.Registry$NoResultEncoderAvailableException: Failed to find result encoder for resource class: class com.caverock.androidsvg.SVG
	at com.bumptech.glide.load.engine.DecodeJob$DecodeCallback.onResourceDecoded(DecodeJob.java:559)
	at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:45)
	at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
	at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
	at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:499)
	at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:471)
	at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:457)
	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:411)
	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:380)
	at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
	at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:69)
	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:303)
	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:273)
	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:445)


Load failed for https://my.host.enpoint/images/someUninteresting.svg with size [118x118]
	class com.bumptech.glide.load.engine.GlideException: Failed to load resource
	Cause (1 of 1): class com.bumptech.glide.Registry$NoResultEncoderAvailableException: Failed to find result encoder for resource class: class com.caverock.androidsvg.SVG
```

There was no need for an encoder before (I think it was done by the transcoder) and there is no sample for an svg encoder in the sample app. Do I miss something?

**Comment by sjudd** [comment]
You're using ``RequestOptions options = new RequestOptions().diskCacheStrategy(DiskCacheStrategy.RESOURCE);`` which requires an encoder.

**Comment by Devenias** [comment]
I think I tried it already without RequestOptions, with the same result. Do I have to set DiskCacheStrategy.NONE to disable it?
Nevertheless I have to write an encoder now, even though I don't understand why it worked without encoder in v3.
Thanks so far. I'll give it a shot on wednesday.

**Comment by sjudd** [comment]
Huh I don't see a `DiskCacheStrategy` in the current SVG sample. I'm not actually sure why that works. Sorry... let me know what you find.

**Comment by Devenias** [comment]
In the SVG sample is no `DiskCacheStrategy`, but I added it in my released app version with **Glide v3**. There were no problems with that and caching worked and I didn't need an encoder. That's why I was confused after upgrading to **Glide v4**.
I wrote an `SvgEncoder` now and it works again. Thanks for your help :)

**Comment by huopochuan** [comment]
How to fix it？ SvgEncoder ? can you write a sample

**Comment by akfpnd** [comment]
@Devenias yes please provide exact example of `SvgEncoder` and how to use it for this [sample](https://github.com/bumptech/glide/tree/master/samples/svg)?
I facing the same issue 😥

**Comment by atonamy** [comment]
@huopochuan I managed to find the solution (thanks to the help of GPT-4):

```
import android.graphics.Bitmap
import android.graphics.Canvas
import com.bumptech.glide.load.EncodeStrategy
import com.bumptech.glide.load.Options
import com.bumptech.glide.load.ResourceEncoder
import com.bumptech.glide.load.engine.Resource
import com.bumptech.glide.load.engine.bitmap_recycle.ArrayPool
import com.bumptech.glide.load.engine.bitmap_recycle.BitmapPool
import com.caverock.androidsvg.SVG
import java.io.File
import com.bumptech.glide.load.resource.bitmap.BitmapEncoder
import com.bumptech.glide.load.resource.bitmap.BitmapResource

class SvgEncoder(arrayPool: ArrayPool, private val bitmapPool: BitmapPool) : ResourceEncoder<SVG> {

    private val bitmapEncoder: BitmapEncoder = BitmapEncoder(arrayPool)

    override fun encode(data: Resource<SVG>, file: File, options: Options): Boolean {
        val svg = data.get()
        val picture = svg.renderToPicture()
        val width = picture.width
        val height = picture.height
        val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(bitmap)

        picture.draw(canvas)

        return bitmapEncoder.encode(BitmapResource.obtain(bitmap, bitmapPool) ?: return false, file, options)
    }

    override fun getEncodeStrategy(options: Options): EncodeStrategy {
        return bitmapEncoder.getEncodeStrategy(options)
    }
}
```
