### ISSUE TITLE
Images present but Glide loading only few images

### ISSUE THREAD

**Issue by Masquerade0097** [bumptech/glide#2756]
**Glide Version**: 
4.2.0

**Integration libraries**:
com.github.chrisbanes:PhotoView:2.1.3

**Device/Android Version**:
I've tested it on Moto G4 Plus and the issue arises

**Issue details / Repro steps / Use case background**: 
Glide is loading some images into the photoview but fails to load other images in the same directory. There are some buttons in my app which on clicking send it's corresponding uri to Glide which loads it and displays it. But Glide is working fine for some images( size 100 Kb to 250 Kb ) but not working for others similar images( size 100 Kb - 250 Kb). I tried reducing the image size but still the problem persists.This is the error log - 

```
W/Glide: Load failed for file:///storage/emulated/0/hhp_images/cylhd_chang.jpg with size [1080x1704]
         class com.bumptech.glide.load.engine.GlideException: Failed to load resource
           Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, LOCAL
             Cause (1 of 1): class java.io.FileNotFoundException: /storage/emulated/0/hhp_images/cylhd_chang.jpg (No such file or directory)
           Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.os.ParcelFileDescriptor, LOCAL
             Cause (1 of 1): class java.io.FileNotFoundException: No such file or directory
I/Glide: Root cause (1 of 2)
         java.io.FileNotFoundException: /storage/emulated/0/hhp_images/cylhd_chang.jpg (No such file or directory)
             at java.io.FileInputStream.open(Native Method)
             at java.io.FileInputStream.<init>(FileInputStream.java:146)
             at java.io.FileInputStream.<init>(FileInputStream.java:99)
             at android.content.ContentResolver.openInputStream(ContentResolver.java:700)
             at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResourceFromUri(StreamLocalUriFetcher.java:87)
             at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResource(StreamLocalUriFetcher.java:62)
             at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResource(StreamLocalUriFetcher.java:17)
             at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:41)
             at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
             at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:293)
             at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:263)
             at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
             at java.lang.Thread.run(Thread.java:761)
             at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:386)
I/Glide: Root cause (2 of 2)
         java.io.FileNotFoundException: No such file or directory
             at android.os.Parcel.openFileDescriptor(Native Method)
             at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:283)
             at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:200)
             at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:977)
             at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:905)
             at com.bumptech.glide.load.data.FileDescriptorLocalUriFetcher.loadResource(FileDescriptorLocalUriFetcher.java:22)
             at com.bumptech.glide.load.data.FileDescriptorLocalUriFetcher.loadResource(FileDescriptorLocalUriFetcher.java:14)
             at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:41)
             at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
             at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:293)
             at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherFailed(DecodeJob.java:388)
             at com.bumptech.glide.load.engine.SourceGenerator.onLoadFailed(SourceGenerator.java:118)
             at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:46)
             at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
             at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:293)
             at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:263)
             at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
             at java.lang.Thread.run(Thread.java:761)
             at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:386)

```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

I'm using Glide with christbanes photoview and i got this problem so I tested Glide in a normal Imageview but this problem still exists. This is the code for the activity which takes in the File Uri and displays the image using Glide.
```
 
public class PhotoFullPopupWindow extends PopupWindow {

    View view;
    Context mContext;
    PhotoView photoView;
    ProgressBar loading;
    ViewGroup parent;
    private static PhotoFullPopupWindow instance = null;


    public PhotoFullPopupWindow(Context ctx, int layout, View v, String imageUrl, Bitmap bitmap) {
        super(((LayoutInflater) ctx.getSystemService(LAYOUT_INFLATER_SERVICE)).inflate( R.layout.popup_photo_full, null)
                , ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT);

        if (Build.VERSION.SDK_INT >= 21) {
            setElevation(5.0f);
        }

        this.mContext = ctx;
        this.view = getContentView();
        ImageButton closeButton = (ImageButton) this.view.findViewById(R.id.ib_close);
        setOutsideTouchable(true);

        setFocusable(true);
        closeButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                dismiss();
            }
        });

        photoView = (PhotoView) view.findViewById(R.id.image);
        photoView.setMaximumScale(6);
        parent = (ViewGroup) photoView.getParent();

        if (bitmap != null) {
            if (Build.VERSION.SDK_INT >= 16) {
                parent.setBackground(new BitmapDrawable(mContext.getResources(), Constants.fastblur(Bitmap.createScaledBitmap(bitmap, 50, 50, true))));// ));
            } else {
                onPalette(Palette.from(bitmap).generate());

            }
            photoView.setImageBitmap(bitmap);
        } else {

            GlideApp.with(ctx) .asBitmap()
                    .load(Uri.fromFile(new File(imageUrl)))
                    .error(R.drawable.sample_image)
                    .listener(new RequestListener<Bitmap>() {
                        @Override
                        public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Bitmap> target, boolean isFirstResource) {

                            Toast.makeText(mContext, "Error: Unable to open image", Toast.LENGTH_SHORT).show();
                            return false;
                        }

                        @Override
                        public boolean onResourceReady(Bitmap resource, Object model, Target<Bitmap> target, DataSource dataSource, boolean isFirstResource) {
                            if (Build.VERSION.SDK_INT >= 16) {
                                parent.setBackgroundColor(Color.BLACK);
                            } else {
                                onPalette(Palette.from(resource).generate());

                            }
                            photoView.setImageBitmap(resource);

                            return false;
                        }
                    })



                    .diskCacheStrategy(DiskCacheStrategy.ALL)
                    .into(photoView);

            showAtLocation(v, Gravity.CENTER, 0, 0);
        }

    }

    public void onPalette(Palette palette) {
        if (null != palette) {
            ViewGroup parent = (ViewGroup) photoView.getParent().getParent();
            parent.setBackgroundColor(palette.getDarkVibrantColor(Color.GRAY));
        }
    }
}
```

**Layout XML**:
```
<com.github.chrisbanes.photoview.PhotoView
        android:id="@+id/image"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

```

**Comment by sjudd** [comment]
The relevant error is here: 

```
         java.io.FileNotFoundException: /storage/emulated/0/hhp_images/cylhd_chang.jpg (No such file or directory)
             at java.io.FileInputStream.open(Native Method)
             at java.io.FileInputStream.<init>(FileInputStream.java:146)
             at java.io.FileInputStream.<init>(FileInputStream.java:99)
             at android.content.ContentResolver.openInputStream(ContentResolver.java:700)
             at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResourceFromUri(StreamLocalUriFetcher.java:87)
             at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResource(StreamLocalUriFetcher.java:62)
             at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResource(StreamLocalUriFetcher.java:17)
             at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:41)
             at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
             at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:293)
             at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:263)
             at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
             at java.lang.Thread.run(Thread.java:761)
```

That implies that the File you're trying to load isn't at the path you expect.

**Comment by Masquerade0097** [comment]
@sjudd The file exists I've checked it. I'm also checking for external storage permission at runtime, which I have but still I'm getting this error

**Comment by sjudd** [comment]
If you can reproduce it in a sample app on an emulator I'm happy to take a look. Otherwise I'm not sure what to suggest. Maybe there's an issue with the device you're using?

**Comment by Masquerade0097** [comment]
*SOLVED* @sjudd you're right. The problem was not with Glide, it was with my device. I tested the app on other devices and it worked.
