### ISSUE TITLE
File unsuitable for memory mapping

### ISSUE THREAD

**Issue by EricBigGod** [bumptech/glide#2794]
**Glide Version**: 4.4.0

**Integration libraries**:
"com.squareup.okhttp3:okhttp:3.6.0",
"com.squareup.okhttp3:logging-interceptor:3.6.0",
"com.github.bumptech.glide:glide:4.4.0",
'com.github.bumptech.glide:compiler:4.4.0',
"com.github.bumptech.glide:okhttp3-integration:4.4.0",

**Device/Android Version**:
HuaWei Honor V9 DUK-AL20     Android7.0     EMUI5.1

**Issue details / Repro steps / Use case background**: 
I'm loading a avatar from server,but it's fail. Then i get a log from logcat. What's going to happen?

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(applicationGlobalContext())
                                .asBitmap()
                                .load(Utils.getImageCompress(avatarUrl))
                                .apply(new RequestOptions().placeholder(R.drawable.placeholder_square)
                                .dontAnimate())
                                .into(mRivHead);
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
01-08 16:57:54.050 10412-10412/? I/Glide: Root cause (1 of 4)
                                          java.io.IOException: File unsuitable for memory mapping
                                              at com.b.a.i.a.a(ByteBufferUtil.java:39)
                                              at com.b.a.c.c.d$a.a(ByteBufferFileLoader.java:63)
                                              at com.b.a.c.b.b.a(DataCacheGenerator.java:71)
                                              at com.b.a.c.b.g.k(DecodeJob.java:303)
                                              at com.b.a.c.b.g.i(DecodeJob.java:270)
                                              at com.b.a.c.b.g.run(DecodeJob.java:234)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                              at java.lang.Thread.run(Thread.java:776)
                                              at com.b.a.c.b.c.a$a$1.run(GlideExecutor.java:445)
01-08 16:57:54.050 10412-10412/? I/Glide: Root cause (2 of 4)
                                          java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
                                              at com.b.a.c.d.a.v.a(VideoBitmapDecoder.java:138)
                                              at com.b.a.c.d.a.v.a(VideoBitmapDecoder.java:25)
                                              at com.b.a.c.b.h.a(DecodePath.java:68)
                                              at com.b.a.c.b.h.a(DecodePath.java:53)
                                              at com.b.a.c.b.h.a(DecodePath.java:44)
                                              at com.b.a.c.b.s.a(LoadPath.java:56)
                                              at com.b.a.c.b.s.a(LoadPath.java:42)
                                              at com.b.a.c.b.g.a(DecodeJob.java:499)
                                              at com.b.a.c.b.g.a(DecodeJob.java:471)
                                              at com.b.a.c.b.g.a(DecodeJob.java:457)
                                              at com.b.a.c.b.g.n(DecodeJob.java:411)
                                              at com.b.a.c.b.g.a(DecodeJob.java:380)
                                              at com.b.a.c.b.b.a(DataCacheGenerator.java:91)
                                              at com.b.a.c.c.f$c.a(FileLoader.java:76)
                                              at com.b.a.c.b.b.a(DataCacheGenerator.java:71)
                                              at com.b.a.c.b.g.k(DecodeJob.java:303)
                                              at com.b.a.c.b.g.n(DecodeJob.java:419)
                                              at com.b.a.c.b.g.a(DecodeJob.java:380)
                                              at com.b.a.c.b.b.a(DataCacheGenerator.java:91)
                                              at com.b.a.c.c.f$c.a(FileLoader.java:76)
                                              at com.b.a.c.b.b.a(DataCacheGenerator.java:71)
                                              at com.b.a.c.b.g.k(DecodeJob.java:303)
                                              at com.b.a.c.b.g.a(DecodeJob.java:398)
                                              at com.b.a.c.b.b.a(DataCacheGenerator.java:96)
                                              at com.b.a.c.c.d$a.a(ByteBufferFileLoader.java:68)
                                              at com.b.a.c.b.b.a(DataCacheGenerator.java:71)
                                              at com.b.a.c.b.g.k(DecodeJob.java:303)
                                              at com.b.a.c.b.g.i(DecodeJob.java:270)
                                              at com.b.a.c.b.g.run(DecodeJob.java:234)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                              at java.lang.Thread.run(Thread.java:776)
                                              at com.b.a.c.b.c.a$a$1.run(GlideExecutor.java:445)
                                           Caused by: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
                                              at android.media.MediaMetadataRetriever.setDataSource(Native Method)
                                              at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:136)
                                              at com.b.a.c.d.a.v.a(VideoBitmapDecoder.java:128)
                                              at com.b.a.c.d.a.v.a(VideoBitmapDecoder.java:25) 
                                              at com.b.a.c.b.h.a(DecodePath.java:68) 
                                              at com.b.a.c.b.h.a(DecodePath.java:53) 
                                              at com.b.a.c.b.h.a(DecodePath.java:44) 
                                              at com.b.a.c.b.s.a(LoadPath.java:56) 
                                              at com.b.a.c.b.s.a(LoadPath.java:42) 
                                              at com.b.a.c.b.g.a(DecodeJob.java:499) 
                                              at com.b.a.c.b.g.a(DecodeJob.java:471) 
                                              at com.b.a.c.b.g.a(DecodeJob.java:457) 
                                              at com.b.a.c.b.g.n(DecodeJob.java:411) 
                                              at com.b.a.c.b.g.a(DecodeJob.java:380) 
                                              at com.b.a.c.b.b.a(DataCacheGenerator.java:91) 
                                              at com.b.a.c.c.f$c.a(FileLoader.java:76) 
                                              at com.b.a.c.b.b.a(DataCacheGenerator.java:71) 
                                              at com.b.a.c.b.g.k(DecodeJob.java:303) 
                                              at com.b.a.c.b.g.n(DecodeJob.java:419) 
                                              at com.b.a.c.b.g.a(DecodeJob.java:380) 
                                              at com.b.a.c.b.b.a(DataCacheGenerator.java:91) 
                                              at com.b.a.c.c.f$c.a(FileLoader.java:76) 
                                              at com.b.a.c.b.b.a(DataCacheGenerator.java:71) 
                                              at com.b.a.c.b.g.k(DecodeJob.java:303) 
                                              at com.b.a.c.b.g.a(DecodeJob.java:398) 
                                              at com.b.a.c.b.b.a(DataCacheGenerator.java:96) 
                                              at com.b.a.c.c.d$a.a(ByteBufferFileLoader.java:68) 
                                              at com.b.a.c.b.b.a(DataCacheGenerator.java:71) 
                                              at com.b.a.c.b.g.k(DecodeJob.java:303) 
                                              at com.b.a.c.b.g.i(DecodeJob.java:270) 
                                              at com.b.a.c.b.g.run(DecodeJob.java:234) 
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                              at java.lang.Thread.run(Thread.java:776) 
                                              at com.b.a.c.b.c.a$a$1.run(GlideExecutor.java:445) 
```

**Comment by EricBigGod** [comment]
I/Glide: Root cause (5 of 5)
                                                        java.io.FileNotFoundException: No content provider: http://192.168.32.112:8888/member/headPortrait/20180108/93c8c29b34cd4df699b5188cbe481fcc_compress.jpg
                                                            at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1059)
                                                            at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:914)
                                                            at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:841)
                                                            at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:22)
                                                            at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:13)
                                                            at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
                                                            at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
                                                            at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
                                                            at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:415)
                                                            at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:376)
                                                            at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:135)
                                                            at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
                                                            at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:76)
                                                            at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
                                                            at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
                                                            at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
                                                            at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:415)
                                                            at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:376)
                                                            at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:135)
                                                            at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
                                                            at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:76)
                                                            at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
                                                            at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
                                                            at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
                                                            at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherFailed(DecodeJob.java:394)
                                                            at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherFailed(SourceGenerator.java:141)
                                                            at com.bumptech.glide.load.engine.DataCacheGenerator.onLoadFailed(DataCacheGenerator.java:100)
                                                            at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:70)
                                                            at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
                                                            at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
                                                            at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
                                                            at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
                                                            at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                            at java.lang.Thread.run(Thread.java:841)
                                                            at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)

**Comment by sjudd** [comment]
It's probably unrelated, but if you can provide the actual full stack trace with all of the causes I might be able to help more. De-obfuscated stack traces would also be helpful.

**Comment by sjudd** [comment]
Hi @EricBigGod,

It looks like you might not have included some important information when you filed this issue. To make sure we have all the information we need to help with your issue. Please take a look at the [Issue Template](https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md) and make sure you've filled out as many sections as possible.

In particular you **must** include:

* Glide Version
* Glide load line
* Issue details.

I'm marking this issue as requiring more information. Please understand that if you do not provide that information or update the issue within the next 7 days this issue will be automatically closed so that it doesn''t clutter the bug tracker.

Best regards,

~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by benlc** [comment]
Running into the same issue, it happens frequently with the set of images I'm working with on one device. For some reason, it doesn't happen on emulator

```


01-23 17:49:24.013 10740-10740/com.theoutbound.theoutbound.debug W/Glide: Load failed for https://images.theoutbound.com/2014/05/04/04/08/37/160/12244307166_50fa5784a8_o.jpg? with size [1008x750]
                                                                          class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                                          There was 1 cause:
                                                                          java.io.FileNotFoundException(No content provider: https://images.theoutbound.com/2014/05/04/04/08/37/160/12244307166_50fa5784a8_o.jpg?)
                                                                           call GlideException#logRootCauses(String) for more detail
                                                                            Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.content.res.AssetFileDescriptor, LOCAL, DataCacheKey{sourceKey=https://images.theoutbound.com/2014/05/04/04/08/37/160/12244307166_50fa5784a8_o.jpg?, signature=EmptySignature}
                                                                          There was 1 cause:
                                                                          java.io.FileNotFoundException(No content provider: https://images.theoutbound.com/2014/05/04/04/08/37/160/12244307166_50fa5784a8_o.jpg?)
                                                                           call GlideException#logRootCauses(String) for more detail
                                                                              Cause (1 of 1): class java.io.FileNotFoundException: No content provider: https://images.theoutbound.com/2014/05/04/04/08/37/160/12244307166_50fa5784a8_o.jpg?
01-23 17:49:24.014 10740-10740/com.theoutbound.theoutbound.debug I/Glide: Root cause (1 of 1)
                                                                          java.io.FileNotFoundException: No content provider: https://images.theoutbound.com/2014/05/04/04/08/37/160/12244307166_50fa5784a8_o.jpg?
                                                                              at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1137)
                                                                              at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:988)
                                                                              at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:911)
                                                                              at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:22)
                                                                              at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:13)
                                                                              at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
                                                                              at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
                                                                              at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
                                                                              at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
                                                                              at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                              at java.lang.Thread.run(Thread.java:762)
                                                                              at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
01-23 17:49:24.015 10740-10740/com.theoutbound.theoutbound.debug I/AdventureBinder: Root cause (1 of 1)
                                                                                    java.io.FileNotFoundException: No content provider: https://images.theoutbound.com/2014/05/04/04/08/37/160/12244307166_50fa5784a8_o.jpg?
                                                                                        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1137)
                                                                                        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:988)
                                                                                        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:911)
                                                                                        at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:22)
                                                                                        at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:13)
                                                                                        at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
                                                                                        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
                                                                                        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
                                                                                        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
                                                                                        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                        at java.lang.Thread.run(Thread.java:762)
                                                                                        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
01-23 17:49:24.016 10740-10740/com.theoutbound.theoutbound.debug W/Glide: Load failed for https://images.theoutbound.com/contents/100515/assets/1416266283028? with size [1008x750]
                                                                          class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                                          There was 1 cause:
                                                                          java.io.FileNotFoundException(No content provider: https://images.theoutbound.com/contents/100515/assets/1416266283028?)
                                                                           call GlideException#logRootCauses(String) for more detail
                                                                            Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.content.res.AssetFileDescriptor, LOCAL, DataCacheKey{sourceKey=https://images.theoutbound.com/contents/100515/assets/1416266283028?, signature=EmptySignature}
                                                                          There was 1 cause:
                                                                          java.io.FileNotFoundException(No content provider: https://images.theoutbound.com/contents/100515/assets/1416266283028?)
                                                                           call GlideException#logRootCauses(String) for more detail
                                                                              Cause (1 of 1): class java.io.FileNotFoundException: No content provider: https://images.theoutbound.com/contents/100515/assets/1416266283028?
01-23 17:49:24.018 10740-10740/com.theoutbound.theoutbound.debug I/Glide: Root cause (1 of 1)
                                                                          java.io.FileNotFoundException: No content provider: https://images.theoutbound.com/contents/100515/assets/1416266283028?
                                                                              at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1137)
                                                                              at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:988)
                                                                              at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:911)
                                                                              at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:22)
                                                                              at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:13)
                                                                              at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
                                                                              at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
                                                                              at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
                                                                              at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
                                                                              at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                              at java.lang.Thread.run(Thread.java:762)
                                                                              at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
01-23 17:49:24.023 10740-10740/com.theoutbound.theoutbound.debug I/AdventureBinder: Root cause (1 of 1)
                                                                                    java.io.FileNotFoundException: No content provider: https://images.theoutbound.com/contents/100515/assets/1416266283028?
                                                                                        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1137)
                                                                                        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:988)
                                                                                        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:911)
                                                                                        at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:22)
                                                                                        at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:13)
                                                                                        at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
                                                                                        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
                                                                                        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
                                                                                        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
                                                                                        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                        at java.lang.Thread.run(Thread.java:762)
                                                                                        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
01-23 17:49:24.129 10740-10740/com.theoutbound.theoutbound.debug W/Glide: Load failed for https://images.theoutbound.com/contents/100477/assets/1507922244086? with size [1008x750]
                                                                          class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                                          There was 1 cause:
                                                                          java.io.FileNotFoundException(No content provider: https://images.theoutbound.com/contents/100477/assets/1507922244086?)
                                                                           call GlideException#logRootCauses(String) for more detail
                                                                            Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.content.res.AssetFileDescriptor, LOCAL, DataCacheKey{sourceKey=https://images.theoutbound.com/contents/100477/assets/1507922244086?, signature=EmptySignature}
                                                                          There was 1 cause:
                                                                          java.io.FileNotFoundException(No content provider: https://images.theoutbound.com/contents/100477/assets/1507922244086?)
                                                                           call GlideException#logRootCauses(String) for more detail
                                                                              Cause (1 of 1): class java.io.FileNotFoundException: No content provider: https://images.theoutbound.com/contents/100477/assets/1507922244086?
01-23 17:49:24.134 10740-10740/com.theoutbound.theoutbound.debug I/Glide: Root cause (1 of 1)
                                                                          java.io.FileNotFoundException: No content provider: https://images.theoutbound.com/contents/100477/assets/1507922244086?
                                                                              at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1137)
                                                                              at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:988)
                                                                              at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:911)
                                                                              at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:22)
                                                                              at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:13)
                                                                              at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
                                                                              at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
                                                                              at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
                                                                              at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
                                                                              at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                              at java.lang.Thread.run(Thread.java:762)
                                                                              at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
01-23 17:49:24.135 10740-10740/com.theoutbound.theoutbound.debug I/AdventureBinder: Root cause (1 of 1)
                                                                                    java.io.FileNotFoundException: No content provider: https://images.theoutbound.com/contents/100477/assets/1507922244086?
                                                                                        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1137)
                                                                                        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:988)
                                                                                        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:911)
                                                                                        at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:22)
                                                                                        at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:13)
                                                                                        at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
                                                                                        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
                                                                                        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
                                                                                        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
                                                                                        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                        at java.lang.Thread.run(Thread.java:762)
                                                                                        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
```

**Comment by EricBigGod** [comment]
I think the reason is that glide saves a invalid picture. Because i upload an original picture to server, then, server will compress the picture in order to get a thumbnail. in the meantime, i use glide to load the thumbnail. I guess the thumbnail is unfinished when i load it.

**Comment by sjudd** [comment]
These are all generic load failed exceptions. Glide is just iterating over every decoder it has to try to find one that will work and then printing the failures when none do. 

If you're unable to decode an image, try decoding it with BitmapFactory directly on the same device. If you're able to decode it with BitmapFactory, please file a new issue with the Glide load line you're using and the image that you're unable to decode.

**Comment by fabio-filho** [comment]
I'm having the same issue :

**Device:** Genymotion Emulator
**Failing on Android API:** 25
**Tested and working on Android APIs:** 21, 22, 23, 24, 26



_Gradle:_
`    /* Glide */
    implementation ("com.github.bumptech.glide:glide:4.6.1") {
        exclude group: "com.android.support"
    }
    implementation "com.android.support:support-fragment:27.1.0"
    kapt 'com.github.bumptech.glide:compiler:4.6.1'`


_Adapter:_
```
Glide.with(context)
                .load("http://192.168.0.101:5558/api/test_picture")
                .into(holder.imgProfile)
```


_Logcat:_
`I/Glide: Root cause (5 of 5)
                                                              java.io.FileNotFoundException: No content provider: http://192.168.0.101:5558/api/test_picture
                                                                  at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1133)
                                                                  at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:984)
                                                                  at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:907)
                                                                  at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:22)
                                                                  at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:13)
                                                                  at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
                                                                  at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:415)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:376)
                                                                  at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:135)
                                                                  at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
                                                                  at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:76)
                                                                  at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
                                                                  at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:415)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:376)
                                                                  at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:135)
                                                                  at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
                                                                  at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:76)
                                                                  at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
                                                                  at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:415)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:376)
                                                                  at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:135)
                                                                  at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
                                                                  at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:74)
                                                                  at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
                                                                  at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                  at java.lang.Thread.run(Thread.java:761)
                                                                  at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)`

**Comment by eshaanb** [comment]
for the record - this can happen if you save jpgs as pngs without doing a conversion it seems like
