### ISSUE TITLE
StandardGifDecoder throws ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by michaeimm** [bumptech/glide#2814]
**Glide Version**: 4.5.0

**Integration libraries**: 

**Device/Android Version**: Sony XZ Premium 8.0.0

StandardGifDecoder throws ArrayIndexOutOfBoundsException when load a GIF. 

> 
> java.lang.ArrayIndexOutOfBoundsException: length=2304; index=2309
>                                                                                at com.bumptech.glide.gifdecoder.StandardGifDecoder.copyIntoScratchFast(StandardGifDecoder.java:532)
>                                                                                at com.bumptech.glide.gifdecoder.StandardGifDecoder.setPixels(StandardGifDecoder.java:481)
>                                                                                at com.bumptech.glide.gifdecoder.StandardGifDecoder.getNextFrame(StandardGifDecoder.java:284)
>                                                                                at com.bumptech.glide.load.resource.gif.GifFrameResourceDecoder.decode(GifFrameResourceDecoder.java:31)
>                                                                                at com.bumptech.glide.load.resource.gif.GifFrameResourceDecoder.decode(GifFrameResourceDecoder.java:16)
>                                                                                at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:69)
>                                                                                at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:53)
>                                                                                at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:44)
>                                                                                at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
>                                                                                at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
>                                                                                at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:497)
>                                                                                at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:469)
>                                                                                at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:455)
>                                                                                at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:407)
>                                                                                at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:376)
>                                                                                at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:112)
>                                                                                at com.bumptech.glide.load.model.UnitModelLoader$UnitFetcher.loadData(UnitModelLoader.java:57)
>                                                                                at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
>                                                                                at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
>                                                                                at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:266)
>                                                                                at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
>                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
>                                                                                at java.lang.Thread.run(Thread.java:764)
>                                                                                at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)

[Here is the GIF.](https://images.plurk.com/19Z5uHZmVDp2RqEJsCrI.gif)

**Comment by sjudd** [comment]
The GIF in question looks corrupt in chrome, which probably explains the exception in Glide. We could improve the error message, but doing so would require a bunch of additional bounds checking  that would make an already slow decode process slower.

If you can reproduce this with a GIF that isn't corrupt, please let me know and attach the GIF.
