### ISSUE TITLE
java.lang.IllegalArgumentException(Bitmap not large enough to support new configuration)

### ISSUE THREAD

**Issue by Mathbl** [bumptech/glide#2818]
**Glide Version**: 4.5.0

**Integration libraries**: okhttp3-integration

**Device/Android Version**: doesn't seem device related

**Issue details / Repro steps / Use case background**: 
Ok, i'm going to try to give as much details as possible and be concise.

I have a list of conversations (think facebook messenger). When it's a group conversation, I show the avatars of the users in a custom view (DuoAvatarLayout, a layout that wraps two `ImageView`) that shows the pictures side-by-side in a circle:
![](https://dha4w82d62smt.cloudfront.net/items/410O140a3l3w0g003Z1s/%5B194cf79c38be9f03b81ca42929362ff6%5D_Image+2018-01-16+at+4.14.00+PM.png)

Here's the class:
```java
public class DuoAvatarLayout extends LinearLayout {

    private Bitmap maskBitmap;
    private Paint paint, maskPaint;
    private float radius;

    public DuoAvatarLayout(Context context) {
        super(context);
        init(context, null, 0);
    }

    // Other constructors omitted for sake of brevity 
    
    private void init(Context context, AttributeSet attrs, int defStyle) {
        paint = new Paint(Paint.ANTI_ALIAS_FLAG);

        maskPaint = new Paint(Paint.ANTI_ALIAS_FLAG | Paint.FILTER_BITMAP_FLAG);
        maskPaint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.CLEAR));
        radius = getResources().getDimension(R.dimen.avatar_layout_radius);

        setWillNotDraw(false);
    }

    @Override
    public void draw(Canvas canvas) {
        Bitmap offscreenBitmap = Bitmap.createBitmap(canvas.getWidth(), canvas.getHeight(), Bitmap.Config.ARGB_8888);
        Canvas offscreenCanvas = new Canvas(offscreenBitmap);
        super.draw(offscreenCanvas);

        if (maskBitmap == null) {
            maskBitmap = createMask(canvas.getWidth(), canvas.getHeight());
        }

        offscreenCanvas.drawBitmap(maskBitmap, 0f, 0f, maskPaint);
        canvas.drawBitmap(offscreenBitmap, 0f, 0f, paint);
    }

    private Bitmap createMask(int width, int height) {
        Bitmap mask = Bitmap.createBitmap(width, height, Bitmap.Config.ALPHA_8);
        Canvas canvas = new Canvas(mask);

        Paint paint = new Paint(Paint.ANTI_ALIAS_FLAG);
        paint.setColor(Color.WHITE);

        canvas.drawRect(0, 0, width, height, paint);
        paint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.CLEAR));
        canvas.drawCircle(radius, radius, radius, paint);

        return mask;
    }
}
```
And the layout:
```xml
<com.myapp.views.widgets.DuoAvatarLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/duo_avatar_layout_container"
    android:layout_width="50dp"
    android:layout_height="50dp"
    android:orientation="horizontal"
    >

    <ImageView
        android:id="@+id/duo_avatar_image_left"
        android:layout_width="25dp"
        android:layout_height="50dp"
        android:scaleType="centerCrop"
        />

    <View
        android:layout_width="2dp"
        android:layout_height="match_parent"
        android:paddingHorizontal="2dp"
        android:background="@color/white"
        />

    <ImageView
        android:id="@+id/duo_avatar_image_right"
        android:layout_width="25dp"
        android:layout_height="50dp"
        android:scaleType="centerCrop"
        />

</com.myapp.views.widgets.DuoAvatarLayout>
```
When the user has no picture, the API returns a 300x300 image with the initials of the user. For some reasons (and it's intermittent, it doesn't always happen and I can't seem to understand what's different when it does), sometimes one of these image won't load and I get the stacktrace below. It doesn't crash the app though.
```java
01-16 15:43:56.285 D/Glide: Finished loading BitmapDrawable from DATA_DISK_CACHE for http://192.168.1.171:5060/api/avatars/1-jb.png with size [66x61] in 212.897 ms
01-16 15:43:56.287 W/Glide: Load failed for http://192.168.1.171:5060/api/avatars/1-jb.png with size [66x131]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.lang.IllegalArgumentException(Bitmap not large enough to support new configuration)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class java.lang.IllegalArgumentException: Bitmap not large enough to support new configuration
01-16 15:43:56.288 I/Glide: Root cause (1 of 1)
    java.lang.IllegalArgumentException: Bitmap not large enough to support new configuration
        at android.graphics.Bitmap.nativeReconfigure(Native Method)
        at android.graphics.Bitmap.reconfigure(Bitmap.java:267)
        at com.bumptech.glide.load.engine.bitmap_recycle.SizeConfigStrategy.get(SizeConfigStrategy.java:70)
        at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.getDirtyOrNull(LruBitmapPool.java:172)
        at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.get(LruBitmapPool.java:124)
        at com.bumptech.glide.load.resource.bitmap.TransformationUtils.centerCrop(TransformationUtils.java:140)
        at com.bumptech.glide.load.resource.bitmap.CenterCrop.transform(CenterCrop.java:22)
        at com.bumptech.glide.load.resource.bitmap.BitmapTransformation.transform(BitmapTransformation.java:97)
        at com.bumptech.glide.load.engine.DecodeJob.onResourceDecoded(DecodeJob.java:527)
        at com.bumptech.glide.load.engine.DecodeJob$DecodeCallback.onResourceDecoded(DecodeJob.java:590)
        at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:45)
        at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
        at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
        at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:497)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:469)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:455)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:407)
        at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:376)
        at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
        at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:74)
        at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:266)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
Here's the code used to load the image into each `ImageView` of my DuoAvatarLayout. This code is inside my adapter:
```kotlin
members.forEachIndexed { index, member ->
    val requestCreator = 
        GlideApp
            .with(context)
            .load(member.profile.pictureThumbUrl)
            .placeholder(R.drawable.rectangle_placeholder)

    when (index) {
        0 -> requestCreator.into(duoAvatarLeftImage)
        1 -> requestCreator.into(duoAvatarRightImage)
    }
}
```

Finally, here's the image it's supposed to load (1-jb.png)
![1-1ae317c33bd344440157e85303d49d82](https://user-images.githubusercontent.com/906656/35011734-38cbf010-fad5-11e7-8d38-9a99317c9c68.png)
Here's a row of my list with the DuoAvatarLayout. Sometimes, one of those images in the circle will not load and I will get the stacktrace.
![](https://dha4w82d62smt.cloudfront.net/items/410O140a3l3w0g003Z1s/%5B194cf79c38be9f03b81ca42929362ff6%5D_Image+2018-01-16+at+4.14.00+PM.png)

**Comment by sjudd** [comment]
Can you enable downsampler logging and copy/paste the output here?

```
adb shell setprop log.tag.Downsamapler VERBOSE
```

It will be quite verbose so you'll have to try to filter it down to your particular request.

**Comment by sjudd** [comment]
Also can you provide the device and version of Android you were able to reproduce on?

**Comment by sjudd** [comment]
For what it's worth I tried loading this image tonight on API 27 and API 25 with a variety of different sizes based on 25dp and 50dp and I'm not able to reproduce this or a case where Downsampler calculates an incorrect target size.

On API 27 this image is decoded into RGBA_F16 instead of ARGB_8888, but I'm not able to reproduce any issue related to that either. 

If I know exactly which device and version of Android you used, I won't need to guess about which version of Android and which sizes to test with.

**Comment by sjudd** [comment]
Ah I figured it out. It is indeed API 26+ only (let me know if you can reproduce it < 26). The issue is that the utility method for calculating Bitmap sizes has not been updated to handle RGBA_F16: https://github.com/bumptech/glide/blob/d45956144f72f080675c119a7d21dc1bf6057380/library/src/main/java/com/bumptech/glide/util/Util.java#L104

**Comment by Mathbl** [comment]
Hey! Sorry for the delay. I didn't have access to the codebase until now, so I wasn't able to give you the logs. 

Thanks for the amazing job. Can I provide you with additional information, or do you think you've pinpoint the issue?

**Comment by sjudd** [comment]
No worries I think this is sufficient. Do let me know if you've seen this on APIs < 26.
