### ISSUE TITLE
android 7.0 Raw中video获取不到缩略图 glide4.5.0

### ISSUE THREAD

**Issue by zhaojianmou** [bumptech/glide#2819]

**Comment by sjudd** [comment]
Hi @zhaojianmou,

It looks like you might not have included some important information when you filed this issue. To make sure we have all the information we need to help with your issue. Please take a look at the [Issue Template](https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md) and make sure you've filled out as many sections as possible.

In particular you **must** include:

* Glide Version
* Glide load line
* Issue details.

I'm marking this issue as requiring more information. Please understand that if you do not provide that information or update the issue within the next 7 days this issue will be automatically closed so that it doesn''t clutter the bug tracker.

Best regards,

~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by zhaojianmou** [comment]
Glide version 4.5.0

Device: Samsung Galaxy S7 edge
Android Version : 7.0

 protected void initView() {
        ButterKnife.bind(this);
       //  dunkirk720.mp4
       String path = ""android.resource://"+ getPackageName()+“/”+ R.raw.dunkirk720;
        if (!TextUtils.isEmpty(path)) {
            Glide.with(bgRl).load(Uri.parse(path)).into(videoIv);
        }
    }

Layout:

    <ImageView
                android:id="@+id/videoIv"
                android:layout_width="1000px"
                android:layout_height="600px"
                android:scaleType="centerCrop" />

    </ImageView>
Stack trace / LogCat:
No Logs. No bugs..

**Comment by sjudd** [comment]
Are you trying to load a thumbnail for a video? And not seeing a thumbnail? If so, there's a test for this here: https://github.com/bumptech/glide/blob/17e0943fdc9e24ce4f105df53e91c7cdea60edf6/instrumentation/src/androidTest/java/com/bumptech/glide/LoadVideoResourceTest.java#L30. Can you send a pull request with a failing test case that demonstrates the issue you're running into?

There's more details on writing test cases here: http://bumptech.github.io/glide/tut/failing-test-cases.html

**Comment by zhaojianmou** [comment]
android 5.0 have thumbnail
android 7.0 not have thumbnail

  class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{AssetInputStream->Object->Drawable}, LOCAL
      Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AssetInputStream->GifDrawable->Drawable}
      Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AssetInputStream->Bitmap->Drawable}
      Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AssetInputStream->BitmapDrawable->Drawable}
    Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, LOCAL
      Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
      Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
        Cause (1 of 1): class java.io.IOException: java.lang.IllegalArgumentException
    Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{HierarchicalUri->Object->Drawable}, LOCAL
      Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{HierarchicalUri->Drawable->Drawable}
        Cause (1 of 1): class java.lang.NullPointerException: Argument must not be null
      Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{HierarchicalUri->Bitmap->Drawable}
        Cause (1 of 1): class java.lang.NullPointerException: Argument must not be null
01-19 17:03:43.282 19450-19450/com.lazonlaser.solase I/Glide: Root cause (1 of 3)
  java.io.IOException: java.lang.IllegalArgumentException
      at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:138)
      at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:25)
      at com.bumptech.glide.load.resource.bitmap.BitmapDrawableDecoder.decode(BitmapDrawableDecoder.java:57)
      at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:68)
      at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:53)
      at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:44)
      at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
      at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
      at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:499)
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:471)
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:457)
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:411)
      at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:380)
      at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
      at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:51)
      at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:303)
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:419)
      at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:380)
      at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
      at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:51)
      at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:303)
      at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:273)
      at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
      at java.lang.Thread.run(Thread.java:762)
      at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:445)
   Caused by: java.lang.IllegalArgumentException
      at android.media.MediaMetadataRetriever.setDataSource(Native Method)
      at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:153)
      at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:128)
      at com.bumptech.glide.load.resource.bitmap.VideoBitmapDecoder.decode(VideoBitmapDecoder.java:25) 
      at com.bumptech.glide.load.resource.bitmap.BitmapDrawableDecoder.decode(BitmapDrawableDecoder.java:57) 
      at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:68) 
      at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:53) 
      at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:44) 
      at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56) 
      at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42) 
      at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:499) 
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:471) 
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:457) 
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:411) 
      at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:380) 
      at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111) 
      at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:51) 
      at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61) 
      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:303) 
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:419) 
      at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:380) 
      at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111) 
      at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:51) 
      at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61) 
      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:303) 
      at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:273) 
      at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234) 
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
      at java.lang.Thread.run(Thread.java:762) 
      at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:445) 
  java.lang.NullPointerException: Argument must not be null
      at com.bumptech.glide.util.Preconditions.checkNotNull(Preconditions.java:27)
      at com.bumptech.glide.util.Preconditions.checkNotNull(Preconditions.java:22)
      at com.bumptech.glide.load.resource.drawable.DrawableResource.<init>(DrawableResource.java:27)
      at com.bumptech.glide.load.resource.drawable.NonOwnedDrawableResource.<init>(NonOwnedDrawableResource.java:18)
      at com.bumptech.glide.load.resource.drawable.NonOwnedDrawableResource.newInstance(NonOwnedDrawableResource.java:14)
      at com.bumptech.glide.load.resource.drawable.ResourceDrawableDecoder.decode(ResourceDrawableDecoder.java:54)
      at com.bumptech.glide.load.resource.drawable.ResourceDrawableDecoder.decode(ResourceDrawableDecoder.java:24)
      at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:68)
      at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:53)
      at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:44)
      at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
      at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
      at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:499)
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:471)
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:457)
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:411)
      at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:380)
      at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
      at com.bumptech.glide.load.model.UnitModelLoader$UnitFetcher.loadData(UnitModelLoader.java:54)
      at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:303)
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:419)
      at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:380)
      at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
      at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:51)
      at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:303)
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:419)
      at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:380)
      at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
      at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:51)
      at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:303)
      at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:273)
      at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
      at java.lang.Thread.run(Thread.java:762)
      at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:445)
  java.lang.NullPointerException: Argument must not be null
      at com.bumptech.glide.util.Preconditions.checkNotNull(Preconditions.java:27)
      at com.bumptech.glide.util.Preconditions.checkNotNull(Preconditions.java:22)
      at com.bumptech.glide.load.resource.drawable.DrawableResource.<init>(DrawableResource.java:27)
      at com.bumptech.glide.load.resource.drawable.NonOwnedDrawableResource.<init>(NonOwnedDrawableResource.java:18)
      at com.bumptech.glide.load.resource.drawable.NonOwnedDrawableResource.newInstance(NonOwnedDrawableResource.java:14)
      at com.bumptech.glide.load.resource.drawable.ResourceDrawableDecoder.decode(ResourceDrawableDecoder.java:54)
      at com.bumptech.glide.load.resource.bitmap.ResourceBitmapDecoder.decode(ResourceBitmapDecoder.java:50)
      at com.bumptech.glide.load.resource.bitmap.ResourceBitmapDecoder.decode(ResourceBitmapDecoder.java:31)
      at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:68)
      at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:53)
      at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:44)
      at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
      at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
      at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:499)
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:471)
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:457)
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:411)
      at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:380)
      at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
      at com.bumptech.glide.load.model.UnitModelLoader$UnitFetcher.loadData(UnitModelLoader.java:54)
      at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:303)
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:419)
      at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:380)
      at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
      at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:51)
      at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:303)
      at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:419)
      at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:380)
      at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
      at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:51)
      at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:303)
      at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:273)
      at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
      at java.lang.Thread.run(Thread.java:762)
      at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:445)

**Comment by sjudd** [comment]
The NPE in ResourceDrawable decoder was fixed in Glide v4.5.0. What version of Glide are you using?

Otherwise the ``IllegalArgumentException`` implies that the framework was unable to decode the video in question. You can try passing the video to ``MediaMetadataRetriever`` outside of Glide. If it decodes a frame successfully, then it's most likely a framework issue.

Otherwise if you can attach a small video that reproduces the issue I can take a look.
