### ISSUE TITLE
at lz.terminal.UI.MainActivity$4.onLoadFailed(MainActivity.java:795)

### ISSUE THREAD

**Issue by liushengqiang** [bumptech/glide#2822]
```java
Glide.with(this).load(rtbNotice.getSourceUrl()).asBitmap().into(new SimpleTarget<Bitmap>() {
                @Override
                public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                    Drawable drawable = new BitmapDrawable(resource);
                    surface.setBackgroundDrawable(drawable);
                    ProgramApi.getInstance().saveRTBPlayLog(rtbNotice, 0, rtbNotice.getRtb_provider_id());
                    timeHandle.removeCallbacks(imgTiming);
                    timeHandle.postDelayed(imgTiming, rtbNotice.getSecond() * 1000);
                }

                @Override
                public void onLoadFailed(Exception e, Drawable errorDrawable) {
                    super.onLoadFailed(e, errorDrawable);
                    LogUtil.e(TAG, "简视图像加载失败:" + e.getMessage());
                    playComplete();
                }
            });
```

when loadFailed,  LogUtil.e(TAG, "简视图像加载失败:" + e.getMessage()); this have problem:

```
2018-01-16 07:08:15,719 - [ERROR::lz.terminal.log.LogUtil::lz.terminal.log.LogUtil] - 20180116_070815   lz.terminal.Application.LzApplication  捕捉到的崩溃信息java.lang.NullPointerException
	at lz.terminal.UI.MainActivity$4.onLoadFailed(MainActivity.java:795)
	at com.bumptech.glide.request.GenericRequest.setErrorPlaceholder(GenericRequest.java:404)
	at com.bumptech.glide.request.GenericRequest.onException(GenericRequest.java:548)
	at com.bumptech.glide.load.engine.EngineJob.handleExceptionOnMainThread(EngineJob.java:183)
	at com.bumptech.glide.load.engine.EngineJob.access$200(EngineJob.java:22)
	at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:204)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5041)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:816)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:582)
	at dalvik.system.NativeStart.main(Native Method)
  main
```

**Comment by sjudd** [comment]
Please fill out the [issue template][1] when filing new issues.

It looks like you're missing the exception cause which makes it difficult to comment. If you can reproduce on Glide v4 let me know.

[1]: https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md
