### ISSUE TITLE
ANR error with Glide

### ISSUE THREAD

**Issue by amankumarjain** [bumptech/glide#2825]
```
01-20 18:42:20.307 30104-30143/? E/AndroidRuntime: FATAL EXCEPTION: |ANR-WatchDog|
                                                   Process: in.codersbyte.namostu, PID: 30104
                                                   com.github.anrwatchdog.ANRError: Application Not Responding
                                                   Caused by: com.github.anrwatchdog.ANRError$$$_Thread: main (state = RUNNABLE)
                                                       at android.view.ThreadedRenderer.nPauseSurface(Native Method)
                                                       at android.view.ThreadedRenderer.pauseSurface(ThreadedRenderer.java:486)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1781)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1288)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6359)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:685)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
                                                       at android.os.Handler.handleCallback(Handler.java:754)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:163)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6237)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                    Caused by: com.github.anrwatchdog.ANRError$$$_Thread: FileObserver (state = RUNNABLE)
                                                       at android.os.FileObserver$ObserverThread.observe(Native Method)
                                                       at android.os.FileObserver$ObserverThread.run(FileObserver.java:85)
                                                    Caused by: com.github.anrwatchdog.ANRError$$$_Thread: FinalizerDaemon (state = WAITING)
                                                       at java.lang.Object.wait(Native Method)
                                                       at java.lang.Object.wait(Object.java:407)
                                                       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
                                                       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
                                                       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:204)
                                                       at java.lang.Thread.run(Thread.java:760)
                                                    Caused by: com.github.anrwatchdog.ANRError$$$_Thread: FinalizerWatchdogDaemon (state = WAITING)
                                                       at java.lang.Object.wait(Native Method)
                                                       at java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded(Daemons.java:269)
                                                       at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:249)
                                                       at java.lang.Thread.run(Thread.java:760) 
                                                    Caused by: com.github.anrwatchdog.ANRError$$$_Thread: HeapTaskDaemon (state = BLOCKED)
                                                       at dalvik.system.VMRuntime.runHeapTasks(Native Method)
                                                       at java.lang.Daemons$HeapTaskDaemon.run(Daemons.java:433)
                                                       at java.lang.Thread.run(Thread.java:760) 
                                                    Caused by: com.github.anrwatchdog.ANRError$$$_Thread: ReferenceQueueDaemon (state = WAITING)
                                                       at java.lang.Object.wait(Native Method)
                                                       at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:150)
                                                       at java.lang.Thread.run(Thread.java:760) 
                                                    Caused by: com.github.anrwatchdog.ANRError$$$_Thread: fifo-pool-thread-0 (state = WAITING)
                                                       at java.lang.Object.wait(Native Method)
                                                       at java.lang.Thread.parkFor$(Thread.java:2160)
                                                       at sun.misc.Unsafe.park(Unsafe.java:325)
                                                       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:161)
                                                       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035)
                                                       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:519)
                                                       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                       at java.lang.Thread.run(Thread.java:760)
                                                       at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
                                                    Caused by: com.github.anrwatchdog.ANRError$$$_Thread: |ANR-WatchDog| (state = RUNNABLE)
                                                       at dalvik.system.VMStack.getThreadStackTrace(Native Method)
                                                       at java.lang.Thread.getStackTrace(Thread.java:1565)
                                                       at java.lang.Thread.getAllStackTraces(Thread.java:1615)
                                                       at com.github.anrwatchdog.ANRError.New(ANRError.java:72)
                                                       at com.github.anrwatchdog.ANRWatchDog.run(ANRWatchDog.java:209)
```

please help me why this anr exception occur as it is very hard to debug anr exception but using anr-watchdog i am able to find out which library is causing this and it turns out glide is responsible for this, so i have posted this error over here, please help me how to solve this.

**Comment by sjudd** [comment]
That stack trace looks incoherent. The Glide thread pool in this trace is doing nothing and WAI. The rest of the trace makes me suspect the tool you're using isn't working.

**Comment by amankumarjain** [comment]
I am using ANR-WatchDog to trace anr exception: https://github.com/SalomonBrys/ANR-WatchDog.
uing anr/traces.txt i was not able to find out which part of code is reponsible for anr, but this library throw an exception every time anr occur. I have posted the same exception which i get. if this exception is incoherent, please let me know how to debug that anr exception in a best way to analyse the root cause

**Comment by sjudd** [comment]
I'm not familiar with that library and can't help you debug it. However, it looks like it's just printing out all pending threads in your application whenever the ANR occurs, one of which is Glide's thread pool. That doesn't seem to mean that Glide's thread pool is in any way involved in the ANR.

I'd suggest you contact the author of that library for help understanding what it prints out and why.
