### ISSUE TITLE
Gldie 4.5.0 cann't load image with repeated setting "format(DecodeFormat.PREFER_ARGB_8888)" in Android 8.0.0

### ISSUE THREAD

**Issue by nuli1228588792** [bumptech/glide#2836]
**Glide Version**: 4.5.0

**Integration libraries**: okhttp3:okhttp:3.8.1

**Device/Android Version**:  MHA-AL00 8.0.0.340(C00)

**Issue details / Repro steps / Use case background**: 
in my application , my  SdkVersion Config is like that:    
    compileSdkVersion 27
    buildToolsVersion "27.0.3" 
    minSdkVersion 17
    targetSdkVersion 25
I use AppGlideModule to initialize Glide , my AppGlideModule  is :

```
   @GlideModule
   public class MyGlideMoudle extends AppGlideModule {
	public static final String GLIDE_CARCH_DIR = "glide_image_catch";
	public static final int GLIDE_CATCH_SIZE = 150 * 1024 * 1024;
	@Override
	public void applyOptions(Context context, GlideBuilder builder) {
		ViewTarget.setTagId(R.id.glide_tag_id);
		builder.setDefaultRequestOptions(new                                    RequestOptions().format(DecodeFormat.PREFER_ARGB_8888));
		builder.setDiskCache(new InternalCacheDiskCacheFactory(MyApp.context,
				GLIDE_CARCH_DIR,GLIDE_CATCH_SIZE));
	}
    }
```
then I load image with glide  in Activity :
```
RequestOptions options=new RequestOptions()
				.skipMemoryCache(true)
				.diskCacheStrategy(DiskCacheStrategy.RESOURCE)
				.dontAnimate().placeholder(R.mipmap.picture_loading_failed)
				.error(R.mipmap.picture_loading_failed)
				.encodeFormat(Bitmap.CompressFormat.JPEG)
				.format(DecodeFormat.PREFER_ARGB_8888)
				.encodeQuality(100)
				.transform(new ScaleTransformation(ImageActivity.this));
private void displayImages(){
		for (int i = 0; i < imagesUrl.size(); i++) {
			String url = imagesUrl.get(i);
			final FrameLayout frameLayout=new FrameLayout(this);
			LinearLayout.LayoutParams params=new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,
					LinearLayout.LayoutParams.WRAP_CONTENT);
			frameLayout.setLayoutParams(params);

			final ImageView imageView = new ImageView(this);
			FrameLayout.LayoutParams params2 = new FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT,
					FrameLayout.LayoutParams.WRAP_CONTENT);
			params2.gravity=Gravity.CENTER_HORIZONTAL;
			imageView.setLayoutParams(params2);
			imageView.setVisibility(View.VISIBLE);
			frameLayout.addView(imageView);
			Glide.with(ImageActivity.this).load(url).apply(options).into(imageView);
			llImageContainer.addView(frameLayout);
		}
	}
```
First time my device show images which load with glide , and when I click the refresh button , my ImageView container remove all views, then I call method of  "displayImages()", my device cann't show any image, the images reload by glide is blank . I just called the method of "format(DecodeFormat.PREFER_ARGB_8888)" twice, It doesn't works on Android 8.0.0 . I try some devices 
less than 8.0 , it works well ,why?

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```
my ImageView is not generated by xml, I add ImageViews in java code dynamically, its parent view is linearlayout.

**Stack trace / LogCat**:
```
java.lang.IllegalStateException: Software rendering doesn't support hardware bitmaps
   at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:532)
   at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:62)
   at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:120)
   at android.graphics.Canvas.drawBitmap(Canvas.java:1434)
   at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:530)
   at android.widget.ImageView.onDraw(ImageView.java:1428)
   at android.view.View.draw(View.java:19314)
   at android.view.View.draw(View.java:19184)
   at android.view.ViewGroup.drawChild(ViewGroup.java:4263)
   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4046)
   at android.view.View.draw(View.java:19182)
   at android.view.ViewGroup.drawChild(ViewGroup.java:4263)
   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4046)
   at android.view.View.draw(View.java:19182)
   at android.view.ViewGroup.drawChild(ViewGroup.java:4263)
   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4046)
   at android.view.View.draw(View.java:19317)
   at android.widget.ScrollView.draw(ScrollView.java:1777)
   at android.view.View.draw(View.java:19184)
   at android.view.ViewGroup.drawChild(ViewGroup.java:4263)
   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4046)
   at android.view.View.draw(View.java:19182)
   at android.view.ViewGroup.drawChild(ViewGroup.java:4263)
   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4046)
   at android.view.View.draw(View.java:19182)
   at android.view.ViewGroup.drawChild(ViewGroup.java:4263)
   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4046)
   at android.view.View.draw(View.java:19182)
   at android.view.ViewGroup.drawChild(ViewGroup.java:4263)
   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4046)
   at android.view.View.draw(View.java:19182)
   at android.view.ViewGroup.drawChild(ViewGroup.java:4263)
   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4046)
   at android.view.View.draw(View.java:19182)
   at android.view.ViewGroup.drawChild(ViewGroup.java:4263)
   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4046)
   at android.view.View.draw(View.java:19317)
   at com.android.internal.policy.DecorView.draw(DecorView.java:912)
   at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:3335)
   at android.view.ViewRootImpl.draw(ViewRootImpl.java:3207)
   at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2978)
   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2507)
   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1511)
   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7198)
   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
   at android.view.Choreographer.doCallbacks(Choreographer.java:790)
   at android.view.Choreographer.doFrame(Choreographer.java:721)
   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
   at android.os.Handler.handleCallback(Handler.java:808)
   at android.os.Handler.dispatchMessage(Handler.java:101)
   at android.os.Looper.loop(Looper.java:166)
   at android.app.ActivityThread.main(ActivityThread.java:7406)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)
E/BitmapDrawable: Canvas: trying to use a recycled bitmap
```

**Comment by sjudd** [comment]
Using ``PREFER_ARGB_8888`` allows Glide to load hardware Bitmaps. You're apparently trying to draw the hardware Bitmap in a view using software rendering.

You can disallow hardware Bitmaps with [``disallowHardwareConfig()``][1]. 

If you can reproduce this in a sample app I'm curious to see why the View is rendering in software mode, I haven't seen that before.

[1]: http://bumptech.github.io/glide/javadocs/450/com/bumptech/glide/request/RequestOptions.html#disallowHardwareConfig--

**Comment by nuli1228588792** [comment]
@sjudd Thank you very much , I use "DecodeFormat.DEFAULT" instead of PREFER_ARGB_8888 , then run my Android 8.0 device , it works well .

**Comment by sjudd** [comment]
Great thanks for the follow up.
