### ISSUE TITLE
Socket timeout exception ！

### ISSUE THREAD

**Issue by fg2q1q3q** [bumptech/glide#2842]
Hello, my URL can be opened in the browser, but when the use of glide 4.0 will be wrong, the following is the wrong information, is there any advice?
URL：http://211.138.31.210:8088/maip/action/anonymous/fileAuthentication/authenticate?url=o%2FZYJLta0kTG9MHqhP%2BvAxDg3rAHIURVmDCMhuXyjC5As5RBN9LyJHfoOjLvUGWK9q2jUdAoRAQ6%0AlSonegCDRIJaM9JfwwSBWRxYNCs4KmBuwdOBKPQIay4%2BuBOY7QGCil6ZXEvOsRImXdpiTA%2BWHnfJ%0AdYuMD%2BopuDuoNjf3vkSsyfj5cxOtmkuv9Ft29aw49MKqfz9Q7IcTNJnIuXF4HOcGLRiYcxlF%0A&token=ZdQ7%2Fdvf7nC1vdsB9DmZg4BnS5uzbJgv3D4QJtXdlmOUm8%2FQOgem39KjzMg31Xu8otNPTcMH37AkjUt%2BDWQf8VWxQckArfAkucFxjAIJt1SLmDTvYl4M0D1BgCdN7%2BpE%2FCx2FK5ry4yie2FBhSIZxkT7dHnR4zN7DR%2F7TsNaWrw%3D

`
Load failed for http://211.138.31.210:8088/maip/action/anonymous/fileAuthentication/authenticate?url=o%2FZYJLta0kTG9MHqhP%2BvAxDg3rAHIURVmDCMhuXyjC5As5RBN9LyJHfoOjLvUGWK9q2jUdAoRAQ6%0AlSonegCDRIJaM9JfwwSBWRxYNCs4KmBuwdOBKPQIay4%2BuBOY7QGCil6ZXEvOsRImXdpiTA%2BWHnfJ%0AdYuMD%2BopuDuoNjf3vkSsyfj5cxOtmkuv9Ft29aw49MKqfz9Q7IcTNJnIuXF4HOcGLRiYcxlF%0A&token=ZdQ7%2Fdvf7nC1vdsB9DmZg4BnS5uzbJgv3D4QJtXdlmOUm8%2FQOgem39KjzMg31Xu8otNPTcMH37AkjUt%2BDWQf8VWxQckArfAkucFxjAIJt1SLmDTvYl4M0D1BgCdN7%2BpE%2FCx2FK5ry4yie2FBhSIZxkT7dHnR4zN7DR%2F7TsNaWrw%3D with size [1440x2280]
class com.bumptech.glide.load.engine.GlideException: Failed to load resource
  Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
      Cause (1 of 1): class java.net.SocketTimeoutException: 
class com.bumptech.glide.load.engine.GlideException: Failed to load resource
Root cause (1 of 1)
java.net.SocketTimeoutException
    at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
    at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
    at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
    at com.android.okhttp.okio.Okio$2.read(Okio.java:135)
    at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
    at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
    at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
    at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
    at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
    at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
    at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:905)
    at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:789)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501)
    at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:105)
    at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:114)
    at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:53)
    at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:95)
    at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:144)
    at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:138)
    at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:59)
    at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:95)
    at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
    at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:282)
    at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:249)
    at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:222)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
    at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)`

**Comment by sjudd** [comment]
Root cause (1 of 1) java.net.SocketTimeoutException 

Your connection timed out, you can set timeouts with [``.timeout()``][1] on ``RequestOptions``.

[1]: http://bumptech.github.io/glide/javadocs/450/com/bumptech/glide/request/RequestOptions.html#timeout-int-

**Comment by fg2q1q3q** [comment]
thanks but I used glide 4.0.0，it's no timeout() on RequestOptions;
