### ISSUE TITLE
Loading Gif Image from drawable folder. IllegalArgumentException: You must call this method on the main thread

### ISSUE THREAD

**Issue by pradeepsagayam** [bumptech/glide#2846]
![fabric_crash_log](https://user-images.githubusercontent.com/5426616/35509764-7f33da40-051b-11e8-8fae-fb885b6a79df.png)
**Glide Version:**
 compile 'com.github.bumptech.glide:glide:4.5.0'

**Device/Android Version:** 4.4 or higher

**Issue details / Repro steps / Use case background:**

I want to display loader.gif file from drawable folder. Code is called inside Activity.
Please find the code snippet below.
           **runOnUiThread(new Runnable() {
                  @Override
                   public void run() {
                         DrawableImageViewTarget imageViewTarget = new 
                            DrawableImageViewTarget(imageView);
                          Glide.with(CommonActivity.this).load(R.drawable.gif_file).
                          into(imageViewTarget);
                 }
             });**
In few devices like **Redmi and OPPO,** I am facing the below  issue.

java.lang.IllegalArgumentException: **You must call this method on the main thread**
       at com.bumptech.glide.util.Util.assertMainThread(SourceFile:139)
       at com.bumptech.glide.RequestBuilder.into(SourceFile:590)
       at com.bumptech.glide.RequestBuilder.into(SourceFile:583)
       at com.bumptech.glide.RequestBuilder.into(SourceFile:576)
       at com.bumptech.glide.load.resource.gif.GifFrameLoader.loadNextFrame(SourceFile:226)
       at com.bumptech.glide.load.resource.gif.GifFrameLoader.onFrameReady(SourceFile:284)
       at com.bumptech.glide.load.resource.gif.GifFrameLoader.loadNextFrame(SourceFile:215)
       at com.bumptech.glide.load.resource.gif.GifFrameLoader.start(SourceFile:171)
       at com.bumptech.glide.load.resource.gif.GifFrameLoader.subscribe(SourceFile:120)
       at com.bumptech.glide.load.resource.gif.GifDrawable.startRunning(SourceFile:235)
       at com.bumptech.glide.load.resource.gif.GifDrawable.setVisible(SourceFile:254)
       at android.widget.ImageView.onVisibilityAggregated(ImageView.java:1525)
       at android.view.View.dispatchAttachedToWindow(View.java:15584)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1656)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1372)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6782)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:933)
       at android.view.Choreographer.doCallbacks(Choreographer.java:742)
       at android.view.Choreographer.doFrame(Choreographer.java:674)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:919)
       at android.os.Handler.handleCallback(Handler.java:761)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:156)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by sjudd** [comment]
Please attach a failing test case or a sample app in which you can reproduce this.

This will only happen if the looper being used here is not the main thread looper, which seems unlikely.
