### ISSUE TITLE
SingleRequest NullPointerException java.lang.Object.getClass()

### ISSUE THREAD

**Issue by OsBelief** [bumptech/glide#2859]
I have a problem.

Glide Version: 4.3.1
Android Version:5.1.1
Device:SM_J200H

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at android.util.Log.getStackTraceString(Log.java:340)
	at android.util.Log.w(Log.java:192)
	at com.bumptech.glide.request.SingleRequest.onLoadFailed(SourceFile:581)
	at com.bumptech.glide.request.SingleRequest.onLoadFailed(SourceFile:574)
	at com.bumptech.glide.load.engine.EngineJob.handleExceptionOnMainThread(SourceFile:282)
	at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(SourceFile:314)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5667)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:969)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)

I think it is GlideException.appendExceptionMessage() cause this problem:
private static void appendExceptionMessage(Throwable t, Appendable appendable) {
    try {
      appendable.append(t.getClass().toString()).append(": ").append(t.getMessage()).append('\n');
    } catch (IOException e1) {
      throw new RuntimeException(t);
    }
  }

**Comment by sjudd** [comment]
Let me know if you're able to reproduce this on 4.5.0 or higher.

**Comment by OsBelief** [comment]
@sjudd ，This error is counted by the official version of our application. We didn't find this problem in the test version. Now we have upgraded Glide to 4.5.0. Has this problem been solved?

**Comment by JerryDu0306** [comment]
I still have this problem in my app.  glide version is 4.5.0. can you confirm this problem resolved?
