### ISSUE TITLE
Glide 4.6.1: 3 kind of crashes with Android 4.4

### ISSUE THREAD

**Issue by camino2007** [bumptech/glide#2878]
**Glide Version**: 4.6.1

**Integration libraries**: okhttp: 3.9.0

**Device/Android Version**: Samsung GT-I9195l/4.4.4

**Issue details / Repro steps / Use case background**: Scroll up and down in a list with customized images

In a fragment we have a list with items, where each item has a BaseImageView. There we start to load images via our GlideUtils

**BaseImageView**:
```java
@BindingMethods({@BindingMethod(type = BaseImageView.class, attribute = "imageInfos", method = "setImageInfos")})
public class BaseImageView extends InjectedBindableView<ViewBaseImageViewBinding> {

    @Inject
    protected GlideUtils glideUtils;

    private BaseImageViewModel viewModel;
    private ImageType imageType;
    private ProfileImageSize profileImageSize;
    private boolean handleSpicy;

   //constructors

    @Override
    protected void loadAttributes(final Context context, final AttributeSet attrs, final int defStyleAttr) {
      //get attributes
    }

    @Override
    public void initBinding(final ViewBaseImageViewBinding binding) {
        viewModel = new BaseImageViewModel();
        viewModel.tooSpicyIcon.set(imageType.getTooSpicyIcon());
        viewModel.tooSpicyText.set(getResources().getString(imageType.getTooSpicyText()));
        binding.setViewModel(viewModel);
        binding.setHandlers(new Handlers());
    }

    public void setImageInfos(final ImageInfos imageInfos) {
        if (imageInfos == null || ImageInfos.Tools.areImageInfosEqual(imageInfos, viewModel.imageInfos.get())) {
            return;
        }

        this.viewModel.imageInfos.set(imageInfos);
        loadImage();
    }

    private void loadImage() {
        if (viewModel == null) {
            return;
        }
        final ImageView imageView = getBinding().imageView;
        if (imageView == null) {
            return;
        }
        final ImageInfos imageInfos = viewModel.imageInfos.get();
        if (imageInfos.isLocalImage() || TextUtils.isEmpty(imageInfos.getImageUrl())) {
            loadLocalImage(imageView, imageInfos);
        } else {
            loadRemoteImage(imageView, imageInfos);
        }
    }

    private void loadLocalImage(final ImageView imageView, final ImageInfos imageInfos) {
        //placeHolderId is used here as an imageId
        int imageId = imageInfos.getPlaceholderImageId(profileImageSize);
        if (imageId == 0) {
            imageId = imageInfos.getImageId();
        }
        if (imageId == 0) {
            imageId = GlideUtils.DEFAULT_PLACEHOLDER_IMAGE;
        }
        glideUtils.with(this).showLocalImage(imageView, imageType, imageId);
        viewModel.imageState.set(ImageState.LOADED);
    }

    private void loadRemoteImage(final ImageView imageView, final ImageInfos imageInfos) {
        final int placeHolderId = imageInfos.getPlaceholderImageId(profileImageSize);
        viewModel.imageState.set(ImageState.LOADING);
        final JoyceGlideRequestListener glideRequestListener = new JoyceGlideRequestListener();
        glideRequestListener.setValues(viewModel, imageType, imageInfos);
        glideUtils.with(this).showImage(imageView, imageType, placeHolderId, imageInfos, glideRequestListener);
    }

    private static class JoyceGlideRequestListener implements RequestListener<Bitmap> {

        private BaseImageViewModel viewModel;
        private ImageType imageType;
        private ImageInfos imageInfos;

        void setValues(final BaseImageViewModel viewModel, final ImageType imageType, final ImageInfos imageInfos) {
            this.viewModel = viewModel;
            this.imageType = imageType;
            this.imageInfos = imageInfos;
        }

        @Override
        public boolean onLoadFailed(@Nullable final GlideException e, final Object o, final Target<Bitmap> target, final boolean isFirstResource) {
            viewModel.imageState.set(ImageState.ERROR);
            return false;
        }

        @Override
        public boolean onResourceReady(final Bitmap bitmap, final Object o, final Target<Bitmap> target, final DataSource dataSource, final boolean b) {
            viewModel.imageState.set(ImageState.LOADED);
            viewModel.onShowTooSpicy.set(imageType.canShowTooSpicy() && imageInfos.isBlurred());
            return false;
        }
    }

    public class Handlers {
        public void retry(final View view) {
            loadImage();
        }

        public void onShowTooSpicy(final View view) {
            if (handleSpicy) {
                //not important
            }
        }
    }
}

```

**Glide Loading Line in GlideUtils**:
Is called from the BaseImageView class above. If you need the code of the two Transformations, please let me know. There is only one instance of them. No where is called ```Bitmap.recycle();```

```java
 public void showImage(final ImageView imageView,
                              final ImageType imageType,
                              @DrawableRes final int placeHolderId,
                              final ImageInfos imageInfos,
                              @Nullable final RequestListener<Bitmap> listener) {
            if (imageView == null) {
                LOG.warn("The ImageView is not set. Take sure that the caller passes all arguments.");
                return;
            }

            final String imageUrl = imageInfos.getImageUrl();
            final boolean isBlurred = imageInfos.isBlurred();
            RequestOptions options = new RequestOptions().diskCacheStrategy(DiskCacheStrategy.RESOURCE).placeholder(placeHolderId);
            if (isBlurred) {
                options = options.transforms(imageScaleTransformation, blurTransformation);
            } else {
                options = options.transform(imageScaleTransformation);
            }

            requestManager.asBitmap()
                          .load(imageUrl)
                          .apply(options)
                          .listener(new GlideLoggingListener<>(listener))
                          .into(new BaseImageViewTarget(imageView, imageType));
        }
```

**GlideModule**:
```java
@GlideModule
public class CustomGlideModule extends AppGlideModule {

    @Inject
    protected OkHttpClient okHttpClient;

    public CustomGlideModule () {
        OurApplication.getDependencyComponent().inject(this);
    }

    @Override
    public boolean isManifestParsingEnabled() {
        return false;
    }

    @Override
    public void applyOptions(final Context context, final GlideBuilder builder) {
        builder.setDefaultRequestOptions(new RequestOptions().format(DecodeFormat.PREFER_RGB_565));
    }

    @Override
    public void registerComponents(@NonNull final Context context, @NonNull final Glide glide, @NonNull final Registry registry) {
        registry.append(GlideUrl.class, InputStream.class, new OkHttpUrlLoader.Factory(okHttpClient));
    }

}
```

And we have a Custom TargetView:

**BaseImageViewTarget extends BitmapImageViewTarget**:
```java
public class BaseImageViewTarget extends BitmapImageViewTarget {

    private float cornerRadius = -1f;
    private float borderSize = -1f;
    @ColorInt
    private int borderColor = -1;
    private boolean hasBorder = false;
    private boolean hasRoundedCorners = false;
    private boolean isCircular;

    public BaseImageViewTarget(@NonNull final ImageView view, @NonNull final ImageType imageType) {
        super(view);

        final Context context = view.getContext();
        final Resources resources = context.getResources();

        isCircular = imageType.isCircular();

        final int cornerRadiusRes = imageType.getCornerRadius();
        if (cornerRadiusRes > 0) {
            this.cornerRadius = resources.getDimensionPixelSize(cornerRadiusRes);
        }

        final int borderSizeRes = imageType.getBorderSize();
        if (borderSizeRes > 0) {
            this.borderSize = resources.getDimensionPixelSize(borderSizeRes);
        }

        final int borderColorRes = imageType.getBorderColor();
        if (borderColorRes > 0) {
            this.borderColor = ContextCompat.getColor(context, borderColorRes);
        }

        hasBorder = borderSize > 0f;
        hasRoundedCorners = cornerRadius > 0f;
    }

   @Override
    public void onResourceReady(@NonNull final Bitmap resource, @Nullable final Transition<? super Bitmap> transition) {
        final Context context = getView().getContext();
        final Resources resources = context.getResources();
        final LayerDrawable ld = createImageDrawable(resources, resource);
        getView().setImageDrawable(ld);
    }

    @Nullable
    public LayerDrawable createImageDrawable(@NonNull final Resources resources, @Nullable final Bitmap bitmap) {
        if (bitmap != null) {
            final RoundedBitmapDrawable roundedBitmapDrawable = RoundedBitmapDrawableFactory.create(resources, bitmap);

            if (isCircular) {
                roundedBitmapDrawable.setCircular(true);
            } else if (hasRoundedCorners) {
                roundedBitmapDrawable.setCornerRadius(cornerRadius);
            }

            final int density = calculateDensity(resources, bitmap);
            if (density > 0) {
                roundedBitmapDrawable.setTargetDensity(density);
            }

            RoundedBorderDrawable roundedBorderDrawable = null;
            if (hasBorder) {
                final float borderCornerRadius = isCircular ? Integer.MAX_VALUE : this.cornerRadius;
                roundedBorderDrawable = new RoundedBorderDrawable(borderColor, borderCornerRadius, borderSize);
            }
            LayerDrawable layerDrawable;
            if (roundedBorderDrawable != null) {
                layerDrawable = new LayerDrawable(new Drawable[]{roundedBitmapDrawable, roundedBorderDrawable});
            } else {
                layerDrawable = new LayerDrawable(new Drawable[]{roundedBitmapDrawable});
            }
            return layerDrawable;
        }
        return null;
    }

    /**
     * Calculates the density to apply to the {@link RoundedBitmapDrawable}. This is done by using the width and height of the ImageView and calculating the
     * scale factor for the given bitmap so it correctly fits into the ImageView.
     * <p>
     * Using this approach the drawable will be rendered in its correct size including the correct border size and corner radius.
     *
     * @return the new density or -1 if the density should not be changed.
     */
    private int calculateDensity(@NonNull final Resources resources, @Nullable final Bitmap bitmap) {
        final ImageView imageView = getView();

        final int viewWidth = imageView.getWidth() > 0 ? imageView.getWidth() : imageView.getMeasuredWidth();
        final int viewHeight = imageView.getHeight() > 0 ? imageView.getHeight() : imageView.getMeasuredHeight();

        if (bitmap != null) {
            final int bitmapWidth = bitmap.getWidth();
            final int bitmapHeight = bitmap.getHeight();
            if (viewWidth <= 0 || viewHeight <= 0 || viewWidth == bitmapWidth || viewHeight == bitmapHeight) {
                // view is not layed out so we cannot set the drawable size correctly
                return -1;
            }
            final float scaleX = (float) viewWidth / (float) bitmapWidth;
            return (int) (scaleX * resources.getDisplayMetrics().densityDpi);
        }
        return -1;
    }
}
```

**Layout XML**: BaseImageView.java which has the following layout:

```xml
<layout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto">

    <data>

        <import type="aa.bbb.ccc.ui.base.view.image.ImageState"/>

        <variable
                name="viewModel"
                type="aa.bbb.ccc.base.view.image.BaseImageViewModel"/>

        <variable
                name="handlers"
                type="aa.bbb.ccc.ui.base.view.image.BaseImageView.Handlers"/>

    </data>

    <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

        <ImageView
                android:id="@+id/imageView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:visibleOrNot="@{viewModel.imageState == ImageState.LOADED}"/>

        <ImageView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                android:src="@drawable/ic_select_image"
                app:visibleOrNot="@{viewModel.imageState == ImageState.LOADING}"/>

        <ProgressBar
                android:id="@+id/progressBar"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                app:visibleOrNot="@{viewModel.imageState == ImageState.LOADING}"/>

        <LinearLayout
                android:id="@+id/spicyLayout"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:orientation="vertical"
                android:gravity="center"
                android:onClick="@{handlers.onShowTooSpicy}"
                app:visibleOrNot="@{viewModel.onShowTooSpicy}">

            <ImageView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:scaleType="centerInside"
                    android:src="@{viewModel.tooSpicyIcon}"/>

            <aa.bbb.ccc.ui.base.font.CustomFontTextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="@dimen/space_one_unit"
                    android:textAppearance="@style/TextAppearance.AppCompat.Body2.Bold.WarmGrey"
                    android:text="@{viewModel.tooSpicyText}"
                    app:visibleOrGone="@{viewModel.showTooSpicyText}"/>

        </LinearLayout>

        <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:paddingLeft="@dimen/space_one_unit"
                android:paddingRight="@dimen/space_one_unit"
                android:paddingTop="@dimen/space_one_unit"
                android:paddingBottom="@dimen/space_one_unit"
                android:orientation="vertical"
                android:gravity="center"
                app:visibleOrNot="@{viewModel.imageState == ImageState.ERROR &amp;&amp; viewModel.canShowRetryView}"
                android:onClick="@{handlers.retry}">

            <aa.bbb.ccc.ui.base.font.CustomFontTextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:textAppearance="@style/TextAppearance.AppCompat.Body1.WarmGrey"
                    android:gravity="center_horizontal"
                    android:text="@string/retry_image_view_error"/>

            <aa.bbb.ccc.ui.base.font.CustomFontTextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    style="@style/ButtonStyle.Red.Compact"
                    android:layout_marginTop="@dimen/space_one_unit"
                    android:layout_gravity="center"
                    android:text="@string/retry_image_view_retry"/>

        </LinearLayout>

    </FrameLayout>

</layout>
```

Well, it's strange. When I scroll up and down on a Samsung S4 I get 3 different kind of crashes. I'm not sure if it's smart to put all of them in one issue but for me it's always the same use case with 3 different kind of crashes. It seems to me randomly when one of the three happens. I cannot reproduce one of them in a certain way. 

**Stack trace / LogCat - IllegalStateException: Cannot acquire a recycled resource**:
```ruby
  java.lang.IllegalStateException: Cannot acquire a recycled resource
                                                                        at com.bumptech.glide.load.engine.EngineResource.acquire(EngineResource.java:88)
                                                                        at com.bumptech.glide.load.engine.Engine.loadFromActiveResources(Engine.java:249)
                                                                        at com.bumptech.glide.load.engine.Engine.load(Engine.java:173)
                                                                        at com.bumptech.glide.request.SingleRequest.onSizeReady(SingleRequest.java:451)
                                                                        at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.getSize(ViewTarget.java:383)
                                                                        at com.bumptech.glide.request.target.ViewTarget.getSize(ViewTarget.java:215)
                                                                        at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:264)
                                                                        at com.bumptech.glide.manager.RequestTracker.runRequest(RequestTracker.java:42)
                                                                        at com.bumptech.glide.RequestManager.track(RequestManager.java:634)
                                                                        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:618)
                                                                        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:583)
                                                                        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:576)
```

**Stack trace / LogCat - IllegalStateException: Cannot recycle a resource while it is still acquired**:
```ruby
java.lang.IllegalStateException: Cannot recycle a resource while it is still acquired
                                                                        at com.bumptech.glide.load.engine.EngineResource.recycle(EngineResource.java:66)
                                                                        at com.bumptech.glide.load.engine.ResourceRecycler.recycle(ResourceRecycler.java:28)
                                                                        at com.bumptech.glide.load.engine.Engine.onResourceRemoved(Engine.java:318)
                                                                        at com.bumptech.glide.load.engine.cache.LruResourceCache.onItemEvicted(LruResourceCache.java:33)
                                                                        at com.bumptech.glide.load.engine.cache.LruResourceCache.onItemEvicted(LruResourceCache.java:13)
                                                                        at com.bumptech.glide.util.LruCache.trimToSize(LruCache.java:183)
                                                                        at com.bumptech.glide.util.LruCache.evict(LruCache.java:188)
                                                                        at com.bumptech.glide.util.LruCache.put(LruCache.java:141)
                                                                        at com.bumptech.glide.load.engine.cache.LruResourceCache.put(LruResourceCache.java:13)
                                                                        at com.bumptech.glide.load.engine.Engine.onResourceReleased(Engine.java:326)
                                                                        at com.bumptech.glide.load.engine.EngineResource.release(EngineResource.java:112)
                                                                        at com.bumptech.glide.load.engine.Engine.release(Engine.java:286)
                                                                        at com.bumptech.glide.request.SingleRequest.releaseResource(SingleRequest.java:345)
                                                                        at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:324)
                                                                        at com.bumptech.glide.manager.RequestTracker.clearRemoveAndMaybeRecycle(RequestTracker.java:73)
                                                                        at com.bumptech.glide.manager.RequestTracker.clearRemoveAndRecycle(RequestTracker.java:60)
                                                                        at com.bumptech.glide.RequestManager.untrack(RequestManager.java:623)
                                                                        at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:591)
                                                                        at com.bumptech.glide.RequestManager.clear(RequestManager.java:579)
                                                                        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:616)
                                                                        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:583)
                                                                        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:576)
```

**Stack trace / LogCat - java.lang.NullPointerException:**:
```ruby
  java.lang.NullPointerException
                                                                        at com.bumptech.glide.load.engine.LockedResource.getSize(LockedResource.java:80)
                                                                        at com.bumptech.glide.load.engine.EngineResource.getSize(EngineResource.java:60)
                                                                        at com.bumptech.glide.load.engine.cache.LruResourceCache.getSize(LruResourceCache.java:42)
                                                                        at com.bumptech.glide.load.engine.cache.LruResourceCache.getSize(LruResourceCache.java:13)
                                                                        at com.bumptech.glide.util.LruCache.trimToSize(LruCache.java:180)
                                                                        at com.bumptech.glide.util.LruCache.evict(LruCache.java:188)
                                                                        at com.bumptech.glide.util.LruCache.put(LruCache.java:141)
                                                                        at com.bumptech.glide.load.engine.cache.LruResourceCache.put(LruResourceCache.java:13)
                                                                        at com.bumptech.glide.load.engine.Engine.onResourceReleased(Engine.java:326)
                                                                        at com.bumptech.glide.load.engine.EngineResource.release(EngineResource.java:112)
                                                                        at com.bumptech.glide.load.engine.Engine.release(Engine.java:286)
                                                                        at com.bumptech.glide.request.SingleRequest.releaseResource(SingleRequest.java:345)
                                                                        at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:324)
                                                                        at com.bumptech.glide.manager.RequestTracker.clearRemoveAndMaybeRecycle(RequestTracker.java:73)
                                                                        at com.bumptech.glide.manager.RequestTracker.clearRemoveAndRecycle(RequestTracker.java:60)
                                                                        at com.bumptech.glide.RequestManager.untrack(RequestManager.java:623)
                                                                        at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:591)
                                                                        at com.bumptech.glide.RequestManager.clear(RequestManager.java:579)
                                                                        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:616)
                                                                        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:583)
                                                                        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:576)
```

**What I've done**:

I've read this page (and each page of the FAQ):
http://bumptech.github.io/glide/doc/resourcereuse.html#common-errors
and tried the provided soultions there with no luck.

I've tried it with an ```ObjectKey ``` how it's mentioned here:
http://bumptech.github.io/glide/doc/caching.html#custom-cache-invalidation

Thanks for reading and any help is appreciated. :)

**Comment by sjudd** [comment]
I don't see anything obvious. If you're able to reproduce this in a sample app I can take a look.

**Comment by camino2007** [comment]
I'm sorry that I cannot provide a sample app, our app is too complex to extract this list into a sample. 
But I found the problem. The FAQ suggests to define transformations as a global instance, but somehow the Glide cache didn't like this in pre Lollipop devices. When I use something like this:
```         
private ImageScaleTransformation getImageScaleTransformation() {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                return imageScaleTransformation;
            } else {
                return new ImageScaleTransformation();
            }
        }
```

The crashes are gone.
