### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by GavinZhoug** [bumptech/glide#2879]
Issue happened when I scroll UI  fastly. How do I fix this bug?  or avoid it.  thank you.
Glide verson 4.6.1
Andoird verson 6.0
Integration libraries: glide-4.6.1-full.jar; annotation-4.6.1.jar;
Glide load Line:
Glide.with(context).load(url).transition(withCrossFade()).into(view);

E/AndroidRuntime( 4263): FATAL EXCEPTION: Thread-171
E/AndroidRuntime( 4263): Process: com.mgtv.tv.desktop, PID: 4263
E/AndroidRuntime( 4263): java.lang.NullPointerException: Argument must not be null
E/AndroidRuntime( 4263): 	at 
com.bumptech.glide.util.Preconditions.checkNotNull(Preconditions.java:31)
E/AndroidRuntime( 4263): 	at 
com.bumptech.glide.util.Preconditions.checkNotNull(Preconditions.java:25)
E/AndroidRuntime( 4263): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:141)
E/AndroidRuntime( 4263): 	at com.bumptech.glide.integration.volley.VolleyStreamFetcher$GlideRequest.parseNetworkError(VolleyStreamFetcher.java:136)
E/AndroidRuntime( 4263): 	at com.android.volley.NetworkDispatcher.parseAndDeliverNetworkError(NetworkDis
![_20180207143520](https://user-images.githubusercontent.com/15116718/35901933-3316ffe8-0c14-11e8-8321-af42da616856.jpg)
patcher.java:149)
E/AndroidRuntime( 4263): 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:138)

**Comment by sjudd** [comment]
Hi @GavinZhoug,

It looks like you might not have included some important information when you filed this issue. To make sure we have all the information we need to help with your issue. Please take a look at the [Issue Template](https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md) and make sure you've filled out as many sections as possible.

In particular you **must** include:

* Glide Version
* Glide load line
* Issue details.

I'm marking this issue as requiring more information. Please understand that if you do not provide that information or update the issue within the next 7 days this issue will be automatically closed so that it doesn''t clutter the bug tracker.

Best regards,

~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by GavinZhoug** [comment]
Glide verson 4.6.1

**Comment by GavinZhoug** [comment]
Glide verson 4.6.1
Andoird verson 6.0
Integration libraries: glide-4.6.1-full.jar; annotation-4.6.1.jar;
Glide load Line:
Glide.with(context).load(url).transition(withCrossFade()).into(view);

**Comment by sjudd** [comment]
I believe this happens because the volley integration library may notify that a load fails after we've cancelled it. I have a fix for that, but I'm not sure there's much you're going to be able to do to work around the issue other than use a different networking library.
