### ISSUE TITLE
java.lang.IllegalStateException: Failed to find any load path from class java.lang.String to class android.graphics.drawable.Drawable

### ISSUE THREAD

**Issue by cbruegg** [bumptech/glide#2887]
**Glide Version**: 4.6.1

**Integration libraries**: None.

**Device/Android Version**: HTC U11 (Android 8.0), Galaxy S8 (Android version unknown)

**Issue details / Repro steps / Use case background**: 
After my app has been running in the background for a longer time now, Glide fails to load images in a RecyclerView. In logcat, I can see this stacktrace:

```
E/GlideExecutor: Request threw uncaught throwable
                 java.lang.IllegalStateException: Failed to find any load path from class java.lang.String to class android.graphics.drawable.Drawable
                     at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:53)
                     at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
                     at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:266)
                     at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                     at java.lang.Thread.run(Thread.java:764)
                     at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
```
After some investigation, it seems that `Registry.getRegisteredResourceClasses(String.class, Object.class, Drawable.class)` (as set in the `DecodeHelper`) returns an empty list. This is because `decoderRegistry.getResourceClasses(dataClass, resourceClass)` with `dataClass` from `[InputStream, ParcelFileDescriptor, AssetFileDescriptor]` (as returned by `modelLoaderRegistry.getDataClasses(String.class)` and `resourceClass=Object.class` is always empty.
Unfortunately, I have no clue what any of this means.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```kotlin
GlideApp.with(holder.itemView)
            .load(postViewModel.post.imageUrl)
            .centerCrop()
            .transform(MultiTransformation<Bitmap>(DarkenTransformation(), RoundedCorners(dimensionPixelSize)))
            .transition(DrawableTransitionOptions.withCrossFade())
            .into(holder.image)
```

**Layout XML**:
```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="200dp"
    android:elevation="2dp">

    <ImageView
        android:id="@+id/rowPostBackground"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:contentDescription="@string/article_image"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        tools:srcCompat="@android:color/black" />

    <TextView
        android:id="@+id/rowPostTitle"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_marginBottom="8dp"
        android:layout_marginEnd="8dp"
        android:layout_marginStart="8dp"
        android:layout_marginTop="8dp"
        android:ellipsize="end"
        android:fontFamily="sans-serif-condensed"
        android:gravity="bottom"
        android:maxLines="3"
        android:textAppearance="@style/TextAppearance.AppCompat"
        android:textSize="18sp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.0"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_bias="1.0"
        />

    <TextView
        android:id="@+id/rowPostBreaking"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginEnd="8dp"
        android:layout_marginStart="8dp"
        android:layout_marginTop="8dp"
        android:fontFamily="sans-serif"
        android:shadowColor="@android:color/white"
        android:shadowDx="-1"
        android:shadowDy="-1"
        android:shadowRadius="1"
        android:text="@string/breaking_highlight"
        android:textAppearance="@style/TextAppearance.AppCompat"
        android:textColor="@color/colorAccent"
        android:textSize="22sp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.0"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
</android.support.constraint.ConstraintLayout>
```

**Comment by sjudd** [comment]
These values you're referring to are cached. Were the cached values empty? Or also the list returned by the registry before the cache was populated?

Do you have modify the registry directly via ``Glide.get(context).getRegistry()``? Or register any custom components in a ``GlideModule``?

I haven't seen this before. If you have any ideas on how to reproduce it let me know.

**Comment by cbruegg** [comment]
The cached values were not empty, but IIRC the lists were. I evaluated the functions that compute the cached values manually with a debugger and got the results mentioned in my first post.

I did not modify Glide's registry and neither did I register any custom components.

Unfortunately I wasn't able to reproduce this problem yet, since after a restart of the app it disappeared.

**Comment by sjudd** [comment]
Sounds similar to #2894

**Comment by liungkejin** [comment]
I have the same problem!  and i find the reason
I use this code
```
File file;
try {
    file = GlideApp.with(activity).asFile().load(url).apply(new RequestOptions().onlyRetrieveFromCache(true)).submit().get();
} catch (Exception e) {
    file = null;
}
```
All glide request is failed and throw this exception
```
E/GlideExecutor: Request threw uncaught throwable
                 java.lang.IllegalStateException: Failed to find any load path from class java.lang.String to class android.graphics.drawable.Drawable
                     at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:53)
                     at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
                     at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:266)
                     at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                     at java.lang.Thread.run(Thread.java:764)
                     at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
```

But if i change my code to
```
File file;
try {
    file = GlideApp.with(activity).downloadOnly().load(url).apply(new RequestOptions().onlyRetrieveFromCache(true)).submit().get();
} catch (Exception e) {
    file = null;
}
```

All exception gone
