### ISSUE TITLE
DisallowHardwareConfig - how to decide if we should disallow it

### ISSUE THREAD

**Issue by MFlisar** [bumptech/glide#2890]
**Glide Version**: 4.6.1

**Integration libraries**: -

**Device/Android Version**: 8.1.0, maybe more

**Issue details / Repro steps / Use case background**: 

I'm loading bitmaps via `reqeust.submit(w, h).get()` and then draw them manually onto a canvas. On one device I see following exceptions:

	LoadDataException: Class = class com.my.app.images.glide.loader.FolderItemLoader$WrappedFolderItem
	java.lang.IllegalStateException: Software rendering doesn't support hardware bitmaps
		at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:532)
		at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:62)
		at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:120)
		at android.graphics.Canvas.drawBitmap(Canvas.java:1434)
		at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
		at com.my.app.views.icon.IconDrawingUtil.a(SourceFile:192)
		at com.my.app.views.icon.IconDrawingUtil.a(SourceFile:104)
		at com.my.app.images.glide.loader.FolderItemLoader$FolderItemDataFetcher.e(SourceFile:123)
		at com.my.app.images.glide.base.BaseSidebarItemDataFetcher.a(SourceFile:81)
		at com.bumptech.glide.load.engine.SourceGenerator.a(SourceFile:62)
		at com.bumptech.glide.load.engine.DecodeJob.k(SourceFile:299)
		at com.bumptech.glide.load.engine.DecodeJob.i(SourceFile:269)
		at com.bumptech.glide.load.engine.DecodeJob.run(SourceFile:230)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at java.lang.Thread.run(Thread.java:764)
		at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(SourceFile:446)

I know I can simply use `RequestOptions.disallowHardwareConfig()`, but is there some good way to decide when I should do this? Or should I do this always, because I see such a crash?

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/hardwarebitmaps.html
