### ISSUE TITLE
DiskCacheStrategy.NONE causes com.bumptech.glide.load.engine.GlideException: Failed to load resource

### ISSUE THREAD

**Issue by JasonAndujar** [bumptech/glide#2891]
**Glide Version**:4.3.1

**Integration libraries**:retrofit 2.1.0

**Device/Android Version**:Nexus 5X API 27

**Issue details / Repro steps / Use case background**: 
Glide has been working fantastic so far, so first off thank you to the team! I am trying to download a GIF image, but avoid the caching mechanism since I would like the file extension to be .gif and it currently saves with .0 (I have read this is due to caching). Here is my request and stack trace, it's a pretty ambiguous exception :(

```
RequestOptions requestOptions = new RequestOptions()
                    .diskCacheStrategy(DiskCacheStrategy.NONE)
                    .skipMemoryCache(true);
            FutureTarget<File> future = Glide.with(getContext())
                    .downloadOnly()
                    .apply(requestOptions)
                    .load(post.getPostImage().getUrl())
                    .submit(1024, 1024);
```

Stacktrace:
```
 W/Glide: Load failed for http://trashitaliano.it/dev/wp-content/uploads/2018/02/MichellePer%c3%b2.gif with size [1024x1024]
                                                                       class com.bumptech.glide.load.engine.GlideException: Failed to load resource
com.bumptech.glide.request.RequestFutureTarget$GlideExecutionException
at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:206)
    at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:115)
at ShareFragment$GetFileTask.doInBackground(ShareFragment.java:246)
    at ShareFragment$GetFileTask.doInBackground(ShareFragment.java:233)
    at android.os.AsyncTask$2.call(AsyncTask.java:333)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
Caused by: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
```

**Comment by sjudd** [comment]
downloadOnly returns you a File from the cache. If you've disabled the cache, then the request is going to fail.

If you're just trying to download the image somewhere, use a networking library directly. Glide is for displaying content and isn't designed to act as a download manager.

**Comment by JasonAndujar** [comment]
Thanks for the response! Closing issue.
