### ISSUE TITLE
Wrong package of ProGuard ImageHeaderParser config

### ISSUE THREAD

**Issue by sosite** [bumptech/glide#2917]
**TL;DR**
Just change in proguard:
```
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
```
to
```
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
```

**Glide Version**: 4.6.1
**Device/Android Version**: Sony Xperia X Compact / Android 7.1.1
**Issue details / Repro steps / Use case background**: 
When try to build app with **enabled proguard** I received errors when try open Activity with `ImageView` with Glide loaded image.

**Stack trace**:
```
Fatal Exception: java.lang.AssertionError: impossible
       at java.lang.Enum$1.create(Enum.java:269)
       at java.lang.Enum$1.create(Enum.java:260)
       at libcore.util.BasicLruCache.get(BasicLruCache.java:58)
       at java.lang.Enum.getSharedConstants(Enum.java:286)
       at java.lang.Class.getEnumConstantsShared(Class.java:2291)
       at java.lang.JavaLangAccess.getEnumConstantsShared(JavaLangAccess.java:40)
       at java.util.EnumSet.getUniverse(EnumSet.java:389)
       at java.util.EnumSet.noneOf(EnumSet.java:107)
       at java.util.EnumSet.of(EnumSet.java:245)
       at com.bumptech.glide.load.resource.bitmap.Downsampler.(Downsampler.java:116)
       at com.bumptech.glide.Glide.(Glide.java:328)
       at com.bumptech.glide.GlideBuilder.build(GlideBuilder.java:472)
       at com.bumptech.glide.Glide.initializeGlide(Glide.java:264)
       at com.bumptech.glide.Glide.initializeGlide(Glide.java:1219)
       at com.bumptech.glide.Glide.getRetriever(Glide.java:670)
       at com.bumptech.glide.Glide.with(Glide.java:722)
       at pl.solutionslab.tikrow.data.network.GlideApp.with(GlideApp.java:104)
       at pl.solutionslab.tikrow.view.offer.details.OfferActivity.displayHeaderImg(OfferActivity.kt:169)
       at pl.solutionslab.tikrow.view.offer.details.OfferActivity.onCreate(OfferActivity.kt:123)
       at android.app.Activity.performCreate(Activity.java:6720)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2673)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2781)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1508)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:6274)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
```
Caused by java.lang.NoSuchMethodException: values []
       at java.lang.Class.getMethod(Class.java:1981)
       at java.lang.Class.getDeclaredMethod(Class.java:1960)
       at java.lang.Enum$1.create(Enum.java:265)
       at java.lang.Enum$1.create(Enum.java:260)
       at libcore.util.BasicLruCache.get(BasicLruCache.java:58)
       at java.lang.Enum.getSharedConstants(Enum.java:286)
       at java.lang.Class.getEnumConstantsShared(Class.java:2291)
       at java.lang.JavaLangAccess.getEnumConstantsShared(JavaLangAccess.java:40)
       at java.util.EnumSet.getUniverse(EnumSet.java:389)
       at java.util.EnumSet.noneOf(EnumSet.java:107)
       at java.util.EnumSet.of(EnumSet.java:245)
       at com.bumptech.glide.load.resource.bitmap.Downsampler.(Downsampler.java:116)
       at com.bumptech.glide.Glide.(Glide.java:328)
       at com.bumptech.glide.GlideBuilder.build(GlideBuilder.java:472)
       at com.bumptech.glide.Glide.initializeGlide(Glide.java:264)
       at com.bumptech.glide.Glide.initializeGlide(Glide.java:1219)
       at com.bumptech.glide.Glide.getRetriever(Glide.java:670)
       at com.bumptech.glide.Glide.with(Glide.java:722)
       at pl.solutionslab.tikrow.data.network.GlideApp.with(GlideApp.java:104)
       at pl.solutionslab.tikrow.view.offer.details.OfferActivity.displayHeaderImg(OfferActivity.kt:169)
       at pl.solutionslab.tikrow.view.offer.details.OfferActivity.onCreate(OfferActivity.kt:123)
       at android.app.Activity.performCreate(Activity.java:6720)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2673)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2781)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1508)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:6274)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**How to fix it**:
In proguard just change
```
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
```
to
```
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
```

**Comment by sjudd** [comment]
Thanks for pointing this out!

**Comment by sjudd** [comment]
Hi @sosite,

It looks like you might not have included some important information when you filed this issue. To make sure we have all the information we need to help with your issue. Please take a look at the [Issue Template](https://github.com/bumptech/glide/blob/master/ISSUE_TEMPLATE.md) and make sure you've filled out as many sections as possible.

In particular you **must** include:

* Glide Version
* Glide load line
* Issue details.

I'm marking this issue as requiring more information. Please understand that if you do not provide that information or update the issue within the next 7 days this issue will be automatically closed so that it doesn''t clutter the bug tracker.

Best regards,

~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by sjudd** [comment]
Wups this is fixed, thanks!
