### ISSUE TITLE
Display image in InfoWindow

### ISSUE THREAD

**Issue by szymonk92** [bumptech/glide#2920]
I just moved from Picasso to Glide and everything was working great except loading images in InfoWindow. According to [developers guide](https://developers.google.com/maps/documentation/android-api/infowindows) I have to refresh marker using `showInfoWindow();` and I'm doing that, in the listener. Code brakes when I am trying to invoke: `marker.showInfoWindow();` 
Removing the listener will require double click marker to display an image. 
Any suggestions? 

**Glide Version**: 4.6.1

**Code**:
```java
 Glide.with(view.getContext())
                    .asBitmap()
                    .load(images.get(marker.getId()))
                    .apply(RequestOptions.circleCropTransform())
                    .listener(new RequestListener<Bitmap>() {
                        @Override
                        public boolean onResourceReady(Bitmap resource, Object model, Target<Bitmap> target, DataSource dataSource, boolean isFirstResource) {
                            if ( marker.isInfoWindowShown()) {
                                marker.hideInfoWindow();
                                marker.showInfoWindow();
                            }
                            return false;
                        }

                        @Override
                        public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Bitmap> target, boolean isFirstResource) {
                            Timber.d("onLoadFailed");
                            handler.post(() -> Glide.with(view.getContext())
                                    .load(R.drawable.background_horizontal)
                                    .into(viewHolder.profileIcon));
                            return false;
                        }

                    })
                    .into(viewHolder.profileIcon);
```

**Stack trace / LogCat**:
```ruby
java.lang.IllegalStateException: You can't start or clear loads in RequestListener or Target callbacks. If you're trying to start a fallback request when a load fails, use RequestBuilder#error(RequestBuilder). Otherwise consider posting your into() or clear() calls to the main thread using a Handler instead.
                      at com.bumptech.glide.request.SingleRequest.assertNotCallingCallbacks(SingleRequest.java:298)
                      at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:227)
                      at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:611)
                      at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:678)
                      at com.urbanforms.main.map.InfoWindowAdapter.renderInfoWindow(InfoWindowAdapter.java:91)
                      at com.urbanforms.main.map.InfoWindowAdapter.getInfoContents(InfoWindowAdapter.java:52)
                      at com.google.android.gms.maps.zzg.zzi(Unknown Source:7)
                      at com.google.android.gms.maps.internal.zzi.onTransact(Unknown Source:40)
                      at android.os.Binder.transact(Binder.java:627)
                      at er.a(:com.google.android.gms.DynamiteModulesB@11975470:10)
                      at com.google.android.gms.maps.internal.n.b(:com.google.android.gms.DynamiteModulesB@11975470:18)
                      at com.google.maps.api.android.lib6.impl.bw.a(:com.google.android.gms.DynamiteModulesB@11975470:54)
                      at com.google.maps.api.android.lib6.impl.bw.a(:com.google.android.gms.DynamiteModulesB@11975470:73)
                      at com.google.maps.api.android.lib6.gmm6.api.e.a(:com.google.android.gms.DynamiteModulesB@11975470:36)
                      at com.google.maps.api.android.lib6.gmm6.api.g.c(:com.google.android.gms.DynamiteModulesB@11975470:154)
                      at com.google.maps.api.android.lib6.impl.cz.g(:com.google.android.gms.DynamiteModulesB@11975470:239)
                      at com.google.android.gms.maps.model.internal.q.onTransact(:com.google.android.gms.DynamiteModulesB@11975470:46)
                      at android.os.Binder.transact(Binder.java:627)
                      at com.google.android.gms.internal.zzeu.zzb(Unknown Source:7)
                      at com.google.android.gms.maps.model.internal.zzr.showInfoWindow(Unknown Source:6)
                      at com.google.android.gms.maps.model.Marker.showInfoWindow(Unknown Source:2)
                      at com.urbanforms.main.map.InfoWindowAdapter$1.onResourceReady(InfoWindowAdapter.java:70)
                      at com.urbanforms.main.map.InfoWindowAdapter$1.onResourceReady(InfoWindowAdapter.java:66)
                      at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:574)
                      at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:549)
                      at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:218)
                      at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:324)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by sjudd** [comment]
Post both hiding and showing the info window together in a single Runnable?

**Comment by szymonk92** [comment]
It's going to refresh every time user click a marker and it's going to slow down the app

**Comment by sjudd** [comment]
Sorry I missed your update.

It's fairly difficult to deal with the cleanup after recursively starting new requests. For failed loads Glide offers an additional API that allows you to start a new request without posting. We might be able to offer something similar for chaining requests when loads succeed.

I don't think either of those are going to help your case though where an API you don't control causes the recursive entry.

**Comment by szymonk92** [comment]
The problem with Runnable is that it might easily throw `java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity` invoking showInfoWindow() on the marker. I am going to dig deeper into the topic.

**Comment by chitgoks** [comment]
this should be reopened.

**Comment by chitgoks** [comment]
> It's going to refresh every time user click a marker and it's going to slow down the app.
> 
> **UPDATE** Actually with small modification Runnable works fine, but it's a workaround, isn't it?
> 
> ```
> public boolean onResourceReady(Bitmap resource, Object model, Target<Bitmap> target, DataSource dataSource, boolean isFirstResource) {
>                             new Handler().postDelayed(() -> {
>                                 if (marker.isInfoWindowShown()) {
>                                     marker.showInfoWindow();
>                                 }
>                             }, 100);
> 
>                             return false;
>                         }
> ```

TRied this. but keeps images blinking when  i move the map around
