### ISSUE TITLE
Only glide 4.6.1 has an outofmemory issue

### ISSUE THREAD

**Issue by sikeeoh** [bumptech/glide#2940]
**Glide Version**: 4.6.1
**Integration libraries**:

**Device/Android Version**: Galaxy Note8/SM-N950N 7.1.1

**Issue details / Repro steps / Use case background**: outofmemory does not occur in glide 4.5.0 but outofmemory occurs only in 4.6.1.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(ivProductImage.getContext())
                .asBitmap()
                .load(product.getPhotoUrl())
                .apply(GlideManager.getDefaultRequestOptions(context, 3))
                .transition(BitmapTransitionOptions.withCrossFade())
                .into(ivProductImage);
```

**Stack trace / LogCat**:
```log
E/GlideExecutor: Request threw uncaught throwable
                                                                     java.lang.OutOfMemoryError: Failed to allocate a 603372 byte allocation with 521568 free bytes and 509KB until OOM
                                                                         at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                         at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                         at android.graphics.Bitmap.createBitmap(Bitmap.java:977)
                                                                         at android.graphics.Bitmap.createBitmap(Bitmap.java:948)
                                                                         at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
                                                                         at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:755)
                                                                         at .manager.ImageManager.getResizePhotoBitmap(ImageManager.java:67)
                                                                         at .utils.AspectRatioCrop.transform(AspectRatioCrop.java:33)
                                                                         at com.bumptech.glide.load.resource.bitmap.BitmapTransformation.transform(BitmapTransformation.java:97)
                                                                         at com.bumptech.glide.load.engine.DecodeJob.onResourceDecoded(DecodeJob.java:531)
                                                                         at com.bumptech.glide.load.engine.DecodeJob$DecodeCallback.onResourceDecoded(DecodeJob.java:595)
                                                                         at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:46)
                                                                         at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:58)
                                                                         at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:43)
                                                                         at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:498)
                                                                         at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:469)
                                                                         at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:455)
                                                                         at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:407)
                                                                         at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:376)
                                                                         at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:135)
                                                                         at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
                                                                         at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:74)
                                                                         at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
                                                                         at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
                                                                         at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
                                                                         at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
                                                                         at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                         at java.lang.Thread.run(Thread.java:762)
                                                                         at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)

03-07 18:22:14.553 1063-1063/ W/Glide: Load failed for 95c7ae062866ec12b3fdb with size [338x383]
                                                             class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                             There was 1 cause:
                                                             java.lang.OutOfMemoryError(Failed to allocate a 603372 byte allocation with 90520 free bytes and 88KB until OOM)
                                                              call GlideException#logRootCauses(String) for more detail
                                                               Cause (1 of 1): class java.lang.OutOfMemoryError: Failed to allocate a 603372 byte allocation with 90520 free bytes and 88KB until OOM
03-07 18:22:14.554 1063-1063/ I/Glide: Root cause (1 of 1)
                                                             java.lang.OutOfMemoryError: Failed to allocate a 603372 byte allocation with 90520 free bytes and 88KB until OOM
                                                                 at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                 at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                 at android.graphics.Bitmap.createBitmap(Bitmap.java:977)
                                                                 at android.graphics.Bitmap.createBitmap(Bitmap.java:948)
                                                                 at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
                                                                 at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:755)
                                                                 at manager.ImageManager.getResizePhotoBitmap(ImageManager.java:67)
                                                                 at utils.AspectRatioCrop.transform(AspectRatioCrop.java:33)
                                                                 at com.bumptech.glide.load.resource.bitmap.BitmapTransformation.transform(BitmapTransformation.java:97)
                                                                 at com.bumptech.glide.load.engine.DecodeJob.onResourceDecoded(DecodeJob.java:531)
                                                                 at com.bumptech.glide.load.engine.DecodeJob$DecodeCallback.onResourceDecoded(DecodeJob.java:595)
                                                                 at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:46)
                                                                 at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:58)
                                                                 at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:43)
                                                                 at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:498)
                                                                 at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:469)
                                                                 at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:455)
                                                                 at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:407)
                                                                 at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:376)
                                                                 at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:135)
                                                                 at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
                                                                 at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:74)
                                                                 at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
                                                                 at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
                                                                 at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
                                                                 at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
                                                                 at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                 at java.lang.Thread.run(Thread.java:762)
                                                                 at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
03-07 18:22:14.555 1063-1063/ W/Glide: Load failed for aa4d70483dbfce49fdaa0 with size [338x383]
                                                             class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                             There was 1 cause:
                                                             java.lang.OutOfMemoryError(Failed to allocate a 603372 byte allocation with 521568 free bytes and 509KB until OOM)
                                                              call GlideException#logRootCauses(String) for more detail
                                                               Cause (1 of 1): class java.lang.OutOfMemoryError: Failed to allocate a 603372 byte allocation with 521568 free bytes and 509KB until OOM
03-07 18:22:14.556 1063-1063/ I/Glide: Root cause (1 of 1)
                                                             java.lang.OutOfMemoryError: Failed to allocate a 603372 byte allocation with 521568 free bytes and 509KB until OOM
                                                                 at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                 at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                 at android.graphics.Bitmap.createBitmap(Bitmap.java:977)
                                                                 at android.graphics.Bitmap.createBitmap(Bitmap.java:948)
                                                                 at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
                                                                 at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:755)
                                                                 at .manager.ImageManager.getResizePhotoBitmap(ImageManager.java:67)
                                                                 at .utils.AspectRatioCrop.transform(AspectRatioCrop.java:33)
                                                                 at com.bumptech.glide.load.resource.bitmap.BitmapTransformation.transform(BitmapTransformation.java:97)
                                                                 at com.bumptech.glide.load.engine.DecodeJob.onResourceDecoded(DecodeJob.java:531)
                                                                 at com.bumptech.glide.load.engine.DecodeJob$DecodeCallback.onResourceDecoded(DecodeJob.java:595)
                                                                 at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:46)
                                                                 at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:58)
                                                                 at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:43)
                                                                 at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:498)
                                                                 at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:469)
                                                                 at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:455)
                                                                 at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:407)
                                                                 at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:376)
                                                                 at com.bumptech.glide.load.engine.SourceGenerator.onDataFetcherReady(SourceGenerator.java:135)
                                                                 at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
                                                                 at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:74)
                                                                 at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
                                                                 at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:49)
                                                                 at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
                                                                 at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
                                                                 at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                 at java.lang.Thread.run(Thread.java:762)
                                                                 at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
```

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/doc/debugging.html#out-of-memory-errors
