### ISSUE TITLE
Out of memory exception when loading huge images 

### ISSUE THREAD

**Issue by ashwinkhadgi** [bumptech/glide#2971]
Glide Version:  4.6.1

Integration libraries:

Device/Android Version: Samsung Galaxy S7 (Android 7.0)

Issue details / Repro steps / Use case background:
I am working on a Weather application where I want to show weather forecast as a Map overlay.
I am loading lots of forecast images as a Bitmaps and create GroundOverlayOptions(required for Maps) 
Also I am scaling my bitmaps.

Glide load line / GlideModule (if any) / list Adapter code (if any):
//////////////////////// Glide image loading code ///////////////////////////////
  //Glide request for image downloading as Bitmap
            for (int i = 0; i < mapOverlays.size(); i++) {
                Overlay overlay = mapOverlays.get(i);
                imageTargetsArray[i] = new ImageTarget(i, overlay.getDateTime(), mapObj.getTypeId(), mapObj.getBounds());

                DecodeFormat decodeFormat = DecodeFormat.PREFER_RGB_565;
                if (mapObj.getTypeId() == 1 || mapObj.getTypeId() == 3 || mapObj.getTypeId() == 4) {
                    decodeFormat = DecodeFormat.PREFER_ARGB_8888;
                }

                GlideApp.with(this)
                        .asBitmap()
                        .format(decodeFormat)
                        .load(mapObj.getOverlayPath() + overlay.getName())
                        .transform(new LowResTransformation())
                        .into(imageTargetsArray[i]);
            }
        }

////////////////////////// Supporting classes  //////////////////////////////////////////////

protected class ImageTarget extends BaseTarget<Bitmap> {
        private int mPosition;
        private int mTypeId;
        private boolean mBitmapLoaded = false;
        private Bounds mBounds;
        private String mTime;

        public ImageTarget(int position, String time, int typeID, Bounds bounds) {
            mPosition = position;
            mTypeId = typeID;
            mBounds = bounds;
            mTime = time;
        }

        public boolean isBitmapLoaded() {
            return mBitmapLoaded;
        }

        @Override
        public void onLoadFailed(@Nullable Drawable errorDrawable) {
            super.onLoadFailed(errorDrawable);
            mBitmapLoaded = false;

            Log.e(TAG, "onBitmapFailed : for position = " + mPosition);
        }

        @Override
        public void onResourceReady(@NonNull Bitmap bitmap, @Nullable Transition<? super Bitmap> transition) {
            mBitmapLoaded = true;
            HashMap<String, GroundOverlay> groundOverlaysItemMap = mGroundOverlayMap.get(mTypeId);

            // Flag to see if we should automatically show this image.
            boolean frameVisible = !mAutoAnimating && mPosition == mAnimationFrame;

            GroundOverlayOptions overlayOptions = new GroundOverlayOptions()
                    .image(BitmapDescriptorFactory.fromBitmap(bitmap))
                    .positionFromBounds(getLatLngBounds(mBounds))
                    .visible(frameVisible);

            groundOverlaysItemMap.put(mTime, mMap.addGroundOverlay(overlayOptions));
        }

        @Override
        public void getSize(@NonNull SizeReadyCallback cb) {
            cb.onSizeReady(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL);
        }

        @Override
        public void removeCallback(@NonNull SizeReadyCallback cb) {

        }
    }

    public class LowResTransformation extends BitmapTransformation {

        private final String ID = "temp value";
        private final byte[] ID_BYTES = ID.getBytes(CHARSET);

        @Override
        protected Bitmap transform(@NonNull BitmapPool bitmapPool, @NonNull Bitmap toTransform, int outWidth, int outHeight) {

            if (toTransform.getWidth() > 1080 || toTransform.getHeight() > 1080) {
                int width = toTransform.getWidth()/3;
                int height = toTransform.getHeight()/3;
                Bitmap transformed = Bitmap.createScaledBitmap(toTransform, width, height, true);
                return BitmapResource.obtain(transformed, bitmapPool).get();
            } else {
                return toTransform;
            }
        }

        @Override
        public void updateDiskCacheKey(@NonNull MessageDigest messageDigest) {
            messageDigest.update(ID_BYTES);
        }

        @Override
        public int hashCode() {
            return ID.hashCode();
        }

        @Override
        public boolean equals(Object obj) {
            return obj instanceof LowResTransformation;
        }
    }

Glide.with...
Layout XML: 

<FrameLayout xmlns:android="...
Stack trace / LogCat:
Process: au.com.willyweather_test, PID: 16189
                                                                          java.lang.OutOfMemoryError: Failed to allocate a 4194316 byte allocation with 1244144 free bytes and 1214KB until OOM
                                                                              at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                              at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                              at android.graphics.Bitmap.createBitmap(Bitmap.java:977)
                                                                              at android.graphics.Bitmap.createBitmap(Bitmap.java:948)
                                                                              at android.graphics.Bitmap.createBitmap(Bitmap.java:915)
                                                                              at com.google.maps.api.android.lib6.gmm6.vector.gl.k.a(com.google.android.gms.DynamiteModulesB@12221448@12.2.21 (448-188803320):7)
                                                                              at com.google.maps.api.android.lib6.gmm6.vector.gl.ah.a(com.google.android.gms.DynamiteModulesB@12221448@12.2.21 (448-188803320):73)
                                                                              at com.google.maps.api.android.lib6.gmm6.vector.gl.ah.a(com.google.android.gms.DynamiteModulesB@12221448@12.2.21 (448-188803320):33)
                                                                              at com.google.maps.api.android.lib6.impl.bk.a(com.google.android.gms.DynamiteModulesB@12221448@12.2.21 (448-188803320):60)
                                                                              at com.google.maps.api.android.lib6.gmm6.api.m.a(com.google.android.gms.DynamiteModulesB@12221448@12.2.21 (448-188803320):78)
                                                                              at com.google.maps.api.android.lib6.gmm6.vector.bs.a(com.google.android.gms.DynamiteModulesB@12221448@12.2.21 (448-188803320):666)
                                                                              at com.google.maps.api.android.lib6.gmm6.vector.bs.b(com.google.android.gms.DynamiteModulesB@12221448@12.2.21 (448-188803320):270)
                                                                              at com.google.maps.api.android.lib6.gmm6.vector.bb.f(com.google.android.gms.DynamiteModulesB@12221448@12.2.21 (448-188803320):257)
                                                                              at com.google.maps.api.android.lib6.gmm6.vector.bb.run(com.google.android.gms.DynamiteModulesB@12221448@12.2.21 (448-188803320):11)
03-21 22:04:52.036 16189-20814/au.com.willyweather_test V/FA: Recording u

**Comment by ashwinkhadgi** [comment]
Please guide me which strategy should I use in such case.
I want to load a Bitmap into a Target, scale if required and create a GroundOverlay using this Bitmap.

**Comment by ashwinkhadgi** [comment]
[logs.txt](https://github.com/bumptech/glide/files/1833077/logs.txt)

Attached more detailed logs

**Comment by Saketme** [comment]
Use `RequestOptions#downsample()`.

**Comment by sjudd** [comment]
Generic advice here: http://bumptech.github.io/glide/doc/debugging.html#out-of-memory-errors
