### ISSUE TITLE
In a weak network (3G), the local picture is displayed only after the network picture fails to load.

### ISSUE THREAD

**Issue by yxcSini** [bumptech/glide#2998]
**Glide Version**:4.3.0

**Integration libraries**:okhttp3

**Device/Android Version**:Android Emulator P 27

**Issue details / Repro steps / Use case background**: 
In a weak network (3G), the local picture is displayed only after the network picture fails to load.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(this).load("http://img5.imgtn.bdimg.com/it/u=4054007864,2464688467&fm=27&gp=0.jpg").into(addImageView("Network Image"));
Glide.with(this).load("http://img.zcool.cn/community/01f17956138a5832f875a132eb1d85.jpg@1280w_1l_2o_100sh.jpg").into(addImageView("Network Image"));
Glide.with(this).load("http://img.zcool.cn/community/01ad9a56f29a3832f875a9448d2d7c.jpg").into(addImageView("Network Image"));
Glide.with(this).load("http://pic.58pic.com/58pic/13/76/61/33N58PICRdp_1024.jpg").into(addImageView("Network Image"));
Glide.with(this).load("http://img3.redocn.com/tupian/20150204/qingxinsuyashuyebiankuangppt_3868316.jpg").into(addImageView("Network Image"));
Glide.with(this).load("http://pic31.nipic.com/20130804/12906030_061954811000_2.png").into(addImageView("Network Image"));
new Handler().postDelayed(new Runnable() {
       @Override
       public void run() {
            Glide.with(TestBitmapActivity.this).load("/mnt/sdcard/temp.jpg").into(addImageView("local Image"));
      }
},2000);
```

**Layout XML**:
```xml
no xml
```

**Stack trace / LogCat**:
```ruby
03-30 05:19:05.127 5057-5057/com.paisheng.example.pslib I/ViewTarget: Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use .override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
03-30 05:19:05.129 5057-5057/com.paisheng.example.pslib I/ViewTarget: Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use .override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
03-30 05:19:06.780 5057-5057/com.paisheng.example.pslib I/ViewTarget: Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use .override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
03-30 05:19:06.780 5057-5057/com.paisheng.example.pslib I/ViewTarget: Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use .override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
03-30 05:19:15.202 5057-5057/com.paisheng.example.pslib W/Glide: Load failed for http://pic.58pic.com/58pic/13/76/61/33N58PICRdp_1024.jpg with size [2392x2392]
                                                                 class com.bumptech.glide.load.engine.GlideException: Failed to load resource
03-30 05:19:19.633 5057-5057/com.paisheng.example.pslib W/Glide: Load failed for http://img3.redocn.com/tupian/20150204/qingxinsuyashuyebiankuangppt_3868316.jpg with size [2392x2392]
                                                                 class com.bumptech.glide.load.engine.GlideException: Failed to load resource
03-30 05:19:29.641 5057-5057/com.paisheng.example.pslib W/Glide: Load failed for http://pic31.nipic.com/20130804/12906030_061954811000_2.png with size [2392x2392]
                                                                 class com.bumptech.glide.load.engine.GlideException: Failed to load resource
03-30 05:19:31.668 5057-5057/com.paisheng.example.pslib W/Glide: Load failed for http://img5.imgtn.bdimg.com/it/u=4054007864,2464688467&fm=27&gp=0.jpg with size [2392x2392]
                                                                 class com.bumptech.glide.load.engine.GlideException: Failed to load resource
03-30 05:19:41.684 5057-5057/com.paisheng.example.pslib W/Glide: Load failed for http://img.zcool.cn/community/01ad9a56f29a3832f875a9448d2d7c.jpg with size [2392x2392]
                                                                 class com.bumptech.glide.load.engine.GlideException: Failed to load resource
03-30 05:19:47.693 5057-5057/com.paisheng.example.pslib W/Glide: Load failed for http://img.zcool.cn/community/01f17956138a5832f875a132eb1d85.jpg@1280w_1l_2o_100sh.jpg with size [2392x2392]
                                                                 class com.bumptech.glide.load.engine.GlideException: Failed to load resource
```

**Comment by yxcSini** [comment]
The local picture displays error logs only after the network picture fails to load.
```ruby
03-30 05:24:22.384 5057-5057/com.paisheng.example.pslib I/ViewTarget: Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use .override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
03-30 05:24:22.385 5057-5057/com.paisheng.example.pslib I/ViewTarget: Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use .override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
03-30 05:24:24.108 5057-5057/com.paisheng.example.pslib I/ViewTarget: Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use .override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
03-30 05:24:24.108 5057-5057/com.paisheng.example.pslib I/ViewTarget: Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use .override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
03-30 05:24:32.430 5057-5057/com.paisheng.example.pslib W/Glide: Load failed for http://img5.imgtn.bdimg.com/it/u=4054007864,2464688467&fm=27&gp=0.jpg with size [2392x2392]
                                                                 class com.bumptech.glide.load.engine.GlideException: Failed to load resource
03-30 05:24:36.692 5057-5057/com.paisheng.example.pslib W/Glide: Load failed for http://img3.redocn.com/tupian/20150204/qingxinsuyashuyebiankuangppt_3868316.jpg with size [2392x2392]
                                                                 class com.bumptech.glide.load.engine.GlideException: Failed to load resource
03-30 05:24:42.744 5057-5057/com.paisheng.example.pslib W/Glide: Load failed for http://pic31.nipic.com/20130804/12906030_061954811000_2.png with size [2392x2392]
                                                                 class com.bumptech.glide.load.engine.GlideException: Failed to load resource
03-30 05:24:48.747 5057-5057/com.paisheng.example.pslib W/Glide: Load failed for http://pic.58pic.com/58pic/13/76/61/33N58PICRdp_1024.jpg with size [2392x2392]
                                                                 class com.bumptech.glide.load.engine.GlideException: Failed to load resource
03-30 05:24:52.795 5057-5057/com.paisheng.example.pslib W/Glide: Load failed for http://img.zcool.cn/community/01ad9a56f29a3832f875a9448d2d7c.jpg with size [2392x2392]
                                                                 class com.bumptech.glide.load.engine.GlideException: Failed to load resource
03-30 05:24:52.796 5057-5057/com.paisheng.example.pslib W/Glide: Load failed for /mnt/sdcard/temp.jpg with size [2392x2392]
                                                                 class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                                   Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, LOCAL
                                                                     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
                                                                       Cause (1 of 1): class java.io.FileNotFoundException: /mnt/sdcard/temp.jpg (No such file or directory)
                                                                   Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.os.ParcelFileDescriptor, LOCAL
                                                                     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
                                                                       Cause (1 of 1): class java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
03-30 05:24:52.796 5057-5057/com.paisheng.example.pslib I/Glide: Root cause (1 of 2)
                                                                 java.io.FileNotFoundException: /mnt/sdcard/temp.jpg (No such file or directory)
                                                                     at java.io.FileInputStream.open0(Native Method)
                                                                     at java.io.FileInputStream.open(FileInputStream.java:231)
                                                                     at java.io.FileInputStream.<init>(FileInputStream.java:165)
                                                                     at java.io.FileInputStream.<init>(FileInputStream.java:112)
                                                                     at android.content.ContentResolver.openInputStream(ContentResolver.java:984)
                                                                     at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResourceFromUri(StreamLocalUriFetcher.java:87)
                                                                     at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResource(StreamLocalUriFetcher.java:62)
                                                                     at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResource(StreamLocalUriFetcher.java:17)
                                                                     at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:41)
                                                                     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96)
                                                                     at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:268)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:229)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                     at java.lang.Thread.run(Thread.java:764)
                                                                     at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)
03-30 05:24:52.797 5057-5057/com.paisheng.example.pslib I/Glide: Root cause (2 of 2)
                                                                 java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
                                                                     at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:313)
                                                                     at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:211)
                                                                     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1261)
                                                                     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1189)
                                                                     at com.bumptech.glide.load.data.FileDescriptorLocalUriFetcher.loadResource(FileDescriptorLocalUriFetcher.java:22)
                                                                     at com.bumptech.glide.load.data.FileDescriptorLocalUriFetcher.loadResource(FileDescriptorLocalUriFetcher.java:14)
                                                                     at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:41)
                                                                     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96)
                                                                     at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherFailed(DecodeJob.java:393)
                                                                     at com.bumptech.glide.load.engine.SourceGenerator.onLoadFailed(SourceGenerator.java:118)
                                                                     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:149)
                                                                     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:141)
                                                                     at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:46)
                                                                     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96)
                                                                     at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:298)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:268)
                                                                     at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:229)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                     at java.lang.Thread.run(Thread.java:764)
                                                                     at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)
03-30 05:24:58.782 5057-5057/com.paisheng.example.pslib W/Glide: Load failed for http://img.zcool.cn/community/01f17956138a5832f875a132eb1d85.jpg@1280w_1l_2o_100sh.jpg with size [2392x2392]
                                                                 class com.bumptech.glide.load.engine.GlideException: Failed to load resource
```

**Comment by sjudd** [comment]
Glide's default networking library uses Glide's resize service to run network RPCs. You can avoid this by picking a more robust networking library like OkHttp and using the integration library: http://bumptech.github.io/glide/int/okhttp3.html.

**Comment by yxcSini** [comment]
@sjudd It is not a problem that the network picture fails to load, but the local image cannot be displayed immediately when the network image is being loaded. The local image will not be displayed until the network image is loaded or fails.

**Comment by yxcSini** [comment]
@sjudd I already use okhttp3

**Comment by sjudd** [comment]
I'm aware that it's not a load error. The issue you're describing is that downloading slow remote images is blocking local images. Usually that happens because you're using the default networking library which doesn't use an independent thread to run network requests on.

If you're using OkHttp, are you using the integration library I pointed to? Or just in the rest of your app?

**Comment by yxcSini** [comment]
@sjudd  
That is my config.
 //glide
        compile 'com.github.bumptech.glide:glide:4.3.0'
        compile "com.github.bumptech.glide:okhttp3-integration:4.3.0"
        annotationProcessor 'com.github.bumptech.glide:compiler:4.3.0'

**Comment by sjudd** [comment]
Are you able to reproduce it on 4.6.1? Can you attach a sample app or failing test case that reproduces the issue? http://bumptech.github.io/glide/tut/failing-test-cases.html

**Comment by yxcSini** [comment]
@sjudd This seems to be related to the type of network. Selecting UMTS in the emulator's network type, the network picture will block the loading of local pictures, the printed log will not see okhttp3. When selecting GSM it will not block and see okhttp3 log.

**Comment by sjudd** [comment]
Ah the no content provider thing is interesting in this context.

**Comment by proft** [comment]
The same error log ``No content provider`` if I select Network type = HSDPA in emulator settings.

**Comment by Sdghasemi** [comment]
Any updates on this??

**Comment by r4sh33d** [comment]
I'm experiencing the same issue. No updates yet....

**Comment by yihuaqi** [comment]
@r4sh33d @Sdghasemi @yxcSini 
That's because the default OkHttpStreamFetcher returns a SocketInputStream which could block the source thread. Read all the bytes into memory and wrap it with ByteArrayInputStream could solve this issue.
However there's a pitfall, setPriority will no longer work, because the GlideExecutor will consume the queue very fast.
`            override fun onDataReady(stream: InputStream?) {
                if (stream != null) {
                    var inputStream = stream.readBytes().let { byteArray ->
                        size = byteArray.size.toLong()
                        ByteArrayInputStream(byteArray)
                    }
                }
                 super.onDataReady(inputStream)`

**Comment by dingpengqiang** [comment]
huawei mate7, android version 5.1.1 ,but Other test mobile phones are normal.
`java.net.SocketTimeoutException: failed to connect to cp2.oss-cn-hangzhou.aliyuncs.com/47.110.23.53 (port 443) after 2500ms
        at libcore.io.IoBridge.connectErrno(IoBridge.java:181)
        at libcore.io.IoBridge.connect(IoBridge.java:122)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
        at java.net.Socket.connect(Socket.java:935)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174)
        at com.android.okhttp.Connection.connect(Connection.java:152)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:104)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:59)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:65)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
        at com.bumptech.glide.load.engin`
