### ISSUE TITLE
OutOfMemory.

### ISSUE THREAD

**Issue by taoliuh** [bumptech/glide#300]
I have a recyclerivew which hold a list view pagers, each viewPager has three pictures.and each picture's size is about 200kb.When load image from the network, the OOM occurs.And if you need, i will send you the 2 hprof file for comparison.I thought if there is something wrong with DownSampler when decodeStream.
```
803	31961100	byte[]	29	dalvik.system.VMRuntime	newNonMovableArray	
647	31961100	byte[]	32	dalvik.system.VMRuntime	newNonMovableArray	
316	31961100	byte[]	31	dalvik.system.VMRuntime	newNonMovableArray	
289	31961100	byte[]	30	dalvik.system.VMRuntime	newNonMovableArray	
279	31961100	byte[]	32	dalvik.system.VMRuntime	newNonMovableArray	
144	31961100	byte[]	29	dalvik.system.VMRuntime	newNonMovableArray	
8	31961100	byte[]	30	dalvik.system.VMRuntime	newNonMovableArray	
203	3203859	byte[]	6	org.apache.harmony.dalvik.ddmc.DdmVmInternal	getRecentAllocations	
502	3167547	byte[]	6	org.apache.harmony.dalvik.ddmc.DdmVmInternal	getRecentAllocations	
177	2764812	byte[]	32	dalvik.system.VMRuntime	newNonMovableArray	
66	2764812	byte[]	29	dalvik.system.VMRuntime	newNonMovableArray	
1000	65548	byte[]	29	com.bumptech.glide.util.ByteArrayPool	getBytes	
999	65548	byte[]	29	com.bumptech.glide.util.ByteArrayPool	getBytes	
662	65548	byte[]	32	com.bumptech.glide.util.ByteArrayPool	getBytes	
661	65548	byte[]	32	com.bumptech.glide.util.ByteArrayPool	getBytes	
380	65548	byte[]	30	com.bumptech.glide.util.ByteArrayPool	getBytes	
339	65548	byte[]	31	com.bumptech.glide.util.ByteArrayPool	getBytes	
338	65548	byte[]	30	com.bumptech.glide.util.ByteArrayPool	getBytes	
329	65548	byte[]	31	com.bumptech.glide.util.ByteArrayPool	getBytes	

  at dalvik.system.VMRuntime.newNonMovableArray(Native Method)	
  at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)	
  at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)	
  at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)	
  at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:307)	
  at com.bumptech.glide.load.resource.bitmap.Downsampler.downsampleWithSize(Downsampler.java:202)	
  at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:140)	
  at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:50)	
  at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)	
  at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:39)	
  at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)	
  at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:189)	
  at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:176)	
  at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:127)	
  at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)	
  at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)	


And the log:
12-27 14:49:42.071     601-1008/com.ganlan.poster I/art﹕ Alloc sticky concurrent mark sweep GC freed 7(192B) AllocSpace objects, 0(0B) LOS objects, 4% free, 170MB/178MB, paused 728us total 6.889ms
12-27 14:49:42.084     601-1008/com.ganlan.poster I/art﹕ Alloc partial concurrent mark sweep GC freed 99(4KB) AllocSpace objects, 0(0B) LOS objects, 8% free, 170MB/186MB, paused 609us total 11.547ms
12-27 14:49:42.117     601-1008/com.ganlan.poster I/art﹕ Alloc concurrent mark sweep GC freed 9(12KB) AllocSpace objects, 0(0B) LOS objects, 8% free, 170MB/186MB, paused 829us total 31.672ms
12-27 14:49:42.118     601-1008/com.ganlan.poster I/art﹕ Forcing collection of SoftReferences for 30MB allocation
12-27 14:49:42.137     601-1008/com.ganlan.poster I/art﹕ Alloc concurrent mark sweep GC freed 11(344B) AllocSpace objects, 0(0B) LOS objects, 8% free, 170MB/186MB, paused 524us total 18.585ms
12-27 14:49:42.138     601-1008/com.ganlan.poster E/art﹕ Throwing OutOfMemoryError "Failed to allocate a 31961100 byte allocation with 16777120 free bytes and 21MB until OOM"
12-27 14:49:52.896      601-601/com.ganlan.poster D/poster_PosterCursorAda﹕ image :http://ganlan.qiniudn.com/21de4b26453e355c865cb97765d5d880
12-27 14:49:52.897      601-601/com.ganlan.poster D/poster_PosterCursorAda﹕ image : http://ganlan.qiniudn.com/21de4b26453e355c865cb97765d5d880
12-27 14:49:53.146      601-601/com.ganlan.poster D/poster_PosterCursorAda﹕ image :http://ganlan.qiniudn.com/21de4b26453e355c865cb97765d5d880
12-27 14:49:53.147      601-601/com.ganlan.poster D/poster_PosterCursorAda﹕ image : http://ganlan.qiniudn.com/21de4b26453e355c865cb97765d5d880
12-27 14:50:45.005     601-1009/com.ganlan.poster I/art﹕ Alloc sticky concurrent mark sweep GC freed 1733(133KB) AllocSpace objects, 0(0B) LOS objects, 1% free, 184MB/186MB, paused 630us total 38.637ms
12-27 14:50:45.056     601-1009/com.ganlan.poster I/art﹕ Alloc partial concurrent mark sweep GC freed 255(9KB) AllocSpace objects, 5(152MB) LOS objects, 33% free, 31MB/47MB, paused 627us total 47.905ms
```

**Comment by sjudd** [comment]
You can use the [ComponentCallbacks][1] interface, override those methods in your Application object and call clear or trim memory on Glide then. There is a callback for when the application is backgrounded I believe.

It's possible that you're not seeing any change with those methods currently because requests are cleared in onDestroy in a viewless Fragment, which may be called before or after your Activity's onDestroy.

[1]: http://developer.android.com/reference/android/content/ComponentCallbacks2.html

**Comment by aqiansunboy** [comment]
![glide](https://cloud.githubusercontent.com/assets/6840638/7808476/0dfde1da-03c6-11e5-89b2-87066eb8ff5d.png)

does newest Glide solove memory leak in Android 2.3?

**Comment by TWiStErRob** [comment]
[Glide 2.3=API 9 is not supported](https://github.com/bumptech/glide#android-sdk-version). If you mean 2.3.3+, can you please open a new issue with a more detailed description using the [issue template](https://github.com/bumptech/glide/issues/new?body=**Glide%20Version/Integration%20library%20(if%20any)**:%0A**Device/Android%20Version**:%0A**Issue%20details/Repro%20steps**:%0A%0A**Glide%20load%20line**:%0A%60%60%60%0AGlide.with(context)...%3B%0A%60%60%60%0A%0A**Stack%20trace**:%0A%60%60%60%0Apaste%20stack%20trace%20here%0A%60%60%60) in [/CONTRIBUTING.md](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md)?
