### ISSUE TITLE
dalvikvm: DexOpt: couldn't find static field Landroid/graphics/Bitmap$Config;.HARDWARE

### ISSUE THREAD

**Issue by FedericoPonzi** [bumptech/glide#3001]
**Glide Version**: 4.6.1

**Integration libraries**: No

**Device/Android Version**: api 19, android 4.4.2, model number HSG1279,

**Issue details / Repro steps / Use case background**: I've created a simple application, that download and display images/mp4 on imageview/videoview. It works fine on my android device 8.0.0 API 26, but dosen't work on an older android tablet. It dosen't load anything, and give some weird log errors that I'm gonna attach.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GlideApp.with(this).asFile().load(new FTPFileStringWrapper(fileName))
                    .listener(new RequestListener<File>()
                    {
                        @Override
                        public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<File> target, boolean isFirstResource)
                        {
        
                            return false;
                        }
    
                        @Override
                        public boolean onResourceReady(File resource, Object model, Target<File> target, DataSource dataSource, boolean isFirstResource)
                        {
                            videoView.setVideoURI(Uri.fromFile(resource));
                            videoView.start();
                            videoView.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
                                @Override
                                public void onPrepared(MediaPlayer mp) {
                                    mp.setLooping(true);
                                }
                            });
                            return false;
                        }
                    }).submit();
```

**Layout XML**:
```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/container"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:layout_behavior="@string/appbar_scrolling_view_behavior"
    tools:context=".MainActivity"
    tools:showIn="@layout/activity_main">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center"
        android:orientation="vertical">
 <VideoView
            android:id="@+id/video_preview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:visibility="gone" />

    </LinearLayout>
</android.support.constraint.ConstraintLayout>
```

**Stack trace / LogCat**:
```ruby

03-31 14:13:10.858 9351-9351/? E/Zygote: Zygote:  error closing descriptor
    libcore.io.ErrnoException: close failed: EBADF (Bad file number)
        at libcore.io.Posix.close(Native Method)
        at libcore.io.BlockGuardOs.close(BlockGuardOs.java:75)
        at com.android.internal.os.ZygoteInit.closeServerSocket(ZygoteInit.java:198)
        at com.android.internal.os.ZygoteConnection.handleChildProc(ZygoteConnection.java:879)
        at com.android.internal.os.ZygoteConnection.runOnce(ZygoteConnection.java:242)
        at com.android.internal.os.ZygoteInit.runSelectLoop(ZygoteInit.java:661)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
        at dalvik.system.NativeStart.main(Native Method)

03-31 14:13:13.838 9351-9351/me.fponzi.instantsharing D/dalvikvm: DexOpt: couldn't find static field Landroid/graphics/Bitmap$Config;.HARDWARE
03-31 14:13:13.838 9351-9351/me.fponzi.instantsharing I/dalvikvm: DexOpt: unable to optimize static field ref 0x0087 at 0x07 in Lcom/bumptech/glide/load/engine/bitmap_recycle/LruBitmapPool;.assertNotHardwareConfig
03-31 14:13:13.838 9351-9351/me.fponzi.instantsharing D/dalvikvm: DexOpt: couldn't find static field Landroid/graphics/Bitmap$Config;.HARDWARE
03-31 14:13:13.838 9351-9351/me.fponzi.instantsharing I/dalvikvm: DexOpt: unable to optimize static field ref 0x0087 at 0x1d in Lcom/bumptech/glide/load/engine/bitmap_recycle/LruBitmapPool;.getDefaultAllowedConfigs
03-31 14:13:13.838 9351-9351/me.fponzi.instantsharing D/dalvikvm: DexOpt: couldn't find static field Landroid/graphics/Bitmap$Config;.RGBA_F16
03-31 14:13:13.838 9351-9351/me.fponzi.instantsharing I/dalvikvm: DexOpt: unable to optimize static field ref 0x0088 at 0x1d in Lcom/bumptech/glide/load/engine/bitmap_recycle/SizeConfigStrategy;.<clinit>
03-31 14:13:13.838 9351-9351/me.fponzi.instantsharing D/dalvikvm: DexOpt: couldn't find static field Landroid/graphics/Bitmap$Config;.RGBA_F16
03-31 14:13:13.838 9351-9351/me.fponzi.instantsharing I/dalvikvm: DexOpt: unable to optimize static field ref 0x0088 at 0x06 in Lcom/bumptech/glide/load/engine/bitmap_recycle/SizeConfigStrategy;.getInConfigs
03-31 14:13:13.878 9351-9351/me.fponzi.instantsharing D/dalvikvm: DexOpt: couldn't find static field Landroid/graphics/Bitmap$Config;.HARDWARE
03-31 14:13:13.878 9351-9351/me.fponzi.instantsharing I/dalvikvm: DexOpt: unable to optimize static field ref 0x0087 at 0x09 in Lcom/bumptech/glide/load/resource/bitmap/Downsampler;.setInBitmap
03-31 14:13:13.878 9351-9351/me.fponzi.instantsharing D/dalvikvm: DexOpt: couldn't find field Landroid/graphics/BitmapFactory$Options;.outConfig
03-31 14:13:13.878 9351-9351/me.fponzi.instantsharing I/dalvikvm: DexOpt: unable to optimize instance field ref 0x0094 at 0x0e in Lcom/bumptech/glide/load/resource/bitmap/Downsampler;.setInBitmap
03-31 14:13:13.898 9351-9351/me.fponzi.instantsharing D/dalvikvm: DexOpt: couldn't find static field Landroid/graphics/Bitmap$Config;.HARDWARE
03-31 14:13:13.898 9351-9351/me.fponzi.instantsharing I/dalvikvm: DexOpt: unable to optimize static field ref 0x0087 at 0x21 in Lcom/bumptech/glide/load/resource/bitmap/HardwareConfigState;.setHardwareConfigIfAllowed
03-31 14:13:13.968 9351-9609/me.fponzi.instantsharing D/dalvikvm: GC_FOR_ALLOC freed 422K, 13% free 3592K/4120K, paused 18ms, total 19ms
```
This is my android{}:
```
    compileSdkVersion 27
    defaultConfig {
        applicationId "me.fponzi.instantsharing"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
```

**Comment by FedericoPonzi** [comment]
I don't think the title is appropriate, because that log output comes even before the call to onCreate. Also, I forgot to tell that the medias are loaded via a custom ftp model loader (which works fine on my other api 26 device).
To reduce the test case, I've commented everything on my oncreate, and now looks like ths:

```
        super.onCreate(savedInstanceState);
        Log.i(TAG, "onCreate: Start");
        setContentView(R.layout.activity_main);
        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
    
        this.printerBtn = findViewById(R.id.printer_btn);
        this.imageView = findViewById(R.id.image_preview);
        this.videoView = findViewById(R.id.video_preview);
        this.containerView = findViewById(R.id.container);
        this.instagamLogin = findViewById(R.id.instagram_login_button);
        GlideApp.with(this).load("http://goo.gl/gEgYUd").into(imageView);
```

And still not working.

This is the logcat:

```ruby
03-31 16:28:04.118 22284-22284/? D/dalvikvm: Late-enabling CheckJNI
03-31 16:28:04.138 22284-22284/? E/Zygote: Zygote:  error closing descriptor
    libcore.io.ErrnoException: close failed: EBADF (Bad file number)
        at libcore.io.Posix.close(Native Method)
        at libcore.io.BlockGuardOs.close(BlockGuardOs.java:75)
        at com.android.internal.os.ZygoteInit.closeServerSocket(ZygoteInit.java:198)
        at com.android.internal.os.ZygoteConnection.handleChildProc(ZygoteConnection.java:879)
        at com.android.internal.os.ZygoteConnection.runOnce(ZygoteConnection.java:242)
        at com.android.internal.os.ZygoteInit.runSelectLoop(ZygoteInit.java:661)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
        at dalvik.system.NativeStart.main(Native Method)
03-31 16:28:04.348 22284-22303/me.fponzi.instantsharing D/dalvikvm: GC_FOR_ALLOC freed 329K, 13% free 2891K/3308K, paused 22ms, total 23ms
03-31 16:28:04.438 22284-22284/me.fponzi.instantsharing I/me.fponzi.instantsharing.MainActivity: onCreate: Start
03-31 16:28:04.458 22284-22307/me.fponzi.instantsharing D/dalvikvm: GC_FOR_ALLOC freed 270K, 11% free 3117K/3484K, paused 21ms, total 21ms
03-31 16:28:04.718 22284-22284/me.fponzi.instantsharing D/dalvikvm: GC_FOR_ALLOC freed 290K, 11% free 3341K/3720K, paused 17ms, total 17ms
03-31 16:28:04.768 22284-22284/me.fponzi.instantsharing D/dalvikvm: DexOpt: couldn't find static field Landroid/graphics/Bitmap$Config;.HARDWARE
03-31 16:28:04.768 22284-22284/me.fponzi.instantsharing I/dalvikvm: DexOpt: unable to optimize static field ref 0x0087 at 0x07 in Lcom/bumptech/glide/load/engine/bitmap_recycle/LruBitmapPool;.assertNotHardwareConfig
03-31 16:28:04.768 22284-22284/me.fponzi.instantsharing D/dalvikvm: DexOpt: couldn't find static field Landroid/graphics/Bitmap$Config;.HARDWARE
03-31 16:28:04.768 22284-22284/me.fponzi.instantsharing I/dalvikvm: DexOpt: unable to optimize static field ref 0x0087 at 0x1d in Lcom/bumptech/glide/load/engine/bitmap_recycle/LruBitmapPool;.getDefaultAllowedConfigs
03-31 16:28:04.768 22284-22284/me.fponzi.instantsharing D/dalvikvm: DexOpt: couldn't find static field Landroid/graphics/Bitmap$Config;.RGBA_F16
03-31 16:28:04.768 22284-22284/me.fponzi.instantsharing I/dalvikvm: DexOpt: unable to optimize static field ref 0x0088 at 0x1d in Lcom/bumptech/glide/load/engine/bitmap_recycle/SizeConfigStrategy;.<clinit>
03-31 16:28:04.768 22284-22284/me.fponzi.instantsharing D/dalvikvm: DexOpt: couldn't find static field Landroid/graphics/Bitmap$Config;.RGBA_F16
03-31 16:28:04.768 22284-22284/me.fponzi.instantsharing I/dalvikvm: DexOpt: unable to optimize static field ref 0x0088 at 0x06 in Lcom/bumptech/glide/load/engine/bitmap_recycle/SizeConfigStrategy;.getInConfigs
03-31 16:28:04.788 22284-22284/me.fponzi.instantsharing D/dalvikvm: DexOpt: couldn't find static field Landroid/graphics/Bitmap$Config;.HARDWARE
03-31 16:28:04.788 22284-22284/me.fponzi.instantsharing I/dalvikvm: DexOpt: unable to optimize static field ref 0x0087 at 0x09 in Lcom/bumptech/glide/load/resource/bitmap/Downsampler;.setInBitmap
03-31 16:28:04.788 22284-22284/me.fponzi.instantsharing D/dalvikvm: DexOpt: couldn't find field Landroid/graphics/BitmapFactory$Options;.outConfig
03-31 16:28:04.788 22284-22284/me.fponzi.instantsharing I/dalvikvm: DexOpt: unable to optimize instance field ref 0x0094 at 0x0e in Lcom/bumptech/glide/load/resource/bitmap/Downsampler;.setInBitmap
03-31 16:28:04.798 22284-22284/me.fponzi.instantsharing D/dalvikvm: DexOpt: couldn't find static field Landroid/graphics/Bitmap$Config;.HARDWARE
03-31 16:28:04.798 22284-22284/me.fponzi.instantsharing I/dalvikvm: DexOpt: unable to optimize static field ref 0x0087 at 0x21 in Lcom/bumptech/glide/load/resource/bitmap/HardwareConfigState;.setHardwareConfigIfAllowed
03-31 16:28:04.898 22284-22284/me.fponzi.instantsharing D/dalvikvm: GC_FOR_ALLOC freed 376K, 12% free 3480K/3944K, paused 18ms, total 18ms
03-31 16:28:04.908 22284-22304/me.fponzi.instantsharing W/AnalyticsUserIDStore: initStore should have been called before calling setUserID
03-31 16:28:05.008 22284-22284/me.fponzi.instantsharing D/OpenGLRenderer: Enabling debug mode 0
03-31 16:28:05.168 22284-22296/me.fponzi.instantsharing D/dalvikvm: GC_FOR_ALLOC freed 428K, 13% free 3564K/4080K, paused 24ms, total 24ms
03-31 16:28:19.938 22284-22304/me.fponzi.instantsharing D/dalvikvm: GC_FOR_ALLOC freed 438K, 14% free 3577K/4156K, paused 19ms, total 19ms
```

**Comment by FedericoPonzi** [comment]
I've create another project, with only glide code:
```java
package me.fponzi.testapplication;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.ImageView;

public class MainActivity extends AppCompatActivity
{
    
    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    
        ImageView imageView = (ImageView) findViewById(R.id.my_image_view);
    
        GlideApp.with(this).load("http://goo.gl/gEgYUd").into(imageView);
    }

}
```

```java
package me.fponzi.testapplication;


import com.bumptech.glide.annotation.GlideModule;
import com.bumptech.glide.module.AppGlideModule;

@GlideModule
public final class MyAppGlideModule extends AppGlideModule
{}
```

```gradle
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "me.fponzi.testapplication"
        minSdkVersion 19
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

    implementation 'com.github.bumptech.glide:glide:4.6.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.6.1'

}
```

**Comment by sjudd** [comment]
The can't find messages are expected and normal when using apps that use new sdk methods on older versions of Android.

There isn't actually any error log here. Maybe see http://bumptech.github.io/glide/doc/debugging.html#requestlistener-and-custom-logs

**Comment by FedericoPonzi** [comment]
I'm not sure why, but seems working now. Thanks anyway!
