### ISSUE TITLE
Java.lang.IllegalStateException: Cannot obtain size for recycled Bitmap: android.graphics.Bitmap@a4f3bcf[896x157] ARGB_8888

### ISSUE THREAD

**Issue by agustinsivoplas** [bumptech/glide#3013]
I have an activity with a recycler view with some backgrounds, one of the background is a set of views (dynamic views). 

To load the blurred background I use:

```
taskAcceptedContainerLayout.isDrawingCacheEnabled = true
val viewBitmap = taskAcceptedContainerLayout.drawingCache
Glide.with(mContext)
    .asBitmap()
    .load(viewBitmap)
    .into(object : SimpleTarget<Bitmap>() {
       override fun onResourceReady(bitmap: Bitmap, transition: Transition<in Bitmap>?) {                             
            taskAcceptedBlurredImageView.setImageBitmap(bitmap.blurRenderScript(mContext, CARD_VIEW_RADIUS))
             taskAcceptedContainerLayout.isDrawingCacheEnabled = false
          }
})

fun Bitmap.blurRenderScript(context: Context, radius: Float): Bitmap {
    val rs = RenderScript.create(context)
    val blurredBitmap = copy(Bitmap.Config.ARGB_8888, true)

    val input = Allocation.createFromBitmap(rs, blurredBitmap, Allocation.MipmapControl.MIPMAP_FULL, Allocation.USAGE_SHARED)
    val output = Allocation.createTyped(rs, input.type)

    val script = ScriptIntrinsicBlur.create(rs, Element.U8_4(rs))
    script.setInput(input)

    script.setRadius(radius)
    script.forEach(output)
    output.copyTo(blurredBitmap)
    return blurredBitmap
}
```

 java.lang.RuntimeException: Unable to destroy activity {com.yourpackage/com.yourpackage.DashboardActivity}: java.lang.IllegalStateException: Cannot obtain size for recycled Bitmap: android.graphics.Bitmap@a4f3bcf[896x157] ARGB_8888
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4383)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4401)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalStateException: Cannot obtain size for recycled Bitmap: android.graphics.Bitmap@a4f3bcf[896x157] ARGB_8888
        at com.bumptech.glide.util.Util.getBitmapByteSize(Util.java:78)
        at com.bumptech.glide.load.resource.bitmap.UnitBitmapDecoder$NonOwnedBitmapResource.getSize(UnitBitmapDecoder.java:49)
        at com.bumptech.glide.load.engine.EngineResource.getSize(EngineResource.java:60)
        at com.bumptech.glide.load.engine.cache.LruResourceCache.getSize(LruResourceCache.java:42)
        at com.bumptech.glide.load.engine.cache.LruResourceCache.getSize(LruResourceCache.java:13)
        at com.bumptech.glide.util.LruCache.put(LruCache.java:124)
        at com.bumptech.glide.load.engine.cache.LruResourceCache.put(LruResourceCache.java:13)
        at com.bumptech.glide.load.engine.Engine.onResourceReleased(Engine.java:326)
        at com.bumptech.glide.load.engine.EngineResource.release(EngineResource.java:112)
        at com.bumptech.glide.load.engine.Engine.release(Engine.java:286)
        at com.bumptech.glide.request.SingleRequest.releaseResource(SingleRequest.java:345)
        at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:324)
        at com.bumptech.glide.manager.RequestTracker.clearRemoveAndMaybeRecycle(RequestTracker.java:73)
        at com.bumptech.glide.manager.RequestTracker.clearRemoveAndRecycle(RequestTracker.java:60)
        at com.bumptech.glide.RequestManager.untrack(RequestManager.java:623)
        at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:591)
        at com.bumptech.glide.RequestManager.clear(RequestManager.java:579)
        at com.bumptech.glide.RequestManager.onDestroy(RequestManager.java:323)
        at com.bumptech.glide.manager.ActivityFragmentLifecycle.onDestroy(ActivityFragmentLifecycle.java:65)
        at com.bumptech.glide.manager.SupportRequestManagerFragment.onDestroy(SupportRequestManagerFragment.java:194)
        at android.support.v4.app.Fragment.performDestroy(Fragment.java:2585)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1559)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3251)
        at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3242)
        at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:265)
        at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:390)
        at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)
        at android.app.Activity.performDestroy(Activity.java:7208)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4370)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4401) 
        at android.app.ActivityThread.-wrap5(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

Any idea?

**Comment by rahulk11** [comment]
Hey @agustinsivoplas ,  were you able to solve this issue. I am also facing this issue. May be you could help?

**Comment by j05u3** [comment]
In case it is of any use for anyone coming here (like me): #2646

**Comment by AbdulMateen-Tintash** [comment]
Hi, @j05u3! Was this of any use to you by the way?
