### ISSUE TITLE
Cannot recycle a resource while it is still acquired

### ISSUE THREAD

**Issue by Archer1347** [bumptech/glide#3037]
Hello! We suffered from the issue after upgrade from v 4.3.1 to 4.4.0
**Stack trace / LogCat:**

java.lang.IllegalStateException: Cannot recycle a resource while it is still acquired
	at com.bumptech.glide.load.engine.n.f(EngineResource.java:63)
	at com.bumptech.glide.load.engine.v.a(ResourceRecycler.java:28)
	at com.bumptech.glide.load.engine.i.b(Engine.java:319)
	at com.bumptech.glide.load.engine.b.g.a(LruResourceCache.java:33)
	at com.bumptech.glide.load.engine.b.g.a(LruResourceCache.java:13)
	at com.bumptech.glide.f.e.a(LruCache.java:182)
	at com.bumptech.glide.f.e.c(LruCache.java:187)
	at com.bumptech.glide.f.e.b(LruCache.java:140)
	at com.bumptech.glide.load.engine.b.g.b(LruResourceCache.java:13)
	at com.bumptech.glide.load.engine.i.a(Engine.java:327)
	at com.bumptech.glide.load.engine.a.a(ActiveResources.java:104)
	at com.bumptech.glide.load.engine.a.a(ActiveResources.java:22)
	at com.bumptech.glide.load.engine.a$1.handleMessage(ActiveResources.java:30)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5628)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:980)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)

**Comment by sjudd** [comment]
Let me know if you're able to reproduce on 4.7.1+

**Comment by halizton** [comment]
I am now seeing this happening on 4.14.2 when using the [RequestBuilder.preload](https://bumptech.github.io/glide/javadocs/420/com/bumptech/glide/RequestBuilder.html#preload) to preload the image into cache, not frequently but it happens.
