### ISSUE TITLE
com.bumptech.glide.load.engine.GlideException: Failed to load resource

### ISSUE THREAD

**Issue by zhangYanGitHub** [bumptech/glide#3042]
04-23 11:12:39.428 16800-17244/xxx.xxx.xxx  D/skia: libjpeg error 98 <RST6> from Incomplete image data
04-23 10:25:01.671 16800-16800/xxx.xxx.xxx W/Glide: Load failed for https://www.nongmuren.com//upload/shop_12/adv/15220294870419207.jpg with size [1080x368]
                                                           class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                             Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ContentLengthInputStream->Bitmap->Bitmap}, REMOTE
                                                               Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ContentLengthInputStream->Bitmap->Bitmap}
                                                                 Cause (1 of 1): class java.io.IOException: Failed to read all expected data, expected: 8792821, but read: 5483648
04-23 10:25:01.671 16800-16800/xxx.xxx.xxx E/Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource

 04-23 10:25:01.671 16800-16800/xxx.xxx.xxx E/Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    04-23 10:25:01.673 16800-16800/xxx.xxx.xxx I/Glide: Root cause (1 of 1)
    java.io.IOException: Failed to read all expected data, expected: 8792821, but read: 5483648
    at com.bumptech.glide.util.ContentLengthInputStream.checkReadSoFarOrThrow(ContentLengthInputStream.java:73)
    at com.bumptech.glide.util.ContentLengthInputStream.read(ContentLengthInputStream.java:66)
    at com.bumptech.glide.util.ContentLengthInputStream.read(ContentLengthInputStream.java:61)
    at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:140)
    at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:309)
    at com.bumptech.glide.util.ExceptionCatchingInputStream.read(ExceptionCatchingInputStream.java:85)
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at com.bumptech.glide.util.MarkEnforcingInputStream.read(MarkEnforcingInputStream.java:45)
    at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
    at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:650)
    at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:626)
    at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:424)
    at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:243)
    at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:176)
    at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:60)
    at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:17)
    at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:67)
    at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:52)
    at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:43)
    at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
    at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
    at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:457)
    at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:450)
    at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:436)
    at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:390)
    at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:359)
    at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
    at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:129)
    at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:67)
    at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:95)
    at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
    at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:282)
    at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:252)
    at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:222)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:760)
    at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)

**Comment by qianshui423** [comment]
这个问题怎么解决的？
