### ISSUE TITLE
Svg images cannot be loaded , app crashes 

### ISSUE THREAD

**Issue by mancyzbooni** [bumptech/glide#3044]
I am trying to load an SVG image from api response , but i am getting a crash as of now 

**Glide Version**:
3.8.0

**Integration libraries**:
 "com.squareup.okhttp3:logging-interceptor:3.10.0

**Device/Android Version**:
Sony 

**Issue details / Repro steps / Use case background**: 
The app crashes when i try to load an Svg image .

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```
   <ImageView
                        android:layout_width="50dp"
                        android:layout_gravity="center"
                        android:gravity="center"
                        app:svgUrl="@{model.fulfillmentImage}"
                        android:layout_height="50dp" />

FATAL EXCEPTION: main
                                                                  Process: com.zbooni.staging, PID: 5040
                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
                                                                      at com.bumptech.glide.load.engine.EngineKey.hashCode(EngineKey.java:108)
                                                                      at sun.misc.Hashing.singleWordWangJenkinsHash(Hashing.java:48)
                                                                      at java.util.HashMap.getEntry(HashMap.java:393)
                                                                      at java.util.HashMap.get(HashMap.java:348)
                                                                      at com.bumptech.glide.load.engine.Engine.loadFromActiveResources(Engine.java:204)
                                                                      at com.bumptech.glide.load.engine.Engine.load(Engine.java:162)
                                                                      at com.bumptech.glide.request.GenericRequest.onSizeReady(GenericRequest.java:449)
                                                                      at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.getSize(ViewTarget.java:211)
                                                                      at com.bumptech.glide.request.target.ViewTarget.getSize(ViewTarget.java:100)
                                                                      at com.bumptech.glide.request.GenericRequest.begin(GenericRequest.java:272)
                                                                      at com.bumptech.glide.manager.RequestTracker.resumeRequests(RequestTracker.java:83)
                                                                      at com.bumptech.glide.RequestManager.resumeRequests(RequestManager.java:180)
                                                                      at com.bumptech.glide.RequestManager.onStart(RequestManager.java:203)
                                                                      at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStart(ActivityFragmentLifecycle.java:50)
                                                                      at com.bumptech.glide.manager.SupportRequestManagerFragment.onStart(SupportRequestManagerFragment.java:147)
                                                                      at android.support.v4.app.Fragment.performStart(Fragment.java:2218)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                      at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:241)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6274)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
Let me know if you're able to reproduce this on v4.

**Comment by mancyzbooni** [comment]
v4?? what u mean ? i am using older version ?

**Comment by sjudd** [comment]
See https://github.com/bumptech/glide/releases for the latest versions.
