### ISSUE TITLE
Change Glide OkHttpClient dynamicly

### ISSUE THREAD

**Issue by TigerZhag** [bumptech/glide#3048]
Glide Version:  4.5.0
build.gradle: 
```gradle
    implementation('com.github.bumptech.glide:glide:4.5.0') { exclude group: "com.android.support" }
    kapt 'com.github.bumptech.glide:compiler:4.5.0'
    implementation ('com.github.bumptech.glide:okhttp3-integration:4.5.0'){ exclude group: 'glide-parent' }
    implementation('jp.wasabeef:glide-transformations:3.1.0') {
        exclude group: "com.android.support"
    }
```
I need to change Glide OkhttpClient to use data network when user connect to wifi which is not connect to internet. here is my solusion:

```kotlin
@GlideModule
class GlideM : AppGlideModule(){
    override fun registerComponents(context: Context, glide: Glide, registry: Registry) {
        //如果在连接相机
        val connectivityManager = context.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M && (ptp is PtpIpService && (ptp as PtpIpService).cameraIsAp)) {
            //是相机，切换到4G网
            Log.i("zzz", "找到了相机 切换Glide至4G网络")
//            Glide.with(context).pauseAllRequests()
            var etherNetwork: Network? = null
            val dnsServers = mutableListOf<InetAddress>()
            for (network in connectivityManager.allNetworks) {
                val networkInfo = connectivityManager.getNetworkInfo(network)
                if (networkInfo.type == ConnectivityManager.TYPE_MOBILE) {
                    etherNetwork = network
                    val lp = connectivityManager.getLinkProperties(network)
                    for (addr in lp.getDnsServers()) {
                        Log.i("zzz", "network dns server: " + addr.hostAddress)
                        dnsServers.add(addr)
                    }
                }
            }
            val r1 = AndroidDnsServer.defaultResolver()
            var r2: IResolver? = null
            try {
                r2 = Resolver(InetAddress.getByName("119.29.29.29"))
            } catch (ex: IOException) {
                ex.printStackTrace()
            }
            val dns = DnsManager(NetworkInfo(NetworkInfo.NetSatus.MOBILE, NetworkInfo.ISP_GENERAL, dnsServers), arrayOf(r1, r2), null)
            val client = OkHttpClient.Builder()
                    .readTimeout(15, TimeUnit.SECONDS)
                    .connectTimeout(15, TimeUnit.SECONDS)
                    .socketFactory(etherNetwork?.socketFactory)
                    .dns { dns.queryInetAdress(Domain(it), etherNetwork).asList() }
                    .build()
            val factory = OkHttpUrlLoader.Factory(client)

            glide.registry.replace(GlideUrl::class.java, InputStream::class.java, factory)
//            Glide.with(context).resumeRequests()
        }else {
            val client = OkHttpClient.Builder()
                    .readTimeout(15, TimeUnit.SECONDS)
                    .connectTimeout(15, TimeUnit.SECONDS)
                    .addInterceptor {
                        val req = it.request()
                        Log.i("Glide", req.url().encodedPath())
                        it.proceed(req)
                    }
                    .build()

            val factory = OkHttpUrlLoader.Factory(client)
            glide.registry.replace(GlideUrl::class.java, InputStream::class.java, factory)
        }
    }
}
```
and after User change Wifi , I will invoke 
```kotlin
Glide.init(context, new GlideBuilder());
```
The problem is when I reinit Glide, My App will crash with this info(below) when loading an image
```java
java.util.concurrent.RejectedExecutionException: Task com.bumptech.glide.load.engine.DecodeJob@50fa439 rejected from java.util.concurrent.ThreadPoolExecutor@8c87a7e[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 29]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2078)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:843)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1389)
        at com.bumptech.glide.load.engine.executor.GlideExecutor.execute(GlideExecutor.java:268)
        at com.bumptech.glide.load.engine.EngineJob.start(EngineJob.java:120)
        at com.bumptech.glide.load.engine.Engine.load(Engine.java:230)
        at com.bumptech.glide.request.SingleRequest.onSizeReady(SingleRequest.java:451)
        at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.notifyCbs(ViewTarget.java:359)
        at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.checkCurrentDimens(ViewTarget.java:375)
        at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer$SizeDeterminerLayoutListener.onPreDraw(ViewTarget.java:518)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2349)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Glide Version**: 4.5.0

**Integration libraries**: 4.5.0

**Device/Android Version**: Pixel I / Android8.1 /Api level : 27

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(this@LiveDetailActivity)
                        .load(picUrl)
                        .into(holder.img)
```

**Comment by TigerZhag** [comment]
I found if I close foreground Activity , this solution is working perfectly without any problem, if not , it will crash

**Comment by TigerZhag** [comment]
solved, just change the context to Application Context

**Comment by TigerZhag** [comment]
It happened again。。

**Comment by TigerZhag** [comment]
Change okhttp client doesn't need to reinit the whole glide, just 
```kotlin
val client = OkHttpClient.Builder()
                .readTimeout(15, TimeUnit.SECONDS)
                .connectTimeout(15, TimeUnit.SECONDS)
                .socketFactory(net?.socketFactory)
                .dns { dns.queryInetAdress(Domain(it), net).asList() }
                .build()
        val factory = OkHttpUrlLoader.Factory(client)

        glide.registry.replace(GlideUrl::class.java, InputStream::class.java, factory)
```
working now

**Comment by Pinaki93** [comment]
@TigerZhag where did you get the object of glide?

**Comment by kroussevrb** [comment]
We can't do `glide.registry.replace` anymore, so how is this done from here on out?
