### ISSUE TITLE
Request threw uncaught throwable on 404 encountered when loading data

### ISSUE THREAD

**Issue by stevenfzero07** [bumptech/glide#3055]
**Glide Version**:
4.7.1

**Integration libraries**:
OkHttp3-3.4.0; using integration library okhttp3-integration-4.7.1

**Device/Android Version**:
Android Studio emulator (Pixel XL, 8.0)
Nexus 7, 6.0.1

**Issue details / Repro steps / Use case background**:
We are using a custom Model that, similar to GlideUrl, wraps a string representing a URL. As detailed in the log included in the Stack Trace section, the issue occurs when a 404 is encountered when attempting to load. The expected behavior is to load in the Drawable specified in error(). The actual behavior is that nothing loads into the ImageView. Log from Stack Trace includes references to the loadData() method inside the custom DataFetcher; code snippet of loadData() is included here.

```java
try {
	call = okHttpClient.newCall(request);
	response = call.execute();
	responseBody = response.body();
	if (!response.isSuccessful()) {
		callback.onLoadFailed(new IOException("Request failed with code: " + response.code()));
	}

	long contentLength = responseBody.contentLength();
	stream = ContentLengthInputStream.obtain(responseBody.byteStream(), contentLength);
		callback.onDataReady(stream);
} catch (Exception e) {
	callback.onLoadFailed(e);
}
```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
 GlideApp.with(fragment)
                .load(customModel) // customModel is a wrapper for Strings representing URLs 
                // plus logic for request options
                .error(placeholder) // placeHolder is a Drawable
                .into(imageView)
```

**Layout XML**:
Layout is for a row used in a RecyclerView.
```xml
<merge xmlns:android="http://schemas.android.com/apk/res/android">

    <ImageView
        android:layout_width="32dp"
        android:layout_height="32dp"
        android:layout_gravity="center_vertical|start"
        android:scaleType="centerInside"/>

    <CheckedTextView
        android:layout_width="0dp"
        android:layout_height="match_parent"
        android:layout_weight="1"
        android:layout_marginStart="24dp"
        android:ellipsize="end"
        android:gravity="center_vertical"
        android:maxLines="1"/>

    <ViewStub
        android:layout_width="wrap_content"
        android:layout_height="match_parent"/>

</merge>
```

**Stack trace / LogCat**:
```ruby
04-26 12:03:17.456 29415-29415 W/Glide: Load failed for <URL to load image data from> with size [868x168]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There were 2 causes:
    java.lang.NullPointerException(Attempt to read from field 'com.bumptech.glide.load.data.DataFetcher com.bumptech.glide.load.model.ModelLoader$LoadData.fetcher' on a null object reference)
    java.io.IOException(Request failed with code: 404)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 2): class java.lang.NullPointerException: Attempt to read from field 'com.bumptech.glide.load.data.DataFetcher com.bumptech.glide.load.model.ModelLoader$LoadData.fetcher' on a null object reference
      Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    java.io.IOException(Request failed with code: 404)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class java.io.IOException: Request failed with code: 404
04-26 12:03:17.457 29415-29415 I/Glide: Root cause (1 of 2)
    java.lang.NullPointerException: Attempt to read from field 'com.bumptech.glide.load.data.DataFetcher com.bumptech.glide.load.model.ModelLoader$LoadData.fetcher' on a null object reference
        at com.bumptech.glide.load.engine.SourceGenerator.onLoadFailed(SourceGenerator.java:119)
        at <custom DataFetcher>.loadData(<line in custom DataFetcher: callback.onLoadFailed(e);>)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
    Root cause (2 of 2)
    java.io.IOException: Request failed with code: 404
        at <line in custom DataFetcher: callback.onLoadFailed(new IOException("Request failed with code: " + response.code()));>)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
04-26 12:03:17.459 29415-29868 E/GlideExecutor: Request threw uncaught throwable
    java.lang.IllegalStateException: Already notified
        at com.bumptech.glide.load.engine.DecodeJob.setNotifiedOrThrow(DecodeJob.java:335)
        at com.bumptech.glide.load.engine.DecodeJob.notifyFailed(DecodeJob.java:321)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:249)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)

```

**Comment by sjudd** [comment]
You're calling the callback more than once:

```java
  if (!response.isSuccessful()) {
    callback.onLoadFailed(new IOException("Request failed with code: " + response.code()));
  }
```

Should probably be:
```java
  if (!response.isSuccessful()) {
    callback.onLoadFailed(new IOException("Request failed with code: " + response.code()));
    return;
  }
```
