### ISSUE TITLE
TransformationUtils.rotateImageExif may cause NullPointerException

### ISSUE THREAD

**Issue by b22n** [bumptech/glide#307]
java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Bitmap$Config.nativeInt' on a null object reference
 at android.graphics.Bitmap.createBitmap(Bitmap.java:817)
 at android.graphics.Bitmap.createBitmap(Bitmap.java:794)
 at android.graphics.Bitmap.createBitmap(Bitmap.java:761)
 at com.bumptech.glide.load.resource.bitmap.TransformationUtils.rotateImageExif(TransformationUtils.java:273)
 at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:154)
 at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:50)
 at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
 at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:39)
 at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)
 at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:189)
 at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:176)
 at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:127)
 at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
 at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
 at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 at java.lang.Thread.run(Thread.java:818)
 at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:52)

**Comment by TWiStErRob** [comment]
Hey, please help us out with your Glide version, Android version, Glide.with line and global Glide configuration, if any? Also whether it's  reproductible or only happened once, what were the circumstances? What were you doing in your app?

**Comment by sjudd** [comment]
This looks obsolete, though it's possible it was a bug in 3.4 or one of the earlier released versions. Let me know if you can reproduce on 3.4, or on head.
