### ISSUE TITLE
Package manager has died 4.6.1

### ISSUE THREAD

**Issue by peach-djf** [bumptech/glide#3104]
···
java.lang.RuntimeException: Package manager has died
  at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:304)
  at com.bumptech.glide.module.ManifestParser.parse(ManifestParser.java:35)
  at com.bumptech.glide.Glide.initializeGlide(Glide.java:228)
  at com.bumptech.glide.Glide.initializeGlide(Glide.java:219)
  at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:180)
  at com.bumptech.glide.Glide.get(Glide.java:164)
  at com.bumptech.glide.Glide.getRetriever(Glide.java:670)
  at com.bumptech.glide.Glide.with(Glide.java:697)
  at com.xxx.video.utils.ImgUtil.displayImage(ImgUtil.java:41)

···

micromax  q402  Android 6.0

**Comment by sjudd** [comment]
In Glide v4 you can disable manifest parsing, see: http://bumptech.github.io/glide/doc/configuration.html#manifest-parsing

**Comment by shahbaz-smpx** [comment]
I'm facing this same issue. Is this issue resolved?
