### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Already released

### ISSUE THREAD

**Issue by wangrunxiang** [bumptech/glide#3112]
Hello,my glide version is 4.7.1 and I found this issue is already fixed on the last release,but I can also found this problem.

**Glide Version**:4.7.1

**Integration libraries**:

**Device/Android Version**:Many devices exist this problem

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
java.lang.RuntimeException: Unable to destroy activity {com.duowan.mobile/com.yy.mobile.ui.widget.photopicker.PhotoPickActivity}: java.lang.IllegalStateException: Already released
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4398)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4417)
	at android.app.ActivityThread.-wrap6(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1629)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
Caused by: java.lang.IllegalStateException: Already released
	    at com.bumptech.glide.util.pool.StateVerifier$DefaultStateVerifier.throwIfRecycled(StateVerifier.java:46)
	    at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:317)
	    at com.bumptech.glide.manager.RequestTracker.clearRemoveAndMaybeRecycle(RequestTracker.java:78)
	    at com.bumptech.glide.manager.RequestTracker.clearRequests(RequestTracker.java:139)
	    at com.bumptech.glide.RequestManager.onDestroy(RequestManager.java:306)
	    at com.bumptech.glide.manager.ActivityFragmentLifecycle.onDestroy(ActivityFragmentLifecycle.java:65)
	    at com.bumptech.glide.manager.SupportRequestManagerFragment.onDestroy(SupportRequestManagerFragment.java:194)
	    at android.support.v4.app.Fragment.performDestroy(Fragment.java:2588)
	    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1566)
	    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	    at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
	    at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3235)
	    at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:265)
	    at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:390)
	    at com.trello.rxlifecycle2.components.support.RxFragmentActivity.onDestroy(RxFragmentActivity.java:95)
	    at com.yy.mobile.mvp.MvpActivity.onDestroy(MvpActivity.java:87)
	at com.yy.mobile.ui.DialogBaseActivity.onDestroy(DialogBaseActivity.java:124)
	at com.yy.mobile.ui.BaseActivity.onDestroy(BaseActivity.java:209)
	at com.yy.mobile.ui.widget.photopicker.PhotoPickActivity.onDestroy(PhotoPickActivity.java)
	at android.app.Activity.performDestroy(Activity.java:7141)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1158)
	    at com.yy.android.small.launcher.ApkPluginLauncher$InstrumentationWrapper.callActivityOnDestroy(ApkPluginLauncher.java:311)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4385)
	... 9 more
```

**Comment by wangrunxiang** [comment]
@sjudd

**Comment by wangrunxiang** [comment]
this problem is already call Glide.with().clear()

**Comment by CyrusCeasar** [comment]
@wangrunxiang  How do you solve this problem?
