### ISSUE TITLE
SVG Sample Crash

### ISSUE THREAD

**Issue by xmenxwk** [bumptech/glide#313]
To reproduce, open SVG Sample, let the images load on both side. Then cycle through the "Scale Type" quickly. And crash.

Using android 4.0.4

"UnsupportedOperationException. GLES20Canvas.drawPicture" usually happens when using Hardware Acceleration

``` ruby
FATAL EXCEPTION: main
    java.lang.UnsupportedOperationException
        at android.view.GLES20Canvas.drawPicture(GLES20Canvas.java:911)
        at android.graphics.drawable.PictureDrawable.draw(PictureDrawable.java:73)
        at android.widget.ImageView.onDraw(ImageView.java:973)
        at android.view.View.draw(View.java:11064)
        at android.view.ViewGroup.drawChild(ViewGroup.java:2895)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2497)
        at android.view.View.getDisplayList(View.java:10453)
        at android.view.ViewGroup.drawChild(ViewGroup.java:2858)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2497)
        at android.view.View.getDisplayList(View.java:10453)
        at android.view.ViewGroup.drawChild(ViewGroup.java:2858)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2497)
        at android.view.View.getDisplayList(View.java:10453)
        at android.view.ViewGroup.drawChild(ViewGroup.java:2858)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2497)
        at android.view.View.draw(View.java:11067)
        at android.widget.FrameLayout.draw(FrameLayout.java:450)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2196)
        at android.view.View.getDisplayList(View.java:10455)
        at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:881)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:1955)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1661)
        at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2505)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:4945)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by TWiStErRob** [comment]
I have 4.4.2 on Galaxy S4 and I can't repro this.

Note that I see a black picture when using ScaleType.CENTER, maybe it crashes when you reach that in the cycle.

Try https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#debugging to see if there's a hidden error. Try commenting out `view.setLayerType(ImageView.LAYER_TYPE_NONE, null);` in the listener.
