### ISSUE TITLE
java.lang.IllegalStateException: Already released

### ISSUE THREAD

**Issue by zczhzy** [bumptech/glide#3143]
## **fragment里面有个recyclerview，fragment点击跳转到activity，activity返回时，报错了。recyclerview里面使用glide加载图片的方法：**
Glide.with(context)
                    .load(imageUrl)
                    .apply(options)
                    .into(new SimpleTarget<Drawable>() {
                        @Override
                        public void onResourceReady(Drawable resource, Transition<? super Drawable> transition) {
                            imageView.setImageDrawable(resource);
                        }

                        @Override
                        public void onLoadFailed(@Nullable Drawable errorDrawable) {
                            
                        }
                    });

## **error:**
java.lang.RuntimeException: Unable to resume activity {com.n_add.android/com.n_add.android.activity.search.SearchResultActivity}: java.lang.IllegalStateException: Already released
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3499)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3539)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1571)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6265)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:906)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
Caused by: java.lang.IllegalStateException: Already released
	at com.bumptech.glide.util.pool.StateVerifier$DefaultStateVerifier.throwIfRecycled(StateVerifier.java:46)
	at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:228)
	at com.bumptech.glide.manager.RequestTracker.resumeRequests(RequestTracker.java:124)
	at com.bumptech.glide.RequestManager.resumeRequests(RequestManager.java:256)
	at com.bumptech.glide.RequestManager.onStart(RequestManager.java:281)
	at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStart(ActivityFragmentLifecycle.java:51)
	at com.bumptech.glide.manager.SupportRequestManagerFragment.onStart(SupportRequestManagerFragment.java:182)
	at android.support.v4.app.Fragment.performStart(Fragment.java:2372)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
	at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3206)
	at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:206)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:605)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1255)
	at android.app.Activity.performStart(Activity.java:6791)
	at android.app.Activity.performRestart(Activity.java:6865)
	at android.app.Activity.performResume(Activity.java:6870)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3476)
	... 8 more
java.lang.IllegalStateException: Already released
	at com.bumptech.glide.util.pool.StateVerifier$DefaultStateVerifier.throwIfRecycled(StateVerifier.java:46)
	at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:228)
	at com.bumptech.glide.manager.RequestTracker.resumeRequests(RequestTracker.java:124)
	at com.bumptech.glide.RequestManager.resumeRequests(RequestManager.java:256)
	at com.bumptech.glide.RequestManager.onStart(RequestManager.java:281)
	at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStart(ActivityFragmentLifecycle.java:51)
	at com.bumptech.glide.manager.SupportRequestManagerFragment.onStart(SupportRequestManagerFragment.java:182)
	at android.support.v4.app.Fragment.performStart(Fragment.java:2372)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
	at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3206)
	at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:206)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:605)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1255)
	at android.app.Activity.performStart(Activity.java:6791)
	at android.app.Activity.performRestart(Activity.java:6865)
	at android.app.Activity.performResume(Activity.java:6870)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3476)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3539)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1571)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6265)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:906)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)

**Comment by zhangli1845** [comment]
did you solve this issue?
