### ISSUE TITLE
Loading local pictures

### ISSUE THREAD

**Issue by imyyq-star** [bumptech/glide#3147]
`
ImageUtil.loadImg(MemberManagementActivity.this, R.mipmap.my_head_portrait, ivIcon);

private final static RequestOptions COMMON_OPTION = new RequestOptions().placeholder(
            R.mipmap.icon_load_failure).error(R.mipmap.icon_load_failure);

public static void loadImg(Activity context, Integer res, ImageView imageView)
    {
        into(Glide.with(context), res, imageView);
    }

private static void into(RequestManager manager, Integer resourceId, ImageView imageView)
    {
        manager.load(resourceId).apply(COMMON_OPTION).into(imageView);
    }

Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.Object[]
	at android.support.v4.util.SimpleArrayMap.allocArrays(SimpleArrayMap.java:183)
	at android.support.v4.util.SimpleArrayMap.put(SimpleArrayMap.java:437)
	at com.bumptech.glide.util.CachedHashCodeArrayMap.put(CachedHashCodeArrayMap.java:34)
	at com.bumptech.glide.load.Options.set(Options.java:22)
	at com.bumptech.glide.request.RequestOptions.set(RequestOptions.java:844)
	at com.bumptech.glide.request.RequestOptions.downsample(RequestOptions.java:971)
	at com.bumptech.glide.request.RequestOptions.optionalTransform(RequestOptions.java:1126)
	at com.bumptech.glide.request.RequestOptions.optionalCenterCrop(RequestOptions.java:1003)
	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:662)
	at xxx.xxxx.xxxxx.xxxx.util.ImageUtil.into(ImageUtil.java:110)
	at xxx.xxxx.xxxxx.xxxx.util.ImageUtil.loadImg(ImageUtil.java:54)
	at xxx.xxxx.xxxxx.xxxx.ui.activity.xxx.xxx(MemberManagementActivity.java:90)
	at xxx.xxxx.xxxxx.xxxx.ui.activity.xxx.onEvent(MemberManagementActivity.java:156)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)

`

**Comment by imyyq-star** [comment]
This is not an inevitable mistake. I don't know where it will lead to mistakes.

**Comment by imyyq-star** [comment]
`java.lang.ClassCastException: com.bumptech.glide.load.Option cannot be cast to java.lang.Object[]
at android.support.v4.util.SimpleArrayMap.allocArrays(SimpleArrayMap.java:183)
at android.support.v4.util.SimpleArrayMap.put(SimpleArrayMap.java:437)
at android.support.v4.widget.DirectedAcyclicGraph.addNode(DirectedAcyclicGraph.java:55)
at android.support.design.widget.CoordinatorLayout.prepareChildren(CoordinatorLayout.java:677)
at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:745)
at android.view.View.measure(View.java:17611)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5589)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
at android.view.View.measure(View.java:17611)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5589)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
at android.view.View.measure(View.java:17611)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5589)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
at android.view.View.measure(View.java:17611)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5589)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
at android.view.View.measure(View.java:17611)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5589)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
at android.view.View.measure(View.java:17611)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5589)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2797)
at android.view.View.measure(View.java:17611)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2297)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1439)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1656)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1315)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6534)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
at android.view.Choreographer.doCallbacks(Choreographer.java:580)
at android.view.Choreographer.doFrame(Choreographer.java:550)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5372)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1125)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)`

**Comment by shekharreddy** [comment]
We are still seeing this issue randomly, not 100% reproducible.
Sample code:

RequestOptions myOptions = new RequestOptions()
                .fitCenter()
                .disallowHardwareConfig()
                .skipMemoryCache(isCachingEnabled)
                .override(channelWidth, channelHeight)
                .diskCacheStrategy(DiskCacheStrategy.ALL);
        Bitmap bitmap = null;
        try {
            bitmap = GlideApp
                    .with(context)
                    .applyDefaultRequestOptions(myOptions)
                    .asBitmap()
                    .load(imageUrl)
                    .submit()
                    .get();
        } catch (final ExecutionException e) {
            MsvLog.e(TAG, "ExecutionException " + e);
        } catch (final InterruptedException e) {
            MsvLog.e(TAG, "InterruptedException " + e);
        }
        return bitmap;

**Comment by pyushmahore** [comment]
Below crash keeps coming everyday.

Fatal Exception: java.lang.ClassCastException: com.bumptech.glide.load.d cannot be cast to java.lang.Object[]
       at android.support.v4.util.SimpleArrayMap.allocArrays(SimpleArrayMap.java:183)
       at android.support.v4.util.SimpleArrayMap.put(SimpleArrayMap.java:437)
       at android.support.design.widget.DirectedAcyclicGraph.addNode(DirectedAcyclicGraph.java:47)
       at android.support.design.widget.CoordinatorLayout.prepareChildren(CoordinatorLayout.java:657)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:725)
       at android.view.View.measure(View.java:23265)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:23265)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
       at android.view.View.measure(View.java:23265)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:23265)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:23265)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
       at android.view.View.measure(View.java:23265)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:898)
       at android.view.View.measure(View.java:23265)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2832)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1869)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2124)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1738)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7745)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:658)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
