### ISSUE TITLE
Can't build samples?

### ISSUE THREAD

**Issue by hzsweers** [bumptech/glide#316]
I get this exception with all three samples:

```
com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Users/hsweers/dev/android/android-sdk/build-tools/19.1.0/dx --dex --output /Users/hsweers/dev/android/glide/samples/giphy/build/intermediates/pre-dexed/debug/disklrucache-efbbd88a0137c6c9884b170a00e9c2a553b15e92.jar /Users/hsweers/dev/android/glide/third_party/disklrucache/build/libs/disklrucache.jar
  Error Code:
  	1
  Output:

  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
  		at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
  		at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
  		at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
  		at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
  		at com.android.dx.command.dexer.Main.processClass(Main.java:665)
  		at com.android.dx.command.dexer.Main.processFileBytes(Main.java:634)
  		at com.android.dx.command.dexer.Main.access$600(Main.java:78)
  		at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:572)
  		at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
  		at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
  		at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
  		at com.android.dx.command.dexer.Main.processOne(Main.java:596)
  		at com.android.dx.command.dexer.Main.processAllFiles(Main.java:498)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:264)
  		at com.android.dx.command.dexer.Main.run(Main.java:230)
  		at com.android.dx.command.dexer.Main.main(Main.java:199)
  		at com.android.dx.command.Main.main(Main.java:103)
  	...while parsing com/bumptech/glide/disklrucache/DiskLruCache$1.class

  	1 error; aborting


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by hzsweers** [comment]
As a side note, it would be nice if you uploaded the sample APKs for releases for convenience. It's a bit of a hassle to have to clone and build the project first

**Comment by hzsweers** [comment]
Apparently the gradle files don't declare a target JVM version, so it was using my system's default java 8. My bad!

**Comment by sjudd** [comment]
Huh, if it's possible we could specify 6 to avoid that, it would still have to be installed though.

I can look in to uploading sample apks, signing is a bit of a issue but I'm sure we can come up with something.

**Comment by hzsweers** [comment]
Yeah even just debug signings would be fine, it's more of a convenience.

**Comment by amansatija** [comment]
Is there any way to make this work on java 8 ,?? I can't downgrade to java 6 neither can i install multiple java environment ,,

**Comment by TWiStErRob** [comment]
You can wait for 4.0 or use the [preliminary 4.0a brach](https://github.com/bumptech/glide/tree/4.0a), that should/will be supporting a higher Java version, see #110 and https://github.com/bumptech/glide/milestones/4.0
