### ISSUE TITLE
GifDecoder:   java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by wasabeef** [bumptech/glide#319]
Hi. 
Multiple gif image loading in RecyclerView cause OOM.
Any workaround for avoiding this?

```java
                        E  java.lang.OutOfMemoryError: Failed to allocate a 2825292 byte allocation with 24577 free bytes and 24KB until OOM
                        E      at com.bumptech.glide.gifdecoder.GifDecoder.setData(GifDecoder.java:379)
                        E      at com.bumptech.glide.load.resource.gif.GifDrawable.<init>(GifDrawable.java:85)
                        E      at com.bumptech.glide.load.resource.gif.GifDrawable$GifState.newDrawable(GifDrawable.java:360)
                        E      at com.bumptech.glide.load.resource.drawable.DrawableResource.get(DrawableResource.java:32)
                        E      at com.bumptech.glide.load.resource.drawable.DrawableResource.get(DrawableResource.java:16)
                        E      at com.bumptech.glide.load.engine.EngineResource.get(EngineResource.java:44)
                        E      at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:466)
                        E      at com.bumptech.glide.load.engine.Engine.load(Engine.java:154)
                        E      at com.bumptech.glide.request.GenericRequest.onSizeReady(GenericRequest.java:428)
                        E      at com.bumptech.glide.request.GenericRequest.begin(GenericRequest.java:259)
                        E      at com.bumptech.glide.request.ThumbnailRequestCoordinator.begin(ThumbnailRequestCoordinator.java:85)
                        E      at com.bumptech.glide.manager.RequestTracker.runRequest(RequestTracker.java:28)
                        E      at com.bumptech.glide.GenericRequestBuilder.into(GenericRequestBuilder.java:611)
                        E      at com.bumptech.glide.GenericRequestBuilder.into(GenericRequestBuilder.java:647)
                        E      at com.bumptech.glide.DrawableRequestBuilder.into(DrawableRequestBuilder.java:436)
                        E      at jp.co.cyberagent.madrid.ui.adapter.binder.FeedTimelineBinder.setPostImage(FeedTimelineBinder.java:222)
                        E      at jp.co.cyberagent.madrid.ui.adapter.binder.FeedTimelineBinder.bindViewHolder(FeedTimelineBinder.java:119)
                        E      at jp.co.cyberagent.madrid.ui.adapter.binder.FeedTimelineBinder.bindViewHolder(FeedTimelineBinder.java:57)
                        E      at jp.co.cyberagent.madrid.ui.adapter.DataBindAdapter.onBindViewHolder(DataBindAdapter.java:37)
                        E      at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:4138)
                        E      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3448)
                        E      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3340)
                        E      at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1810)
                        E      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1306)
                        E      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1269)
                        E      at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1097)
                        E      at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:957)
                        E      at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:2797)
                        E      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                        E      at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                        E      at android.view.Choreographer.doFrame(Choreographer.java:549)
                        E      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                        E      at android.os.Handler.handleCallback(Handler.java:739)
                        E      at android.os.Handler.dispatchMessage(Handler.java:95)
                        E      at android.os.Looper.loop(Looper.java:135)
                        E      at android.app.ActivityThread.main(ActivityThread.java:5221)
                        E      at java.lang.reflect.Method.invoke(Native Method)
                        E      at java.lang.reflect.Method.invoke(Method.java:372)
                        E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                        E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by sjudd** [comment]
How large are the GIFs? Large GIFs (> 1k by 1k at least) can increased memory pressure because they can't yet be downsampled. 

If you're not loading a ton of GIFs or a few large ones, the most common cause of OOM exceptions is usually some kind of memory leak. Have you looked at a heap bump? Bitmap/GIF or other large allocations commonly throw the actual OOM exception even when the underlying cause is a memory leak somewhere else in the application.

**Comment by wasabeef** [comment]
Hi.

Yes Large Gifs (7Mb * 3).
I no longer occurs using the override and centerCrop :D

**Comment by hatpick** [comment]
I have a small gif (200KB) and I get this OOM exception, how can I solve the issue?

**Comment by TWiStErRob** [comment]
The GIF format is compressed as well as JPEG and PNG. They're all able to express extreme amount of pixels in a very small file size, that's why they were invented. Android requires uncompressed bitmaps in memory which need huge allocations sometimes: the area of the image (in pixels) times the bit depth (16-24-32) in bytes. So a 10kB image can easily represent a 4000*5000 big image which comes up to 80MB with transparency (32bits/ARGB8888) in memory.

Search for OOM or "Out of memory" or OutOfMemoryError in Glide issues for more on how to resolve it. Most likely a leak somewhere else as Sam said here, if not an extremely large image. Please open another issue if you've checked your app for leaks, fixed them and it still happens.

**Comment by jatin-lakhani** [comment]
+1
I'm having same issue...

Multiple gif image loading in RecyclerView cause OOM.
Any workaround for avoiding this?

**Comment by TWiStErRob** [comment]
1. Make sure you have no leaks
2. Make sure Glide is able to load the smallest possible Bitmaps (i.e. no `override` and a good layout).
3. If it still happens, consider not playing all the GIFs at once, only when tapped. This is especially needed if the original GIF files are huge (multiple megs). Two loads: `.asBitmap().diskCacheStrategy(SOURCE)` for still image in bind, and then no `asBitmap` when user taps.
