### ISSUE TITLE
Load remote video with DiskCacheStrategy.RESOURCE will got FileNotFoundException

### ISSUE THREAD

**Issue by hvsimon** [bumptech/glide#3196]
**Glide Version**: 4.7.1

**Device/Android Version**: HTC Desire 820 5.0.2

**Issue details / Repro steps / Use case background**: 
I want to show the video thumbnail with mp4 source from server and it work with default diskCacheStrategy.
But the Android Profiler - Network Profiler show Glide load whole video source, it take too much time.
So I set diskCacheStrategy to `DiskCacheStrategy.RESOURCE` then I got `FileNotFoundException`.

Not only `DiskCacheStrategy.RESOURCE` but also `DiskCacheStrategy.NONE`.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
Success
```java
GlideApp.with(context)
    .load(url) // .mp4
    .into(imageVIew)
```

Failure
```
GlideApp.with(context)
    .load(url) // .mp4
    .diskCacheStrategy(DiskCacheStrategy.RESOURCE)
    .into(imageVIew)
```

**Stack trace / LogCat**:
```ruby
Root cause (1 of 1)
    java.io.FileNotFoundException: No content provider: private url
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1131)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:986)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:913)
        at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:22)
        at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:13)
        at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:418)
        at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:379)
        at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:112)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:135)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:60)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
```

**Comment by sjudd** [comment]
Duplicate of #2894
