### ISSUE TITLE
java.lang.NoClassDefFoundError: com.bumptech.glide.RequestManager 

### ISSUE THREAD

**Issue by ulx** [bumptech/glide#320]
android 2.3
I use lib glide v3.5 and have exception 
 java.lang.NoClassDefFoundError: com.bumptech.glide.RequestManager
            at com.bumptech.glide.manager.RequestManagerRetriever.supportFragmentGet(RequestManagerRetriever.java:184)
            at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:103)
            at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:86)
            at com.bumptech.glide.Glide.with(Glide.java:609)

**Comment by sjudd** [comment]
Looks like 3.5 broke support for 2.3. I'll push a dot release with a fix by Friday. Sorry for the inconvenience!
