### ISSUE TITLE
Caused by java.util.ConcurrentModificationException - Bitmap loading crash

### ISSUE THREAD

**Issue by shekharreddy** [bumptech/glide#3213]
Glide version 4.7.1
Not used any integration libraries.
Issue observed on Galaxy S6, Galaxy S7, Galaxy Tab A 10.1, Nexus 6P, and other devices.
Android OS version 6, 7 and 8
Observed on Crashlytics portal, not 100% reproducible.

**Crash details:** 

Caused by java.util.ConcurrentModificationException
       at android.support.v4.util.SimpleArrayMap.put(SimpleArrayMap.java:461)
       at com.bumptech.glide.util.CachedHashCodeArrayMap.put(CachedHashCodeArrayMap.java:34)
       at android.support.v4.util.ArrayMap.putAll(ArrayMap.java:141)
       at com.bumptech.glide.request.RequestOptions.apply(RequestOptions.java:1433)
       at com.x.x.x.x.imagedownloader.GlideOptions.apply(GlideOptions.java:605)
       at com.x.x.x.x..imagedownloader.GlideOptions.apply(GlideOptions.java:31)
       at com.bumptech.glide.RequestManager.updateRequestOptions(RequestManager.java:128)
       at com.bumptech.glide.RequestManager.applyDefaultRequestOptions(RequestManager.java:151)
       at com.x.x.x.x.imagedownloader.GlideRequests.applyDefaultRequestOptions(GlideRequests.java:51)
       at com.x.x.x.x.imagedownloader.GlideImageDownloader.loadImageAsBitmap(GlideImageDownloader.java:171)
       at com.x.x.x.x.imageprocessing.IPGImageWorker$BitmapWorkerTask.doInBackground(IPGImageWorker.java:275)
       at com.x.x.x.x.imageprocessing.IPGImageWorker$BitmapWorkerTask.onPostExecute(IPGImageWorker.java:232)
       at com.x.x.x.x.imageprocessing.IpgAsyncTask$2.call(IpgAsyncTask.java:314)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Sample code:**

RequestOptions myOptions = new RequestOptions()
                .fitCenter()
                .disallowHardwareConfig()
                .skipMemoryCache(isCachingEnabled)
                .override(channelWidth, channelHeight)
                .diskCacheStrategy(DiskCacheStrategy.ALL);
        Bitmap bitmap = null;
        try {
            bitmap = GlideApp
                    .with(context)
                    .applyDefaultRequestOptions(myOptions)
                    .asBitmap()
                    .load(imageUrl)
                    .submit()
                    .get();
        } catch (final ExecutionException e) {
            MsvLog.e(TAG, "ExecutionException " + e);
        } catch (final InterruptedException e) {
            MsvLog.e(TAG, "InterruptedException " + e);
        }
        return bitmap;

**Comment by sjudd** [comment]
It's not safe to call applyDefaultRequestOptions on a background thread. applyDefaultRequestOptions changes the options for all future calls with that RequestManager, it's not for individual requests. 

You want `apply`: http://bumptech.github.io/glide/doc/options.html#requestoptions

**Comment by CharlieZheng** [comment]
I am facing the same crash

I invoke the glide code in the main thread

crash details:

`
Caused by java.util.ConcurrentModificationException
       at androidx.collection.SimpleArrayMap.put(SimpleArrayMap.java:482)
       at com.bumptech.glide.util.CachedHashCodeArrayMap.put(CachedHashCodeArrayMap.java:34)
       at com.bumptech.glide.request.BaseRequestOptions.transform(BaseRequestOptions.java:1017)
       at com.bumptech.glide.request.BaseRequestOptions.transform(BaseRequestOptions.java:971)
       at com.bumptech.glide.request.BaseRequestOptions.optionalTransform(BaseRequestOptions.java:830)
       at com.bumptech.glide.request.BaseRequestOptions.scaleOnlyTransform(BaseRequestOptions.java:871)
       at com.bumptech.glide.request.BaseRequestOptions.optionalScaleOnlyTransform(BaseRequestOptions.java:858)
       at com.bumptech.glide.request.BaseRequestOptions.optionalFitCenter(BaseRequestOptions.java:738)
       at pullrefresh.lizhiyun.com.baselibrary.imageGlide.GlideImageLoader.getRequestOptions2(GlideImageLoader.java:128)
       at pullrefresh.lizhiyun.com.baselibrary.imageGlide.GlideImageLoader.showImage(GlideImageLoader.java:51)
       at pullrefresh.lizhiyun.com.baselibrary.image.ImageLoaderManager.showImage(ImageLoaderManager.java:28)
       at pullrefresh.lizhiyun.com.baselibrary.image.ImageOption.show(ImageOption.java:374)
       at pullrefresh.lizhiyun.com.baselibrary.image.ImageLoader.show(ImageLoader.java:43)
       at com.interfocusllc.patpat.ui.home.widget.NewPatSnackbar.<init>(NewPatSnackbar.java:82)
       at com.interfocusllc.patpat.ui.home.widget.NewPatSnackbar.<init>(NewPatSnackbar.java:60)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at android.view.LayoutInflater.createView(LayoutInflater.java:686)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:829)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:902)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:905)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:554)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:461)
       at pullrefresh.lizhiyun.com.baselibrary.base.BaseFrg.onCreateView(BaseFrg.java:43)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
       at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2224)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1997)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
       at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1818)
       at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
       at com.interfocusllc.patpat.ui.adapter.ReplaceableFragmentPagerAdapter.finishUpdate(ReplaceableFragmentPagerAdapter.java:102)
       at pullrefresh.lizhiyun.com.baselibrary.view.DelegatingPagerAdapter.finishUpdate(DelegatingPagerAdapter.java:46)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
       at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
       at pullrefresh.lizhiyun.com.baselibrary.view.RtlViewPager.onMeasure(RtlViewPager.java:208)
       at android.view.View.measure(View.java:24955)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:978)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
       at android.view.View.measure(View.java:24955)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7149)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:24955)
       at android.view.ViewGroup.measureChild(ViewGroup.java:7120)
       at pullrefresh.lizhiyun.com.baselibrary.view.statelayout.LayoutLevelView.mc(LayoutLevelView.java:59)
       at pullrefresh.lizhiyun.com.baselibrary.view.statelayout.LayoutLevelView.onMeasure(LayoutLevelView.java:44)
       at android.view.View.measure(View.java:24955)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7149)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
       at android.view.View.measure(View.java:24955)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7149)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
       at android.view.View.measure(View.java:24955)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7149)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:24955)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7149)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
       at android.view.View.measure(View.java:24955)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7149)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1029)
       at android.view.View.measure(View.java:24955)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3338)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2067)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2366)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1927)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8558)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:696)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7094)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
`
