### ISSUE TITLE
java.lang.Throwable: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage

### ISSUE THREAD

**Issue by rekirt** [bumptech/glide#3217]
when i open StrictMode，there is a warn log,how can i fix it
 

java.lang.Throwable: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
                                                                      at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2012)
                                                                      at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:78)
                                                                      at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:47)
                                                                      at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:310)
                                                                      at libcore.io.IoBridge.socket(IoBridge.java:667)
                                                                      at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:116)
                                                                      at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:98)
                                                                      at java.net.Socket.createImpl(Socket.java:484)
                                                                      at java.net.Socket.getImpl(Socket.java:547)
                                                                      at java.net.Socket.setSoTimeout(Socket.java:1175)
                                                                      at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:139)
                                                                      at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
                                                                      at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
                                                                      at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
                                                                      at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
                                                                      at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
                                                                      at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
                                                                      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
                                                                      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
                                                                      at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:72)
                                                                      at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:44)
                                                                      at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:20)
                                                                      at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:70)
                                                                      at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:53)
                                                                      at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
                                                                      at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
                                                                      at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
                                                                      at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
                                                                      at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                      at java.lang.Thread.run(Thread.java:764)

**Comment by dikkini** [comment]
I got such error when connect to VPN

**Comment by krantiveersapalya** [comment]
i think u r connected with charles or any vpn please reconnect it ..        check ip and host name
