### ISSUE TITLE
Only the original thread that created a view hierarchy can touch its views.

### ISSUE THREAD

**Issue by huangbryant210707** [bumptech/glide#3220]
**Glide Version**: com.github.bumptech.glide:okhttp3-integration:1.4.0@aar

**Integration libraries**:

**Device/Android Version**: MI3  5.1

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(imageView.getContext()).load(imageUrl).asBitmap().centerCrop().
                placeholder(errorImgResouce).error(errorImgResouce).
                diskCacheStrategy(DiskCacheStrategy.ALL).
                dontAnimate().into(imageView);
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7229)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1072)
	at android.view.View.requestLayout(View.java:17932)
	at android.view.View.requestLayout(View.java:17932)
	at android.view.View.requestLayout(View.java:17932)
	at android.view.View.requestLayout(View.java:17932)
	at android.view.View.requestLayout(View.java:17932)
	at android.view.View.requestLayout(View.java:17932)
	at android.view.View.requestLayout(View.java:17932)
	at android.widget.ImageView.setImageDrawable(ImageView.java:454)
	at android.support.v7.widget.AppCompatImageView.setImageDrawable(SourceFile:100)
	at com.bumptech.glide.request.b.e.c(SourceFile:48)
	at com.bumptech.glide.request.GenericRequest.b(SourceFile:276)
	at com.bumptech.glide.manager.l.b(SourceFile:83)
	at com.bumptech.glide.h.c(SourceFile:180)
	at com.bumptech.glide.h.d(SourceFile:203)
	at com.bumptech.glide.manager.a.a(SourceFile:50)
	at com.bumptech.glide.manager.SupportRequestManagerFragment.onStart(SourceFile:135)
```

**Comment by Drjacky** [comment]
For me this happened when I used `submit` on `RequestListener`
