### ISSUE TITLE
 com.bumptech.glide.load.engine.GlideException: Failed to load resource

### ISSUE THREAD

**Issue by liuhea** [bumptech/glide#3227]
**Glide Version**:

    implementation 'com.github.bumptech.glide:glide:4.4.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.4.0'

**Integration libraries**:

**Device/Android Version**:

Android 4.4 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
            Glide.with(context).asGif().apply(options).load(drawableId).into(targetView);
```

**Stack trace / LogCat**:
```ruby


07-25 14:00:48.856 9806-9806/cn.xtev.giftest W/Glide: Load failed for 2131099736 with size [1920x656]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{AssetInputStream->GifDrawable->GifDrawable}, LOCAL
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AssetInputStream->GifDrawable->GifDrawable}
          Cause (1 of 1): class java.lang.NullPointerException: 
07-25 14:00:48.866 9806-9806/cn.xtev.giftest I/Glide: Root cause (1 of 1)
    java.lang.NullPointerException
        at com.bumptech.glide.gifdecoder.StandardGifDecoder.copyCopyIntoScratchRobust(StandardGifDecoder.java:606)
        at com.bumptech.glide.gifdecoder.StandardGifDecoder.setPixels(StandardGifDecoder.java:475)
        at com.bumptech.glide.gifdecoder.StandardGifDecoder.getNextFrame(StandardGifDecoder.java:282)
        at com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder.decode(ByteBufferGifDecoder.java:104)
        at com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder.decode(ByteBufferGifDecoder.java:82)
        at com.bumptech.glide.load.resource.gif.ByteBufferGifDecoder.decode(ByteBufferGifDecoder.java:33)
        at com.bumptech.glide.load.resource.gif.StreamGifDecoder.decode(StreamGifDecoder.java:50)
        at com.bumptech.glide.load.resource.gif.StreamGifDecoder.decode(StreamGifDecoder.java:22)
        at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:68)
        at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:53)
        at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:44)
        at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:56)
        at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:42)
        at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:499)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:471)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:457)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:411)
        at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:380)
        at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:111)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:132)
        at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:51)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:303)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:273)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:445)

```

**Comment by liuhea** [comment]
![default](https://user-images.githubusercontent.com/19663285/43196258-f425a67c-9039-11e8-86ad-efedf189a025.gif)

**Comment by liuhea** [comment]
?

**Comment by yangjiantao** [comment]
i meet the same problem

**Comment by sjudd** [comment]
I'm not able to reproduce in a test: https://github.com/sjudd/glide/commit/cbe257e3a7851397f54cdbd2df0f42935d966bf9.

If you can modify that test to reproduce the failure and can send a pull request with the failing test I'd be happy to take a look.

**Comment by sjc90516** [comment]
解决了吗？

Did that solve?
