### ISSUE TITLE
Crash: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@xxxxxxx when using Theme.AppCompat.NoActionBar theme.

### ISSUE THREAD

**Issue by zeroarst** [bumptech/glide#3228]
**Glide Version**: 4.7.1

**Device/Android Version**: Samsung S7 Edge

**Issue details / Repro steps / Use case background**: 

In FirstActivity.kt it pulls the image from the internet, click "LOAD" button, go to SecondActivity.kt, then click "GO BACK", it will go back to FirstActivity and try to load the same image again with different alpha. then the app crashes. This happens when use the theme `Theme.AppCompat.NoActionBar`. 
I created a repo to reproduce the issue. https://github.com/zeroarst/TestGlideCrash
If you change to default theme `Theme.AppCompat.Light.DarkActionBar` in `style.xml` it won't crash...very strange...

I spent two days to find out this issue...tried every thing in my project but none of them work. So I created a new project, gradually added things, until I found the cause of the issue..

I looked at the log, I notice there is line said: `Theme.AppCompat.Light.DarkActionBar`, I don't know if this is relevant, maybe not.

**Style XML**:
```xml
<resources>

    <!-- Base application theme. -->

     <!-- This causes crash -->
    <style name="AppTheme" parent="Theme.AppCompat.NoActionBar">

    </style>

     <!-- This won't crash -->
    <!--<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">-->

    <!--</style>-->

</resources>

```

**Stack trace / LogCat**:
```ruby
W/Bitmap: Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
              (HTTPLog)-Static: isSBSettingEnabled false
V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
D/ViewRootImpl@aa9add9[FirstActivity]: Relayout returned: old=[0,0][1080,1920] new=[0,0][1080,1920] result=0x7 surface={valid=true 544783900672} changed=true
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1080x1920]-format:1
D/OpenGLRenderer: eglCreateWindowSurface = 0x7edf81da00
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.zeorarst.testglidecrash, PID: 1463
                  java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@4049fdf
                      at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:55)
                      at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:226)
                      at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
                      at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
                      at android.widget.ImageView.onDraw(ImageView.java:1367)
                      at android.view.View.draw(View.java:20370)
                      at android.view.View.updateDisplayListIfDirty(View.java:19315)
                      at android.view.View.draw(View.java:20093)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
                      at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1966)
                      at android.view.View.updateDisplayListIfDirty(View.java:19306)
                      at android.view.View.draw(View.java:20093)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
                      at android.view.View.updateDisplayListIfDirty(View.java:19306)
                      at android.view.View.draw(View.java:20093)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
                      at android.view.View.updateDisplayListIfDirty(View.java:19306)
                      at android.view.View.draw(View.java:20093)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
                      at android.view.View.updateDisplayListIfDirty(View.java:19306)
                      at android.view.View.draw(View.java:20093)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
                      at android.view.View.updateDisplayListIfDirty(View.java:19306)
                      at android.view.View.draw(View.java:20093)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
                      at android.view.View.draw(View.java:20373)
                      at com.android.internal.policy.DecorView.draw(DecorView.java:980)
                      at android.view.View.updateDisplayListIfDirty(View.java:19315)
                      at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
                      at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
                      at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:800)
                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:3459)
                      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3246)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2781)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1743)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7780)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                      at android.view.Choreographer.doFrame(Choreographer.java:658)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                      at android.os.Handler.handleCallback(Handler.java:789)
                      at android.os.Handler.dispatchMessage(Handler.java:98)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6944)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by sembozdemir** [comment]
@zeroarst did you fix this issue with NoActionBar theme?
