### ISSUE TITLE
Rare RejectedExecutionException

### ISSUE THREAD

**Issue by Tolriq** [bumptech/glide#3235]
Glide 4.7.1

Got some really rare crash where Glide is trying to send task to a terminated executor.
Can't reproduce for the moment, but since it's fully inside Glide I suppose adding a !isTerminated could reduce that, but no idea of the side effects.

@sjudd 

```
Caused by java.util.concurrent.RejectedExecutionException: Task com.a.a.c.b.j@86fdb73 rejected from java.util.concurrent.ThreadPoolExecutor@6ff2ff[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 99]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2078)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:843)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1389)
       at com.bumptech.glide.load.engine.executor.GlideExecutor.execute(GlideExecutor.java:268)
       at com.bumptech.glide.request.SingleRequest.com.bumptech.glide.load.engine.EngineJob.start(SingleRequest.java:22120)
       at com.bumptech.glide.request.target.ViewTarget.com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.getSize(ViewTarget.java:1383)
       at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:264)
       at com.bumptech.glide.RequestManager.com.bumptech.glide.manager.RequestTracker.resumeRequests(RequestManager.java:4124)
       at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStart(ActivityFragmentLifecycle.java:51)
       at com.bumptech.glide.manager.SupportRequestManagerFragment.onStart(SupportRequestManagerFragment.java:182)
       at android.support.v4.app.Fragment.performStart(Fragment.java:2372)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
       at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3206)
       at android.support.v4.app.Fragment.performStart(Fragment.java:2378)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
       at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3212)
       at android.support.v4.app.FragmentActivity.android.support.v4.app.FragmentController.dispatchResume(FragmentActivity.java:9217)
       at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
       at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:171)
       at android.app.Activity.performResume(Activity.java:7368)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3763)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3828)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1746)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by Tolriq** [comment]
unstale :)

**Comment by sjudd** [comment]
The executor is actually not dead, it's task queue is full (there are 99 items in queue). That means that some particular blocking task is running for a super long time, or there's some kind of deadlock.

One possibility is lots of requests with a fairly slow network connection when you're using Glide's default networking library. Another is some kind of custom DataFetcher that uses a library that could cause deadlock. Another is trying to start recursive loads in Glide without using http://bumptech.github.io/glide/javadocs/480/com/bumptech/glide/request/RequestOptions.html#useUnlimitedSourceGeneratorsPool-boolean-

**Comment by Tolriq** [comment]
@sjudd 

Caused by java.util.concurrent.RejectedExecutionException: Task com.a.a.c.b.j@86fdb73 rejected from java.util.concurrent.ThreadPoolExecutor@6ff2ff[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 99]

This means it has executed 99 tasks ;) That it have 0 in queue, 0 thread and is terminated ;)

**Comment by Tolriq** [comment]
Another variant to the same result trying to queue on terminated pool.

```
Fatal Exception: java.util.concurrent.RejectedExecutionException: Task com.a.a.c.b.j@89621aa rejected from java.util.concurrent.ThreadPoolExecutor@5898733[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 23]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2014)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1340)
       at com.bumptech.glide.load.engine.executor.GlideExecutor.execute(GlideExecutor.java:268)
       at com.bumptech.glide.request.SingleRequest.com.bumptech.glide.load.engine.EngineJob.start(SingleRequest.java:22120)
       at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.notifyCbs(ViewTarget.java:1359)
       at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer$SizeDeterminerLayoutListener.onPreDraw(ViewTarget.java:518)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1014)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2513)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1440)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7421)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
       at android.view.Choreographer.doCallbacks(Choreographer.java:695)
       at android.view.Choreographer.doFrame(Choreographer.java:631)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7230)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by Tolriq** [comment]
@sjudd this is really a bug :) [Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 23]
 
No way to have a fix for 4.8.0?

**Comment by sjudd** [comment]
Ah thanks I misread this. 

I don't have any internal reports of this. Let me know if you're able to reproduce it or have an idea about how it could happen.

**Comment by Tolriq** [comment]
@sjudd 
I can't reproduce and the 2 stack traces seems to be the only cases it happens.

Happens on Android 5 6 7 8 Samsung Huawey and LGE.

But probably all devices and all OS but just 10 crash over the last 90 days so very little sample and very rare crash.

But since SupportLibrary 28 will finally fix a multiple years bug I'm hopping to target 100% crash free sessions instead of the 99,99% so every little crash count :)

I can suppose it's tied to me using TearDown that is only visible for testing but never had any issues and the process seemed correct.

Maybe there's another way to have Glide fully reinit itself (typical usecase: clear cache and move cache to external on user action)

**Comment by Tolriq** [comment]
One more unstale :)

**Comment by sjudd** [comment]
Sorry I missed this. 

If you're using tearDown outside of tests I can't really guarantee much. tearDown is pretty aggressive about trying to stop threads to try to make sure that emulator tests are consistent. 

If you have suggestions for how to improve the tearDown methods themselves, I'm ok with it. I don't want to build support for re-creating Glide outside of visiblefortesting methods.

**Comment by Tolriq** [comment]
@sjudd 
Threading in Glide is a little complex so not sure about tearDown improvements with my current knowledge :(

I did went that road as could not find a way to properly update the Glide configuration with new cache directory and new init of my loaders.

Not sure it's possible to address that need without a global restart of Glide like the tearDown.

I use that configuration for a very long time and this is the only drawback that I can see. My simple naive solution would be to add a !isTerminated in that part of the code to prevent the crash. 
Or having a global state isTearDowned and testing that but it's pretty much the same.
After all changing cache folder is a relatively rare operation and usually one time.

If you have better ideas and can give enough data for a start I can propose other things in PR but will need help :)

**Comment by Tolriq** [comment]
Well also need to reinit my loaders and all that needs to be done correctly to avoid any race conditions with things going at one place and other reading at other. And in proper threading to avoid doing access on main thread.

Not sure that it's that simple but will try to find time to look into that way if it's possible.

Unrelated but where there something missing in https://github.com/bumptech/glide/pull/2701 to finish that?

**Comment by Tolriq** [comment]
@sjudd So it's relatively complicated actually to be sure that there's nothing running or potentially queued with previous configuration. Specially with my custom loader that adds a second cache level to everything.

Without control of the threads I can't ensure integrity, but you require GlideExecutors and that class is final so I can't add things to it to fit additional needs.

Except having the !isTerminated check, I don't see any simple solution. Adding a new API to restart Glide is clearly out of my competences :(

I suppose this is more a race condition in the tearDown that keeps things running after the executors shutdown but it's again a little too complex for my current Glide understanding to fix.

So I'll need your help about how Glide can be enhanced to allow a full restart without restart the application.

**Comment by Tolriq** [comment]
Can this be changed to feature request or bug to avoid stale ? :)

**Comment by MagneticLlama** [comment]
This is still a huge problem.

**Comment by ice45571** [comment]
This is still a huge problem too!

**Comment by sadeqem** [comment]
i have thise bug and problam too !

**Comment by sadeqem** [comment]
i find a good answer : 
put your line code in try - catch .

**Comment by Aorlinn** [comment]
I have the same issue, and am able to reproduce:
The first activity (after app start) loads an image in the onResume method. I immediately start another activity on top of the task stack (because there are missing configuration values, so I handle to the ConfigurationActivity). When the configuration is done, the ConfigurationActivity is closed and so the first activity is on top of the task stack. The onResume loads the image again, while the first call was not yet finished (because it might have changed in the ConfigurationActivity). And voilá, a RejectedExecutionException is thrown.

```
java.lang.RuntimeException: Unable to resume activity {ch.yourwaiter.customertablet/ch.yourwaiter.customertablet.view.WelcomeActivity}: java.util.concurrent.RejectedExecutionException: Task com.bumptech.glide.load.engine.DecodeJob@1502395 rejected from java.util.concurrent.ThreadPoolExecutor@434bcaa[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4444)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.util.concurrent.RejectedExecutionException: Task com.bumptech.glide.load.engine.DecodeJob@1502395 rejected from java.util.concurrent.ThreadPoolExecutor@434bcaa[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
        at com.bumptech.glide.load.engine.executor.GlideExecutor.execute(GlideExecutor.java:220)
        at com.bumptech.glide.load.engine.EngineJob.start(EngineJob.java:132)
        at com.bumptech.glide.load.engine.Engine.waitForExistingOrStartNewJob(Engine.java:287)
        at com.bumptech.glide.load.engine.Engine.load(Engine.java:193)
        at com.bumptech.glide.request.SingleRequest.onSizeReady(SingleRequest.java:451)
        at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.getSize(ViewTarget.java:376)
        at com.bumptech.glide.request.target.ViewTarget.getSize(ViewTarget.java:218)
        at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:253)
        at com.bumptech.glide.manager.RequestTracker.runRequest(RequestTracker.java:43)
        at com.bumptech.glide.RequestManager.track(RequestManager.java:671)
        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:740)
        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:799)
        at ch.yourwaiter.customertablet.view.WelcomeActivity.loadWelcomeImage(WelcomeActivity.java:97)
        at ch.yourwaiter.customertablet.view.WelcomeActivity.onResume(WelcomeActivity.java:65)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
        at android.app.Activity.performResume(Activity.java:8135)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4434)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```
