### ISSUE TITLE
Cannot obtain size for recycled Bitmap in onDestroy

### ISSUE THREAD

**Issue by mars3142** [bumptech/glide#3237]
**Glide Version**: 4.7.1

**Device/Android Version**: Galaxy S6 (Android 7); Galaxy A3 (Android 7); Galaxy S7 (Android 8); Moto E (Android 7.1.1)

**Issue details / Repro steps / Use case background**:  it's not 100% happening, but we see it within our crashlytics logs

**Stack trace / LogCat**:
```ruby
Caused by java.lang.IllegalStateException: Cannot obtain size for recycled Bitmap: android.graphics.Bitmap@bf5619f[656x224] ARGB_8888
       at com.bumptech.glide.util.Util.getBitmapByteSize(Util.java:78)
       at com.bumptech.glide.load.resource.bitmap.BitmapResource.getSize(BitmapResource.java:55)
       at com.bumptech.glide.load.engine.EngineResource.getSize(EngineResource.java:60)
       at com.bumptech.glide.load.engine.cache.LruResourceCache.getSize(LruResourceCache.java:42)
       at com.bumptech.glide.load.engine.cache.LruResourceCache.getSize(LruResourceCache.java:13)
       at com.bumptech.glide.util.LruCache.put(LruCache.java:124)
       at com.bumptech.glide.load.engine.cache.LruResourceCache.put(LruResourceCache.java:13)
       at com.bumptech.glide.load.engine.Engine.onResourceReleased(Engine.java:327)
       at com.bumptech.glide.load.engine.EngineResource.release(EngineResource.java:112)
       at com.bumptech.glide.load.engine.Engine.release(Engine.java:287)
       at com.bumptech.glide.request.SingleRequest.releaseResource(SingleRequest.java:345)
       at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:324)
       at com.bumptech.glide.manager.RequestTracker.clearRemoveAndMaybeRecycle(RequestTracker.java:78)
       at com.bumptech.glide.manager.RequestTracker.clearRemoveAndRecycle(RequestTracker.java:65)
       at com.bumptech.glide.RequestManager.untrack(RequestManager.java:603)
       at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:571)
       at com.bumptech.glide.RequestManager.clear(RequestManager.java:559)
       at com.bumptech.glide.RequestManager.onDestroy(RequestManager.java:303)
       at com.bumptech.glide.manager.ActivityFragmentLifecycle.onDestroy(ActivityFragmentLifecycle.java:65)
       at com.bumptech.glide.manager.SupportRequestManagerFragment.onDestroy(SupportRequestManagerFragment.java:194)
       at android.support.v4.app.Fragment.performDestroy(Fragment.java:2588)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1566)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
       at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3235)
       at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:265)
       at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:390)
       at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)
       at com.examples.activities.MainActivity.onDestroy(MainOteloActivity.java:190)
       at android.app.Activity.performDestroy(Activity.java:7195)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1161)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4573)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4609)
       at android.app.ActivityThread.-wrap7(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/doc/resourcereuse.html#common-errors

**Comment by yanchengdeng** [comment]
the same issue

**Comment by yanchengdeng** [comment]
if (bitmap?.isRecycled!!){
                            return
                        }
可以解决这个问题

**Comment by juyao** [comment]
> if (bitmap?.isRecycled!!){
> return
> }
> 可以解决这个问题

是将源码copy下来改源码吗?

**Comment by juyao** [comment]
@yanchengdeng 
是将源码copy下来改源码吗?
