### ISSUE TITLE
Registry$NoModelLoaderAvailableException

### ISSUE THREAD

**Issue by androidjanuary** [bumptech/glide#3250]
com.bumptech.glide.Registry$NoModelLoaderAvailableException: Failed to find any ModelLoaders for model: com.jiulong.yizhitong.entity.medicalMeeting.MeetingDetails$AreaImages@f0c1ae6
        at com.bumptech.glide.Registry.getModelLoaders(Registry.java:584)
        at com.bumptech.glide.load.engine.DecodeHelper.getLoadData(DecodeHelper.java:205)
        at com.bumptech.glide.load.engine.DecodeHelper.getCacheKeys(DecodeHelper.java:223)
        at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:44)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)

集成的最新版本   加载图片报这个错

**Comment by sjudd** [comment]
You need to either pass in a model that Glide supports (url, file path, uri etc) or [write a ModelLoader][1] for `MeetingDetails$AreaImages`.

[1]: http://bumptech.github.io/glide/tut/custom-modelloader.html
