### ISSUE TITLE
Crash when using Android R8 Code Shrinker

### ISSUE THREAD

**Issue by phileo** [bumptech/glide#3255]
using v4.6.1

when I use Proguard and turn off the R8 code shrinker, everything works fine.
However, when I turn on the R8 code shrinker in gradle.properties,
`GlideApp.with()` crashes with the following stacktrace:

`java.lang.NoSuchMethodException: values []`

        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getDeclaredMethod(Class.java:2047)
        at java.lang.Enum$1.create(Enum.java:268)
        at java.lang.Enum$1.create(Enum.java:263) 
        at libcore.util.BasicLruCache.get(BasicLruCache.java:58) 
        at java.lang.Enum.getSharedConstants(Enum.java:289) 
        at java.lang.Class.getEnumConstantsShared(Class.java:2414) 
        at java.lang.JavaLangAccess.getEnumConstantsShared(JavaLangAccess.java:40) 
        at java.util.EnumSet.getUniverse(EnumSet.java:407) 
        at java.util.EnumSet.noneOf(EnumSet.java:109) 
        at java.util.EnumSet.of(EnumSet.java:258) 
        at c.b.a.c.d.a.l.<clinit>(Downsampler.java:116) 
        at com.bumptech.glide.Glide.<init>(Glide.java:328) 
        at com.bumptech.glide.GlideBuilder.a(GlideBuilder.java:472) 
        at com.bumptech.glide.Glide.a(Glide.java:264) 
        at com.bumptech.glide.Glide.c(Glide.java:219) 
        at com.bumptech.glide.Glide.b(Glide.java:180) 
        at com.bumptech.glide.Glide.a(Glide.java:164) 
        at com.bumptech.glide.Glide.d(Glide.java:670) 
        at com.bumptech.glide.Glide.a(Glide.java:722) 
        at c.p.c.a.h.c.a(GlideApp.java:104)

**Comment by phileo** [comment]
The crash does not occur when I use Proguard and turn of R8 shrinker.
Are there any plans to support the R8 code shrinker?

**Comment by sjudd** [comment]
If it's only reproducible with R8, it's probably a bug in R8. Please report the issue to them so they can make sure it's fixed: https://developer.android.com/studio/report-bugs
