### ISSUE TITLE
Classcast exception glide 

### ISSUE THREAD

**Issue by pyushmahore** [bumptech/glide#3261]
Glide:4.7.1

**Integration libraries**:

SM-G960U1
SM-G955U1
SM-N950U1
Galaxy Tab A 10.1
Pixel XL
Pixel 2 XL
Mostly coming in operating system 8(80%) and few times came in Operating system 7

No steps to reproducible observed daily few times in crashlytics system

GlideApp.with(context)
                .load(model)
                .dontTransform()
                .disallowHardwareConfig()
                .placeholder(placeHolder)
                .transition(withCrossFade(crossFadeDuration))
                .skipMemoryCache(isCachingEnabled)
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .into(imageView)
        ;

GlideApp.with(context)
                .load(model)
                .dontTransform()
                .disallowHardwareConfig()
                .placeholder(placeHolder)
                .transition(withCrossFade(crossFadeDuration))
                .skipMemoryCache(isCachingEnabled)
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .into(imageView)
        ;

GlideApp.with(context)
                .load(resource)
                .dontTransform()
                .disallowHardwareConfig()
                .skipMemoryCache(true)
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .into(imageView);
RequestOptions myOptions = new RequestOptions()
                .fitCenter()
                .disallowHardwareConfig()
                .skipMemoryCache(isCachingEnabled)
                .override(width, height)
                .diskCacheStrategy(DiskCacheStrategy.ALL);
        Bitmap bitmap = null;
        try {
            bitmap = GlideApp
                    .with(context)
                    .applyDefaultRequestOptions(myOptions)
                    .asBitmap()
                    .load(imageUrl)
                    .submit()
                    .get();
        } catch (final Exception e) {
            log.e(TAG, "Exception " + e);
        }

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

Fatal Exception: java.lang.ClassCastException: com.bumptech.glide.load.Option cannot be cast to java.lang.Object[]
       at android.support.v4.util.SimpleArrayMap.allocArrays(SimpleArrayMap.java:183)
       at android.support.v4.util.SimpleArrayMap.put(SimpleArrayMap.java:437)
       at android.support.v4.widget.DirectedAcyclicGraph.addNode(DirectedAcyclicGraph.java:55)
       at android.support.design.widget.CoordinatorLayout.prepareChildren(CoordinatorLayout.java:677)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:745)
       at android.view.View.measure(View.java:23169)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:23169)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
       at android.view.View.measure(View.java:23169)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:23169)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:23169)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
       at android.view.View.measure(View.java:23169)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:716)
       at android.view.View.measure(View.java:23169)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2719)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1572)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1856)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7184)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:696)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by sjudd** [comment]
This looks like a support library issue. Something in CoordinatorLayout or SimpleArrayMap is trying to cast a Glide class incorrectly. Consider opening an issue for Android or StackOverflow.

**Comment by pyushmahore** [comment]
As per logs its coming in Glide:

Fatal Exception: java.lang.ClassCastException: com.bumptech.glide.load.d cannot be cast to java.lang.Object[]

Also this started coming in latest version of glide, this issue was not present in older glide version.

**Comment by sjudd** [comment]
The object the support library is trying to cast happens to be in Glide, but the stack trace clearly originates elsewhere:

```
at android.support.v4.util.SimpleArrayMap.allocArrays(SimpleArrayMap.java:183)
at android.support.v4.util.SimpleArrayMap.put(SimpleArrayMap.java:437)
at android.support.design.widget.DirectedAcyclicGraph.addNode(DirectedAcyclicGraph.java:47)
at android.support.design.widget.CoordinatorLayout.prepareChildren(CoordinatorLayout.java:657)
at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:725)
```

Consider filing an issue for the support library team.

**Comment by pyushmahore** [comment]
Even after updating the support library this issue is still coming.
Strange thing is its not coming in older glide version:

Fatal Exception: java.lang.ClassCastException: com.bumptech.glide.load.Option cannot be cast to java.lang.Object[]
       at android.support.v4.util.SimpleArrayMap.allocArrays(SimpleArrayMap.java:183)
       at android.support.v4.util.SimpleArrayMap.put(SimpleArrayMap.java:437)
       at android.support.v4.widget.DirectedAcyclicGraph.addNode(DirectedAcyclicGraph.java:55)
       at android.support.design.widget.CoordinatorLayout.prepareChildren(CoordinatorLayout.java:677)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:745)
       at android.view.View.measure(View.java:23169)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:23169)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
       at android.view.View.measure(View.java:23169)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:23169)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:23169)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
       at android.view.View.measure(View.java:23169)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:716)
       at android.view.View.measure(View.java:23169)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2719)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1572)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1856)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7184)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:696)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by pyushmahore** [comment]
@sjudd here are more logs.
I see something related to disallowHardwareConfig.
Its coming mostly in Android P.

java.lang.ClassCastException: com.bumptech.glide.load.Option cannot be cast to java.lang.Object[]
        at android.support.v4.util.SimpleArrayMap.allocArrays(SimpleArrayMap.java:183)
        at android.support.v4.util.SimpleArrayMap.put(SimpleArrayMap.java:437)
        at com.bumptech.glide.util.CachedHashCodeArrayMap.put(CachedHashCodeArrayMap.java:34)
        at com.bumptech.glide.load.Options.set(Options.java:22)
        at com.bumptech.glide.request.RequestOptions.set(RequestOptions.java:874)
        at com.verizon.fios.tv.sdk.imagedownloader.GlideOptions.set(GlideOptions.java:433)
        at com.verizon.fios.tv.sdk.imagedownloader.GlideOptions.set(GlideOptions.java:31)
        at com.bumptech.glide.request.RequestOptions.disallowHardwareConfig(RequestOptions.java:988)
        at com.verizon.fios.tv.sdk.imagedownloader.GlideOptions.disallowHardwareConfig(GlideOptions.java:475)
        at com.verizon.fios.tv.sdk.imagedownloader.GlideRequest.disallowHardwareConfig(GlideRequest.java:401)

**Comment by pyushmahore** [comment]
@sjudd any update on this?

**Comment by pyushmahore** [comment]
@sjudd This issue is still coming in latest Glide version as well.

**Comment by Logan676** [comment]
Using Glide 4.9.0, I have the same issue, with android 
8.1.0, 9, 10. 

devices show as below: 

VKY-AL00   9.1.0.228(C00E80R1P12)
M1AJQ.C7100ZCU1BSA3
COL-TL10   10.0.0.156(C01E156R1P4)
HLK-AL00   10.1.0.110(C00E105R8P2)



crash log is 
```
java.lang.ClassCastException: com.bumptech.glide.load.Option cannot be cast to java.lang.Object[]
 android.support.v4.util.SimpleArrayMap.allocArrays(SourceFile:15)
 android.support.v4.util.SimpleArrayMap.put(SourceFile:10)
 com.bumptech.glide.util.CachedHashCodeArrayMap.put(SourceFile:2)
 com.bumptech.glide.request.BaseRequestOptions.transform(SourceFile:23)
 com.bumptech.glide.request.BaseRequestOptions.transform(SourceFile:14)
 com.bumptech.glide.request.BaseRequestOptions.transform(SourceFile:5)
 m8.c.c0(SourceFile:1)
 m8.c.transform(SourceFile:1)
 com.bumptech.glide.request.BaseRequestOptions.transform(SourceFile:4)
 com.bumptech.glide.request.BaseRequestOptions.centerCrop(SourceFile:1)
 m8.c.c(SourceFile:1)
 m8.c.centerCrop(SourceFile:1)
```

Before, using Glide 3.5.2, didn\`t have the issue.
