### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'int com.bumptech.glide.gifdecoder.GifHeader.frameCount' on a null object reference

### ISSUE THREAD

**Issue by vicktorial** [bumptech/glide#3265]
TinkerUncaughtHandler catch exception:java.lang.NullPointerException: Attempt to read from field 'int com.bumptech.glide.gifdecoder.GifHeader.frameCount' on a null object reference
                                                                                 at com.bumptech.glide.gifdecoder.StandardGifDecoder.getFrameCount(StandardGifDecoder.java:188)
                                                                                 at com.bumptech.glide.load.resource.gif.GifFrameLoader.getFrameCount(GifFrameLoader.java:157)
                                                                                 at com.bumptech.glide.load.resource.gif.GifDrawable.startRunning(GifDrawable.java:231)
                                                                                 at com.bumptech.glide.load.resource.gif.GifDrawable.setVisible(GifDrawable.java:254)
                                                                                 at android.widget.ImageView.onAttachedToWindow(ImageView.java:1628)
                                                                                 at android.view.View.dispatchAttachedToWindow(View.java:17589)
                                                                                 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3337)
                                                                                 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3337)
                                                                                 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3337)
                                                                                 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3337)
                                                                                 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3337)
                                                                                 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3337)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1817)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1541)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7327)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:778)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:713)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
                                                                                 at android.os.Handler.handleCallback(Handler.java:790)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                 at android.os.Looper.loop(Looper.java:164)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6753)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by nicai1900** [comment]
I have the same problem,  please fix it

**Comment by dy1023348109** [comment]
got this issue too, anyone know how to avoid it ?

**Comment by OPHsysbilla** [comment]
same issue here

**Comment by laipi007** [comment]
same issue here
version：4.8.0

**Comment by lvjiancong** [comment]
same issue here
version：4.12.0

**Comment by victory316** [comment]
Same issue here on version 4.12.0

**Comment by joy2helloworld** [comment]
same  issue
