### ISSUE TITLE
java.lang.NullPointerException at com.bumptech.glide.manager.RequestManagerFragment

### ISSUE THREAD

**Issue by falhassen** [bumptech/glide#329]
I was trying to switch out of my app and I encountered this NPE:

java.lang.NullPointerException
            at com.bumptech.glide.manager.RequestManagerFragment.onTrimMemory(RequestManagerFragment.java:74)
            at android.app.Fragment.performTrimMemory(Fragment.java:1769)
            at android.app.FragmentManagerImpl.dispatchTrimMemory(FragmentManager.java:1914)
            at android.app.Activity.onTrimMemory(Activity.java:1693)
            at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:4043)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1388)

**Comment by sjudd** [comment]
Let's leave this open until we import the fix.

**Comment by alsajoo** [comment]
Is there a workaround for this at the moment? Maybe go back to a previous version till 4.0 comes out?

**Comment by sjudd** [comment]
Sorry for the delay, there isn't a workaround that I know of. I'll try and do a dot release in the next week or two once I'm more confident we've fixed this.

**Comment by alsajoo** [comment]
Tried 3.6-SNAPSHOT and bug is still present. See stack trace below.

java.lang.NullPointerException
       at ade.onTrimMemory(RequestManagerFragment.java:74)
       at android.app.Fragment.performTrimMemory(Fragment.java:1769)
       at android.app.FragmentManagerImpl.dispatchTrimMemory(FragmentManager.java:1920)
       at android.app.Activity.onTrimMemory(Activity.java:1795)
       at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:4298)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1481)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5487)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by sjudd** [comment]
That line number is out of date, it looks like you're using an old snapshot that doesn't contain the fix: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/manager/RequestManagerFragment.java#L74. You may need to try forcing whatever build system you're using to refresh the dependencies for your project.

**Comment by erichkleung** [comment]
Hi, do you know when you will be doing the 3.5.2 release?

**Comment by sjudd** [comment]
@erichkleung You can see target dates in [milestones][1]. Goal is this Friday the 20th unless more bugs come up.

[1]: https://github.com/bumptech/glide/milestones
