### ISSUE TITLE
int[] cannot be cast to java.lang.Object[] in setResourceDecoderBucketPriorityList

### ISSUE THREAD

**Issue by zmemo** [bumptech/glide#3296]
**Glide Version**:  4.7.1

**Integration libraries**: com.squareup.okhttp3:okhttp:3.11.0

**Device/Android Version**:  MeiZu M1     flymeos 4.2.1 (android4.4  API19)

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GlideApp.with(context).load(path).into(imageView);
```

**Layout XML**:

**Stack trace / LogCat**:
```
java.lang.ClassCastException: int[] cannot be cast to java.lang.Object[]
        at java.util.Arrays$ArrayList.toArray(Arrays.java:120)
        at java.util.ArrayList.<init>(ArrayList.java:97)
        at com.bumptech.glide.Registry.setResourceDecoderBucketPriorityList(Registry.java:268)
        at com.bumptech.glide.Registry.<init>(Registry.java:67)
        at com.bumptech.glide.Glide.<init>(Glide.java:333)
        at com.bumptech.glide.GlideBuilder.build(GlideBuilder.java:452)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:264)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:219)
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:180)
        at com.bumptech.glide.Glide.get(Glide.java:164)
        at com.bumptech.glide.Glide.getRetriever(Glide.java:671)
        at com.bumptech.glide.Glide.with(Glide.java:698)
        at com.***.Glide.GlideApp.with(GlideApp.java:88)
        at com.***.GlideImageLoader.loadCircleImage(GlideImageLoader.java:58)
        at com.***.MineFragment.initView(MineFragment.java:116)
        at com.***.MineFragment.initialize(MineFragment.java:102)
        at com.***.Fragment.BaseFragment.onCreateView(BaseFragment.java:79)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
        at android.view.View.measure(View.java:17481)
        at android.support.constraint.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:1212)
        at android.support.constraint.ConstraintLayout.onMeasure(ConstraintLayout.java:1552)
        at android.view.View.measure(View.java:17481)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5437)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:332)
        at android.view.View.measure(View.java:17481)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:818)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:495)
        at android.view.View.measure(View.java:17481)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5437)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:332)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
        at android.view.View.measure(View.java:17481)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5437)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1616)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:729)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:601)
        at android.view.View.measure(View.java:17481)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5437)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:332)
        at android.view.View.measure(View.java:17481)
```

**Comment by sjudd** [comment]
There's a note in the Android API 27 code for ArrayList that indicates that calling toArray() might erroneously return an array of an incorrect type:

```java
   public ArrayList(Collection<? extends E> c) {
        elementData = c.toArray();
        if ((size = elementData.length) != 0) {
            // c.toArray might (incorrectly) not return Object[] (see 6260652)
            if (elementData.getClass() != Object[].class)
                elementData = Arrays.copyOf(elementData, size, Object[].class);
        } else {
            // replace with empty array.
            this.elementData = EMPTY_ELEMENTDATA;
        }
    }
```

**Comment by hzyxym** [comment]
And how to solve this bug?@sjudd

**Comment by wilsonssss** [comment]
MeiZu M1  crash too...

**Comment by EHG613** [comment]
MeiZu M1 crash too... +1

**Comment by sjudd** [comment]
See the associated commit.

If you're able to reproduce this on 4.9.0+ let me know.

**Comment by EHG613** [comment]
`   api 'com.github.bumptech.glide:glide:4.9.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'`
`java.lang.ClassCastException: int[] cannot be cast to java.lang.Object[]
        at java.util.Arrays$ArrayList.toArray(Arrays.java:120)
        at java.util.ArrayList.addAll(ArrayList.java:188)
        at com.bumptech.glide.Registry.setResourceDecoderBucketPriorityList(Registry.java:270)
        at com.bumptech.glide.Registry.<init>(Registry.java:67)
        at com.bumptech.glide.Glide.<init>(Glide.java:339)
        at com.bumptech.glide.GlideBuilder.build(GlideBuilder.java:509)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:268)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:223)
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:184)
        at com.bumptech.glide.Glide.get(Glide.java:168)
        at com.bumptech.glide.Glide.getRetriever(Glide.java:689)
        at com.bumptech.glide.Glide.with(Glide.java:716)`
@sjudd

**Comment by EHG613** [comment]
`
setResourceDecoderBucketPriorityList(
        Arrays.asList(BUCKET_GIF, BUCKET_BITMAP, BUCKET_BITMAP_DRAWABLE));
`

`
public synchronized void setBucketPriorityList(@NonNull List<String> buckets) {
    List<String> previousBuckets = new ArrayList<>(bucketPriorityList);
    bucketPriorityList.clear();
    bucketPriorityList.addAll(buckets);
    for (String previousBucket : previousBuckets) {
      if (!buckets.contains(previousBucket)) {
        // Keep any buckets from the previous list that aren't included here, but but them at the
        // end.
        bucketPriorityList.add(previousBucket);
      }
    }
  }
`

`
  @NonNull
  public final Registry setResourceDecoderBucketPriorityList(@NonNull List<String> buckets) {
    // See #3296 and https://bugs.openjdk.java.net/browse/JDK-6260652.
    List<String> modifiedBuckets = new ArrayList<>(buckets.size());
    modifiedBuckets.addAll(buckets);
    modifiedBuckets.add(0, BUCKET_PREPEND_ALL);
    modifiedBuckets.add(BUCKET_APPEND_ALL);
    decoderRegistry.setBucketPriorityList(modifiedBuckets);
    return this;
  }
`

new ArrayList<>() maybe the crash reason @sjudd

**Comment by Logan676** [comment]
> See the associated commit.
> 
> If you're able to reproduce this on 4.9.0+ let me know.

Using Glide 4.9.0, I have the same issue, with android 
8.1.0, 9, 10. 

devices show as below: 

VKY-AL00   9.1.0.228(C00E80R1P12)
M1AJQ.C7100ZCU1BSA3
COL-TL10   10.0.0.156(C01E156R1P4)
HLK-AL00   10.1.0.110(C00E105R8P2)



crash log is 
```
java.lang.ClassCastException: com.bumptech.glide.load.Option cannot be cast to java.lang.Object[]
 android.support.v4.util.SimpleArrayMap.allocArrays(SourceFile:15)
 android.support.v4.util.SimpleArrayMap.put(SourceFile:10)
 com.bumptech.glide.util.CachedHashCodeArrayMap.put(SourceFile:2)
 com.bumptech.glide.request.BaseRequestOptions.transform(SourceFile:23)
 com.bumptech.glide.request.BaseRequestOptions.transform(SourceFile:14)
 com.bumptech.glide.request.BaseRequestOptions.transform(SourceFile:5)
 m8.c.c0(SourceFile:1)
 m8.c.transform(SourceFile:1)
 com.bumptech.glide.request.BaseRequestOptions.transform(SourceFile:4)
 com.bumptech.glide.request.BaseRequestOptions.centerCrop(SourceFile:1)
 m8.c.c(SourceFile:1)
 m8.c.centerCrop(SourceFile:1)
```

Before, using Glide 3.5.2, didn\`t have the issue.

**Comment by mohitrajput987** [comment]
We are also using
Glide 4.9.0

facing following issue in multiple devices and multiple OS:

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{app.trell/app.geochat.revamp.activity.HomeGenericActivity}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Object[]
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2517)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
       at android.app.ActivityThread.access$1000(ActivityThread.java:166)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5628)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
​
​
       Caused by java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Object[]
       at android.util.ArrayMap.allocArrays(ArrayMap.java:173)
       at android.util.ArrayMap.put(ArrayMap.java:459)
       at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:736)
       at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1174)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1154)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1148)
       at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:554)
       at com.bumptech.glide.manager.DefaultConnectivityMonitor.register(DefaultConnectivityMonitor.java:55)
       at com.bumptech.glide.manager.DefaultConnectivityMonitor.onStart(DefaultConnectivityMonitor.java:101)
       at com.bumptech.glide.manager.ApplicationLifecycle.addListener(ApplicationLifecycle.java:15)
       at com.bumptech.glide.RequestManager.<init>(RequestManager.java:132)
       at com.bumptech.glide.RequestManager.<init>(RequestManager.java:94)
       at app.trell.network.GlideRequests.<init>(GlideRequests.java:39)
       at com.bumptech.glide.GeneratedRequestManagerFactory.build(GeneratedRequestManagerFactory.java:19)
       at com.bumptech.glide.manager.RequestManagerRetriever.getApplicationManager(RequestManagerRetriever.java:98)
       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:124)
       at com.bumptech.glide.Glide.with(Glide.java:716)
       at app.geochat.revamp.utils.Utils.setProfileImage(Utils.java:366)
       at app.geochat.revamp.activity.HomeGenericActivity.updateNavDrawerInfo(HomeGenericActivity.java:4518)
       at app.geochat.revamp.activity.HomeGenericActivity.setupUserMenuDrawer(HomeGenericActivity.java:4352)
       at app.geochat.revamp.activity.HomeGenericActivity.initData(HomeGenericActivity.java:967)
       at app.geochat.revamp.base.BaseActivity.onCreate(BaseActivity.java:104)
       at app.geochat.revamp.activity.Hilt_HomeGenericActivity.onCreate(Hilt_HomeGenericActivity.java:29)
       at app.geochat.revamp.activity.HomeGenericActivity.onCreate(HomeGenericActivity.java:683)
       at android.app.Activity.performCreate(Activity.java:6351)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2470)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
       at android.app.ActivityThread.access$1000(ActivityThread.java:166)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5628)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
```
