### ISSUE TITLE
ava.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by Saqrag** [bumptech/glide#3298]
Glide Version: 4.7.1

Device/Android Version: all device

Issue details / Repro steps / Use case background: sometimes, all pictures don't preview when the app starts.  And restart app can resolve

Glide.with(activity)
                .load(url)
                .into(imageview);

Stack trace / LogCat:

```
09-05 11:30:45.060 15175-15515/com.zuga.im E/GlideExecutor: Request threw uncaught throwable
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at java.util.Collections$UnmodifiableList.get(Collections.java:1351)
        at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:71)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
```

**Comment by Saqrag** [comment]
It is possible that the method I used is wrong. But reproduce very frequently.

**Comment by sjudd** [comment]
If you're able to reproduce this, please consider attaching a sample app.
