### ISSUE TITLE
Canvas: trying to use a recycled bitmap android.graphics.Bitmap@22558fc

### ISSUE THREAD

**Issue by mushtaq99** [bumptech/glide#3299]
Fatal Exception: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@22558fc
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1225)
       at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:600)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:537)
       at android.widget.ImageView.onDraw(ImageView.java:1148)
       at android.view.View.draw(View.java:15380)
       at android.view.View.updateDisplayListIfDirty(View.java:14270)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.View.draw(View.java:15085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
       at android.view.View.updateDisplayListIfDirty(View.java:14262)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.View.draw(View.java:15085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
       at android.view.View.draw(View.java:15392)
       at android.view.View.updateDisplayListIfDirty(View.java:14270)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.View.draw(View.java:15085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
       at android.view.View.updateDisplayListIfDirty(View.java:14262)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.View.draw(View.java:15085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
       at android.view.View.updateDisplayListIfDirty(View.java:14262)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.View.draw(View.java:15085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
       at android.view.View.draw(View.java:15392)
       at android.view.View.updateDisplayListIfDirty(View.java:14270)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.View.draw(View.java:15085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
       at android.view.View.updateDisplayListIfDirty(View.java:14262)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.View.draw(View.java:15085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
       at android.view.View.updateDisplayListIfDirty(View.java:14262)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.View.draw(View.java:15085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
       at android.view.View.updateDisplayListIfDirty(View.java:14262)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.View.draw(View.java:15085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
       at android.view.View.updateDisplayListIfDirty(View.java:14262)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.View.draw(View.java:15085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2700)
       at android.view.View.draw(View.java:15392)
       at android.widget.FrameLayout.draw(FrameLayout.java:652)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2679)
       at android.view.View.updateDisplayListIfDirty(View.java:14270)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:272)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:278)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:313)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2909)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2743)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2358)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1290)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6520)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:821)
       at android.view.Choreographer.doCallbacks(Choreographer.java:624)
       at android.view.Choreographer.doFrame(Choreographer.java:593)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:807)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5562)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:968)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:763)

#0. Crashed: main
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1225)
       at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:600)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:537)
       at android.widget.ImageView.onDraw(ImageView.java:1148)
       at android.view.View.draw(View.java:15380)
       at android.view.View.updateDisplayListIfDirty(View.java:14270)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.View.draw(View.java:15085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
       at android.view.View.updateDisplayListIfDirty(View.java:14262)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.View.draw(View.java:15085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
       at android.view.View.draw(View.java:15392)
       at android.view.View.updateDisplayListIfDirty(View.java:14270)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.View.draw(View.java:15085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
       at android.view.View.updateDisplayListIfDirty(View.java:14262)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.View.draw(View.java:15085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
       at android.view.View.updateDisplayListIfDirty(View.java:14262)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.View.draw(View.java:15085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
       at android.view.View.draw(View.java:15392)
       at android.view.View.updateDisplayListIfDirty(View.java:14270)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.View.draw(View.java:15085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
       at android.view.View.updateDisplayListIfDirty(View.java:14262)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.View.draw(View.java:15085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
       at android.view.View.updateDisplayListIfDirty(View.java:14262)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.View.draw(View.java:15085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
       at android.view.View.updateDisplayListIfDirty(View.java:14262)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.View.draw(View.java:15085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
       at android.view.View.updateDisplayListIfDirty(View.java:14262)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.View.draw(View.java:15085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3535)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2700)
       at android.view.View.draw(View.java:15392)
       at android.widget.FrameLayout.draw(FrameLayout.java:652)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2679)
       at android.view.View.updateDisplayListIfDirty(View.java:14270)
       at android.view.View.getDisplayList(View.java:14300)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:272)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:278)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:313)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2909)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2743)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2358)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1290)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6520)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:821)
       at android.view.Choreographer.doCallbacks(Choreographer.java:624)
       at android.view.Choreographer.doFrame(Choreographer.java:593)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:807)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5562)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:968)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:763)

 I Got this Issue through Crashlytics searching a lot but did not find any satisfactory solution.

**Comment by luffykou** [comment]
我用的glide-3.6.1.jar，是有这样的问题，估计代码中大量调用了Bitmap.recycle()方法：

// CRASH: com.android.gallery (pid 6661)
// Short Msg: java.lang.RuntimeException
// Long Msg: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.**Bitmap@6847648**
// Build Label: Lenovo/LenovoPB-6505NC/PB-6505NC:9/PKQ1/PB-6505NC_S000001_180904_PRC:userd/release-keys
// Build Changelist: PB-6505NC_S000001_180904_PRC
// Build Time: 1548924487000
// java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@6847648
// 	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:62)
// 	at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:226)
// 	at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:98)
// 	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
// 	at android.widget.ImageView.onDraw(ImageView.java:1360)

01-17 02:02:15.113  6661  6661 D BitmapTAG: Object tried to call recycle,this=android.graphics.**Bitmap@6847648**
01-17 02:02:15.114  6661  6661 W System.err: java.lang.Exception: Stack trace
01-17 02:02:15.115  6661  6661 W System.err: 	at java.lang.Thread.dumpStack(Thread.java:1348)
01-17 02:02:15.115  6661  6661 W System.err: 	at android.graphics.Bitmap.recycle(Bitmap.java:354)
01-17 02:02:15.115  6661  6661 W System.err: 	at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.trimToSize(LruBitmapPool.java:188)
01-17 02:02:15.116  6661  6661 W System.err: 	at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.evict(LruBitmapPool.java:109)
01-17 02:02:15.116  6661  6661 W System.err: 	at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.put(LruBitmapPool.java:104)
01-17 02:02:15.116  6661  6661 W System.err: 	at com.bumptech.glide.load.resource.bitmap.BitmapResource.recycle(BitmapResource.java:54)
01-17 02:02:15.117  6661  6661 W System.err: 	at com.bumptech.glide.load.engine.EngineResource.recycle(EngineResource.java:61)
01-17 02:02:15.117  6661  6661 W System.err: 	at com.bumptech.glide.load.engine.ResourceRecycler.recycle(ResourceRecycler.java:25)
01-17 02:02:15.118  6661  6661 W System.err: 	at com.bumptech.glide.load.engine.Engine.onResourceRemoved(Engine.java:283)
01-17 02:02:15.118  6661  6661 W System.err: 	at com.bumptech.glide.load.engine.cache.LruResourceCache.onItemEvicted(LruResourceCache.java:32)
01-17 02:02:15.118  6661  6661 W System.err: 	at com.bumptech.glide.load.engine.cache.LruResourceCache.onItemEvicted(LruResourceCache.java:12)
01-17 02:02:15.119  6661  6661 W System.err: 	at com.bumptech.glide.util.LruCache.trimToSize(LruCache.java:162)
01-17 02:02:15.119  6661  6661 W System.err: 	at com.bumptech.glide.util.LruCache.evict(LruCache.java:167)
01-17 02:02:15.119  6661  6661 W System.err: 	at com.bumptech.glide.util.LruCache.put(LruCache.java:124)
01-17 02:02:15.120  6661  6661 W System.err: 	at com.bumptech.glide.load.engine.cache.LruResourceCache.put(LruResourceCache.java:12)
01-17 02:02:15.120  6661  6661 W System.err: 	at com.bumptech.glide.load.engine.Engine.onResourceReleased(Engine.java:291)
01-17 02:02:15.121  6661  6661 W System.err: 	at com.bumptech.glide.load.engine.EngineResource.release(EngineResource.java:100)
01-17 02:02:15.121  6661  6661 W System.err: 	at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:162)
01-17 02:02:15.121  6661  6661 W System.err: 	at com.bumptech.glide.load.engine.EngineJob.access$100(EngineJob.java:22)
01-17 02:02:15.122  6661  6661 W System.err: 	at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:202)
01-17 02:02:15.122  6661  6661 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-17 02:02:15.123  6661  6661 W System.err: 	at android.os.Looper.loop(Looper.java:193)
01-17 02:02:15.123  6661  6661 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6870)
01-17 02:02:15.123  6661  6661 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
01-17 02:02:15.124  6661  6661 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-17 02:02:15.124  6661  6661 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
