### ISSUE TITLE
IllegalArgumentException: Unable to find GlideModule implementation when proguarded

### ISSUE THREAD

**Issue by ishaangarg** [bumptech/glide#3331]
**Glide Version**: 4.8.0

**Integration libraries**: glide:okhttp3-integration:4.8.0

**Device/Android Version**: fails on Note8/Note9/Emulator Nexus5 API21

**Issue details / Repro steps / Use case background**: Initial Glide load fails when proguarded

**Stack trace / LogCat**:
```ruby
java.lang.RuntimeException: Unable to start activity 
java.lang.IllegalArgumentException: Unable to find GlideModule implementation
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2974)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7002)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.IllegalArgumentException: Unable to find GlideModule implementation
        at com.bumptech.glide.module.ManifestParser.parseModule(ManifestParser.java:69)
        at com.bumptech.glide.module.ManifestParser.parse(ManifestParser.java:47)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:230)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:221)
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:182)
        at com.bumptech.glide.Glide.get(Glide.java:166)
        at com.bumptech.glide.Glide.getRetriever(Glide.java:680)
        at com.bumptech.glide.Glide.with(Glide.java:732)
        at in.lubble.app.GlideApp.with(GlideApp.java:104)
        at in.lubble.app.MainActivity.onCreate(MainActivity.java:129)
        at android.app.Activity.performCreate(Activity.java:7258)
        at android.app.Activity.performCreate(Activity.java:7249)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1221)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:7002) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408) 
     Caused by: java.lang.ClassNotFoundException: com.bumptech.glide.integration.okhttp3.OkHttpGlideModule
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at com.bumptech.glide.module.ManifestParser.parseModule(ManifestParser.java:67)
        at com.bumptech.glide.module.ManifestParser.parse(ManifestParser.java:47) 
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:230) 
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:221) 
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:182) 
        at com.bumptech.glide.Glide.get(Glide.java:166) 
        at com.bumptech.glide.Glide.getRetriever(Glide.java:680) 
        at com.bumptech.glide.Glide.with(Glide.java:732) 
        at in.lubble.app.GlideApp.with(GlideApp.java:104) 
        at in.lubble.app.MainActivity.onCreate(MainActivity.java:129) 
        at android.app.Activity.performCreate(Activity.java:7258) 
        at android.app.Activity.performCreate(Activity.java:7249) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1221) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:7002) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bumptech.glide.integration.okhttp3.OkHttpGlideModule" on path: DexPathList[[zip file "/data/app/in.lubble.app-8EnY0F_AIcvToay-aKJL9w==/base.apk"],nativeLibraryDirectories=[/data/app/in.lubble.app-8EnY0F_AIcvToay-aKJL9w==/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at java.lang.Class.forName(Class.java:378) 
        at com.bumptech.glide.module.ManifestParser.parseModule(ManifestParser.java:67) 
        at com.bumptech.glide.module.ManifestParser.parse(ManifestParser.java:47) 
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:230) 
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:221) 
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:182) 
        at com.bumptech.glide.Glide.get(Glide.java:166) 
        at com.bumptech.glide.Glide.getRetriever(Glide.java:680) 
        at com.bumptech.glide.Glide.with(Glide.java:732) 
        at in.lubble.app.GlideApp.with(GlideApp.java:104) 
        at in.lubble.app.MainActivity.onCreate(MainActivity.java:129) 
        at android.app.Activity.performCreate(Activity.java:7258) 
        at android.app.Activity.performCreate(Activity.java:7249) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1221) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:7002) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408) 
```

Multidex is Disabled

Proguard config:

-dontwarn com.bumptech.glide.load.resource.bitmap.VideoDecoder
-dontwarn okio.**
-dontwarn javax.annotation.Nullable
-dontwarn javax.annotation.ParametersAreNonnullByDefault
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep class com.bumptech.glide.GeneratedAppGlideModuleImpl
# for firebase auth
-keepattributes *Annotation*

**Comment by ishaangarg** [comment]
#579 is similar but for a very old version of Glide, the solution mentioned there by @TWiStErRob  seems no longer valid.

**Comment by ishaansrm** [comment]
Build works fine on Glide 4.5.0

**Comment by ishaangarg** [comment]
FYI: Working fine on Glide 4.5.0

**Comment by ishaangarg** [comment]
This is still not working in the latest Glide v4.8.0

**Comment by sjudd** [comment]
It looks like you're missing:

`-keep public class * implements com.bumptech.glide.module.GlideModule`

See http://bumptech.github.io/glide/doc/download-setup.html#proguard.

Alternatively disable manifest parsing if you have an AppGlideModule anyway: http://bumptech.github.io/glide/doc/configuration.html#manifest-parsing

**Comment by TommyFen** [comment]
I have same trouble， any idea?
