### ISSUE TITLE
android 9 cant show 

### ISSUE THREAD

**Issue by meimz** [bumptech/glide#3336]
android 9 cant show on the imageview
see below img
![tim 20180929101303](https://user-images.githubusercontent.com/14367223/46239803-43a06880-c3d0-11e8-9e5c-3a9671ec1b5a.png)
![tim 20180929101322](https://user-images.githubusercontent.com/14367223/46239805-4f8c2a80-c3d0-11e8-980d-bf1489a7eeb8.png)

   ` implementation 'com.github.bumptech.glide:glide:4.8.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'`

09-29 02:08:31.555 26258-26282/cn.mrcong.zhusumessage.zhusumessage D/EGL_emulation: eglMakeCurrent: 0xe19054e0: ver 3 0 (tinfo 0xe19036e0)
09-29 02:08:31.576 26258-26282/cn.mrcong.zhusumessage.zhusumessage D/EGL_emulation: eglMakeCurrent: 0xe19054e0: ver 3 0 (tinfo 0xe19036e0)
09-29 02:08:34.564 26258-26282/cn.mrcong.zhusumessage.zhusumessage D/EGL_emulation: eglMakeCurrent: 0xe19054e0: ver 3 0 (tinfo 0xe19036e0)
09-29 02:15:16.598 26258-26258/cn.mrcong.zhusumessage.zhusumessage W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@70b21e2
09-29 02:15:16.750 26258-26273/cn.mrcong.zhusumessage.zhusumessage I/ge.zhusumessag: Background concurrent copying GC freed 3712(333KB) AllocSpace objects, 0(0B) LOS objects, 53% free, 1353KB/2MB, paused 6.641ms total 32.999ms
09-29 02:15:17.420 26258-26282/cn.mrcong.zhusumessage.zhusumessage D/EGL_emulation: eglMakeCurrent: 0xe19054e0: ver 3 0 (tinfo 0xe19036e0)
09-29 02:15:17.481 26258-26282/cn.mrcong.zhusumessage.zhusumessage D/EGL_emulation: eglMakeCurrent: 0xe19054e0: ver 3 0 (tinfo 0xe19036e0)
09-29 02:15:17.554 26258-26258/cn.mrcong.zhusumessage.zhusumessage W/Glide: Load failed for http://i4.bvimg.com/512235/4bf47a851059bf12.jpg with size [1080x1731]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.io.IOException(Cleartext HTTP traffic to i4.bvimg.com not permitted)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    java.io.IOException(Cleartext HTTP traffic to i4.bvimg.com not permitted)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.io.IOException(Cleartext HTTP traffic to i4.bvimg.com not permitted)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.IOException: Cleartext HTTP traffic to i4.bvimg.com not permitted
09-29 02:15:17.555 26258-26258/cn.mrcong.zhusumessage.zhusumessage I/Glide: Root cause (1 of 1)
    java.io.IOException: Cleartext HTTP traffic to i4.bvimg.com not permitted
        at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:458)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:104)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:59)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:150)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:144)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:65)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
09-29 02:15:17.574 26258-26282/cn.mrcong.zhusumessage.zhusumessage D/EGL_emulation: eglMakeCurrent: 0xe19054e0: ver 3 0 (tinfo 0xe19036e0)
09-29 02:15:17.604 26258-26282/cn.mrcong.zhusumessage.zhusumessage D/EGL_emulation: eglMakeCurrent: 0xe19054e0: ver 3 0 (tinfo 0xe19036e0)
09-29 02:15:20.366 26258-26282/cn.mrcong.zhusumessage.zhusumessage D/EGL_emulation: eglMakeCurrent: 0xe19054e0: ver 3 0 (tinfo 0xe19036e0)

**Comment by onexuan** [comment]
https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

**Comment by sjudd** [comment]
Thanks @onexuan, that looks like the problem.
