### ISSUE TITLE
java.lang.RuntimeException: Failed to unparcel Bitmap - Load local disk image file using Glide and RemoteViews

### ISSUE THREAD

**Issue by yccheok** [bumptech/glide#3340]
I'm using `targetSdkVersion 28`, with the following glide library

    implementation 'com.github.bumptech.glide:glide:4.7.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'

I'm using Glide to load image in home widget. Given same set of data. Sometimes, it works. Sometimes it fails. When it fails, trying to resizing the home widget, will make the image appears again. I notice that regardless images shown in home widget, the following error message will be displayed

```
2018-10-04 05:02:38.470 2421-4125/? E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    java.lang.RuntimeException: Failed to unparcel Bitmap
        at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1793)
        at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1784)
        at android.widget.RemoteViews$BitmapCache.<init>(RemoteViews.java:1176)
        at android.widget.RemoteViews.<init>(RemoteViews.java:2433)
        at android.widget.RemoteViews.<init>(RemoteViews.java:2419)
        at android.widget.RemoteViews$3.createFromParcel(RemoteViews.java:3865)
        at android.widget.RemoteViews$3.createFromParcel(RemoteViews.java:3864)
        at com.android.internal.appwidget.IAppWidgetService$Stub.onTransact(IAppWidgetService.java:179)
        at android.os.Binder.execTransact(Binder.java:697)
```

The images are local disk file. This is how it looks like when users get what they want.

![0](https://user-images.githubusercontent.com/308276/46439485-4cf45100-c793-11e8-93dc-770ee871833a.png)

And this is how it looks like, when users don't get what they want.

![1](https://user-images.githubusercontent.com/308276/46439554-77460e80-c793-11e8-87dd-bf19bdd11121.png)

This is how we perform image loading

```
        AppWidgetTarget awt = new AppWidgetTarget(context, R.id.image_view_0, rv, appWidgetId);
        final Pair<Integer, Integer> bestSize = getBestSizeForWidget(attachment);
        Glide.with(context)
                .asBitmap()
                .load(attachment.getPath())
                .apply(new RequestOptions().override(bestSize.first, bestSize.second))
                .into(awt);
```

Any idea how we can debug this problem? Thank you.

**Comment by sjudd** [comment]
I'm not really sure how to debug that error. If it's an error parceling the only thing that comes to mind is that you might occasionally be exceeding the maximum parcel size. You could test this by artificially creating larger and larger Bitmaps and seeing if there's a size at which you can reliably send the Bitmap and a greater size at which you see the same error.
