### ISSUE TITLE
OutOfMemoryError  at IndentedAppendable.append

### ISSUE THREAD

**Issue by tamtom** [bumptech/glide#3341]
Glide throws OutOfMemory while creating excpetion 

**Glide Version**:4.7.1

**Integration libraries**:non

**Device/Android Version**:
<img width="783" alt="screen shot 2018-10-04 at 9 01 11 am" src="https://user-images.githubusercontent.com/7765381/46455536-27c40a80-c7b4-11e8-9edc-24905114026e.png">

**Stack trace / LogCat**:
```ruby
Fatal Exception: java.lang.OutOfMemoryError
       at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:94)
       at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:124)
       at java.lang.StringBuffer.append(StringBuffer.java:278)
       at java.io.StringWriter.write(StringWriter.java:123)
       at com.android.internal.util.FastPrintWriter.flushLocked(FastPrintWriter.java:358)
       at com.android.internal.util.FastPrintWriter.appendLocked(FastPrintWriter.java:303)
       at com.android.internal.util.FastPrintWriter.write(FastPrintWriter.java:625)
       at com.android.internal.util.FastPrintWriter.append(FastPrintWriter.java:658)
       at com.android.internal.util.FastPrintWriter.append(FastPrintWriter.java:17)
       at com.bumptech.glide.load.engine.GlideException$IndentedAppendable.append(GlideException.java:242)
       at com.bumptech.glide.load.engine.GlideException$IndentedAppendable.append(GlideException.java:242)
       at com.bumptech.glide.load.engine.GlideException$IndentedAppendable.append(GlideException.java:242)
       at com.bumptech.glide.load.engine.GlideException$IndentedAppendable.append(GlideException.java:230)
       at com.bumptech.glide.load.engine.GlideException.appendExceptionMessage(GlideException.java:168)
       at com.bumptech.glide.load.engine.GlideException.appendCausesWrapped(GlideException.java:201)
       at com.bumptech.glide.load.engine.GlideException.appendCauses(GlideException.java:179)
       at com.bumptech.glide.load.engine.GlideException.printStackTrace(GlideException.java:134)
       at com.bumptech.glide.load.engine.GlideException.appendCausesWrapped(GlideException.java:199)
       at com.bumptech.glide.load.engine.GlideException.appendCauses(GlideException.java:179)
       at com.bumptech.glide.load.engine.GlideException.printStackTrace(GlideException.java:134)
       at com.bumptech.glide.load.engine.GlideException.appendCausesWrapped(GlideException.java:199)
       at com.bumptech.glide.load.engine.GlideException.appendCauses(GlideException.java:179)
       at com.bumptech.glide.load.engine.GlideException.printStackTrace(GlideException.java:134)
       at com.bumptech.glide.load.engine.GlideException.printStackTrace(GlideException.java:129)
       at android.util.Log.getStackTraceString(Log.java:459)
       at android.util.Log.w(Log.java:272)
       at com.bumptech.glide.request.SingleRequest.onLoadFailed(SingleRequest.java:600)
       at com.bumptech.glide.request.SingleRequest.onLoadFailed(SingleRequest.java:593)
       at com.bumptech.glide.load.engine.EngineJob.handleExceptionOnMainThread(EngineJob.java:293)
       at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:327)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5584)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/debugging.html#out-of-memory-errors
