### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by SeongHeumPark** [bumptech/glide#3354]
**Glide Version**: 3.7.0

**Integration libraries**: okhttp3-integration:1.4.0

**Device/Android Version**: SM-A310N0/Android 7.0

**Issue details / Repro steps / Use case background**: 
My Project configuration is
1. Gradle Version 4.7
2. Support Library Version 26.1.0

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(activity)
        .load(pictureUrl)
        .placeholder(R.drawable.default)
        .bitmapTransform(new CircleTransform(Glide.get(activity).getBitmapPool()))
        .into(picture);
```

**Layout XML**:
```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    ...

    <ImageView
        android:id="@+id/image"
        android:layout_width="51dp"
        android:layout_height="51dp"
        ... />

    ...

</android.support.constraint.ConstraintLayout>
```

**Stack trace / LogCat**:
```ruby
java.lang.NoSuchMethodError: No direct method <init>(Lcom/bumptech/glide/manager/SupportRequestManagerFragment;Lcom/bumptech/glide/manager/SupportRequestManagerFragment$1;)V in class Lcom/bumptech/glide/manager/SupportRequestManagerFragment$SupportFragmentRequestManagerTreeNode; or its super classes (declaration of 'com.bumptech.glide.manager.SupportRequestManagerFragment$SupportFragmentRequestManagerTreeNode' appears in base.apk)
    at com.bumptech.glide.manager.SupportRequestManagerFragment.<init>(SupportRequestManagerFragment.java:25)
    at com.bumptech.glide.manager.SupportRequestManagerFragment.<init>(SupportRequestManagerFragment.java:32)
    at com.bumptech.glide.manager.SupportRequestManagerFragment.<init>(SupportRequestManagerFragment.java:32)
    at com.bumptech.glide.manager.RequestManagerRetriever.getSupportRequestManagerFragment(RequestManagerRetriever.java:185)
    at com.bumptech.glide.manager.RequestManagerRetriever.supportFragmentGet(RequestManagerRetriever.java:195)
    at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:104)
    at com.bumptech.glide.Glide.with(Glide.java:653)
```

**Comment by ejChathuranga** [comment]
Same here.

**Comment by longdw** [comment]
this is because the project implementation more than one version of glide,such as implementation 3.0.0 and 4.0.0.
