### ISSUE TITLE
BufferedOutputStream EBADF (Bad file descriptor)

### ISSUE THREAD

**Issue by rcketscientist** [bumptech/glide#3377]
**Glide Version**: 4.8.0

**Integration libraries**:N/A

**Device/Android Version**: Tab S

**Issue details / Repro steps / Use case background**: Scrolling to load new thumbs causes this reliably for me.  It does not crash, but might not load the thumb.  Scrolling to cause a reload usually loads fine.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
            GlideApp.with(itemView.context)
                .load(it)
                .centerCrop()
                .into(galleryImageView)
```

**Layout XML**:
```xml
    <ImageView
        android:id="@+id/galleryImageView"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_gravity="center"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintDimensionRatio="1"/>
```
parent:
```xml
            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/galleryView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:padding="@dimen/image_thumbnail_margin"
                app:fastScrollEnabled="true"
                app:fastScrollHorizontalThumbDrawable="@drawable/thumb_drawable"
                app:fastScrollHorizontalTrackDrawable="@drawable/line"
                app:fastScrollVerticalThumbDrawable="@drawable/thumb_drawable"
                app:fastScrollVerticalTrackDrawable="@drawable/line" />
```

**Stack trace / LogCat**:
```ruby
2018-10-27 13:33:24.297 2054-2779/com.anthonymandra.rawdroidpro W/System.err: java.io.IOException: write failed: EBADF (Bad file descriptor)
2018-10-27 13:33:24.297 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at libcore.io.IoBridge.write(IoBridge.java:501)
2018-10-27 13:33:24.297 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at java.io.FileOutputStream.write(FileOutputStream.java:316)
2018-10-27 13:33:24.297 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at com.bumptech.glide.load.data.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:75)
2018-10-27 13:33:24.298 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at com.bumptech.glide.load.data.BufferedOutputStream.maybeFlushBuffer(BufferedOutputStream.java:82)
2018-10-27 13:33:24.299 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at com.bumptech.glide.load.data.BufferedOutputStream.write(BufferedOutputStream.java:63)
2018-10-27 13:33:24.299 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at android.graphics.Bitmap.nativeCompress(Native Method)
2018-10-27 13:33:24.299 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at android.graphics.Bitmap.compress(Bitmap.java:1075)
2018-10-27 13:33:24.299 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at com.bumptech.glide.load.resource.bitmap.BitmapEncoder.encode(BitmapEncoder.java:88)
2018-10-27 13:33:24.299 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at com.bumptech.glide.load.resource.bitmap.BitmapEncoder.encode(BitmapEncoder.java:35)
2018-10-27 13:33:24.299 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at com.bumptech.glide.load.engine.DataCacheWriter.write(DataCacheWriter.java:31)
2018-10-27 13:33:24.299 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper.put(DiskLruCacheWrapper.java:134)
2018-10-27 13:33:24.299 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at com.bumptech.glide.load.engine.DecodeJob$DeferredEncodeManager.encode(DecodeJob.java:668)
2018-10-27 13:33:24.299 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.notifyEncodeAndRelease(DecodeJob.java:439)
2018-10-27 13:33:24.299 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:416)
2018-10-27 13:33:24.300 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:379)
2018-10-27 13:33:24.300 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:112)
2018-10-27 13:33:24.300 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at com.anthonymandra.rawdroid.ui.RawModelLoader$RawFetcher.loadData(RawModelLoader.kt:41)
2018-10-27 13:33:24.300 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
2018-10-27 13:33:24.300 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
2018-10-27 13:33:24.300 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
2018-10-27 13:33:24.300 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
2018-10-27 13:33:24.300 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2018-10-27 13:33:24.300 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2018-10-27 13:33:24.300 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at java.lang.Thread.run(Thread.java:761)
2018-10-27 13:33:24.300 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
2018-10-27 13:33:24.300 2054-2779/com.anthonymandra.rawdroidpro W/System.err: Caused by: android.system.ErrnoException: write failed: EBADF (Bad file descriptor)
2018-10-27 13:33:24.300 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at libcore.io.Posix.writeBytes(Native Method)
2018-10-27 13:33:24.300 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at libcore.io.Posix.write(Posix.java:273)
2018-10-27 13:33:24.301 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at libcore.io.BlockGuardOs.write(BlockGuardOs.java:319)
2018-10-27 13:33:24.301 2054-2779/com.anthonymandra.rawdroidpro W/System.err:     at libcore.io.IoBridge.write(IoBridge.java:496)
2018-10-27 13:33:24.301 2054-2779/com.anthonymandra.rawdroidpro W/System.err: 	... 24 more
```

Generally this error seems related to permissions, but this appears to be during the thumb caching which would be in the app sandbox and hence always permissible.  This does seem to go away when the cache exists to load.

**Comment by rcketscientist** [comment]
bump

**Comment by qq287597590** [comment]
I encounter the same problem,and solve it.

**Comment by qq287597590** [comment]
close Inputstream of StreamEncoder.java

**Comment by rcketscientist** [comment]
Thanks for the update!

Were you using a custom loader?  Did you try closing the stream there?

I'll try your patch this weekend, but it does make me a little nervous closing a parameter.
