### ISSUE TITLE
SVG example giving ArrayIndexOutOfBounds exception

### ISSUE THREAD

**Issue by ahmadalibaloch** [bumptech/glide#3378]
**Glide Version**:
`4.8.0`

**Integration libraries**:
`implementation 'com.caverock:androidsvg-aar:1.3'`

**Device/Android Version**:
Galaxy S8+, Android 8.1

**Issue details / Repro steps / Use case background**: 
SVG example in a Kotline project

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
        val requestBuilder: RequestBuilder<PictureDrawable> =
                Glide.with(this.context)
                        .`as`(PictureDrawable::class.java)
                        .transition(withCrossFade())
                        .listener(SvgSoftwareLayerSetter())
        val uri = Uri.parse("http://www.clker.com/cliparts/u/Z/2/b/a/6/android-toy-h.svg")
        requestBuilder.load(uri).into(holder.mImgView)
```

**Layout XML**:
AppCompactImageView

**Stack trace / LogCat**:
```2018-10-27 22:37:15.452 23692-23692/com.abc.abc W/Glide: Load failed for http://www.clker.com/cliparts/u/Z/2/b/a/6/android-toy-h.svg with size [350x350]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.lang.IndexOutOfBoundsException(Index: 0, Size: 0)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
2018-10-27 22:37:15.452 23692-23692/com.abc.abc I/Glide: Root cause (1 of 1)
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at java.util.Collections$UnmodifiableList.get(Collections.java:1351)
        at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:71)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
```

**Comment by rohfosho** [comment]
Make sure to include the annotation processor using `kapt` and also make sure to implement the `SvgModule`

**Comment by dinorahtovar** [comment]
Im having this same issue on Kotlin
There is any information we can receive?
