### ISSUE TITLE
Error Drawable not shown on OOM error

### ISSUE THREAD

**Issue by grote** [bumptech/glide#3404]
**Glide Version**: 4.8.0

**Integration libraries**: None

**Device/Android Version**: Android 28 emulator

**Issue details / Repro steps / Use case background**: 

If I load a very large image like this one: ![error_large](https://user-images.githubusercontent.com/244947/48498340-34a93480-e81d-11e8-8e3f-35ea07457228.gif)

Glide fails of course to load it, but it doesn't show the error drawable as it should. The image just stays blank. Note that `RequestListener#loadFailed()` gets called. But even calling `target.onLoadFailed(errorDrawable)` there doesn't show the error drawable.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
		GlideApp.with(imageView)
				.load(url)
				.error(R.drawable.ic_image_broken)
				.into(imageView)
				.waitForLayout();
```

**Stack trace / LogCat**:
```ruby
W/r.android.debu: Throwing OutOfMemoryError "Failed to allocate a 268435468 byte allocation with 6291456 free bytes and 114MB until OOM, max allowed footprint 289082504, growth limit 402653184"
```

**Comment by grote** [comment]
Note that there's a different kind of OOM error (caused by a different type of test image) that *does* show the error drawable as expected:

```ruby
2018-11-14 15:01:58.092 W/Glide: Load failed for org.briarproject.briar.android.conversation.AttachmentItem@ef80b1e with size [394x551]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There were 2 causes:
    java.lang.OutOfMemoryError(null)
    java.lang.OutOfMemoryError(null)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{->Object->Drawable}, LOCAL
    There were 2 causes:
    java.lang.OutOfMemoryError(null)
    java.lang.OutOfMemoryError(null)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{->GifDrawable->Drawable}
        Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{->Bitmap->Drawable}
    There was 1 cause:
    java.lang.OutOfMemoryError(null)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.lang.OutOfMemoryError: 
        Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{->BitmapDrawable->Drawable}
    There was 1 cause:
    java.lang.OutOfMemoryError(null)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.lang.OutOfMemoryError: 
2018-11-14 15:01:58.093 I/Glide: Root cause (1 of 2)
    java.lang.OutOfMemoryError
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1046)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1000)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:950)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:911)
        at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.createBitmap(LruBitmapPool.java:149)
        at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.getDirty(LruBitmapPool.java:142)
        at com.bumptech.glide.load.resource.bitmap.Downsampler.setInBitmap(Downsampler.java:686)
        at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:296)
        at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:206)
        at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:62)
        at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:18)
        at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:72)
        at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:55)
        at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:45)
```

**Comment by grote** [comment]
Looks like nobody has time to look at this right now. Maybe I can least make the bot go away until that changes.

**Comment by grote** [comment]
@TWiStErRob do you want to have a quick look at this ticket? If you think it isn't important enough, I'll stop fighting the closing bot.

**Comment by sjudd** [comment]
Are you able to attach a simple sample app that reproduces this? Consider also: http://bumptech.github.io/glide/tut/failing-test-cases.html. Seems like this would be simple to add to one of the existing emulator tests.
