### ISSUE TITLE
 java.lang.String cannot be cast to java.lang.Object[]

### ISSUE THREAD

**Issue by hzyxym** [bumptech/glide#3414]
build:gradle:3.1.4
glide:4.8.0
okhttp3 -3.3.1

code：
GlideApp.with(mContext)
                        .load(imgUrl)
                        .transforms(new CenterCrop(), new RoundedCorners(12))
                        .placeholder(defaultDrawable)
                        .into(mImageView);

error msg：
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Object[]
	at android.support.v4.util.SimpleArrayMap.allocArrays(SimpleArrayMap.java:183)
	at android.support.v4.util.SimpleArrayMap.put(SimpleArrayMap.java:437)
	at com.bumptech.glide.util.CachedHashCodeArrayMap.put(CachedHashCodeArrayMap.java:34)
	at com.bumptech.glide.request.RequestOptions.transform(RequestOptions.java:1315)
	at com.bumptech.glide.request.RequestOptions.transform(RequestOptions.java:1269)
	at com.bumptech.glide.request.RequestOptions.transforms(RequestOptions.java:1237)
	at com.phone580.base.GlideOptions.transforms(GlideOptions.java:561)
	at com.phone580.base.b.a(GlideRequest.java:573)
	at com.phone580.base.ui.widget.CommonBanner.onCreateItemView(CommonBanner.java:82)
	at com.flyco.banner.widget.Banner.base.BaseBanner$a.instantiateItem(BaseBanner.java:454)
	at com.flyco.banner.widget.LoopViewPager.b.instantiateItem(LoopPagerAdapterWrapper.java:88)
	at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1004)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1186)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:663)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:625)
	at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:617)
	at com.flyco.banner.widget.LoopViewPager.LoopViewPager.setCurrentItem(LoopViewPager.java:70)
	at com.flyco.banner.widget.LoopViewPager.LoopViewPager$1.onPageScrollStateChanged(LoopViewPager.java:198)
	at android.support.v4.view.ViewPager.dispatchOnScrollStateChanged(ViewPager.java:1958)
	at android.support.v4.view.ViewPager.setScrollState(ViewPager.java:491)
	at android.support.v4.view.ViewPager$3.run(ViewPager.java:266)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
	at android.view.Choreographer.doCallbacks(Choreographer.java:732)
	at android.view.Choreographer.doFrame(Choreographer.java:661)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:187)
	at android.app.ActivityThread.main(ActivityThread.java:7025)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)

**Comment by sjudd** [comment]
What version of Android was this?

Similar to #3296

**Comment by hzyxym** [comment]
What  can I do for this？sir

**Comment by ovUdemy** [comment]
@hzyxym did you find a solution for this?
