### ISSUE TITLE
a gif crash

### ISSUE THREAD

**Issue by wangrunxiang** [bumptech/glide#3424]
**Glide Version**:4.7.1

**Device/Android Version**:Android 8.0 and 8.1

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
java.lang.RuntimeException: Unable to destroy activity {com.duowan.mobile/com.duowan.mobile.basemedia.watchlive.activity.LiveTemplateActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5046)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5065)
	at android.app.ActivityThread.-wrap6(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at com.bumptech.glide.load.resource.gif.GifFrameLoader.getWidth(GifFrameLoader.java:132)
	at com.bumptech.glide.load.resource.gif.GifDrawable.getIntrinsicWidth(GifDrawable.java:261)
	at android.widget.ImageView.invalidateDrawable(ImageView.java:292)
	at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:450)
	at android.graphics.drawable.Drawable.setVisible(Drawable.java:859)
	    at com.bumptech.glide.load.resource.gif.GifDrawable.setVisible(GifDrawable.java:256)
	at android.widget.ImageView.onDetachedFromWindow(ImageView.java:1725)
	at android.view.View.dispatchDetachedFromWindow(View.java:17611)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5286)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5257)
	at android.view.ViewGroup.removeView(ViewGroup.java:5188)
	    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1529)
	    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	    at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
	    at android.support.v4.app.FragmentManagerImpl.dispatchDestroyView(FragmentManager.java:3229)
	    at android.support.v4.app.Fragment.performDestroyView(Fragment.java:2561)
	    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1512)
	    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	    at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
	    at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3235)
	    at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:265)
	    at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:390)
	    at com.trello.rxlifecycle2.components.support.RxFragmentActivity.onDestroy(RxFragmentActivity.java:95)
	    at com.yy.mobile.mvp.MvpActivity.onDestroy(MvpActivity.java:87)
	    at com.yy.immersion.ImmersionActivity.onDestroy(ImmersionActivity.java:73)
	at com.yy.mobile.ui.DialogBaseActivity.onDestroy(DialogBaseActivity.java:142)
	at com.duowan.mobile.basemedia.watchlive.activity.BasePluginEntLiveActivity.onDestroy(BasePluginEntLiveActivity.java:273)
	at com.duowan.mobile.basemedia.watchlive.activity.LiveTemplateActivity.onDestroy(LiveTemplateActivity.java:81)
	at android.app.Activity.performDestroy(Activity.java:7604)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1253)
	    at com.yy.android.small.launcher.ApkPluginLauncher$InstrumentationWrapper.callActivityOnDestroy(ApkPluginLauncher.java:357)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5033)
	... 9 more
```

**Comment by wangrunxiang** [comment]
how can i fix it?

**Comment by robertcabrera4871** [comment]
This just happened to me
