### ISSUE TITLE
File descriptor problem

### ISSUE THREAD

**Issue by qq287597590** [bumptech/glide#3429]
**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
``` cause this problem, because of  file descriptor leaked
// Short Msg: java.lang.RuntimeException
// Long Msg: java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
// Build Time: 1480739752000
// java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
// 	at android.view.InputChannel.nativeReadFromParcel(Native Method)
// 	at android.view.InputChannel.readFromParcel(InputChannel.java:148)
// 	at android.view.InputChannel$1.createFromParcel(InputChannel.java:39)
// 	at android.view.InputChannel$1.createFromParcel(InputChannel.java:36)
// 	at com.android.internal.view.InputBindResult.<init>(InputBindResult.java:68)
// 	at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:112)
// 	at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:109)
// 	at com.android.internal.view.IInputMethodManager$Stub$Proxy.startInput(IInputMethodManager.java:631)
// 	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1326)
// 	at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1466)
// 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3610)
// 	at android.os.Handler.dispatchMessage(Handler.java:102)
// 	at android.os.Looper.loop(Looper.java:179)
// 	at android.app.ActivityThread.main(ActivityThread.java:5672)
// 	at java.lang.reflect.Method.invoke(Native Method)
// 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
// 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
// 

<!--
What is the error message that you got in the log?
You can find some help on diagnosing issues here: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling
-->
**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by sjudd** [comment]
Please fill out the issue template. What version are you using? How are you reproducing this?
