### ISSUE TITLE
[Q]How to load a gif image drawable into ImageView？

### ISSUE THREAD

**Issue by lomoya90** [bumptech/glide#3435]
**Glide Version**:
4.2.0

**Integration libraries**:

**Device/Android Version**:
Pixel 2 XL / Android 9

**Issue details / Repro steps / Use case background**: 

I can only get the GIF's Drawable object.
![image](https://user-images.githubusercontent.com/6427266/49284041-5d445600-f4ce-11e8-9f6d-be56f544d909.png)

**Stack trace / LogCat**:
```ruby
 E/GlideExecutor: Request threw uncaught throwable
    com.bumptech.glide.Registry$NoModelLoaderAvailableException: Failed to find any ModelLoaders for model: android.graphics.drawable.AnimatedImageDrawable@66550b1
        at com.bumptech.glide.Registry.getModelLoaders(Registry.java:543)
        at com.bumptech.glide.load.engine.DecodeHelper.getLoadData(DecodeHelper.java:186)
        at com.bumptech.glide.load.engine.DecodeHelper.getCacheKeys(DecodeHelper.java:204)
        at com.bumptech.glide.load.engine.DataCacheGenerator.<init>(DataCacheGenerator.java:33)
        at com.bumptech.glide.load.engine.DecodeJob.getNextGenerator(DecodeJob.java:278)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:259)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:386)
```

**Comment by sjudd** [comment]
I think this actually is supported in newer versions of Glide, take a look through the release notes: https://github.com/bumptech/glide/releases
