### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by mingxin-yang** [bumptech/glide#3441]
**Glide Version 4.8.0**:

**okhttp3:okhttp:3.12.0**:

**HUAWEI/8.0**:

**Issue details / Repro steps / Use case background**: 
```
2018-12-04 11:53:00.697 14276-14276/im.autobot.mirrorlink W/Glide: Load failed for http://192.72.1.1/thumb/Normal/FILE181204-100432-004502.MOV with size [480x270]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.io.FileNotFoundException(http://192.72.1.1/thumb/Normal/FILE181204-100432-004502.MOV)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    java.io.FileNotFoundException(http://192.72.1.1/thumb/Normal/FILE181204-100432-004502.MOV)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.io.FileNotFoundException(http://192.72.1.1/thumb/Normal/FILE181204-100432-004502.MOV)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.FileNotFoundException: http://192.72.1.1/thumb/Normal/FILE181204-100432-004502.MOV
2018-12-04 11:53:00.698 14276-14276/im.autobot.mirrorlink I/Glide: Root cause (1 of 1)
    java.io.FileNotFoundException: http://192.72.1.1/thumb/Normal/FILE181204-100432-004502.MOV
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:106)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:59)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:150)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:144)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:65)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
String url = "http://192.72.1.1/thumb/Normal/FILE181204-100432-004502.MOV";
Glide.with(view.getContext())
	.load(url)
	.into(mVideoIV);
```

**Layout XML**:
```xml
<RelativeLayout
            android:id="@+id/rl_video"
            android:layout_width="160dp"
            android:layout_height="90dp" >

            <ImageView
                android:id="@+id/iv_video"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:scaleType="centerCrop"
                android:src="@drawable/bg_drivingrecord_video_default" />

            <ImageView
                android:id="@+id/iv_video_icon"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerInParent="true"
                android:src="@drawable/ic_drivingrecord_play" />

            <ProgressBar
                android:id="@+id/progress_bar"
                style="?android:attr/progressBarStyleHorizontal"
                android:layout_width="40dp"
                android:layout_height="40dp"
                android:layout_centerInParent="true"
                android:background="@drawable/shape_circle_progress_grey"
                android:indeterminate="false"
                android:max="100"
                android:progress="0"
                android:progressDrawable="@drawable/shape_circle_progress_white"
                android:visibility="gone" />

            <TextView
                android:id="@+id/tv_download_state"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentBottom="true"
                android:layout_alignParentLeft="true"
                android:layout_margin="5dp"
                android:text="@string/camera_downloaded"
                android:textColor="#fff" />
        </RelativeLayout>

        <TextView
            android:id="@+id/tv_time1"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginLeft="10dp"
            android:layout_marginTop="14dp"
            android:layout_toRightOf="@id/rl_video"
            android:text="2015-8-08"
            android:textColor="#47606e"
            android:textSize="12sp" />

        <TextView
            android:id="@+id/tv_time2"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignLeft="@id/tv_time1"
            android:layout_below="@id/tv_time1"
            android:layout_toRightOf="@id/rl_video"
            android:text="12:12"
            android:textColor="#47606e"
            android:textSize="16sp"
            android:textStyle="bold" />

        <TextView
            android:id="@+id/tv_size"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignBottom="@id/rl_video"
            android:layout_alignLeft="@id/tv_time1"
            android:layout_marginBottom="10dp"
            android:layout_toRightOf="@id/rl_video"
            android:text="312M"
            android:textColor="#a1abb0"
            android:textSize="12sp" />

        <CheckBox
            android:id="@+id/cb_edite"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:layout_centerVertical="true"
            android:button="@drawable/selector_img"
            android:padding="6dp" />

        <ImageView
            android:id="@+id/iv_download"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:layout_centerVertical="true"
            android:padding="10dp"
            android:src="@drawable/ic_drivingrecord_video_download" />
    </RelativeLayout>
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by hardikamal** [comment]
@mingxin-yang Any solution found to this issue. I am facing the same issue.
