### ISSUE TITLE
How to properly restart GIF playback with Glide?

### ISSUE THREAD

**Issue by Zhuinden** [bumptech/glide#3445]
**Glide Version**: 4.7.1
**Integration libraries**: OkHttp3 but it is not relevant
**Device/Android Version**: Not relevant
**Issue details / Repro steps / Use case background**: 

I want to restart the GifDrawable instead of sharing the playback % across loads. 

I saw that each time I load the gif, it "continued" from where it was, instead of restarting it.

I wanted to be able to make it so that it restarts each time.

This actually proved to be quite difficult.

>  How do you use Glide?

I finally managed to make it work without crashing like this:

```kotlin
class GlideImageView : AppCompatImageView {
    private var asGif = false
    private var drawableResource = 0

    constructor(context: Context) : super(context) {
        init(context, null, 0)
    }

    constructor(context: Context, attrs: AttributeSet) : super(context, attrs) {
        init(context, attrs, 0)
    }

    constructor(context: Context, attrs: AttributeSet, defStyleAttr: Int) : super(context, attrs, defStyleAttr) {
        init(context, attrs, defStyleAttr)
    }

    private fun init(context: Context, attributeSet: AttributeSet?, defStyle: Int) {
        if (attributeSet != null) {
            val a: TypedArray? = when {
                defStyle != 0 -> context.obtainStyledAttributes(attributeSet, R.styleable.GlideImageView, defStyle, 0)
                else -> context.obtainStyledAttributes(attributeSet, R.styleable.GlideImageView)
            }
            asGif = a!!.getBoolean(R.styleable.GlideImageView_as_gif, false)
            drawableResource = a.getResourceId(R.styleable.GlideImageView_image_resource, 0)
            a.recycle()

            waitForMeasure { _, _, _ ->
                if (!isInEditMode) {
                    if (drawableResource != 0) {
                        if (asGif) {
                            GlideApp.with(context).asGif().diskCacheStrategy(DiskCacheStrategy.NONE).load(drawableResource).listener(object: RequestListener<GifDrawable>{
                                override fun onLoadFailed(e: GlideException?, model: Any?, target: Target<GifDrawable>?, isFirstResource: Boolean): Boolean =
                                    false

                                override fun onResourceReady(resource: GifDrawable, model: Any?, target: Target<GifDrawable>, dataSource: DataSource?, isFirstResource: Boolean): Boolean {
                                    GifDrawableAccessor.setIsRunning(resource, false)
                                    GifDrawableAccessor.setFrameLoaderIsRunning(resource, false)
                                    resource.startFromFirstFrame()
                                    GifDrawableAccessor.setFrameLoaderIsRunning(resource, true)
                                    GifDrawableAccessor.setIsRunning(resource, true)
                                    return false
                                }
                            }).into(this@GlideImageView)
                        } else {
                            GlideApp.with(context).load(drawableResource).into(this@GlideImageView)
                        }
                    } else {
                        GlideApp.with(context).clear(this@GlideImageView)
                    }
                } else {
                    setImageResource(drawableResource)
                }
            }
        }
    }
}
```

where `GifDrawableAccessor` is:

``` java
package com.bumptech.glide.load.resource.gif;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

// # Proguard config for glide gif loading for GifDrawableAccessor
//-keep class com.bumptech.glide.load.resource.gif.** { *; }
public class GifDrawableAccessor {
    public static void setIsRunning(GifDrawable gifDrawable, boolean isRunning) {
        gifDrawable.setIsRunning(isRunning);
    }

    public static void setFrameLoaderIsRunning(GifDrawable gifDrawable, boolean isRunning) {
        GifDrawable.GifState gifState = ((GifDrawable.GifState) (gifDrawable.getConstantState()));
        GifFrameLoader gifFrameLoader = gifState.frameLoader;
        Class<?> gifFrameLoaderClass = gifFrameLoader.getClass();
        try {
            if(isRunning) {
                Method start = gifFrameLoaderClass.getDeclaredMethod("start");
                start.setAccessible(true);
                start.invoke(gifFrameLoader);
            } else {
                Method stop = gifFrameLoaderClass.getDeclaredMethod("stop");
                stop.setAccessible(true);
                stop.invoke(gifFrameLoader);
            }
        } catch(NoSuchMethodException e) {
            throw new RuntimeException(e);
        } catch(IllegalAccessException e) {
            throw new RuntimeException(e);
        } catch(InvocationTargetException e) {
            throw new RuntimeException(e);
        }
    }
}
```

Without the use of Reflection and manually stopping FrameLoader with via invoking its private methods, I was getting:

```
    java.lang.IllegalArgumentException: Can't restart a running animation
        at com.bumptech.glide.util.Preconditions.checkArgument(Preconditions.java:19)
        at com.bumptech.glide.load.resource.gif.GifFrameLoader.setNextStartFromFirstFrame(GifFrameLoader.java:237)
        at com.bumptech.glide.load.resource.gif.GifDrawable.startFromFirstFrame(GifDrawable.java:208)
        at *.utils.GlideImageView$init$$inlined$waitForMeasure$1$lambda$1.onResourceReady(GlideImageView.kt:62)
        at *.utils.GlideImageView$init$$inlined$waitForMeasure$1$lambda$1.onResourceReady(GlideImageView.kt:56)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:574)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:549)
        at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:218)
        at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:324)
```

----------

Nothing in https://github.com/bumptech/glide/issues/2745 was helpful, so I had to resort to reflection.

I don't really want to use reflection, so please provide a sane way to restart a GIF.

Thanks.

**Comment by Zhuinden** [comment]
I think I've stated what's necessary to reproduce the problem and know what to do to make it work.

**Comment by sjudd** [comment]
I wrote a couple of tests that seem to pass: https://github.com/sjudd/glide/commit/45d50f73082153baeb3db4a8c72d0c6336ca78bb. If you could modify them to reproduce your crash and send a pull request I'd be happy to take a look.

**Comment by Zhuinden** [comment]
.....huh. That is rather odd, I expected it to fail - it was clearly not stopping the GifFrameLoader no matter how much I tried to stop it (except for the reflection trick, of course).

I'll try to break it reliably and in a reproducible manner then, sometime this week, thanks for looking at it.

**Comment by sjudd** [comment]
Sure no problem. It's a bit tough to get the View to behave realistically in those tests. It's always possible that there's a race in the frame loader too.

**Comment by Zhuinden** [comment]
Christmas got in the way but I'll try to do it between the holidays :p

**Comment by micaelomota** [comment]
Hey people, anybody has solved that issue? I'm getting the same problem even after run `.stop()`. I've tried running it directly on the image instance but it keeps throwing the same exception.

```
if (imageView.getDrawable() instanceof GifDrawable) {
            ((GifDrawable)imageView.getDrawable()).stop();
            ((GifDrawable)imageView.getDrawable()).startFromFirstFrame();
}

**Comment by Zhuinden** [comment]
@micaelomota have you tried the reflection solution I did above?

**Comment by micaelomota** [comment]
> @micaelomota have you tried the reflection solution I did above?

Thank you! Actually I found out what was wrong...
I was getting the same exception when running it inside the view holder. I was trying to make the GIF start from the beginning with adapter.notifyItemChanged();. My solution was to keep an instance of the GifDrawable resource in the activity

**Comment by a365344743s** [comment]
GifDrawable.GifState & GifDrawable.GifState.frameLoader is unaccessible now.

**Comment by satyarajanaidu** [comment]
> Hey people, anybody has solved that issue? I'm getting the same problem even after run `.stop()`. I've tried running it directly on the image instance but it keeps throwing the same exception.
> 
> ```
> if (imageView.getDrawable() instanceof GifDrawable) {
>             ((GifDrawable)imageView.getDrawable()).stop();
>             ((GifDrawable)imageView.getDrawable()).startFromFirstFrame();
> }
> ```
> 
> wtf
> 
> ```
> resource.stop();
> if (!resource.isRunning()) {
>     resource.startFromFirstFrame();
> }
> ```
> 
> `java.lang.IllegalArgumentException: Can't restart a running animation`

Worked for me.
