### ISSUE TITLE
 java.lang.IllegalStateException: Already released

### ISSUE THREAD

**Issue by zhangli1845** [bumptech/glide#3462]
12-20 22:08:54.077 25609-25609/? E/CrashHandler: java.lang.RuntimeException: Unable to resume activity {com.one.venus/com.one.venus.ui.main.PayMainActivity}: java.lang.IllegalStateException: Already released
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3502)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3538)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1648)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:191)
        at android.app.ActivityThread.main(ActivityThread.java:6016)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
     Caused by: java.lang.IllegalStateException: Already released
        at com.bumptech.glide.util.pool.StateVerifier$DefaultStateVerifier.throwIfRecycled(StateVerifier.java:46)
        at com.bumptech.glide.load.engine.EngineJob.addCallback(EngineJob.java:125)
        at com.bumptech.glide.load.engine.Engine.load(Engine.java:194)
        at com.bumptech.glide.request.SingleRequest.onSizeReady(SingleRequest.java:432)
        at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.getSize(ViewTarget.java:389)
        at com.bumptech.glide.request.target.ViewTarget.getSize(ViewTarget.java:221)
        at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:257)
        at com.bumptech.glide.manager.RequestTracker.resumeRequests(RequestTracker.java:128)
        at com.bumptech.glide.RequestManager.resumeRequests(RequestManager.java:256)
        at com.bumptech.glide.RequestManager.onStart(RequestManager.java:281)
        at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStart(ActivityFragmentLifecycle.java:51)
        at com.bumptech.glide.manager.SupportRequestManagerFragment.onStart(SupportRequestManagerFragment.java:182)
        at android.support.v4.app.Fragment.performStart(Fragment.java:2372)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
        at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3206)
        at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:206)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:605)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1268)
        at android.app.Activity.performStart(Activity.java:6387)
        at android.app.Activity.performRestart(Activity.java:6433)
        at android.app.Activity.performResume(Activity.java:6438)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3481)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3538) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1648) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:191) 
        at android.app.ActivityThread.main(ActivityThread.java:6016) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)

is anyone can explain " Already released" mean what released?

@sjudd

**Comment by botraunak** [comment]
were you able to solve this?

**Comment by zhangli1845** [comment]
> were you able to solve this?

no,sorry still do not know how to resolve this
