### ISSUE TITLE
java.lang.IllegalStateException: Already released

### ISSUE THREAD

**Issue by OsBelief** [bumptech/glide#3464]
Glide Version:4.6.1
Device/Android Version:
SM-J111F 5.1.1

java.lang.IllegalStateException: Already released
    at com.bumptech.glide.util.pool.StateVerifier$DefaultStateVerifier.throwIfRecycled(SourceFile:46)
    at com.bumptech.glide.load.engine.EngineJob.handleExceptionOnMainThread(SourceFile:278)
    at om.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(SourceFile:327)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6934)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by botraunak** [comment]
were you able yo solve this?
