### ISSUE TITLE
Glide custom ResourceDecoder not work?

### ISSUE THREAD

**Issue by didikee** [bumptech/glide#3465]
**Glide Version**:4.8.0
**Device/Android Version**: SM-930 android8.0

**There has relation issues: #2618 #2607 ,But not work for me.**
So, I open a new issues to report my problem.
Any help is welcome!

**log**
```
com.bumptech.glide.Registry$NoModelLoaderAvailableException: Failed to find any ModelLoaders for model: com.poly.book.view.glide.GlideSvgItem@88a4796
        at com.bumptech.glide.Registry.getModelLoaders(Registry.java:584)
        at com.bumptech.glide.load.engine.DecodeHelper.getLoadData(DecodeHelper.java:205)
        at com.bumptech.glide.load.engine.DecodeHelper.getCacheKeys(DecodeHelper.java:223)
        at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:44)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:833)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
```

Here is my code:
**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

```
@GlideModule
public class MyGlideModule extends AppGlideModule {
    @Override
    public void registerComponents(@NonNull Context context, @NonNull Glide glide, @NonNull Registry registry) {
        super.registerComponents(context, glide, registry);
        registry.append(Registry.BUCKET_BITMAP, GlideSvgItem.class, Bitmap.class, new SvgFileDecoder(glide.getBitmapPool()));
//        registry.prepend(GlideSvgItem.class, InputStream.class, new SvgLoaderFactory()); // this work fine.
    }
}
```

```
public class SvgFileDecoder implements ResourceDecoder<GlideSvgItem, Bitmap> {
    private final BitmapPool bitmapPool;

    SvgFileDecoder(BitmapPool bitmapPool) {
        this.bitmapPool = bitmapPool;
    }

    @Override
    public boolean handles(@NonNull GlideSvgItem source, @NonNull Options options) throws IOException {
        return true;
    }

    @Nullable
    @Override
    public Resource<Bitmap> decode(@NonNull GlideSvgItem source, int width, int height, @NonNull Options options) throws IOException {
        Bitmap bitmap = SvgBitmapUtil.render(new File(source.path), width, height, false, source.progress, false);
        return BitmapResource.obtain(bitmap, bitmapPool);
    }
}
```

```
// context is activity
// hold.svgView is Normal ImageView
Glide.with(context).load(new GlideSvgItem(svgFile.getAbsolutePath(), progress)).into(holder.svgView);
```

When i use Modeloader,it's work fine.But if i use ResouceLoader,glide can't load anything.
what's wrong with me?

**Comment by sjudd** [comment]
Are you able to reproduce this in a sample app?
