### ISSUE TITLE
Crash when mutating SquaringDrawable (getConstantState is not overridden) - v3.5.2

### ISSUE THREAD

**Issue by alex2069** [bumptech/glide#349]
If an ImageView has something that has its (internal) <code>mColorMod</code> field set to true (i.e. there is an alpha or color filter set - see <code>ImageView.applyColorMod()</code>), then when Glide updates the image view providing the <code>TransitionDrawable</code> (the current drawable + <code>SquaringDrawable</code>), the image view attempts to mutate it and crashes (NPE) when calling <code>SquaringDrawable.getConstantState()</code>.

Trace from Genymotion v4.4.2
```Java
    java.lang.NullPointerException
            at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:671)
            at android.graphics.drawable.TransitionDrawable$TransitionState.<init>(TransitionDrawable.java:249)
            at android.graphics.drawable.TransitionDrawable.createConstantState(TransitionDrawable.java:101)
            at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:608)
            at android.widget.ImageView.applyColorMod(ImageView.java:1216)
            at android.widget.ImageView.updateDrawable(ImageView.java:716)
            at android.widget.ImageView.setImageDrawable(ImageView.java:421)
            at com.bumptech.glide.request.target.ImageViewTarget.setDrawable(ImageViewTarget.java:37)
            at com.bumptech.glide.request.animation.DrawableCrossFadeViewAnimation.animate(DrawableCrossFadeViewAnimation.java:49)
            at com.bumptech.glide.request.animation.DrawableCrossFadeViewAnimation.animate(DrawableCrossFadeViewAnimation.java:14)
            at com.bumptech.glide.request.target.ImageViewTarget.onResourceReady(ImageViewTarget.java:75)
            at com.bumptech.glide.request.target.GlideDrawableImageViewTarget.onResourceReady(GlideDrawableImageViewTarget.java:66)
            at com.bumptech.glide.request.target.GlideDrawableImageViewTarget.onResourceReady(GlideDrawableImageViewTarget.java:12)
            at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:499)
            at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:486)
            at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:158)
            at com.bumptech.glide.load.engine.EngineJob.access$100(EngineJob.java:22)
            at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:202)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by sjudd** [comment]
Thanks for the report, any chance you can add a few lines of example code that will reproduce the problem?

**Comment by alex2069** [comment]
MainActivity
```java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.main_activity);

        final ImageView imgView = (ImageView) findViewById(R.id.main_img);
        imgView.setColorFilter(new PorterDuffColorFilter(Color.RED, PorterDuff.Mode.MULTIPLY));

        findViewById(R.id.main_click_to_crash).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Uri uri = Uri.parse("http://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Square_-_black_simple.svg/200px-Square_-_black_simple.svg.png");
                Glide.with(MainActivity.this)
                        .load(uri)
                        .placeholder(R.drawable.glide_logo)
                        .into(imgView);
            }
        });
    }
```

Layout
```xml
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:tools="http://schemas.android.com/tools"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:paddingLeft="@dimen/activity_horizontal_margin"
              android:paddingRight="@dimen/activity_horizontal_margin"
              android:paddingTop="@dimen/activity_vertical_margin"
              android:paddingBottom="@dimen/activity_vertical_margin"
              tools:context=".MainActivity"
              android:orientation="vertical">

    <Button
            android:id="@+id/main_click_to_crash"
            android:layout_width="100dp"
            android:text="Click to crash"
            android:layout_height="wrap_content"
            tools:ignore="HardcodedText"/>

    <ImageView
            android:id="@+id/main_img"
            android:layout_width="100dp"
            android:layout_height="100dp"
            android:contentDescription="@null"/>

</LinearLayout>
```

The <code>R.drawable.glide_logo</code> was just the logo in the Glide read me heh.

Here is a demo project: https://www.dropbox.com/s/6yg6zk5qt3ibp95/glide-mutate-crash.zip?dl=0
