### ISSUE TITLE
anr from Glide library

### ISSUE THREAD

**Issue by kofboy2000** [bumptech/glide#3493]
**Glide Version**:
**4.7.1**

**Integration libraries**:
**No**

**Device/Android Version**:
**fails on Galayx Note9 / N960F**

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
        GlideApp.with(mContext)
                .load(path)
                .into(view);
```

**Layout XML**:
```xml
<ImageView ...
```

**Stack trace / LogCat**:
```ruby
"glide-active-resources" prio=5 tid=19 Waiting
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x12c816d0 self=0x7b771a3800
  | sysTid=28928 nice=10 cgrp=default sched=0/0 handle=0x7b7c35f4f0
  | state=S schedstat=( 2378962 0 3 ) utm=0 stm=0 core=7 HZ=100
  | stack=0x7b7c25c000-0x7b7c25e000 stackSize=1041KB
  | held mutexes=
  at java.lang.Object.wait(Native method)
  - waiting on <0x0d9b9216> (a java.lang.Object)
  at java.lang.Object.wait(Object.java:422)
  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
  - locked <0x0d9b9216> (a java.lang.Object)
  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
  at com.bumptech.glide.load.engine.ActiveResources.cleanReferenceQueue(ActiveResources.java:131)
  at com.bumptech.glide.load.engine.ActiveResources$2.run(ActiveResources.java:119)
  at java.lang.Thread.run(Thread.java:764)
```

**Comment by sjudd** [comment]
This looks expected, do you have the main thread stack trace?

**Comment by kofboy2000** [comment]
Dear sjudd,
Here is main thread stack trace,

**Stack trace / LogCat**:

```ruby
"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x768b0fb8 self=0x7b98414c00
  | sysTid=24102 nice=0 cgrp=default sched=0/0 handle=0x7c1f14e560
  | state=S schedstat=( 3260790072 2712153238 3574 ) utm=126 stm=200 core=1 HZ=100
  | stack=0x7fc8ce6000-0x7fc8ce8000 stackSize=8MB
  | held mutexes=
  kernel: __switch_to+0xcc/0xdc
  kernel: SyS_epoll_wait+0x2ec/0x3b4
  kernel: SyS_epoll_pwait+0xc8/0x140
  kernel: __sys_trace+0x6c/0x6c
  native: #00 pc 00000000000712e0  /system/lib64/libc.so (__epoll_pwait+8)
  native: #01 pc 00000000000141c0  /system/lib64/libutils.so (android::Looper::pollInner(int)+144)
  native: #02 pc 000000000001408c  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+60)
  native: #03 pc 000000000012c7cc  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
  at android.os.MessageQueue.nativePollOnce(Native method)
  at android.os.MessageQueue.next(MessageQueue.java:326)
  at android.os.Looper.loop(Looper.java:181)
  at android.app.ActivityThread.main(ActivityThread.java:6981)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```
Please let me know if you need more information related to this issue.
Thank you.
