### ISSUE TITLE
SecurityException when loading thumbnail on some devices

### ISSUE THREAD

**Issue by dbarwacz** [bumptech/glide#3504]
Glide: 4.8.0
Integration: irrelevant (local image)
Device: some samsungs

We use glide to load preview from image selected using system picker. On some samsungs, it causes SecurityException, as apparently app does not have access to thumbnail of an image. 
Actual resource uri is accessible, as we are still able to upload it. 

We've migrated from picasso recently. We've had same issues with Picasso. Glide seemed to work ok, but apparently not on all devices. 

How can we skip request for thumbnail? 
Is it configurable?

**Comment by joimxjtuse** [comment]
Show exception log may help to solve the problem.

**Comment by dbarwacz** [comment]
Sure, here it is: 
```
E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/thumbnails from pid=16105, uid=10259 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:641)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:507)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:218)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
        at android.os.Binder.execTransact(Binder.java:682)
2019-01-28 11:37:28.453 16105-21839/com.hidden.app E/LocalConsoleLoggingManager: Not uploading exceptions encountered in debug builds:
    java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/thumbnails from pid=16105, uid=10259 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
        at android.os.Parcel.readException(Parcel.java:1967)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
        at android.content.ContentResolver.query(ContentResolver.java:760)
        at android.content.ContentResolver.query(ContentResolver.java:710)
        at android.content.ContentResolver.query(ContentResolver.java:668)
        at com.bumptech.glide.load.data.mediastore.ThumbFetcher$ImageThumbnailQuery.query(ThumbFetcher.java:158)
        at com.bumptech.glide.load.data.mediastore.ThumbnailStreamOpener.getPath(ThumbnailStreamOpener.java:93)
        at com.bumptech.glide.load.data.mediastore.ThumbnailStreamOpener.open(ThumbnailStreamOpener.java:71)
        at com.bumptech.glide.load.data.mediastore.ThumbFetcher.openThumbInputStream(ThumbFetcher.java:71)
        at com.bumptech.glide.load.data.mediastore.ThumbFetcher.loadData(ThumbFetcher.java:58)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
```

**Comment by krsoaiheim** [comment]
I have the same problem

**Comment by dbarwacz** [comment]
I think (and tests confirm that) everyone without 'storage read' permission
is affected on one device or another. I'll look around for a workaround
when I have some time in the coming weeks.

**Comment by sjudd** [comment]
You'll need to get the read storage permission for your app to load images from media store. How would you like Glide to help you here?

**Comment by dbarwacz** [comment]
That's not true @sjudd because I'm granted temporary access by picker activity ('We use glide to load preview from image selected using system picker') which is confirmed as I can access resource directly ('Actual resource uri is accessible, as we are still able to upload it'). Only glide attempts to load thumbnail that apparently has system-specific bugs.

**Comment by sjudd** [comment]
Got it thanks for clarifying. 

So you have Uri permissions for content://media/external/images/media/<N> but accessing the equivalent thumbnail with content://media/external/images/thumbnails/<N> fails.

**Comment by sjudd** [comment]
Internal issue is b/126712454, but we can work around this in Glide without a framework change.
