### ISSUE TITLE
Glide v3.8.0 load image sometimes mistakes occur.

### ISSUE THREAD

**Issue by hansionit** [bumptech/glide#3507]
**Glide Version**:3.8.0

**Integration libraries**:okhttp:3.9.0

**Device/Android Version**:Google Pixel Android 9   / ZUK Z2 Android 7.0

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
public class GlideConfiguration extends OkHttpGlideModule {
 
    ...

    @Override
    public void applyOptions(final Context context, GlideBuilder builder) {

        builder.setDiskCache(new DiskCache.Factory() {
            @Override
            public DiskCache build() {
                return getDiskCache(context);
            }
        });

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_8888);
        }
    }

    ....
}



 Glide
                .with(context)
                .load(imageUrl)
                .asBitmap()
                .crossFade()
                .listener(new RequestListener<String, Bitmap>() {
                    @Override
                    public boolean onException(Exception e, String model, Target<Bitmap> target, boolean isFirstResource) {
                        LogHandler.d("onException",e.getMessage() + ","+imageUrl);
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(Bitmap resource, String model, Target<Bitmap> target, boolean isFromMemoryCache, boolean isFirstResource) {
                        return false;
                    }
                })
                .format(DecodeFormat.PREFER_RGB_565)
                .into(imageView);
```

**Layout XML**:
```xml
 <ImageView
            android:id="@+id/thumb"
            android:layout_width="match_parent"
            android:layout_height="200dp"
            android:scaleType="fitXY" />
```

**Stack trace / LogCat**:
```ruby

    03-01 10:16:50.116 18365-19214/com.hansion.app W/BitmapFactory: bitmap marked for reuse (545664bytes) can't fit new bitmap (1091328 bytes)
            03-01 10:16:50.124 18365-18365/com.hansion.app W/System.err: java.lang.IllegalArgumentException: Problem decoding into existing bitmap
    03-01 10:16:50.124 18365-18365/com.hansion.app W/System.err:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:735)
            03-01 10:16:50.124 18365-18365/com.hansion.app W/System.err:     at com.networkbench.agent.impl.instrumentation.NBSBitmapFactoryInstrumentation.decodeStream(SourceFile:88)
            03-01 10:16:50.124 18365-18365/com.hansion.app W/System.err:     at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:329)
            03-01 10:16:50.124 18365-18365/com.hansion.app W/System.err:     at com.bumptech.glide.load.resource.bitmap.Downsampler.downsampleWithSize(Downsampler.java:220)
            03-01 10:16:50.124 18365-18365/com.hansion.app W/System.err:     at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:153)
            03-01 10:16:50.124 18365-18365/com.hansion.app W/System.err:     at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:50)
            03-01 10:16:50.124 18365-18365/com.hansion.app W/System.err:     at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
            03-01 10:16:50.124 18365-18365/com.hansion.app W/System.err:     at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:39)
            03-01 10:16:50.124 18365-18365/com.hansion.app W/System.err:     at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)
            03-01 10:16:50.124 18365-18365/com.hansion.app W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:190)
            03-01 10:16:50.124 18365-18365/com.hansion.app W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
            03-01 10:16:50.125 18365-18365/com.hansion.app W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
            03-01 10:16:50.125 18365-18365/com.hansion.app W/System.err:     at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:127)
            03-01 10:16:50.125 18365-18365/com.hansion.app W/System.err:     at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:106)
            03-01 10:16:50.125 18365-18365/com.hansion.app W/System.err:     at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
            03-01 10:16:50.125 18365-18365/com.hansion.app W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
            03-01 10:16:50.125 18365-18365/com.hansion.app W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            03-01 10:16:50.125 18365-18365/com.hansion.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
            03-01 10:16:50.125 18365-18365/com.hansion.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
            03-01 10:16:50.125 18365-18365/com.hansion.app W/System.err:     at java.lang.Thread.run(Thread.java:764)
            03-01 10:16:50.125 18365-18365/com.hansion.app W/System.err:     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)

```

I set default DecodeFormat is PREFER_ARGB_8888.

but When I load with  .format(DecodeFormat.PREFER_RGB_565) ,sometimes mistakes occur.

url:https://d.ifengimg.com/w696_h392_q100_webp/p0.ifengimg.com/pmop/2018/0124/E13D8ED46B6E4C4DA8FC6F6C2748B9B486279A4F_size330_w658_h370.png.webp

width:696,height:392

"bitmap marked for reuse (545664bytes) can't fit new bitmap (1091328 bytes)",I think sometimes this setting is invalid.Sometimes it still uses PREFER_ARGB_8888 to load.

when I load with .format(DecodeFormat.PREFER_ARGB_8888) ,Errors will not happen again.But Sometimes I need to use .format(DecodeFormat.PREFER_RGB_565) to load image.
Please help me solve this problem.Thanks!

I loading image on RecyclerView,Sometimes mistakes occur when sliding upwards.

**Comment by hansionit** [comment]
Could you help me?
