### ISSUE TITLE
NPE on low memory

### ISSUE THREAD

**Issue by matthewmichihara** [bumptech/glide#351]
Ran into the following a few times --

```java
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.bumptech.glide.RequestManager.onLowMemory()' on a null object reference
       at com.bumptech.glide.manager.SupportRequestManagerFragment.onLowMemory(SupportRequestManagerFragment.java:72)
       at android.support.v4.app.Fragment.performLowMemory(Fragment.java:1848)
       at android.support.v4.app.FragmentManagerImpl.dispatchLowMemory(FragmentManager.java:1976)
       at android.support.v4.app.Fragment.performLowMemory(Fragment.java:1850)
       at android.support.v4.app.FragmentManagerImpl.dispatchLowMemory(FragmentManager.java:1976)
       at android.support.v4.app.Fragment.performLowMemory(Fragment.java:1850)
       at android.support.v4.app.FragmentManagerImpl.dispatchLowMemory(FragmentManager.java:1976)
       at android.support.v4.app.FragmentActivity.onLowMemory(FragmentActivity.java:342)
       at android.app.ActivityThread.handleLowMemory(ActivityThread.java:4191)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

Unfortunately, I don't have a deterministic way to reproduce. This occurred on my 1st generation Moto G, Lollipop 5.0.1. I'm using Glide version 3.5.1. Let me know if there's other info I can provide.

**Comment by matthewmichihara** [comment]
Ah sorry I just saw https://github.com/bumptech/glide/issues/329, upgrading to 3.5.2 and closing.
