### ISSUE TITLE
Crash in StrictMode

### ISSUE THREAD

**Issue by Harlber** [bumptech/glide#3521]
Is this a bug in Glide or okhttp
 ```java
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'response.body().close()' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:223)
        at java.lang.reflect.Method.invoke(Native Method)
        at okhttp3.internal.platform.AndroidPlatform$CloseGuard.createAndOpen(AndroidPlatform.java:343)
        at okhttp3.internal.platform.AndroidPlatform.getStackTraceForCloseable(AndroidPlatform.java:158)
        at okhttp3.RealCall.captureCallStackTrace(RealCall.java:89)
        at okhttp3.RealCall.enqueue(RealCall.java:98)
        at com.gx.util.glide.OkHttpStreamFetcher.loadData(OkHttpStreamFetcher.java:70)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
```
 - I saw someone raised a similar issue before. #2594   #3403 
 - see [issue in OkHttp](https://github.com/square/okhttp/issues/4607)
 - And what should we do with this issue.

**Comment by sjudd** [comment]
It looks like you're using your own custom integration with OkHttp? If so, you'll need to make sure you close the response body. There's an open issue in Glide where this is logged that I've been unable to reproduce: #3403. If you've just copy/pasted Glide's implementation into your package, you can dupe this against that issue.

**Comment by Harlber** [comment]
@sjudd Thanks a lot
