### ISSUE TITLE
java.net.ProtocolException: unexpected end of stream

### ISSUE THREAD

**Issue by josemontiel** [bumptech/glide#354]
Hello, I've been having the following issue:

**Glide Version/Integration library (if any)**: 3.5.2
**Device/Android Version**: 5.0
**Issue details/Repro steps**:

Loading either image or gif from server.

**Implementation**:
```
Glide.with(this).load(imgUrl).fitCenter()
                    .into(new GlideDrawableImageViewTarget(imgView) {
                        @Override
                        public void onResourceReady(GlideDrawable drawable, GlideAnimation anim) {
                            super.onResourceReady(drawable, anim);
                            progressBar.setVisibility(View.GONE);
                        }
                    });

```

**Stack trace**:
```


java.net.ProtocolException: unexpected end of stream
            at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:445)
            at com.android.okio.RealBufferedSource.exhausted(RealBufferedSource.java:58)
            at com.android.okio.GzipSource.read(GzipSource.java:94)
            at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
            at java.io.InputStream.read(InputStream.java:162)
            at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:132)
            at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:309)
            at java.io.InputStream.read(InputStream.java:162)
            at com.bumptech.glide.load.resource.gif.GifResourceDecoder.inputStreamToBytes(GifResourceDecoder.java:105)
            at com.bumptech.glide.load.resource.gif.GifResourceDecoder.decode(GifResourceDecoder.java:57)
            at com.bumptech.glide.load.resource.gif.GifResourceDecoder.decode(GifResourceDecoder.java:26)
            at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeGifWrapper(GifBitmapWrapperResourceDecoder.java:101)
            at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeStream(GifBitmapWrapperResourceDecoder.java:87)
            at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:71)
            at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:61)
            at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:22)
            at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:190)
            at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
            at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
            at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
            at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
            at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
            at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:52)
```

**Comment by sjudd** [comment]
Does this cause a crash? If not it looks like an expected exception if you're on a less than perfect network or your server occasionally fails to complete requests.

**Comment by josemontiel** [comment]
First of all, thank you for such fast reply and your help, Sam.

Indeed this doesn't cause a crash. Despite the exception being thrown, the images seem to load the second time around (from cache?).

As far as the server goes, the requests are completed successfully when called from Chrome or the iOS client.

Once again, I appreciate your help.

**Comment by sjudd** [comment]
Do the images always fail to load at least once? Or is it some images some of the time? It also looks like you're using the OkHttp integration library? My first thought is still that it might be a connectivity issue if it is intermittent. If not, it may be an issue with OkHttp or your perhaps your request headers?

It looks like the failure is here: https://github.com/square/okhttp/blob/b4a9de148766daf970ec38564156f95b3830e16c/okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpConnection.java#L383, which seems to imply your server is returning an incorrect content length.

Another thing you might try is seeing if this is reproducible using Glide's default http library or Volley. Particularly if you do so pre-KitKat, you may be able to narrow this down to an issue with OkHttp and/or your request headers.

The logic in Glide is relatively simple, we're just fully reading the input stream into a byte array, so it seems unlikely to be an issue with Glide itself. It's possible there's an option we are or aren't setting in the OkHttp integration library though.

**Comment by josemontiel** [comment]
Although I am still looking where the issue lies, I think you are right, I managed to get it working by implementing a GlideModule, based on the OkHttp module, using Apache's HttpClient.

Thank you very much for your help @sjudd .

**Comment by kalpanaliu** [comment]
@JOSE for this issue, have you solved it? 
Can you share your solution?

Thanks

**Comment by Sugarya** [comment]
So bad, I meet the same issue today...
