### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by 654277633** [bumptech/glide#3549]
glide version : 4.8.0 
okhttp version : 3.12.1
Operating System : 4.2.1

log by fabric:

Fatal Exception: java.lang.OutOfMemoryError
       at android.graphics.BitmapFactory.nativeDecodeAsset(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:521)
       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:374)
       at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:785)
       at android.content.res.Resources.loadDrawable(Resources.java:2005)
       at android.content.res.Resources.getDrawable(Resources.java:673)
       at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:465)
       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:203)
       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
       at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:102)
       at com.bumptech.glide.load.resource.drawable.DrawableDecoderCompat.loadDrawableV7(DrawableDecoderCompat.java:70)
       at com.bumptech.glide.load.resource.drawable.DrawableDecoderCompat.getDrawable(DrawableDecoderCompat.java:50)

**Comment by sjudd** [comment]
See http://bumptech.github.io/glide/doc/debugging.html#out-of-memory-errors
