### ISSUE TITLE
Glide Engine NPE when running test with Roboelectric.

### ISSUE THREAD

**Issue by danysantiago** [bumptech/glide#355]
Hi, I've been successfully using Glide in our application but I'm starting to run into some trouble with our test suite. We use Robolectric 2.4 for our Android testing and Glide calls usually respond well, but lately I've started to notice the following NPE in the engine which in turns causes some tests to fail. The curious situation is that the NPE occurs asynchronously, which we noticed because the failing test are not related to Glide calls and because they occur on one of the fifo-threads. Any tips and help would be awesome.

**Glide Version/Integration library (if any)**: 3.5.2
**Device/Android Version**: Robolectric

**Glide load line**:
```
Glide.with(getContext())
        .load(albumArtUrl)
        .placeholder(R.drawable.empty_art)
        .into(holder.albumArt);
```

**Stack trace**:
```
java.lang.NullPointerException
	at com.bumptech.glide.load.engine.Engine.getReferenceQueue(Engine.java:300)
	at com.bumptech.glide.load.engine.Engine.onEngineJobComplete(Engine.java:263)
	at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:153)
	at com.bumptech.glide.load.engine.EngineJob.access$100(EngineJob.java:22)
	at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:202)
	at org.robolectric.shadows.ShadowHandler.routeMessage(ShadowHandler.java:123)
	at org.robolectric.shadows.ShadowHandler.access$100(ShadowHandler.java:25)
	at org.robolectric.shadows.ShadowHandler$1.run(ShadowHandler.java:110)
	at org.robolectric.util.Scheduler$PostedRunnable.run(Scheduler.java:162)
	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:107)
	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:92)
	at org.robolectric.util.Scheduler.advanceToLastPostedRunnable(Scheduler.java:68)
	at org.robolectric.util.Scheduler.unPause(Scheduler.java:25)
	at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:228)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:267)
	at org.robolectric.shadows.ShadowViewGroup.addView(ShadowViewGroup.java:32)
	at android.view.ViewGroup.addView(ViewGroup.java)
	at android.view.ViewGroup.addView(ViewGroup.java:3353)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
```

**Comment by sjudd** [comment]
The problem area is here: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/engine/Engine.java#L300. 

I'd imagine that Looper.myQueue() is returning null. Although there isn't an explicitly assertion, it's assumed that ``getReferenceQueue()`` is called on the main thread. Are your tests testing load calls on background threads? Glide also uses Robolectric (for example: https://github.com/bumptech/glide/blob/master/library/src/androidTest/java/com/bumptech/glide/GlideTest.java) and I have yet to see this.

If you can provide a small test that reproduces the problem I can probably do better at suggesting a workaround for Robolectric (or fixing a bug in Glide if it's possible for ``getReferenceQueue()`` to be called on a background thread)?

**Comment by danysantiago** [comment]
Looking at GlideTest.java I was able to better mock and test Glide usage, for now I'm no longer seeing this problem. Thanks!
