### ISSUE TITLE
Glide loading network resource from disk cache executor. Glide 4.9.0

### ISSUE THREAD

**Issue by bitsydarel** [bumptech/glide#3586]
We have some issue in our release build, strangly our debug build is working fine.
We don't use proguard so i dont understand why the behavior is different.

We can't load images from network, because glide seems to be doing network call on the disk cache executor.

Stacktrace:
2019-03-27 23:03:12.555 21491-21720/? E/GlideExecutor: Request threw uncaught throwable
    java.lang.RuntimeException: StrictMode ThreadPolicy violation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onThreadPolicyViolation(StrictMode.java:1705)
        at android.os.StrictMode$AndroidBlockGuardPolicy.handleViolationWithTimingAttempt(StrictMode.java:1562)
        at android.os.StrictMode$AndroidBlockGuardPolicy.startHandlingViolationException(StrictMode.java:1533)
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1518)
        at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:415)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:527)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.java:385)
        at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.java:471)
        at okhttp3.internal.Util.skipAll(Util.java:204)
        at okhttp3.internal.Util.discard(Util.java:186)
        at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.close(Http1ExchangeCodec.java:507)
        at okio.ForwardingSource.close(ForwardingSource.java:43)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.close(Exchange.java:313)
        at okio.RealBufferedSource.close(RealBufferedSource.java:476)
        at okio.RealBufferedSource.close(RealBufferedSource.java:476)
        at okio.InflaterSource.close(InflaterSource.java:127)
        at okio.GzipSource.close(GzipSource.java:182)
        at okio.RealBufferedSource.close(RealBufferedSource.java:476)
        at okio.RealBufferedSource$1.close(RealBufferedSource.java:460)
        at java.io.FilterInputStream.close(FilterInputStream.java:181)
        at com.bumptech.glide.integration.okhttp3.OkHttpStreamFetcher.cleanup(OkHttpStreamFetcher.java:81)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:472)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:418)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:282)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
     Caused by: android.os.strictmode.NetworkViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1518) 
        at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:415) 
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:527) 
        at okio.Okio$2.read(Okio.java:140) 
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) 
        at okio.RealBufferedSource.read(RealBufferedSource.java:51) 
        at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.java:385) 
        at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.java:471) 
        at okhttp3.internal.Util.skipAll(Util.java:204) 
        at okhttp3.internal.Util.discard(Util.java:186) 
        at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.close(Http1ExchangeCodec.java:507) 
        at okio.ForwardingSource.close(ForwardingSource.java:43) 
        at okhttp3.internal.connection.Exchange$ResponseBodySource.close(Exchange.java:313) 
        at okio.RealBufferedSource.close(RealBufferedSource.java:476) 
        at okio.RealBufferedSource.close(RealBufferedSource.java:476) 
        at okio.InflaterSource.close(InflaterSource.java:127) 
        at okio.GzipSource.close(GzipSource.java:182) 
        at okio.RealBufferedSource.close(RealBufferedSource.java:476) 
        at okio.RealBufferedSource$1.close(RealBufferedSource.java:460) 
        at java.io.FilterInputStream.close(FilterInputStream.java:181) 
        at com.bumptech.glide.integration.okhttp3.OkHttpStreamFetcher.cleanup(OkHttpStreamFetcher.java:81) 
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:472) 
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:418) 
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:282) 
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446) 

the line causing the crash:

https://github.com/bumptech/glide/blob/4b26d774fa4c5d6b5332c732a51a92eaeb1ee8b9/library/src/main/java/com/bumptech/glide/load/engine/executor/GlideExecutor.java#L438

**Comment by bitsydarel** [comment]
@sjudd this issue is blocking us from releasing our app with bugfixing

**Comment by bitsydarel** [comment]
Tested the same issue is happening on 4.8.0.
we have a multi module project.

**Comment by bitsydarel** [comment]
Commenting this line of our AppGlide module made the image loading.
    override fun applyOptions(context: Context, builder: GlideBuilder) {
//        builder.setDefaultRequestOptions(
//            RequestOptions()
//                .diskCacheStrategy(DiskCacheStrategy.AUTOMATIC)
//                .theme(context.theme)
//                .useAnimationPool(true)
//        ).setLogLevel(if (BuildConfig.DEBUG) Log.VERBOSE else Log.ERROR)
    }

why would this affect which executor the library use?

**Comment by bitsydarel** [comment]
@sjudd please take a look into that, when you will be available or any other maintainer of the library.
