### ISSUE TITLE
Canvas: trying to use a recycled bitmap, Glide 4.9.0

### ISSUE THREAD

**Issue by alexeyselina** [bumptech/glide#3594]
Happens only on Samsung devices (S5, S6 edge) with Marshmallow OS (according to analytics. I cannot reproduce it)

Don't know the proper place, but all calls are simple like:

GlideApp.with(context)
                .load(imgUrl)
                .centerCrop()
                .dontAnimate()
                .into(imgListing);

I have one place (in BitmapTransformation for glide's .transform() ) in application where I do bitmap.recycle() - can it be the problem?

Stacktrace:
Fatal Exception: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@6424232
at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1301)
at android.graphics.Canvas.drawBitmap(Canvas.java:1435)
at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:551)
at android.graphics.drawable.DrawableContainer.draw(DrawableContainer.java:81)
at android.widget.ImageView.onDraw(ImageView.java:1252)
at android.view.View.draw(View.java:17469)
at android.view.View.updateDisplayListIfDirty(View.java:16464)
at android.view.View.draw(View.java:17238)
at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
at android.view.View.updateDisplayListIfDirty(View.java:16459)
at android.view.View.draw(View.java:17238)
at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
at android.view.View.draw(View.java:17472)
at android.view.View.updateDisplayListIfDirty(View.java:16464)
at android.view.View.draw(View.java:17238)
at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
at android.view.View.draw(View.java:17472)
at android.support.design.widget.TabLayout$SlidingTabStrip.draw(TabLayout.java:2034)
at android.view.View.updateDisplayListIfDirty(View.java:16464)
at android.view.View.draw(View.java:17238)
at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
at android.view.View.draw(View.java:17472)
at android.widget.HorizontalScrollView.draw(HorizontalScrollView.java:2216)
at android.view.View.updateDisplayListIfDirty(View.java:16464)
at android.view.View.draw(View.java:17238)
at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
at android.view.View.updateDisplayListIfDirty(View.java:16459)
at android.view.View.draw(View.java:17238)
at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
at android.view.View.draw(View.java:17472)
at android.support.v4.widget.NestedScrollView.draw(NestedScrollView.java:1819)
at android.view.View.updateDisplayListIfDirty(View.java:16464)
at android.view.View.draw(View.java:17238)
at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1254)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
at android.view.View.draw(View.java:17472)
at android.view.View.updateDisplayListIfDirty(View.java:16464)
at android.view.View.draw(View.java:17238)
at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
at android.view.View.updateDisplayListIfDirty(View.java:16459)
at android.view.View.draw(View.java:17238)
at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
at android.view.View.draw(View.java:17472)
at android.support.v4.view.ViewPager.draw(ViewPager.java:2420)
at android.view.View.updateDisplayListIfDirty(View.java:16464)
at android.view.View.draw(View.java:17238)
at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
at android.view.View.updateDisplayListIfDirty(View.java:16459)
at android.view.View.draw(View.java:17238)
at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
at android.view.View.updateDisplayListIfDirty(View.java:16459)
at android.view.View.draw(View.java:17238)
at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
at android.view.View.updateDisplayListIfDirty(View.java:16459)
at android.view.View.draw(View.java:17238)
at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
at android.view.View.updateDisplayListIfDirty(View.java:16459)
at android.view.View.draw(View.java:17238)
at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
at android.view.View.updateDisplayListIfDirty(View.java:16459)
at android.view.View.draw(View.java:17238)
at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
at android.view.View.draw(View.java:17472)
at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:3205)
at android.view.View.updateDisplayListIfDirty(View.java:16464)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:3134)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2933)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2522)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
at android.view.Choreographer.doCallbacks(Choreographer.java:695)
at android.view.Choreographer.doFrame(Choreographer.java:631)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7229)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by sjudd** [comment]
http://bumptech.github.io/glide/doc/resourcereuse.html#common-errors

**Comment by joimxjtuse** [comment]
Your logs do not help to solve the exception,

**Comment by sjudd** [comment]
I missed that you said you're calling Bitmap.recycle. that can be
problematic, check out the javadoc for BitmapTransformation or the docs
site page on transformations as well.

Sam

**Comment by 18722650553** [comment]
I missed this error!

**Comment by MomenZaq** [comment]
**Use this custom ImageView class**


```
    public class MyImageView extends ImageView {
     
    	public MyImageView(Context context, AttributeSet attrs, int defStyle) {
    		super(context, attrs, defStyle);
    	}
     
    	public MyImageView(Context context, AttributeSet attrs) {
    		super(context, attrs);
    	}
     
    	public MyImageView(Context context) {
    		super(context);
    	}
     
    	@Override
    	protected void onDraw(Canvas canvas) {
    		try {
    			super.onDraw(canvas);
    		} catch (Exception e) {
    			Log.i(MyImageView.class.getSimpleName(), "Catch Canvas: trying to use a recycled bitmap");
    		}
    	}
     
    }
```
