### ISSUE TITLE
RuntimeException: Canvas: trying to use a recycled bitmap 

### ISSUE THREAD

**Issue by van11** [bumptech/glide#360]
Hi,

not sure why I am getting a lot of there errors?

```
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@4503a610
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1084)
       at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:844)
       at com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable.draw(GlideBitmapDrawable.java:101)
       at com.bumptech.glide.request.target.SquaringDrawable.draw(SquaringDrawable.java:137)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:208)
       at android.widget.ImageView.onDraw(ImageView.java:1019)
       at android.view.View.draw(View.java:14596)
       at android.view.View.getDisplayList(View.java:13493)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.View.draw(View.java:14313)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13488)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.View.draw(View.java:14313)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13488)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.View.draw(View.java:14313)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13488)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.View.draw(View.java:14313)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.widget.ListView.drawChild(ListView.java:3363)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.widget.AbsListView.dispatchDraw(AbsListView.java:2465)
       at android.widget.ListView.dispatchDraw(ListView.java:3358)
       at android.view.View.draw(View.java:14599)
       at android.widget.AbsListView.draw(AbsListView.java:3824)
       at android.view.View.getDisplayList(View.java:13493)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.View.draw(View.java:14313)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.getDisplayList(View.java:13488)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.View.draw(View.java:14313)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14599)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:13493)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13431)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13431)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13431)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13431)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.View.draw(View.java:14313)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14599)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:13493)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13431)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13431)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13431)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
       at android.view.View.getDisplayList(View.java:13431)
       at android.view.View.getDisplayList(View.java:13535)
       at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2381)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2253)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1883)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5610)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:212)
       at android.app.ActivityThread.main(ActivityThread.java:5137)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Transformation:

```
public class CircleTransformation<T> extends BitmapTransformation {

    public static final String GLIDE_CIRCLE_TRANSFORMATION = "Glide_Circle_Transformation";
    private int x, y;
    private T id;

    public CircleTransformation(BitmapPool bitmapPool, T id) {
        super(bitmapPool);
        this.id = id;
    }

    public CircleTransformation(Context context, T id) {
        super(context);
        this.id = id;
    }

    @Override
    protected Bitmap transform(BitmapPool pool, Bitmap original, int outWidth, int outHeight) {
        x = outWidth;
        y = outHeight;
        Bitmap result = pool.get(outWidth, outHeight, Bitmap.Config.ARGB_8888);
        int size = Math.min(original.getWidth(), original.getHeight());

        if (result == null) {
            result = Bitmap.createBitmap(outWidth, outHeight, Bitmap.Config.ARGB_8888);
        }

        Paint paint = new Paint();
        BitmapShader shader = new BitmapShader(original, BitmapShader.TileMode.CLAMP, BitmapShader.TileMode.CLAMP);
        paint.setShader(shader);
        paint.setAntiAlias(true);

        Paint borderStrokePaint = new Paint();
        borderStrokePaint.setStyle(Paint.Style.STROKE);
        borderStrokePaint.setAntiAlias(true);
        borderStrokePaint.setColor(Color.WHITE);
        borderStrokePaint.setStrokeWidth(3);

        Canvas canvas = new Canvas(result);
        float r = size / 2f;
        float r1 = (size - 2) / 2f;
        canvas.drawCircle(r, r, r, paint);
        canvas.drawCircle(r, r, r1, borderStrokePaint);

        return result;
    }

    @Override
    public String getId() {
        return GLIDE_CIRCLE_TRANSFORMATION + id + x + y;
    }
}
```
Method where transformation is used:

```
 public <T> void displayAvatar(T resource, final ImageView view, @DrawableRes int placeholderResource, final ImageLoaderListener callBackListener) {
        requestManager
            .load(resource)
            .diskCacheStrategy(DiskCacheStrategy.RESULT)
            .thumbnail(requestManager.load(placeholderResource).transform(
                new FitCenter(glideInstance.getBitmapPool()),
                new CircleTransformation(glideInstance.getBitmapPool(), placeholderResource)))
            .transform(
                new FitCenter(glideInstance.getBitmapPool()),
                new CircleTransformation(glideInstance.getBitmapPool(), resource))
            .crossFade()
            .listener(new RequestListener<T, GlideDrawable>() {
                @Override
                public boolean onException(Exception e, T model, Target<GlideDrawable> target, boolean isFirstResource) {
                    if (callBackListener != null) {
                        callBackListener.onLoadingFailed(e);
                    }
                    return false;
                }

                @Override
                public boolean onResourceReady(GlideDrawable resource, T model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                    if (callBackListener != null) {
                        callBackListener.onLoadingCompleted();
                    }
                    return false;
                }
            })
            .into(new GlideDrawableImageViewTarget(view) {
                @Override
                public void onLoadStarted(Drawable placeholder) {
                    super.onLoadStarted(placeholder);
                    if (callBackListener != null) {
                        callBackListener.onLoadingStarted(placeholder);
                    }
                }
            });
    }
```

Transformation looks like is made by documentation:
https://github.com/bumptech/glide/wiki/Transformations#bitmap-re-use

Maybe it is related to thumbnail loading and `.crossFade()`? Because I can not found any clues why this is happening... Also not sure how to reproduce, stacktrace comes from production app. Looks like I am doing something wrong.

Looking forward for this.

**Comment by sjudd** [comment]
It's possible that this was fixed here: https://github.com/bumptech/glide/commit/a9f80ea1a5a5c3576feb3b58e38240b597cc586f. Can you try the latest snapshot and see if that fixes the issue?

The repro case would be very racy, but I'd guess either disabling the BitmapPool entirely or providing a pool with a small size would make it much more common.

**Comment by van11** [comment]
OK, thanks, will try.

**Comment by van11** [comment]
No luck in reproducing it, but replacing `.crossFade` to view animation which simulates cross fade effect helped. Suggest to close this :) Thanks!

**Comment by sjudd** [comment]
Just to double check, did you try with the snapshot version with the commit I mentioned? Or not? Just want to check to see if there's still something we need to fix.

**Comment by van11** [comment]
No, I just removed `.crossFade`. After you release next version I will try again with `.crossFade` enabled and let you know if it works correctly.
