### ISSUE TITLE
NPE when using crossFade transition

### ISSUE THREAD

**Issue by ArmChilingarov** [bumptech/glide#3635]
Throws npe when using transition(withCrossfade()) function

it crashes on Glide version 4.7.1 , i updated to 4.9.0  and it still crashes.

fails on Sony E2312  And Asus Z010DD
**Device/Android Version**:
Asus api level 23
Sony api level 21

Here is code
GlideApp.with(viewHolder.itemView.context).`as`(PictureDrawable::class.java)
                    .load(partnersLogo[item.partner])
                    .transition(DrawableTransitionOptions.withCrossFade())
                    .listener(SvgSoftwareLayerSetter())
                    .into(taskViewHolder.iconImageView)

and stacktrace

05-02 18:47:43.066 19278-19278/io.techbuddy.buddy E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.techbuddy.buddy, PID: 19278
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable()' on a null object reference
        at android.graphics.drawable.LayerDrawable$ChildDrawable.<init>(LayerDrawable.java:968)
        at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:1014)
        at android.graphics.drawable.TransitionDrawable$TransitionState.<init>(TransitionDrawable.java:250)
        at android.graphics.drawable.TransitionDrawable.createConstantState(TransitionDrawable.java:102)
        at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:932)
        at android.widget.ImageView.applyImageTint(ImageView.java:521)
        at android.widget.ImageView.updateDrawable(ImageView.java:821)
        at android.widget.ImageView.setImageDrawable(ImageView.java:451)
        at android.support.v7.widget.AppCompatImageView.setImageDrawable(AppCompatImageView.java:100)
        at com.bumptech.glide.request.target.ImageViewTarget.setDrawable(ImageViewTarget.java:56)
        at com.bumptech.glide.request.transition.DrawableCrossFadeTransition.transition(DrawableCrossFadeTransition.java:57)
        at com.bumptech.glide.request.transition.DrawableCrossFadeTransition.transition(DrawableCrossFadeTransition.java:15)
        at com.bumptech.glide.request.target.ImageViewTarget.onResourceReady(ImageViewTarget.java:103)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:579)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:549)
        at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:218)
        at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:324)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5319)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by jonakyd** [comment]
+1
