### ISSUE TITLE
com.github.bumptech.glide:glide:4.9.0  exclude group: "com.android.support" crash！！！

### ISSUE THREAD

**Issue by chichengjunma** [bumptech/glide#3638]
There is no problem with using the 4.7.1, but when you use the 4.9.0, the specific crash information is as follows:

Process: com.xxx.xxx, PID: 11496
    java.lang.NoClassDefFoundError: com.bumptech.glide.load.resource.gif.GifDrawable
        at com.bumptech.glide.Glide.<init>(Glide.java:413)
        at com.bumptech.glide.GlideBuilder.build(GlideBuilder.java:509)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:268)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:223)
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:184)
        at com.bumptech.glide.Glide.get(Glide.java:168)
        at com.bumptech.glide.Glide.getRetriever(Glide.java:689)
        at com.bumptech.glide.Glide.with(Glide.java:741)
        at com.xxx.xxx.utils.BitmapUtil.getManager(BitmapUtil.java:97)
        at com.xxx.xxx.utils.BitmapUtil.displayImage(BitmapUtil.java:249)
        at com.xxx.xxx.adapter.MainMenuAdapter.onBindViewHolder(MainMenuAdapter.java:634)
        at com.xxx.xxx.adapter.MainMenuAdapter.onBindViewHolder(MainMenuAdapter.java:72)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5069)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5088)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5389)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5292)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1391)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:894)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:865)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:334)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:2031)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:1946)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2234)
        at android.view.View.layout(View.java:14817)

**Comment by chichengjunma** [comment]
why close？

**Comment by chichengjunma** [comment]
why close？  waiting

**Comment by sjudd** [comment]
This is some kind of build issue with your application I think. If the aar were corrupt other people would be reporting the same issue.
