### ISSUE TITLE
RejectedExecutionException

### ISSUE THREAD

**Issue by ice45571** [bumptech/glide#3668]
Glide 4.6.1
#0. Crashed: OkHttp Dispatcher
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2078)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:843)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1389)
       at com.bumptech.glide.load.engine.executor.GlideExecutor.execute(GlideExecutor.java:268)
       at com.bumptech.glide.load.engine.EngineJob.reschedule(EngineJob.java:273)
       at com.bumptech.glide.load.engine.DecodeJob.reschedule(DecodeJob.java:359)
       at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:110)
       at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:133)
       at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:133)
       at com.bumptech.glide.integration.okhttp3.OkHttpStreamFetcher.onResponse(OkHttpStreamFetcher.java:71)
       at com.google.firebase.perf.network.zzg.onResponse(zzg.java:22)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

--

Fatal Exception: java.util.concurrent.RejectedExecutionException: Task com.bumptech.glide.load.engine.DecodeJob@e9052aa rejected from java.util.concurrent.ThreadPoolExecutor@61f2e9b[Shutting down, pool size = 3, active threads = 3, queued tasks = 0, completed tasks = 6]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2078)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:843)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1389)
       at com.bumptech.glide.load.engine.executor.GlideExecutor.execute(GlideExecutor.java:268)
       at com.bumptech.glide.load.engine.EngineJob.reschedule(EngineJob.java:273)
       at com.bumptech.glide.load.engine.DecodeJob.reschedule(DecodeJob.java:359)
       at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:110)
       at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:133)
       at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:133)
       at com.bumptech.glide.integration.okhttp3.OkHttpStreamFetcher.onResponse(OkHttpStreamFetcher.java:71)
       at com.google.firebase.perf.network.zzg.onResponse(zzg.java:22)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Comment by ice45571** [comment]
like this  https://github.com/bumptech/glide/issues/3235

**Comment by ice45571** [comment]
![image](https://user-images.githubusercontent.com/21982940/58446982-63da2000-8135-11e9-92c2-9bb8ef968f94.png)

Is there any use to add a line of code like `if (!executor.isTerminated())` before execute a runnable?

**Comment by sjudd** [comment]
This error means you've exceeded the maximum queue size for the executor, which probably means you're trying to run too many requests at once.

Checking `isTerminated()` won't help.

**Comment by Abgaryan** [comment]
I am facing the same issue : 

```fun AppCompatImageView.loadUrl(url: String) {
    Glide
        .with(this)
        .applyDefaultRequestOptions(
            RequestOptions()
                .useUnlimitedSourceGeneratorsPool(true)
        )
        .load(url)
        .into(this)
}
```
Crash 

```    --------- beginning of crash
2020-04-29 13:10:31.921 12987-12987/ E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mobimeo.shellapp.sberlin.debug, PID: 12987
    java.util.concurrent.RejectedExecutionException: Task com.bumptech.glide.load.engine.DecodeJob@fa70388 rejected from java.util.concurrent.ThreadPoolExecutor@33f1f8d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 5]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
        at com.bumptech.glide.load.engine.executor.GlideExecutor.execute(GlideExecutor.java:220)
        at com.bumptech.glide.load.engine.EngineJob.start(EngineJob.java:131)
        at com.bumptech.glide.load.engine.Engine.waitForExistingOrStartNewJob(Engine.java:286)
        at com.bumptech.glide.load.engine.Engine.load(Engine.java:193)
        at com.bumptech.glide.request.SingleRequest.onSizeReady(SingleRequest.java:449)
        at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.notifyCbs(ViewTarget.java:352)
        at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.checkCurrentDimens(ViewTarget.java:368)
        at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer$SizeDeterminerLayoutListener.onPreDraw(ViewTarget.java:513)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2745)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:725)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by candyguy242** [comment]
I found a reason that may cause this exception，you can check that if you init your Glide more that once.
like: 

Glide.init(application,glideBuilder);

It must not be executed twice when you already load some image into image view.  the 'tearDown' method will shut down the previous executors, and lead to this exception.

`
synchronized (Glide.class) {
      if (Glide.glide != null) {
        tearDown();
      }
      initializeGlide(context, builder, annotationGeneratedModule);
    }
`

**Comment by wangxuejing** [comment]
Fatal Exception: java.util.concurrent.RejectedExecutionException: Task com.bumptech.glide.load.engine.DecodeJob@51e0984 rejected from java.util.concurrent.ThreadPoolExecutor@4c8756d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2085)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
       at com.bumptech.glide.load.engine.executor.GlideExecutor.execute(GlideExecutor.java:1)
       at com.bumptech.glide.load.engine.EngineJob.s(EngineJob.java:3)
       at com.bumptech.glide.load.engine.Engine.m(Engine.java:12)
       at com.bumptech.glide.load.engine.Engine.g(Engine.java:6)
       at com.bumptech.glide.request.SingleRequest.e(SingleRequest.java:24)
       at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.j(ViewTarget.java:2)
       at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.a(ViewTarget.java:5)
       at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer$SizeDeterminerLayoutListener.onPreDraw(ViewTarget.java:4)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:986)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3158)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1928)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8374)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090)
       at android.view.Choreographer.doCallbacks(Choreographer.java:902)
       at android.view.Choreographer.doFrame(Choreographer.java:834)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1076)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:962)

**Comment by Wizardp007** [comment]
> Glide 4.12.0
> 
> Fatal Exception: java.util.concurrent.RejectedExecutionException: Task com.bumptech.glide.load.engine.DecodeJob@e084844 rejected from java.util.concurrent.ThreadPoolExecutor@fcbca5f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1] at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086) at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848) at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394) at com.bumptech.glide.load.engine.executor.GlideExecutor.execute(GlideExecutor.java:1) at com.bumptech.glide.load.engine.EngineJob.s(EngineJob.java:3) at com.bumptech.glide.load.engine.Engine.m(Engine.java:12) at com.bumptech.glide.load.engine.Engine.g(Engine.java:6) at com.bumptech.glide.request.SingleRequest.e(SingleRequest.java:24) at com.bumptech.glide.request.target.CustomViewTarget$SizeDeterminer.d(CustomViewTarget.java:4) at com.bumptech.glide.request.target.CustomViewTarget.p(CustomViewTarget.java:1) at com.bumptech.glide.request.SingleRequest.i(SingleRequest.java:19) at com.bumptech.glide.manager.RequestTracker.h(RequestTracker.java:3) at com.bumptech.glide.RequestManager.Y(RequestManager.java:2) at com.bumptech.glide.RequestBuilder.j1(RequestBuilder.java:11) at com.bumptech.glide.RequestBuilder.k1(RequestBuilder.java:1) at com.bumptech.glide.RequestBuilder.i1(RequestBuilder.java:1) at com.heytap.browser.filemanager.imageload.FileImageLoader.o(FileImageLoader.kt:21) at com.heytap.browser.filemanager.imageload.FileImageLoader.p(FileImageLoader.kt:1) at com.heytap.browser.filemanager.imageload.FileImageLoader.j(FileImageLoader.kt:33) at com.heytap.browser.filemanager.imageload.FileImageLoader.m(FileImageLoader.kt:1) at com.heytap.browser.filemanager.imageload.FileImageLoader.i(FileImageLoader.kt:1) at com.heytap.browser.filemanager.category.audio.viewholders.RecentAudioGridViewHolder.C0(RecentAudioGridViewHolder.kt:15) at com.heytap.browser.filemanager.category.mediabase.BaseViewHolder.K0(BaseViewHolder.kt:3) at com.heytap.browser.filemanager.category.mediabase.BaseAdapter.l0(BaseAdapter.kt:2) at com.heytap.browser.filemanager.category.mediabase.BaseAdapter.onBindViewHolder(BaseAdapter.kt:1) at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:1) at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6) at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6) at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:55) at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:2) at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1) at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:3) at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:12) at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:9) at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:64) at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:3) at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:8) at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:9) at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2) at android.view.View.layout(View.java:23154) at android.view.ViewGroup.layout(ViewGroup.java:6497) at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12) at android.view.View.layout(View.java:23154) at android.view.ViewGroup.layout(ViewGroup.java:6497) at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12) at android.view.View.layout(View.java:23154) at android.view.ViewGroup.layout(ViewGroup.java:6497) at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12) at android.view.View.layout(View.java:23154) at android.view.ViewGroup.layout(ViewGroup.java:6497) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332) at android.widget.FrameLayout.onLayout(FrameLayout.java:270) at android.view.View.layout(View.java:23154) at android.view.ViewGroup.layout(ViewGroup.java:6497) at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:3) at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:31) at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:9) at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:64) at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:8) at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:9) at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2) at android.view.View.layout(View.java:23154) at android.view.ViewGroup.layout(ViewGroup.java:6497) at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:8) at android.view.View.layout(View.java:23154) at android.view.ViewGroup.layout(ViewGroup.java:6497) at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12) at android.view.View.layout(View.java:23154) at android.view.ViewGroup.layout(ViewGroup.java:6497) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332) at android.widget.FrameLayout.onLayout(FrameLayout.java:270) at android.view.View.layout(View.java:23154) at android.view.ViewGroup.layout(ViewGroup.java:6497) at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12) at android.view.View.layout(View.java:23154) at android.view.ViewGroup.layout(ViewGroup.java:6497) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332) at android.widget.FrameLayout.onLayout(FrameLayout.java:270) at android.view.View.layout(View.java:23154) at android.view.ViewGroup.layout(ViewGroup.java:6497) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332) at android.widget.FrameLayout.onLayout(FrameLayout.java:270) at android.view.View.layout(View.java:23154) at android.view.ViewGroup.layout(ViewGroup.java:6497) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332) at android.widget.FrameLayout.onLayout(FrameLayout.java:270) at com.heytap.browser.home.HomeFrame.O0(HomeFrame.java:1) at com.heytap.browser.home.HomeFrameAnimHelper.c(HomeFrameAnimHelper.java:2) at com.heytap.browser.home.HomeFrame.onLayout(HomeFrame.java:1) at android.view.View.layout(View.java:23154) at android.view.ViewGroup.layout(ViewGroup.java:6497) at com.heytap.browser.widget.ViewPager.onLayout(ViewPager.java:35) at android.view.View.layout(View.java:23154) at android.view.ViewGroup.layout(ViewGroup.java:6497) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332) at android.widget.FrameLayout.onLayout(FrameLayout.java:270) at android.view.View.layout(View.java:23154) at android.view.ViewGroup.layout(ViewGroup.java:6497) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332) at android.widget.FrameLayout.onLayout(FrameLayout.java:270) at com.heytap.browser.root.RootLayout.z(RootLayout.java:1) at com.heytap.browser.root.RootLayoutAnimHelper.h(RootLayoutAnimHelper.java:1) at com.heytap.browser.root.RootLayout.onLayout(RootLayout.java:1) at android.view.View.layout(View.java:23154) at android.view.ViewGroup.layout(ViewGroup.java:6497) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332) at android.widget.FrameLayout.onLayout(FrameLayout.java:270) at android.view.View.layout(View.java:23154) at android.view.ViewGroup.layout(ViewGroup.java:6497) at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841) at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673) at android.widget.LinearLayout.onLayout(LinearLayout.java:1582) at android.view.View.layout(View.java:23154) at android.view.ViewGroup.layout(ViewGroup.java:6497) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332) at android.widget.FrameLayout.onLayout(FrameLayout.java:270) at com.android.internal.policy.DecorView.onLayout(DecorView.java:877) at android.view.View.layout(View.java:23154) at android.view.ViewGroup.layout(ViewGroup.java:6497) at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3861) at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3272) at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2266) at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8847) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1483) at android.view.Choreographer.doCallbacks(Choreographer.java:1280) at android.view.Choreographer.doFrame(Choreographer.java:1014) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1468) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:263) at android.app.ActivityThread.main(ActivityThread.java:8288) at java.lang.reflect.Method.invoke(Method.java) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

请问最后怎么解决的？
