### ISSUE TITLE
java.lang.StackOverflowError  LRUBitmapBool init Error 

### ISSUE THREAD

**Issue by GavinZhoug** [bumptech/glide#3679]
**Glide Version**: 4.6.1

**Integration libraries**: volley

**Device/Android Version**:   Xiaomi | MiBOX2 / 4.4.2

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:

import android.content.Context;

import com.bumptech.glide.GlideBuilder;
import com.bumptech.glide.annotation.GlideModule;
import com.bumptech.glide.load.DecodeFormat;
import com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool;
import com.bumptech.glide.load.engine.cache.LruResourceCache;
import com.bumptech.glide.load.engine.cache.MemorySizeCalculator;
import com.bumptech.glide.module.AppGlideModule;

@GlideModule
public final class CustomAppGlideModule extends AppGlideModule {

    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        MemorySizeCalculator calculator = new MemorySizeCalculator.Builder(context)
                .setMemoryCacheScreens(2)
                .setBitmapPoolScreens(3)
                .build();
        builder.setMemoryCache(new LruResourceCache(calculator.getMemoryCacheSize()));
        **builder.setBitmapPool(new LruBitmapPool(calculator.getBitmapPoolSize()));** （error line）

        builder.setDecodeFormat(DecodeFormat.PREFER_RGB_565);
//        builder.setDecodeFormat(DecodeFormat.PREFER_ARGB_8888);
    }

    @Override
    public boolean isManifestParsingEnabled() {
        return false;
    }
}
Exception log:

```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
java.lang.StackOverflowError at com.bumptech.glide.load.engine.bitmap_recycle.SizeConfigStrategy$KeyPool.<init>(SizeConfigStrategy.java:178) at com.bumptech.glide.load.engine.bitmap_recycle.SizeConfigStrategy.<init>(SizeConfigStrategy.java:57) at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.getDefaultStrategy(LruBitmapPool.java:264) at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.<init>(LruBitmapPool.java:54) at com.mgtv.lib.tv.imageloader.b.applyOptions(CustomAppGlideModule.java:30) at com.bumptech.glide.GeneratedAppGlideModuleImpl.applyOptions(GeneratedAppGlideModuleImpl.java:28) at com.bumptech.glide.Glide.initializeGlide(Glide.java:262) at com.bumptech.glide.Glide.initializeGlide(Glide.java:219) at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:180) at com.bumptech.glide.Glide.get(Glide.java:164) at com.bumptech.glide.Glide.getRetriever(Glide.java:670) at com.bumptech.glide.Glide.with(Glide.java:697) at com.*****.f.a(ImageLoader.java:633) at com.*****.b.a.a(BootAdImgPlayer.java:71) at com.*****.b.c.a(BootAdPlayController.java:111) at com.******.b.f.a(BootAdViewImpl.java:95) at com.*****.b.f.b(BootAdViewImpl.java:68) at com.****.b.d.b(BootAdPresenter.java:313) at com.*****.b.d.a(BootAdPresenter.java:255) at com.****.b.d.showCacheAd(BootAdPresenter.java:119) at com.****.api.BootAdManager.showCacheAd(BootAdManager.java:56) at com.****.BootAdActivity.onCreate(BootAdActivity.java:120) at android.app.Activity.performCreate(Activity.java:5281) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1103) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) at android.app.ActivityThread.access$800(ActivityThread.java:135) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:136) at android.app.ActivityThread.main(ActivityThread.java:5018) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:515) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644) at dalvik.system.NativeStart.main(Native Method)
```ruby
paste stack trace and/or log here
```

**Comment by GavinZhoug** [comment]
I hasn't see relate issues on this gitgub project. How can I fix this problem? 
Thank you！
