### ISSUE TITLE
Glide The url with [] is inaccessible

### ISSUE THREAD

**Issue by ddong1031** [bumptech/glide#3806]
url like 
”https://scpub-img07.antelopecloud.cn:1443/image/v1/2147506178/objects/5d3eaa5080005802103052b8/1564761600000.jpg?client_token=2147506178_0_1564761600000_afa16fc8d95dd351208083585a462fd1&crop=x_612,y_0,w_270,h_232&watermark=m_53454E534F524F,c_FFFFFF,t_185,r_45,s_93,p_[0.6:0.1]&watermark=m_4F524F534E4553,c_FFFFFF,t_185,r_45,s_93,p_[0.1:0.6]“
please copy its url not click it！！！
has FileNotFoundException but its can show in other browers
java.io.FileNotFoundException: https://scpub-img07.antelopecloud.cn:1443/image/v1/2147506178/objects/5d3eaa5080005802103052b8/1564761600000.jpg?client_token=2147506178_0_1564761600000_afa16fc8d95dd351208083585a462fd1&crop=x_612,y_0,w_270,h_232&watermark=m_53454E534F524F,c_FFFFFF,t_185,r_45,s_93,p_%5B0.6:0.1%5D&watermark=m_4F524F534E4553,c_FFFFFF,t_185,r_45,s_93,p_%5B0.1:0.6%5D
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:106)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:59)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:65)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:309)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)

**Comment by cxmmxc** [comment]
who are u?

**Comment by yeguoqiang** [comment]
who are u ?你怎么也在用羚羊云的东西？

**Comment by fine1021** [comment]
For kotlin language


import android.net.Uri
import com.bumptech.glide.load.model.GlideUrl
import com.bumptech.glide.load.model.Headers
import com.bumptech.glide.util.Preconditions
import java.net.MalformedURLException
import java.net.URL


@Suppress("unused")
class MyGlideUrl : GlideUrl {

    companion object {

        private const val ALLOWED_URI_CHARS = "@#&=*+-_.,:!?()/~'%;$[]"
    }

    private val url: URL?
    private val stringUrl: String?

    private lateinit var safeStringUrl: String
    private lateinit var safeUrl: URL

    constructor(url: URL) : super(url) {
        this.url = url
        this.stringUrl = null
    }

    constructor(url: String) : super(url) {
        this.url = null
        this.stringUrl = url
    }

    constructor(url: URL, headers: Headers) : super(url, headers) {
        this.url = url
        this.stringUrl = null
    }

    constructor(url: String, headers: Headers) : super(url, headers) {
        this.url = null
        this.stringUrl = url
    }

    override fun getCacheKey(): String {
        return stringUrl ?: Preconditions.checkNotNull(url).toString()
    }

    override fun toURL(): URL {
        return getSafeUrl()
    }

    @Throws(MalformedURLException::class)
    private fun getSafeUrl(): URL {
        if (!this::safeUrl.isInitialized) {
            safeUrl = URL(getSafeStringUrl())
        }
        return safeUrl
    }

    override fun toStringUrl(): String {
        return getSafeStringUrl()
    }

    private fun getSafeStringUrl(): String {
        if (!this::safeStringUrl.isInitialized) {
            var unsafeStringUrl = stringUrl
            if (unsafeStringUrl.isNullOrEmpty()) {
                unsafeStringUrl = Preconditions.checkNotNull(url).toString()
            }
            safeStringUrl = Uri.encode(unsafeStringUrl, ALLOWED_URI_CHARS)
        }
        return safeStringUrl
    }
}


use like this: 

Glide.with(this)
                .load(MyGlideUrl(url))
                .into(imageView)

@ddong1031，you can transform this file to java

**Comment by sjudd** [comment]
From https://www.ietf.org/rfc/rfc1738.txt, brackets are unsafe characters and should be encoded in urls.

**Comment by FishHawk** [comment]
> From https://www.ietf.org/rfc/rfc1738.txt, brackets are unsafe characters and should be encoded in urls.

But the url of ipv6 uses brackets, like this:
http://[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]:80/index.html

see https://www.ietf.org/rfc/rfc2732.txt
