### ISSUE TITLE
conflit with huawei moniter count

### ISSUE THREAD

**Issue by xiaobaDev** [bumptech/glide#3863]
huawei limit 500 of BroadCastReceiver，when exceed it throws IllegalArgumentException

so in class  DefaultConnectivityMonitor please change the ExceptionType to Exception

private void register() {
    if (isRegistered) {
      return;
    }

    // Initialize isConnected.
    isConnected = isConnected(context);
    try {
      // See #1405
      context.registerReceiver(connectivityReceiver,
          new IntentFilter(ConnectivityManager.CONNECTIVITY_ACTION));
      isRegistered = true;
    } catch (SecurityException e) {
      // See #1417, registering the receiver can throw SecurityException.
      if (Log.isLoggable(TAG, Log.WARN)) {
        Log.w(TAG, "Failed to register", e);
      }
    }
  }

exception stack 

java.lang.IllegalArgumentException: regist too many Broadcast Receivers
    at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1838)
    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1794)
    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1788)
    at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:489)
    at com.bumptech.glide.c.e.a(DefaultConnectivityMonitor.java:55)
    at com.bumptech.glide.c.e.onStart(DefaultConnectivityMonitor.java:101)
    at com.bumptech.glide.c.a.a(ActivityFragmentLifecycle.java:37)
    at com.bumptech.glide.p.<init>(RequestManager.java:116)
    at com.bumptech.glide.p.<init>(RequestManager.java:78)
    at net.kimmy.android.core.image.module.GlideRequests.<init>(GlideRequests.java:38)
    at com.bumptech.glide.d.a(GeneratedRequestManagerFactory.java:19)
    at com.bumptech.glide.c.l.a(RequestManagerRetriever.java:441)
    at com.bumptech.glide.c.l.a(RequestManagerRetriever.java:134)
    at com.bumptech.glide.c.l.a(RequestManagerRetriever.java:116)
    at com.bumptech.glide.f.c(Glide.java:707)
    at net.kimmy.android.core.image.ImageRequestBuilder.generateRequestBuilder(ImageRequestBuilder.java:125)
    at net.kimmy.android.core.image.ImageRequestBuilder.into(ImageRequestBuilder.java:233)
    at net.kimmy.android.core.image.ImageManager.bindImage(ImageManager.java:52)
    at net.kimmy.android.ui.widget.imageSwitch.InfiniteIndicator$ParamsBuilder$2.load(InfiniteIndicator.java:560)
    at net.kimmy.android.ui.widget.imageSwitch.RecycleAdapter.getView(RecycleAdapter.java:58)
    at net.kimmy.android.ui.widget.imageSwitch.RecyclingPagerAdapter.instantiateItem(RecyclingPagerAdapter.java:50)
    at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1004)
    at android.support.v4.view.ViewPager.populate(ViewPager.java:1152)
    at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
    at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
    at android.view.View.measure(View.java:17628)
    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
    at android.view.View.measure(View.java:17628)
    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
    at android.view.View.measure(View.java:17628)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5548)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1467)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:638)
    at android.view.View.measure(View.java:17628)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5548)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1467)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:638)
    at android.view.View.measure(View.java:17628)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5548)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1467)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:638)
    at net.kimmy.android.ui.widget.stickylayout.StickyNavLayout.onMeasure(StickyNavLayout.java:343)
    at android.view.View.measure(View.java:17628)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5548)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
    at android.view.View.measure(View.java:17628)
    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
    at android.view.View.measure(View.java:17628)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5548)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
    at android.view.View.measure(View.java:17628)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5548)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1467)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:638)
    at android.view.View.measure(View.java:17628)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5548)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2693)
    at android.view.View.measure(View.java:17628)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2084)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1217)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1424)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1105)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6207)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:799)
    at android.view.Choreographer.doCallbacks(Choreographer.java:612)
    at android.view.Choreographer.doFrame(Choreographer.java:581)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:785)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5689)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by xiaobaDev** [comment]
device 
FDR-A03L

android version
5.1.1

**Comment by xiaobaDev** [comment]
i fix this bug by disable connection monitor in huawei 5.0 5.1， link https://www.jianshu.com/p/37cb1c32d2a4
