### ISSUE TITLE
java.lang.IllegalStateException: Already released

### ISSUE THREAD

**Issue by huongtran84** [bumptech/glide#3895]
Glide Version:
4.9.0

Issue details / Repro steps / Use case background:
Activity1: launch to Activity 2
Activity2: change image then finish back Activity1

Glide load line / GlideModule (if any) / list Adapter code (if any):
GlideApp.with(this).asDrawable()
.load(getImage(eventClicked.imageName))
.centerCrop()
.override(200, 200)
.into(new Target<Drawable>()
{
@override
public void onLoadStarted(@nullable Drawable placeholder)
{

                    }

                    @Override
                    public void onLoadFailed(@Nullable Drawable errorDrawable)
                    {

                    }

                    @Override
                    public void onResourceReady(@NonNull Drawable resource, @Nullable Transition<? super Drawable> transition)
                    {
                        try {
                            Bitmap bitmap = Bitmap.createBitmap(AppConfig.PHOTO_SCALE_FACTOR, AppConfig.PHOTO_SCALE_FACTOR, Bitmap.Config.ARGB_8888);
                            Canvas canvas = new Canvas(bitmap);
                            FileOutputStream outputStream = openFileOutput("profilePicture", MODE_PRIVATE);

                            resource.setBounds(0, 0, canvas.getWidth(), canvas.getHeight());
                            resource.draw(canvas);
                            bitmap.compress(Bitmap.CompressFormat.PNG, 100, outputStream);

                            outputStream.close();

                            notifyUserProfileChanged();
                        } catch (Exception error) {
                            error.printStackTrace();
                        }
                    }

                    @Override
                    public void onLoadCleared(@Nullable Drawable placeholder)
                    {

                    }

                    @Override
                    public void getSize(@NonNull SizeReadyCallback cb)
                    {

                    }

                    @Override
                    public void removeCallback(@NonNull SizeReadyCallback cb)
                    {
                    }

                    @Nullable
                    @Override
                    public Request getRequest()
                    {
                        return null;
                    }

                    @Override
                    public void setRequest(@Nullable Request request)
                    {

                    }

                    @Override
                    public void onStart()
                    {

                    }

                    @Override
                    public void onStop()
                    {

                    }

                    @Override
                    public void onDestroy()
                    {

                    }
                });
Stack trace / LogCat:
java.lang.IllegalStateException: Already released
at com.bumptech.glide.util.pool.StateVerifier$DefaultStateVerifier.throwIfRecycled(StateVerifier.java:46)
at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:236)
at com.bumptech.glide.manager.RequestTracker.resumeRequests(RequestTracker.java:128)
at com.bumptech.glide.RequestManager.resumeRequests(RequestManager.java:292)
at com.bumptech.glide.RequestManager.onStart(RequestManager.java:317)
at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStart(ActivityFragmentLifecycle.java:51)
at com.bumptech.glide.manager.SupportRequestManagerFragment.onStart(SupportRequestManagerFragment.java:182)
at androidx.fragment.app.Fragment.performStart(Fragment.java:2478)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:919)
at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1229)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1295)
at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2605)
at androidx.fragment.app.FragmentManagerImpl.dispatchStart(FragmentManagerImpl.java:2571)
at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:256)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:533)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:179)

**Glide Version**:

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by forJrking** [comment]
@huongtran84  Did you solve the problem？
