### ISSUE TITLE
NPE at ProcessorUtil.findInstanceMethodsReturning line 498

### ISSUE THREAD

**Issue by lpellegr** [bumptech/glide#3905]
**Glide Version**: 4.10.0

**Integration libraries**: okhttp:4.2.0

**Device/Android Version**: Emulator Pixel 2 Android 27

**Issue details / Repro steps / Use case background**: 

Upgrading from version 4.8.0 to 4.10.0 my project build fails with the following error:

> org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':app:compileFreeDebugJavaWithJavac'.
> ...
> Caused by: java.lang.NullPointerException
> 	at com.bumptech.glide.annotation.compiler.ProcessorUtil.findInstanceMethodsReturning(ProcessorUtil.java:498)
> 	at com.bumptech.glide.annotation.compiler.RequestOptionsOverrideGenerator.generateInstanceMethodOverridesForRequestOptions(RequestOptionsOverrideGenerator.java:48)
> ...

Downgrading back to 4.8.0 fixes the problem. The problem is also present with 4.9.0.

Android X support and jetifier is enabled:

```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by sjudd** [comment]
Are you able to provide any sample code that reproduces the problem?
