### ISSUE TITLE
GeneratedAppGlideModuleImpl is implemented incorrectly.

### ISSUE THREAD

**Issue by ppabcd** [bumptech/glide#3918]
**Glide Version**: 4.90

**Device/Android Version**: Xiaomi Note 5 Pro / Android 9 ( Pie )

**Issue details / Repro steps / Use case background**: 
Hello,
I have problem with my module. When i create a module like this i got error *GeneratedAppGlideModuleImpl is implemented incorrectly.*. How to fix this error.
```
package id.rezajuliandri.film.module;

import com.bumptech.glide.annotation.GlideModule;
import com.bumptech.glide.module.AppGlideModule;

@GlideModule
public class MyGlideModule extends AppGlideModule {
    @Override
    public boolean isManifestParsingEnabled() {
        return false;
    }
}
```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GlideApp.with(holder.itemView.getContext())
                .load("https://image.tmdb.org/t/p/original" + movie.getImage())
                .fitCenter()
                .into(holder.img);
```

**Layout XML**:
```xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_margin="20dp"
    android:orientation="vertical">

    <ImageView
        android:id="@+id/img_film"
        android:layout_width="100dp"
        android:layout_height="150dp"
        android:scaleType="fitXY"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        tools:layout_conversion_wrapHeight="394"
        tools:layout_conversion_wrapWidth="263"
        android:contentDescription="@string/film_image"/>

    <TextView
        android:id="@+id/title_film"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginStart="26dp"
        android:textSize="18sp"
        android:textStyle="bold"
        app:layout_constraintStart_toEndOf="@id/img_film"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        tools:layout_conversion_wrapHeight="63"
        tools:layout_conversion_wrapWidth="97"
        tools:text="@string/title_film" />

    <TextView
        android:id="@+id/description_film"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginStart="26dp"
        android:layout_marginTop="10dp"
        android:ellipsize="end"
        android:maxLines="3"
        app:layout_constraintLeft_toRightOf="@id/img_film"
        app:layout_constraintTop_toBottomOf="@+id/title_film"
        app:layout_constraintRight_toRightOf="parent"
        tools:layout_conversion_wrapHeight="50"
        tools:layout_conversion_wrapWidth="191"
        tools:text="@string/description_film" />

    <TextView
        android:id="@+id/date_film"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginStart="26dp"
        android:layout_marginTop="10dp"
        app:layout_constraintLeft_toRightOf="@id/img_film"
        app:layout_constraintTop_toBottomOf="@id/description_film"
        tools:layout_conversion_wrapHeight="50"
        tools:layout_conversion_wrapWidth="158"
        tools:text="@string/film_date" />

    <TextView
        android:id="@+id/score_film"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginStart="26dp"
        android:layout_marginTop="10dp"
        app:layout_constraintLeft_toRightOf="@id/date_film"
        app:layout_constraintTop_toBottomOf="@id/description_film"
        tools:layout_conversion_wrapHeight="50"
        tools:layout_conversion_wrapWidth="177"
        tools:text="@string/score_film" />
</androidx.constraintlayout.widget.ConstraintLayout>
```

**Stack trace / LogCat**:
```ruby
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: id.rezajuliandri.film, PID: 18957
    java.lang.IllegalStateException: GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation.
        at com.bumptech.glide.Glide.throwIncorrectGlideModule(Glide.java:309)
        at com.bumptech.glide.Glide.getAnnotationGeneratedGlideModules(Glide.java:301)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:229)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:223)
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:184)
        at com.bumptech.glide.Glide.get(Glide.java:168)
        at com.bumptech.glide.Glide.getRetriever(Glide.java:689)
        at com.bumptech.glide.Glide.with(Glide.java:716)
        at id.rezajuliandri.film.module.GlideApp.with(GlideApp.java:86)
        at id.rezajuliandri.film.adapter.ListAdapter.onBindViewHolder(ListAdapter.java:53)
        at id.rezajuliandri.film.adapter.ListAdapter.onBindViewHolder(ListAdapter.java:22)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:446)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:757)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2840)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2367)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1505)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7354)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
        at android.view.Choreographer.doCallbacks(Choreographer.java:888)
        at android.view.Choreographer.doFrame(Choreographer.java:819)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.NoSuchMethodException: <init> []
        at java.lang.Class.getConstructor0(Class.java:2327)
        at java.lang.Class.getDeclaredConstructor(Class.java:2166)
        at com.bumptech.glide.Glide.getAnnotationGeneratedGlideModules(Glide.java:287)
        	... 70 more
```

**Comment by yunxingyu** [comment]
升级androidx后，检查是否有三方库没做androidx适配，我的之前引用的aar包包含了非androidx版本的glide，升级三方aar库后就正常。
