### ISSUE TITLE
Too many receivers, total of 1000, registered for pid: 21355,

### ISSUE THREAD

**Issue by tanwu520** [bumptech/glide#3932]
java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 21355, callerPackage: com.ttd.tokl
	at android.os.Parcel.createException(Parcel.java:1971)
	at android.os.Parcel.readException(Parcel.java:1931)
	at android.os.Parcel.readException(Parcel.java:1881)
	at android.app.IActivityManager$Stub$Proxy.registerReceiver(IActivityManager.java:3676)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1507)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1468)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1456)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:623)
	at com.bumptech.glide.c.e.a(SourceFile:55)
	at com.bumptech.glide.c.e.i(SourceFile:101)
	at com.bumptech.glide.c.a.a(SourceFile:37)
	at com.bumptech.glide.i.<init>(SourceFile:116)
	at com.bumptech.glide.i.<init>(SourceFile:78)
	at com.bbk.appstore.imageloader.e.<init>(SourceFile:38)
	at com.bumptech.glide.c.a(SourceFile:19)
	at com.bumptech.glide.c.l.a(SourceFile:441)
	at com.bumptech.glide.c.l.a(SourceFile:134)
	at com.bumptech.glide.c.l.a(SourceFile:116)
	at com.bumptech.glide.e.b(SourceFile:707)

**Comment by sjudd** [comment]
Duplicate of #1161

**Comment by Sharmila31** [comment]
@sjudd Hi, I am facing this issue but unable to find the exact cause as it occurs only on Android 11 OS and on the remaining versions it seems to work fine. Any thought or suggestions would be helpful?
