### ISSUE TITLE
Can We Cache 404 Error Image URLs and Stop Glide Calling Them When Loaded Next Time?

### ISSUE THREAD

**Issue by amarilindra** [bumptech/glide#3951]
**Glide Version**:
4.9.0

**Integration libraries**:
implementation "com.github.bumptech.glide:glide:4.9.0"
kapt "com.github.bumptech.glide:compiler:4.9.0"

**Device/Android Version**:
Google Pixel 2XL / Android 10

**Issue details / Repro steps / Use case background**: 
We are using 3 fallback URLs to load an image. Among those 3 fallbacks and 1 main image URL, only one of them will have a 200 response. 

So let's assume, the last fallback URL is 200 responses and the rest of them are 400. In this case, Glide keeps calling all fallback URLs every time when I re-open the app and finally showing the last image URL from the cache. So technically my app is waiting so long till the last fallback URL is called. 

Is there any way to cache those 404 errors too? 
For instance, the first fallback URL throws a 404 error, so when Glide wants to show the same URL next time, Glide should stop making that request to the internet and call error() immediately. This way my last fallback URL will be shown from cache instantly. 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
GlideApp.with(context)
                .load(openLibraryCover)
                .error(
                        Glide.with(context).load(coverImageWithID).error(
                                Glide.with(context).load(fallbackImageUrlOne).error(
                                        Glide.with(context).load(fallbackImageUrlTwo)
                                ).diskCacheStrategy(DiskCacheStrategy.ALL)

                        ).diskCacheStrategy(DiskCacheStrategy.ALL)

                ).diskCacheStrategy(DiskCacheStrategy.ALL)

                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .into(this)
```

**Layout XML**:
```xml
 <ImageView
                        android:id="@+id/detailsBookCoverImage"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:scaleType="centerCrop"
                        android:transitionName="@string/shared_element_cover_image"
                        />
```

**Stack trace / LogCat**:
```ruby
Root cause (1 of 1)
    java.io.FileNotFoundException: http://covers.openlibrary.org/b/id/40175124-L.jpg?default=false
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:106)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:59)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:65)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:309)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)

```

**Comment by sjudd** [comment]
For http caching you might consider a networking library like Volley, Cronet, or OkHttp.

Glide in general isn't aware of http status codes. Networking libraries have a lot more freedom to choose how they deal with http specifically.

See also: http://bumptech.github.io/glide/int/okhttp3.html

**Comment by baderkhane** [comment]
Hello, i have the same issue.
Could you please guide me how i can get status code withing http://bumptech.github.io/glide/int/okhttp3.html
Thanks
