### ISSUE TITLE
 trying to use a recycled bitmap android.graphics.Bitmap@4a412b？

### ISSUE THREAD

**Issue by VeeWikis** [bumptech/glide#3981]
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@4a412b
        at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:70)
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:226)
        at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:101)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
        at android.widget.ImageView.onDraw(ImageView.java:1360)
        at android.view.View.draw(View.java:21875)
        at android.view.View.updateDisplayListIfDirty(View.java:20748)
        at android.view.View.draw(View.java:21601)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.view.View.updateDisplayListIfDirty(View.java:20734)
        at android.view.View.draw(View.java:21601)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.view.View.updateDisplayListIfDirty(View.java:20734)
        at android.view.View.draw(View.java:21601)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.view.View.updateDisplayListIfDirty(View.java:20734)
        at android.view.View.draw(View.java:21601)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.view.View.updateDisplayListIfDirty(View.java:20734)
        at android.view.View.draw(View.java:21601)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.widget.ListView.drawChild(ListView.java:3816)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.widget.AbsListView.dispatchDraw(AbsListView.java:3531)
        at android.widget.ListView.dispatchDraw(ListView.java:3797)
        at android.view.View.draw(View.java:21878)
        at android.widget.AbsListView.draw(AbsListView.java:7106)
        at android.view.View.updateDisplayListIfDirty(View.java:20748)
        at android.view.View.draw(View.java:21601)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.view.View.draw(View.java:21878)
        at android.view.View.updateDisplayListIfDirty(View.java:20748)
        at android.view.View.draw(View.java:21601)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.view.View.updateDisplayListIfDirty(View.java:20734)
        at android.view.View.draw(View.java:21601)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.view.View.updateDisplayListIfDirty(View.java:20734)
        at android.view.View.draw(View.java:21601)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.view.View.updateDisplayListIfDirty(View.java:20734)
        at android.view.View.draw(View.java:21601)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.view.View.draw(View.java:21878)
        at android.view.View.updateDisplayListIfDirty(View.java:20748)
        at android.view.View.draw(View.java:21601)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.view.View.updateDisplayListIfDirty(View.java:20734)
        at android.view.View.draw(View.java:21601)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.view.View.updateDisplayListIfDirty(View.java:20734)
        at android.view.View.draw(View.java:21601)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.view.View.updateDisplayListIfDirty(View.java:20734)
        at android.view.View.draw(View.java:21601)

**Comment by wang869755676** [comment]
I had the same problem  （version 4.8）

**Comment by xuanzhiqiang** [comment]
I had the same problem （version 4.10

**Comment by bd901029** [comment]
I had the same problem when going to another app and return back.

**Comment by Mohamadkotb** [comment]
I had the same problem (version 4.11.0)

**Comment by mikilangkilo** [comment]
i had the same problem expand memory not work

**Comment by algrid** [comment]
Same problem on 4.12.0

**Comment by DearZack** [comment]
Same problem on 4.11.0

**Comment by actor20170211030627** [comment]
Same problem on 4.16.0, in RecyclerView, not from background.

**Comment by 1mean** [comment]
> Same problem on 4.12.0

same 4.12.0，Have you solved this problem now?
