### ISSUE TITLE
Glide calls .setResource when app .onDestroy  is called. Why? Complete meltdown!

### ISSUE THREAD

**Issue by chjan** [bumptech/glide#3986]
Glide 490 on a LG v30 A9:

The following code is called during usage, and THEN AGAIN (not by my code but by glide) when .onDestroy is called e.g. after tilt detection. The first question is why it is called again then? What could be the reasons, what could I have done wrong when this happens? The second question is why the parameter in the .setResource call is null, causing exception?

This code (when called by my code when it shall be called) ends up saving a bitmap to the internal directory of the app, perhaps this is part of the reason? However, nothing in my code should cause this method call again. Looks very, very mysterious!

Hopefully, it is only a question about "terminating" Glide in a way that I have not done properly. I have tried Glide.with(this).onDestroy(); before super.onDestroy(), but that causes another exception inside glide

Code that is called: 

`try {
                    Glide.with(activity)
                        .asBitmap()
                        .load(url)
                        .into(new BitmapImageViewTarget(stationButton) {

                            @Override
                            protected void setResource(Bitmap sourceBitmap) {

                                //1. load preset_blank into a bitmap
                                Bitmap presetBlank = BitmapFactory.decodeResource(activity.getResources(),
                                        R.drawable.preset_blank);`
```

StackTrace: 

? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hdsl.a.zapp, PID: 14718
    java.lang.RuntimeException: Unable to destroy activity {com.hdsl.a.zapp/com.hdsl.a.zapp.PlayerManager}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4642)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4661)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4949)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4883)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:205)
        at android.app.ActivityThread.main(ActivityThread.java:6991)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:734)
        at com.hdsl.a.zapp.players.PresetRadioSelector$2.setResource(PresetRadioSelector.java:1046)
        at com.hdsl.a.zapp.players.PresetRadioSelector$2.setResource(PresetRadioSelector.java:1036)
        at com.bumptech.glide.request.target.ImageViewTarget.setResourceInternal(ImageViewTarget.java:127)
        at com.bumptech.glide.request.target.ImageViewTarget.onLoadCleared(ImageViewTarget.java:97)
        at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:333)
        at com.bumptech.glide.manager.RequestTracker.clearRemoveAndMaybeRecycle(RequestTracker.java:79)
        at com.bumptech.glide.manager.RequestTracker.clearRemoveAndRecycle(RequestTracker.java:66)
        at com.bumptech.glide.RequestManager.untrack(RequestManager.java:630)
        at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:598)
        at com.bumptech.glide.RequestManager.clear(RequestManager.java:594)
        at com.bumptech.glide.RequestManager.onDestroy(RequestManager.java:339)
        at com.bumptech.glide.manager.ActivityFragmentLifecycle.onDestroy(ActivityFragmentLifecycle.java:65)
        at com.bumptech.glide.manager.SupportRequestManagerFragment.onDestroy(SupportRequestManagerFragment.java:194)
        at android.support.v4.app.Fragment.performDestroy(Fragment.java:2699)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1591)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3260)
        at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:274)
        at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:419)
        at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:210)
        at com.hdsl.a.zapp.PlayerManager.onDestroy(PlayerManager.java:360)
        at android.app.Activity.performDestroy(Activity.java:7418)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1307)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4627)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4661) 
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4949) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4883) 
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:205) 
        at android.app.ActivityThread.main(ActivityThread.java:6991) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)

**Comment by chjan** [comment]
For some reason, I cannot edit my own text. Hence I add the following in a comment:  I have tried Glide.with(this).onDestroy(); before super.onDestroy(), but that causes another exception inside glide

**Comment by chjan** [comment]
I additionally want to add that the method .setResource is often (always) called twice, probably because the first call is about a placeholder and if null, the method brings null as parameter. Then the second call contains the bitmap.

I want to suggest that this is counterproductive and a timethief for using Glide, in that the first null-call is deeply unwanted as it creates more complex code. It would be much better to implement the method .onResourceReady( thumbnail, image), then the null would not cause confusion. And to that, add a .onThumbnailReady() so as to serve those in the need of that.

I repeat that my usage is related to storing a png to the app folder, as it is used as background on button. Hence, thumbnail is irrelevant.

**Comment by sjudd** [comment]
Glide wants to free up and re-use resources when activities are destroyed. It's not safe to do so if anyone is still referencing those resources. To remove the references, targets are notified that they've been cleared. The API allows you to optionally display a drawable when a target is cleared. The same code path is used both for explicit calls to clear() and for implicit calls to clear() for consistency.

If you haven't set a placeholder, then the Drawable will be null. As far as I can tell this is expected behavior.

You could definitely argue that it's wasteful to set a non-null placeholder Drawable during on destroy. However it seems like you're objecting to the null placeholder, so even that minor improvement wouldn't help.

We don't want to start re-using resources while they're still used because that leads to reuse errors: http://bumptech.github.io/glide/doc/resourcereuse.html#common-errors
