### ISSUE TITLE
anr in glide   at com.bumptech.glide.load.engine.EngineJob.removeCallback(EngineJob.java:-1)   - waiting to lock <0x072b41e0> (a com.bumptech.glide.load.engine.EngineJob) held by thread 34

### ISSUE THREAD

**Issue by mrtion** [bumptech/glide#3993]
anr in glide with monkey test.

"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 obj=0x742eee00 self=0xb4db6500
  | sysTid=2078 nice=0 cgrp=default sched=0/0 handle=0xb6fb9b34
  | state=S schedstat=( 64642462125 136132828585 201683 ) utm=5791 stm=673 core=0 HZ=100
  | stack=0xbe035000-0xbe037000 stackSize=8MB
  | held mutexes=
  at com.bumptech.glide.load.engine.EngineJob.removeCallback(EngineJob.java:-1)
  - waiting to lock <0x072b41e0> (a com.bumptech.glide.load.engine.EngineJob) held by thread 34
  at com.bumptech.glide.load.engine.Engine$LoadStatus.cancel(Engine.java:359)
  - locked <0x0ebd7c99> (a com.bumptech.glide.load.engine.Engine)
  at com.bumptech.glide.request.SingleRequest.cancel(SingleRequest.java:297)
  at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:327)
  - locked <0x0d71e8aa> (a com.bumptech.glide.request.SingleRequest)
  at com.bumptech.glide.manager.RequestTracker.restartRequests(RequestTracker.java:154)
  at com.bumptech.glide.RequestManager$RequestManagerConnectivityListener.onConnectivityChanged(RequestManager.java:675)
  - locked <0x09fadb5e> (a com.bumptech.glide.RequestManager)
  at com.bumptech.glide.manager.DefaultConnectivityMonitor$1.onReceive(DefaultConnectivityMonitor.java:36)
  at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:881)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5417)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:743)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:633)

...

"glide-disk-cache-thread-0" prio=5 tid=34 Blocked
  | group="main" sCount=1 dsCount=0 obj=0x12cade80 self=0xb4d51200
  | sysTid=2230 nice=9 cgrp=default sched=0/0 handle=0xa0f26930
  | state=S schedstat=( 12490502790 112931797597 38132 ) utm=1080 stm=169 core=1 HZ=100
  | stack=0xa0e24000-0xa0e26000 stackSize=1038KB
  | held mutexes=
  at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:-1)
  - waiting to lock <0x0d71e8aa> (a com.bumptech.glide.request.SingleRequest) held by thread 1
  at com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:152)
  - locked <0x072b41e0> (a com.bumptech.glide.load.engine.EngineJob)
  at com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:398)
  - locked <0x072b41e0> (a com.bumptech.glide.load.engine.EngineJob)
  at com.bumptech.glide.util.Executors$2.execute(Executors.java:30)
  at com.bumptech.glide.load.engine.EngineJob.notifyCallbacksOfResult(EngineJob.java:250)
  at com.bumptech.glide.load.engine.EngineJob.onResourceReady(EngineJob.java:304)
  at com.bumptech.glide.load.engine.DecodeJob.notifyComplete(DecodeJob.java:336)
  at com.bumptech.glide.load.engine.DecodeJob.notifyEncodeAndRelease(DecodeJob.java:442)
  at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:424)
  at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:387)
  at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:95)
  at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:74)
  at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:75)
  at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:309)
  at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:276)
  at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
  at java.lang.Thread.run(Thread.java:818)
  at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)

**Comment by mrtion** [comment]
glide version : 4.9.0
