### ISSUE TITLE
You must not call setTag() on a view Glide is targeting

### ISSUE THREAD

**Issue by zhairui** [bumptech/glide#3996]
**Glide Version**:4.9.0

**Integration libraries**:

**Device/Android Version**:5.1.1

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(context).load(url).apply().into(imageview)
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...>
<ImageView
        android:id="@+id/image"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="centerInside"/>
</FrameLayout>
```

**Stack trace / LogCat**:
 Caused by: java.lang.IllegalArgumentException: You must not call setTag() on a view Glide is targeting
        at com.bumptech.glide.request.target.ViewTarget.getRequest(ViewTarget.java:271)
        at com.bumptech.glide.RequestManager.untrack(RequestManager.java:597)
        at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:571)
        at com.bumptech.glide.RequestManager.clear(RequestManager.java:559)
        at com.bumptech.glide.RequestManager.onDestroy(RequestManager.java:303)
        at com.bumptech.glide.manager.ActivityFragmentLifecycle.onDestroy(ActivityFragmentLifecycle.java:65)
        at com.bumptech.glide.manager.SupportRequestManagerFragment.onDestroy(SupportRequestManagerFragment.java:194)
        at android.support.v4.app.Fragment.performDestroy(Fragment.java:2588)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1566)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
        at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3235)
        at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:265)
        at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:390)

**Help**

I used glide in RecyclerView and never used setTag() , when the activity destroy , the exception was thrown . could you give me some advice? thanks!

**Comment by NicolasGodfather** [comment]
The same bug - how fix it??? In my case I have 3 fragments(F1, F2, F3) in my activity (A1). Glide load urls in items of recyclerview in F2. Crash happens when backpressed from F3->F2->F1->exit from app. It seem a long bug in glide since v4.
