### ISSUE TITLE
the reason of java.lang.IllegalStateException: Already released

### ISSUE THREAD

**Issue by will-shi** [bumptech/glide#3997]
**Glide Version**: 4.5.0

**Integration libraries**: OkHttp3

**Device/Android Version**: 

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
2019-11-27 11:57:32.793 4575-5035/com.test E/testglide: is release: false | is notified: false | hash: com.bumptech.glide.load.engine.DecodeJob@70c29fe
2019-11-27 11:57:32.793 4575-5014/com.test E/testglide: is release: false | is notified: false | hash: com.bumptech.glide.load.engine.DecodeJob@70c29fe
2019-11-27 11:57:32.794 4575-4575/com.test E/testglide: is release------>: false | hash: com.bumptech.glide.load.engine.EngineJob@d6d755f
2019-11-27 11:57:32.794 4575-4575/com.test E/testglide: is release------>: true | hash: com.bumptech.glide.load.engine.EngineJob@d6d755f
2019-11-27 11:57:32.799 4575-4575/com.test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test, PID: 4575
    java.lang.IllegalStateException: Already released
        at com.bumptech.glide.util.pool.StateVerifier$DefaultStateVerifier.throwIfRecycled(StateVerifier.java:48)
        at com.bumptech.glide.load.engine.EngineJob.handleExceptionOnMainThread(EngineJob.java:285)
        at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:334)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6866)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:817)
```

what trigger crash on glide is two or more work thread holds a same instance of ```DecodeJob```, and DecodeJob's callback(actually callback is ```EngineJob```) invoke ```onResourceReady``` or ```onLoadFailed```  twice in the same time. so in ```EngineJob``` the first time to check ```stateVerifier.throwIfRecycled();``` it will be fine,but the second time to check ```stateVerifier.throwIfRecycled();``` it will be crashed!

**Comment by will-shi** [comment]
### reproduce step:

1. use fiddler to intercept glide's request and delay 5000ms

2. a view page with two fragment

3. the first fragment load image and before load complete sliding to the second fragment and load image

4. then app crash
