### ISSUE TITLE
Glide can't load this gif

### ISSUE THREAD

**Issue by zhuantou233** [bumptech/glide#4018]
**Glide Version**: 4.8.0

**Integration libraries**: No

**Device/Android Version**: Google Pixel 2XL Android 10, Xiaomi 6 Android 9, Moto g6 Android 9

**Issue details / Repro steps / Use case background**: This gif can't be loaded, whether from uri or local file, [GIF](https://pic4.zhimg.com/100/v2-2b28c4ebbf5ed22c07744c4f84b9b1ac_b.gif)

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
RequestOptions options = new RequestOptions()
        .error(R.drawable.ic_launcher_background);
Uri uri = Uri.parse("https://pic4.zhimg.com/100/v2-2b28c4ebbf5ed22c07744c4f84b9b1ac_b.gif");
Glide.with(this)
        .asGif()
        .load(uri)
        .apply(options)
        .into(imageView);
```

**Layout XML**:
```xml
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <ImageView
        android:id="@+id/imageView"
        android:layout_width="331dp"
        android:layout_height="220dp"
        android:layout_marginStart="8dp"
        android:layout_marginTop="8dp"
        android:layout_marginEnd="8dp"
        android:layout_marginBottom="8dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintVertical_bias="0.802" />

</android.support.constraint.ConstraintLayout>
```

**Stack trace / LogCat**:
```ruby
2019-12-19 14:31:59.759 29320-30391/? E/GlideExecutor: Request threw uncaught throwable
    com.bumptech.glide.Registry$NoSourceEncoderAvailableException: Failed to find source encoder for data class: class android.os.ParcelFileDescriptor
        at com.bumptech.glide.Registry.getSourceEncoder(Registry.java:572)
        at com.bumptech.glide.load.engine.DecodeHelper.getSourceEncoder(DecodeHelper.java:241)
        at com.bumptech.glide.load.engine.SourceGenerator.cacheData(SourceGenerator.java:75)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:46)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:798)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
```

**Comment by iliucong** [comment]
you can put the url to the load method directly instead of building Url object.

**Comment by zhuantou233** [comment]
> you can put the url to the load method directly instead of building Url object.

```java
String url = "https://pic4.zhimg.com/100/v2-2b28c4ebbf5ed22c07744c4f84b9b1ac_b.gif";
Glide.with(this)
        .asGif()
        .load(url)
        .apply(options)
        .into(imageView);
```
The code above still can't load this gif.

It seems to be something wrong when Glide encoding or decoding this gif, but only this gif. I have used other gif or images, they could be loaded correctly with Glide.

**Comment by iliucong** [comment]
the gif file is invalid。
same thing in #1849
