### ISSUE TITLE
recycled bitmaps not checked crashes the app

### ISSUE THREAD

**Issue by mariuspena** [bumptech/glide#4028]
**Glide Version**: 4.10.0
**Device/Android Version**: multiple devices according to crashlytics
**Issue details / Repro steps / Use case background**: app tries to destroy an activity and glide crashes because it does not check for recycled bitmaps I presume.. 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
 GlideApp.with(this)
                        .load(bitmap)
                        .override(imgW, imgH)
                        .diskCacheStrategy(DiskCacheStrategy.NONE)
                        .apply(new RequestOptions().transforms(new FitCenter(),
                                new RoundCornersShadowTransformation(getResources()
                                        .getDimensionPixelSize(R.dimen.exercise_step_radius_list),
                                        0)))
                        .transition(DrawableTransitionOptions.withCrossFade())
                        .into(presetImage);
```

**Stack trace / LogCat**:
```ruby
Caused by java.lang.IllegalStateException: Cannot obtain size for recycled Bitmap: android.graphics.Bitmap@5d1efee[207x244] RGB_565
       at com.bumptech.glide.util.Util.getBitmapByteSize(Util.java:79)
       at com.bumptech.glide.load.resource.bitmap.UnitBitmapDecoder$NonOwnedBitmapResource.getSize(UnitBitmapDecoder.java:49)
       at com.bumptech.glide.load.resource.bitmap.LazyBitmapDrawableResource.getSize(LazyBitmapDrawableResource.java:76)
       at com.bumptech.glide.load.engine.EngineResource.getSize(EngineResource.java:62)
       at com.bumptech.glide.load.engine.cache.LruResourceCache.getSize(LruResourceCache.java:40)
       at com.bumptech.glide.load.engine.cache.LruResourceCache.getSize(LruResourceCache.java:11)
       at com.bumptech.glide.util.LruCache.put(LruCache.java:117)
       at com.bumptech.glide.load.engine.cache.LruResourceCache.put(LruResourceCache.java:11)
       at com.bumptech.glide.load.engine.Engine.onResourceReleased(Engine.java:394)
       at com.bumptech.glide.load.engine.EngineResource.release(EngineResource.java:116)
       at com.bumptech.glide.load.engine.Engine.release(Engine.java:362)
       at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:326)
       at com.bumptech.glide.manager.RequestTracker.clearAndRemove(RequestTracker.java:72)
       at com.bumptech.glide.RequestManager.untrack(RequestManager.java:663)
       at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:631)
       at com.bumptech.glide.RequestManager.clear(RequestManager.java:627)
       at com.bumptech.glide.RequestManager.onDestroy(RequestManager.java:374)
       at com.bumptech.glide.manager.ActivityFragmentLifecycle.onDestroy(ActivityFragmentLifecycle.java:65)
       at com.bumptech.glide.manager.SupportRequestManagerFragment.onDestroy(SupportRequestManagerFragment.java:215)
       at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2830)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1028)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
       at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2644)
       at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:329)
       at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:366)
       at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:233)
```

Please check this closed issue too: https://github.com/bumptech/glide/issues/2574

**Comment by Nir-Zigler** [comment]
We are seeing the same issue.

**Comment by Nir-Zigler** [comment]
Any update?
Thanks in advance.
