### ISSUE TITLE
Cannot recycle a resource that has already been recycled

### ISSUE THREAD

**Issue by VasilisKatsoris** [bumptech/glide#4055]
Device Xiaomi Redmi 3S
Android 5.1.1 LMY47V with MIUI 7.3.2.0.0(LHPCNDD)
Glide 4.11.0

I am in a list screen that shows objects created and deleted by the user. Each object is assigned an icon (enter Glide) selected by the user from local resources. No networking is involved. The user opens a new screen to create an object and when the user is done they return to the list screen and the object shows on the list. 

Both screens are a fragment inside an activity of their own. (An activity with the list fragment opens an activity with the object creator fragment).  To reproduce the crash I do a series of add/delete operations. The crash always happens after the creation of an object at the return to the list fragment. I include a video of reproducing the crash.

I could reproduce it every time on Redmi 3S. 
On Samsung SM-G355HN after many failed attempts to reproduce it I put the app in background while I was at the list screen and it immediately crashed with the same error. I haven't been able to reproduce that again.

The exception logged is:

```
E/UncaughtException: java.lang.IllegalStateException: Cannot recycle a resource that has already been recycled
        at com.bumptech.glide.load.engine.EngineResource.recycle(EngineResource.java:71)
        at com.bumptech.glide.load.engine.ResourceRecycler$ResourceRecyclerCallback.handleMessage(ResourceRecycler.java:37)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5287)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

My Glide model class is this :

```
public class MyGlideInput {

    private String packageName, apkFilePath, iconResName;

    public MyGlideInput() {
    }

    @Override
    public boolean equals(@Nullable Object obj) {
        if(obj == null){
            return false;
        }
        if(!(obj instanceof MyGlideInput)){
            return false;
        }
        MyGlideInput input = (MyGlideInput) obj;
        return stringsEqual(packageName, input.packageName ) && stringsEqual(apkFilePath, input.apkFilePath)
                && stringsEqual(iconResName, input.iconResName);
    }

    @Override
    public int hashCode() {
        return (apkFilePath+packageName+iconResName+"").hashCode();
    }

    public boolean stringsEqual(String a, String b){
        return a != null && a.equals(b);
    }

}
```

Inside the RecyclerView adapter class on bindViewHolder I do this:
```
GlideInput glideInput = new GlideInput().setDrawableResName(iconName);
GlideApp.with(img).load(glideInput).dontAnimate().error(R.drawable.warning).into(img);
```
 

My Glide decoder

```
public class GlideInputBitmapDecoder implements ResourceDecoder<GlideInput, Drawable> {


    PackageManager packageManager;

    public GlideInputBitmapDecoder(PackageManager packageManager) {
        this.packageManager = packageManager;
    }

    @Override
    public boolean handles(@NonNull GlideInput source, @NonNull Options options) throws IOException {
        return true;
    }

    @Nullable
    @Override
    public Resource<Drawable> decode(@NonNull GlideInput source, int width, int height, @NonNull Options options) throws IOException {
        Drawable icon = null;
        Context con = MyApplication.context;
        if(source.getPackageName()!=null) {
            try {
                icon = packageManager.getApplicationIcon(source.getPackageName());
            } catch (PackageManager.NameNotFoundException e) {
                e.printStackTrace();
            }
        }
        else if(source.getApkFilePath()!=null){
            Bitmap b = Utils.getIconForApk(packageManager, source.getApkFilePath());
            if(b!=null){
                icon = new BitmapDrawable(con.getResources(), b);
            }
        }
        else if(source.getIconResName()!=null){
            String iconResName = source.getIconResName();
            Bitmap bm = Utils.getIconBitmapFromResName(iconResName, con);
            if(bm!=null) {
                icon = new BitmapDrawable(con.getResources(), bm);
            }
        }
        return new SimpleResource<>(icon);
    }

}
```

Keep in mind that the issue was present in Glide v 4.10.0. 

Same way to reproduce it but with a different exception message which was the following:

```
Attempt to invoke interface method 'int com.bumptech.glide.load.engine.Resource.getSize()' on a null object reference
com.bumptech.glide.load.engine.LockedResource.getSize (LockedResource.java:81)
com.bumptech.glide.load.engine.EngineResource.getSize (EngineResource.java:62)
com.bumptech.glide.load.engine.cache.LruResourceCache.getSize (LruResourceCache.java:40)
com.bumptech.glide.load.engine.cache.LruResourceCache.getSize (LruResourceCache.java:11)
com.bumptech.glide.util.LruCache.trimToSize (LruCache.java:171)
com.bumptech.glide.util.LruCache.evict (LruCache.java:179)
com.bumptech.glide.util.LruCache.put (LruCache.java:134)
com.bumptech.glide.load.engine.cache.LruResourceCache.put (LruResourceCache.java:11)
com.bumptech.glide.load.engine.Engine.onResourceReleased (Engine.java:394)
com.bumptech.glide.load.engine.EngineResource.release (EngineResource.java:116)
com.bumptech.glide.load.engine.Engine.release (Engine.java:362)
com.bumptech.glide.request.SingleRequest.clear (SingleRequest.java:326)
com.bumptech.glide.manager.RequestTracker.clearAndRemove (RequestTracker.java:72)
com.bumptech.glide.RequestManager.untrack (RequestManager.java:663)
com.bumptech.glide.RequestManager.untrackOrDelegate (RequestManager.java:631)
com.bumptech.glide.RequestManager.clear (RequestManager.java:627)
com.bumptech.glide.RequestManager.onDestroy (RequestManager.java:374)
com.bumptech.glide.manager.ActivityFragmentLifecycle.onDestroy (ActivityFragmentLifecycle.java:65)
com.bumptech.glide.manager.SupportRequestManagerFragment.onDestroy (SupportRequestManagerFragment.java:215)
```
[crash_video.zip](https://github.com/bumptech/glide/files/4081604/crash_video.zip)

**Comment by VasilisKatsoris** [comment]
..?

**Comment by kaiattrib** [comment]
Have you solved ?

**Comment by chubecode** [comment]
Still got error..

**Comment by agvozdik-tu** [comment]
Got that error as well in v.4.11.0. Cannot reproduce but can see few crashes in production with stacktrace mentioned above.

**Comment by amg** [comment]
Got that error as well in v.4.11.0. Cannot reproduce but can see few crashes in production with stacktrace mentioned above.

**Comment by ninesoltech** [comment]
To Remove this issue please add   
**.diskCacheStrategy(DiskCacheStrategy.NONE)
.skipMemoryCache(true)**
if your are caching images via signature make sure to override equal and hashcode method of signature class 
while setting signature to glide 
**.signature(IntegerVersionSignature(path))**
Signature Class
```
class IntegerVersionSignature(var curentImgPth: String) : Key {

  var genericUniqueFlag:ByteArray?=null
    override fun equals(o: Any?): Boolean {
        if (o is IntegerVersionSignature) {
            return o.genericUniqueFlag?.equals(genericUniqueFlag)?:o.curentImgPth.equals(curentImgPth)
        }
        return false
    }


    override fun updateDiskCacheKey(messageDigest: MessageDigest) {
        val modLast = File(curentImgPth).lastModified()
        genericUniqueFlag = (modLast.toString() + curentImgPth + "${(0..10).random()}").toByteArray()
        // messageDigest.update(ByteBuffer.allocate(Integer.SIZE).putInt().array())
        messageDigest.update(genericUniqueFlag)
    }

    override fun hashCode(): Int {
        var result = curentImgPth.hashCode()
        result = 31 * result + (genericUniqueFlag?.contentHashCode() ?: 0)
        return result
    }


}
```
