### ISSUE TITLE
java.lang.IllegalArgumentException: You must not call setTag() on a view Glide is targeting

### ISSUE THREAD

**Issue by NicolasGodfather** [bumptech/glide#4060]
**Glide Version**:
implementation("com.github.bumptech.glide:glide:4.9.0") {
        exclude group: "com.android.support"
    }
    kapt 'com.github.bumptech.glide:compiler:4.9.0'

**Integration libraries**:no

**Device/Android Version**: Samsung SM-J260F Android 8.1.0 api 27 and other real devices

**Issue details / Repro steps / Use case background**: 
Bug still reproducing in v4.9.0 - how fix it??? In my case I have 3 fragments(F1, F2, F3) in my activity (A1). Glide load urls in items of recyclerview in F2. Crash happens when backpressed from F3->F2->F1->exit from app. It seem a long bug in glide since v4.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```kotlin
 private fun loadImage(url: File, holder: GridViewHolder) {
        val requestOptions = RequestOptions()
                .override(960, 540)
        if (activity is MainActivity && !activity.isFinishing && !activity.isDestroyed) {
            val glide = Glide.with(activity)
                    .setDefaultRequestOptions(requestOptions)
                    .load(url)
            if (holder.image != null) {
                glide.into(holder.image)
            }
        }
    }
```

**Layout XML**:
```xml
  <androidx.cardview.widget.CardView
        android:layout_width="match_parent"
        android:layout_height="130dp"
        app:cardCornerRadius="4dp"
        app:cardElevation="0dp">

        <ImageView
            android:id="@+id/img_screenshot"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:scaleType="centerCrop" />

    </androidx.cardview.widget.CardView>

**Stack trace / LogCat**:
```ruby
2020-01-21 16:27:38.011 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xxx, PID: 24813
    java.lang.RuntimeException: Unable to destroy activity {xxx.MainActivity}: java.lang.IllegalArgumentException: You must not call setTag() on a view Glide is targeting
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4411)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4429)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1655)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6543)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
     **Caused by: java.lang.IllegalArgumentException: You must not call setTag() on a view Glide is targeting**
        at com.bumptech.glide.request.target.ViewTarget.getRequest(ViewTarget.java:271)
        at com.bumptech.glide.RequestManager.untrack(RequestManager.java:624)
        at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:598)
        at com.bumptech.glide.RequestManager.clear(RequestManager.java:594)
        at com.bumptech.glide.RequestManager.onDestroy(RequestManager.java:339)
        at com.bumptech.glide.manager.ActivityFragmentLifecycle.onDestroy(ActivityFragmentLifecycle.java:65)
        at com.bumptech.glide.manager.SupportRequestManagerFragment.onDestroy(SupportRequestManagerFragment.java:194)
        at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2830)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1028)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2644)
        at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:329)
        at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:366)
        at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:233)
        at xxx.MainActivity.onDestroy(MainActivity.kt:600)
        at android.app.Activity.performDestroy(Activity.java:7218)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4398)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4429) 
        at android.app.ActivityThread.-wrap5(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1655) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6543) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810) 
```

**Comment by weizaishouex2010** [comment]
> **Glide Version**:
> implementation("com.github.bumptech.glide:glide:4.9.0") {
> exclude group: "com.android.support"
> }
> kapt 'com.github.bumptech.glide:compiler:4.9.0'
> 
> **Integration libraries**:no
> 
> **Device/Android Version**: Samsung SM-J260F Android 8.1.0 api 27 and other real devices
> 
> **Issue details / Repro steps / Use case background**:
> Bug still reproducing in v4.9.0 - how fix it??? In my case I have 3 fragments(F1, F2, F3) in my activity (A1). Glide load urls in items of recyclerview in F2. Crash happens when backpressed from F3->F2->F1->exit from app. It seem a long bug in glide since v4.
> 
> **Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
> 
> ```kotlin
>  private fun loadImage(url: File, holder: GridViewHolder) {
>         val requestOptions = RequestOptions()
>                 .override(960, 540)
>         if (activity is MainActivity && !activity.isFinishing && !activity.isDestroyed) {
>             val glide = Glide.with(activity)
>                     .setDefaultRequestOptions(requestOptions)
>                     .load(url)
>             if (holder.image != null) {
>                 glide.into(holder.image)
>             }
>         }
>     }
> ```
> 
> **Layout XML**:
> 
> ```
>   <androidx.cardview.widget.CardView
>         android:layout_width="match_parent"
>         android:layout_height="130dp"
>         app:cardCornerRadius="4dp"
>         app:cardElevation="0dp">
> 
>         <ImageView
>             android:id="@+id/img_screenshot"
>             android:layout_width="match_parent"
>             android:layout_height="match_parent"
>             android:scaleType="centerCrop" />
> 
>     </androidx.cardview.widget.CardView>
> 
> **Stack trace / LogCat**:
> ```ruby
> 2020-01-21 16:27:38.011 E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: xxx, PID: 24813
>     java.lang.RuntimeException: Unable to destroy activity {xxx.MainActivity}: java.lang.IllegalArgumentException: You must not call setTag() on a view Glide is targeting
>         at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4411)
>         at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4429)
>         at android.app.ActivityThread.-wrap5(Unknown Source:0)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1655)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6543)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
>      **Caused by: java.lang.IllegalArgumentException: You must not call setTag() on a view Glide is targeting**
>         at com.bumptech.glide.request.target.ViewTarget.getRequest(ViewTarget.java:271)
>         at com.bumptech.glide.RequestManager.untrack(RequestManager.java:624)
>         at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:598)
>         at com.bumptech.glide.RequestManager.clear(RequestManager.java:594)
>         at com.bumptech.glide.RequestManager.onDestroy(RequestManager.java:339)
>         at com.bumptech.glide.manager.ActivityFragmentLifecycle.onDestroy(ActivityFragmentLifecycle.java:65)
>         at com.bumptech.glide.manager.SupportRequestManagerFragment.onDestroy(SupportRequestManagerFragment.java:194)
>         at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2830)
>         at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1028)
>         at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
>         at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
>         at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
>         at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2644)
>         at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:329)
>         at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:366)
>         at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:233)
>         at xxx.MainActivity.onDestroy(MainActivity.kt:600)
>         at android.app.Activity.performDestroy(Activity.java:7218)
>         at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249)
>         at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4398)
>         at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4429) 
>         at android.app.ActivityThread.-wrap5(Unknown Source:0) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1655) 
>         at android.os.Handler.dispatchMessage(Handler.java:106) 
>         at android.os.Looper.loop(Looper.java:164) 
>         at android.app.ActivityThread.main(ActivityThread.java:6543) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810) 
> ```

I meet the same problem, do you solve this?
