### ISSUE TITLE
[RANDOM CRASH] Unexpected exception thrown by non-Glide code

### ISSUE THREAD

**Issue by HighA** [bumptech/glide#4061]
**Glide Version**:4.10.0

**Integration libraries**:none

**Device/Android Version**:MotorolaG4 / API 24

**Issue details / Repro steps / Use case background**:  It happens when a distant image is loaded into an ImageView, randomly, I can't reproduce it myself I just let the app run and at some point (can take hours or days) it will happen, then after the app will keep crashing and restarting until I manually kill it.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(getApplicationContext())
                            .asBitmap()
                            .load(*a_valid_url*)
                            .diskCacheStrategy(DiskCacheStrategy.NONE)
                            .skipMemoryCache(true)
                            .apply(new RequestOptions().override(1000, 1000))
                            .centerCrop()
                            .placeholder(R.drawable.holder)
                            .error(R.drawable.error)
                            .into(new SimpleTarget<Bitmap>() {
                                @Override
                                public void onResourceReady(Bitmap resource, Transition<? super Bitmap> transition) {
                                    bitmap_cover = resource;
                                    lockscreen_background = resource;
                                    backCoverLoad(bitmap_cover, previous, current);                                   
                                }
                            });
```
When the image has been loaded as bitmap into bitmap_cover, I call another function to load it into the imageview :
```
public void backCoverLoad(Bitmap bitmap, String previous, String current)
    {
        Glide.with(getApplicationContext())
                .load(bitmap)
                .apply(new RequestOptions().override(1000, 1000))
                .centerCrop()
                .apply(options_front)
                .placeholder(R.drawable.holder)
                .error(R.drawable.error)
                .listener(new RequestListener<Drawable>() {
                    @Override
                    public boolean onLoadFailed( GlideException e, Object model, Target<Drawable> target, boolean isFirstResource)
                    {
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource)
                    {
                        return false;
                    }
                })
                .into(cover);
```

**Layout XML**:
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".RadioFragment">

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <androidx.constraintlayout.widget.Guideline
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:id="@+id/horizontal_center_guideline"
            android:orientation="vertical"
            app:layout_constraintGuide_percent="0.5"/>
        <androidx.constraintlayout.widget.Guideline
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:id="@+id/top_cover_guideline"
            android:orientation="horizontal"
            app:layout_constraintGuide_percent="0.1"/>

        <androidx.constraintlayout.widget.Guideline
            android:id="@+id/left_cover_guideline"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:layout_constraintGuide_percent="0.25"
            android:orientation="vertical"/>

        <androidx.constraintlayout.widget.Guideline
            android:id="@+id/right_cover_guideline"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:layout_constraintGuide_percent="0.75"
            android:orientation="vertical"/>

        <ImageView
            android:id="@+id/background_blur"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintBottom_toBottomOf="parent"
            android:scaleType="centerCrop"
            android:adjustViewBounds="true"/>

        <ImageView
            android:id="@+id/front_blur"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintBottom_toBottomOf="parent"
            android:scaleType="centerCrop"
            android:adjustViewBounds="true"/>

        <ImageView
            android:id="@+id/frontDark"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintBottom_toBottomOf="parent"
            android:scaleType="centerCrop"
            android:background="#59000000"
            android:visibility="invisible"/>

        <ImageView
            android:id="@+id/homescreen"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintBottom_toBottomOf="parent"
            android:scaleType="centerCrop"
            android:src="@drawable/homescreen_background"/>

        <ImageView
            android:id="@+id/back_cover"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            app:layout_constraintLeft_toLeftOf="@+id/left_cover_guideline"
            app:layout_constraintRight_toRightOf="@+id/right_cover_guideline"
            app:layout_constraintTop_toTopOf="@+id/top_cover_guideline"
            android:scaleType="fitStart"
            android:layout_alignParentTop="true"
            android:layout_gravity="top"
            android:gravity="top"
            android:adjustViewBounds="true"/>

        <ImageView
            android:id="@+id/front_cover"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            app:layout_constraintLeft_toLeftOf="@+id/left_cover_guideline"
            app:layout_constraintRight_toRightOf="@+id/right_cover_guideline"
            app:layout_constraintTop_toTopOf="@+id/top_cover_guideline"
            android:scaleType="fitStart"
            android:layout_alignParentTop="true"
            android:layout_gravity="top"
            android:gravity="top"
            android:adjustViewBounds="true"/>
    </androidx.constraintlayout.widget.ConstraintLayout>
</androidx.coordinatorlayout.widget.CoordinatorLayout>
```
**Stack trace / LogCat**:
```2020-01-22 20:50:07.160 5124-5124/com.laprise.app W/Glide: Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
2020-01-22 20:50:07.257 5124-5124/com.laprise.app W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
2020-01-22 20:50:07.806 5124-5124/com.laprise.app D/AndroidRuntime: Shutting down VM
2020-01-22 20:50:08.021 5124-5158/com.laprise.app I/FA: Tag Manager is not found and thus will not be used
2020-01-22 20:50:08.023 5124-5124/com.laprise.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.laprise.app, PID: 5124
    com.bumptech.glide.load.engine.CallbackException: Unexpected exception thrown by non-Glide code
        at com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:160)
        at com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:424)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
     Caused by: java.lang.NullPointerException: Argument must not be null
        at com.bumptech.glide.util.Preconditions.checkNotNull(Preconditions.java:29)
        at com.bumptech.glide.util.Preconditions.checkNotNull(Preconditions.java:23)
        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:669)
        at com.laprise.app.PlayerInterfaceService.backCoverLoad(PlayerInterfaceService.java:344)
        at com.laprise.app.PlayerInterfaceService$1.onResourceReady(PlayerInterfaceService.java:253)
        at com.laprise.app.PlayerInterfaceService$1.onResourceReady(PlayerInterfaceService.java:229)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:624)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:568)
        at com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:158)
        at com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:424) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6123) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
2020-01-22 20:50:08.059 5124-5158/com.laprise.app D/FA: Logging event (FE): app_exception(_ae), Bundle[{ga_event_origin(_o)=clx, _r=1, timestamp=1579722607809, fatal=1}]
```

**Comment by vishrut2207** [comment]
@HighA I am also facing the same issue.
Did you get any solution for It?

**Comment by arivalencia** [comment]
Tengo el mismo problema, ¿Encontraron la solución?

**Comment by Mujas** [comment]
Any Solution? facing same issue

**Comment by amalnafia** [comment]
any solution ?

**Comment by ArunShankar-yotta** [comment]
Try this, cover the code with Handler(Looper.getMainLooper()).post { //glide code }
