### ISSUE TITLE
Glide stopped loading svg files after AndroidX migration

### ISSUE THREAD

**Issue by srijith1979** [bumptech/glide#4064]
**Glide Version**:

4.10.0

implementation 'com.github.bumptech.glide:glide:4.10.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.10.0'

**Integration libraries**:
We make a Retrofit call (uses okhttp3) in the app to get the svg url

**Device/Android Version**:

Samsung S9, Android 9

**Issue details**: 

We are using glide to load svg files. Glide is used in a separate library of our app. We recently migrated our app to AndroidX and all of a sudden Glide stopped working. 

I see the below exceptions logged to the console

```
java.lang.IllegalStateException: Failed to find any load path from class android.net.Uri$StringUri to class android.graphics.drawable.PictureDrawable
        at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:57)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:276)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
2020-01-23 17:27:53.327 7342-7515/com.cerner.wellness.healthypath.play E/GlideExecutor: Request threw uncaught throwable
    java.lang.IllegalStateException: Failed to find any load path from class android.net.Uri$StringUri to class android.graphics.drawable.PictureDrawable
        at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:57)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:276)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)

Load failed for https://svgur.com/i/HX0.svg with size [613x154]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.lang.IllegalStateException(Failed to find any load path from class android.net.Uri$StringUri to class android.graphics.drawable.PictureDrawable)

```

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java

        requestBuilder =
                Glide.with(this)  //since glide is used in a library, I cannot find GlideApp.with
                        .as(PictureDrawable.class)
                        .listener(new SvgSoftwareLayerSetter());

        //and finally, use this requestBuilder

        requestBuilder.load(Uri.parse(imageUrl)).centerInside().into(logoImageView);

```

**Layout XML**:
```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">

    <ImageView
        android:id="@+id/actionBarLogo"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        tools:src="@mipmap/hl_logo" />

</RelativeLayout>
```

On a side note, I use all the classes needed to work with SVG. Please find the screenshot below. 

![Screen Shot 2020-01-23 at 5 33 40 PM](https://user-images.githubusercontent.com/16881321/73033080-90e6eb80-3e06-11ea-9752-cdfbf3b81c29.png)

Looking forward for your help on this. Thanks

**Comment by elisealix22** [comment]
I think you might need `GlideApp.with()` instead of `Glide.with()`. GlideApp is generated from the `@GlideModule` annotation on a `AppGlideModule` (likely your `SvgModule`). Hope that helps!

**Comment by srijith1979** [comment]
@elisealix22  thanks for your response.

However, I am using Glide in a library module and not in the app. All I see is a `Glide.with()` and not `GlideApp.with()`. I have tried `@GlideModule` annotation on a `AppGlideModule` (please find the screenshot above) but nothing works.

However, I could get `GlideApp.with()` in the main app (not in the library module) with `@GlideModule` annotation.

Is there any way you could think of for `GlideApp.with()` to appear in the library module?

I appreciate your response. Thanks.
