### ISSUE TITLE
java.lang.IllegalStateException: Can't call reconfigure() on a recycled bitmap

### ISSUE THREAD

**Issue by vaxus** [bumptech/glide#408]
**Glide Version/Integration library (if any)**: 3.5.2
**Device/Android Version**: HTC One M8. KitKat 4.4.4
**Issue details/Repro steps**:
My imageviews have a predefined size (90dp x 90dp, not using wrap_content).

If I back out of the listview and reload it or scroll up and down, the images sometimes load correctly.

I've double checked the image links and there's no issue with them either.

Note: I'm using the viewholder pattern in my adapter to load images into my listview.

Here's my adapter code:

    ArrayList ItemArrayList;

    if (view == null) {
        LayoutInflater inflater = (LayoutInflater) viewGroup.getContext().getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        row = inflater.inflate(R.layout.item_row, viewGroup, false);
        holder = new ItemHolder(row);
        row.setTag(holder);
    }

    else {
        row = view;
        holder = (ItemHolder) row.getTag();
    }

    Glide.with(viewGroup.getContext()).load(ItemArrayList.get(position).getItemImage()).transform(new GlideCircleTransform(c)).error(R.drawable.mm_avatar).into(holder.itemImage);

After using adb debugging, I get the following error on failed image loads:

    java.lang.IllegalStateException: Can't call reconfigure() on a recycled bitmap

**Glide load line**:
       Glide.with(viewGroup.getContext()).load(ItemArrayList.get(position).getItemImage()).transform(new GlideCircleTransform(c)).error(R.drawable.mm_avatar).into(holder.itemImage);

**Stack trace**:
```
    java.lang.IllegalStateException: Can't call reconfigure() on a recycled bitmap
            at android.graphics.Bitmap.checkRecycled(Bitmap.java:668)
            at android.graphics.Bitmap.reconfigure(Bitmap.java:460)
            at com.bumptech.glide.load.engine.bitmap_recycle.SizeConfigStrategy.get(SizeConfigStrategy.java:72)
            at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.getDirty(LruBitmapPool.java:130)
            at com.bumptech.glide.load.resource.bitmap.Downsampler.downsampleWithSize(Downsampler.java:215)
            at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:151)
            at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:50)
            at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
            at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:39)
            at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)
            at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeBitmapWrapper(GifBitmapWrapperResourceDecoder.java:121)
            at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeStream(GifBitmapWrapperResourceDecoder.java:94)
            at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:71)
            at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:61)
            at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:22)
            at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:190)
            at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
            at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
            at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
            at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
            at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:864)
            at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:52)
```

**Comment by sjudd** [comment]
Can you provide the full stack trace? and fill out the [issue template][1]?

This is branched out of #395.

**Comment by krohnjw** [comment]
Seeing the same issue here:

**Glide Version/Integration library (if any)**:
3.5.2

**Device/Android Version**:
Nexus 5 - 5.1
S5 - 4.4.X
S3 - 4.3

**Issue details/Repro steps**:
Intermittent.  URI's reolve fine when manually queried.  Backing out and relaunching the activity will generally work to properly load the image when it fails.

**Glide load line**:
Glide.with(this).load(Uri.parse(uri)).into(imageView); // Scoped to Activity Lifecycle

**Stack trace**:
java.lang.IllegalStateException: Can't call reconfigure() on a recycled bitmap
  at android.graphics.Bitmap.checkRecycled(Bitmap.java:347)
  at android.graphics.Bitmap.reconfigure(Bitmap.java:219)
  at com.bumptech.glide.load.engine.bitmap_recycle.SizeConfigStrategy.get(SizeConfigStrategy.java:72)
  at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.getDirty(LruBitmapPool.java:130)
  at com.bumptech.glide.load.resource.bitmap.Downsampler.downsampleWithSize(Downsampler.java:215)
  at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:151)
  at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:50)
  at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
  at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:39)
  at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)
  at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeBitmapWrapper(GifBitmapWrapperResourceDecoder.java:121)
  at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeStream(GifBitmapWrapperResourceDecoder.java:94)
  at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:71)
  at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:61)
  at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:22)
  at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:190)
  at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
  at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
  at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
  at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
  at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
  at java.lang.Thread.run(Thread.java:818)
  at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:52)

**Comment by sjudd** [comment]
Usually this is the result of misusing Bitmaps, either by returning a Bitmap to the pool multiple times without an intermediate get, or by referencing the Bitmap after calling ``clear()`` on the corresponding Target. If you have custom transformations, that's a good place to look closely to make sure you aren't returning a Bitmap to the pool twice. You can see more about this issue on the wiki: https://github.com/bumptech/glide/wiki/Resource-re-use-in-Glide.

If you can reproduce in a sample app I can definitely help debug. Unfortunately the nature of this problem makes it really hard to suggest solutions otherwise.

**Comment by krohnjw** [comment]
Clear is never explicitly called nor any explicit bitmap manipulation outside of some transformations.

Could this be caused by 2x requests within 100ms to load the same resource (URI) into different views (e.g. preview view and a gallery) and both recycling the "source" in their respective transformations?

**Comment by TWiStErRob** [comment]
Can you provide your Transformations' source (if custom)? (There aren't any in your Glide load line).
Also what is your "other" ImageView Glide load line. (If you start two loads, how do you know which load the above stacktrace belongs to?)

**Comment by krohnjw** [comment]
It wasn't included as the error when loading that was reported doesn't contain any transform.

Since then I've added some exception handling via the request listener and retries.  This reveals it happening far more often than initially expected.  There's a number of *dead* image links on CDNs within our sandbox environment so I had incorrectly assumed that gallery / preview images that did not load were a result of this.  But after logging all exceptions here It would appear that often it's a result of the above error and not dead links.

Here's the flow:
Fragment A loads the same image into a "hero" image and then into the gallery (it's one of many loaded into the gallery).  So, for 5 images 1 will be loaded twice while 2-5 will be loaded once.

On Gallery item click the same image is loaded in a separate activity and undergoes no transformation.

I'm tracking the both the success and failure for the View ID as well as the unique request id (long - time in millis assigned on load call) via a RequestListener (which is used to optionally dynamically show / hide loading and error indicators).

Transform source below.  Note that there are only utilized in the initial fragment load.  In the instance of the full screen view (initiated by a click on the gallery image) there is no transformation used.

To "work around" the issue I can catch the exception in the request listener and dispatch a retry after a short delay (e.g. 500ms).  This seems to work reasonably well to get the images to load properly but is a real hack job.

Circle Transform (hero)
````
        int size = Math.min(source.getWidth(), source.getHeight());
        int x = (source.getWidth() - size) / 2;
        int y = (source.getHeight() - size) / 2;
        Bitmap squaredBitmap = Bitmap.createBitmap(source, x, y, size, size);
        if (squaredBitmap != source) {
            source.recycle();
        }
        Bitmap bitmap = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bitmap);
        Paint paint = new Paint();
        BitmapShader shader = new BitmapShader(squaredBitmap, BitmapShader.TileMode.CLAMP, BitmapShader.TileMode.CLAMP);
        paint.setShader(shader);
        paint.setAntiAlias(true);
        float r = size / 2f;
        canvas.drawCircle(r, r, r, paint);
        squaredBitmap.recycle();
        return bitmap;
````


Variable Width Transformation (Gallery - item is RecyclerView ViewHolder)
````
            double aspectRatio = (double) source.getWidth() / (double) source.getHeight();
            int targetWidth = (int) (mHeight * aspectRatio);
            Bitmap result = Bitmap.createScaledBitmap(source, targetWidth, mHeight, false);
            if (result != source) {
                // Same bitmap is returned if sizes are the same
                source.recycle();
            }
            return result;
````

The only difference in the load lines is the utilization of the transformation.  Modifying disk caching strategies seems to have no effect on the issue either.

It's really easy to recreate here so I'm happy to make any transform modifications or pull up any more info that might be helpful.

**Comment by krohnjw** [comment]
@TWiStErRob It looks like that's the circle transform we currently utilize.  Let me pull this out and see if the issue persists.

**Comment by sjudd** [comment]
Try not calling ``source.recycle()``. If that's the Bitmap Glide passes in to you, that will definitely cause problems.

**Comment by krohnjw** [comment]
That is the bitmap from Glide itself as delivered in onResourceReady.  Let me pull those out and see what happens.

**Comment by sjudd** [comment]
@TWiStErRob Argh you're right, there are a lot of problems with that answer. 

I could just go in and edit it...

**Comment by krohnjw** [comment]
It looks like removing the recycle call resolves the issue unless I'm incredibly lucky (unlucky?) so far.  What was able to be recreated trivially has no worked 40+ times in a row.

Is the solution to never recycle the source bitmap in transformations?

**Comment by TWiStErRob** [comment]
I'll update the SO answer so we'll have a reference, you can then utilize that fixed class.

**Comment by sjudd** [comment]
Yes, you don't want to ever recycle the source Bitmap. It's a little wonky but Glide takes care of reusing/recycling the Bitmap it passes into the Transformation. The original idea was to reduce the duplicated work (every transformation would end with the same few lines), but it's probably more confusing than it's worth.

The transformation also wastes a few opportunities to re-use Bitmaps, which hopefully @TWiStErRob  is working on fixing too :)

**Comment by TWiStErRob** [comment]
@krohnjw updated SO answer, you may need to work a little more if you want to be as performant as possible, becuase `squared` could come from the pool. and then you'll have to `drawBitmap` to a `Canvas(squared)` with the correct coordinates.

@vaxus Can you please also pull the changes from the [SO answer](http://stackoverflow.com/a/25806229/253468) and confirm that it doesn't happen any more?

@sjudd "Yes, you don't want to ever recycle the source Bitmap." should be in the javadoc ;)

**Comment by krohnjw** [comment]
@TWiStErRob Thanks.  I'll go ahead to pull that in and go from there.

Given previous experience in the *recycle all bitmaps possible!* mentality it was really counter intuitive to *not* recycle the bitmap there.  Given the explanation it makes sense, but I don't recall running across this in the Glide docs.

Thanks for helping track this down.

**Comment by sjudd** [comment]
Yes you're right, I really need to update the javadoc. I keep thinking I've put that in there, but I double checked and I haven't. Given how confusing the behavior is I absolutely need to update it: Filed #422

**Comment by sjudd** [comment]
I think this is fixed? Feel free to re-open if something still isn't resolved here.

**Comment by marcelonoguti** [comment]
I used to have this issue as well, in my case I was using the transformation BrightnessFilterTransformation. The public method 'transform' just recycled the bitmap at the end and seemed to be the reason for the issue.
