### ISSUE TITLE
Annotation processor can't handle more than 5 library modules

### ISSUE THREAD

**Issue by TWiStErRob** [bumptech/glide#4106]
**Glide Version**: 4.12.0

**Integration libraries**: none / all

**Device/Android Version**: all

**Build system**: Gradle 5.6.4 on Windows 10

**Issue details / Repro steps / Use case background**:
Having 5-6 library modules in the project (depending on package and class names) stops AppGlideModule from compiling.

1. Get this project: https://github.com/TWiStErRob/repros/tree/master/glide/apt_many_libs
1. `gradlew assembleDebug --stacktrace` -> fails

Expected:
same behavior as when there are less modules, e.g.
1. Delete `LibModule6.java`, or comment it out, or remove `@GlideModule`.
1. `gradlew assembleDebug --stacktrace` -> all good

Actual: see stack trace.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
package com.example.application.pack.age;
@GlideModule public final class AppModule extends AppGlideModule { }
@GlideModule public class LibModule1 extends LibraryGlideModule { }
@GlideModule public class LibModule2 extends LibraryGlideModule { }
@GlideModule public class LibModule3 extends LibraryGlideModule { }
@GlideModule public class LibModule4 extends LibraryGlideModule { }
@GlideModule public class LibModule5 extends LibraryGlideModule { }
@GlideModule public class LibModule6 extends LibraryGlideModule { }
```

**Layout XML**: N/A

**Stack trace / LogCat**:
<details>
  <summary>

Execution failed for task ':compileDebugJavaWithJavac'.
  > java.lang.RuntimeException: java.io.FileNotFoundException: 
 > P:\projects\bugs\glide\apt_many_libs\build\generated\ap_generated_sources\debug\out\com\bumptech\glide\annotation\compiler\GlideIndexer_GlideModule_com_example_application_pack_age_LibModule1_com_example_application_pack_age_LibModule2_com_example_application_pack_age_LibModule3_com_example_application_pack_age_LibModule4_com_example_application_pack_age_LibModule5_com_example_application_pack_age_LibModule6.java (The filename, directory name, or volume label syntax is incorrect)
  **Click to expand...**
  </summary>

  ```ruby
  > Task :compileDebugJavaWithJavac FAILED

  FAILURE: Build failed with an exception.

  * What went wrong:
  Execution failed for task ':compileDebugJavaWithJavac'.
  > java.lang.RuntimeException: java.io.FileNotFoundException: P:\projects\bugs\glide\apt_many_libs\build\generated\ap_generated_sources\debug\out\com\bumptech\glide\annotation\compiler\GlideIndexer_GlideModule_com_example_application_pack_age_LibModule1_com_example_application_pack_age_LibModule
  2_com_example_application_pack_age_LibModule3_com_example_application_pack_age_LibModule4_com_example_application_pack_age_LibModule5_com_example_application_pack_age_LibModule6.java (The filename, directory name, or volume label syntax is incorrect)

  * Try:
  Run with --info or --debug option to get more log output. Run with --scan to get full insights.

  * Exception is:
  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileDebugJavaWithJavac'.
          at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
          at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
          at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
          at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
          at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
          at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
          at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
          at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
          at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
          at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
          at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
          at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
          at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
          at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
          at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
          at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
          at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
          at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
          at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
          at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
          at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
          at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
          at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
          at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
          at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
          at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
          at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
          at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
          at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
          at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
          at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
          at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
          at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
          at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
          at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
          at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
          at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
          at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
          at java.lang.Thread.run(Thread.java:748)
  Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.io.FileNotFoundException: P:\projects\bugs\glide\apt_many_libs\build\generated\ap_generated_sources\debug\out\com\bumptech\glide\annotation\compiler\GlideIndexer_GlideModule_com_example_application_pack_age_LibModule1_com_e
  xample_application_pack_age_LibModule2_com_example_application_pack_age_LibModule3_com_example_application_pack_age_LibModule4_com_example_application_pack_age_LibModule5_com_example_application_pack_age_LibModule6.java (The filename, directory name, or volume label syntax is incorrect)
          at com.sun.tools.javac.main.Main.compile(Main.java:553)
          at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
          at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
          at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.call(AnnotationProcessingCompileTask.java:93)
          at org.gradle.api.internal.tasks.compile.ResourceCleaningCompilationTask.call(ResourceCleaningCompilationTask.java:57)
          at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:54)
          at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:39)
          at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:100)
          at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:52)
          at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
          at org.gradle.api.internal.tasks.compile.AnnotationProcessorDiscoveringCompiler.execute(AnnotationProcessorDiscoveringCompiler.java:51)
          at org.gradle.api.internal.tasks.compile.AnnotationProcessorDiscoveringCompiler.execute(AnnotationProcessorDiscoveringCompiler.java:37)
          at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:39)
          at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilerFactory$2.execute(IncrementalCompilerFactory.java:101)
          at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilerFactory$2.execute(IncrementalCompilerFactory.java:97)
          at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringCompiler.execute(IncrementalResultStoringCompiler.java:60)
          at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringCompiler.execute(IncrementalResultStoringCompiler.java:44)
          at org.gradle.api.internal.tasks.compile.CompileJavaBuildOperationReportingCompiler$2.call(CompileJavaBuildOperationReportingCompiler.java:59)
          at org.gradle.api.internal.tasks.compile.CompileJavaBuildOperationReportingCompiler$2.call(CompileJavaBuildOperationReportingCompiler.java:51)
          at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
          at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
          at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
          at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
          at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
          at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
          at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
          at org.gradle.api.internal.tasks.compile.CompileJavaBuildOperationReportingCompiler.execute(CompileJavaBuildOperationReportingCompiler.java:51)
          at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:158)
          at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:126)
          at com.android.build.gradle.tasks.AndroidJavaCompile.compile(AndroidJavaCompile.kt:237)
          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
          at java.lang.reflect.Method.invoke(Method.java:498)
          at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
          at org.gradle.api.internal.project.taskfactory.IncrementalTaskInputsTaskAction.doExecute(IncrementalTaskInputsTaskAction.java:47)
          at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
          at org.gradle.api.internal.project.taskfactory.AbstractIncrementalTaskAction.execute(AbstractIncrementalTaskAction.java:25)
          at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
          at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
          at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
          at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
          at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
          at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
          at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
          at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
          at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
          at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
          at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
          at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
          at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
          at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$0(ExecuteStep.java:32)
          at java.util.Optional.map(Optional.java:215)
          at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:32)
          at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
          at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
          at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
          at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
          at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
          at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
          at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
          at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
          at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
          at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
          at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
          at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
          at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
          at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
          at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
          at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
          at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
          at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
          at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
          at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
          at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
          at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
          at java.util.Optional.map(Optional.java:215)
          at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
          at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
          at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
          at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
          at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
          at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
          at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
          at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
          at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
          at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
          at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
          at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
          ... 37 more
  Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: P:\projects\bugs\glide\apt_many_libs\build\generated\ap_generated_sources\debug\out\com\bumptech\glide\annotation\compiler\GlideIndexer_GlideModule_com_example_application_pack_age_LibModule1_com_example_application_pack_age_
  LibModule2_com_example_application_pack_age_LibModule3_com_example_application_pack_age_LibModule4_com_example_application_pack_age_LibModule5_com_example_application_pack_age_LibModule6.java (The filename, directory name, or volume label syntax is incorrect)
          at com.bumptech.glide.annotation.compiler.ProcessorUtil.writeClass(ProcessorUtil.java:133)
          at com.bumptech.glide.annotation.compiler.ProcessorUtil.writeIndexer(ProcessorUtil.java:122)
          at com.bumptech.glide.annotation.compiler.LibraryModuleProcessor.processModules(LibraryModuleProcessor.java:47)
          at com.bumptech.glide.annotation.compiler.GlideAnnotationProcessor.process(GlideAnnotationProcessor.java:112)
          at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
          at org.gradle.api.internal.tasks.compile.processing.AggregatingProcessor.process(AggregatingProcessor.java:50)
          at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
          at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.access$401(TimeTrackingProcessor.java:37)
          at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor$5.create(TimeTrackingProcessor.java:99)
          at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor$5.create(TimeTrackingProcessor.java:96)
          at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.track(TimeTrackingProcessor.java:117)
          at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.process(TimeTrackingProcessor.java:96)
          at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
          at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
          at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
          at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
          at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
          at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
          at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
          at com.sun.tools.javac.main.Main.compile(Main.java:523)
          ... 125 more
  Caused by: java.io.FileNotFoundException: P:\projects\bugs\glide\apt_many_libs\build\generated\ap_generated_sources\debug\out\com\bumptech\glide\annotation\compiler\GlideIndexer_GlideModule_com_example_application_pack_age_LibModule1_com_example_application_pack_age_LibModule2_com_example_appli
  cation_pack_age_LibModule3_com_example_application_pack_age_LibModule4_com_example_application_pack_age_LibModule5_com_example_application_pack_age_LibModule6.java (The filename, directory name, or volume label syntax is incorrect)
          at java.io.FileOutputStream.open0(Native Method)
          at java.io.FileOutputStream.open(FileOutputStream.java:270)
          at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
          at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
          at com.sun.tools.javac.file.RegularFileObject.openWriter(RegularFileObject.java:136)
          at com.sun.tools.javac.processing.JavacFiler$FilerWriter.<init>(JavacFiler.java:286)
          at com.sun.tools.javac.processing.JavacFiler$FilerOutputFileObject.openWriter(JavacFiler.java:136)
          at com.bumptech.glide.repackaged.com.squareup.javapoet.JavaFile.writeTo(JavaFile.java:116)
          at com.bumptech.glide.annotation.compiler.ProcessorUtil.writeClass(ProcessorUtil.java:131)
          ... 144 more


  * Get more help at https://help.gradle.org

  BUILD FAILED in 1s
  ```
</details>

**Comment by sjudd** [comment]
Huh, I have a project with 10 library modules at Google. I wonder if the name limit varies by the specific compiler. 

We can probably do something more intelligent by trading off readability. I'm not even sure it's intentional that any particular indexer has every single module and package name listed...

**Comment by TWiStErRob** [comment]
May be just Windows 10, what happens if you build the sample project?

**Comment by TWiStErRob** [comment]
Also, maybe worth looking how Dagger Components handle Modules. Never had a problem even with lots of modules.

**Comment by sjudd** [comment]
Reproduces on OSX: > java.lang.RuntimeException: java.nio.file.FileSystemException: /Users/judds/opensource/repros/glide/apt_many_libs/build/generated/ap_generated_sources/debug/out/com/bumptech/glide/annotation/compiler/GlideIndexer_GlideModule_com_example_application_pack_age_LibModule6_com_example_application_pack_age_LibModule1_com_example_application_pack_age_LibModule3_com_example_application_pack_age_LibModule2_com_example_application_pack_age_LibModule5_com_example_application_pack_age_LibModule4.java: File name too long

**Comment by TWiStErRob** [comment]
Ooh, cool, thanks! What is this indexer btw?
