### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method override(II)Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears

### ISSUE THREAD

**Issue by Hinal1108** [bumptech/glide#4111]
**Glide Version**:4.11.0

**Integration libraries**:com.squareup.okhttp3:logging-interceptor:3.10.0

**Device/Android Version**: Android 10

**Language**: Kotlin

**Stack trace / LogCat**:
```ruby
java.lang.NoSuchMethodError: No virtual method override(II)Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears
```

**Comment by Hinal1108** [comment]
Are you solve it?

**Comment by hoordev** [comment]
I think same too (with kotlin code)

Own code

`val image = Glide.with(context).asBitmap().load(thumnailPhoto).submit().get()`

`Fatal Exception: java.lang.NoSuchMethodError: No interface method acquire()Ljava/lang/Object; in class Landroidx/core/util/Pools$Pool; or its super classes (declaration of 'androidx.core.util.Pools$Pool' appears in /data/app/com.xx.example-3dFouJOsZiRFtl3-7FE55w==/base.apk)
       at com.bumptech.glide.load.engine.Engine$EngineJobFactory.build(Engine.java:589)
       at com.bumptech.glide.load.engine.Engine.waitForExistingOrStartNewJob(Engine.java:257)
       at com.bumptech.glide.load.engine.Engine.load(Engine.java:193)
       at com.bumptech.glide.request.SingleRequest.onSizeReady(SingleRequest.java:449)
       at com.bumptech.glide.request.RequestFutureTarget.getSize(RequestFutureTarget.java:145)
       at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:251)
       at com.bumptech.glide.manager.RequestTracker.runRequest(RequestTracker.java:43)
       at com.bumptech.glide.RequestManager.track(RequestManager.java:674)
       at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:641)
       at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:608)
       at com.bumptech.glide.RequestBuilder.submit(RequestBuilder.java:754)
       at com.bumptech.glide.RequestBuilder.submit(RequestBuilder.java:738)`

**Comment by shalang312** [comment]
Are you solve it?

**Comment by kaitian521** [comment]
Are you solve it?

**Comment by santyarbo** [comment]
Are you solve it?

**Comment by ljk761626336** [comment]
Are you solve it?

**Comment by pokerfce** [comment]
Are you solve it?
