### ISSUE TITLE
java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid

### ISSUE THREAD

**Issue by Lissten** [bumptech/glide#4151]
Broadcasting is restricted on android9.0,I found an exception using glide4.11

STACK_TRACE=java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 32311
	at android.os.Parcel.createException(Parcel.java:1958)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.IActivityManager$Stub$Proxy.registerReceiver(IActivityManager.java:3780)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1488)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1449)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1437)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:623)
	at com.bumptech.glide.manager.DefaultConnectivityMonitor.register(DefaultConnectivityMonitor.java:60)
	at com.bumptech.glide.manager.DefaultConnectivityMonitor.onStart(DefaultConnectivityMonitor.java:106)
	at com.bumptech.glide.manager.ActivityFragmentLifecycle.addListener(ActivityFragmentLifecycle.java:37)
	at com.bumptech.glide.RequestManager.<init>(RequestManager.java:144)
	at com.bumptech.glide.RequestManager.<init>(RequestManager.java:106)
	at com.bumptech.glide.manager.RequestManagerRetriever$1.build(RequestManagerRetriever.java:490)
	at com.bumptech.glide.manager.RequestManagerRetriever.supportFragmentGet(RequestManagerRetriever.java:438)
	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:130)
	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:108)
	at com.bumptech.glide.Glide.with(Glide.java:776)

**Comment by Nirmal-Grubbrr** [comment]
I am facing the same issue.

**Comment by Sharmila31** [comment]
I am facing the same issue, unable to reproduce it, any suggestions would be helpful?
