### ISSUE TITLE
com.bumptech.glide.Glide.trimMemory(Glide.java:688)  

### ISSUE THREAD

**Issue by Belka1000867** [bumptech/glide#4162]
**Glide Version**:4.11.0

**Integration libraries**:

**Device/Android Version**:  8.0.0

**Issue details / Repro steps / Use case background**: An error from crashlytics

**Stack trace / LogCat**:
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.bumptech.glide.Glide.trimMemory(Glide.java:688)
       at com.bumptech.glide.Glide.onTrimMemory(Glide.java:900)
       at android.app.Application.onTrimMemory(Application.java:147)
       at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:6137)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2230)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by Warnner0001** [comment]
Hi team
I got this ANR again and version of Glide is 4.12.0 please let me know what should we do??
