### ISSUE TITLE
SSLHandshakeException(Connection closed by peer)  while showing an image 

### ISSUE THREAD

**Issue by Tanhab** [bumptech/glide#4164]
<W/Glide: Load failed for https://firebasestorage.googleapis.com/v0/b/java-project-21.appspot.com/o/yFERY8j8snZesnVfrn74TNekTUR2.jpg?alt=media&token=ba062708-83f6-4d0e-b3fd-d3a9a69ed24d with size [140x140]

    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    javax.net.ssl.SSLHandshakeException(Connection closed by peer)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    javax.net.ssl.SSLHandshakeException(Connection closed by peer)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    javax.net.ssl.SSLHandshakeException(Connection closed by peer)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class javax.net.ssl.SSLHandshakeException: Connection closed by peer
2020-03-29 12:47:18.165 13829-13829/com.example.javaproject21 I/Glide: Root cause (1 of 1)
    javax.net.ssl.SSLHandshakeException: Connection closed by peer
        at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@200616026@20.06.16 (100306-296104215):6)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@200616026@20.06.16 (100306-296104215):14)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:1483)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1427)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1371)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:219)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:142)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:104)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:392)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:325)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:488)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:26)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:100)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:56)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:62)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
        at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
>

**I am getting  javax.net.ssl.SSLHandshakeException(Connection closed by peer) while showing an image from firebase storage. the link is correct and with https. my firebase configuration is also correct. I am using Glide 4.11.0 no integration library.Please, any idea how to fix this? there is no active thread in this issue. **    
my code 
`  Glide.with(view).setDefaultRequestOptions(new RequestOptions().timeout(30*1000)).load(imageUrl).placeholder(R.drawable.classroom).into(imageView);`

**Comment by bwalsh0** [comment]
I've also started running into this exception more frequently recently, roughly 25% of all image requests fail for numerous, valid image URLs. This has been consistent for the past few weeks across many users/devices. Request is usually successful on the 2nd or 3rd attempt.

**Examples of the two common errors in all cases:**
```
java.util.concurrent.ExecutionException: 
com.bumptech.glide.load.engine.GlideException: Failed to load resource

There was 1 cause:
javax.net.ssl.SSLException(Read error: ssl=0x70d811cb88: I/O error during system call, 
Software caused connection abort)
```

```
java.util.concurrent.ExecutionException: 
com.bumptech.glide.load.engine.GlideException: Failed to load resource

There was 1 cause:
java.net.SocketTimeoutException(failed to connect to i.redd.it/151.101.41.140 (port 443) from 
/192.168.1.3 (port 49232) after 60000ms: isConnected failed: ETIMEDOUT (Connection timed out))
```


**Occurred with versions:**
Glide 4.10 with OkHttp3 4.2.2 integration
Glide 4.11 with OkHttp3 4.4.1 integration

**Comment by Dipongkar12** [comment]
Any solution????
