### ISSUE TITLE
VerifyError on KitKat after R8 optimization

### ISSUE THREAD

**Issue by hqzxzwb** [bumptech/glide#4177]
**Glide Version**: 4.11.0

**Integration libraries**: okhttp3

**Device/Android Version**: Redmi 3 4.4. But probably shows on all dalvik devices.

**Issue details / Repro steps / Use case background**: 
Use R8 with proguard-android-optimization.txt rules. The app will crash with a VerifyError.

I am skipping usage details here because it's probably not relevant.

**Stack trace / LogCat**:
```ruby
E/AndroidRuntime(  567): FATAL EXCEPTION: main
E/AndroidRuntime(  567): Process: ***, PID: 567
E/AndroidRuntime(  567): java.lang.VerifyError: l/f/a/m/i/m
E/AndroidRuntime(  567): 	at com.bumptech.glide.Glide.<init>(SourceFile:43)
E/AndroidRuntime(  567): 	at com.bumptech.glide.Glide.a(SourceFile:102)
E/AndroidRuntime(  567): 	at com.bumptech.glide.Glide.a(SourceFile:14)
E/AndroidRuntime(  567): 	at com.bumptech.glide.Glide.b(SourceFile:2)
E/AndroidRuntime(  567): 	at com.bumptech.glide.Glide.a(SourceFile:119)
E/AndroidRuntime(  567): 	at e.a.c.k.c$a.a(SourceFile:122)
E/AndroidRuntime(  567): 	at ***.databinding.BottomButtonBindingImpl.executeBindings(SourceFile:26)
E/AndroidRuntime(  567): 	at androidx.databinding.ViewDataBinding.executeBindingsInternal(SourceFile:11)
E/AndroidRuntime(  567): 	at androidx.databinding.ViewDataBinding.executeBindingsOn(SourceFile:1)
E/AndroidRuntime(  567): 	at ***.databinding.RootViewBindingImpl.executeBindings(SourceFile:17)
E/AndroidRuntime(  567): 	at androidx.databinding.ViewDataBinding.executeBindingsInternal(SourceFile:11)
E/AndroidRuntime(  567): 	at androidx.databinding.ViewDataBinding.executePendingBindings(SourceFile:2)
E/AndroidRuntime(  567): 	at e.a.a.a.a.c.<init>(SourceFile:13)
E/AndroidRuntime(  567): 	at ***.fragment.root.RootViewFragment.onCreateView(SourceFile:1)
E/AndroidRuntime(  567): 	at androidx.fragment.app.Fragment.performCreateView(SourceFile:4)
E/AndroidRuntime(  567): 	at androidx.fragment.app.FragmentManager.a(SourceFile:165)
E/AndroidRuntime(  567): 	at androidx.fragment.app.FragmentManager.m(SourceFile:4)
E/AndroidRuntime(  567): 	at androidx.fragment.app.FragmentManager.a(SourceFile:319)
E/AndroidRuntime(  567): 	at androidx.fragment.app.FragmentManager.a(SourceFile:636)
E/AndroidRuntime(  567): 	at o1.m.d.b.onStart(SourceFile:9)
E/AndroidRuntime(  567): 	at o1.b.k.i.onStart(SourceFile:1)
E/AndroidRuntime(  567): 	at ***.QTRadioActivity.onStart(SourceFile:1)
E/AndroidRuntime(  567): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
E/AndroidRuntime(  567): 	at android.app.Activity.performStart(Activity.java:5252)
E/AndroidRuntime(  567): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2173)
E/AndroidRuntime(  567): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
E/AndroidRuntime(  567): 	at android.app.ActivityThread.access$800(ActivityThread.java:141)
E/AndroidRuntime(  567): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
E/AndroidRuntime(  567): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(  567): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(  567): 	at android.app.ActivityThread.main(ActivityThread.java:5052)
E/AndroidRuntime(  567): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(  567): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(  567): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
E/AndroidRuntime(  567): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
E/AndroidRuntime(  567): 	at dalvik.system.NativeStart.main(Native Method)

```

This is due to issue https://issuetracker.google.com/issues/131349148. It causes class failing to load if the class has catch clauses with non-existent (only available in newer APIs) throwable types.
Although that issue is marked as Fixed, it is not fixed for all cases. Google's fix is avoiding inlining functions with catching clause for **only** `ReflectiveOperationException` type, so that a running code won't crash after R8 optimizes it. I already filed a [new issue](https://issuetracker.google.com/issues/153514654) requesting consideration of ErrnoException but I think it will take some time for the fix and for developers to upgrade to newest R8.

The nested class `InternalRewinder` in Glide tries to solve this problem. The class is located in file https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/data/ParcelFileDescriptorRewinder.java . The `InternalRewinder` solution is good, but it is broken after R8 inlined its method body to the nesting class.

I suggest the following code for this problem:

```diff
 try {
     Os.lseek(parcelFileDescriptor.getFileDescriptor(), 0, SEEK_SET);
-} catch (ErrnoException e) {
-     throw new IOException(e);
+} catch (Exception e) {
+     if (e instanceof ErrnoException) {
+         throw new IOException(e);
+     } else {
+         throw e;
+     }
 }
```

It is just a naive change demonstrating the idea. I tested it and it does not cause VerifyError on loading of the class. If you maintainers are OK with this, I am willing to open a pull request with better written code.

**Comment by Firefly822** [comment]
i have the same issue on device android 4.4

**Comment by vkomysh-vicman** [comment]
solution is here: https://github.com/bumptech/glide/issues/3152#issuecomment-601699075

**Comment by hqzxzwb** [comment]
There is already a merged solution.
