### ISSUE TITLE
[Load local image failed]Glide   : class com.bumptech.glide.load.engine.GlideException: Failed to load resource.    

### ISSUE THREAD

**Issue by mmaSunshine** [bumptech/glide#4202]
**Glide Version**:4.9.0

**Integration libraries**: implementation 'com.github.bumptech.glide:glide:4.9.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'

**Device/Android Version**:   Android 28

**Issue details / Repro steps / Use case background**: I develop a camera app, take  picture and save, make the Intent pass the file path to Second Activity,and let Glide load the file，but there is a probabilistic error of loading failure.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide
                .with(this)
                .load(new File(getIntent().getStringExtra(KEY_PATH)))
                .skipMemoryCache(true)
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .into(image);
```

**Layout XML**:

```xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/black"
    tools:context=".activity.ImageDetailsActivity">

    <androidx.appcompat.widget.AppCompatImageView
        android:id="@+id/image"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="fitXY"/>


</RelativeLayout>
```

**Stack trace / LogCat**:
```ruby
04-23 08:18:50.600  3419  3419 W glide-source-th: type=1400 audit(0.0:246): avc: denied { read } for path="/data/data/com.tcl.gallery/cache/take_cache/tcl_take.jpg" dev="mmcblk0p17" ino=1178339 scontext=u:r:mediaserver:s0 tcontext=u:object_r:system_app_data_file:s0 tclass=file permissive=0

04-23 08:18:50.750  3419  3419 W Glide   : Load failed for /data/user/0/com.tcl.gallery/cache/take_cache/tcl_take.jpg with size [1920x1080]
04-23 08:18:50.750  3419  3419 W Glide   : class com.bumptech.glide.load.engine.GlideException: Failed to load resource
04-23 08:18:50.750  3419  3419 W Glide   :   Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, LOCAL
04-23 08:18:50.750  3419  3419 W Glide   :     Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
04-23 08:18:50.750  3419  3419 W Glide   :     Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
04-23 08:18:50.750  3419  3419 W Glide   :     Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
04-23 08:18:50.750  3419  3419 W Glide   :   Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, LOCAL
04-23 08:18:50.750  3419  3419 W Glide   :     Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
04-23 08:18:50.750  3419  3419 W Glide   :     Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
04-23 08:18:50.750  3419  3419 W Glide   :   Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{AssetFileDescriptor->Object->Drawable}, LOCAL
04-23 08:18:50.750  3419  3419 W Glide   :     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AssetFileDescriptor->Bitmap->Drawable}
```

**Comment by yin-haoran** [comment]
解决了吗

**Comment by IronFuturist** [comment]
I'm having the same issue.

2020-11-23 20:15:08.354 8305-8305/com.learndiscussvote.projectguardian.androidApp W/Glide: Load failed for https://s3.amazonaws.com/uifaces/faces/twitter/heyimjuani/128.jpg with size [341x338]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.io.FileNotFoundException(https://s3.amazonaws.com/uifaces/faces/twitter/heyimjuani/128.jpg)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    java.io.FileNotFoundException(https://s3.amazonaws.com/uifaces/faces/twitter/heyimjuani/128.jpg)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.io.FileNotFoundException(https://s3.amazonaws.com/uifaces/faces/twitter/heyimjuani/128.jpg)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.FileNotFoundException: https://s3.amazonaws.com/uifaces/faces/twitter/heyimjuani/128.jpg
2020-11-23 20:15:08.355 8305-8305/com.learndiscussvote.projectguardian.androidApp I/Glide: Root cause (1 of 1)
    java.io.FileNotFoundException: https://s3.amazonaws.com/uifaces/faces/twitter/heyimjuani/128.jpg
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:102)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:56)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:62)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
        at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
2020-11-23 20:15:08.356 8305-8305/com.learndiscussvote.projectguardian.androidApp W/Glide: Load failed for https://s3.amazonaws.com/uifaces/faces/twitter/heyimjuani/128.jpg with size [333x341]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.io.FileNotFoundException(https://s3.amazonaws.com/uifaces/faces/twitter/heyimjuani/128.jpg)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    java.io.FileNotFoundException(https://s3.amazonaws.com/uifaces/faces/twitter/heyimjuani/128.jpg)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.io.FileNotFoundException(https://s3.amazonaws.com/uifaces/faces/twitter/heyimjuani/128.jpg)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.FileNotFoundException: https://s3.amazonaws.com/uifaces/faces/twitter/heyimjuani/128.jpg
2020-11-23 20:15:08.356 8305-8305/com.learndiscussvote.projectguardian.androidApp I/Glide: Root cause (1 of 1)
    java.io.FileNotFoundException: https://s3.amazonaws.com/uifaces/faces/twitter/heyimjuani/128.jpg
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:102)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:56)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:62)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
        at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
