### ISSUE TITLE
Unable to extract the trust manager on Android10Platform, sslSocketFactory is class com.android.org.conscrypt.OpenSSLSocketFactoryImpl

### ISSUE THREAD

**Issue by e9ab98e991ab** [bumptech/glide#4216]
### 在使用 **@GlideModule 注解**
@GlideModule
```
public class MyAppGlideModule extends AppGlideModule{

    @Override
    public void applyOptions(@NonNull Context context, GlideBuilder builder) {
        // Apply options to the builder here.
        builder.setDefaultRequestOptions(new RequestOptions().format(DecodeFormat.PREFER_RGB_565)); 
    } 
    @Override
    public void registerComponents(@NonNull Context context,
                                   @NonNull Glide glide,
                                   @NonNull Registry registry) { 
        registry.replace(GlideUrl.class, InputStream.class,
                new OkHttpUrlLoader.Factory(ProgressManager.getOkHttpClient()));
    }

}
```
在Android10 上报错 **GlideApp的错**
### 错误信息
```
 Caused by: java.lang.IllegalStateException: Unable to extract the trust manager on Android10Platform, sslSocketFactory is class com.android.org.conscrypt.OpenSSLSocketFactoryImpl
        at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:751)
        at cc.shinichi.library.glide.sunfusheng.progress.ProgressManager.getOkHttpClient(ProgressManager.java:57)
        at cc.shinichi.library.glide.sunfusheng.progress.ProgressLibraryGlideModule.registerComponents(ProgressLibraryGlideModule.java:24)
        at com.bumptech.glide.GeneratedAppGlideModuleImpl.registerComponents(GeneratedAppGlideModuleImpl.java:33)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:305)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:242)
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:201)
        at com.bumptech.glide.Glide.get(Glide.java:182)
        at com.bumptech.glide.Glide.getRetriever(Glide.java:749)
        at com.bumptech.glide.Glide.with(Glide.java:813)
        at com.meetacg.GlideApp.with(GlideApp.java:110)
        at com.meetacg.ui.base.BaseFragment.onResume(BaseFragment.java:70)
```

**Comment by e9ab98e991ab** [comment]
com.github.SherlockGougou:BigImageViewPager 导致的 已解决
