### ISSUE TITLE
java.lang.NullPointerException  Null reference used for synchronization (monitor-enter)

### ISSUE THREAD

**Issue by Apeplan** [bumptech/glide#4219]
**Glide Version**:
4.9.0

**Integration libraries**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```
GlideApp.with(Application.APP.getApplicationContext()).load(url)
                                .diskCacheStrategy(DiskCacheStrategy.ALL).preload();


GlideApp.with(getContext()).load(url)
                    .diskCacheStrategy(DiskCacheStrategy.RESOURCE)
                    .error(R.drawable.xxx)
                    .placeholder(R.drawable.xxx)
                    .into(imageView);

```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```

1 com.bumptech.glide.load.engine.EngineResource.release(EngineResource.java:107)
2 com.bumptech.glide.load.engine.Engine.release(Engine.java:286)
3 com.bumptech.glide.request.SingleRequest.releaseResource(SingleRequest.java:340)
4 com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:330)
5 com.bumptech.glide.manager.RequestTracker.clearRemoveAndMaybeRecycle(RequestTracker.java:79)
6 com.bumptech.glide.manager.RequestTracker.clearRemoveAndRecycle(RequestTracker.java:66)
7 com.bumptech.glide.RequestManager.untrack(RequestManager.java:630)
8 com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:598)
9 com.bumptech.glide.RequestManager.clear(RequestManager.java:594)
10 com.bumptech.glide.request.target.PreloadTarget.clear(PreloadTarget.java:57)
11 com.bumptech.glide.request.target.PreloadTarget$1.handleMessage(PreloadTarget.java:25)
12 android.os.Handler.dispatchMessage(Handler.java:103)
13 android.os.Looper.loop(Looper.java:213)
14 android.app.ActivityThread.main(ActivityThread.java:8147)
15 java.lang.reflect.Method.invoke(Native Method)
16 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
17 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)


```

**Comment by ShubhamTiwari479** [comment]
also facing the same error

E/System: Uncaught exception thrown by finalizer
V/studio.deploy: Fixing application and activity contexts
E/System: java.lang.NullPointerException: Null reference used for synchronization (monitor-enter)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.finalize(ConscryptFileDescriptorSocket.java:1053)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:252)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:239)
        at java.lang.Daemons$Daemon.run(Daemons.java:105)
        at java.lang.Thread.run(Thread.java:764)
E/System: Uncaught exception thrown by finalizer
E/System: java.lang.NullPointerException: Null reference used for synchronization (monitor-enter)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.finalize(ConscryptFileDescriptorSocket.java:1053)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:252)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:239)
        at java.lang.Daemons$Daemon.run(Daemons.java:105)
        at java.lang.Thread.run(Thread.java:764)
E/System: Uncaught exception thrown by finalizer
E/System: java.lang.NullPointerException: Null reference used for synchronization (monitor-enter)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.finalize(ConscryptFileDescriptorSocket.java:1053)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:252)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:239)
        at java.lang.Daemons$Daemon.run(Daemons.java:105)
        at java.lang.Thread.run(Thread.java:764)
    Uncaught exception thrown by finalizer
E/System: java.lang.NullPointerException: Null reference used for synchronization (monitor-enter)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.finalize(ConscryptFileDescriptorSocket.java:1053)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:252)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:239)
        at java.lang.Daemons$Daemon.run(Daemons.java:105)
        at java.lang.Thread.run(Thread.java:764)
    Uncaught exception thrown by finalizer
    java.lang.NullPointerException: Null reference used for synchronization (monitor-enter)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.finalize(ConscryptFileDescriptorSocket.java:1053)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:252)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:239)
        at java.lang.Daemons$Daemon.run(Daemons.java:105)
        at java.lang.Thread.run(Thread.java:764)
E/System: Uncaught exception thrown by finalizer
E/System: java.lang.NullPointerException: Null reference used for synchronization (monitor-enter)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.finalize(ConscryptFileDescriptorSocket.java:1053)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:252)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:239)
        at java.lang.Daemons$Daemon.run(Daemons.java:105)
        at java.lang.Thread.run(Thread.java:764)
E/System: Uncaught exception thrown by finalizer
E/System: java.lang.NullPointerException: Null reference used for synchronization (monitor-enter)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.finalize(ConscryptFileDescriptorSocket.java:1053)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:252)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:239)
        at java.lang.Daemons$Daemon.run(Daemons.java:105)
        at java.lang.Thread.run(Thread.java:764)
E/System: Uncaught exception thrown by finalizer
E/System: java.lang.NullPointerException: Null reference used for synchronization (monitor-enter)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.finalize(ConscryptFileDescriptorSocket.java:1053)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:252)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:239)
        at java.lang.Daemons$Daemon.run(Daemons.java:105)
        at java.lang.Thread.run(Thread.java:764)
E/System: Uncaught exception thrown by finalizer
E/System: java.lang.NullPointerException: Null reference used for synchronization (monitor-enter)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.finalize(ConscryptFileDescriptorSocket.java:1053)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:252)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:239)
        at java.lang.Daemons$Daemon.run(Daemons.java:105)
        at java.lang.Thread.run(Thread.java:764)
E/System: Uncaught exception thrown by finalizer
E/System: java.lang.NullPointerException: Null reference used for synchronization (monitor-enter)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.finalize(ConscryptFileDescriptorSocket.java:1053)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:252)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:239)
        at java.lang.Daemons$Daemon.run(Daemons.java:105)
        at java.lang.Thread.run(Thread.java:764)
    Uncaught exception thrown by finalizer
E/System: java.lang.NullPointerException: Null reference used for synchronization (monitor-enter)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.finalize(ConscryptFileDescriptorSocket.java:1053)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:252)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:239)
        at java.lang.Daemons$Daemon.run(Daemons.java:105)
        at java.lang.Thread.run(Thread.java:764)
E/System: Uncaught exception thrown by finalizer
E/System: java.lang.NullPointerException: Null reference used for synchronization (monitor-enter)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.finalize(ConscryptFileDescriptorSocket.java:1053)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:252)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:239)
        at java.lang.Daemons$Daemon.run(Daemons.java:105)
        at java.lang.Thread.run(Thread.java:764)
E/System: Uncaught exception thrown by finalizer
    java.lang.NullPointerException: Null reference used for synchronization (monitor-enter)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.finalize(ConscryptFileDescriptorSocket.java:1053)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:252)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:239)
        at java.lang.Daemons$Daemon.run(Daemons.java:105)
        at java.lang.Thread.run(Thread.java:764)
