### ISSUE TITLE
Suggestion: add loaded from source to RequestListener callback

### ISSUE THREAD

**Issue by Erlend2** [bumptech/glide#4234]
Hello, could it be possible to add one or two additional variables to the onResourceReady callback, which states whether the image was downloaded or loaded from cache?

For example:

```java
//final int FROM_INTERNET=0;
//final int FROM_CACHE=1;
//final int FROM_EXTERNAL=2;

Glide.with(c).load(url).listener(new RequestListener<Drawable>(){
    @Override
    public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
        return false;
    }

    @Override
    public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource, int loadedFrom, String loadPath) {
        Log.d("MainActivity","loadedFrom: "+loadedFrom+", loadPath: "+loadPath);
        // loadedFrom could return: 0 (downloaded), 1 (from cache), 2 (from external storage?), etc.
        // loadPath could return: url (for 0), path to cache (for 1), path to external location (for 2), etc.
        return false;
    }
})
```

Glide version: 4.11.0

Integration: Okhttp3

Device: Xiaomi MA 1A, Android 8.1.0

Why: I simply want to know whether an image has been downloaded or fetched from cache when loaded. I've read and tried to implement onlyRetrieveFromCache(true) with custom target and listener, and it's not reliable, convenient, or efficient for checking it.

**Comment by Erlend2** [comment]
Hi sjudd, thank you, it helps. 

I use Glide with a Gridview, and most of the images in onResourceReady returned the datasource REMOTE, but some displayed MEMORY_CACHE and RESOURCE_DISK_CACHE as well. I found that odd as I was only scrolling down. With a Logcat test to Debug, I got REMOTE 35 times, MEMORY_CACHE 10 times, and RESOURCE_DISK_CACHE 1 time, out of 50 loaded images to empty cache.

However, when scrolling up again, only MEMORY_CACHE and RESOURCE_DISK_CACHE was returned, which is good.

I assume REMOTE means downloaded from url. What's the difference between MEMORY_CACHE and RESOURCE_DISK_CACHE?

I load the images with Glide like this:

        Glide.with(c).
                load(url).
                diskCacheStrategy(DiskCacheStrategy.RESOURCE).
                listener(new RequestListener<Drawable>() {
                    @Override public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
                        return false;
                    }
                    @Override public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
                        Log.d("MainActivity","dataSource: "+dataSource);
                        return false;
                    }

                }).
                into(holder.imageView);

**Comment by Erlend2** [comment]
Hi again, I've been testing again and I see a strange issue for one of my image searches: A single image is loaded multiple times while scrolling down. I confirmed it by adding the url to the log message inside the onResourceReady callback. The duplicated image has the url "http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg".

Firstly, I received a GlideException that the load of the image failed:

```
2020-06-20 12:11:03.061 32214-32214/com.myapp.app W/Glide: Load failed for http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg with size [3x4]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There were 2 causes:
    java.net.SocketTimeoutException(timeout)
    com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException(Mark has been invalidated, pos: 342 markLimit: 65536)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ContentLengthInputStream->Object->Drawable}, REMOTE
    There were 2 causes:
    java.net.SocketTimeoutException(timeout)
    com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException(Mark has been invalidated, pos: 342 markLimit: 65536)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ContentLengthInputStream->GifDrawable->Drawable}
        Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ContentLengthInputStream->Bitmap->Drawable}
    There was 1 cause:
    java.net.SocketTimeoutException(timeout)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.net.SocketTimeoutException: timeout
        Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ContentLengthInputStream->BitmapDrawable->Drawable}
    There was 1 cause:
    com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException(Mark has been invalidated, pos: 342 markLimit: 65536)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException: Mark has been invalidated, pos: 342 markLimit: 65536
2020-06-20 12:11:03.063 32214-32214/com.myapp.app I/Glide: Root cause (1 of 2)
    java.net.SocketTimeoutException: timeout
        at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:143)
        at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:162)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:340)
        at okio.RealBufferedSource.read(RealBufferedSource.kt:188)
        at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.kt:349)
        at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.kt:430)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
        at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at com.bumptech.glide.util.ContentLengthInputStream.read(ContentLengthInputStream.java:71)
        at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:300)
        at com.bumptech.glide.util.ExceptionCatchingInputStream.read(ExceptionCatchingInputStream.java:88)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at com.bumptech.glide.util.MarkEnforcingInputStream.read(MarkEnforcingInputStream.java:46)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:137)
        at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:305)
        at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
        at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:747)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:723)
        at com.bumptech.glide.load.resource.bitmap.ImageReader$InputStreamImageReader.decodeBitmap(ImageReader.java:50)
        at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:742)
        at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:390)
        at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:248)
        at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:207)
        at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:62)
        at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:18)
        at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:92)
        at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70)
        at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:59)
        at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76)
        at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57)
        at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:524)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:488)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:474)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:426)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:282)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
     Caused by: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.read(SocketInputStream.java:203)
        at java.net.SocketInputStream.read(SocketInputStream.java:139)
        at okio.InputStreamSource.read(JvmOkio.kt:90)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
        at okio.RealBufferedSource.read(RealBufferedSource.kt:188) 
        at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.kt:349) 
        at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.kt:430) 
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276) 
        at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158) 
        at java.io.FilterInputStream.read(FilterInputStream.java:133) 
        at com.bumptech.glide.util.ContentLengthInputStream.read(ContentLengthInputStream.java:71) 
        at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:300) 
        at com.bumptech.glide.util.ExceptionCatchingInputStream.read(ExceptionCatchingInputStream.java:88) 
        at java.io.FilterInputStream.read(FilterInputStream.java:133) 
        at com.bumptech.glide.util.MarkEnforcingInputStream.read(MarkEnforcingInputStream.java:46) 
        at java.io.FilterInputStream.read(FilterInputStream.java:107) 
        at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:137) 
        at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:305) 
        at android.graphics.BitmapFactory.nativeDecodeStream(Native Method) 
        at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:747) 
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:723) 
        at com.bumptech.glide.load.resource.bitmap.ImageReader$InputStreamImageReader.decodeBitmap(ImageReader.java:50) 
        at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:742) 
        at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:390) 
        at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:248) 
        at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:207) 
        at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:62) 
        at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:18) 
        at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:92) 
        at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70) 
        at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:59) 
        at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76) 
        at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57) 
        at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:524) 
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:488) 
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:474) 
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:426) 
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:282) 
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393) 
2020-06-20 12:11:03.067 32214-32214/com.myapp.app I/Glide: Root cause (2 of 2)
    com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream$InvalidMarkException: Mark has been invalidated, pos: 342 markLimit: 65536
        at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.reset(RecyclableBufferedInputStream.java:344)
        at com.bumptech.glide.load.data.InputStreamRewinder.rewindAndGet(InputStreamRewinder.java:31)
        at com.bumptech.glide.load.data.InputStreamRewinder.rewindAndGet(InputStreamRewinder.java:14)
        at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:89)
        at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70)
        at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:59)
        at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76)
        at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57)
        at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:524)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:488)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:474)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:426)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:282)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
```

Nontheless, it succesfully loaded, and then it was somehow triggered numerous times:

```
2020-06-20 12:13:39.849 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:39.854 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:39.964 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: REMOTE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=12194080&type=jpeg
2020-06-20 12:13:39.977 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:39.980 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:45.343 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:45.348 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:45.352 32214-32224/com.erlendhaartveit.vilde I/zygote64: Do full code cache collection, code=1007KB, data=638KB
2020-06-20 12:13:45.358 32214-32224/com.myapp.app I/zygote64: After code cache collection, code=992KB, data=566KB
2020-06-20 12:13:45.729 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: REMOTE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=13984543&type=jpeg
2020-06-20 12:13:45.744 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:45.748 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:46.916 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:46.923 32214-32214/com.myapp.app I/chatty: uid=10527(com.erlendhaartveit.vilde) identical 1 line
2020-06-20 12:13:47.012 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:47.015 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:48.199 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:48.204 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:48.632 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:48.682 32214-32214/com.myapp.app I/chatty: uid=10527(com.erlendhaartveit.vilde) identical 2 lines
2020-06-20 12:13:48.685 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:49.101 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:49.105 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:51.041 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: REMOTE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14857816&type=jpeg
2020-06-20 12:13:51.055 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:51.058 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:51.793 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:51.797 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:51.825 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: REMOTE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14784760&type=jpeg
2020-06-20 12:13:51.840 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:51.843 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:53.460 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:53.464 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:53.763 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: REMOTE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14757937&type=jpeg
2020-06-20 12:13:53.778 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:53.782 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:54.381 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:54.386 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:54.846 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:54.849 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:55.653 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: REMOTE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14718596&type=jpeg
2020-06-20 12:13:55.667 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:55.670 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:56.252 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: REMOTE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14801365&type=jpeg
2020-06-20 12:13:56.268 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:56.271 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:57.788 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: REMOTE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14851243&type=jpeg
2020-06-20 12:13:57.804 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:57.807 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:58.023 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: REMOTE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14860815&type=jpeg
2020-06-20 12:13:58.039 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:58.044 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:59.027 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: REMOTE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=13222062&type=jpeg
2020-06-20 12:13:59.041 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:59.045 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:59.751 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: REMOTE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14794707&type=jpeg
2020-06-20 12:13:59.759 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:13:59.764 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:14:00.114 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: REMOTE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=13222059&type=jpeg
2020-06-20 12:14:00.127 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
2020-06-20 12:14:00.129 32214-32214/com.myapp.app D/MainActivity: onResourceReady ~ dataSource: MEMORY_CACHE, url: http://www.unimus.no/felles/bilder/web_hent_bilde.php?id=14928204&type=jpeg
```

These logs show that on a load of 12 images with the data source "REMOTE", that image was reloaded 48 times from cache with the source "MEMORY_CACHE". This happened on a simple scrolldown of a gridview.
