### ISSUE TITLE
CN:加载不了这张Png图片, EN: can not load this .png image

### ISSUE THREAD

**Issue by 123ufo** [bumptech/glide#4247]
CN: 我用Glide加载不了这张.png的网络图片,但是我用Picasso是可以加载出来的.
EN: I use glide can not load this png image, But Picasso yes
String url = "http://pic13.nipic.com/20110418/2457331_234501212000_2.png"

  NO : Glide.with(this)
                .load(url )
                .into(mIvSimple);

throw error :+1: 
Glide: Root cause (1 of 1)
                                                          java.io.FileNotFoundException: http://pic13.nipic.com/20110418/2457331_234501212000_2.png
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
                                                              at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:106)
                                                              at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:59)
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:150)
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:144)
                                                              at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:65)
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
                                                              at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
                                                              at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
                                                              at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
                                                              at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                              at java.lang.Thread.run(Thread.java:764)
                                                              at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
06-07 15:35:47.481 10971-10971/com.ufo.glideproj W/Glide: Load failed for http://pic13.nipic.com/20110418/2457331_234501212000_2.png with size [600x600]
                                                          class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                          There was 1 cause:
                                                          java.io.FileNotFoundException(http://pic13.nipic.com/20110418/2457331_234501212000_2.png)
                                                           call GlideException#logRootCauses(String) for more detail
                                                            Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
                                                          There was 1 cause:
                                                          java.io.FileNotFoundException(http://pic13.nipic.com/20110418/2457331_234501212000_2.png)
                                                           call GlideException#logRootCauses(String) for more detail
                                                              Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
                                                          There was 1 cause:
                                                          java.io.FileNotFoundException(http://pic13.nipic.com/20110418/2457331_234501212000_2.png)
                                                           call GlideException#logRootCauses(String) for more detail
                                                                Cause (1 of 1): class java.io.FileNotFoundException: http://pic13.nipic.com/20110418/2457331_234501212000_2.png
06-07 15:35:47.483 10971-10971/com.ufo.glideproj I/Glide: Root cause (1 of 1)
                                                          java.io.FileNotFoundException: http://pic13.nipic.com/20110418/2457331_234501212000_2.png
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
                                                              at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:106)
                                                              at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:59)
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:150)
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:144)
                                                              at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:65)
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
                                                              at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
                                                              at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
                                                              at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
                                                              at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                              at java.lang.Thread.run(Thread.java:764)
                                                              at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
06-07 15:35:51.207 10971-10971/com.ufo.glideproj W/Glide: Load failed for http://pic13.nipic.com/20110418/2457331_234501212000_2.png with size [600x600]
                                                          class com.bumptech.glide.load.engine.GlideException: Failed to load resource
                                                          There was 1 cause:
                                                          java.io.FileNotFoundException(http://pic13.nipic.com/20110418/2457331_234501212000_2.png)
                                                           call GlideException#logRootCauses(String) for more detail
                                                            Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
                                                          There was 1 cause:
                                                          java.io.FileNotFoundException(http://pic13.nipic.com/20110418/2457331_234501212000_2.png)
                                                           call GlideException#logRootCauses(String) for more detail
                                                              Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
                                                          There was 1 cause:
                                                          java.io.FileNotFoundException(http://pic13.nipic.com/20110418/2457331_234501212000_2.png)
                                                           call GlideException#logRootCauses(String) for more detail
                                                                Cause (1 of 1): class java.io.FileNotFoundException: http://pic13.nipic.com/20110418/2457331_234501212000_2.png
06-07 15:35:51.212 10971-10971/com.ufo.glideproj I/Glide: Root cause (1 of 1)
                                                          java.io.FileNotFoundException: http://pic13.nipic.com/20110418/2457331_234501212000_2.png
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
                                                              at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:106)
                                                              at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:59)
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:150)
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:144)
                                                              at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:65)
                                                              at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
                                                              at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
                                                              at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
                                                              at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
                                                              at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                              at java.lang.Thread.run(Thread.java:764)
                                                              at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)

-----------------------------------------------------------------------------------
 Yes:  Picasso.get().load(url ).into(mIvSimple);

why????

**Comment by jiyewushen** [comment]
服务端对Http请求标头中的User-Agent进行了限制，使用Glide中默认获取到User-Agent值无法请求到数据，使用电脑端的可以，代码如下
```kotlin
val url = GlideUrl("http://pic13.nipic.com/20110418/2457331_234501212000_2.png",
            LazyHeaders.Builder().addHeader( "User-Agent","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit / 537.36(KHTML, like Gecko) Chrome  47.0.2526.106 Safari / 537.36" ).build())
GlideApp.with(this).load(url).into(image)
```
