### ISSUE TITLE
Fatal Exception: java.lang.VerifyError

### ISSUE THREAD

**Issue by mhd-dll** [bumptech/glide#4275]
**Glide Version**: 4.11.0

**Integration libraries**: none

**Device/Android Version**: It mostly happens on Android 4, we have little amount of crashes for android 5 & 8 & 9.
Such device: Galaxy J1, Version: 4.4.4

**Issue details / Repro steps / Use case background**: 
Trying to load image from app resources (Note: ldpi image version is not provided, but for other DPIs are provided).
When app lunches, after splash screen, it should show an image drawable in welcome screen, but it crashes for some devices.
Couldn't reproduce, as crash is taken from Crashlytics reports.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
    val options = RequestOptions()

    Glide.with(this.context)
        .load(R.drawable.img_welcome_note)
        .apply(options)
        .into(imageView)
```

**Layout XML**:
```xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/lighter_grey">

    <ImageView
        android:id="@+id/backgroundImageView"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:scaleType="centerCrop"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintBottom_toTopOf="@id/selectionContainer"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        tools:src="@drawable/img_welcome_note" />

    <androidx.constraintlayout.widget.ConstraintLayout
        android:id="@+id/selectionContainer"
        android:orientation="vertical"
        android:layout_width="0dp"
        android:layout_height="256dp"
        android:paddingStart="16dp"
        android:paddingEnd="16dp"
        android:layout_marginBottom="8dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent">

        <TextView
            android:id="@+id/titleTextView"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginTop="24dp"
            android:gravity="center_horizontal"
            android:textSize="22sp"
            android:textColor="@color/navy_blue"
            android:text="@string/onboarding_welcome_back"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintTop_toTopOf="parent"/>

    </androidx.constraintlayout.widget.ConstraintLayout>

</androidx.constraintlayout.widget.ConstraintLayout>
```

**Stack trace / LogCat**:
```ruby
Fatal Exception: java.lang.VerifyError: d0/e/a/k/i/m
       at com.bumptech.glide.Glide.<init>(Glide.java:428)
       at com.bumptech.glide.GlideBuilder.build(GlideBuilder.java:564)
       at com.bumptech.glide.Glide.initializeGlide(Glide.java:290)
       at com.bumptech.glide.Glide.initializeGlide(Glide.java:242)
       at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:201)
       at com.bumptech.glide.Glide.get(Glide.java:182)
       at com.bumptech.glide.Glide.getRetriever(Glide.java:749)
       at com.bumptech.glide.Glide.with(Glide.java:776)
       at com.myApp.android.util.ImageExtensionKt.load(ImageExtensionKt.java:190)
       at com.myApp.android.util.ImageExtensionKt.load$default(ImageExtensionKt.java:183)
       at com.myApp.android.module.onboarding.CountrySelectionActivity.setupView(CountrySelectionActivity.java:75)
       at com.myApp.android.module.onboarding.CountrySelectionActivity.onCreate(CountrySelectionActivity.java:45)
       at android.app.Activity.performCreate(Activity.java:5442)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
       at android.app.ActivityThread.access$800(ActivityThread.java:166)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5584)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by hqzxzwb** [comment]
Probably the same as #3152
