### ISSUE TITLE
Glide returns java.io.FileNotFoundException to URL with a query parameter

### ISSUE THREAD

**Issue by heaven-dev** [bumptech/glide#4311]
**Glide Version**: 4.11.0

**Integration libraries**: no

**Device/Android Version**: Android TV emulator API 23

**Issue details / Repro steps / Use case background**: At first thanks this great library. Im trying to load image (https://helsinki.tv7.fi/exodus-interfaces/image?id=12766) and show it on Android TV UI. Glide gives me **FileNotFoundException**. Other image (http://goo.gl/gEgYUd) works without problems.

Is this problem related to the query parameter of the URL? I am able to open URL in browser and also URL works in an other javascript app.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
import android.widget.ImageView;
import com.bumptech.glide.Glide;

// example code which gives FileNotFoundException:
ImageView imageView = root.findViewById(R.id.myImage);
Glide.with(this).asBitmap().load("http://helsinki.tv7.fi/exodus-interfaces/image?id=12766").into(imageView);


// example code which works ok:
ImageView imageView = root.findViewById(R.id.myImage);
Glide.with(this).asBitmap().load("http://goo.gl/gEgYUd").into(imageView);
```

**Layout XML**:
```xml
<ImageView
        android:id="@+id/myImage"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_margin="8dp"
        android:paddingStart="15dp"
        android:paddingEnd="15dp"
        android:background="@drawable/content_item"/>
```

**Stack trace / LogCat**:
```ruby
08-14 09:54:33.463 7638-7638/org.tv7 I/Glide: Root cause (1 of 1)
java.io.FileNotFoundException: http://helsinki.tv7.fi/exodus-interfaces/image?id=12766
     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:238)
     at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:102)
     at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:56)
     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
     at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:62)
     at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
     at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
     at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
     at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
     at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
     at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
     at java.lang.Thread.run(Thread.java:818)
     at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
```

**Comment by heaven-dev** [comment]
I solved this issue by changing URL scheme from **http** to **https**.

It wasn't Glide problem.
