### ISSUE TITLE
Glide Unable to Parse a particular GIF

### ISSUE THREAD

**Issue by stonecauldron** [bumptech/glide#4320]
**Glide Version**:
3.7.0

**Device/Android Version**:
Android tablet emulator running API 30

**Issue details / Repro steps / Use case background**: 
We are trying to load the following gif:
![91191428-114f3100-e6f5-11ea-941c-2dbf0a8ea217](https://user-images.githubusercontent.com/2352056/91278855-08a63b80-e785-11ea-99ed-5246c545ff83.gif)
But Glide fails with its parsing. The gif was encoded using the [gifski](https://gif.ski) library. Loading the sample gif from the gifski library does not cause any issues so there seems to be a particular problem with the gif we are using.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
// thumbnailUrl = the url from our API endpoint
Glide.with(ResultsActivity.this).load(thumbnailUrl)
  .thumbnail(0.5f)
  .crossFade()
  .diskCacheStrategy(DiskCacheStrategy.ALL)
  .into(holder.thumbnail);
```

**Layout XML**:
```xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="500dp"
    android:layout_alignWithParentIfMissing="false"
    android:layout_alignParentStart="false"
    android:layout_alignParentTop="false"
    android:layout_alignParentEnd="false"
    android:layout_alignParentBottom="false"
    android:orientation="vertical">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="horizontal">

        <ImageView
            android:id="@+id/results_thumbnail"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_weight="1"
            android:adjustViewBounds="true"
            android:scaleType="centerCrop" />

    </LinearLayout
</RelativeLayout>
```

**Stack trace / LogCat**:
```ruby
java.lang.IllegalArgumentException: Bad position 2949201/2949120
        at java.nio.Buffer.position(Buffer.java:259)
        at java.nio.ByteBuffer.position(ByteBuffer.java:812)
        at com.bumptech.glide.gifdecoder.GifHeaderParser.skip(GifHeaderParser.java:319)
        at com.bumptech.glide.gifdecoder.GifHeaderParser.skipImageData(GifHeaderParser.java:309)
        at com.bumptech.glide.gifdecoder.GifHeaderParser.readBitmap(GifHeaderParser.java:202)
        at com.bumptech.glide.gifdecoder.GifHeaderParser.readContents(GifHeaderParser.java:93)
        at com.bumptech.glide.gifdecoder.GifHeaderParser.parseHeader(GifHeaderParser.java:67)
        at com.bumptech.glide.load.resource.gif.GifResourceDecoder.decode(GifResourceDecoder.java:69)
        at com.bumptech.glide.load.resource.gif.GifResourceDecoder.decode(GifResourceDecoder.java:61)
        at com.bumptech.glide.load.resource.gif.GifResourceDecoder.decode(GifResourceDecoder.java:26)
        at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeGifWrapper(GifBitmapWrapperResourceDecoder.java:101)
        at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeStream(GifBitmapWrapperResourceDecoder.java:87)
        at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:71)
        at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:61)
        at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:22)
        at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperStreamResourceDecoder.decode(GifBitmapWrapperStreamResourceDecoder.java:24)
        at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperStreamResourceDecoder.decode(GifBitmapWrapperStreamResourceDecoder.java:14)
        at com.bumptech.glide.load.resource.file.FileToStreamDecoder.decode(FileToStreamDecoder.java:39)
        at com.bumptech.glide.load.resource.file.FileToStreamDecoder.decode(FileToStreamDecoder.java:17)
        at com.bumptech.glide.load.engine.DecodeJob.loadFromCache(DecodeJob.java:222)
        at com.bumptech.glide.load.engine.DecodeJob.cacheAndDecodeSourceData(DecodeJob.java:207)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:187)
        at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
        at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
        at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
        at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
        at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
```

**Comment by stonecauldron** [comment]
Problem was solved by upgrading to version `4.11.0`
