### ISSUE TITLE
Fatal Crash: Expected Android API level 21+ but was 30 - Glide 4.11.0

### ISSUE THREAD

**Issue by Dararii** [bumptech/glide#4360]
**Glide Version**: 4.11.0

**Integration libraries**: glide:okhttp3-integration

**Device/Android Version**: Pixel API 30 Emulator

**Issue details / Repro steps / Use case background**:  
Use it as normal use
![image](https://user-images.githubusercontent.com/7982335/94400667-aed5ce80-0193-11eb-91d2-6d27b1ce6113.png)
And boom. Only happened in API 30. API 21-29 produced no error.
![image](https://user-images.githubusercontent.com/7982335/94400618-9b2a6800-0193-11eb-9af8-0646c236063f.png)

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(imgBackgroundImage.context)
                .asBitmap()
                .skipMemoryCache(true)
                .load(url.trim())
                .apply(options)
                .into(imgIntroBackgroundImage)
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
--------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.essensift.velodi.app, PID: 6988
    java.lang.ExceptionInInitializerError
        at okhttp3.internal.platform.Platform.get(Platform.java:85)
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:202)
        at com.bumptech.glide.integration.okhttp3.OkHttpUrlLoader$Factory.getInternalClient(OkHttpUrlLoader.java:46)
        at com.bumptech.glide.integration.okhttp3.OkHttpUrlLoader$Factory.<init>(OkHttpUrlLoader.java:55)
        at com.bumptech.glide.integration.okhttp3.OkHttpGlideModule.registerComponents(OkHttpGlideModule.java:32)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:293)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:242)
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:201)
        at com.bumptech.glide.Glide.get(Glide.java:182)
        at com.bumptech.glide.Glide.getRetriever(Glide.java:749)
        at com.bumptech.glide.Glide.with(Glide.java:776)
        at com.essensift.velodi.auth.ui.IntroFragment.onViewCreated(IntroFragment.kt:37)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2959)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:571)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:276)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1632)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:455)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2389)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2145)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2083)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1985)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3119)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3053)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:473)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8024)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30
        at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
        at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
```

**Comment by sjudd** [comment]
This looks like a bug in okhttp3, did you try specifying a newer version of it and seeing if that works? We may just need to pull forward in Glide, but you should be able to fix it in your build too before that happens.

**Comment by Dararii** [comment]
I use Okhttp3 integration from glide and there is no higher version than 4.11. So, I think, the glide code must be updated.

**Comment by lorenc-tomasz** [comment]
I set manually implementation("com.squareup.okhttp3:okhttp:4.9.0") and it worked.

**Comment by Dararii** [comment]
> I set manually implementation("com.squareup.okhttp3:okhttp:4.9.0") and it worked.

So we have to downgrade the version?

**Comment by Dararii** [comment]
The solution is by adding implementation("com.squareup.okhttp3:okhttp:4.9.0") as @lorenc-tomasz said.

**Comment by whilson03** [comment]
changing compileSdkVersion and targetSdkVersion from api level 30 to 29 fixed it for me

**Comment by SachinA94** [comment]
Issue was resolved after adding  

`implementation 'com.squareup.okhttp3:okhttp:4.9.1'
`
but now I'm getting crashes caused by okhttp.

```
Fatal Exception: java.lang.NoSuchMethodError: No virtual method toString(Z)Ljava/lang/String; in class Lokhttp3/Cookie; or its super classes (declaration of 'okhttp3.Cookie' appears in /data/app/~~FWxRE0yb901IwnM16CUGdA==/com.xxxxx-54po0AUgD2TzTa8kec_EPA==/base.apk)
       at okhttp3.JavaNetCookieJar.saveFromResponse(:26)
       at com.facebook.react.modules.network.l.saveFromResponse(:4)
       at okhttp3.internal.http.HttpHeaders.receiveHeaders(:33)
       at okhttp3.internal.http.BridgeInterceptor.intercept(:181)
       at okhttp3.internal.http.RealInterceptorChain.proceed(:166)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(:34)
       at okhttp3.internal.http.RealInterceptorChain.proceed(:166)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(:113)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(:51)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```
