### ISSUE TITLE
App crash with this logcat

### ISSUE THREAD

**Issue by ahmadbajwa12315** [bumptech/glide#4390]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xtenxion.photoframe, PID: 14780
    java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/~~HwHeMQMPozSgML4R-_eJEg==/com.xtenxion.photoframe-GWnMgFqdWcRss52SoUdDxg==/base.apk)
        at com.darsh.multipleimageselect.adapters.CustomAlbumSelectAdapter.getView(CustomAlbumSelectAdapter.java:44)
        at android.widget.AbsListView.obtainView(AbsListView.java:2387)
        at android.widget.GridView.onMeasure(GridView.java:1085)
        at android.view.View.measure(View.java:25466)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:747)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3397)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2228)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2486)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:731)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by zeeshanbeg** [comment]
hi. i am interested in contributing to this issue. can i have this assigned 
thanks

**Comment by ahmadbajwa12315** [comment]
sure

**Comment by zeeshanbeg** [comment]
its always giving me this error. 
Gradle sync failed: CreateProcess error=2, The system cannot find the file specified
				Consult IDE log for more details (Help | Show Log) (390ms)

**Comment by mecoFarid** [comment]
@ahmadbajwa12315  This may happen if 3rd party libraries you've implemented uses different versions of Glide. Could you share your app level `buiild.gradle`?

**Comment by ahmadbajwa12315** [comment]
> @ahmadbajwa12315 This may happen if 3rd party libraries you've implemented uses different versions of Glide. Could you share your app level `buiild.gradle`?
Yes this was the reason some of my dependency making glide crash. Thanks for your help guyz

**Comment by mecoFarid** [comment]
@ahmadbajwa12315 Could you consider closing the issue if you case is resolved?

**Comment by ahmadbajwa12315** [comment]
> @ahmadbajwa12315 Could you consider closing the issue if you case is resolved?

ok
