### ISSUE TITLE
NPE when using crossfade transition and a placeholder drawable

### ISSUE THREAD

**Issue by lwasyl** [bumptech/glide#4416]
**Glide Version**: 4.11.0
**Integration libraries**: none that I know of
**Device/Android Version**: Android Emulator API 23 (`system-images;android-23;default;x86_64`)
**Issue details / Repro steps / Use case background**: Load image 
**Related issues**: https://github.com/bumptech/glide/issues/3635 closed by StaleBot 😕 

**Glide load line**:
```kotlin
Glide.with(context)
    .load(photoUrl)
    .placeholder(CustomDrawable())
    .transition(DrawableTransitionOptions.withCrossFade())
    .into(this)

class CustomDrawable : Drawable() {

    private val paint = Paint().apply {
        color = Color.BLACK
    }

    override fun draw(canvas: Canvas) {
        canvas.drawRect(bounds, paint)
    }

    override fun setColorFilter(colorFilter: ColorFilter?) {
        paint.colorFilter = colorFilter
    }

    override fun setAlpha(alpha: Int) = Unit

    override fun getOpacity(): Int = PixelFormat.OPAQUE
}

```

Removing either placeholder or the transition resolves the issue.

<details>
  <summary>Stacktrace</summary>
  
```ruby
    com.bumptech.glide.load.engine.CallbackException: Unexpected exception thrown by non-Glide code
        at com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:160)
        at com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:424)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable()' on a null object reference
        at android.graphics.drawable.LayerDrawable$ChildDrawable.<init>(LayerDrawable.java:1723)
        at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:1792)
        at android.graphics.drawable.TransitionDrawable$TransitionState.<init>(TransitionDrawable.java:248)
        at android.graphics.drawable.TransitionDrawable.createConstantState(TransitionDrawable.java:101)
        at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:1652)
        at android.widget.ImageView.applyImageTint(ImageView.java:560)
        at android.widget.ImageView.updateDrawable(ImageView.java:895)
        at android.widget.ImageView.setImageDrawable(ImageView.java:472)
        at androidx.appcompat.widget.AppCompatImageView.setImageDrawable(AppCompatImageView.java:104)
        at com.bumptech.glide.request.target.ImageViewTarget.setDrawable(ImageViewTarget.java:53)
        at com.bumptech.glide.request.transition.DrawableCrossFadeTransition.transition(DrawableCrossFadeTransition.java:57)
        at com.bumptech.glide.request.transition.DrawableCrossFadeTransition.transition(DrawableCrossFadeTransition.java:15)
        at com.bumptech.glide.request.target.ImageViewTarget.onResourceReady(ImageViewTarget.java:100)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:631)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:575)
        at com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:158)
        at com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:424) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```
  
</details>

**Comment by lwasyl** [comment]
I figured out the root cause: there's a path in a `LayerDrawable` class (used by `TransitionDrawable`) that will try to get drawable's constant state and copy drawable from it:
```java
ChildDrawable(ChildDrawable orig, LayerDrawable owner, Resources res) {
    final Drawable dr = orig.mDrawable;
    final Drawable clone;
    if (dr != null) {
        final ConstantState cs = dr.getConstantState(); // This returns `null` by default
        if (res != null) {
            clone = cs.newDrawable(res);
        } else {
            clone = cs.newDrawable(); // This doesn't have a null-check
        }
```

If the drawable used as a placeholder doesn't implement `getConstantState()` properly , this will crash. The solution is to implement `fun getConstantState(): Drawable.ConstantState` and proper `newDrawable` method there
