### ISSUE TITLE
Glide 4.11.0 : Failed to create image decoder with message unimplemented : java.net.SocketException: Socket closed

### ISSUE THREAD

**Issue by Truvuongss** [bumptech/glide#4464]
Hello Glide dev,
I am using Glide 4.11.0 and get warning when scroll recycler view: 

 W/System.err: java.net.SocketException: Socket closed
 W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
 W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:766)
 W/System.err:     at okio.InputStreamSource.read(Okio.kt:102)
 W/System.err:     at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:159)
 W/System.err:     at okio.RealBufferedSource.read(RealBufferedSource.kt:41)
 W/System.err:     at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.kt:352)
 W/System.err:     at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.kt:389)
 W/System.err:     at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:279)
 W/System.err:     at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:438)
 W/System.err:     at java.io.FilterInputStream.read(FilterInputStream.java:133)
 W/System.err:     at com.bumptech.glide.util.ContentLengthInputStream.read(ContentLengthInputStream.java:71)
 W/System.err:     at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:173)
 W/System.err:     at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:305)
 W/System.err:     at java.io.FilterInputStream.read(FilterInputStream.java:107)
 W/System.err:     at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:137)
 W/System.err:     at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:305)
 W/System.err:     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
 W/System.err:     at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:822)
 W/System.err:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:798)
 W/System.err:     at ImageReader$InputStreamImageReader.decodeBitmap(ImageReader.java:54)
 W/System.err:     at xxx.ArtworkCustomDownSampler.decodeStream(ArtworkDownSampler.java:744)
 W/System.err:     at xxx.ArtworkCustomDownSampler.decodeFromWrappedStreams(ArtworkDownSampler.java:392)
 W/System.err:     at xxx.ArtworkCustomDownSampler.decode(ArtworkDownSampler.java:251)
 W/System.err:     at xxx.ArtworkCustomDownSampler.decode(ArtworkDownSampler.java:210)
 W/System.err:     at xxx.ArtworkCustomDownSampler.decode(ArtworkDownSampler.java:180)
 W/System.err:     at xxx.ArtworkCustomResourceDecoder.decode(ArtworkResourceDecoder.java:37)
 W/System.err:     at xxx.ArtworkCustomResourceDecoder.decode(ArtworkResourceDecoder.java:21)
 W/System.err:     at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:92)
 W/System.err:     at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70)
 W/System.err:     at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:59)
 W/System.err:     at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76)
 W/System.err:     at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57)
 W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:524)
 W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:488)
 W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:474)
 W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:426)
 W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:282)
 W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
 W/System.err:     at java.lang.Thread.run(Thread.java:764)
 W/System.err:     at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
 D/skia: ---- read threw an exception

In my app, I am using my custom ArtworkCustomDownSampler. It's same with DownSampler. Only ignore orientation in decodeFromWrappedStreams().
Please help me to check this.

**Comment by Truvuongss** [comment]
https://github.com/android/uamp/issues/354

**Comment by Truvuongss** [comment]
@sjudd Please help me to check this.

**Comment by Truvuongss** [comment]
I found that set option diskCacheStrategy is the reason of this issue. Please help to check this
