### ISSUE TITLE
Crash when loading url with no image

### ISSUE THREAD

**Issue by davidoskky** [bumptech/glide#4471]
**Glide Version**:4.1.1

**Integration libraries**:okhttp3-integration:4.1.1

**Device/Android Version**:Android 10

**Issue details / Repro steps / Use case background**: I'm using Glide to cache images during a background sync. When it tries caching images from a url where there is no image, the application crashes.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```kotlin
        val imageUrl = "https://uxmovement.com/wp-content/uploads/2020/12/loginux-discloseemail.png"
        val glideOptions = RequestOptions.diskCacheStrategyOf(DiskCacheStrategy.ALL)

        val image = Glide.with(context).asBitmap()
                .apply(glideOptions)
                .load(imageUrl).submit().get()
```

**Stack trace / LogCat**:
```ruby
2021-01-10 15:16:14.161 30762-30762/apps.amine.bou.readerforselfoss W/Glide: Load failed for https://uxmovement.com/wp-content/uploads/2020/12/loginux-discloseemail.png with size [-2147483648x-2147483648]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
          Cause (1 of 1): class com.bumptech.glide.load.HttpException: Not Found
2021-01-10 15:16:14.161 30762-30762/apps.amine.bou.readerforselfoss I/Glide: Root cause (1 of 1)
    com.bumptech.glide.load.HttpException: Not Found
2021-01-10 15:16:14.161 30762-30762/apps.amine.bou.readerforselfoss I/Glide: Root cause (1 of 1)
    com.bumptech.glide.load.HttpException: Not Found
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:119)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:54)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:147)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:141)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:60)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:96)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:286)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:256)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:226)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)
```

**Comment by sjudd** [comment]
The logs you've provided don't appear to be a crash. Glide will log an exception whenever an image load fails, but unless you catch/rethrow, it shouldn't crash your app. 

The call to `.get()` after `.submit()` is suspicious. `.get()` on a Future can throw any number of checked exceptions. It wouldn't surprise me if Kotlin turns those checked exceptions into unchecked runtime exceptions.
