### ISSUE TITLE
IllegalStateException: Already released

### ISSUE THREAD

**Issue by renaudcerrato** [bumptech/glide#4497]
**Glide Version**: 4.11.0

**Integration libraries**: okhttp3-integration

**Device/Android Version**: Oppo/Lollipop (unable to reproduce on my Pixel / Android 10) 

**Repro steps**: back and forth between activities. **It can take a while.**

**Glide load line**:
```java
Glide.with(fragment).load(model).apply(RoundedCorners(4.dp)).into(CompositeBadgeViewTarget(view))

class CompositeBadgeViewTarget(view: CompositeBadgeView) : CustomViewTarget<CompositeBadgeView, Drawable>(view) {

    override fun onLoadFailed(errorDrawable: Drawable?) {
        view.badge.background = view.getDrawable(R.drawable.rounded_rectangle_surface200)
        view.badge.icon = errorDrawable
        view.badge.color = view.resolveThemeColorOrThrow(R.attr.colorSurface400)
    }

    override fun onResourceCleared(placeholder: Drawable?) {
        view.badge.background = null
        view.badge.icon = null
    }

    override fun onResourceReady(resource: Drawable, transition: Transition<in Drawable>?) {
        view.badge.background = resource
        view.badge.icon = null
    }

}

```

**Stack trace / LogCat**:
```ruby
java.lang.RuntimeException: Unable to resume activity \{com.*/*.ui.home.HomeActivity\}: java.lang.IllegalStateException: Already released\
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3334)\
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3365)\
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1574)\
        at android.os.Handler.dispatchMessage(Handler.java:111)\
        at android.os.Looper.loop(Looper.java:210)\
        at android.app.ActivityThread.main(ActivityThread.java:5839)\
        at java.lang.reflect.Method.invoke(Native Method)\
        at java.lang.reflect.Method.invoke(Method.java:372)\
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)\
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)\
     Caused by: java.lang.IllegalStateException: Already released\
        at com.bumptech.glide.util.pool.StateVerifier$DefaultStateVerifier.c(SourceFile:2)\
        at com.bumptech.glide.load.engine.EngineJob.c(SourceFile:1)\
        at com.bumptech.glide.load.engine.Engine.l(SourceFile:2)\
        at com.bumptech.glide.load.engine.Engine.f(SourceFile:6)\
        at com.bumptech.glide.request.SingleRequest.e(SourceFile:24)\
        at com.bumptech.glide.request.target.CustomViewTarget$SizeDeterminer.d(SourceFile:4)\
        at com.bumptech.glide.request.target.CustomViewTarget.n(SourceFile:1)\
        at com.bumptech.glide.request.SingleRequest.f(SourceFile:19)\
        at com.bumptech.glide.manager.RequestTracker.f(SourceFile:4)\
        at com.bumptech.glide.RequestManager.x(SourceFile:1)\
        at com.bumptech.glide.RequestManager.b(SourceFile:1)\
        at com.bumptech.glide.manager.ActivityFragmentLifecycle.d(SourceFile:3)\
        at com.bumptech.glide.manager.SupportRequestManagerFragment.D1(SourceFile:2)\
        at androidx.fragment.app.Fragment.c2(SourceFile:5)\
        at androidx.fragment.app.FragmentStateManager.v(SourceFile:3)\
        at androidx.fragment.app.FragmentStateManager.m(SourceFile:9)\
        at androidx.fragment.app.FragmentStore.r(SourceFile:3)\
        at androidx.fragment.app.FragmentManager.P0(SourceFile:6)\
        at androidx.fragment.app.FragmentManager.T(SourceFile:3)\
        at androidx.fragment.app.FragmentManager.S(SourceFile:4)\
        at androidx.fragment.app.Fragment.c2(SourceFile:10)\
        at androidx.fragment.app.FragmentStateManager.v(SourceFile:3)\
        at androidx.fragment.app.FragmentStateManager.m(SourceFile:9)\
        at androidx.fragment.app.FragmentStore.r(SourceFile:3)\
        at androidx.fragment.app.FragmentManager.P0(SourceFile:6)\
        at androidx.fragment.app.FragmentManager.T(SourceFile:3)\
        at androidx.fragment.app.FragmentManager.S(SourceFile:4)\
        at androidx.fragment.app.FragmentController.q(SourceFile:1)\
        at androidx.fragment.app.FragmentActivity.onStart(SourceFile:9)\
        at androidx.appcompat.app.AppCompatActivity.onStart(SourceFile:1)\
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1244)\
        at android.app.Activity.performStart(Activity.java:6193)\
        at android.app.Activity.performRestart(Activity.java:6250)\
        at android.app.Activity.performResume(Activity.java:6255)\
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3319)\
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3365)\'a0\
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1574)\'a0\
        at android.os.Handler.dispatchMessage(Handler.java:111)\'a0\
        at android.os.Looper.loop(Looper.java:210)\'a0\
        at android.app.ActivityThread.main(ActivityThread.java:5839)\'a0\
        at java.lang.reflect.Method.invoke(Native Method)\'a0\
        at java.lang.reflect.Method.invoke(Method.java:372)\'a0\
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)\'a0\
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)\'a0\
```

**Comment by shenmaoqing** [comment]
We found the reason why occur "Already released" Exception(when 2020-06-19). Here is the log:

06-19 20:17:29.860 21511 21511 I RequestTracker: resumeRequests(), start
06-19 20:17:29.865 21511 21511 I RequestTracker: clearRemoveAndMaybeRecycle(), request=com.bumptech.glide.request.SingleRequest@477f55a
06-19 20:17:29.866 21511 21511 D Request : recycle(),  com.bumptech.glide.request.SingleRequest@477f55a
06-19 20:17:29.868 21511 21511 D Request : begin(),  com.bumptech.glide.request.SingleRequest@477f55a

We can find it is happened in Main thread(single thread),but the execute order is : resumeRequests -> getSnapShot -> one of them run clearRemoveAndMaybeRecycle -> and then request.begin.
Although we execute this in main thread, the request set is not thread safe.

Hope this can help
