### ISSUE TITLE
Glide unable to load this url and similars

### ISSUE THREAD

**Issue by TonyAndroid1991** [bumptech/glide#4506]
I have been using glide for many years, and never had this issue before. When I try to load this url and others with the same format Glide is unable to load them. I thought it was because of the size, but I used the .override() and it didn't worked either. I used the ,listener() to check and it prompts a status code 503, but the you can access to the url. Here the url that I am trying to load [](https://www.publicdomainpictures.net/pictures/10000/nahled/thinking-monkey-11282237747K8xB.jpg). 

**Glide Version**:

```
apply plugin: 'kotlin-kapt'

def glide_version = "4.12.0"
 implementation "com.github.bumptech.glide:glide:$glide_version"
 kapt "com.github.bumptech.glide:compiler:$glide_version"
```

**Integration libraries**:

Retrofit

**Device/Android Version**:

Samsung A70, Google pixel 4XL

**Issue details / Repro steps / Use case background**: 

I am just trying to load this image to an ImageView using, this is for a job interview

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with...

   ```
binding.name.text = gnome.name`

val requestOptions = RequestOptions()
                .placeholder(R.drawable.ic_launcher_background)
                .error(R.drawable.ic_launcher_background)
            

            Glide.with(binding.root.context)
                .applyDefaultRequestOptions(requestOptions)
                .load("https://www.publicdomainpictures.net/pictures/10000/nahled/thinking-monkey-11282237747K8xB.jpg")
                .listener(object : RequestListener<Drawable> {
                    override fun onLoadFailed(e: GlideException?, model: Any?, target: Target<Drawable>?, isFirstResource: Boolean
                    ): Boolean {
                        Log.e(TAG, "onLoadFailed: ${e}")
                        return false
                    }

                    override fun onResourceReady(resource: Drawable?, model: Any?, target: Target<Drawable>?, dataSource: DataSource?, isFirstResource: Boolean
                    ): Boolean {
                        return true
                    }
                })
                .into(binding.gnomeImage)
```
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <androidx.cardview.widget.CardView
        android:layout_marginTop="10dp"
        android:id="@+id/gnome_element"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content">

<ImageView
                    android:id="@+id/gnome_image"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    tools:srcCompat="@tools:sample/avatars"
                    android:scaleType="centerCrop" />
    </androidx.cardview.widget.CardView>
</layout>

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

The specific class I am working on is HomeRecyclerAdapter, here my repository

[](https://github.com/TonyAndroid1991/TestForVass)

**Comment by YangJ0720** [comment]
I have the same problem -> https://www.tianyabook.com/favicon.ico

**Comment by beyondeye** [comment]
same problem -> http://www.youtube.com/favicon.ico.
glide version; 4.12.0
                                                                                                    java.lang.Exception: error loading image http://www.youtube.com/favicon.ico
                                                                                                    	at com.splitbits.appcore.androidutils.GlideUtils$Companion$loadImageIntoViewAsync$5$1.onLoadFailed(GlideUtils.kt:365)
                                                                                                    	at com.bumptech.glide.request.SingleRequest.setErrorPlaceholder(SingleRequest.java:427)
                                                                                                    	at com.bumptech.glide.request.SingleRequest.onLoadFailed(SingleRequest.java:691)
                                                                                                    	at com.bumptech.glide.request.SingleRequest.onLoadFailed(SingleRequest.java:651)
                                                                                                    	at com.bumptech.glide.load.engine.EngineJob.callCallbackOnLoadFailed(EngineJob.java:173)
                                                                                                    	at com.bumptech.glide.load.engine.EngineJob$CallLoadFailed.run(EngineJob.java:402)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
