### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by ayyaztalat** [bumptech/glide#4507]
I am currently using Glide version : 4.11.0
implementation 'com.github.bumptech.glide:glide:4.11.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'

Cannot recycle a resource while it is still acquired
com.bumptech.glide.load.engine.EngineResource.recycle (EngineResource.java:68)
com.bumptech.glide.load.engine.ResourceRecycler$ResourceRecyclerCallback.handleMessage (ResourceRecycler.java:37)
android.os.Handler.dispatchMessage (Handler.java:103)
android.os.Looper.loop (Looper.java:227)
android.app.ActivityThread.main (ActivityThread.java:7822)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1026)

**Comment by mkocus** [comment]
We've got exactly the same issue.
It seems that the glide crashes randomly on production - this issue cannot be replicated locally.

Full stack log:
```
Fatal Exception: java.lang.IllegalStateException: Cannot recycle a resource while it is still acquired
       at com.bumptech.glide.load.engine.EngineResource.recycle(EngineResource.java:68)
       at com.bumptech.glide.load.engine.ResourceRecycler$ResourceRecyclerCallback.handleMessage(ResourceRecycler.java:37)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6680)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Environment:
- Android 9
- Glide 4.12.0

Do you have any ideas how to debug this issue?

**Comment by ayyaztalat** [comment]
For my case i have invalidate my current bitmap clear glide cache and then
reassigned bitmap thus it solved the problem but the main problem it
arrose. It slowed down the loading of receyclerview images

**Comment by mkocus** [comment]
Well, we are using glide a lot and cannot locate where precisely this crash happen :/
The steps that you are proposing are totally destructive - clearing glide cache all the time basically kills the performance and is a no-go for us.

**Comment by ayyaztalat** [comment]
I didn't say clear cache from everyone just from the glide which is used
inside the receyclerview
However if you can solve the actual problem.it is inside the cache it
doesn't let to update the cache which changes in iteration behavior which
causes the crash as what i observe

**Comment by mkocus** [comment]
Of course, but this is what I have in mind - we just don't want to clear glide cache.

**Comment by ayyaztalat** [comment]
Cool, thanks!

**Comment by mkocus** [comment]
We still didn't managed to fix this issue.
Do you have a knowledge when the glide tries to recycle resource? The stacktrace only shows that this is an async code which receives message to recycle resource - but who sent it and why?

**Comment by EzequielAdrianM** [comment]
Galaxy A20 Android 11
The crash doesn't point to any specific line of code in the application.

```
Fatal Exception: java.lang.IllegalStateException: Cannot recycle a resource while it is still acquired
       at com.bumptech.glide.load.engine.EngineResource.recycle(EngineResource.java:68)
       at com.bumptech.glide.load.engine.ResourceRecycler$ResourceRecyclerCallback.handleMessage(ResourceRecycler.java:37)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8645)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
