### ISSUE TITLE
ANR  getActiveNetworkInfo() is deprecated in API 29

### ISSUE THREAD

**Issue by LiWeiQiangAndroid** [bumptech/glide#4572]
ANR

android.os.BinderProxy.transactNative(Native Method)
android.os.BinderProxy.transact(Binder.java:753)
android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:1215)
android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:903)
com.bumptech.glide.manager.DefaultConnectivityMonitor.isConnected(DefaultConnectivityMonitor.java:90)
com.bumptech.glide.manager.DefaultConnectivityMonitor$1.onReceive(DefaultConnectivityMonitor.java:35)
android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_58300(LoadedApk.java:1435)
android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.$m$0(Unknown Source:4)
android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.run(Unknown Source:0)
android.os.Handler.handleCallback(Handler.java:808)
android.os.Handler.dispatchMessage(Handler.java:101)
android.os.Looper.loop(Looper.java:166)
android.app.ActivityThread.main(ActivityThread.java:7529)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

https://stackoverflow.com/questions/57277759/getactivenetworkinfo-is-deprecated-in-api-29

**Comment by tanmeifang** [comment]
i have the same issue

**Comment by AlexanderGH** [comment]
There's a few places in this code where an IPC is being made on the UI thread. I haven't looked at the code in detail to know if there's an easy fix though (i only checked to confirm that the issue hasn't already been fixed).

The first location is the one listed in the original comment, in onReceive.
The second is actually more problematic IMO, in that it happens in Glide.with():
```
  at android.os.BinderProxy.transactNative(Native method)
  at android.os.BinderProxy.transact(BinderProxy.java:550)
  at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:2140)
  at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:998)
  at com.bumptech.glide.manager.DefaultConnectivityMonitor.isConnected(:12)
  at com.bumptech.glide.manager.DefaultConnectivityMonitor.onStart(:6)
  at com.bumptech.glide.manager.ApplicationLifecycle.addListener(:0)
  at com.bumptech.glide.RequestManager.<init>(:110)
  at com.bumptech.glide.manager.RequestManagerRetriever.get(:268435608)
  - locked <0x0d99aed4> (a com.bumptech.glide.manager.RequestManagerRetriever)
  at com.bumptech.glide.Glide.with(:331)
```

In both cases, the cause is `DefaultConnectivityMonitor.isConnected`.

In addition, as the original commented noted, `getActiveNetworkInfo` is deprecated in favor of checking for specific types of networks, but that is both a simpler, and less impactful change compared to the ANR risk of the IPCs.
