### ISSUE TITLE
crash while trimMemory

### ISSUE THREAD

**Issue by DanGdl** [bumptech/glide#4595]
system: Android 9
device:  samsung Galaxy s8+

Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.bumptech.glide.Glide.trimMemory(Glide.java:688)
       at com.bumptech.glide.Glide.onTrimMemory(Glide.java:900)
       at android.app.Application.onTrimMemory(Application.java:174)
       at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:5762)
       at android.app.ActivityThread.access$1000(ActivityThread.java:237)
       at android.app.ActivityThread$ApplicationThread.lambda$scheduleTrimMemory$0(ActivityThread.java:1529)
       at android.app.-$$Lambda$ActivityThread$ApplicationThread$tUGFX7CUhzB4Pg5wFd5yeqOnu38.accept(:8)
       at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:258)
       at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:182)
       at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:77)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:698)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by sjudd** [comment]
Please re-open if you're able to reproduce on the latest version.
