### ISSUE TITLE
ava.lang.NullPointerException

### ISSUE THREAD

**Issue by cwl-git** [bumptech/glide#4604]
**### java.lang.NullPointerException
Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
com.bumptech.glide.load.resource.gif.GifDrawable.draw(GifDrawable.java:291)**

### logcat：
1
android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:65)
2
android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:277)
3
android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
4
com.bumptech.glide.load.resource.gif.GifDrawable.draw(GifDrawable.java:291)
5
android.widget.ImageView.onDraw(ImageView.java:1505)
6
android.view.View.draw(View.java:21618)
7
android.view.View.updateDisplayListIfDirty(View.java:20483)
8
android.view.View.draw(View.java:21350)
9
android.view.ViewGroup.drawChild(ViewGroup.java:4446)
10
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
11
androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1882)
12
android.view.View.updateDisplayListIfDirty(View.java:20474)
13
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4428)
14
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4401)
15
android.view.View.updateDisplayListIfDirty(View.java:20441)
16
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4428)
17
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4401)
18
android.view.View.updateDisplayListIfDirty(View.java:20441)
19
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4428)
20
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4401)
21
android.view.View.updateDisplayListIfDirty(View.java:20441)
22
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4428)
23
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4401)
24
android.view.View.updateDisplayListIfDirty(View.java:20441)
25
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4428)
26
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4401)
27
android.view.View.updateDisplayListIfDirty(View.java:20441)
28
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4428)
29
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4401)
30
android.view.View.updateDisplayListIfDirty(View.java:20441)
31
android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:584)
32
android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:590)
33
android.view.ThreadedRenderer.draw(ThreadedRenderer.java:668)
34
android.view.ViewRootImpl.draw(ViewRootImpl.java:3840)
35
android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3648)
36
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2954)
37
android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1857)
38
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8089)
39
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
40
android.view.Choreographer.doCallbacks(Choreographer.java:875)
41
android.view.Choreographer.doFrame(Choreographer.java:776)
42
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
43
android.os.Handler.handleCallback(Handler.java:888)
44
android.os.Handler.dispatchMessage(Handler.java:100)
45
android.os.Looper.loop(Looper.java:213)
46
android.app.ActivityThread.main(ActivityThread.java:8178)
47
java.lang.reflect.Method.invoke(Native Method)
48
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
49
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by JoyHong** [comment]
any update?

**Comment by leonsir** [comment]
> any update?

the latest version(4.13.2) solve this problem?

**Comment by EdwinSmartBoy** [comment]
the latest version(4.13.2)  Still have this problem

**Comment by dantist0** [comment]
we very need fix this

**Comment by xiashengming-kanyun** [comment]
I also encountered this problem
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
                                                                                                    	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:65)
                                                                                                    	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:277)
                                                                                                    	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
                                                                                                    	at com.bumptech.glide.load.resource.gif.GifDrawable.draw(GifDrawable.java:291)
                                                                                                    	at android.widget.ImageView.onDraw(ImageView.java:1418)
                                                                                                    	at android.view.View.draw(View.java:22354)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21230)
                                                                                                    	at android.view.View.draw(View.java:22085)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
                                                                                                    	at android.view.View.draw(View.java:22357)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21230)
                                                                                                    	at android.view.View.draw(View.java:22085)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
                                                                                                    	at android.view.View.draw(View.java:22357)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21230)
                                                                                                    	at android.view.View.draw(View.java:22085)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
                                                                                                    	at android.view.View.draw(View.java:22357)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21230)
                                                                                                    	at android.view.View.draw(View.java:22085)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
                                                                                                    	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.java:268)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
                                                                                                    	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.java:256)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21221)
                                                                                                    	at android.view.View.draw(View.java:22085)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
                                                                                                    	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21221)
                                                                                                    	at android.view.View.draw(View.java:22085)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21221)
                                                                                                    	at android.view.View.draw(View.java:22085)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21221)
                                                                                                    	at android.view.View.draw(View.java:22085)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21221)
                                                                                                    	at android.view.View.draw(View.java:22085)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21221)
                                                                                                    	at android.view.View.draw(View.java:22085)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
                                                                                                    	at android.view.View.draw(View.java:22357)
                                                                                                    	at com.android.internal.policy.DecorView.draw(DecorView.java:806)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:21230)
                                                                                                    	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
                                                                                                    	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
                                                                                                    	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
                                                                                                    	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4108)
                                                                                                    	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3835)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3106)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1950)
