### ISSUE TITLE
Glide not loading some images when loading multiple through a recyclerView

### ISSUE THREAD

**Issue by RaulRohjans** [bumptech/glide#4635]
**Glide Version**: 4.12.0

**Integration libraries**: No

**Device/Android Version**: Tested on Pixel 4 XL, Galaxy S10, Galaxy S8, Galaxy A70. Same issue on all of them.

**Issue details / Repro steps / Use case background**: I have an activity with a recycler view in it that loads items in a Card View. These items are composed of an image and some text. The image is loaded from a URL. I noticed a weird behavior, there are only some specific images that decide not to load, but this can change across device and item quantity.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```Glide.with(this).load(thumbnail).into(img_thumbnail);
```

**Layout XML**:
```<ImageView
                    android:id="@+id/img_thumbnail"
                    android:layout_width="550px"
                    android:layout_height="777px"
                    android:layout_centerHorizontal="true"/>
```

**Stack trace / LogCat**:
```
W/Glide: Load failed for https://drive.google.com/uc?export=download&id=1BL-AcswbVSrX7b7bcMOReD1ugzN1AQCv with size [550x777]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 root cause:
    com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 root cause:
    com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 root cause:
    com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: -1)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class com.bumptech.glide.load.HttpException: Failed to connect or obtain data, status code: -1
I/Glide: Root cause (1 of 1)
    com.bumptech.glide.load.HttpException: Failed to connect or obtain data, status code: -1
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:98)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:58)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
        at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
     Caused by: java.net.SocketTimeoutException: timeout
        at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:214)
        at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
        at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
        at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:95)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:58) 
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100) 
        at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70) 
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63) 
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311) 
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280) 
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393) 
     Caused by: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.read(SocketInputStream.java:209)
        at java.net.SocketInputStream.read(SocketInputStream.java:144)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
        at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307) 
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301) 
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197) 
        at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188) 
        at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129) 
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750) 
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248) 
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211) 
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30) 
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:95) 
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:58) 
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100) 
        at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70) 
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63) 
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311) 
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280) 
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393) 
```

**Comment by Faydee1220** [comment]
I got same error `Failed to connect or obtain data, status code: -1` and found out another solution here:
https://medium.com/@mustafayanik/how-to-fix-android-glide-ssl-exception-ab9b2c4dbada

Maybe it's just a workaround solution, but it works for me.

**Comment by sjudd** [comment]
`Caused by: java.net.SocketTimeoutException: timeout`

That's a connection issue.

**Comment by RaulRohjans** [comment]
> `Caused by: java.net.SocketTimeoutException: timeout`
> 
> That's a connection issue.

That is very weird since all the links I'm using to obtain the images work and all of the devices tested had a very good internet connection.


> I got same error `Failed to connect or obtain data, status code: -1` and found out another solution here:
> https://medium.com/@mustafayanik/how-to-fix-android-glide-ssl-exception-ab9b2c4dbada
> 
> Maybe it's just a workaround solution, but it works for me.

I will give this a try later and post a comment with the result. Thank you.

**Comment by RaulRohjans** [comment]
@Faydee1220 I have tried your solution, but unfortunately it did not fix it. I, however, noticed a different error when loading some other images on another activity. It gives me a 403 error.

´´´
W/Glide: Load failed for https://drive.google.com/uc?export=download&id=1B-ExsAlUv0wMP1bylInlEl4M1QF5cESU with size [550x777]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 root cause:
    com.bumptech.glide.load.HttpException(Forbidden, status code: 403)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 root cause:
    com.bumptech.glide.load.HttpException(Forbidden, status code: 403)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 root cause:
    com.bumptech.glide.load.HttpException(Forbidden, status code: 403)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class com.bumptech.glide.load.HttpException: Forbidden, status code: 403
´´´
