### ISSUE TITLE
activeresource

### ISSUE THREAD

**Issue by honglei92** [bumptech/glide#4662]
glide 4.12.0

"glide-active-resources" prio=5 tid=19 Waiting
  | group="main" sCount=1 ucsCount=0 flags=1 obj=0x12d007e0 self=0xb40000774dd8e1b0
  | sysTid=15041 nice=10 cgrp=default sched=0/0 handle=0x7556ce5cb0
  | state=S schedstat=( 200260 24948 2 ) utm=0 stm=0 core=4 HZ=100
  | stack=0x7556be2000-0x7556be4000 stackSize=1039KB
  | held mutexes=
  at java.lang.Object.wait(Native method)
  - waiting on <0x0c55548c> (a java.lang.Object)
  at java.lang.Object.wait(Object.java:442)
  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
  - locked <0x0c55548c> (a java.lang.Object)
  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
  at com.bumptech.glide.load.engine.ActiveResources.cleanReferenceQueue(SourceFile:2)
  at com.bumptech.glide.load.engine.ActiveResources$2.run(SourceFile:1)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  at com.bumptech.glide.load.engine.ActiveResources$1$1.run(SourceFile:2)
  at java.lang.Thread.run(Thread.java:920)
 in my  log，there is a load file error

**Comment by mingway426** [comment]
Same problem! need help~ @sjudd

**Comment by mingway426** [comment]
@honglei92 这个 ANR 的问题，搞定了吗？
