### ISSUE TITLE
Too many receivers

### ISSUE THREAD

**Issue by pbaiyy** [bumptech/glide#4682]
Stack trace:  
java.lang.reflect.UndeclaredThrowableException
	at $Proxy2.registerReceiverWithFeature(Unknown Source)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1636)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1590)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1578)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:679)
	at com.bumptech.glide.manager.e.a(DefaultConnectivityMonitor.java:60)
	at com.bumptech.glide.manager.e.b(DefaultConnectivityMonitor.java:106)
	at com.bumptech.glide.manager.a.a(ActivityFragmentLifecycle.java:51)
	at com.bumptech.glide.manager.r.onStart(SupportRequestManagerFragment.java:203)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:2632)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:915)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStart(FragmentManagerImpl.java:2619)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:2641)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:915)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStart(FragmentManagerImpl.java:2619)
	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:257)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:551)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1436)
	at android.app.Activity.performStart(Activity.java:8190)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3565)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8056)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.a.a.a.b$f$a.invoke(LoadedApkHuaWei.java:135)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	... 38 more
Caused by: java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 19896, callerPackage: com.xxxx.xxxx
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2384)
	at android.os.Parcel.createException(Parcel.java:2360)
	at android.os.Parcel.readException(Parcel.java:2343)
	at android.os.Parcel.readException(Parcel.java:2285)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5650)

when I use Glide ,this bug always happen.

**Comment by baole** [comment]
We also have the same issue, Glide 4.12.0
`Too many receivers, total of 1000, registered for pid: 11214, callerPackage: net.tandem`

```android.os.Parcel.createExceptionOrNull (Parcel.java:2393)
android.os.Parcel.createException (Parcel.java:2369)
android.os.Parcel.readException (Parcel.java:2352)
android.os.Parcel.readException (Parcel.java:2294)
android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature (IActivityManager.java:6402)
android.app.ContextImpl.registerReceiverInternal (ContextImpl.java:1696)
android.app.ContextImpl.registerReceiver (ContextImpl.java:1650)
android.app.ContextImpl.registerReceiver (ContextImpl.java:1638)
android.content.ContextWrapper.registerReceiver (ContextWrapper.java:686)
com.bumptech.glide.manager.DefaultConnectivityMonitor.register (DefaultConnectivityMonitor.java:60)
com.bumptech.glide.manager.DefaultConnectivityMonitor.onStart (DefaultConnectivityMonitor.java:106)
com.bumptech.glide.manager.ActivityFragmentLifecycle.onStart (ActivityFragmentLifecycle.java:51)
com.bumptech.glide.manager.SupportRequestManagerFragment.onStart (SupportRequestManagerFragment.java:203)
androidx.fragment.app.Fragment.performStart (Fragment.java:3021)
androidx.fragment.app.FragmentStateManager.start (FragmentStateManager.java:589)
androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:300)
androidx.fragment.app.FragmentStore.moveToExpectedState (FragmentStore.java:112)
androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1647)
androidx.fragment.app.FragmentManager.dispatchStateChange (FragmentManager.java:3128)
androidx.fragment.app.FragmentManager.dispatchStart (FragmentManager.java:3079)
androidx.fragment.app.FragmentController.dispatchStart (FragmentController.java:262)
androidx.fragment.app.FragmentActivity.onStart (FragmentActivity.java:510)
androidx.appcompat.app.AppCompatActivity.onStart (AppCompatActivity.java:246)
com.trello.rxlifecycle4.components.support.RxAppCompatActivity.onStart (RxAppCompatActivity.java:80)
net.tandem.ext.anr.ArnInjectionActivity.onStart (ArnInjectionActivity.java:13)
net.tandem.ui.MainActivity.onStart (MainActivity.java:1084)
android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1435)
android.app.Activity.performStart (Activity.java:8231)
android.app.ActivityThread.handleStartActivity (ActivityThread.java:3861)
android.app.servertransaction.TransactionExecutor.performLifecycleSequence (TransactionExecutor.java:221)
android.app.servertransaction.TransactionExecutor.cycleToPath (TransactionExecutor.java:201)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:173)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2325)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:246)
android.app.ActivityThread.main (ActivityThread.java:8633)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
```

**Comment by baole** [comment]
It seems to be fixed in the `master` branch. Is there any plan for new release?
