### ISSUE TITLE
4.12.0.3 and 4.12.0.4 introduces a regression

### ISSUE THREAD

**Issue by bdovaz** [bumptech/glide#4689]
I have this problem.

If I roll back on NuGet to 4.12.0.2 it doesn't appear.

``
Error		System.IO.FileNotFoundException: Could not find file 'C:\Users\myuser\.nuget\packages\xamarin.android.glide.disklrucache\4.12.0.4\buildTransitive\monoandroid10.0\..\..\jar\annotations.jar'.
File name: 'C:\Users\myuser\.nuget\packages\xamarin.android.glide.disklrucache\4.12.0.4\buildTransitive\monoandroid10.0\..\..\jar\annotations.jar'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at Xamarin.Android.Tasks.MonoAndroidHelper.SizeAndContentFileComparer.GetHashCode(FileInfo obj)
   at System.Linq.Set`1.InternalGetHashCode(TElement value)
   at System.Linq.Set`1.Find(TElement value, Boolean add)
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Xamarin.Android.Tasks.CheckDuplicateJavaLibraries.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/builder/azdo/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17	Xamarin.Android			
``

**Glide Version**: 4.12.0.3 or 4.12.0.4

**Comment by DmitriyKirakosyan** [comment]
Facing the same

**Comment by bmarrdev** [comment]
This issue was fixed in 4.12.0.6
