### ISSUE TITLE
java.lang.VerifyError: Verifier rejected class com.bumptech.glide.load.ImageHeaderParser$ImageType

### ISSUE THREAD

**Issue by TsmileAssassin** [bumptech/glide#4698]
Some users of my app have such a crash stack. I don't know the specific reason. Please help me~

**Glide Version**:
    implementation 'com.github.bumptech.glide:glide:4.12.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'
    implementation 'com.github.bumptech.glide:okhttp3-integration:4.12.0'

**Integration libraries**:
    implementation 'com.squareup.okhttp3:okhttp:4.9.1'

**Device/Android Version**:
Android 29

**Issue details / Repro steps / Use case background**: 

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
Glide.with(context).load(url).format(DecodeFormat.PREFER_RGB_565).into(imageView);
```

**Stack trace / LogCat**:
```ruby
11-30 21:23:38.139 D/AndroidRuntime(19758): Shutting down VM
11-30 21:23:38.141 E/AndroidRuntime(19758): FATAL EXCEPTION: main
11-30 21:23:38.141 E/AndroidRuntime(19758): Process: com.picovr.store, PID: 19758
11-30 21:23:38.141 E/AndroidRuntime(19758): java.lang.VerifyError: Verifier rejected class com.bumptech.glide.load.ImageHeaderParser$ImageType: void com.bumptech.glide.load.ImageHeaderParser$ImageType.<init>(java.lang.String, int, boolean) failed to verify: void com.bumptech.glide.load.ImageHeaderParser$ImageType.<init>(java.lang.String, int, boolean): [0x3] cannot access instance field java.util.ArrayList androidx.transition.Transition.mAnimators from object of type Precise Reference: com.bumptech.glide.load.ImageHeaderParser$ImageType (declaration of 'com.bumptech.glide.load.ImageHeaderParser$ImageType' appears in base.apk)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at com.bumptech.glide.load.resource.bitmap.Downsampler.<clinit>(Downsampler.java:11)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at com.bumptech.glide.Glide.<init>(Glide.java:19)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at com.bumptech.glide.GlideBuilder.build(GlideBuilder.java:29)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at com.bumptech.glide.Glide.initializeGlide(Glide.java:23)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at com.bumptech.glide.Glide.initializeGlide(Glide.java:1)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:3)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at com.bumptech.glide.Glide.get(Glide.java:5)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at com.bumptech.glide.Glide.getRetriever(Glide.java:2)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at com.bumptech.glide.Glide.with(Glide.java:1)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at V.e.a(ImageLoadUtil.java:1)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at com.acs.store.view.MainMenuUser.setIcon(MainMenuUser.java:1)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at T.oa.b(UserFragment.java:1)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at T.oa.a(UserFragment.java:5)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at com.acs.store.ui.EventActivity.onLogin(EventActivity.java:4)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at U.l.c(UserManager.java:3)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at U.l.a(UserManager.java:2)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at U.h.handleMessage(UserManager.java:2)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at android.os.Handler.dispatchMessage(Handler.java:107)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at android.os.Looper.loop(Looper.java:214)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at android.app.ActivityThread.main(ActivityThread.java:7417)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at java.lang.reflect.Method.invoke(Native Method)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
11-30 21:23:38.141 E/AndroidRuntime(19758): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by lichong951** [comment]
DecodeFormat.PREFER_RGB_565 改成RGB_8888.日志显示有透明通道或动画信息
