### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by SS1922** [bumptech/glide#4730]
2022-01-16 07:33:13.128 15860-15860/com.ssripper.sschat E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ssripper.sschat, PID: 15860
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.ssripper.sschat.Activities.MainActivity$4.onDataChange(MainActivity.java:176)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(ValueEventRegistration.java:75)
        at com.google.firebase.database.core.view.DataEvent.fire(DataEvent.java:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(EventRaiser.java:55)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by jaredsburrows** [comment]
What is on line MainActivity.java:176?
