### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:348)

### ISSUE THREAD

**Issue by aykutuludag** [bumptech/glide#4794]
**Glide Version**: 4.12.0

**Integration libraries**: com.squareup.okhttp3:okhttp:4.9.1

**Device/Android Version**: All Devices

**Issue details / Repro steps / Use case background**:  I don't know probably home screen while loading profile picture

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
```java
   String base64String = profilPhotoSplitted[1];
   byte[] decodedString = Base64.decode(base64String, Base64.NO_WRAP);
   Bitmap decodedByte = BitmapFactory.decodeByteArray(decodedString, 0, decodedString.length);

   Glide.with(this).load(decodedByte).error(R.drawable.userprofile_placeholder).into(civUserProfile);
```

**Layout XML**:
```xml
<FrameLayout xmlns:android="...
```

**Stack trace / LogCat**:
```ruby
Fatal Exception: java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
       at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:348)
       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:148)
       at com.bumptech.glide.Glide.with(Glide.java:826)
       at app.package.name.MainActivity.initDrawerHeader(MainActivity.java:1969)
       at app.package.name.gui.fragment.UserFragment$4.onSuccess(UserFragment.java:766)
       at app.package.name.RequestServiceHelper$ParseAndSendResponseWithObject.onPostExecute(RequestServiceHelper.java:530)
       at app.package.name.RequestServiceHelper$ParseAndSendResponseWithObject.onPostExecute(RequestServiceHelper.java:421)
       at android.os.AsyncTask.finish(AsyncTask.java:695)
       at android.os.AsyncTask.access$600(AsyncTask.java:180)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7127)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

![image](https://user-images.githubusercontent.com/18382503/165405873-4547a252-e8bb-402b-a863-7ca2eb5504f9.png)

**Comment by sjudd** [comment]
Your AsyncTask is finishing after your Activity is destroyed. You need to make sure you cancel your AsyncTask or use some other pattern to avoid interacting with a destroyed activity.
