### ISSUE TITLE
Could not find com.bumptech.glide.R.id when using Glide 4.13.2

### ISSUE THREAD

**Issue by huannan** [bumptech/glide#4798]
I got an exception when using Glide 4.13.2, compile sdk is Android 12 ：

```
03-26 08:58:55.557 31616 31616 D AndroidRuntime: Shutting down VM
03-26 08:58:55.559 31616 31616 E AndroidRuntime: FATAL EXCEPTION: main
03-26 08:58:55.559 31616 31616 E AndroidRuntime: Process: com.meizu.media.reader, PID: 31616
03-26 08:58:55.559 31616 31616 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/R$id;
03-26 08:58:55.559 31616 31616 E AndroidRuntime: 	at com.bumptech.glide.request.target.ViewTarget.<clinit>(ViewTarget.java:52)
03-26 08:58:55.559 31616 31616 E AndroidRuntime: 	at com.bumptech.glide.request.target.ImageViewTargetFactory.buildTarget(ImageViewTargetFactory.java:20)
03-26 08:58:55.559 31616 31616 E AndroidRuntime: 	at com.bumptech.glide.GlideContext.buildImageViewTarget(GlideContext.java:100)
03-26 08:58:55.559 31616 31616 E AndroidRuntime: 	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:873)
```

**Comment by huannan** [comment]
Is this exception related to the new AVIF dependency library?

**Comment by huannan** [comment]
I have found the reason: AS could not download Glide aar and is just use jar

**Comment by binbinyYang** [comment]
glide  aar  4.13.2
  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/gifdecoder/GifDecoder$BitmapProvider;
        at com.bumptech.glide.Glide.<init>(Glide.java:411)
        at com.bumptech.glide.GlideBuilder.build(GlideBuilder.java:571)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:316)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:268)
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:212)
        at com.bumptech.glide.Glide.get(Glide.java:193)
        at com.bumptech.glide.Glide.getRetriever(Glide.java:791)
        at com.bumptech.glide.Glide.with(Glide.java:818)
        at com.xlw.car.settings.home.XlwCarHomeFragmentAdapter.loadOneTimeGif(XlwCarHomeFragmentAdapter.java:179)
        at com.xlw.car.settings.home.XlwCarHomeFragmentAdapter.onBindViewHolder(XlwCarHomeFragmentAdapter.java:78)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7031)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7073)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5990)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6257)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6096)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6092)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(Recyc
