### ISSUE TITLE
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.Object[]

### ISSUE THREAD

**Issue by qingguoguo** [bumptech/glide#4810]
Glide Version: 4.11.0

Device/Android Version: HUAWEI (Android 8.1.0)

Stack trace / LogCat:

Thread Name: 'main'
Back traces starts.
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.Object[]
	at androidx.collection.SimpleArrayMap.allocArrays(SimpleArrayMap.java:184)
	at androidx.collection.SimpleArrayMap.put(SimpleArrayMap.java:458)
	at com.bumptech.glide.util.CachedHashCodeArrayMap.put(CachedHashCodeArrayMap.java:34)
	at com.bumptech.glide.request.BaseRequestOptions.transform(BaseRequestOptions.java:1017)
	at com.bumptech.glide.request.BaseRequestOptions.transform(BaseRequestOptions.java:971)
	at com.bumptech.glide.request.BaseRequestOptions.transform(BaseRequestOptions.java:893)
	at com.bumptech.glide.request.BaseRequestOptions.transform(BaseRequestOptions.java:846)
	at com.bumptech.glide.request.BaseRequestOptions.scaleOnlyTransform(BaseRequestOptions.java:852)
	at com.bumptech.glide.request.BaseRequestOptions.centerInside(BaseRequestOptions.java:786)
	at com.bumptech.glide.request.BaseRequestOptions.scaleOnlyTransform(BaseRequestOptions.java:870)

**Comment by sjudd** [comment]
This looks like an androidx bug, maybe a newer version would help? If not, you'll want to report the issue to them.
