### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference

### ISSUE THREAD

**Issue by michael-winkler** [bumptech/glide#4819]
**Description:**

It looks like there is a uncatched null pointer exception in the hash code function.    
`com.bumptech.glide.load.engine.EngineKey.hashCode(EngineKey.java:63)`

**Environment**

`implementation 'com.onesignal:OneSignal:4.7.3'`

**Steps to Reproduce Issue:**

I can't recreate the bug since it was posted by Firebase Crashlytics.

**Anything else:**

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
       at java.io.UnixFileSystem.hashCode(UnixFileSystem.java:427)
       at java.io.File.hashCode(File.java:2115)
       at com.bumptech.glide.load.engine.EngineKey.hashCode(EngineKey.java:63)
       at java.util.HashMap.hash(HashMap.java:338)
       at java.util.HashMap.get(HashMap.java:556)
       at com.bumptech.glide.load.engine.ActiveResources.get(ActiveResources.java:94)
       at com.bumptech.glide.load.engine.Engine.loadFromActiveResources(Engine.java:327)
       at com.bumptech.glide.load.engine.Engine.loadFromMemory(Engine.java:302)
       at com.bumptech.glide.load.engine.Engine.load(Engine.java:190)
       at com.bumptech.glide.request.SingleRequest.onSizeReady(SingleRequest.java:468)
       at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:256)
       at com.bumptech.glide.manager.RequestTracker.runRequest(RequestTracker.java:41)
       at com.bumptech.glide.RequestManager.track(RequestManager.java:671)
       at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:813)
       at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:780)
       at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:771)
       at com.mugler.sitemanTicketSystem.adapters.FotosAdapter.onBindViewHolder(FotosAdapter.kt:89)
       at com.mugler.sitemanTicketSystem.adapters.FotosAdapter.onBindViewHolder(FotosAdapter.kt:42)
       at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7531)
       at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7614)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6435)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6701)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6541)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6537)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4475)
       at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3852)
       at android.view.View.measure(View.java:25982)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7073)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
       at android.view.View.measure(View.java:25982)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7073)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
       at android.view.View.measure(View.java:25982)
       at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1695)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:604)
       at android.view.View.measure(View.java:25982)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7073)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
       at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:99)
       at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:2241)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:831)
       at android.view.View.measure(View.java:25982)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7073)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
       at android.view.View.measure(View.java:25982)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7073)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
       at android.view.View.measure(View.java:25982)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7073)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:25982)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7073)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
       at android.view.View.measure(View.java:25982)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7073)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:832)
       at android.view.View.measure(View.java:25982)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3848)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2587)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2857)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2299)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9127)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1228)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1025)
       at android.view.Choreographer.doFrame(Choreographer.java:930)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1213)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8210)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

### Device:    
- Android 12
- OPPO (CPH2195)

**Comment by Mika-89** [comment]
The problem is at this line:

https://github.com/bumptech/glide/blob/fd5e7df9fc8d43522a32b3be966f5895e78a8d15/library/src/main/java/com/bumptech/glide/load/engine/EngineKey.java#L63

@Override
  ```
public int hashCode() {
    if (hashCode == 0) {
      hashCode = model.hashCode();
      hashCode = 31 * hashCode + signature.hashCode();
      hashCode = 31 * hashCode + width;
      hashCode = 31 * hashCode + height;
      hashCode = 31 * hashCode + transformations.hashCode();
      hashCode = 31 * hashCode + resourceClass.hashCode();
      hashCode = 31 * hashCode + transcodeClass.hashCode();
      hashCode = 31 * hashCode + options.hashCode();
    }
    return hashCode;
  }
```

Would be great to add there a null pointer check.

**Comment by pradeep-orbi** [comment]
@Mika-89 How did you solve this issue ? I have added null check on file object before passing to Glide load(file), but still i see it is crashing. Any idea on how to fix this issue ?
```
 Glide.with(context).load(file).into(imageView)
```

**Comment by pradeep-orbi** [comment]
In my case, the issue was not related to Glide. The issue was in Gson() serialization and deserialization of File object. Getting this issue on Android 12. Fixed it by storing file path(String object) instead of File object.

**Comment by Mika-89** [comment]
Sorry for the late response. I didn't solved it yet. Current on vacation.
But thanks for the hint. Will look at my source code if it's the same case for the crash,

**Comment by Xewlie** [comment]
Any update on this, has anyone solved it, getting this on a massive amount of samsung phones with android 12 on crashlytics
