### ISSUE TITLE
java.lang.IllegalStateException  Already released 

### ISSUE THREAD

**Issue by hangwangyu** [bumptech/glide#4832]
at com.bumptech.glide.util.pool.StateVerifier$DefaultStateVerifier.throwIfRecycled(StateVerifier.java:46)
	at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:236)
	at com.bumptech.glide.manager.RequestTracker.resumeRequests(RequestTracker.java:128)
	at com.bumptech.glide.RequestManager.resumeRequests(RequestManager.java:292)
	at com.bumptech.glide.RequestManager.onStart(RequestManager.java:317)
	at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStart(ActivityFragmentLifecycle.java:51)
	at com.bumptech.glide.manager.SupportRequestManagerFragment.onStart(SupportRequestManagerFragment.java:182)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:2477)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1494)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3235)
	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:212)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:628)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178)

**Comment by jaredsburrows** [comment]
How do you reproduce this? Do you have example code?

**Comment by menshen** [comment]
i face this problem
firebase collect this crash
bu i cant reproduce this
has any fix for this bug?

**Comment by menshen** [comment]
> How do you reproduce this? Do you have example code?

hi, guys 
has any fix for this bug , my glide version is 4.16.0
I've tried many methods, but I couldn't reproduce it.
