### ISSUE TITLE
Error creating a bitmap from a File

### ISSUE THREAD

**Issue by russellhoff** [bumptech/glide#484]
I've an AsyncTask which creates bitmaps from files:

-------------------------------------------------------------------------------------------------------------------------------
private class BitmapFileGlideTask extends AsyncTask<Void, Void, Void> {

		private File file;
		private int width, height;
		private boolean isBackground;

		private Bitmap bmp;

		public BitmapFileGlideTask(File pFile, int pWidth, int pHeight, boolean pIsBackground){
			file = pFile;
			width = pWidth;
			height = pHeight;
			isBackground = pIsBackground;
		}

		@Override
		protected Void doInBackground(Void... params) {
			Looper.prepare();
			try {
				bmp = Glide.with(getContext())
						.load(file)
						.asBitmap()
						.into(width, height)
						.get();
			} catch (final ExecutionException e) {
				Log.e(TAG, e.getMessage());
			} catch (final InterruptedException e) {
				Log.e(TAG, e.getMessage());
			}

			return null;

		}

		@Override
		protected void onPostExecute(Void aVoid) {
			if(isBackground){
				mBackground = bmp;
			}else{
				mForeground = bmp;
			}
			Log.d(TAG, "Image loaded");
		}

	}
-------------------------------------------------------------------------------------------------------------------------------

These lines execute an instance of that AsyncTask:

-------------------------------------------------------------------------------------------------------------------------------
		
File foregroundFile = new File(imagesFolder + mPages[0]);
		File backgroundFile = new File(imagesFolder + mPages[1]);

		BitmapFileGlideTask taskForeground = new BitmapFileGlideTask(foregroundFile, width, height, false);
		taskForeground.execute();

		BitmapFileGlideTask taskBackground = new BitmapFileGlideTask(backgroundFile, width, height, true);
		taskBackground.execute();

-------------------------------------------------------------------------------------------------------------------------------

Unfortunately, an uncaught exception is thrown:
-------------------------------------------------------------------------------------------------------------------------------
06-04 10:42:21.064  12899-13331/com.ingartek.android.ipuin E/PriorityExecutor﹕ Request threw uncaught throwable
    java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Failed to allocate a 6127628 byte allocation with 4344378 free bytes and 4MB until OOM
            at java.util.concurrent.FutureTask.report(FutureTask.java:93)
            at java.util.concurrent.FutureTask.get(FutureTask.java:163)
            at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1120)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
            at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 6127628 byte allocation with 4344378 free bytes and 4MB until OOM
            at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
            at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
            at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:771)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:747)
            at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:329)
            at com.bumptech.glide.load.resource.bitmap.Downsampler.downsampleWithSize(Downsampler.java:220)
            at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:153)
            at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:50)
            at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
            at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:39)
            at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)
            at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:190)
            at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
            at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
            at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
            at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
            at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
            at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
-------------------------------------------------------------------------------------------------------------------------------

Why is that happening?

**Comment by TWiStErRob** [comment]
You're probably loading a lot of images at once on one screen and there's no more memory for the next one.
If this is not the case, then you have a memory leak somewhere.

In any case, reproduce the above exception in your app and then [take a heap dump and check what's using so much memory](http://android-developers.blogspot.hu/2011/03/memory-analysis-for-android.html).

**Comment by TWiStErRob** [comment]
You should also note that [non-top activities in the active app are not destroyed to reclaim memory](http://commonsware.com/blog/2011/10/03/activities-not-destroyed-to-free-heap-space.html).

**Comment by russellhoff** [comment]
The original issue is that the application hasn't been done by me (on the company), and I'm making some changes...

It's a storytelling-like app. The app works nice, but on Samsung devices images aren't shown, indeed, the app crashes if I don't handle OutOfMemoryException.

Because of that, I decided to use an image library. 

I've installed the application through ADB using windows' powershell and a warning message had appeared telling me about the memory leak. So I'm aware of it, but I don't know how to solve it. 

Speaking about the problem, images are being loaded from a expansion file downloaded after the app installation (OBB files). Images are pictures drawn by an artist and consists of a high resolution 2048x1496...

**Comment by TWiStErRob** [comment]
Assuming mBackground and mForeground is used like: `mForegroundView.setImageBitmap(mForeground)`, you could greatly simplify loading the images:

```java
Glide.with(getContext()) // use this if you're in a Fragment/Activity!
        .load(new File(imagesFolder + mPages[0]))
        .into(mForegroundView);

Glide.with(getContext())
        .load(new File(imagesFolder + mPages[1]))
        .into(mForegroundView);
```
The whole point of using an image loader is that it'll handle async and sizes FOR YOU. Glide will take the size of the target view and only load a Bitmap big enough to fit it, using much less memory than loading originals.

> I've installed the application through ADB using windows' powershell

Installing through ADB is not the easiest way to develop an Android application, as a developer you shouldn't accept less than a one-click compile-deploy-run cycle. You should invest a few days of setting up an IDE where you can debug, see logs (logcat) and track memory usage and not manually deploy. See https://developer.android.com/sdk/index.html

> but I don't know how to solve it.

http://android-developers.blogspot.hu/2011/03/memory-analysis-for-android.html
The article I linked describes how to find the entities hogging your memory. From there it's your job to find what created that entity and modify your source code.

**Comment by russellhoff** [comment]
Thanks for your help @TWiStErRob 

I've been able to use load() & into() methods to draw bitmaps into views.

Other methods try to draw canvas with a bitmap (canvas.drawBitmap) within a View class...

Thank you for your assistance :)

**Comment by russellhoff** [comment]
More memory leaks...

Target targetFore = Glide.with(context)
				.load(imagesFolder + mPages[0])
				.asBitmap()

				.into(new SimpleTarget<Bitmap>(width, height) {

					@Override
					public void onResourceReady(Bitmap resource, GlideAnimation glideAnimation) {
						Log.i(TAG, "Foreground ready!!!");
						mForeground = resource;
					}

					@Override
					public void onLoadFailed(Exception e, Drawable errorDrawable) {
						Log.e(TAG, "Error al cargar foreground: " + e.getMessage());
						mForeground = null;
					}

				});

06-04 14:24:01.756  18385-18385/com.ingartek.android.ipuin E/Zygote﹕ MountEmulatedStorage()
06-04 14:24:01.756  18385-18385/com.ingartek.android.ipuin E/Zygote﹕ v2
06-04 14:24:01.806  18385-18385/com.ingartek.android.ipuin E/SELinux﹕ [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
06-04 14:24:01.856  18385-18392/com.ingartek.android.ipuin E/art﹕ Failed writing handshake bytes (-1 of 14): Broken pipe
06-04 14:24:10.736  18385-18385/com.ingartek.android.ipuin E/MediaPlayer-JNI﹕ QCMediaPlayer mediaplayer NOT present
06-04 14:24:10.746  18385-18385/com.ingartek.android.ipuin E/MediaPlayer-JNI﹕ QCMediaPlayer mediaplayer NOT present
06-04 14:24:10.806  18385-18385/com.ingartek.android.ipuin E/MediaPlayer﹕ Should have subtitle controller already set
06-04 14:24:10.996  18385-19008/com.ingartek.android.ipuin E/art﹕ Throwing OutOfMemoryError "Failed to allocate a 6127628 byte allocation with 2507450 free bytes and 2MB until OOM"
06-04 14:24:11.006  18385-19008/com.ingartek.android.ipuin E/PriorityExecutor﹕ Request threw uncaught throwable
    java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Failed to allocate a 6127628 byte allocation with 2507450 free bytes and 2MB until OOM
            at java.util.concurrent.FutureTask.report(FutureTask.java:93)
            at java.util.concurrent.FutureTask.get(FutureTask.java:163)
            at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1120)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
            at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 6127628 byte allocation with 2507450 free bytes and 2MB until OOM
            at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
            at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
            at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:771)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:747)
            at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:329)
            at com.bumptech.glide.load.resource.bitmap.Downsampler.downsampleWithSize(Downsampler.java:220)
            at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:153)
            at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:50)
            at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
            at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:39)
            at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)
            at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:190)
            at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
            at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
            at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
            at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
            at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
            at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)

**Comment by russellhoff** [comment]
Adding android:largeHeap="true" to my android manifest within the application tag solved the OutOfMemoryException :)

Thanks!

**Comment by eicm** [comment]
I think if you have a memory leak, requesting larger heap shouldn’t be
considered as the solution. While based on resource usages your app may
need to request for a larger heap but no matter how much memory you have
you can still get out of memory if you don't deal with the memory leak and
dont manage your memory efficiently.
