### ISSUE TITLE
[ANR] com.bumptech.glide.manager.DefaultConnectivityMonitor.isConnected

### ISSUE THREAD

**Issue by raghav2945** [bumptech/glide#4859]
We [Audiomack](https://audiomack.com/) are severely impacted by Glide, one of the most common ANR by the use of this library. However, we are not direct users your SDK. Looking through the app's transitive dependencies, we discovered that Glide is used via Firebase In App Messaging.
And with the support of this transitive dependecy chart, we can see firebase inappmessaging used glide version -  4.11.0
```
+--- com.google.firebase:firebase-inappmessaging-display:20.1.2
|    +--- androidx.appcompat:appcompat:1.1.0 -> 1.4.2 (*)
|    +--- androidx.browser:browser:1.0.0 -> 1.3.0
|    |    +--- androidx.core:core:1.1.0 -> 1.8.0 (*)
|    |    +--- androidx.annotation:annotation:1.1.0 -> 1.3.0
|    |    \--- com.google.guava:listenablefuture:1.0 -> 9999.0-empty-to-avoid-conflict-with-guava
|    +--- androidx.cardview:cardview:1.0.0 (*)
|    +--- androidx.constraintlayout:constraintlayout:1.1.3 -> 2.1.4
|    +--- androidx.legacy:legacy-support-v4:1.0.0
|    |    +--- androidx.core:core:1.0.0 -> 1.8.0 (*)
|    |    +--- androidx.media:media:1.0.0 -> 1.6.0 (*)
|    |    +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    |    +--- androidx.legacy:legacy-support-core-ui:1.0.0
|    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.3.0
|    |    |    +--- androidx.core:core:1.0.0 -> 1.8.0 (*)
|    |    |    +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    |    |    +--- androidx.customview:customview:1.0.0 -> 1.1.0 (*)
|    |    |    +--- androidx.viewpager:viewpager:1.0.0 (*)
|    |    |    +--- androidx.coordinatorlayout:coordinatorlayout:1.0.0 -> 1.1.0 (*)
|    |    |    +--- androidx.drawerlayout:drawerlayout:1.0.0 -> 1.1.1 (*)
|    |    |    +--- androidx.slidingpanelayout:slidingpanelayout:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.3.0
|    |    |    |    +--- androidx.core:core:1.0.0 -> 1.8.0 (*)
|    |    |    |    \--- androidx.customview:customview:1.0.0 -> 1.1.0 (*)
|    |    |    +--- androidx.interpolator:interpolator:1.0.0 (*)
|    |    |    +--- androidx.swiperefreshlayout:swiperefreshlayout:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.3.0
|    |    |    |    +--- androidx.core:core:1.0.0 -> 1.8.0 (*)
|    |    |    |    \--- androidx.interpolator:interpolator:1.0.0 (*)
|    |    |    +--- androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.3.0
|    |    |    |    \--- androidx.core:core:1.0.0 -> 1.8.0 (*)
|    |    |    \--- androidx.cursoradapter:cursoradapter:1.0.0 (*)
|    |    \--- androidx.fragment:fragment:1.0.0 -> 1.5.0 (*)
|    +--- com.github.bumptech.glide:glide:4.11.0
|    |    +--- com.github.bumptech.glide:gifdecoder:4.11.0
|    |    |    \--- androidx.annotation:annotation:1.0.0 -> 1.3.0
|    |    +--- com.github.bumptech.glide:disklrucache:4.11.0
|    |    +--- com.github.bumptech.glide:annotations:4.11.0
|    |    +--- androidx.fragment:fragment:1.0.0 -> 1.5.0 (*)
|    |    +--- androidx.vectordrawable:vectordrawable-animated:1.0.0 -> 1.1.0 (*)
|    |    \--- androidx.exifinterface:exifinterface:1.0.0
|    |         \--- androidx.annotation:annotation:1.0.0 -> 1.3.0

```

**Glide Version**: 4.11.0

**Integration libraries**: com.google.firebase:firebase-inappmessaging-display:20.1.2

**Device/Android Version**: Android - 11, 12 & Device - Samsung

**Stack trace / LogCat**:
```ruby
main (native): tid=1 systid=7020 
#00 pc 0xa0078 libc.so 
#01 pc 0x6c2f3 libc.so 
#02 pc 0x3a2c7 libbinder.so 
#03 pc 0x3b215 libbinder.so 
#04 pc 0x3afdb libbinder.so 
#05 pc 0x356bf libbinder.so 
#06 pc 0xce517 libandroid_runtime.so 
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:605)
       at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:3031)
       at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:1162)
       at com.bumptech.glide.manager.DefaultConnectivityMonitor.isConnected(DefaultConnectivityMonitor.java:90)
       at com.bumptech.glide.manager.DefaultConnectivityMonitor.register(DefaultConnectivityMonitor.java:57)
       at com.bumptech.glide.manager.DefaultConnectivityMonitor.onStart(DefaultConnectivityMonitor.java:106)
       at com.bumptech.glide.manager.ApplicationLifecycle.addListener(ApplicationLifecycle.java:15)
       at com.bumptech.glide.RequestManager.<init>(RequestManager.java:144)
       at com.bumptech.glide.RequestManager.<init>(RequestManager.java:106)
       at com.bumptech.glide.manager.RequestManagerRetriever$1.build(RequestManagerRetriever.java:490)
       at com.bumptech.glide.manager.RequestManagerRetriever.getApplicationManager(RequestManagerRetriever.java:90)
       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:120)
       at com.bumptech.glide.Glide.with(Glide.java:776)
       at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule.providesGlideRequestManager(GlideModule.java:32)
       at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule_ProvidesGlideRequestManagerFactory.providesGlideRequestManager(GlideModule_ProvidesGlideRequestManagerFactory.java:43)
       at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule_ProvidesGlideRequestManagerFactory.get(GlideModule_ProvidesGlideRequestManagerFactory.java:32)
       at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule_ProvidesGlideRequestManagerFactory.get(GlideModule_ProvidesGlideRequestManagerFactory.java:11)
       at com.google.firebase.inappmessaging.display.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.google.firebase.inappmessaging.display.internal.FiamImageLoader_Factory.get(FiamImageLoader_Factory.java:21)
       at com.google.firebase.inappmessaging.display.internal.FiamImageLoader_Factory.get(FiamImageLoader_Factory.java:8)
       at com.google.firebase.inappmessaging.display.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay_Factory.get(FirebaseInAppMessagingDisplay_Factory.java:61)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay_Factory.get(FirebaseInAppMessagingDisplay_Factory.java:16)
       at com.google.firebase.inappmessaging.display.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.google.firebase.inappmessaging.display.internal.injection.components.DaggerAppComponent.providesFirebaseInAppMessagingUI(DaggerAppComponent.java:80)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplayRegistrar.buildFirebaseInAppMessagingUI(FirebaseInAppMessagingDisplayRegistrar.java:72)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplayRegistrar.$r8$lambda$mFT7XCE3YJXhnGdhKohfXnpd5DM(FirebaseInAppMessagingDisplayRegistrar.java)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplayRegistrar$$InternalSyntheticLambda$0$9f5211887ae522004e3755181f8e372b30d8700f5a7cd13dd30a3f769b4f1a32$0.create(FirebaseInAppMessagingDisplayRegistrar.java)
       at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
       at com.google.firebase.components.ComponentRuntime.$r8$lambda$4FqOW9eOQsvFYo-HpMfxCOnPQr0(ComponentRuntime.java)
       at com.google.firebase.components.ComponentRuntime$$InternalSyntheticLambda$1$562ccfbab29457946f69b904d7c620216b88cbd0fd784cee32e00ed2dcd3a60c$0.get(ComponentRuntime.java)
       at com.google.firebase.components.Lazy.get(Lazy.java:53)
       at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:291)
       at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281)
       at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:594)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:305)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:269)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:254)
       at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2429)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2399)
       at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
       at android.app.ActivityThread.installProvider(ActivityThread.java:8190)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7726)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7546)
       at android.app.ActivityThread.access$1400(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by sjudd** [comment]
A stuck binder is usually a framework or device issue. We could call this API on a background thread (96596ae9269e85f31d5c6a158c2ab92c16677703 does so for < SDK 24), but it may not make much practical impact on ANRs if it just moves on to the next binder call

**Comment by raghav2945** [comment]
Agreed. The framework layer is where the transact call is made. However, I believe the async technique should help us here. Obviously, we can't eliminate every transact call with just one modification, but it is an excellent place to start if we want to rework and deal with all such well-known issues.

We probably have this problem because we're still using an outdated version of Glide -  4.11.0. Presumably the version without the abovementioned changes. I can confirm this through the captured stack shared above. So I think we might address this problem by upgrading Glide to latest or atleast to the version which has the abovementioned changes. Thanks for sharing the change list details.
