### ISSUE TITLE
Failed to find generatedGlide module

### ISSUE THREAD

**Issue by ShroukMamdouh** [bumptech/glide#4885]
Dear I followed the video https://youtu.be/zTygdC-QCz8 but when i added the below in gradle
plugins {
id 'com.android.application'
id 'org.jetbrains.kotlin.android'
id 'kotlin.kapt'
}
dependencies {
def glide_version ="4.13.0"
implementation 'com.github.bumptech.glide:glide:$glide_version'
kapt 'com.github.bumptech.glide:compiler:$glide_version'
}

i got the below error

Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'kotlin.kapt'] was not found in any of the following sources:
Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
Plugin Repositories (plugin dependency must include a version number for this source)
at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:222)
at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.lambda$resolvePluginRequests$4(DefaultPluginRequestApplicator.java:148)
at org.gradle.util.internal.CollectionUtils.collect(CollectionUtils.java:207)
at org.gradle.util.internal.CollectionUtils.collect(CollectionUtils.java:201)
at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolvePluginRequests(DefaultPluginRequestApplicator.java:146)
at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:86)
at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:117)
at

**Comment by sjudd** [comment]
The best documentation I have for how to set Glide up is here: https://bumptech.github.io/glide/doc/download-setup.html#kotlin---kapt. It looks like your build system is failing to find the kapt plugin though, so I'd probably look at the kapt documentation instead (it's linked from my link :))
