### ISSUE TITLE
Behavior of Mocked RequestManager was changed after migration from GlideRequests

### ISSUE THREAD

**Issue by ganadist** [bumptech/glide#4920]
**Glide Version**: 4.13.2 / 4.14.1

**Integration libraries**: N/A

**Device/Android Version**: N/A

**Issue details / Repro steps / Use case background**: 
After [Generated API Deprecation](https://bumptech.github.io/glide/doc/generatedapi.html#this-page-and-the-generated-api-are-deprecated), I tried to modify to use vanilla glide APIs instead of generated classes.

But I found behavior of `Mocked` RequestManager was changed after migration.

```
git clone https://github.com/ganadist/VersionCodeDemo -b glide_mock
cd VersionCodeDemo

# mock with RequestManager

./gradlew :lib:glide:check
com.example.mylib.GlideRequestFactoryTest > testFactory FAILED
    java.lang.ClassCastException at GlideRequestFactoryTest.kt:30

class com.bumptech.glide.request.BaseRequestOptions$MockitoMock$1707268325 cannot be cast to class com.bumptech.glide.RequestBuilder (com.bumptech.glide.request.BaseRequestOptions$MockitoMock$1707268325 and com.bumptech.glide.RequestBuilder are in unnamed module of loader org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader @2e1ef60)
java.lang.ClassCastException: class com.bumptech.glide.request.BaseRequestOptions$MockitoMock$1707268325 cannot be cast to class com.bumptech.glide.RequestBuilder (com.bumptech.glide.request.BaseRequestOptions$MockitoMock$1707268325 and com.bumptech.glide.RequestBuilder are in unnamed module of loader org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader @2e1ef60)
	at com.bumptech.glide.RequestBuilder$MockitoMock$1063850520.diskCacheStrategy(Unknown Source)
	at com.bumptech.glide.RequestBuilder$MockitoMock$1063850520.diskCacheStrategy(Unknown Source)
	at com.example.mylib.GlideRequestFactory.createRequest(GlideRequestFactory.kt:11)
	at com.example.mylib.GlideRequestFactoryTest.testFactory(GlideRequestFactoryTest.kt:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829


git checkout HEAD~1

# mock with GlideRequests

./gradlew :lib:glide:check

com.example.mylib.GlideRequestFactoryTest > testFactory PASSED

```

Sample project is using mockito(and mockito-kotlin) but same behavior expected with mockk.

It is unclear whether this is an issue with Glide, but it is expected that many developers will encounter the same error when migrating.

Can anyone share opinions and best practices when migrating?

**Comment by sjudd** [comment]
I think `RETURNS_DEEP_STUBS` is the issue here. It probably is misinterpreting the return value of RequestBuilder to be BaseRequestOptions instead of RequestBuilder.

Glide has its own mocks helper here: https://github.com/bumptech/glide/blob/95c8f811a1a25a9dd893f456dafe2de9deb0f029/mocks/src/main/java/com/bumptech/glide/mocks/MockGlideBuilders.java#L15

Do those work for you?
