### ISSUE TITLE
[Compose] Crash when height or width of GlideImage is <= 0

### ISSUE THREAD

**Issue by arriolac** [bumptech/glide#4952]
**Glide Version**: 1.0.0-alpha.1

compose

emulator / pixel 5 API 32

I noticed this crash while trying out the [sunflower](https://github.com/android/sunflower) sample app which recently switched over to use Glide from Coil. Sunflower implements a collapasing toolbar wherein the image's size changes are you scroll through UI. The image's height eventually goes to <= 0 due to the collapsing toolbar logic. 

Notice the `imageHeight` argument that is provided into the composable `PlantImage`. This is called further up the stack where the collapsable toolbar logic exists.

```
@OptIn(ExperimentalGlideComposeApi::class)
@Composable
private fun PlantImage(
    imageUrl: String,
    imageHeight: Dp,
    modifier: Modifier = Modifier,
    placeholderColor: Color = MaterialTheme.colors.onSurface.copy(0.2f)
) {
    var isLoading by remember { mutableStateOf(true) }
    Box(
        modifier
            .fillMaxWidth()
            .height(imageHeight)) {
        if (isLoading) {
            // TODO: Update this implementation once Glide releases a version
            // that contains this feature: https://github.com/bumptech/glide/pull/4934
            Box(
                Modifier
                    .fillMaxSize()
                    .background(placeholderColor)
            )
        }
        GlideImage(
            model = imageUrl,
            contentDescription = null,
            modifier = Modifier
                .fillMaxSize(),
            contentScale = ContentScale.Crop,
        ) {
            it.addListener(object : RequestListener<Drawable> {
                override fun onLoadFailed(
                    e: GlideException?,
                    model: Any?,
                    target: Target<Drawable>?,
                    isFirstResource: Boolean
                ): Boolean {
                    isLoading = false
                    return false
                }

                override fun onResourceReady(
                    resource: Drawable?,
                    model: Any?,
                    target: Target<Drawable>?,
                    dataSource: DataSource?,
                    isFirstResource: Boolean
                ): Boolean {
                    isLoading = false
                    return false
                }
            })
        }
    }
}
```

```
2022-11-14 11:19:23.615 23484-23484 AndroidRuntime          com.google.samples.apps.sunflower    E  FATAL EXCEPTION: main
                                                                                                    Process: com.google.samples.apps.sunflower, PID: 23484
                                                                                                    java.lang.IllegalArgumentException: Failed requirement.
                                                                                                    	at com.bumptech.glide.integration.ktx.Size.<init>(Flows.kt:381)
                                                                                                    	at com.bumptech.glide.integration.compose.SizesKt.inferredGlideSize-BRTryo0(Sizes.kt:36)
                                                                                                    	at com.bumptech.glide.integration.compose.GlideImageKt$sizeObservingModifier$1.invoke-3p2s80s(GlideImage.kt:195)
                                                                                                    	at com.bumptech.glide.integration.compose.GlideImageKt$sizeObservingModifier$1.invoke(GlideImage.kt:194)
                                                                                                    	at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(LayoutModifier.kt:285)
                                                                                                    	at androidx.compose.ui.node.BackwardsCompatNode.measure-3p2s80s(BackwardsCompatNode.kt:343)
                                                                                                    	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:155)
                                                                                                    	at androidx.compose.foundation.layout.FillModifier.measure-3p2s80s(Size.kt:658)
                                                                                                    	at androidx.compose.ui.node.BackwardsCompatNode.measure-3p2s80s(BackwardsCompatNode.kt:343)
                                                                                                    	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:155)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1077)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1073)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2139)
```

See [sunflower](https://github.com/android/sunflower). You can repro this bug by clicking a plant, and in the plan detail screen scroll down the list.

**Comment by lekstel** [comment]
@sjudd Hi Sam! When could we expect to get a new release with this fix?

**Comment by sjudd** [comment]
Hopefully early next year. Especially for the compose integration which is in very early stages anyway, consider using snapshots to get faster updates: https://bumptech.github.io/glide/dev/snapshots.html

**Comment by ticmaidev** [comment]
OK, I can't use this fix right now, so I've made this composable that'll work as expected. It surely can be improved:

- it uses `com.github.bumptech.glide:glide:4.15.1`

I've got very large grids in my app and I think it's scrolling smoother.

``` kotlin
@Composable
fun GlideImage(
    model: Any?,
    contentDescription: String?,
    modifier: Modifier = Modifier,
    alignment: Alignment = Alignment.Center,
    contentScale: ContentScale = ContentScale.FillBounds,
    alpha: Float = DefaultAlpha,
    colorFilter: ColorFilter? = null,
    placeholder: Painter,
) {
    val context = LocalContext.current
    var imageResource by remember {
        mutableStateOf<Any?>(
            null
        )
    }

    // Load the image using Glide
    LaunchedEffect(model) {
        Glide.with(context)
            .load(model)
            .diskCacheStrategy(DiskCacheStrategy.ALL)
            .into(object : CustomTarget<Drawable>() {
                override fun onResourceReady(resource: Drawable, transition: Transition<in Drawable>?) {
                    imageResource = resource.toBitmap().asImageBitmap()
                }

                override fun onLoadCleared(placeholder: Drawable?) {
                    // Do nothing
                }
            })
    }

    // A Box to position the Image and show a placeholder while loading
    Box(
        modifier = modifier.fillMaxSize(),
        contentAlignment = alignment
    ) {
        if (imageResource is ImageBitmap) {
            Image(
                bitmap = imageResource as ImageBitmap,
                contentDescription = contentDescription,
                contentScale = contentScale,
                alpha = alpha,
                colorFilter = colorFilter,
                modifier = modifier.fillMaxSize(),
            )
        } else {
            // A placeholder drawable while the image is loading
            Image(
                painter = placeholder,
                contentDescription = contentDescription,
                contentScale = contentScale,
                alpha = alpha,
                colorFilter = colorFilter,
                modifier = modifier.fillMaxSize(),
            )
        }
    }
}
```
