### ISSUE TITLE
IllegalStateException in getSupportRequestManagerFragment

### ISSUE THREAD

**Issue by Tolriq** [bumptech/glide#497]
Since I've migrated more Glide calls to use fragment instead of application context I now receive a new crash report :

```
java.lang.RuntimeException: Unable to destroy activity xxx.ui.MediasListActivity}: java.lang.IllegalStateException: Activity has been destroyed
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4199)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4217)
       at android.app.ActivityThread.access$1500(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1502)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
Caused by: java.lang.IllegalStateException: Activity has been destroyed
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1399)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:637)
       at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:620)
       at com.bumptech.glide.manager.RequestManagerRetriever.getSupportRequestManagerFragment(RequestManagerRetriever.java:187)
       at com.bumptech.glide.manager.SupportRequestManagerFragment.onAttach(SupportRequestManagerFragment.java:116)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:907)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
       at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1965)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
       at android.support.v4.app.FragmentManagerImpl.moveToState$2563266(FragmentManager.java:1120)
       at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1966)
       at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:316)
       at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:158)
       at xxxx.ui.BaseActivity.onDestroy(BaseActivity.java:224)
       at android.app.Activity.performDestroy(Activity.java:6519)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4177)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4217)
       at android.app.ActivityThread.access$1500(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1502)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)

```

**Comment by TWiStErRob** [comment]
How do you use Glide in that activity? When (life cycle) is Glide called? What kind of fragments do you have there? How do they use Glide?

Is there a finish() maybe right after (in the same handleMessage loop) a Glide call? Or is it happening on rotation (start the first Glide load and then rotate immediately)?

**Comment by eicm** [comment]
Just a guess: If you have any Glide calls in a inner class handler make sure it has weak reference to your activity.

**Comment by sjudd** [comment]
It does look like onAttach in our Fragment is being called after the Activity is destroyed. We can guard against that on some API levels, but not all. 

If you can tell us more about your use case, maybe there's an issue in the framework, or something else we can do to work around it.

**Comment by Tolriq** [comment]
I target API 14+, I have crash on 5.0 and different 4.x.x

This is a simple 1 activity 1 fragment

In activity onCreate()
```
if (savedInstanceState == null) {
            FragmentManager fragmentManager = getSupportFragmentManager();
            FragmentTransaction fragmentTransaction = fragmentManager.beginTransaction();
            fragmentTransaction.add(R.id.fragment_container, fragment);
            fragmentTransaction.commit();
{
```

So far only 10 crash so not major problem, but still one of the top crash.

**Comment by TWiStErRob** [comment]
Where are you Glide interactions in those Activity/Fragment?
