### ISSUE TITLE
java.lang.IllegalArgumentException: SVG document is empty

### ISSUE THREAD

**Issue by mackwu828** [bumptech/glide#5078]
glide version: 
```
api 'com.github.bumptech.glide:glide:4.12.0'
```

Loading a jpg image, but reporting an svg exception. Any idea why?

```
03-09 18:26:15.223 W/Glide   (  798): Load failed for /storage/emulated/0/xxx/resource/10.1M-VID_20220427_160615.jpg with size [45x45]
03-09 18:26:15.223 W/Glide   (  798): class com.bumptech.glide.load.engine.GlideException: Failed to load resource
03-09 18:26:15.223 W/Glide   (  798): There were 4 root causes:
03-09 18:26:15.223 W/Glide   (  798): java.lang.IllegalArgumentException(SVG document is empty)
03-09 18:26:15.223 W/Glide   (  798): java.lang.RuntimeException(setDataSource failed: status = 0xFFFFFFEA)
03-09 18:26:15.223 W/Glide   (  798): java.lang.RuntimeException(setDataSource failed: status = 0xFFFFFFEA)
03-09 18:26:15.223 W/Glide   (  798): java.lang.RuntimeException(setDataSource failed: status = 0xFFFFFFEA)
03-09 18:26:15.223 W/Glide   (  798):  call GlideException#logRootCauses(String) for more detail
03-09 18:26:15.223 W/Glide   (  798):   Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, LOCAL
03-09 18:26:15.223 W/Glide   (  798): There was 1 root cause:
03-09 18:26:15.223 W/Glide   (  798): java.lang.IllegalArgumentException(SVG document is empty)
03-09 18:26:15.223 W/Glide   (  798):  call GlideException#logRootCauses(String) for more detail
03-09 18:26:15.223 W/Glide   (  798):     Cause (1 of 4): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
03-09 18:26:15.223 W/Glide   (  798):     Cause (2 of 4): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
03-09 18:26:15.223 W/Glide   (  798):     Cause (3 of 4): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
03-09 18:26:15.223 W/Glide   (  798):     Cause (4 of 4): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->SVG->Drawable}
03-09 18:26:15.223 W/Glide   (  798): There was 1 root cause:
03-09 18:26:15.223 W/Glide   (  798): java.lang.IllegalArgumentException(SVG document is empty)
03-09 18:26:15.223 W/Glide   (  798):  call GlideException#logRootCauses(String) for more detail
03-09 18:26:15.223 W/Glide   (  798):       Cause (1 of 1): class java.lang.IllegalArgumentException: SVG document is empty
03-09 18:26:15.223 W/Glide   (  798):   Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, LOCAL
03-09 18:26:15.223 W/Glide   (  798): There were 2 root causes:
03-09 18:26:15.223 W/Glide   (  798): java.lang.RuntimeException(setDataSource failed: status = 0xFFFFFFEA)
03-09 18:26:15.223 W/Glide   (  798): java.lang.RuntimeException(setDataSource failed: status = 0xFFFFFFEA)
03-09 18:26:15.223 W/Glide   (  798):  call GlideException#logRootCauses(String) for more detail
03-09 18:26:15.223 W/Glide   (  798):     Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
03-09 18:26:15.223 W/Glide   (  798): There was 1 root cause:
03-09 18:26:15.223 W/Glide   (  798): java.lang.RuntimeException(setDataSource failed: status = 0xFFFFFFEA)
03-09 18:26:15.223 W/Glide   (  798):  call GlideException#logRootCauses(String) for more detail
03-09 18:26:15.223 W/Glide   (  798):       Cause (1 of 1): class java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
03-09 18:26:15.223 W/Glide   (  798):     Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
03-09 18:26:15.223 W/Glide   (  798): There was 1 root cause:
03-09 18:26:15.223 W/Glide   (  798): java.lang.RuntimeException(setDataSource failed: status = 0xFFFFFFEA)
03-09 18:26:15.223 W/Glide   (  798):  call GlideException#logRootCauses(String) for more detail
03-09 18:26:15.223 W/Glide   (  798):       Cause (1 of 1): class java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
03-09 18:26:15.223 W/Glide   (  798):   Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{AssetFileDescriptor->Object->Drawable}, LOCAL
03-09 18:26:15.223 W/Glide   (  798): There was 1 root cause:
03-09 18:26:15.223 W/Glide   (  798): java.lang.RuntimeException(setDataSource failed: status = 0xFFFFFFEA)
03-09 18:26:15.223 W/Glide   (  798):  call GlideException#logRootCauses(String) for more detail
03-09 18:26:15.223 W/Glide   (  798):     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AssetFileDescriptor->Bitmap->Drawable}
03-09 18:26:15.223 W/Glide   (  798): There was 1 root cause:
03-09 18:26:15.223 W/Glide   (  798): java.lang.RuntimeException(setDataSource failed: status = 0xFFFFFFEA)
03-09 18:26:15.223 W/Glide   (  798):  call GlideException#logRootCauses(String) for more detail
03-09 18:26:15.223 W/Glide   (  798):       Cause (1 of 1): class java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
03-09 18:26:15.224 I/Glide   (  798): Root cause (1 of 4)
03-09 18:26:15.224 I/Glide   (  798): java.lang.IllegalArgumentException: SVG document is empty
03-09 18:26:15.224 I/Glide   (  798): 	at com.caverock.androidsvg.SVG.setDocumentWidth(SVG.java:717)
03-09 18:26:15.224 I/Glide   (  798): 	at com.zeasn.speakerdemo.util.SvgDecoder.decode(SvgDecoder.java:32)
03-09 18:26:15.224 I/Glide   (  798): 	at com.zeasn.speakerdemo.util.SvgDecoder.decode(SvgDecoder.java:18)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:92)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:59)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:529)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:493)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:479)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:430)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:394)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal(SourceGenerator.java:148)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady(SourceGenerator.java:76)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:145)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:45)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
03-09 18:26:15.224 I/Glide   (  798): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
03-09 18:26:15.224 I/Glide   (  798): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
03-09 18:26:15.224 I/Glide   (  798): 	at java.lang.Thread.run(Thread.java:764)
03-09 18:26:15.224 I/Glide   (  798): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
03-09 18:26:15.225 I/Glide   (  798): Root cause (2 of 4)
03-09 18:26:15.225 I/Glide   (  798): java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
03-09 18:26:15.225 I/Glide   (  798): 	at android.media.MediaMetadataRetriever.setDataSource(Native Method)
03-09 18:26:15.225 I/Glide   (  798): 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:139)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder$ParcelFileDescriptorInitializer.initialize(VideoDecoder.java:314)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder$ParcelFileDescriptorInitializer.initialize(VideoDecoder.java:309)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder.decode(VideoDecoder.java:173)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:92)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:59)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:529)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:493)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:479)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:430)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:394)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal(SourceGenerator.java:148)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady(SourceGenerator.java:76)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:145)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:45)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:438)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:394)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal(SourceGenerator.java:148)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady(SourceGenerator.java:76)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:145)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:45)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
03-09 18:26:15.225 I/Glide   (  798): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
03-09 18:26:15.225 I/Glide   (  798): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
03-09 18:26:15.225 I/Glide   (  798): 	at java.lang.Thread.run(Thread.java:764)
03-09 18:26:15.225 I/Glide   (  798): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
03-09 18:26:15.227 I/Glide   (  798): Root cause (3 of 4)
03-09 18:26:15.227 I/Glide   (  798): java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
03-09 18:26:15.227 I/Glide   (  798): 	at android.media.MediaMetadataRetriever.setDataSource(Native Method)
03-09 18:26:15.227 I/Glide   (  798): 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:139)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder$ParcelFileDescriptorInitializer.initialize(VideoDecoder.java:314)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder$ParcelFileDescriptorInitializer.initialize(VideoDecoder.java:309)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder.decode(VideoDecoder.java:173)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.resource.bitmap.BitmapDrawableDecoder.decode(BitmapDrawableDecoder.java:58)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:92)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:59)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:529)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:493)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:479)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:430)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:394)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal(SourceGenerator.java:148)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady(SourceGenerator.java:76)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:145)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:45)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:438)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:394)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal(SourceGenerator.java:148)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady(SourceGenerator.java:76)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:145)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:45)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
03-09 18:26:15.227 I/Glide   (  798): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
03-09 18:26:15.227 I/Glide   (  798): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
03-09 18:26:15.227 I/Glide   (  798): 	at java.lang.Thread.run(Thread.java:764)
03-09 18:26:15.227 I/Glide   (  798): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
03-09 18:26:15.228 I/Glide   (  798): Root cause (4 of 4)
03-09 18:26:15.228 I/Glide   (  798): java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
03-09 18:26:15.228 I/Glide   (  798): 	at android.media.MediaMetadataRetriever.setDataSource(Native Method)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder$AssetFileDescriptorInitializer.initialize(VideoDecoder.java:304)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder$AssetFileDescriptorInitializer.initialize(VideoDecoder.java:299)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.resource.bitmap.VideoDecoder.decode(VideoDecoder.java:173)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:92)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:59)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:529)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:493)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:479)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:430)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:394)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal(SourceGenerator.java:148)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady(SourceGenerator.java:76)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:45)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:438)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:394)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal(SourceGenerator.java:148)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady(SourceGenerator.java:76)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:145)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:45)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:438)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:394)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal(SourceGenerator.java:148)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady(SourceGenerator.java:76)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:145)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:45)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
03-09 18:26:15.228 I/Glide   (  798): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
03-09 18:26:15.228 I/Glide   (  798): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
03-09 18:26:15.228 I/Glide   (  798): 	at java.lang.Thread.run(Thread.java:764)
03-09 18:26:15.228 I/Glide   (  798): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
```

**Comment by moderGamer** [comment]
```java
public static void GetFileSvg(String input, ImageView img, Context activity, TextView tv1) {
		try {
			File startDir = new File(input);
			FileInputStream fileInputStream = new FileInputStream(startDir);
			SVG svg = SVG.getFromInputStream(fileInputStream);
			final Drawable drawable = new PictureDrawable(svg.renderToPicture());
			Glide.with(activity)
			.load(drawable)
			.transition(com.bumptech.glide.load.resource.drawable.DrawableTransitionOptions.withCrossFade((int)600))
			//	.circleCrop()
			.error(R.drawable.close)
			.diskCacheStrategy(com.bumptech.glide.load.engine.DiskCacheStrategy.ALL)
			.priority(Priority.HIGH)
			.into(img);
			infoLog("load");
			if (svg.getDocumentWidth() != 1) {
				
				tv1.setText(String.valueOf((long) Math.ceil(svg.getDocumentWidth())).concat(" x ")
				.concat(String.valueOf((long) Math.ceil(svg.getDocumentHeight()))));
			}
			
		} catch (IOException | SVGParseException d) {
			d.printStackTrace();
			
		}
	}```
@mackwu828 try it bro
