### ISSUE TITLE
Occasional native crash on load glide cache start from android Q

### ISSUE THREAD

**Issue by wl0073921** [bumptech/glide#5129]
**crash info:** 
signal 7 (SIGBUS), code 2 (BUS_ADRERR), fault addr 0x7a0730a000 
path=/mnt/media_rw/9BC9-DB9E/Android/data/**/cache/glide_cache/**.0
fatal_addr=0000007a0730a000
map_addr=0000007a07309000-0000007a07320000
offset=0000000000000000

**native crash info**
    #00 pc 00000000005b3060  /apex/com.android.art/lib64/libart.so  
           art::Unsafe_getByteJ(_JNIEnv*, _jobject*, long) 
    #01 pc 00000000000c6414  /apex/com.android.art/javalib/arm64/boot.oat  
           art_jni_trampoline+100 
    #02 pc 00000000003250fc  /apex/com.android.art/javalib/arm64/boot.oat  
           java.nio.MappedByteBuffer.load+508

**java stack**
  at sun.misc.Unsafe.getByte(Unsafe.java) 
  at java.nio.MappedByteBuffer.load(MappedByteBuffer.java:179) 
  at com.bumptech.glide.util.ByteBufferUtil.fromFile(ByteBufferUtil.java:43)

**Comment by Fossor** [comment]
I am also getting this. Most likely happens when file is deleted
#00  pc 0x0000000000745428  /apex/com.android.art/lib64/libart.so (art::Unsafe_getByteJ(_JNIEnv*, _jobject*, long) (.__uniq.306581074569039686346581217366878976736))
  #01  pc 0x000000000034011c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+92)
  #02  pc 0x00000000004eb9e8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.nio.MappedByteBuffer.load+504)
  #03  pc 0x00000000001fedc4  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.util.ByteBufferUtil.fromFile+244)
  #04  pc 0x0000000000355674  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData+68)
  #05  pc 0x000000000034f484  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.SourceGenerator.startNext+1092)
  #06  pc 0x0000000000346470  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.DecodeJob.runGenerators+192)
  #07  pc 0x0000000000346b10  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.DecodeJob.runWrapped+368)
  #08  pc 0x0000000000347bf4  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.DecodeJob.run+212)
  #09  pc 0x000000000057f0fc  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+796)
  #10  pc 0x000000000057c220  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor$Worker.run+64)
  #11  pc 0x00000000001ea1f8  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run+312)
  #12  pc 0x00000000001e9f3c  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run+92)
  #13  pc 0x000000000033eda4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612)
  #14  pc 0x0000000000239d54  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+144)
  #15  pc 0x000000000053a1b0  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1600)
  #16  pc 0x00000000000c37f4  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208)
  #17  pc 0x000000000005d0c4  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)

**Comment by Fossor** [comment]
Here is another. I have more if you want

backtrace:
  #00  pc 0x00000000000543a0  /apex/com.android.runtime/lib64/bionic/libc.so (__memcpy_aarch64_simd+224)
  #01  pc 0x00000000006c0254  /apex/com.android.art/lib64/libart.so (art::JNI<false>::SetByteArrayRegion(_JNIEnv*, _jbyteArray*, int, int, signed char const*)+352)
  #02  pc 0x00000000003470e4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+116)
  #03  pc 0x000000000055a97c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.nio.DirectByteBuffer.get+236)
  #04  pc 0x00000000001febf4  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.util.ByteBufferUtil$ByteBufferStream.read+148)
  #05  pc 0x000000000033eda4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612)
  #06  pc 0x000000000033cd64  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+772)
  #07  pc 0x000000000055e47c  /apex/com.android.art/lib64/libart.so (art::JNI<false>::CallIntMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+192)
  #08  pc 0x00000000004bd5cc  /system/lib64/libhwui.so (_JNIEnv::CallIntMethod(_jobject*, _jmethodID*, ...)+124)
  #09  pc 0x00000000004bd374  /system/lib64/libhwui.so (JavaInputStreamAdaptor::doRead(void*, unsigned long, _JNIEnv*)+80)
  #10  pc 0x000000000055f158  /system/lib64/libhwui.so ((anonymous namespace)::FrontBufferedStream::read(void*, unsigned long) (.__uniq.259476571162685252206752541612201816602)+296)
  #11  pc 0x000000000057b5d8  /system/lib64/libhwui.so (SkPngCodec::processData()+404)
  #12  pc 0x000000000057c3ec  /system/lib64/libhwui.so (SkPngNormalDecoder::decodeAllRows(void*, unsigned long, int*)+100)
  #13  pc 0x000000000057114c  /system/lib64/libhwui.so (SkCodec::getPixels(SkImageInfo const&, void*, unsigned long, SkCodec::Options const*)+480)
  #14  pc 0x000000000057d1a8  /system/lib64/libhwui.so (SkSampledCodec::onGetAndroidPixels(SkImageInfo const&, void*, unsigned long, SkAndroidCodec::AndroidOptions const&)+528)
  #15  pc 0x000000000056c8a8  /system/lib64/libhwui.so (SkAndroidCodec::getAndroidPixels(SkImageInfo const&, void*, unsigned long, SkAndroidCodec::AndroidOptions const*)+424)
  #16  pc 0x00000000004b8980  /system/lib64/libhwui.so (doDecode(_JNIEnv*, std::__1::unique_ptr<SkStreamRewindable, std::__1::default_delete<SkStreamRewindable> >, _jobject*, _jobject*, long, long, bool) (.__uniq.26938061605105508016343812100800822394)+2944)
  #17  pc 0x00000000004b7710  /system/lib64/libhwui.so (nativeDecodeStream(_JNIEnv*, _jobject*, _jobject*, _jbyteArray*, _jobject*, _jobject*, long, long) (.__uniq.26938061605105508016343812100800822394)+164)
  #18  pc 0x000000000034d8f0  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+176)
  #19  pc 0x0000000000720a34  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.graphics.BitmapFactory.decodeStream+484)
  #20  pc 0x000000000035bdd8  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.resource.bitmap.ImageReader$ByteBufferReader.decodeBitmap+232)
  #21  pc 0x00000000001f02e8  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream+344)
  #22  pc 0x00000000001eff84  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams+2020)
  #23  pc 0x00000000001ef45c  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.resource.bitmap.Downsampler.decode+1116)
  #24  pc 0x0000000000359f68  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.resource.bitmap.ByteBufferBitmapDecoder.decode+232)
  #25  pc 0x0000000000359e50  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.resource.bitmap.ByteBufferBitmapDecoder.decode+80)
  #26  pc 0x00000000003597d8  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.resource.bitmap.BitmapDrawableDecoder.decode+88)
  #27  pc 0x00000000001e4c00  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList+448)
  #28  pc 0x00000000001e4908  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.DecodePath.decodeResource+232)
  #29  pc 0x00000000001e4eb8  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.DecodePath.decode+56)
  #30  pc 0x00000000001e6964  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList+292)
  #31  pc 0x00000000001e6bc4  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.LoadPath.load+244)
  #32  pc 0x0000000000346904  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.DecodeJob.runLoadPath+260)
  #33  pc 0x0000000000344c7c  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.DecodeJob.decodeFromData+348)
  #34  pc 0x00000000003450dc  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData+492)
  #35  pc 0x00000000003471c0  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady+400)
  #36  pc 0x000000000034f010  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.SourceGenerator.onDataReadyInternal+368)
  #37  pc 0x000000000034eca8  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.SourceGenerator$1.onDataReady+136)
  #38  pc 0x000000000035569c  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData+108)
  #39  pc 0x000000000034f484  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.SourceGenerator.startNext+1092)
  #40  pc 0x0000000000346470  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.DecodeJob.runGenerators+192)
  #41  pc 0x0000000000346b10  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.DecodeJob.runWrapped+368)
  #42  pc 0x0000000000347bf4  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.DecodeJob.run+212)
  #43  pc 0x000000000057f0fc  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+796)
  #44  pc 0x000000000057c220  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor$Worker.run+64)
  #45  pc 0x00000000001ea1f8  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run+312)
  #46  pc 0x00000000001e9f3c  /data/app/~~dbyBWBNkebmdA7GHLaiDfA==/com.fossor.panels-4EYpCu4AJkUPLrvOkTXbaA==/oat/arm64/base.odex (com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run+92)
  #47  pc 0x000000000033eda4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612)
  #48  pc 0x0000000000239d54  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+144)
  #49  pc 0x000000000053a1b0  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1600)
  #50  pc 0x00000000000c37f4  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208)
  #51  pc 0x000000000005d0c4  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)

**Comment by MMsmileNN** [comment]
Hello, after upgrading the Gradle version to 8.3 and the JDK version to 17, and upgrading the Glide version to 4.16.0, this issue has been occurring on the live server. Even when we downgrade Glide to the previous version 4.12.0, the problem still persists. Could you please tell me how you resolved this issue?
