### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by sea5241** [bumptech/glide#5180]
I have a picture url ,when I use glide load this url, it don‘t show this picture, this is the log:
`java.lang.IndexOutOfBoundsException: index=-1330518587 out of bounds (limit=49935, nb=2)
                                                                                                    	at java.nio.Buffer.checkIndex(Buffer.java:564)
                                                                                                    	at java.nio.HeapByteBuffer.getShort(HeapByteBuffer.java:263)
                                                                                                    	at com.bumptech.glide.load.resource.bitmap.DefaultImageHeaderParser$RandomAccessReader.getInt16(DefaultImageHeaderParser.java:464)
                                                                                                    	at com.bumptech.glide.load.resource.bitmap.DefaultImageHeaderParser.parseExifSegment(DefaultImageHeaderParser.java:364)
                                                                                                    	at com.bumptech.glide.load.resource.bitmap.DefaultImageHeaderParser.parseExifSegment(DefaultImageHeaderParser.java:269)
                                                                                                    	at com.bumptech.glide.load.resource.bitmap.DefaultImageHeaderParser.getOrientation(DefaultImageHeaderParser.java:237)
                                                                                                    	at com.bumptech.glide.load.resource.bitmap.DefaultImageHeaderParser.getOrientation(DefaultImageHeaderParser.java:83)
                                                                                                    	at com.bumptech.glide.load.ImageHeaderParserUtils$5.getOrientation(ImageHeaderParserUtils.java:174)
                                                                                                    	at com.bumptech.glide.load.ImageHeaderParserUtils.getOrientationInternal(ImageHeaderParserUtils.java:222)
                                                                                                    	at com.bumptech.glide.load.ImageHeaderParserUtils.getOrientation(ImageHeaderParserUtils.java:168)
                                                                                                    	at com.bumptech.glide.load.resource.bitmap.ImageReader$InputStreamImageReader.getImageOrientation(ImageReader.java:204)
                                                                                                    	at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:330)
                                                                                                    	at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:285)
                                                                                                    	at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:222)
                                                                                                    	at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:62)
                                                                                                    	at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:18)
                                                                                                    	at com.bumptech.glide.load.resource.bitmap.BitmapDrawableDecoder.decode(BitmapDrawableDecoder.java:58)
                                                                                                    	at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:92)
                                                                                                    	at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70)`

**Comment by Niranjan029** [comment]
can you please explain me the problem in detail I want to work on these ?
