### ISSUE TITLE
Fatal Exception: com.bumptech.glide.load.engine.CallbackException

### ISSUE THREAD

**Issue by billdizl** [bumptech/glide#5229]
implementation 'com.github.bumptech.glide:glide:4.15.1'

Fatal Exception: com.bumptech.glide.load.engine.CallbackException: Unexpected exception thrown by non-Glide code
       at com.bumptech.glide.load.engine.EngineJob.callCallbackOnLoadFailed(EngineJob.java:175)
       at com.bumptech.glide.load.engine.EngineJob$CallLoadFailed.run(EngineJob.java:402)
       at android.os.Handler.handleCallback(Handler.java:761)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6517)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

Caused by java.lang.OutOfMemoryError: Failed to allocate a 1080012 byte allocation with 861224 free bytes and 841KB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.BitmapFactory.nativeDecodeAsset(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:701)
       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:508)
       at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1152)
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:930)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:769)
       at android.content.res.Resources.getDrawable(Resources.java:834)
       at android.content.Context.getDrawable(Context.java:529)
       at androidx.core.content.ContextCompat$Api21Impl.getDrawable(ContextCompat.java:1012)
       at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:522)
       at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:149)
       at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:137)
       at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:66)
       at com.bumptech.glide.load.resource.drawable.DrawableDecoderCompat.loadDrawableV7(DrawableDecoderCompat.java:78)
       at com.bumptech.glide.load.resource.drawable.DrawableDecoderCompat.getDrawable(DrawableDecoderCompat.java:51)
       at com.bumptech.glide.load.resource.drawable.DrawableDecoderCompat.getDrawable(DrawableDecoderCompat.java:42)
       at com.bumptech.glide.request.SingleRequest.loadDrawable(SingleRequest.java:423)
       at com.bumptech.glide.request.SingleRequest.getErrorDrawable(SingleRequest.java:391)
       at com.bumptech.glide.request.SingleRequest.setErrorPlaceholder(SingleRequest.java:438)
       at com.bumptech.glide.request.SingleRequest.onLoadFailed(SingleRequest.java:715)
       at com.bumptech.glide.request.SingleRequest.onLoadFailed(SingleRequest.java:671)
       at com.bumptech.glide.load.engine.EngineJob.callCallbackOnLoadFailed(EngineJob.java:173)
       at com.bumptech.glide.load.engine.EngineJob$CallLoadFailed.run(EngineJob.java:402)
       at android.os.Handler.handleCallback(Handler.java:761)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6517)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by sjudd** [comment]
841KB until OOM suggests your application has a memory leak somewhere.

**Comment by akingyin1987** [comment]
I also experienced this abnormality
