### ISSUE TITLE
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Object[]

### ISSUE THREAD

**Issue by dzmitrymeshcharakou** [bumptech/glide#5236]
com.github.bumptech.glide:annotations:4.13.2
com.github.bumptech.glide:disklrucache:4.13.2
com.github.bumptech.glide:gifdecoder:4.13.2
com.github.bumptech.glide:glide:4.13.2
com.github.bumptech.glide:okhttp3-integration:4.13.2

Crashlytics:
Android 9 - 50%
Android 12 - 13%
Android 13 - 12%

Most populate devices:
Huawei Y9 2019
Nova 3i
Huawei Y5 2019

57% background crash

Fatal Exception: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Object[]
       at androidx.collection.SimpleArrayMap.allocArrays(SimpleArrayMap.java:184)
       at androidx.collection.SimpleArrayMap.put(SimpleArrayMap.java:458)
       at com.bumptech.glide.util.CachedHashCodeArrayMap.put(CachedHashCodeArrayMap.java:34)
       at com.bumptech.glide.load.Options.set(Options.java:20)
       at com.bumptech.glide.request.BaseRequestOptions.set(BaseRequestOptions.java:554)
       at com.bumptech.glide.request.BaseRequestOptions.dontAnimate(BaseRequestOptions.java:1083)

**Comment by subrataindia** [comment]
The error message you're seeing, Fatal Exception: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Object[], indicates that there is a type casting issue in your Android application's code. Specifically, it's trying to cast a String object to an Object[] object, which is not allowed in Java.

The stack trace shows that the error originates from the SimpleArrayMap class in the AndroidX library, and it seems to be related to the use of the Glide image loading library.

To resolve this issue, you should review the code that's causing this exception and identify where the incorrect type casting is occurring.

If you can't identify the issue in your code, consider providing more context or code snippets related to the Glide setup and usage in your application. This additional information could help in providing more specific guidance.
