### ISSUE TITLE
Crash in version 4.8.0

### ISSUE THREAD

**Issue by jhouska** [bumptech/glide#5419]
I use the Bumptech Glide library to display an animated gif.

After upgrading to version 4.8.0, some users have started experiencing the crash:

java.lang.NullPointerException: null cannot be cast to non-null type T of androidx.core.util.Pools.SimplePool
at androidx.core.util.Pools$SimplePool.acquire(Pools.kt:89)
at com.bumptech.glide.util.pool.FactoryPools$FactoryPool.acquire(FactoryPools.java:157)
at com.bumptech.glide.load.engine.Engine$DecodeJobFactory.build(Engine.java:428)
at com.bumptech.glide.load.engine.Engine.load(Engine.java:210)
at com.bumptech.glide.request.SingleRequest.onSizeReady(SingleRequest.java:432)
at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:255)
at com.bumptech.glide.manager.RequestTracker.runRequest(RequestTracker.java:44)
at com.bumptech.glide.RequestManager.track(RequestManager.java:614)
at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:646)
at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:611)
at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:604)
at com.bumptech.glide.load.resource.gif.GifFrameLoader.loadNextFrame(GifFrameLoader.java:226)
at com.bumptech.glide.load.resource.gif.GifFrameLoader.onFrameReady(GifFrameLoader.java:284)
at com.bumptech.glide.load.resource.gif.GifFrameLoader$FrameLoaderCallback.handleMessage(GifFrameLoader.java:298)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7959)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1001)

**Comment by jthou20121212** [comment]
20250820003025
crash:
// CRASH: com.huche (pid 14958) (dump time: 2025-08-20 00:30:25
// Version: 
// Long Msg: java.lang.NullPointerException: null cannot be cast to non-null type T of androidx.core.util.Pools.SimplePool
// 	at androidx.core.util.s$b.acquire(SourceFile:2)
// 	at com.bumptech.glide.util.pool.FactoryPools$FactoryPool.acquire(SourceFile:1)
// 	at com.bumptech.glide.load.engine.Engine$DecodeJobFactory.build(SourceFile:1)
// 	at com.bumptech.glide.load.engine.Engine.load(SourceFile:17)
// 	at com.bumptech.glide.request.SingleRequest.onSizeReady(SourceFile:22)
// 	at com.bumptech.glide.request.SingleRequest.begin(SourceFile:15)
// 	at com.bumptech.glide.manager.RequestTracker.runRequest(SourceFile:3)
// 	at com.bumptech.glide.RequestManager.track(SourceFile:2)
// 	at com.bumptech.glide.RequestBuilder.into(SourceFile:16)
// 	at com.bumptech.glide.RequestBuilder.into(SourceFile:31)
// 	at com.huche.module.ip.IpAllVideoContentViewHolder.L(SourceFile:8)
// 	at com.huche.module.ip.IpAllVideoContentViewHolder.b(SourceFile:1)
// 	at com.huche.module.ip.IpDetailAdapter.O1(SourceFile:2)
// 	at com.huche.module.ip.IpDetailAdapter.K(SourceFile:1)
// 	at com.chad.library.adapter.base.r.F0(SourceFile:4)
// 	at com.chad.library.adapter.base.r.G0(SourceFile:2)
// 	at com.chad.library.adapter.base.r.onBindViewHolder(SourceFile:2)
// 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(SourceFile:8)
// 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(SourceFile:7)
// 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(SourceFile:55)
// 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:2)
// 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:1)
// 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(SourceFile:3)
// 	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(SourceFile:12)
// 	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:9)
// 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:65)
// 	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(SourceFile:3)
// 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:12)
// 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:14)
// 	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:2)
// 	at com.huche.widget.base.BaseRecyclerView.onLayout(SourceFile:1)
// 	at android.view.View.layout(View.java:24791)
// 	at android.view.ViewGroup.layout(ViewGroup.java:6555)
// 	at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SourceFile:18)
// 	at android.view.View.layout(View.java:24791)
// 	at android.view.ViewGroup.layout(ViewGroup.java:6555)
// 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
// 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
// 	at android.view.View.layout(View.java:24791)
// 	at android.view.ViewGroup.layout(ViewGroup.java:6555)
// 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
// 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
// 	at android.view.View.layout(View.java:24791)
// 	at android.view.ViewGroup.layout(ViewGroup.java:6555)
// 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
// 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
// 	at android.view.View.layout(View.java:24791)
// 	at android.view.ViewGroup.layout(ViewGroup.java:6555)
// 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
// 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
// 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
// 	at android.view.View.layout(View.java:24791)
// 	at android.view.ViewGroup.layout(ViewGroup.java:6555)
// 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
// 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
// 	at android.view.View.layout(View.java:24791)
// 	at android.view.ViewGroup.layout(ViewGroup.java:6555)
// 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
// 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
// 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
// 	at android.view.View.layout(View.java:24791)
// 	at android.view.ViewGroup.layout(ViewGroup.java:6555)
// 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
// 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
// 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:868)
// 	at android.view.View.layout(View.java:24791)
// 	at android.view.ViewGroup.layout(ViewGroup.java:6555)
// 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4768)
// 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4013)
// 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2765)
// 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10219)
// 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1544)
// 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1553)
// 	at android.view.Choreographer.doCallbacks(Choreographer.java:1109)
// 	at android.view.Choreographer.doFrame(Choreographer.java:994)
// 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1527)
// 	at android.os.Handler.handleCallback(Handler.java:958)
// 	at android.os.Handler.dispatchMessage(Handler.java:99)
// 	at android.os.Looper.loopOnce(Looper.java:257)
// 	at android.os.Looper.loop(Looper.java:368)
// 	at android.app.ActivityThread.main(ActivityThread.java:8839)
// 	at java.lang.reflect.Method.invoke(Native Method)
// 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
// 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
// crash end


Glide version 4.8.0
Android version 14
