### ISSUE TITLE
ANR during RequestManager Initialization

### ISSUE THREAD

**Issue by prithvibhola** [bumptech/glide#5459]
We are encountering an ANR which appears to occur when Glide.with() is used to load images, with the stack trace pointing to delays during RequestManager initialization and decoding.

Here’s a relevant portion of the stack trace:

```main (runnable):tid=1 systid=13565 
   at com.bumptech.glide.request.RequestOptions.decodeTypeOf(RequestOptions.java:213)
   at com.bumptech.glide.RequestManager.<clinit>(RequestManager.java:59)
   at com.bumptech.glide.GeneratedRequestManagerFactory.build(GeneratedRequestManagerFactory.java:18)
   at com.bumptech.glide.manager.LifecycleRequestManagerRetriever.getOrCreate(LifecycleRequestManagerRetriever.java:43)
   at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:158)
   at com.bumptech.glide.Glide.with(Glide.java:540)
   ... 
```

The ANR happens during image loading, likely due to some operations such as decoding or request initialization being performed on the main thread.

**Glide Version**: 4.15.1

**Integration libraries**: No

**Device/Android Version**: Based on Firebase Crashlytics data, the ANR occurs on multiple devices, with a significant number of occurrences on Oppo devices running Android 11.

**Glide load line / `GlideModule` (if any) / list Adapter code (if any)**:
We have a helper function that is called from a fragment to load a profile image.

```kotlin
fun loadImageWithScopedContext(
        context: Context,
        imageView: ImageView,
        photoUrl: String?,
        @DrawableRes placeholder: Int
) {
    if (isEmpty(photoUrl)) return

    Glide.with(context)
            .load(photoUrl)
            .dontAnimate()
            .diskCacheStrategy(DiskCacheStrategy.ALL)
            .placeholder(placeholder)
            .into(imageView)
}

```

**Layout XML**:
```xml
<ImageView
            android:id="@+id/profilePicture"
            android:layout_width="48dp"
            android:layout_height="48dp"
            android:layout_marginStart="16dp"
            android:layout_marginTop="16dp"
            android:clickable="true"
            android:elevation="8dp"
            android:focusable="true"
            android:src="@drawable/home_page_avatar_placeholder"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />
```

**Comment by mikelhm** [comment]
I meet the the same problem 


com.bumptech.glide.request.target.ImageViewTarget.<init> (ImageViewTarget.java)
com.bumptech.glide.request.target.BitmapImageViewTarget.<init> (BitmapImageViewTarget.java)
com.bumptech.glide.request.target.ImageViewTargetFactory.buildTarget (ImageViewTargetFactory.java:18)
com.bumptech.glide.GlideContext.buildImageViewTarget (GlideContext.java:103)
com.bumptech.glide.RequestBuilder.into (RequestBuilder.java:877)

**Comment by AlexeyGodyaev** [comment]
Almost the same problem, I'm trying to use workmanger. Am I using it right? 
`Glide.with(context).asBitmap().load(logo).override(24,24).submit(24,24).get()`

**Comment by prithvibhola** [comment]
Hi Team,
Do we have any updates on this? This issue is critical and directly impacts our ANR numbers in the app.

**Comment by sureshmaidaragi1919** [comment]
hi we are seeing this more aggressively on android 15 and above please let us know if there is fix on it

```
 main (runnable):tid=1 systid=31421 
       at java.util.Collections$EmptyList.toArray(Collections.java:4879)
       at java.util.concurrent.CopyOnWriteArrayList.<init>(CopyOnWriteArrayList.java:148)
       at com.bumptech.glide.RequestManager.<init>(RequestManager.java:150)
       at com.bumptech.glide.RequestManager.<init>(RequestManager.java:105)
       at com.bumptech.glide.manager.RequestManagerRetriever$1.build(RequestManagerRetriever.java:293)
       at com.bumptech.glide.manager.RequestManagerRetriever.getApplicationManager(RequestManagerRetriever.java:75)
       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:103)
       at com.bumptech.glide.Glide.with(Glide.java:545)
       at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule.providesGlideRequestManager(GlideModule.java:30)
       at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule_ProvidesGlideRequestManagerFactory.providesGlideRequestManager(GlideModule_ProvidesGlideRequestManagerFactory.java:46)
       at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule_ProvidesGlideRequestManagerFactory.get(GlideModule_ProvidesGlideRequestManagerFactory.java:36)
       at com.google.firebase.inappmessaging.display.internal.injection.modules.GlideModule_ProvidesGlideRequestManagerFactory.get(GlideModule_ProvidesGlideRequestManagerFactory.java:13)
       at com.google.firebase.inappmessaging.display.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.google.firebase.inappmessaging.display.internal.FiamImageLoader_Factory.get(FiamImageLoader_Factory.java:30)
       at com.google.firebase.inappmessaging.display.internal.FiamImageLoader_Factory.get(FiamImageLoader_Factory.java:11)
       at com.google.firebase.inappmessaging.display.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay_Factory.get(FirebaseInAppMessagingDisplay_Factory.java:70)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay_Factory.get(FirebaseInAppMessagingDisplay_Factory.java:19)
       at com.google.firebase.inappmessaging.display.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.google.firebase.inappmessaging.display.internal.injection.components.DaggerAppComponent$AppComponentImpl.providesFirebaseInAppMessagingUI(DaggerAppComponent.java:123)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplayRegistrar.buildFirebaseInAppMessagingUI(FirebaseInAppMessagingDisplayRegistrar.java:75)
       at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
       at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:160)
       at com.google.firebase.components.Lazy.get(Lazy.java:53)
       at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:322)
       at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:312)
       at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:607)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:300)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:264)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:249)
       at com.penpencil.physicswallah.startup.initializers.FirebaseInitializer.create(FirebaseInitializer.kt:11)
       at com.penpencil.physicswallah.startup.initializers.FirebaseInitializer.create(FirebaseInitializer.kt:8)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:173)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:239)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:207)
       at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:49)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2748)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2717)
       at android.app.ActivityThread.installProvider(ActivityThread.java:9437)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:8925)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:8543)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication(unavailable)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2871)
       at android.os.Handler.dispatchMessage(Handler.java:109)
       at android.os.Looper.loopOnce(Looper.java:250)
       at android.os.Looper.loop(Looper.java:340)
       at android.app.ActivityThread.main(ActivityThread.java:9895)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:625)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
        
```

<img width="1382" height="365" alt="Image" src="https://github.com/user-attachments/assets/40dd6713-f2b9-4c15-99e8-1102c28de0ff" />
