### ISSUE TITLE
NoSuchMethodError: Resources.getDisplayMetrics at MemorySizeCalculator:35

### ISSUE THREAD

**Issue by bearprada** [bumptech/glide#586]
Hey guys. I got a few crashes from Samsung(SGH S730M) with Android `4.0.4`

```
java.lang.NoSuchMethodError: android.content.res.Resources.getDisplayMetrics
       at com.bumptech.glide.load.engine.cache.MemorySizeCalculator.(SourceFile:35)
       at com.bumptech.glide.GlideBuilder.createGlide(SourceFile:177)
       at com.bumptech.glide.Glide.get(SourceFile:155)
       at com.cardinalblue.android.piccollage.PCApplication.onCreate(SourceFile:90)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3959)
       at android.app.ActivityThread.access$1300(ActivityThread.java:123)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1189)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4429)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

is it OEM issue?

**Comment by TWiStErRob** [comment]
Yes it is. [`getDisplayMetrics`](http://developer.android.com/reference/android/content/res/Resources.html#getDisplayMetrics())is API Level 1...

Or ProGuard has a rare bug (guess from `SourceFile`), is there anything similar (no such method) to this in you reports?

**Comment by sjudd** [comment]
This sounds kind of similar to #578

**Comment by sjudd** [comment]
Lets track these issues in #578.
