### ISSUE TITLE
OutOfMemory 

### ISSUE THREAD

**Issue by ShaneCarr** [bumptech/glide#653]
Hello, 

I am getting out of memory errors. I am able to reproduce this easily. 

Usage

                        Glide.with(context)
                                .load(filepath)
                                .thumbnail((float).1)
                                .into(imageView);

I am loading animated gifs, and regular images. After scrolling around i get get this to happen. Using the cache options seemed to make things worse so i removed it. I am not using this casually. There are dozens of animated gifs loaded that i am scrolling though in a listView.

09-25 22:24:46.396  14036-14178/com.microsoft.flow.android E/art﹕ Throwing OutOfMemoryError "Failed to allocate a 4548612 byte allocation with 3026579 free bytes and 2MB until OOM"
09-25 22:24:46.450  14036-14183/com.microsoft.flow.android E/art﹕ Throwing OutOfMemoryError "Failed to allocate a 4548612 byte allocation with 1699179 free bytes and 1659KB until OOM"
09-25 22:24:46.559  14036-14146/com.microsoft.flow.android E/art﹕ Throwing OutOfMemoryError "Failed to allocate a 4548612 byte allocation with 1699211 free bytes and 1659KB until OOM"
09-25 22:24:46.763  14036-14178/com.microsoft.flow.android E/art﹕ Throwing OutOfMemoryError "Failed to allocate a 4548612 byte allocation with 1699211 free bytes and 1659KB until OOM"
09-25 22:24:46.771  14036-14178/com.microsoft.flow.android E/PriorityExecutor﹕ Request threw uncaught throwable
    java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Failed to allocate a 4548612 byte allocation with 1699211 free bytes and 1659KB until OOM
            at java.util.concurrent.FutureTask.report(FutureTask.java:93)
            at java.util.concurrent.FutureTask.get(FutureTask.java:163)
            at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1120)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
            at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 4548612 byte allocation with 1699211 free bytes and 1659KB until OOM
            at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
            at android.graphics.Bitmap.nativeCreate(Native Method)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
            at com.bumptech.glide.gifdecoder.GifDecoder.getNextBitmap(GifDecoder.java:691)
            at com.bumptech.glide.gifdecoder.GifDecoder.setPixels(GifDecoder.java:515)
            at com.bumptech.glide.gifdecoder.GifDecoder.getNextFrame(GifDecoder.java:299)
            at com.bumptech.glide.load.resource.gif.GifFrameResourceDecoder.decode(GifFrameResourceDecoder.java:20)
            at com.bumptech.glide.load.resource.gif.GifFrameResourceDecoder.decode(GifFrameResourceDecoder.java:11)
            at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:190)
            at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
            at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
            at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
            at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
            at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)

**Comment by TWiStErRob** [comment]
Can you share the adapter, list item XML and ListView/RecyclerView setup? There may be a leaked activity/fragment/view usually by anonymous inner classes, or too big sizes.
How does it behave if you don't do thumbnail?

A more probable one is that you use something like `getItemViewType(int position) { return position; }` which means that none of the ImageViews get recycled/cleared and all out of screen GIFs are held in memory.

MiniTip: `(float).1` === `.1f`

**Comment by sjudd** [comment]
Let us know if you get the chance to answer Robi's questions.

**Comment by ribads** [comment]
Hello Bob am having the same issues and am using a getItemViewType inside of my adapter. Whats the best way to handle this.

**Comment by TWiStErRob** [comment]
Override `onViewRecycled` and clear the ImageViews (`Glide.clear`), to "unBind" and free the resources.

*(Not sure who Bob is... my name is Róbert and I'm not English to be nicked Bob.)*
