### ISSUE TITLE
Loading image failed

### ISSUE THREAD

**Issue by UsherBaby** [bumptech/glide#679]
com.github.bumptech.glide:glide:3.6.1
SamSung Tab 8000
Android versio 4.1.2

/////////////////////////////////////
In PagerAdaper for ViewPager , PhotoView extends ImageView :
```
@Override
        public View instantiateItem(ViewGroup container, int position) {
            final PhotoView photoView = new PhotoView(container.getContext());               container.addView(photoView,LayoutParams.MATCH_PARENT,LayoutParams.MATCH_PARENT);                                                                          
            Glide.with(context).load(urls.get(position)).into(photoView);
            return photoView;
        }
```
/////////////////////////////////////////////////////////////////////////////////////////
Using view pager in my app to load image via glide from sdcard .
Image space occupied but not Image is shown.But gets Out of memory Exception.

///////////////////////////////////
```
02-09 11:45:36.085 15232-15684/com.ut.utbzhpda E/dalvikvm-heap: Out of memory on a 19660816-byte allocation.
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor: Request threw uncaught throwable
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:223)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.util.concurrent.FutureTask.get(FutureTask.java:82)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1084)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.lang.Thread.run(Thread.java:856)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:  Caused by: java.lang.OutOfMemoryError
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at android.graphics.Bitmap.nativeCreate(Native Method)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at android.graphics.Bitmap.createBitmap(Bitmap.java:669)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at android.graphics.Bitmap.createBitmap(Bitmap.java:649)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.bitmap.TransformationUtils.rotateImageExif(TransformationUtils.java:272)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:167)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:50)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:39)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeBitmapWrapper(GifBitmapWrapperResourceDecoder.java:121)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeStream(GifBitmapWrapperResourceDecoder.java:94)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:71)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:61)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:22)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:190)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at java.lang.Thread.run(Thread.java:856) 
02-09 11:45:36.095 15232-15684/com.ut.utbzhpda E/PriorityExecutor:     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118) 
```

**Comment by TWiStErRob** [comment]
> Out of memory on a 19660816-byte allocation.

This means that Glide is trying to allocate something like a 2560x1920xARGB_8888 Bitmap. I guess this means that the screen is around that big based on `match_parent`s. Now, it should be able to hold an image that big for each application, but more than one is unlikely to fit with memory constrains. The `ViewPager` you're probably instatiates too many pages which leads to keeping multiple images like this in memory. Decrease the `setOffscreenPageLimit` back to the default `1`.

In case you didn't set the page limit to a higher value, or you want to know why it can't fit go through the normal OOM diagnostic steps:
 * reproduce above exception (wait till you see it in LogCat)
 * take a heap dump and analyze it

Here are some links:
 * [Overview of steps (2014)](http://stackoverflow.com/a/24547957/253468)
 * [Detailed steps (2011)](http://android-developers.blogspot.hu/2011/03/memory-analysis-for-android.html)
 * [Detailed steps (latest official docs)](https://developer.android.com/tools/debugging/debugging-memory.html#HeapDump)
 * [Important info to know depending on your Activity structure (timeless)](http://commonsware.com/blog/2011/10/03/activities-not-destroyed-to-free-heap-space.html)

**Comment by sjudd** [comment]
Let us know if those steps/links don't help.

**Comment by UsherBaby** [comment]
Thanks , it really works for me.

**Comment by TWiStErRob** [comment]
@UsherBaby, just out of curiousity: which tip/workaround helped?
