### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by androidbyxj** [bumptech/glide#680]
Hello, When i using of glide, I'm using the ViewPager, each page is a fragment. There is only one ImageView with fragment.

The module configuration:
```java
   public class MyGlideModule implements GlideModule {
	private static final int MAX_POOL = 300*1024*1024;

@Override public void applyOptions(Context context, GlideBuilder builder) {
        // Apply options to the builder here.
    	builder.setBitmapPool(new  LruBitmapPool(MAX_POOL));
    	builder.setMemoryCache(new LruResourceCache(MAX_POOL));
    	builder.setDecodeFormat(DecodeFormat.PREFER_RGB_565);
    }
@Override public void registerComponents(Context context, Glide glide) {
        // register ModelLoaders here.
    }
}
```

xml:
```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/black">

       <ImageView
            android:id="@+id/fragment_image"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:scaleType="fitCenter"
            />
        <ProgressBar
            android:id="@+id/fragment_loading"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:layout_centerInParent="true"
            android:visibility="visible" />
</FrameLayout>
```

fragment:

```java
		Glide.with(this).load(mImageUrl).crossFade(100).fitCenter()
		.into(new GlideDrawableImageViewTarget(mImageView) {

			@Override
			public void onResourceReady(GlideDrawable arg0,
					GlideAnimation<? super GlideDrawable> arg1) {
				// TODO Auto-generated method stub
				super.onResourceReady(arg0, arg1);
				progressBar.setVisibility(View.INVISIBLE);
			}

			@Override
			public void onLoadFailed(Exception e, Drawable errorDrawable) {
				// TODO Auto-generated method stub
				super.onLoadFailed(e, errorDrawable);
				progressBar.setVisibility(View.INVISIBLE);
			}
		});
```

```
10-12 18:52:39.202: E/dalvikvm-heap(25147): Out of memory on a 3144976-byte allocation.
10-12 18:52:39.222: E/PriorityExecutor(25147): Request threw uncaught throwable
10-12 18:52:39.222: E/PriorityExecutor(25147): java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at java.util.concurrent.FutureTask.report(FutureTask.java:93)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at java.util.concurrent.FutureTask.get(FutureTask.java:163)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1120)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at java.lang.Thread.run(Thread.java:841)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
10-12 18:52:39.222: E/PriorityExecutor(25147): Caused by: java.lang.OutOfMemoryError
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at android.graphics.Bitmap.nativeCreate(Native Method)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:819)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:796)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:763)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at com.bumptech.glide.load.resource.bitmap.TransformationUtils.fitCenter(TransformationUtils.java:112)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at com.bumptech.glide.load.resource.bitmap.FitCenter.transform(FitCenter.java:24)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at com.bumptech.glide.load.resource.bitmap.BitmapTransformation.transform(BitmapTransformation.java:54)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperTransformation.transform(GifBitmapWrapperTransformation.java:34)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at com.bumptech.glide.load.engine.DecodeJob.transform(DecodeJob.java:236)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at com.bumptech.glide.load.engine.DecodeJob.transformEncodeAndTranscode(DecodeJob.java:139)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:129)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-12 18:52:39.222: E/PriorityExecutor(25147): 	... 3 more
```

**Comment by TWiStErRob** [comment]
Please do one of the following:
 * There's a link above the comment box: "Styling with Markdown is supported" please click it, read it, and edit (upper right corner) your issue description to make it readable.
 * We also have an [issue template](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues) which has all the formatting you need ready.

**Comment by sjudd** [comment]
300*1024*1024 is 300mb. You're reserving up to 600mb for storing Bitmaps. Use Glide's default cache and bitmap pool sizes.
