### ISSUE TITLE
ClassNotFoundException: OkHttpGlideModule

### ISSUE THREAD

**Issue by brucewuu520** [bumptech/glide#713]
java.lang.IllegalArgumentException: Unable to find GlideModule implementation
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalArgumentException: Unable to find GlideModule implementation
at com.bumptech.glide.d.b.a(ManifestParser.java:46)
at com.bumptech.glide.d.b.a(ManifestParser.java:30)
at com.bumptech.glide.m.b(Glide.java:149)
at com.bumptech.glide.u.<init>(RequestManager.java:62)
at com.bumptech.glide.u.<init>(RequestManager.java:53)
at com.bumptech.glide.manager.k.a(RequestManagerRetriever.java:171)
at com.bumptech.glide.manager.k.a(RequestManagerRetriever.java:127)
at com.bumptech.glide.m.a(Glide.java:632)

Caused by: java.lang.ClassNotFoundException: com.bumptech.glide.integration.okhttp.OkHttpGlideModule
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:324)
at java.lang.Class.forName(Class.java:285)
at com.bumptech.glide.d.b.a(ManifestParser.java:44)
... 20 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bumptech.glide.integration.okhttp.OkHttpGlideModule" on path: DexPathList[[zip file "/data/app/com.brucewuu.android.mdog-1/base.apk"],nativeLibraryDirectories=[/data/app/com.brucewuu.android.mdog-1/lib/arm, /vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
at java.lang.ClassLoader.loadClass(ClassLoader.java:469)

**Comment by TWiStErRob** [comment]
Add to ProGuard.cfg:
```pro
-keep public class * implements com.bumptech.glide.module.GlideModule
```
