### ISSUE TITLE
"Error reading data from stream" from partially downloaded GIFs when used in list/gridview

### ISSUE THREAD

**Issue by kenkyee** [bumptech/glide#725]
I think this is probably because the okhttp thread to download the GIF was cancelled when the gridview/listview item was recycled.

Glide should probably catch this exception and retry the download:
```ruby
11-04 12:22:46.977 27109-27251/com.sdktestapp W/GifResourceDecoder: Error reading data from stream
java.io.InterruptedIOException
    at com.android.okio.Deadline.throwIfReached(Deadline.java:56)
    at com.android.okio.Okio$2.read(Okio.java:110)
    at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
    at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:442)
    at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
    at java.io.FilterInputStream.read(FilterInputStream.java:118)
    at com.bumptech.glide.util.ContentLengthInputStream.read(ContentLengthInputStream.java:65)
    at com.bumptech.glide.util.ContentLengthInputStream.read(ContentLengthInputStream.java:60)
    at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:132)
    at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:309)
    at java.io.InputStream.read(InputStream.java:162)
    at com.bumptech.glide.load.resource.gif.GifResourceDecoder.inputStreamToBytes(GifResourceDecoder.java:105)
    at com.bumptech.glide.load.resource.gif.GifResourceDecoder.decode(GifResourceDecoder.java:57)
    at com.bumptech.glide.load.resource.gif.GifResourceDecoder.decode(GifResourceDecoder.java:26)
    at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeGifWrapper(GifBitmapWrapperResourceDecoder.java:101)
    at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeStream(GifBitmapWrapperResourceDecoder.java:87)
    at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:71)
    at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:61)
    at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:22)
    at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:190)
    at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
    at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
    at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
    at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
    at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
    at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
```

**Comment by TWiStErRob** [comment]
Sounds like #126 and also https://github.com/bumptech/glide/issues/513#issuecomment-117690923

As stated in many issues before: Glide is not a networking library, and retrying would be a networking library feature. You can set up OkHttp however you like to make it retry or build your own logic.

My guess would be that you didn't set `.diskCacheStrategy(SOURCE)` on the load which is [highy recommended for GIFs](https://github.com/bumptech/glide/issues?q=is%3Aissue+gif+diskcachestrategy+source), try to reproduce it with that or increase the timeout.

Please try to provide more information in the future, see [CONTRIBUTING.md](https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues). You can also edit your original comment.

**Comment by kenkyee** [comment]
Thanks Rob.
Setting that helped.  It's probably worth adding a big note on the Glide home page that you should use that diskstrategy flag and turn on LargeMem in your manifest.

Glide isn't a networking library, but it has to be invoking network calls to download stuff.  If it detects this kind of error, it sounds like a truncated file from the networking library's cache, so if possible, Glide should request the networking library to redownload it IMHO.  It's not a networking library, but it uses it, and as users of Glide, we can't initiate the network download retries AFAIK.  If we can do it, I wouldn't have a problem w/ doing it in our code either.

Thanks for GIF support though...that's why I'm using this instead of Picasso :-)

**Comment by kenkyee** [comment]
Hmm..that actually might be a better default setting for diskCacheStrategy....

**Comment by TWiStErRob** [comment]
DiskCacheStrategy will get smarter in Glide 4.0 with better defaults. I think this problem only comes up if you're loading megabytes sized GIFs on a very slow connection/from slow server. LargeMem shouldn't be necessary though.

> If it detects this kind of error, it sounds like a truncated file from the networking library's cache

Glide works with any networking library through [integration libraries](https://github.com/bumptech/glide/wiki/Integration-Libraries). The problem with your proposal is that each of those libraries throw a different exception or return a value indicating failure, so we can't know how and when to retry. Take a look at #520 for more info.

I hope it's clearer now how this is not and should not be Glide's responsibilty. You can set up retries or write an integration library that returns a smart stream that retries if it fails to serve some bytes. OkHttp shouldn't return a partially cached stream and I think it doesn't do that anyway:

Originally you used the default RESULT cache which means that the stream was returned directly to the GIF decoder. While decoding the frames too much time has elapsed and an OkHttp deadline was reached. Maybe the GIF is too long or the delays are too big between frames.
By changing it to SOURCE you essentially told Glide to save that link first to the disk cache and then GIF decoder received a stream pointing to the disk which doesn't have a timeout.

*In general we tend to expect too much from most of the libraries, expecting them to think of every use case and provide a simple method for that, but we can easily forget that people maintain libraries (with Glide it's mostly Sam alone). I'm a Glide user too, and I learned that I can Lego together small bits of it to achieve almost anything: see some of the issues here. It's also open source so PRs are warmly welcome ;)

Anyway, thanks for the feedback! Good to see more critical thinkers out there. Remember that if you thought about it maybe the author did too, it's just not possible or it's not worth the effort.*

**Comment by kenkyee** [comment]
Thanks for the extra detail :-)

In that case, it does seem like SOURCE is a better default, although I'm surprised that the gif decoder will cause an underrun when reading from the network.  Makes more sense than okhttp giving truncated files :-)
