### ISSUE TITLE
Bitmap recycling below Kiktat

### ISSUE THREAD

**Issue by headsvk** [bumptech/glide#747]
I stumbled to an issue with loading images in fragments with a view pager.
Each fragment has a single image view and after loading tens of pages, devices running 4.3 or below start to run out of memory because bitmaps don't get garbage collected.

Calling ```Glide.get(context).clearMemory()``` or calling the GC doesn't help.
Is there a special way to load images below Kitkat?

```
Fatal Exception: java.lang.OutOfMemoryError
       at android.graphics.BitmapFactory.nativeDecodeAsset(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:502)
       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:355)
       at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:785)
       at android.content.res.Resources.loadDrawable(Resources.java:1965)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
       at android.widget.ImageView.<init>(ImageView.java:120)
       at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:60)
       at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:56)
       at android.support.v7.internal.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:98)
       at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:926)
       at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:980)
       at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:171)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:675)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
       at dk.tv2.tvtid.program.ProgramDetailFragment.onCreateView(ProgramDetailFragment.java:140)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1965)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1078)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1624)
       at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
       at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
       at android.support.v4.view.ViewPager$3.run(ViewPager.java:251)
       at android.support.v4.view.ViewPager.completeScroll(ViewPager.java:1849)
       at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1978)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1817)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1875)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1875)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1875)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1875)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1875)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1875)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1953)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1405)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2410)
       at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
       at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1901)
       at android.view.View.dispatchPointerEvent(View.java:7420)
       at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3220)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3165)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4292)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4271)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4363)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:125)
       at android.os.Looper.loop(Looper.java:124)
       at android.app.ActivityThread.main(ActivityThread.java:5039)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by TWiStErRob** [comment]
There's no Glide in stack trace, it looks like you're creating an ImageView from XML and you defined an `android:src="@drawable/..."`. I suggest you remove that if you will overwrite that image anyway, it's just unnecessarily using CPU and hence battery. Though this won't solve your issue, it's good practice.

When you're using a recycler or list view the bonus you get is that each of those items are re-used. When Glide loads into an ImageView that already has something in it, it clears the previous load and starts a new one. You don't need to do this manually for recycler/list. The problem is that pager doesn't reuse any pages, it always creates a new one. You can set how many off-screen pages there are, but sometimes even that is not enough:
 * Make sure you don't hold onto any views/bitmaps from offscreen pages.
 * Call `Glide.clear(imageView)` in `PagerAdapter.destroyItem` to free up memory for pages that are coming on screen.

`clearMemory()` don't do any good in this case, because any Bitmaps that are active (i.e. associated/displayed to/in an ImageView) are not freed, well, because they are in-use according to Glide. This is why you need to clear the views that are not needed any more (even if temporarily). The memory cache will make sure they're reloaded quickly if the users goes left and right quickly (so don't clear memory cache).

Usual memory leak diagnostic steps: https://github.com/bumptech/glide/issues/679#issuecomment-148194654

Let me know if you need more help or you see it differently than the above.

**Comment by headsvk** [comment]
Thanks for the answer, yes it was not related to Glide. I didn't set drawables for that ImageView through xml just a background color, but I have other ImageButtons and ImageViews on which I set drawables and that seems to cause the problem.
I'm sorry for posting this question here, I wouldn't expect that native drawable handling would not work.
