### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by 5google5** [bumptech/glide#774]
OOM on Glide error

```ruby
 E/PriorityExecutor: Request threw uncaught throwable
 E/PriorityExecutor: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
 E/PriorityExecutor:     at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:223)
 E/PriorityExecutor:     at java.util.concurrent.FutureTask.get(FutureTask.java:82)
 E/PriorityExecutor:     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
 E/PriorityExecutor:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1084)
 E/PriorityExecutor:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
 E/PriorityExecutor:     at java.lang.Thread.run(Thread.java:856)
 E/PriorityExecutor:     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
 E/PriorityExecutor:  Caused by: java.lang.OutOfMemoryError
 E/PriorityExecutor:     at android.graphics.Bitmap.nativeCreate(Native Method)
 E/PriorityExecutor:     at android.graphics.Bitmap.createBitmap(Bitmap.java:640)
 E/PriorityExecutor:     at android.graphics.Bitmap.createBitmap(Bitmap.java:620)
 E/PriorityExecutor:     at com.bumptech.glide.load.resource.bitmap.TransformationUtils.fitCenter(TransformationUtils.java:112)
 E/PriorityExecutor:     at com.bumptech.glide.load.resource.bitmap.FitCenter.transform(FitCenter.java:24)
 E/PriorityExecutor:     at com.bumptech.glide.load.resource.bitmap.BitmapTransformation.transform(BitmapTransformation.java:54)
 E/PriorityExecutor:     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperTransformation.transform(GifBitmapWrapperTransformation.java:34)
 E/PriorityExecutor:     at com.bumptech.glide.load.engine.DecodeJob.transform(DecodeJob.java:236)
 E/PriorityExecutor:     at com.bumptech.glide.load.engine.DecodeJob.transformEncodeAndTranscode(DecodeJob.java:139)
 E/PriorityExecutor:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:129)
 E/PriorityExecutor:     at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
 E/PriorityExecutor:     at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
 E/PriorityExecutor:     at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
 E/PriorityExecutor:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
 E/PriorityExecutor:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
 E/PriorityExecutor:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
 E/PriorityExecutor:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
 E/PriorityExecutor:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)?
 E/PriorityExecutor:     at java.lang.Thread.run(Thread.java:856)?
 E/PriorityExecutor:     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)?
```

and i used 

```gradle
compile 'com.github.bumptech.glide:glide:3.6.1'
compile 'com.squareup.okhttp:okhttp:2.5.0'
```

can help me? thanks

**Comment by 5google5** [comment]
and user as:
 Glide.clear(holder.photo_view);
        Glide.with(activity).load(urls.get(position).replace("!small", "!mobile"))
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .skipMemoryCache(true)
                .error(R.mipmap.ic_no_img)
                .into(holder.photo_view);

**Comment by TWiStErRob** [comment]
*Tip: you don't need to `Glide.clear`, `.into()` does it for you if needed.*

From this information it's not clear why you get OOM, there must be a memory leak somewhere, check out these links: https://github.com/bumptech/glide/issues/679#issuecomment-148194654

Usually there's a dead activity that something is holding onto, or there can be a bug in the ViewHolder pattern, or the image is just too big. Only you know how your activities are managed and how you reproduced this issue. Try to figure out what can leak based on what you do to reproduce this.
