### ISSUE TITLE
wrong warning message

### ISSUE THREAD

**Issue by JoesChen** [bumptech/glide#778]
I use a custom ModelLoader to load my image,then it warn me that " You must provide a Model of a type for which there is a registered ModelLoader, if you are using a custom model, you must first call Glide... ".
So I rewrote the model and still failed,and I check my ModelLoader again and again,all seems good.
Finally I found out that I forgot add INTERNET access permission in the manifest....The wrong message just mislead my a lot.. :(

**Comment by TWiStErRob** [comment]
Thanks, I was able to reproduce it with this:
```java
// GlideModule
glide.register(CustomModel.class, InputStream.class, new CustomLoader.Factory());
// UI code
Glide.with(context).load(new CustomModel("http://i.imgur.com/etgBAG4.jpg")).into(imageView);
```

```java
public class CustomModel {
      final String url;
      public CustomModel(String url) { this.url = url; }
}
class CustomLoader implements StreamModelLoader<CustomModel> {
      private final ModelLoader<String, InputStream> loader;
      public CustomLoader(ModelLoader<String, InputStream> loader) {
            this.loader = loader;
      }
      @Override public DataFetcher<InputStream> getResourceFetcher(CustomModel model, int width, int height) {
            return loader.getResourceFetcher(model.url, width, height);
      }

      static class Factory implements ModelLoaderFactory<CustomModel, InputStream> {
            @Override public ModelLoader<CustomModel, InputStream> build(Context context, GenericLoaderFactory factories) {
                  return new CustomLoader(factories.buildModelLoader(String.class, InputStream.class));
            }
            @Override public void teardown() {
            }
      }
}
```

```
java.lang.IllegalArgumentException: Unknown type class net.twisterrob.app.glide.github._778_missing_loader.CustomModel. You must provide a Model of a type for which there is a registered ModelLoader, if you are using a custom model, you must first call Glide#register with a ModelLoaderFactory for your custom model class
    at com.bumptech.glide.RequestManager.loadGeneric(RequestManager.java:629)
    at com.bumptech.glide.RequestManager.load(RequestManager.java:598)
    at net.twisterrob.app.glide.github._778_missing_loader.TestFragment.load(TestFragment.java:13)
```

**Comment by TWiStErRob** [comment]
Oh, actually I forgot to add the `GlideModule` in the manifest. Are you sure you didn't do the same?
Now I'm getting this, correctly:
```
LoggingListener.onException(java.lang.SecurityException: Permission denied (missing INTERNET permission?), net.twisterrob.app.glide.github._778_missing_loader.CustomModel@42ab36c8, Target for: ImageView{42a8e120 V.ED..C. ........ 0,0-1080,1677 #1020006 android:id/icon}, true)
java.lang.SecurityException: Permission denied (missing INTERNET permission?)
    at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
    ...
Caused by: libcore.io.GaiException: getaddrinfo failed: EAI_NODATA (No address associated with hostname)
    at libcore.io.Posix.getaddrinfo(Native Method)
    ...
Caused by: libcore.io.ErrnoException: getaddrinfo failed: EACCES (Permission denied)
    at libcore.io.Posix.getaddrinfo(Native Method)
    at libcore.io.ForwardingOs.getaddrinfo(ForwardingOs.java:61)
    at java.net.InetAddress.lookupHostByName(InetAddress.java:405)
    at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
    at java.net.InetAddress.getAllByName(InetAddress.java:214)
    at com.android.okhttp.internal.Dns$1.getAllByName(Dns.java:28)
    at com.android.okhttp.internal.http....
    at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
    at com.bumptech.glide.load....
    at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
    at java.util.concurrent....
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)
    at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)

```

When you added the INTERNET permission did you also add the GlideModule meta-data? If not, maybe it was just your build not picking up the manifest changes.

 * What do you use to build?
 * Do you use an integration library?
 * Can you please try to reproduce it again by removing the permission?

**Comment by JoesChen** [comment]
Oh,you are right. I added GlideModule in wrong place of the manifest and forgot to add INTERNET permission,and change them at last so it works.

**Comment by TWiStErRob** [comment]
Where was your GlideModule meta in the wrong place?

**Comment by TWiStErRob** [comment]
Updated the [wiki](https://github.com/bumptech/glide/wiki/Configuration#creating-a-glidemodule).

**Comment by JoesChen** [comment]
Just outside the <application> node..  Thanks for your reply too.
