### ISSUE TITLE
NinePatchDrawable can't be loaded

### ISSUE THREAD

**Issue by mullender** [bumptech/glide#786]
```
12-03 15:06:20.230    6525-7174/xx E/GlideExecutor﹕ Request threw uncaught throwable
    com.bumptech.glide.Registry$NoModelLoaderAvailableException: Failed to find any ModelLoaders for model: android.graphics.drawable.NinePatchDrawable@531784b4
            at com.bumptech.glide.Registry.getModelLoaders(Registry.java:222)
            at com.bumptech.glide.load.engine.DecodeHelper.getLoadData(DecodeHelper.java:180)
            at com.bumptech.glide.load.engine.DecodeHelper.getCacheKeys(DecodeHelper.java:198)
            at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:42)
            at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:273)
            at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:240)
            at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:218)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
            at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:263)
```

**Comment by TWiStErRob** [comment]
I think you're experiencing #122. Also take a look at related #350, but that shouldn't affect you as far as I know. It also looks like you're using v4, right? What's your Glide line?

*Any reports are welcome, thank you, but please give more info in the future based on https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues to eliminate guesswork.*
