### ISSUE TITLE
Errors reading from HttpUrlConnection streams are not handled correctly

### ISSUE THREAD

**Issue by sjudd** [bumptech/glide#84]
It appears they aren't passed back to the request which leads to verbose logging and means the exception listener isn't called and the error drawable isn't set.

```
W/GifResourceDecoder( 1250): Error reading data from stream
W/GifResourceDecoder( 1250): java.net.SocketTimeoutException
W/GifResourceDecoder( 1250): at java.net.PlainSocketImpl.read(PlainSocketImpl.java:491)
W/GifResourceDecoder( 1250): at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
W/GifResourceDecoder( 1250): at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
W/GifResourceDecoder( 1250): at java.io.BufferedInputStream.read(BufferedInputStream.java:283)
W/GifResourceDecoder( 1250): at com.android.okhttp.internal.http.HttpTransport$FixedLengthInputStream.read(HttpTransport.java:386)
W/GifResourceDecoder( 1250): at java.io.InputStream.read(InputStream.java:162)
W/GifResourceDecoder( 1250): at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:126)
W/GifResourceDecoder( 1250): at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:308)
W/GifResourceDecoder( 1250): at com.bumptech.glide.load.resource.gif.GifResourceDecoder.inputStreamToBytes(GifResourceDecoder.java:70)
W/GifResourceDecoder( 1250): at com.bumptech.glide.load.resource.gif.GifResourceDecoder.decode(GifResourceDecoder.java:39)
W/GifResourceDecoder( 1250): at com.bumptech.glide.load.resource.gif.GifResourceDecoder.decode(GifResourceDecoder.java:23)
W/GifResourceDecoder( 1250): at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:46)
W/GifResourceDecoder( 1250): at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:20)
W/GifResourceDecoder( 1250): at com.bumptech.glide.load.engine.SourceResourceRunner.decodeFromSource(SourceResourceRunner.java:177)
W/GifResourceDecoder( 1250): at com.bumptech.glide.load.engine.SourceResourceRunner.run(SourceResourceRunner.java:126)
W/GifResourceDecoder( 1250): at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/GifResourceDecoder( 1250): at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/GifResourceDecoder( 1250): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/GifResourceDecoder( 1250): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/GifResourceDecoder( 1250): at java.lang.Thread.run(Thread.java:841)
W/GifResourceDecoder( 1250): at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:46)
W/GifHeaderParser( 1250): Error Reading Block
W/GifHeaderParser( 1250): java.nio.BufferUnderflowException
W/GifHeaderParser( 1250): at java.nio.Buffer.checkGetBounds(Buffer.java:177)
W/GifHeaderParser( 1250): at java.nio.ByteArrayBuffer.get(ByteArrayBuffer.java:108)
W/GifHeaderParser( 1250): at com.bumptech.glide.gifdecoder.GifHeaderParser.readBlock(GifHeaderParser.java:397)
W/GifHeaderParser( 1250): at com.bumptech.glide.gifdecoder.GifHeaderParser.skipBitmapData(GifHeaderParser.java:311)
W/GifHeaderParser( 1250): at com.bumptech.glide.gifdecoder.GifHeaderParser.readBitmap(GifHeaderParser.java:172)
W/GifHeaderParser( 1250): at com.bumptech.glide.gifdecoder.GifHeaderParser.readContents(GifHeaderParser.java:67)
W/GifHeaderParser( 1250): at com.bumptech.glide.gifdecoder.GifHeaderParser.parseHeader(GifHeaderParser.java:47)
W/GifHeaderParser( 1250): at com.bumptech.glide.load.resource.gif.GifResourceDecoder.decode(GifResourceDecoder.java:40)
W/GifHeaderParser( 1250): at com.bumptech.glide.load.resource.gif.GifResourceDecoder.decode(GifResourceDecoder.java:23)
W/GifHeaderParser( 1250): at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:46)
W/GifHeaderParser( 1250): at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:20)
W/GifHeaderParser( 1250): at com.bumptech.glide.load.engine.SourceResourceRunner.decodeFromSource(SourceResourceRunner.java:177)
W/GifHeaderParser( 1250): at com.bumptech.glide.load.engine.SourceResourceRunner.run(SourceResourceRunner.java:126)
W/GifHeaderParser( 1250): at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/GifHeaderParser( 1250): at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/GifHeaderParser( 1250): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/GifHeaderParser( 1250): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/GifHeaderParser( 1250): at java.lang.Thread.run(Thread.java:841)
W/GifHeaderParser( 1250): at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:46)
```

**Comment by walterharlan** [comment]
Thank you for providing such insightful knowledge. Your webpage is fantastic. It's amazing how much information there on your website. I just found a pretty good game that is [snake io](https://snakeio.co) , play right now with me
