### ISSUE TITLE
java.net.SocketTimeoutException while downloading image via target

### ISSUE THREAD

**Issue by MangeshKadam** [bumptech/glide#844]
Hi am trying to download image in Bitmap via target. But I am getting below exception
```
12-26 16:22:45.150 4771-4771/com.itweb.ecommerce W/System.err: java.lang.RuntimeException: java.net.SocketTimeoutException
12-26 16:22:45.151 4771-4771/com.itweb.ecommerce W/System.err:     at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:162)
12-26 16:22:45.151 4771-4771/com.itweb.ecommerce W/System.err:     at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:50)
12-26 16:22:45.151 4771-4771/com.itweb.ecommerce W/System.err:     at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
12-26 16:22:45.151 4771-4771/com.itweb.ecommerce W/System.err:     at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:39)
12-26 16:22:45.151 4771-4771/com.itweb.ecommerce W/System.err:     at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)
```

Strange thing is same code is working fine when I am trying piece of code in activity. I tried even downlading the image via same url. Error I am getting is on fragment. Any help on this will be useful. Below is my sample piece of code.

```java
 target = new SimpleTarget<Bitmap>(150,150) {
            @Override
            public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                Logger.d("I got the bitmap");
                Drawable drawable = new BitmapDrawable(getResources(), resource);
                drawablesArray.add(drawable);            
            }

            @Override
            public void onLoadFailed(Exception e, Drawable errorDrawable) {
                super.onLoadFailed(e, errorDrawable);
                e.printStackTrace();
                Logger.d("FAILED TO DOWNLOAD RESOURCE");
            }
        };
```

```java
Glide.with(HomeCategoryFragment.this).load(url).asBitmap().into(target);
```

**Comment by TWiStErRob** [comment]
There shouldn't be any difference like this for loading with(Fragment) or with(Activity). Maybe when you tried it was already cached or the server was quick enough at that time. If you tried a standalone activity maybe you have many other things going on around the fragment, for example other network requests. You can try to increase the timeout of the networking. Take a look at #753 as it looks similar, and #432 for increasing timeout.
