### ISSUE TITLE
Exception after adding Okhttp3 integration

### ISSUE THREAD

**Issue by alashow** [bumptech/glide#879]
I wanted to add okhttp3 integration and now i have following exception:

```ruby
java.lang.AbstractMethodError: abstract method "void com.bumptech.glide.module.GlideModule.registerComponents(android.content.Context, com.bumptech.glide.Glide)"
       at com.bumptech.glide.Glide.get(Glide.java:157)
       at com.bumptech.glide.RequestManager.<init>(RequestManager.java:62)
       at com.bumptech.glide.RequestManager.<init>(RequestManager.java:53)
       at com.bumptech.glide.manager.RequestManagerRetriever.supportFragmentGet(RequestManagerRetriever.java:198)
       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:104)
       at com.bumptech.glide.Glide.with(Glide.java:644)
       at tm.asmanoky.aziada.ui.fragment.MainFragment.initTopPages(MainFragment.java:226)
       at tm.asmanoky.aziada.ui.fragment.MainFragment.access$300(MainFragment.java:51)
       at tm.asmanoky.aziada.ui.fragment.MainFragment$1.onReady(MainFragment.java:105)
       at tm.asmanoky.aziada.ui.fragment.MainFragment.initMain(MainFragment.java:165)
       at tm.asmanoky.aziada.ui.fragment.MainFragment.onActivityCreated(MainFragment.java:132)
       at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1970)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1092)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
       at android.app.Activity.performStart(Activity.java:6268)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Glide load line:
```java
Glide.with(getActivity())
                .load(url)
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .into(imageView);
```

build.gradle:
```groovy
...
compile 'com.github.bumptech.glide:okhttp3-integration:2.0.0-SNAPSHOT@aar'
compile 'com.squareup.okhttp:okhttp-urlconnection:2.4.0'
compile 'com.github.bumptech.glide:glide:3.6.1'
compile 'com.squareup.okhttp3:okhttp:3.0.0-RC1'
compile 'com.mcxiaoke.volley:library:1.0.19'
compile 'com.squareup.okio:okio:1.6.0'
...
```

**Comment by TWiStErRob** [comment]
GlideModule interface has changed between 3.x (branch 3.0) and 4.x (master). okhttp3 has been only created for Glide 4.x which is not released yet. Either update your glide dep to `4.0.0-SNAPSHOT` or backport #856 to 3.x. Feel free to create a PR against 3.0 branch.

**Comment by alashow** [comment]
@TWiStErRob is there any guidelines for moving to 4.x?

**Comment by TWiStErRob** [comment]
No, because it's not finalised nor released. But if you don't have too many customizations you can essentially go from:
```
Glide.with(...).load(...).[options].into(imageView);
```
to
```
Glide.with(...).load(...).apply(new RequestOptions().[options]).into(imageView);
```
As you can see you can save the options really easily into a (static) field to keep allocation count down.

**Comment by TWiStErRob** [comment]
[Glide 3.7.0](https://github.com/bumptech/glide/releases/tag/v3.7.0) fixes this, so you should be able to use that if you reference `okhttp3-integration:1.4.0`; beware of #941.
