### ISSUE TITLE
Crash when clear memory

### ISSUE THREAD

**Issue by waynell** [bumptech/glide#895]
**Glide Version**: 3.6.1
**Device/Android Version**: SM-N910U/5.0.1
**Issue details/Repro steps/Use case background**: 

call Glide.clearMemory when activity is destroyed

**Glide load line**:

``` java
Glide.with(fragment)
     .load(url)
     .asBitmap()
     .placeholder(R.drawable.placeholder)
     .diskCacheStrategy(DiskCacheStrategy.SOURCE)
     .dontAnimate()
     .into(imageview);
```

**Stack trace / LogCat**:

``` java
java.lang.RuntimeException:Unable to destroy activity {com.xxxxxxx.MainActivity}: java.util.NoSuchElementException
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4229)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4247)
at android.app.ActivityThread.access$1500(ActivityThread.java:179)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5972)
at java.lang.reflect.Method.invoke(Method.java)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by:java.util.NoSuchElementException:null
at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:349)
at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:375)
at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:373)
at com.bumptech.glide.util.LruCache.trimToSize(SourceFile:157)
at com.bumptech.glide.util.LruCache.clearMemory(SourceFile:146)
at com.bumptech.glide.Glide.clearMemory(SourceFile:370)
at com.xxxxxxx.MainActivity.onDestroy(SourceFile:519)
at android.app.Activity.performDestroy(Activity.java:6531)
at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4207)
... 10 more
```

**Comment by TWiStErRob** [comment]
Can you please explain more how you got this?
Can you consistently repro this?
Could you please make a repro app where we can debug?
Does it happen on other devices?
