### ISSUE TITLE
at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed

### ISSUE THREAD

**Issue by fangasvsass** [bumptech/glide#926]
how to use glide  avoid this Exception ？

**Comment by TWiStErRob** [comment]
That's not an exception, that's a method name. Please provide more information, like: https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues

From the available info I would say: don't start a load after the Fragment/Activity has been destroyed.

**Comment by fangasvsass** [comment]
Caused by: java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
                                                                         at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134)
                                                                         at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:102)
                                                                         at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:87)
                                                                         at com.bumptech.glide.Glide.with(Glide.java:620)
                                                                         at com.yunwang.yunwang.utils.GeneralUtil.setIcon(GeneralUtil.java:298)
                                                                         at com.yunwang.yunwang.activity.LearnFriendActivity.changeView(LearnFriendActivity.java:160)
                                                                         at com.yunwang.yunwang.activity.LearnFriendActivity.access$000(LearnFriendActivity.java:60)
                                                                         at com.yunwang.yunwang.activity.LearnFriendActivity$3.onSuccess(LearnFriendActivity.java:206)
                                                                         at com.yunwang.yunwang.activity.LearnFriendActivity$3.onSuccess(LearnFriendActivity.java:196)
                                                                         at com.loopj.android.http.TextHttpResponseHandler.onSuccess(TextHttpResponseHandler.java:153)
                                                                         at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:351)
                                                                         at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage

**Comment by fangasvsass** [comment]
start activity first then  finish actiivty At once ， It will become a crash

**Comment by TWiStErRob** [comment]
How do you finish it? Where is the Glide load? Which life cycle events are involved?

**Comment by fangasvsass** [comment]
when activity onCreate  Glide load

**Comment by fangasvsass** [comment]
how to ues glide to avoid this Exception  in activity or fragment

**Comment by fangasvsass** [comment]
public static void  setIcon(Context mActivity,Me user,CircleIcon circleIcon){
        Glide.with(mActivity)
                .load(user.avatar)
                .fitCenter()
                .into(circleIcon.icon);
        circleIcon.setIdenIcon(user);

    }

this method  in  oncreat

**Comment by TWiStErRob** [comment]
So do you have something like this in onCreate?
```java
setContentView()
circleIcon.icon = findViewById()
setIcon(this, user, circleIcon)
if (something) finish()
```

**Comment by fangasvsass** [comment]
yes

**Comment by TWiStErRob** [comment]
Change it to either:
```java
if (something) {
    finish();
    return;
}
setContentView()
circleIcon.icon = findViewById()
setIcon(this, user, circleIcon)
```
or
```java
setContentView()
circleIcon.icon = findViewById()
if (something) {
    finish()
} else {
    setIcon(this, user, circleIcon)
}
```
Notice that in both cases only one of finish and setIcon will execute.

The first is better because if you know that activity will finish anyway, there's no point in setting up any views.

**Comment by fangasvsass** [comment]
thank you very mach
