### ISSUE TITLE
Cannot load SVG 

### ISSUE THREAD

**Issue by silenus092** [bumptech/glide#936]
```java
GenericRequestBuilder<Uri, InputStream, SVG, PictureDrawable> requestBuilder = Glide.with(this)
    .using(Glide.buildStreamModelLoader(Uri.class, MapActivity.this), InputStream.class)
    .from(Uri.class)
    .as(SVG.class)
    .transcode(new SvgDrawableTranscoder(), PictureDrawable.class)
    .sourceEncoder(new StreamEncoder())
    .cacheDecoder(new FileToStreamDecoder<SVG>(new SvgDecoder()))
    .decoder(new SvgDecoder())
    .placeholder(R.drawable.book)
    .error(R.drawable.background_shelf)
    .animate(android.R.anim.fade_in)
    .listener(new SvgSoftwareLayerSetter<Uri>()) ;

Uri uri = Uri.parse("http://www.clker.com/cliparts/u/Z/2/b/a/6/android-toy-h.svg");
requestBuilder.diskCacheStrategy(DiskCacheStrategy.SOURCE)
              .load(uri)
              .into(imageView);
```

I follow up an example in SVG , but I got an error when I try to run app. The error msg is below:

```ruby
FATAL EXCEPTION: main
Process: com.cu.chulabook, PID: 24035
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
     at com.bumptech.glide.load.engine.EngineKey.hashCode(EngineKey.java:111)
     at java.util.Collections.secondaryHash(Collections.java:3405)
     at java.util.HashMap.remove(HashMap.java:616)
     at com.bumptech.glide.util.LruCache.remove(LruCache.java:135)
     at com.bumptech.glide.load.engine.cache.LruResourceCache.remove(LruResourceCache.java:12)
     at com.bumptech.glide.load.engine.Engine.getEngineResourceFromCache(Engine.java:232)
     at com.bumptech.glide.load.engine.Engine.loadFromCache(Engine.java:222)
     at com.bumptech.glide.load.engine.Engine.load(Engine.java:153)
     at com.bumptech.glide.request.GenericRequest.onSizeReady(GenericRequest.java:449)
     at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.notifyCbs(ViewTarget.java:177)
     at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.checkCurrentDimens(ViewTarget.java:193)
     at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.access$000(ViewTarget.java:161)
     at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer$SizeDeterminerLayoutListener.onPreDraw(ViewTarget.java:292)
     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:948)
     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1974)
     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1065)
     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5901)
     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
     at android.view.Choreographer.doCallbacks(Choreographer.java:580)
     at android.view.Choreographer.doFrame(Choreographer.java:550)
     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
     at android.os.Handler.handleCallback(Handler.java:739)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:211)
     at android.app.ActivityThread.main(ActivityThread.java:5389)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```

**Comment by TWiStErRob** [comment]
See https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/engine/EngineKey.java#L111 `transcoder.getId()` is null. Double-check the implementation.

**Comment by silenus092** [comment]
Oh blimey my big mistake, Many thanks sir , now it work !!
Thank you  for your awesome work

**Comment by mancyzbooni** [comment]
FATAL EXCEPTION: main
                                                                  Process: com.zbooni.staging, PID: 1937
                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
                                                                      at com.bumptech.glide.load.engine.EngineKey.hashCode(EngineKey.java:108)
                                                                      at sun.misc.Hashing.singleWordWangJenkinsHash(Hashing.java:48)
                                                                      at java.util.HashMap.getEntry(HashMap.java:393)
                                                                      at java.util.HashMap.get(HashMap.java:348)
                                                                      at com.bumptech.glide.load.engine.Engine.loadFromActiveResources(Engine.java:204)
                                                                      at com.bumptech.glide.load.engine.Engine.load(Engine.java:162)
                                                                      at com.bumptech.glide.request.GenericRequest.onSizeReady(GenericRequest.java:449)
                                                                      at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.getSize(ViewTarget.java:211)
                                                                      at com.bumptech.glide.request.target.ViewTarget.getSize(ViewTarget.java:100)
                                                                      at com.bumptech.glide.request.GenericRequest.begin(GenericRequest.java:272)
                                                                      at com.bumptech.glide.manager.RequestTracker.resumeRequests(RequestTracker.java:83)
                                                                      at com.bumptech.glide.RequestManager.resumeRequests(RequestManager.java:180)
                                                                      at com.bumptech.glide.RequestManager.onStart(RequestManager.java:203)
                                                                      at com.bumptech.glide.manager.ActivityFragmentLifecycle.onStart(ActivityFragmentLifecycle.java:50)
                                                                      at com.bumptech.glide.manager.SupportRequestManagerFragment.onStart(SupportRequestManagerFragment.java:147)
                                                                      at android.support.v4.app.Fragment.performStart(Fragment.java:2218)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                      at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:241)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6274)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)


i get this crash , 
my implementation is 

 /***
     *
     */
    @BindingAdapter("svgUrl")
    public static void loadSvgImageUrl(@NonNull ImageView view, @Nullable String url){
        GenericRequestBuilder<Uri,InputStream,SVG,PictureDrawable>
                requestBuilder = Glide.with(view.getContext())
                .using(Glide.buildStreamModelLoader(Uri.class, view.getContext()), InputStream.class)
                .from(Uri.class)
                .as(SVG.class)
                .transcode(new SvgDrawableTranscoder(), PictureDrawable.class)
                .sourceEncoder(new StreamEncoder())
                .cacheDecoder(new FileToStreamDecoder<SVG>(new SvgDecoder()))
                .decoder(new SvgDecoder())
               /* .placeholder(R.drawable.svg_image_view_placeholder)
                .error(R.drawable.error_image)*/
                .listener(new SvgSoftwareLayerSetter<Uri>());

        Uri uri = Uri.parse("https://dy6xl8nd39ub2.cloudfront.net/static/fulfillment/images/delivery.svg");
        requestBuilder
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .load(uri)
                .into(view);
    }

i use glide version '3.8.0'  . please help
