### ISSUE TITLE
byte[] buffer memory allocations keeps growing?

### ISSUE THREAD

**Issue by rrahul** [bumptech/glide#960]
This is similar to https://github.com/bumptech/glide/issues/785 , in which GifDecode byte[] buffer memory allocations keeps growing, but not sure, if I have to add it as comment in the same issue, since it is in author-review-pending state. Hence raising as a new issue.

I'm using glide 3.7.0, while scrolling in a list of 30-40 gif images ( I can see lot of byte arrays as mentioned in https://github.com/bumptech/glide/issues/785, accumulated over time)
I am using glide like

```
        Glide.with(myapplicationcontext)
                .load(uri)
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .crossFade()
                .fitCenter()
                .placeholder(R.drawable.placeholder)
                .into(imageView);
```

from my CursorAdapter's `bindView()`.

And my ImageView looks like

```
 <ImageView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:adjustViewBounds="true"
            android:maxHeight="@dimen/max_width"
            android:maxWidth="@dimen/max_width"/>
```

The scrolling is laggy and out of memory error is thrown, after sometime.

![1](https://cloud.githubusercontent.com/assets/1327172/12790131/24ada698-caa1-11e5-898e-679ab331665d.png)
![2](https://cloud.githubusercontent.com/assets/1327172/12790130/24ac8376-caa1-11e5-8e97-36f13c7f6fac.png)
![3](https://cloud.githubusercontent.com/assets/1327172/12790129/24ac3574-caa1-11e5-99f8-fc4f2d5a9a2c.png)

I can see 

```
  java.lang.OutOfMemoryError: Failed to allocate a 863052 byte allocation with 244432 free bytes and 238KB until OOM
            at com.bumptech.glide.gifdecoder.GifDecoder.setData(GifDecoder.java:380)
            at com.bumptech.glide.load.resource.gif.GifDrawable.<init>(GifDrawable.java:92)
            at com.bumptech.glide.load.resource.gif.GifDrawable$GifState.newDrawable(GifDrawable.java:368)
            at com.bumptech.glide.load.resource.drawable.DrawableResource.get(DrawableResource.java:32)
            at com.bumptech.glide.load.resource.drawable.DrawableResource.get(DrawableResource.java:16)
            at com.bumptech.glide.load.engine.EngineResource.get(EngineResource.java:44)
            at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:487)
            at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:158)
            at com.bumptech.glide.load.engine.EngineJob.access$100(EngineJob.java:22)
            at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:202)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:228)
            at android.app.ActivityThread.main(ActivityThread.java:5514)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

    java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Failed to allocate a 2067852 byte allocation with 443680 free bytes and 433KB until OOM
            at java.util.concurrent.FutureTask.report(FutureTask.java:94)
            at java.util.concurrent.FutureTask.get(FutureTask.java:164)
            at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1121)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
            at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 2067852 byte allocation with 443680 free bytes and 433KB until OOM
            at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
            at android.graphics.Bitmap.nativeCreate(Native Method)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
            at com.bumptech.glide.load.resource.bitmap.TransformationUtils.fitCenter(TransformationUtils.java:112)
            at com.bumptech.glide.load.resource.bitmap.FitCenter.transform(FitCenter.java:24)
            at com.bumptech.glide.load.resource.bitmap.BitmapTransformation.transform(BitmapTransformation.java:54)
            at com.bumptech.glide.load.engine.DecodeJob.transform(DecodeJob.java:236)
            at com.bumptech.glide.load.engine.DecodeJob.transformEncodeAndTranscode(DecodeJob.java:139)
            at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:129)
            at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
            at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
            at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
            at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
```

 getting printed a lot of times, when I run into OOM

I tried clearing memory cache and disk cache on onTrimMemory() manually (although I found it mentioned  in some other issues  it may not be needed). Also I tried  

```
   case SCROLL_STATE_IDLE:
                    Glide.with(view.getContext()).resumeRequests();
                    break;
                case SCROLL_STATE_TOUCH_SCROLL:
                case SCROLL_STATE_FLING:
                    Glide.with(view.getContext()).pauseRequests();
                    break;

```

on scroll state changed. But still its running to OOM

**Comment by TWiStErRob** [comment]
The other issue is not in any state, each "added" entry has a corresponding "removed" as well. The current state is always what you see in the right column. But it doesn't matter because it's better to have each issue separate as it may turn out it's not the same and investigation can take a lot of space. Thank you for the detailed report. I'll try to reproduce this over the weekend, if you can create a small repro app it would be even better.

**Comment by TWiStErRob** [comment]
I think your selected byte arrays are the active ones, but may be not. When looking for leaks always do a path to GC root query to see what is keeping it in memory.

**Comment by rrahul** [comment]
One more point to add. I was trying with available apis and I found a work around with setPriority() method, and when I set it to Low, it seems to avoid OOM.  But I'm not sure if this cause some other issues like images failing to load for ever or something.(i'll test it) What exactly this priority do, will it cancel the loading if the device is running out of memory or will it just queue the request without taking any action till GC is done and system regain some memory?

Regarding the heap screen shots, I will try to upload another set during the day.

**Comment by rrahul** [comment]
With this priority(), still first time scrolling of list takes a lot of time, and sometimes, oom is thrown. I just had a look at heap dump with mat.. the leak suspects were

21 instances of "com.bumptech.glide.load.engine.EngineJob", loaded by "dalvik.system.PathClassLoader @ 0x12d13680" occupy 49,375,560 (43.15%) bytes.

and 

22 instances of "com.bumptech.glide.request.GenericRequest", loaded by "dalvik.system.PathClassLoader @ 0x12d13680" occupy 20,707,432 (18.10%) bytes.

I'll upload screenshots..

**Comment by rrahul** [comment]
![1](https://cloud.githubusercontent.com/assets/1327172/12822220/47c132b4-cb67-11e5-8cf8-a30f05feb463.png)
![2](https://cloud.githubusercontent.com/assets/1327172/12822221/47da639c-cb67-11e5-8e83-4df3503126a3.png)
![3](https://cloud.githubusercontent.com/assets/1327172/12822222/47f02786-cb67-11e5-8e96-216ccf77cfca.png)
![5](https://cloud.githubusercontent.com/assets/1327172/12822223/47f1c1fe-cb67-11e5-988d-91fb82bd0a37.png)

**Comment by howyongjun** [comment]
Any updates on this issue?
I tried MAT & it show the same leak suspects as well.

**Comment by ronenfe** [comment]
how can i see this call stuck in android studio? seems like many libraries are poorly written.
