### ISSUE TITLE
 java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity

### ISSUE THREAD

**Issue by vijaykd** [bumptech/glide#975]
I am getting this issue:

```ruby
java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
  at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134)
  at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:102)
  at com.bumptech.glide.Glide.with(Glide.java:644)
  at com.pk.main.DetailActivity$6.onSuccess(DetailActivity.java:924)
  at com.loopj.android.http.JsonHttpResponseHandler$1$1.run(JsonHttpResponseHandler.java:151)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5417)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
even after I give

```java
@Override
protected void onDestroy() 
{
  super.onDestroy();
  Glide.clear(imageview);
  if (client != null) 
  {
    Log.e("value !null","coming");
    client.cancelRequests(DetailActivity.this, true);    
   }
}
```
 
I am retrieving value using AsyncHttpClient onSuccess: I have the following:
                           
```java
Glide.with(DetailActivity.this)
     .load(images[0])
     .diskCacheStrategy(DiskCacheStrategy.SOURCE)
     .fitCenter()
     .crossFade()
     .into(imageview);
```

I know there is an issue that was closed - You have adviced to cancel the Async request. I have done it and still have the same issue.

**Comment by TWiStErRob** [comment]
I'm not sure how you client behaves, but it's possible that requests complete even if they were cancelled. It looks like you're getting the `onSuccess` on the main thread, which probably means that the completion posted a runnable to the main loop before you had a chance to cancel. For this reason you still need to check if the activity is destroyed or not (or if the request was cancelled that you got a result for) when you process the successful response.

**Comment by TWiStErRob** [comment]
Did you manage to make it work?

**Comment by TWiStErRob** [comment]
See #803.

**Comment by rajileshthayath** [comment]
@Override
    public void destroy(View viewHolder) {
       
       if (mContext != null && !mContext.isFinishing()) {
            GlideApp.with(viewHolder.getRootView().getContext()).clear(view);
        }
    }

!mContext.isFinishing() this solved my crash.

**Comment by meikaiss** [comment]
when you load image in Activity, please check like this. If the activity isDestroyed, stop load image by Glide， else load image by Glide

@targetapi(Build.VERSION_CODES.JELLY_BEAN_MR1)
private static boolean isActivityDestroyed(Activity activity) {
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1
&& activity != null && activity.isDestroyed()) {
return true;
}
return false;
}
