### ISSUE TITLE
Glide. After finishing activity with big placeholder app crashes

### ISSUE THREAD

**Issue by idyuzheva** [bumptech/glide#985]
I load image like this:
```
 glide.load(getUrlForPath(originalPath))
                .asBitmap()
                .centerCrop()
                .fitCenter()
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .placeholder(R.drawable.ic_no_image)
                .into(imageView);
```

 The first placeholder was 80x80 and everything seemed to be ok. When I changed placeholder with size 216x296, app started crashing after call `finish();` for activity.

    java.lang.RuntimeException: An error occurred while executing doInBackground()
            at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:142)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NullPointerException: Function passed to this loader should never return null.
            at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
            at com.getbase.android.db.loaders.ComposedCursorLoader.loadInBackground(ComposedCursorLoader.java:61)
            at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:296)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:54)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:42)

**Comment by TWiStErRob** [comment]
The stack trace is totally unrelated to Glide, your async task probably finishes after the activity has been destroyed or similar. Try to replace the above Glide line with `imageView.setImageDrawable(R.drawable.ic_no_image)` to see if you can reproduce.

Also centerCrop and fitCenter overwrite each other, you have to choose one. It's not an issue, because the last one wins, it just misleading for the reader of the code.

**Comment by idyuzheva** [comment]
Thahk you! Actually it was my fault
