### ISSUE TITLE
images not loading from server

### ISSUE THREAD

**Issue by saeed-zh** [bumptech/glide#986]
Hi,

I have asp.net server and android clients, Until now, my server was on localhost and every things was fine. today I published the server on a host and change application base URL to host's URL. but I have one problem. my other information and data is shown in app but images. I have no idea what's the reason?
previous image URLs is something like this

http://10.0.2.2:6815/function/getImage?id=1     // localhost's URL, all things OK

and the new one is
http://nasimshop.com.sahel.mrsservers.com//function/getImage?id=1 // host' URL, images not loading

As you see, the domain name is changed but images not loading in my application. why?
also when I enter the new URL in browsers, the image has shown. so I think there is a problem with glide.

note: for security reason some part of both URLs is changed. actually the domain part is enough to answer.

**Comment by saeed-zh** [comment]
application can load this arbitary URL:
https://www.hallaminternet.com/assets/URL-tagging-image.png

comparing these URL seems give the reason.
when domain name has sub domain it seems does not work.

**Comment by TWiStErRob** [comment]
You have a double-slash `//` before function. If that's just a typo in this issue, then check the error message why it doesn't load: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener

**Comment by saeed-zh** [comment]
oh sorry,  double-slash is just a typo

**Comment by saeed-zh** [comment]
I have problem with learning usage of debugging

**Comment by saeed-zh** [comment]
can you give a simple usage?

**Comment by TWiStErRob** [comment]
`Glide.with(...).load(...).....listener(...).into(...)`

**Comment by saeed-zh** [comment]
02-18 17:36:49.815    7745-7745/com.kingbabak.digitalmarket D/GLIDE﹕ onException(java.net.SocketTimeoutException, http://nasimshop.com.sahel.mrsservers.com/Services/GetProductPicture?id=1, Target for: android.widget.ImageView{42451020 V.ED.... ......ID 0,0-243,450 #7f0e009d app:id/leftProductImage}, true)
    java.net.SocketTimeoutException
            at java.net.PlainSocketImpl.read(PlainSocketImpl.java:495)
            at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
            at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
            at java.io.InputStream.read(InputStream.java:163)
            at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
            at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
            at libcore.io.Streams.readAsciiLine(Streams.java:201)
            at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:573)
            at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:821)
            at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:293)
            at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:505)
            at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:76)
            at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:44)
            at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:20)
            at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:70)
            at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:53)
            at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
            at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
            at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
            at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
            at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:838)
            at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
02-18 17:37:10.610    7745-7745/com.kingbabak.digitalmarket D/GLIDE﹕ onException(java.net.SocketTimeoutException, http://nasimshop.com.sahel.mrsservers.com/Services/GetProductPicture?id=1, Target for: android.widget.ImageView{42451020 V.ED.... ........ 0,0-243,450 #7f0e009d app:id/leftProductImage}, true)
    java.net.SocketTimeoutException
            at java.net.PlainSocketImpl.read(PlainSocketImpl.java:495)
            at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
            at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
            at java.io.InputStream.read(InputStream.java:163)
            at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
            at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
            at libcore.io.Streams.readAsciiLine(Streams.java:201)
            at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:573)
            at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:821)
            at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:293)
            at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:505)
            at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:76)
            at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:44)
            at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:20)
            at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:70)
            at com.bumptech.glide.load.model.ImageVideoModelLoader$ImageVideoFetcher.loadData(ImageVideoModelLoader.java:53)
            at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:170)
            at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
            at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
            at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
            at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:838)
            at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)

**Comment by TWiStErRob** [comment]
So, it's clearly a server side issue, for some reason it's not responding to your request.
Does it work in the browser on the phone as opposed to browser on the computer?
To increase timeout: https://github.com/bumptech/glide/issues/432

**Comment by saeed-zh** [comment]
the image is showing in both computer and mobile browser, i don't think there is any problem in server side

**Comment by saeed-zh** [comment]
because it is shown imediately

**Comment by TWiStErRob** [comment]
Can you give an example? If you want to keep it private you can mail it to me.

**Comment by saeed-zh** [comment]
it seems I haven't any way. :D 

nasimshop.com.sahel.mrsservers.com/Services/GetProductPicture?id=1

is one example that works in browsers

**Comment by saeed-zh** [comment]
are you want code example?

**Comment by TWiStErRob** [comment]
So first I forgot to add logging, so I got:

> D/skia: --- SkImageDecoder::Factory returned null

then with added logging I got the same exception as you (timeout).

With `.diskCacheStrategy(SOURCE).listener` I got:

> .onException(null, <url>, Target for: ImageView{...}, true)

Then I enabled [the big guns](https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#debugging-workflow) and got:

```
V/DecodeJob: Decoded source from cache in 4.333496, key: EngineKey{...}
V/DecodeJob: Transformed resource from source in 0.030518, key: EngineKey{...}
V/DecodeJob: Transcoded transformed from source in 0.030518, key: EngineKey{...}
V/DecodeJob: Fetched data in 2964.4470229999997, key: EngineKey{...}
V/DecodeJob: Wrote source to cache in 10791.259766, key: EngineKey{...}
V/DecodeJob: Transformed resource from source in 0.122071, key: EngineKey{...}
V/DecodeJob: Transcoded transformed from source in 0.091553, key: EngineKey{...}
D/GenericRequest: load failed
D/GLIDE: .onException(null, <url>, Target for: ImageView{...}, true)
```

Which reads as:
 * 4ms to query SOURCE cache and fail (cache miss) -> go for the network
 * 3 seconds to connect to the http endpoint, the default timeout 2500 without integration library so this was lucky to return
 * 10 seconds to fully read the returned stream and write to cache
 * which apparently failed because there's a missing "Decoded source from cache" log line
 * "Transformed resource" and "Transcoded transformed" is just going through the motions with a `null` object

If you get a timeout when stack contains `HttpUrlFetcher.loadData` it means that the connection timed out. If you get a timeout when stack contains `Downsampler.decode` it means that the read timed out. The corresponding lines from `HttpUrlFetcher`:

```java
urlConnection.setConnectTimeout(2500);
urlConnection.setReadTimeout(2500);
```

With `.diskCacheStrategy(SOURCE)` the cache journal contains traces that the file began to write but never finished.

To sum up: this is a server side issue. It's just too slow to respond to either "are you there, do you have content for me?" or "gimme some more bytes" requests. The result is really intermittent, sometimes it's fast some times it slow. I also managed to load the image a few times, when I was lucky to get a fast response; but the I also managed to get the opposite results in Chrome on my desktop:
![image](https://cloud.githubusercontent.com/assets/2906988/13158399/06c61e60-d68d-11e5-8ce5-5c171d9b45c9.png)
![image](https://cloud.githubusercontent.com/assets/2906988/13158538/a6fc46e8-d68d-11e5-99c7-975d97b358ca.png)
![image](https://cloud.githubusercontent.com/assets/2906988/13158569/ce7b441c-d68d-11e5-8c54-57073f89492f.png)

Explanation here: https://developers.google.com/web/tools/chrome-devtools/profile/network-performance/resource-loading#resource-network-timing
Given it's a 180k image, these timings are really bad and the browsers are much more forgiving, they only fail when they really couldn't get the data, sometimes after 3-5-10 minutes, but Glide cannot afford this, because there can be only 1-4 in-flight requests at a time by default, so one bad image can stall the queue.

**Comment by saeed-zh** [comment]
excuse me, but I didn't understand any thing

**Comment by saeed-zh** [comment]
are you test my URL?

**Comment by TWiStErRob** [comment]
Yes, that Assassin's Creed or something image. There's nothing Glide can do about bad network connections or slow servers. All you can do is increase the timeout to be more tolerant to these, or get a better content server. Mind you that I'm in Central Europe so you mileage may vary.

**Comment by saeed-zh** [comment]
The host server is in my country. and as I said, browsers shows the image very fast. I haven't any idea why this happened?

**Comment by saeed-zh** [comment]
are you test the URL using browser? or glide? are you increase timeout duration?

**Comment by TWiStErRob** [comment]
Browser: always displayed, took 5-30 seconds
Glide: timeout 80% of the time, when loaded it was at least 4 seconds.
I didn't increase timeout, but it's clear that it would work then, because of the timeout exceptions and the 2.5 second builtin limit.

**Comment by saeed-zh** [comment]
so H have not any way but increase the time, please give me a simple example how to do it. txn

**Comment by saeed-zh** [comment]
@TWiStErRob

**Comment by TWiStErRob** [comment]
Show some effort, please; #432 (the first result for "glide increase timeout" search) should have enough info, here's the code:
```gradle
compile 'com.github.bumptech.glide:okhttp-integration:1.4.0'
compile 'com.squareup.okhttp:okhttp:2.2.0'
```
```xml
<meta-data
    android:name="com.kingbabak.digitalmarket.glide.Setup"
    android:value="GlideModule" />
```
```java
package com.kingbabak.digitalmarket.glide;
public class Setup implements GlideModule {
	@Override public void applyOptions(Context context, GlideBuilder builder) {
	}
	@Override public void registerComponents(Context context, Glide glide) {
		OkHttpClient client = new OkHttpClient();
		client.setConnectTimeout(15, TimeUnit.SECONDS);
		client.setReadTimeout(15, TimeUnit.SECONDS);
		glide.register(GlideUrl.class, InputStream.class, new OkHttpUrlLoader.Factory(client));
	}
}
```

**Comment by saeed-zh** [comment]
I do not use okhttp. I'm using the Apache http library. That's why I could not use this solution. The library really is very wide and has plenty of features. Learn to use it takes time. Is okhttp the default of glide?
Is there another solution? And this solution should I use?

**Comment by TWiStErRob** [comment]
There's no learning courve for OkHttp, because it is all handled by `OkHttpUrlLoader`: you just add this code and your app will use OkHttp. Obviously if you can't/don't want to add a new dependency you'll need a different way. To change the timeout with the default networking layer, copy `HttpUrlFetcher` and `HttpUrlGlideUrlLoader` classes to a package inside your project and modify the source code to increase timeout. Then register it like above, but use `new HttpUrlGlideUrlLoader.Factory()` instead.
