### ISSUE TITLE
Image first time not displayed when using onResourceReady

### ISSUE THREAD

**Issue by valibran** [bumptech/glide#994]
This code sometimes works and sometimes it doesn't work(the image is not displayed), but only when a certain image uri is called for the first time:
```java
Glide.with(context).load(uri).fitCenter().centerCrop()
    .into(new GlideDrawableImageViewTarget(imageView) {
        @Override
        public void onResourceReady(GlideDrawable drawable, GlideAnimation anim) {
            super.onResourceReady(drawable, anim);
            //some other action
        }
    });
```

This code works always(the image is displayed):
```java
Glide.with(context).load(uri).fitCenter().centerCrop()
    .into(imageView);
```

It seems there is a random caching issue when using the code that can also do a task after the resource is loaded.

Tested with `'com.github.bumptech.glide:glide:3.7.0'`.

**Comment by TWiStErRob** [comment]
`.fitCenter().centerCrop()` contradict each other, use only one of them.
Try using `.listener()` to do something when the resource is loaded. Note that currently your "other action" is run **after** `iv.setImageDrawable`, while the `.listener()` is run **before**.

There shouldn't be any difference between the two `into` calls as by default `GlideDrawableImageViewTarget` is created, but without concrete reproducible case we can't do much. Can you share a working and a non-working URI?

Any chance you're using `CircleImageView`?

**Comment by valibran** [comment]
I removed both `.fitCenter()` and `.centerCrop()`but I have the same issue.

```
Glide.with(cell.contentView.getContext())
                    .load(contact.getPhotoUri())
                    .into(new GlideDrawableImageViewTarget(cell.contactImageView) {
                        @Override
                        public void onResourceReady(GlideDrawable drawable, GlideAnimation anim) {
                            super.onResourceReady(drawable, anim);
                            Log.d(TAG, "Sometimes the image is not loaded and this text is not displayed");
                        }
                    });
```

It's pretty simple to replicate: have a list with say 10 image URIs and a button that calls the code above for a random URI.
Sometimes the image is displayed and sometimes not. 
When repeating the experiment clear that data of the app, close and restart is not enough as once the code is called for a URI it will always work for it.

**Comment by valibran** [comment]
From what I have noticed the issue happens for higher quality images. Small images are usually loaded.

**Comment by TWiStErRob** [comment]
Hmm, those higher quality images may be too large and a timeout happens, try to add a listener to log the error: https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling#requestlistener
If `onResourceReady` is not called it's either in progress of loading or called `onLoadFailed` or `onLoadCleared` if it was cancelled.

**Comment by valibran** [comment]
Logs result for 1 fail and 3 that worked.

```
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest: load failed
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest: java.lang.IllegalStateException: Can't call reconfigure() on a recycled bitmap
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest:     at android.graphics.Bitmap.checkRecycled(Bitmap.java:352)
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest:     at android.graphics.Bitmap.reconfigure(Bitmap.java:224)
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest:     at com.bumptech.glide.load.engine.bitmap_recycle.SizeConfigStrategy.get(SizeConfigStrategy.java:72)
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest:     at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.getDirty(LruBitmapPool.java:130)
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest:     at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.get(LruBitmapPool.java:114)
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest:     at com.bumptech.glide.load.resource.bitmap.CenterCrop.transform(CenterCrop.java:28)
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest:     at com.bumptech.glide.load.resource.bitmap.BitmapTransformation.transform(BitmapTransformation.java:54)
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest:     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperTransformation.transform(GifBitmapWrapperTransformation.java:34)
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest:     at com.bumptech.glide.load.engine.DecodeJob.transform(DecodeJob.java:236)
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest:     at com.bumptech.glide.load.engine.DecodeJob.transformEncodeAndTranscode(DecodeJob.java:139)
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:129)
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest:     at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest:     at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest:     at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest:     at java.lang.Thread.run(Thread.java:818)
02-23 19:34:45.901 19799-19799/ro.example.alpha D/GenericRequest:     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE: onException(java.lang.IllegalStateException: Can't call reconfigure() on a recycled bitmap, content://com.android.contacts/contacts/653/photo, Target for: android.support.v7.widget.AppCompatImageView{234fa2ad V.ED.... ........ 0,0-720,720 #7f0e00a7 app:id/contact_image}, true)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE: java.lang.IllegalStateException: Can't call reconfigure() on a recycled bitmap
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE:     at android.graphics.Bitmap.checkRecycled(Bitmap.java:352)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE:     at android.graphics.Bitmap.reconfigure(Bitmap.java:224)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE:     at com.bumptech.glide.load.engine.bitmap_recycle.SizeConfigStrategy.get(SizeConfigStrategy.java:72)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE:     at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.getDirty(LruBitmapPool.java:130)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE:     at com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool.get(LruBitmapPool.java:114)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE:     at com.bumptech.glide.load.resource.bitmap.CenterCrop.transform(CenterCrop.java:28)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE:     at com.bumptech.glide.load.resource.bitmap.BitmapTransformation.transform(BitmapTransformation.java:54)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE:     at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperTransformation.transform(GifBitmapWrapperTransformation.java:34)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE:     at com.bumptech.glide.load.engine.DecodeJob.transform(DecodeJob.java:236)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE:     at com.bumptech.glide.load.engine.DecodeJob.transformEncodeAndTranscode(DecodeJob.java:139)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:129)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE:     at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE:     at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE:     at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE:     at java.lang.Thread.run(Thread.java:818)
02-23 19:34:45.902 19799-19799/ro.example.alpha D/GLIDE:     at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
02-23 19:34:45.936 19799-19963/ro.example.alpha V/RenderScript: Application requested CPU execution
02-23 19:34:45.943 19799-19963/ro.example.alpha V/RenderScript: 0x9d368a00 Launching thread(s), CPUs 4
02-23 19:34:45.971 19799-19799/ro.example.alpha D/GLIDE: onResourceReady(com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable@b4729e2, content://com.android.contacts/display_photo/350, Target for: android.support.v7.widget.AppCompatImageView{2dbe173 V.ED.... ........ 0,0-360,360 #7f0e00a7 app:id/contact_image}, false, true)
02-23 19:34:46.015 19799-19799/ro.example.alpha D/GLIDE: onResourceReady(com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable@1670bca9, content://com.android.contacts/display_photo/9, Target for: android.support.v7.widget.AppCompatImageView{3b32022e V.ED.... ........ 0,0-720,720 #7f0e00a7 app:id/contact_image}, false, true)
02-23 19:34:46.058 19799-19799/ro.example.alpha D/GLIDE: onResourceReady(com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable@2dcaa75c, content://com.android.contacts/display_photo/357, Target for: android.support.v7.widget.AppCompatImageView{b6f7a65 V.ED.... ........ 0,0-720,720 #7f0e00a7 app:id/contact_image}, false, true)
```

This is the code
```
Glide.with(cell.contentView.getContext())
                    .load(contact.getPhotoUri())
                    .centerCrop()
                    .listener(new RequestListener<String, GlideDrawable>() {
                        @Override
                        public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                            android.util.Log.d("GLIDE", String.format(Locale.ROOT,
                                    "onException(%s, %s, %s, %s)", e, model, target, isFirstResource), e);
                            return false;
                        }

                        @Override
                        public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                            android.util.Log.d("GLIDE", String.format(Locale.ROOT,
                                    "onResourceReady(%s, %s, %s, %s, %s)", resource, model, target, isFromMemoryCache, isFirstResource));
                            return false;
                        }
                    })
                    .into(cell.contactImageView);
```

It seems it also fails even when using a listener.

**Comment by TWiStErRob** [comment]
Ok, so for this exception we need to look at the application as a whole. Because it means that there's a Bitmap in the pool that was already recycled. Glide doesn't do it by itself. Do you have any custom transformations, or call `ImageView.getImageDrawable`, or capture any `onResourceReady(Bitmap|Drawable resource, ...)` objects?

**Comment by valibran** [comment]
I don't do anything specific(I have expanded the code in the last comment), but this problem occurs only sometimes and only once for a specific image URI, then I think something gets cached in glide and it works always(for that URI).

**Comment by TWiStErRob** [comment]
It happens only once, because after that it is loaded from the memory cache and there's no need to touch the bitmap pool (when decoding/transforming the image). If you add `.skipMemoryCache(true)` it may happen more often. My questions were targeting the whole app, any load that may happen before this happens from application startup is a suspect. Can you make small repro app on GitHub or otherwise share the app? (upload to Drive or mail it to me).

**Comment by valibran** [comment]
You were right with your assumptions.
After a deeper inspection it turned out that indeed I had a custom (circle) transformation that was causing the problem just that this was into a different location. Ironically that image was always displaying fine but was propagating the error to the glide code portion that had no custom transformation. 
As a reference I have replaced the custom circle transformation code with `RoundedBitmapDrawable`
```
Glide.with(activity)
                .load(photoUri)
                .asBitmap()
                .centerCrop()
                .into(new BitmapImageViewTarget(imageView) {
                    @Override
                    protected void setResource(Bitmap resource) {
                        RoundedBitmapDrawable circularBitmapDrawable =
                                RoundedBitmapDrawableFactory.create(activity.getResources(), resource);
                        circularBitmapDrawable.setCircular(true);
                        imageView.setImageDrawable(circularBitmapDrawable);
                    }
                });
```

Thanks for your prompt help.

**Comment by TWiStErRob** [comment]
Good to hear that.

You can still use Transformations ([this](https://github.com/wasabeef/glide-transformations) or [this](http://stackoverflow.com/a/25806229/253468)) as they have benefits over the drawable solution: the circle-cropped image is saved into the RESULT cache which means that the GPU doesn't have to do that transformation on every draw. Since it is saved with some transparent pixels you may even save space because the area outside the circle can be compressed well. Transformations also work for GIFs and don't require custom target implementations (this may be important if you want to do something else on that load too which wouldn't work with that target).

**Comment by Mouadabdelghafouraitali** [comment]
@TWiStErRob  hi , i find your code in github i have a problems with android 6.0.1 image doesn't save 
i think I think the problem is related with permission  

> `
                new AsyncTask<FutureTarget<Bitmap>, Void, Bitmap>() {
                    @Override protected Bitmap doInBackground(FutureTarget<Bitmap>... params) {
                        try {
                            return params[0].get();
                            // get needs to be called on background thread
                        } catch (Exception ex) {
                            return null;
                        }
                    }
                    @Override protected void onPostExecute(Bitmap bitmap) {
                        if(bitmap == null) return;
                        MediaStore.Images.Media.insertImage(getContentResolver(), bitmap, "Art_"+System.currentTimeMillis(), "Beschrijving");
                    }
                }.execute(Glide.with(getApplicationContext()).load(url).asBitmap().into(width, height));
                // into needs to be called on main thread
            }
`
